### ISSUE TITLE
Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.

### ISSUE THREAD

**Issue by kamaldlk** [adazzle/react-data-grid#1001]
Hi @jpdriver,
I'm continuously getting below error whenever I focus or select cell 
proxyConsole.js:68 Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.

Here is the reproducible code sample
[https://codesandbox.io/s/3z3lq9zn1](here)

I am using React 16 with react-data-grid latest version. 

Thanks 
Kamal K

**Comment by amanmahajan7** [comment]
Duplicate issue, closing in favor of #978
btw, cannot access codesandbox example

**Comment by kamaldlk** [comment]
@amanmahajan7 

please check : https://codesandbox.io/s/3z3lq9zn1

**Comment by kamaldlk** [comment]
![screen shot 2017-10-31 at 7 47 07 am](https://user-images.githubusercontent.com/9652523/32204533-d1ad16e0-be0f-11e7-9934-91c81717c017.png)
