### ISSUE TITLE
Editable examples are broken

### ISSUE THREAD

**Issue by amanmahajan7** [adazzle/react-data-grid#1002]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [x] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [x] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details
React scripts on the example page was recently updated to version 15.6.1 in #980. This PR removed the deprecated `react-addons-update` addon which the editable examples rely on
![image](https://user-images.githubusercontent.com/1452717/32198032-7bd257f6-bd94-11e7-9fa0-bc14a86c311c.png)

```
Please include:
- What the current behavior is
All editable examples are broken

- What the desired behvaior is
Editable examples work as expected

- (If Bug) Steps to reproduce the issue
Navigate to http://adazzle.github.io/react-data-grid/examples.html#/editable and edit any cell. Check the console for error messages

- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by malonecj** [comment]
Fixed with https://github.com/adazzle/react-data-grid/pull/1003
