### ISSUE TITLE
Unintended sorting after select

### ISSUE THREAD

**Issue by GenoD** [adazzle/react-data-grid#1007]
### Which version of React JS are you using?

✅ Officially supported ✅
- [ x] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [x ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

Please include:
- What the current behavior is
Unintended sorting of grid occurs after checkbox select while a "SortDirection" is applied. Seems to only apply to groups with matching keys values for the sorted column. 

    
           
![sorting bug](https://user-images.githubusercontent.com/5068500/32355686-6f6b86d0-bfed-11e7-994b-8eccb8d973bd.gif)

E.x "A&F" are switching places after each click. 

- What the desired behvaior is
Grid should not change order of rows with matching key values in sorted column.

- (If Bug) Steps to reproduce the issue
Refer to GIF
(Although seems to only occur after selecting a row. Deselecting does not modify row ordering)

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™

Relavant code:
```
<ReactDataGrid
       rowKey='PurchaseOrder_id'
       enableCellSelect={true}
       onGridSort={handleGridSort}
       columns={columns}
       rowGetter={rowGetter}
       rowsCount={getSize() }
       enableRowSelect='single'
       rowSelection={{
         showCheckbox: true,
         onRowsSelected: onRowsSelected,
         onRowsDeselected: onRowsDeselected,
         selectBy: {
         isSelectedKey: 'isSelected'
      }
    }}
    onRowClick={onRowClick}
    onCellSelected={onCellSelected}
/>


const onRowsSelected = (rows) => {
    let newRows = getRows();
    let selectedRows = [newRows[rows[0].rowIdx]];
    newRows.map(r => {
      r.isSelected = false;
    });
    rows.map(r => {
      newRows[r.rowIdx].isSelected = true;
    });
    this.setState({ rows: newRows, selectedRows: selectedRows });
}

const onRowsDeselected = (rows) => {
    let rowIndexes = rows.map(r => r.rowIdx);
    let newRows = [...this.state.rows];
    rows.map (r => {
      newRows[r.rowIdx].isSelected = false;
    });
    this.setState({ rows: newRows, selectedRows: [] });
}

const handleGridSort = (sortColumn, sortDirection) => {
    var state = Object.assign({}, this.state, { sortColumn: sortColumn, sortDirection: sortDirection });
    this.setState(state);
}

const getRows = () => {
    return Data.Selectors.getRows(this.state);
}

const getSize = () => {
    return getRows().length;
}

const rowGetter = rowIdx => {
    var rows = getRows();
    return rows[rowIdx];
}

const columns = [
  {
      key: 'Num',
      name: <Translate value="po_no"/>,
      resizable: true,
      sortable: true,
      width: 100,
      filterable: true
  },
  {
      key: 'VendorID',
      name: <Translate value="vendor_no"/>,
      resizable: true,
      sortable: true,
      width: 100,
      filterable: true
  },

**Comment by kamaldlk** [comment]
Hi ,
check below link u will get idea.
u need to set   static defaultProps = { rowKey: 'EmailId' };
https://codesandbox.io/s/3z3lq9zn1

**Comment by GenoD** [comment]
@kamaldlk Sorry I did not include that line earlier. I have checked and the Product_id's of the rows are unique, yet the rows keep moving

**Comment by kamaldlk** [comment]
May I know have u completed batch edit and delete
