### ISSUE TITLE
How to implement delay in filter application for server side requests

### ISSUE THREAD

**Issue by daredevil82** [adazzle/react-data-grid#1010]
Because I'm working with a data set that is between 6000-25000 rows in length, I've modified `rowGetter`, `onGridSort` and `onAddFilter` props to handle asynchronous data requests and reset the row state on response.

My current issue has to do with the fact the handler for `onAddFilter` executes on each change event that is fired by React, and that works fine when the dataset is local to the browser.  However, with my implementation, this means that I have multiple server requests being fired off during the typing of a filter term.  Because this is all asynchronous, there's no guarantee that when the last letter is entered its corresponding response will be the dataset visible in the component.

Is there a way to set a delay after the last filter onChange event before firing off a new one?

**Comment by daredevil82** [comment]
I've implemented this functionality with the `onAddFilter` handler:

```
this.filterTimeout = 0; // in component constructor

handleFilterChange(filter) { 
    if (this.filterTimeout)
       clearTimeout(this.filterTimeout)

    this.filterTimeout = setTimeout(() => {
       // execute server request and update this.state
    }, 300);
}
```

That said, I really dislike relying on timers for blocking anything asynchronous.  Is there a better method than this?

**Comment by malonecj** [comment]
Hi @daredevil82 
One thing that you could do is implement your own custom filter renderer, similar to the example [here](https://github.com/adazzle/react-data-grid/blob/dc2ad1e809af0566f6a248cb5fcc72e25bac5af4/packages/react-data-grid-examples/src/scripts/example22-custom-filters.js#L15).

Your custom filter component should look similar to the [FilterableHeaderCell](https://github.com/adazzle/react-data-grid/blob/dc2ad1e809af0566f6a248cb5fcc72e25bac5af4/packages/react-data-grid/src/cells/headerCells/FilterableHeaderCell.js) but use use something like [lodash.debounce](https://lodash.com/docs/4.17.4#debounce) to throttle the input.
