### ISSUE TITLE
TypeError: Cannot read property 'Component' of undefined

### ISSUE THREAD

**Issue by phongmanh** [adazzle/react-data-grid#1011]
I'm trying using react-data-grid. When i'm run my project i get an error:

> TypeError: Cannot read property 'Component' of undefined

This error occur in ../node_modules/react-data-grid-addons/dist/react-data-grid-addons.js:9469
`	  return RowsContainer;
	}(_react2['default'].Component);`
How to resolve this ?

**Comment by amanmahajan7** [comment]
@phongmanh can you provide mode details around how to reproduce this issue? Also, please keep the issue template as it is designed to provide useful information to debug an issue. Thanks

**Comment by amanmahajan7** [comment]
Closing as no further details were provided
