### ISSUE TITLE
Grid display is messed up after maximizing a browser window (resizable columns grid)

### ISSUE THREAD

**Issue by yurigenin** [adazzle/react-data-grid#1013]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [X] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [X] v15.5.x
- [X] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [X] Edge
- [X] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [X] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

Go to the resizable columns example. Make a browser window half width of the screen. Resize the 
Title column to take half of the grid's width. Resize the Priority column to take another half. Maximize the browser window by clicking the Maximize button of the browser window. Observe that the rest of the columns are not rendered correctly and resizing the rest of the columns does not rerender the grid either.
```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```
![image](https://user-images.githubusercontent.com/11202960/32630693-3453e94a-c563-11e7-94cb-6274859e4176.png)

**Comment by chrismiceli** [comment]
Looks similar to https://github.com/adazzle/react-data-grid/issues/584, but can't be sure they are the same.
