### ISSUE TITLE
cellClick can not be forced from react data grid component

### ISSUE THREAD

**Issue by Aldizh** [adazzle/react-data-grid#1016]
- Have you already searched for similar issues? Please help us out and double-check first!
_Yes there was one issue that came close to this which suggested that we have our own implementation of onRowClick handler. But this is more specific to cellClick event_

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [x] v15.4.2

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details
First i would like the thank you guys for the great work you have done.
I was wondering if there is a way to force a click event on the cell via focus/cell select instead of a mouse click. This could be very helpful for input elements such as date picker or dropdown list.
```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```
![dropdown](https://user-images.githubusercontent.com/2282120/32672254-fbccb55e-c60f-11e7-94ae-215682c43aa4.png)
<img width="434" alt="focus" src="https://user-images.githubusercontent.com/2282120/32672496-e4361664-c610-11e7-8eed-43d41661aa1d.png">

Currently when you focus on a cell that has a datepicker as an input element nothing happens until you actually click on it.
Would be nice if we can actually trigger the datepicker/dialog expansion on focus.
This could be very practical if a user wants to tab through the whole table and use keyboard only to enter data as quickly and easily as possible.
I have tried two approaches so far but no success.
1. Use enableCellSelect flag and onCellSelected but the problem here is that we can only access the cell coordinates not the event.

        handleCellFocus = (args) => {
             this.refs.reactDataGrid.openCellEditor(args.rowIdx, args.idx)
             // Here i need a way to force the cellClick event
         }
        

        <ReactDataGrid
              ref={'reactDataGrid'}
              enableCellSelect
              onCellSelected={(args) => { this.handleCellFocus(args) }}
              ...
        

2. Use the formatter itself and go up the DOM tree until we hit the 'react-Cell-Grid' div and force a click event there.
      `this.datePicker.refs.input.getInputNode().parentNode.parentNode.parentNode.click()`

**Comment by malonecj** [comment]
This is currently not possible. The default navigation mode is that you need to click mouse or activate a cell using the keyboard. We would accept a pull request for this feature but it is not something that we are going to implement ourselves in the near future, thanks.

**Comment by Aldizh** [comment]
Thanks @malonecj  i will submit a PR for this feature once i have the test cases ready.
