### ISSUE TITLE
Context menu not working please give me suggestion 

### ISSUE THREAD

**Issue by kamaldlk** [adazzle/react-data-grid#1019]
react-data-grid-addons.js:25025 Uncaught TypeError: Cannot read property 'contains' of undefined
    at react-data-grid-addons.js:25025
    at Object.focus (react-data-grid-addons.js:30255)
    at Object.onShow (react-data-grid-addons.js:30195)
    at Object.componentDidUpdate (react-data-grid-addons.js:30172)
    at commitLifeCycles (react-dom.development.js:8806)
    at commitAllLifeCycles (react-dom.development.js:9967)
    at HTMLUnknownElement.callCallback (react-dom.development.js:540)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:579)
    at invokeGuardedCallback (react-dom.development.js:436)
    at commitRoot (react-dom.development.js:10071)
    at performWorkOnRoot (react-dom.development.js:11003)
    at performWork (react-dom.development.js:10952)
    at batchedUpdates (react-dom.development.js:11070)
    at batchedUpdates (react-dom.development.js:2323)
    at dispatchEvent (react-dom.development.js:3414)
(anonymous) @ react-data-grid-addons.js:25025
focus @ react-data-grid-addons.js:30255
onShow @ react-data-grid-addons.js:30195
Modal_componentDidUpdate @ react-data-grid-addons.js:30172
commitLifeCycles @ react-dom.development.js:8806
commitAllLifeCycles @ react-dom.development.js:9967
callCallback @ react-dom.development.js:540
invokeGuardedCallbackDev @ react-dom.development.js:579
invokeGuardedCallback @ react-dom.development.js:436
commitRoot @ react-dom.development.js:10071
performWorkOnRoot @ react-dom.development.js:11003
performWork @ react-dom.development.js:10952
batchedUpdates @ react-dom.development.js:11070
batchedUpdates @ react-dom.development.js:2323
dispatchEvent @ react-dom.development.js:3414
index.js:2177 The above error occurred in the <Modal> component:
    in Modal (created by ContextMenuWrapper)
    in ContextMenuWrapper (created by ContextMenu)
    in ContextMenu (created by ReactDataGridContextMenu)
    in ReactDataGridContextMenu (at App.js:116)
    in MyContextMenu (at App.js:74)
    in div (created by RowsContainer)
    in RowsContainer (created by Canvas)
    in div (created by Canvas)
    in Canvas (created by Viewport)
    in div (created by Viewport)
    in Viewport (created by Grid)
    in div (created by Grid)
    in div (created by Grid)
    in Grid (created by ReactDataGrid)
    in div (created by ReactDataGrid)
    in div (created by ReactDataGrid)
    in ReactDataGrid (at App.js:73)
    in App (at index.js:7)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
__stack_frame_overlay_proxy_console__ @ index.js:2177
logCapturedError @ react-dom.development.js:9769
captureError @ react-dom.development.js:10560
commitRoot @ react-dom.development.js:10079
performWorkOnRoot @ react-dom.development.js:11003
performWork @ react-dom.development.js:10952
batchedUpdates @ react-dom.development.js:11070
batchedUpdates @ react-dom.development.js:2323
dispatchEvent @ react-dom.development.js:3414
react-data-grid-addons.js:25025 Uncaught TypeError: Cannot read property 'contains' of undefined
    at react-data-grid-addons.js:25025
    at Object.focus (react-data-grid-addons.js:30255)
    at Object.onShow (react-data-grid-addons.js:30195)
    at Object.componentDidUpdate (react-data-grid-addons.js:30172)
    at commitLifeCycles (react-dom.development.js:8806)
    at commitAllLifeCycles (react-dom.development.js:9967)
    at HTMLUnknownElement.callCallback (react-dom.development.js:540)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:579)
    at invokeGuardedCallback (react-dom.development.js:436)
    at commitRoot (react-dom.development.js:10071)
    at performWorkOnRoot (react-dom.development.js:11003)
    at performWork (react-dom.development.js:10952)
    at batchedUpdates (react-dom.development.js:11070)
    at batchedUpdates (react-dom.development.js:2323)
    at dispatchEvent (react-dom.development.js:3414)
(anonymous) @ react-data-grid-addons.js:25025
focus @ react-data-grid-addons.js:30255
onShow @ react-data-grid-addons.js:30195
Modal_componentDidUpdate @ react-data-grid-addons.js:30172
commitLifeCycles @ react-dom.development.js:8806
commitAllLifeCycles @ react-dom.development.js:9967
callCallback @ react-dom.development.js:540
invokeGuardedCallbackDev @ react-dom.development.js:579
invokeGuardedCallback @ react-dom.development.js:436
commitRoot @ react-dom.development.js:10071
performWorkOnRoot @ react-dom.development.js:11003
performWork @ react-dom.development.js:10952
batchedUpdates @ react-dom.development.js:11070
batchedUpdates @ react-dom.development.js:2323
dispatchEvent @ react-dom.development.js:3414
react-data-grid-addons.js:26977 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at Object.getMenuPosition (react-data-grid-addons.js:26977)
    at react-data-grid-addons.js:26958

please help me guys i'm struck up last 3 days :(

**Comment by kamaldlk** [comment]
please help me  guys i'm struck up  last 3 days :(

**Comment by mrgurdeep** [comment]
Can you create a jsfiddle for your issue ?

**Comment by kamaldlk** [comment]
first thanks for reply @mrgurdeep  i was waiting last 6 days 
https://codesandbox.io/s/98l9mop7op 
please check above link

**Comment by kamaldlk** [comment]
I got fixed this issue thanks

**Comment by mrgurdeep** [comment]
@kamaldlk how did you manage to do it ? can you share ?

**Comment by kamaldlk** [comment]
yes If we are going to use react 16 with react-data-grid the context menu not working that overlay version0.63  and above version. but luckily working only one version react-overlay  0.73 so i just cloned context menu lib updated packages and then i pushed npm js

**Comment by denv3r** [comment]
@kamaldlk could you please share the way you use your menu in react-data-grid project.
I've tried to replace 
`const { Menu: { ContextMenu, MenuItem, SubMenu }} = require('react-data-grid-addons');`
by
`const { ContextMenu, MenuItem, SubMenu } = require('kf-contextmenu');`
but it doesn't work. Menu is not showing. With no errors.

**Comment by vitorhorta** [comment]
Same issue here. @denv3r did you fix this?

**Comment by denv3r** [comment]
@vitorhorta, nope( Also I think that context menus is very buggy when I use it with Grouping and Tree View. So I decided not to use it. I use Cell Actions instead.

**Comment by OmerAli** [comment]
@kamaldlk Hi can you share you example, as i am facing the issue with context menu.
![error](https://user-images.githubusercontent.com/9985402/37330629-8a18b9c0-26c3-11e8-83a0-f2ed6f3f8b4c.PNG)
