### ISSUE TITLE
[Idea] Enable Cell Expand functionality

### ISSUE THREAD

**Issue by malonecj** [adazzle/react-data-grid#102]
### Description

Currently, when text the text of a cell in React Data Grid becomes too long, it gets truncated and an elipsis is shown. We would like a method to display the full amount of text in a cell if the text is too long.
This could be from either exapanding the height and width of the cell to show the entire content. Or displaying that content in a modal.
### Current functionality

![image](https://cloud.githubusercontent.com/assets/1432798/11126593/7ffcd634-8967-11e5-8526-90266a41baad.png)
### Desired functionality

![image](https://cloud.githubusercontent.com/assets/1432798/11126945/64ec9a58-8969-11e5-9000-3ef155d614be.png)

Requirements:
- Modify the `render` method of https://github.com/adazzle/react-data-grid/blob/master/src/Cell.js such that it renders an `ExpandIcon`  React component  if the text is truncated.
- Expand icon should have an onClick event that renders a modal window adjacent to the cell.
- Navigating across the cells should leave the modal window open but change the content
- Create a new example in https://github.com/adazzle/react-data-grid/tree/master/examples/scripts that demonstrates the functionality and loads a React Data Grid that has truncated text in some cells.

Bonus Points:
Add one of more tests in https://github.com/adazzle/react-data-grid/blob/master/src/Cell.js or on your new component to verify the new functionality

**Comment by snario** [comment]
+1

**Comment by jpdriver** [comment]
related: https://github.com/adazzle/react-data-grid/issues/248

**Comment by azl397985856** [comment]
I wanna know whether the react-data-grid support Cell Expand functionality now

**Comment by joinsunil** [comment]
What is the solution for such use cases.

**Comment by FatehAK** [comment]
Any update on this? Feels like its a must have for such a library

**Comment by iamsaurabhgupt** [comment]
Any update?
