### ISSUE TITLE
getCellActions iterator key warning

### ISSUE THREAD

**Issue by himanshu1691** [adazzle/react-data-grid#1020]
### Which version of React JS are you using?

✅ Officially supported ✅
- [x ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ x] 🐛 Bug Report
- [ ] 💡 Feature Request

---

### Issue Details

- current behavior:
While using the cell actions rendering it gives warning when I want to render actions on multiple cells it gives warning:  

> Each child in an array or iterator should have a unique "key" prop. Check the render method of `Cell` 

I see in the Cell.prototype.getCellActions method that there is no 'key' specified. Is there something I am missing.

Cell.prototype.getCellActions = function getCellActions() {
	    var _props = this.props,
	        cellMetaData = _props.cellMetaData,
	        column = _props.column,
	        rowData = _props.rowData;

	    if (cellMetaData && cellMetaData.getCellActions) {
	      var cellActions = cellMetaData.getCellActions(column, rowData);
	      if (cellActions && cellActions.length) {
	        return cellActions.map(function (action, index) {
	          return React.createElement(_CellAction2['default'], { action: action, isFirst: index === 0 
       });
	        });
	      }
	      return null;
	    }
	    return null;
	  };

- desired behvaior:
There should be no warning when trying to render actions on multiple cells
- Steps to reproduce the issue:
Try rendering action on multiple cells

![GetCellActionsError](https://user-images.githubusercontent.com/10795688/32866863-a60fb18a-ca1e-11e7-9ec8-807112efc64a.png)

**Comment by mrgurdeep** [comment]
Can you try running one of example and check whether you get these messages in console.

And can you also create a jsfiddle for your case ?

**Comment by himanshu1691** [comment]
I was not able to reproduce the issue on jsfiddle.
Turns out that the warnings vanished after I changed the package versions to : 
"react": "15.6.2",
"react-data-grid": "2.0.60"

**Comment by milesrichardson** [comment]
I'm getting this error on 2.0.76

**Comment by milesrichardson** [comment]
Here is the hacky fix I'm using:

``` js

const {
    Cell
} = require('react-data-grid')

var origGetCellActions = Cell.prototype.getCellActions
Cell.prototype.getCellActions = function() {
    const cellActions = origGetCellActions.apply(this, arguments)

    return (cellActions)
        ? cellActions.map((cellAction) => React.cloneElement(cellAction, {key: Math.random()}))
        : null
}
```

@himanshu1691 You might want to try reproducing this issue again in the latest version - it's definitely there.
