### ISSUE TITLE
[Idea] Drag column to reorder

### ISSUE THREAD

**Issue by malonecj** [adazzle/react-data-grid#103]
#### Description
Implement column header dragging to reorder a column

#### Requirements
 - Create a new example in https://github.com/adazzle/react-data-grid/tree/master/examples/scripts similar to https://github.com/adazzle/react-data-grid/blob/master/examples/scripts/example02-resizable-cols.js where each column has a draggable property set to true.

- Modify https://github.com/adazzle/react-data-grid/blob/master/src/HeaderCell.js to listen for  onDragStart, onDrag, onDragEnd events. Triggering onDragStart, onDrag should  should show the column header being dragged. OnDragEnd should bubble up to the `HeaderRow`, and `Header` components, and finally trigger an onColumnReorder event in `ReactDataGrid` component which will modify the order of `state.columnMetrics.column`. Alternatively you could try implementing a drag and drop library like http://gaearon.github.io/react-dnd/

**Comment by ducwings** [comment]
+1

**Comment by bebop14** [comment]
+1

**Comment by diogofcunha** [comment]
This was released in `1.0.37`.

An example can be found [in here](http://adazzle.github.io/react-data-grid/examples.html#/row-reordering).

**Comment by joshparolin** [comment]
@diogofcunha - Row reordering was released, but was _column_ reordering?

**Comment by dkwin** [comment]
Just wanted to chime in on this, any update on column reordering?

**Comment by AmrKafina** [comment]
Still nothing here? Would really like to see this.

**Comment by martinnov92** [comment]
Hello, since we need this to work in the company I work for I tried to implement this feature, here is an pull request https://github.com/adazzle/react-data-grid/pull/702

I hope it will get pass through the code review, but I know they might be a problem with my tests as it were my first tests I was writing :D.

**Comment by martinnov92** [comment]
Here is little clip, where I show you how it works, the second part with popup is not in this pull request, but it is easy to implement it on your own.
https://drive.google.com/file/d/0B04DA-ziLi_GSEJLUnBkMVU3QVU/view

**Comment by JimTheMan** [comment]
Hi. Nice lib! But I'm getting errors with the React.createClass being deprecated. Is there any way I can use this with ES6 React?

**Comment by jpdriver** [comment]
hey @JimTheMan -- that's an issue to do with React versions; you can track that discussion here https://github.com/adazzle/react-data-grid/issues/744

**Comment by JimTheMan** [comment]
Thanks. Unfortunately, this feature uses React dnd and provides no way of passing in an "HTML5Backend". Is there not a way to use this grid in an app that separately uses React dnd?

**Comment by martinnov92** [comment]
Hello @JimTheMan if I am understanding your question correctly you would like to use grid without React DnD context, right? What you can do to remove backend for ReactDnD is to copy and paste this two files in your project (`DraggableHeaderCell` and `DraggableContainer`) https://github.com/adazzle/react-data-grid/tree/master/packages/react-data-grid-addons/src/draggable-header, then remove DragAndDrop Context from this file https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid-addons/src/draggable-header/DraggableContainer.js#L29 (in case you are already using React DnD in your app), then wrap your data grid in DraggableContainer and then it should work as expected. I know it is not the best way how to do it tho :/ Hope it helps

**Comment by JimTheMan** [comment]
@martinnov92 Interesting, but what do you mean by "copy and paste these files into your project"? I can put them anywhere in my project?

**Comment by martinnov92** [comment]
@JimTheMan you can put them anywhere as long as you can import them :D I put them in the folder where I got my grid wrapped and tweaked so it suits my needs and there I import the DraggableContainer, hope it makes sense.

**Comment by JimTheMan** [comment]
@martinnov92 Thanks. Hackish, but it worked! :)

**Comment by arttay** [comment]
Hey guys, kinda old (I know) but the company I work for it evaluating table libraries and draggable column is number 2 on our list of things to have. Has there been any updates?
