### ISSUE TITLE
AutoCompleteFilter fails if cell value is NULL

### ISSUE THREAD

**Issue by dsego** [adazzle/react-data-grid#1031]
### Which version of React JS are you using?

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [x] v15.6.x
---

### Which browser are you using?

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [x] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

### Issue Details

Column filtering will fail with `TypeError: null is not an object (evaluating 'columnValue.toString')` when `row[columnKey]`  is **`null`** (AutoCompleteFilter.js,  line 36). 

https://github.com/adazzle/react-data-grid/blob/e7b5fbfa30bc097d6ed4993e348b50430ffb6178/packages/react-data-grid-addons/src/cells/headerCells/filters/AutoCompleteFilter.js#L34-L42

**Comment by fazamutash** [comment]
I am still facing this issue
