### ISSUE TITLE
getting data from cell

### ISSUE THREAD

**Issue by reactnodevcx** [adazzle/react-data-grid#1033]
How I can get data from cell selected by click?

**Comment by wfgmiami** [comment]
@reactnodevcx 
The way i do it - have onCellSelected assign a custom funciton:
`<ReactDataGrid
			onCellSelected={ this.getSelectedCell }`
then in your getSelectedCell function have the logic for whatever you want to do with the cell that was selected
onCellSelected will give ou rowIdx and idx which are the number of the row and the number of the field/column that the cell represents

**Comment by amanmahajan7** [comment]
Here is the [cell selection events example](http://adazzle.github.io/react-data-grid/examples.html#/cell-selection-events)
