### ISSUE TITLE
Row custom formatter

### ISSUE THREAD

**Issue by himanshu1691** [adazzle/react-data-grid#1036]
I know that the data-grid supports custom column formatter [Example](http://adazzle.github.io/react-data-grid/examples.html#/custom-formatters). But is there a way to achieve the same kind of formatting for a Row?

**Comment by amanmahajan7** [comment]
You can use a custom `RowRenderer` as described in the [row renderer example](http://adazzle.github.io/react-data-grid/examples.html#/customRowRenderer)

**Comment by srikanthpavuluri** [comment]
How to implement the custom row render in react 16?

**Comment by siyuano** [comment]
Hi, this page is deleted.  http://adazzle.github.io/react-data-grid/examples.html#/customRowRenderer

Does it mean this feature is deprecated?

**Comment by amanmahajan7** [comment]
This feature still exists, the example URL has changed
http://adazzle.github.io/react-data-grid/#/examples/customRowRenderer

**Comment by iamwilhelm** [comment]
Updated to:
http://adazzle.github.io/react-data-grid/docs/examples/row-renderer
