### ISSUE TITLE
rowGetter does not takes arrays as input

### ISSUE THREAD

**Issue by arpitkh12** [adazzle/react-data-grid#1040]
The rowGetter in ReactDataGrid does not takes in array of object as an input and always requiring to pass in a function.

Can someone provide and an example of it.

**Comment by jpdriver** [comment]
hey @arpitkh12 -- have a look at the [basic example](http://adazzle.github.io/react-data-grid/scripts/example01-basic.js)

```
  rowGetter = (i) => {
    return this._rows[i];
  };

  render() {
    return  (
      <ReactDataGrid
        columns={this._columns}
        rowGetter={this.rowGetter}
        rowsCount={this._rows.length}
        minHeight={500} />);
  }
```

**Comment by arpitkh12** [comment]
I am trying not to have the function, can we not pass in array itself.
Something like this
``rowGetter={this.rows}"

**Comment by mrgurdeep** [comment]
rowGetter returns current row on the basis of input i which is index. If you dont want seperate function. You can just write inline function

(i) => return this._rows[i]

**Comment by pat12345** [comment]
Hello,

 ` import ReactDataGrid from 'react-data-grid';
const [rows, setRows] = useState([]);
const columns = [{ key: "", name: "Code", editable: true },
        { key: "delete", name: "Action", editable: false}
    ];
function loadcode(){
........service call.... setRows(codes.Tcode.split(','));
}
    function rowGetterTest(index) {
      //  console.log(rows[index]);
        return rows[index];
    };
return( <ReactDataGrid
                columns={columns}
                rowGetter={rowGetterTest}
                rowsCount={rows.length}              
                rowSelection={true}
                onGridRowsUpdated={onGridRowsUpdated}
            />);`

I see single character in the data grid.
I also see column names and data grid with two rows (this is expected - but value is single character).
my array looks like this
(2) ["CKT", " RH"]
0: "CKT"
1:" RH"

My datagrid look like below
 code     Action
K
R

Any idea - why is it not printing whole string?
