### ISSUE TITLE
Row id attributes

### ISSUE THREAD

**Issue by Seurimas** [adazzle/react-data-grid#1046]
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [x] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [x] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [x] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

For testing and other purposes, Rows should be able to be rendered with ids. However, it is not included as a [known div property](https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid/src/Row.js#L20), so it's remarkably difficult to get an id on those elements.

**Comment by jpdriver** [comment]
hey @Seurimas -- can you explain a bit more about the scenarios where you would need this? you already have the id in the component props, so I'm not clear on why would also additionally need this..? if you're able to share one, a small code example would be perfect

**Comment by Seurimas** [comment]
To be clear, I'm not talking about the key or the index of the row. I'm referring to the ability to set the `id` html attribute.

I eventually found a solution:
```
import React from 'react';
import { Row } from 'react-data-grid';

const IdentifiedRow = name => class IdentifiedRenderer extends Row {
    render() {
        const original = super.render();
        const updated = React.cloneElement(original, {
            id: `${name}-${this.props.idx}`,
        });
        return updated;
    }
};
```
