### ISSUE TITLE
Input validations with editors

### ISSUE THREAD

**Issue by martinnov92** [adazzle/react-data-grid#1047]
### Which version of React JS are you using?

✅ Officially supported ✅
- [x] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.6.x
- [ ] v15.5.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] Edge
- [x] Chrome
- [ ] IE 9 / IE 10 / IE 11

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

Hello is it possible to do value validation in editors mode? 

I am currently using custom editors components which can validate inputs, but as soon as I move cursor away from invalid input, data grid "swallows" the error and user can´t see if it was saved or there was an error. Only time this is working is when I click outside the grid and then I can see warning but as soon as I activate another editor this validation message disappears...

Click outside grid:
![gif](http://g.recordit.co/Ob3wCEawqb.gif)

Thank you

**Comment by diogofcunha** [comment]
Hi @martinnov92.

Yes, that is a very valid use case and we use something similar in our product. So that we can give you a best solution for you use case, can you please tell me how your managing your state? Is it redux, local state, mobx?

**Comment by martinnov92** [comment]
Hello, thank you for sour answer, we use MobX

**Comment by diogofcunha** [comment]
The generic steps are:
- You add a row renderer (if you don't have one already)
- That renderer needs to render a `Row`
- Create a cellRenderer to inject in the `Row` component, that cell renderer should be connected to your store (@bonimba will add a few mobx coupled steps in here as I'm not confident enough in that tech)
- To make this as generic as possible you can use an HOC that adds icons to the cells and still keeps all info for your formatters
```
  const { column, cellRef, icons, ...cellProps } = this.props;

    let cellColumn = column;
    if (icons.length > 0) {
      // Create a higher-order component to display warning icons
      const formatter = withIconsFormatter(icons)(column.formatter);
      cellColumn = { ...cellColumn, formatter };
    }

    return (
      <Cell
        {...cellProps}
        column={cellColumn}
        ref={cellRef}
      />
    );
  }
```
- As long as your store holds information about input state (warnings or something more in the future), as long as the cellRenderer is correctly connected you have the power

**Comment by martinnov92** [comment]
Thank you @diogofcunha  I will give it a try
