### ISSUE TITLE
[Idea] Display number of visisble rows count in toolbar

### ISSUE THREAD

**Issue by malonecj** [adazzle/react-data-grid#105]
![image](https://cloud.githubusercontent.com/assets/1432798/11148541/2cc9d2c4-8a15-11e5-8a82-e0cb27614783.png)

Difficulty: Easy
### Description:

The toolbar should display an indication showing the number of visible rows as well as the total rows count as in the image above.
### Requirements

The `ReactDataGrid` component needs to know when the `Viewport` is scrolled. It can then update the toolbar with the indexes of the visible rows.
- Modify the `onScroll` event in https://github.com/adazzle/react-data-grid/blob/master/src/Viewport.js#L85 to pass the `state.displayStart` and `state.displayEnd` properties as parameters
- This event is already consumed by the BaseGrid component in https://github.com/adazzle/react-data-grid/blob/master/src/GridScrollMixin.js#L22. However it should pass this information one level up to the `ReactDataGrid` wrapper component
- The displayStart and displayEnd properties should then be passed to the toolbar where they can be used to render the visible rows information

**Comment by vinaykumar-chekka** [comment]
Can you please give an example code snippet for the displaying the visible row count.
