### ISSUE TITLE
Docs/Examples: Changing background changes foreground instead?

### ISSUE THREAD

**Issue by lordbah** [adazzle/react-data-grid#1050]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ X] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [X ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [X ] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details
Custom Row Renderer example says it is changing background color but when you look at it the cell background color remains the same and the text foreground color gets changed.
```
Please include:
- What the current behavior is
Custom Row Renderer example says it is changing background color but when you look at it the cell background color remains the same and the text foreground color gets changed.
- What the desired behvaior is
Cell background color should be changed. Or docs and code comments changed.
- (If Bug) Steps to reproduce the issue
View http://adazzle.github.io/react-data-grid/examples.html#/customRowRenderer and its source code.
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

![crr](https://user-images.githubusercontent.com/24962539/33859100-7367bfe8-dea0-11e7-870e-41c0ada4c270.png)

**Comment by malonecj** [comment]
Yes you are correct. The custom row renderer is actually changing the text colour.  Fixed here
https://github.com/adazzle/react-data-grid/pull/1052

**Comment by malonecj** [comment]
Yes, you are right. It is actually changing the text colour, not the background. Thanks. The purpose of the example is just to show how to use a custom row renderer.
