### ISSUE TITLE
Overiding sort header/icons with custom markup/css ??

### ISSUE THREAD

**Issue by 29er** [adazzle/react-data-grid#1055]
Can anyone show some guidance as to how to override the default 'sort' icons to use something like font-awesome. basically I am looking to override

```
react-grid-HeaderCell-sortable
react-grid-HeaderCell-sortable--ascending
react-grid-HeaderCell-sortable--descending
```

with my own markup and css ?? From what I see in the source code, it doesn't look like a simple task. Thanks for any help !

**Comment by diogofcunha** [comment]
Hi @29er.

To create your own custom headers (using for example fa) use headerRenderer prop on your column definitions.

If you want to just customise css just override those class names on your style sheet and import it (to add icons you use `content` in css3)

**Comment by BlaineBradbury** [comment]
@diogofcunha I did not find a way to replace the triangle that is inserted in the sortable header, but here is a hack hides it by setting font-size to zero.  Then using a pseudo selector, we can insert css content as I believe you suggested.  Not the greatest for browser support.  We really need a way to simply override `getSortByText()` at [here](https://github.com/adazzle/react-data-grid/blob/master/packages/common/cells/headerCells/SortableHeaderCell.js), I think.

```
.react-grid-HeaderCell-sortable--ascending > .pull-right {
	display: inline-block;
	font-size:0px;
	transform: rotate(90deg);
}
.react-grid-HeaderCell-sortable--ascending > .pull-right::after {
	font-size:12px;
	content: "\25C0" !important;
}
.react-grid-HeaderCell-sortable--descending > .pull-right {
	display: inline-block;
	font-size:0px;
	transform: rotate(270deg);
}
.react-grid-HeaderCell-sortable--descending > .pull-right::after {
	font-size:12px;
	content: "\25C0" !important;
}

.react-grid-Row .react-grid-Cell {
	padding: 8;
	border: 0;
}
```
