### ISSUE TITLE
Add row in the middle of two rows?

### ISSUE THREAD

**Issue by popo63301** [adazzle/react-data-grid#1062]
How do you approach adding a row in the middle of two rows? I've read there's a system of key of each cell, so if you add a row in the middle of two, you probably need to change every key, no?

**Comment by richardware** [comment]
Hi @popo63301, if I understand the question correctly then you need to do one of the following:
1) Pass a modified collection of rows as a prop to the grid (using an array of rows as the `rowGetter` prop).
2) Modify the source rows (if you are passing a getter fn as the `rowGetter` prop).

In either case, you would insert the new row at the correct point in your source rows. The key is automatically assigned on render [here](https://github.com/adazzle/react-data-grid/blob/44d0ac3e7228907e783d8caebdd8f54bbca55d89/packages/react-data-grid/src/Canvas.js#L284).

**Comment by johnstsai** [comment]
Did anyone try to implement?
Would be appreciate any sample code for study purpose.

**Comment by johnstsai** [comment]
@richardware Hi, I am using React Data Grid with mongoDB, our tool lets user add new row and we save the input instantly. We want to insert row between two rows and it is easily done at frontend, however I am not sure what is the best way to deal with backend. If only dealing with frontend, the inserted row will go to the bottom after user refresh. I am asking this on stackoverflow [https://stackoverflow.com/questions/55204873/react-data-grid-insert-rows-between-two-rows-mongodb-generate-id-manually](url) but I haven't find a proper solution yet. Please advise if you have time, many thanks
