### ISSUE TITLE
Grouped Header Feature

### ISSUE THREAD

**Issue by parth1403** [adazzle/react-data-grid#1066]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [x] v15.4.x
---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ ] Chrome
---

### I'm submitting a ...

- [x] 💡 Feature Request
---

### Issue Details

```
Please include:
It will be awesome to have group headers as there are many use cases where there are huge numbers of columns are there and some of columns are of similar types, so having group headers will be very useful for users to navigate or skim headers.

Here is screenshot of grouped headers implemented.
![image]

Here is a patch of sample work.
Let's discuss approach if you like or don't like my changes.

My dev notes:
- I still working on getting rid of conditions of groups at different mixins. Do you have any plan to get rid of mixins?
- I didn't find any way to add it as a add on.

(https://user-images.githubusercontent.com/3193267/34706502-41836e0a-f55c-11e7-8399-20b65d55f601.png)



```

**Comment by angeloocana** [comment]
That is the only feature that is missing for what we need from a grid =/
