### ISSUE TITLE
Can't resolve 'create-react-class' in node_modules\react-data-grid\dist

### ISSUE THREAD

**Issue by barbalex** [adazzle/react-data-grid#1074]
### Which version of React JS are you using?

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.2.0

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

---

### I'm submitting a ...

- [x] 🐛 Bug Report

---

### Issue Details

Please include:
- current behavior:
  When I run `yarn start` I get: `Module not found: Can't resolve 'create-react-class' in 'C:\Users\alexa\ae2\node_modules\react-data-grid\dist'`
  
![2018-01-10_18h38_29](https://user-images.githubusercontent.com/669783/34786909-c9d5460a-f635-11e7-9d63-63235ccf9a57.png)

I have included `create-react-class` as peer dependency, see here: https://github.com/barbalex/ae2/blob/9893ea08299f0f5a76c98e741c527e7611cd0318/package.json

- desired behavior: no error
- (If Bug) Steps to reproduce the issue
  ```
  yarn add react-data-grid
  yarn start
  ```

**Comment by amanmahajan7** [comment]
Thank for reporting this bug, it was introduced in #1065. I will create a PR with a fix soon

**Comment by amanmahajan7** [comment]
`create-react-class` is a `peer` dependency for `react-data-grid` meaning projects using `react-data-grid` should include `create-react-class` as a `dependency`

**Comment by barbalex** [comment]
Is https://github.com/barbalex/ae2/blob/9893ea08299f0f5a76c98e741c527e7611cd0318/package.json#L44 not enough?

**Comment by barbalex** [comment]
...and why would it be looked for in the dist folder of react-data-grid?

**Comment by amanmahajan7** [comment]
Peer dependencies are not installed automatically, you need to _depend_ on `create-react-class`
`yarn add create-react-class`

```
"dependencies": {
    "create-react-class": "15.6.2"
}
```
https://nodejs.org/en/blog/npm/peer-dependencies/

**Comment by barbalex** [comment]
Oh. Seems like that changed with npm v3.

Thanks a lot for helping and for this great tool!
