### ISSUE TITLE
Not possible to filter decimal numbers

### ISSUE THREAD

**Issue by andrascik** [adazzle/react-data-grid#1082]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [x ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
It's not possibe to filter exact values in decimal format, f.e.: 3.14 . It only takes integers.

- What the desired behvaior is
Filtering decimal numbers

- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature
Most tables and grids are used for reports and numeric data. It's necessary to have good filters.

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

Thanks in Advance
Richard

**Comment by pidupuis** [comment]
Any advance or workaround?
