### ISSUE TITLE
Allow columns to be sorted descending on first click

### ISSUE THREAD

**Issue by rlreamy** [adazzle/react-data-grid#1083]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [x ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ x ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [ x ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is:
When we have a sortable column in the table, the initial click will sort the table in ascending order, then on second click, it will switch to descending, upon a third click it will go back to unsorted (or the original order the rows were in)

- What the desired behvaior is:
Developers should be able to specify whether they want the first click to be in ascending or descending order.  So, if the first click is to be in descending order, it will go to ascending on next click, and then back to unsorted.

- (If Feature) The motivation / use case for the feature:
We have scientific data where a higher number is more important.  We want the users to be able to sort the rows by significance/relevance.  Thus, some of our columns we want the highest number at the top, and others the lower number is actually more relevant. 

While we can implement the comparator logic so that it sorts correctly on the first click, we also want the sort indicator to show the direction that the data are actually sorted in (rather than showing it is sorted ascending, but when looking at the values, you see that they are actually descending)


We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by malonecj** [comment]
Fixed by #1086
