### ISSUE TITLE
scrolling is stuck when scrollToRowIndex is specified

### ISSUE THREAD

**Issue by laaglu** [adazzle/react-data-grid#1084]
### Which version of React JS are you using?

- [ x] v15.4.x

---

### Which browser are you using?

- [x] Chrome

---

### I'm submitting a ...

- [ x] 🐛 Bug Report

### Issue Details
scrollToRowIndex specifies the index of the first row to display when the grid is initially rendered. However, once this initial rendering has completed, scrolling is then stuck to this row. That should not be the case.

**Comment by vitorhorta** [comment]
I'm trying to use scrollToRowIndex too and having same issue. Is there any other way to scroll programatically to the end of the grid?

**Comment by laaglu** [comment]
The pull request has not been merged yet and the problem still persists.
