### ISSUE TITLE
Values not showing up for right-hand column cells when resize the window

### ISSUE THREAD

**Issue by francesc79** [adazzle/react-data-grid#1087]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [X ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [X ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [X ] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details
When I resize the window same column cells disappear. I debug the library and I find what hepped.
Into ViewportScrollMixin module is defined componentWillReceiveProps livecycle hook that call updateScroll function. The problem for my opinion is that when call updateScroll  without last parameter width the function getRenderedColumnCount consider this.props.columnMetrics.totalWidth that is not updated. 

--

**Comment by zyxelvincenzo79** [comment]
i have the same problem

**Comment by thupi** [comment]
I have same issue and is currently looking for a table solution :-) Any progress on this :-) ?

**Comment by francesc79** [comment]
@thupi I opened a PR, the bug was just fix, I'm waiting the merge with master. If you want try the fix you can checkout francesc79/react-data-grid branch zazos-issue-1087.

**Comment by amanmahajan7** [comment]
This is a known issue where sometimes the cell content is empty. We are actively working on improving the [cell rendering logic](https://github.com/adazzle/react-data-grid/pull/1123) and v4 should address this issue. In the meantime re-rendering grid seems like a potential solution

```
window.addEventListener('resize', () => {
   // Re-render grid
   // May be recalculate grid's minHeight
   const minHeight = ....;
   this.setState({ minHeight });
   // Or may be forceUpdate (not a huge fan of this approach)
   this.forceUpdate();
});
```

**Comment by animeshkayal** [comment]
Hi Aman,
Kindly let us know when can we expect the V4 release?

**Comment by rlreamy** [comment]
Is this fixed in any of the v4 releases?

**Comment by kevyu** [comment]
I think the bug still exists in v4.

**Comment by amanmahajan7** [comment]
Please check the [change log](https://github.com/adazzle/react-data-grid/blob/master/CHANGELOG.md) for what is included in v4. We recently merged a [PR ](https://github.com/adazzle/react-data-grid/pull/1123)that improves cell rendering logic and will fix this particular issue. It is a big rewrite and we discovered a few [bugs ](https://github.com/adazzle/react-data-grid/pull/1209)during internal testing. This is being actively worked on but at this moment we do not know when this will be released. I will keep you all posted.

**Comment by MickaToast** [comment]
Hi, any update on this? Thanks.

**Comment by rlreamy** [comment]
Is there any update on this?  It looks like it was supposed to be fixed in v4.

**Comment by vellov** [comment]
Any update on this?
