### ISSUE TITLE
Deprecate unused props

### ISSUE THREAD

**Issue by malonecj** [adazzle/react-data-grid#1092]
Investigation to be done on ReactDataGrid props to be deprecated before moving to version 4.0 where they will be removed.

The following should be deprecated
onRowUpdated
onDragHandleDoubleClick
onCellsDragged
onCellCopyPaste

and the rest should be highlighted in this issue.

Use https://www.npmjs.com/package/react-is-deprecated to add warnings when these props are used.

**Comment by diogofcunha** [comment]
We should also deprecate `selectedRows`, it was replaced over a year ago by a more stable and extensible way of selection

Proof:
http://adazzle.github.io/react-data-grid/scripts/example16-row-select.js

**Comment by diogofcunha** [comment]
@malonecj there is a prop called `onRows`, is this used anywhere? doesn't look like it

**Comment by diogofcunha** [comment]
Maybe we should group this props into one: 
```
    onViewportKeydown: PropTypes.func.isRequired,
    onViewportKeyup: PropTypes.func,
    onViewportDragStart: PropTypes.func.isRequired,
    onViewportDragEnd: PropTypes.func.isRequired,
    onViewportClick: PropTypes.func.isRequired,
    onViewportDoubleClick: PropTypes.func.isRequired,
```

My 2 suggestions should ship with some code modes to change the code automatically for rdg users

**Comment by amanmahajan7** [comment]
`rowScrollTimeout` is also not used anywhere
