### ISSUE TITLE
Unable to call a function or use window.location.href inside getCellActions callback method

### ISSUE THREAD

**Issue by dsuraj72** [adazzle/react-data-grid#1098]
- Have you already searched for similar issues? Please help us out and double-check first!
Yes

- Using latest versions
Yes

Hello,
I'm trying to call certain url's on click of following cellActions. Only alert seems to be working inside callback block of getCellActions.

Is there a way to use window.location.href inside the callback block?

**Sample Code:**
`getCellActions(column, row) {
    if (column.key === 'action') {
      return [{
        icon: 'glyphicon glyphicon-option-vertical',
          actions: [{
          icon: 'glyphicon glyphicon-edit',
          text: 'Edit',
          callback: () => { 
              alert('Edit'); 
              this.edit_function(id);
//OR
              window.location.href = "/edit-url?id=1";
          }
        },
        {
          icon: 'glyphicon glyphicon-edit',
          text: 'Delete',
          callback: () => { alert('Delete'); }
        }]
      }
      ];
    }  
  }`

Thanks.

**Comment by arjunkori** [comment]
I have the same issue!
