### ISSUE TITLE
Updating grid data with a new row causes it to jump to the bottom and select

### ISSUE THREAD

**Issue by alistairjcbrown** [adazzle/react-data-grid#110]
There are two places with logic to deal with a new row:
 - The Canvas, which scrolls to the bottom: https://github.com/adazzle/react-data-grid/blob/e6af22516d9f0a6dc68795be537c98721275a865/src/Canvas.js#L160-L162
 - The Grid, which set the last row as selected: https://github.com/adazzle/react-data-grid/blob/e6af22516d9f0a6dc68795be537c98721275a865/src/addons/grids/ReactDataGrid.js#L115-L117

However, this means that modifying the grid data using an external menu (eg. show / hide rows), or updating the grid data periodically can trigger this behaviour.

Is there another way to tag that row has been specifically added, rather than just a change in the row count?

**Comment by gtkovas** [comment]
Ran into an issue with this behavior as well. As a workaround, you can use the OnSelect method to put the focus where you'd prefer it, using the backing reference of your ReactDataGrid, like so:

dataGridRef.onSelect({rowIdx: i, idx: j}); //will place grid focus onto specified cell

**Comment by JoshSGman** [comment]
+1

**Comment by malonecj** [comment]
The scroll to bottom behavior has now been removed from canvas

https://github.com/adazzle/react-data-grid/blob/master/src/Canvas.js#L66
