### ISSUE TITLE
Allow rows to be focused instead of individual cells

### ISSUE THREAD

**Issue by zocky** [adazzle/react-data-grid#1101]
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

---

#### What the current behavior is

Only individual cells can be focused

#### What the desired behavior is

Allow the whole row to be focused, instead of individual cells. This should also work with the keyboard, i.e. up and down arrows should focus the previous/following row. This is separate from row selection (via checkboxes/radio buttons). The currently focused row may or may not be selected. 

An event should be emitted when the currently focused row changes. There should also be a programmatic way to set the focused row, and it should scroll into view. 

#### The motivation / use case for the feature

I have a grid which displays properties of items, and want to show the detail view/preview for the currently focused item in a separate component.

**Comment by Artforge** [comment]
bump
