### ISSUE TITLE
No onCellSelected event fired on the first cell (0,0) 

### ISSUE THREAD

**Issue by dcorb** [adazzle/react-data-grid#1108]
### Which version of React JS are you using?
⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [X ] v15.6.x

### Which browser are you using?

✅ Officially supported ✅
- [ X] Chrome

### I'm submitting a ...

- [X ] 🐛 Bug Report

### Issue Details

**- What the current behavior is**
In this demo case: https://jsfiddle.net/3su9me5j/2/
Clicking on the first cell, position 0,0, it won't call the `onCellSelected` handler, not entering in the debugger mode. (With devtools open)
**- What the desired behvaior is**
Clicking on the first cell, position 0,0, will behave like any other cell, executing `onCellSelected` function, and entering in the debugger mode (With devtools open)

The problem is that the initial "selected" value is 0,0
https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid/src/ReactDataGrid.js#L154

If I assign the value `enableCellSelect`as false, it works. But it should be true, as I understand.

**Comment by bonimba** [comment]
Hi @dcorb,

thanks for reporting the issue.
Good news: It's been fixed in version 3.0.11 :)

**Comment by dcorb** [comment]
Thanks! 💯

**Comment by dcorb** [comment]
I think it doesn't work still, I updated the demo with 3.0.11 
https://jsfiddle.net/3su9me5j/5/

**Comment by bonimba** [comment]
That's weird: It works fine for me. 
I'll try to look into it asap to see what can cause this different behaviour.

**Comment by iamkennytso** [comment]
Has this been fixed or is there a workaround? We're experiencing this issue currently.

**Comment by iamkennytso** [comment]
I've tried adding a temporary dom element .focus() and then removing the temporary element, but the problem still persists. Not sure if it's a focus issue or not.
