### ISSUE TITLE
Custom cell Editors

### ISSUE THREAD

**Issue by divsbhalala** [adazzle/react-data-grid#1111]
`Custom cell Editors - Easily create your own `  Features is implemented ?

**Comment by bonimba** [comment]
Hi @divsbhalala,
yes, it is currently possible to create and use your own custom cell editor.

You can have a look to this example: http://adazzle.github.io/react-data-grid/examples.html#/built-in-editors

In few steps:
- Create your react component or use one of those provided int the `react-data-grid-addons module` (https://github.com/adazzle/react-data-grid/tree/master/packages/react-data-grid-addons/src/editors)
**NOTE:** You need to import it if you want to take advantage of those built-in editors.
`import { Editors } from 'react-data-grid/addons';`
- Add the property `editor` to the column in which you want to use it
```
import MyEditor from './MyEditor';
this._columns = [
     {
        key: 'id',
        name: 'ID',
        width: 80
      },
      {
        key: 'task',
        name: 'Title',
        editable: true
      },
      {
        key: 'priority',
        name: 'Priority',
        editor: MyEditor
      }
    ];
```

- double click on the cell to use it

Let me know if it's all clear :)

**Comment by reebgame** [comment]
I try to create my own editor using a selectbox (material-ui) but when i choose a option then the focus start and commit the cell ... with a value null (indeed the change event of selectbox is triggered after the datagrid focus event)
do you have a trick ?
