### ISSUE TITLE
Dragging a header appears to drag all headers when the page containing the grid has a scrollbar

### ISSUE THREAD

**Issue by mmabraham** [adazzle/react-data-grid#1113]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [x] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

Please include:
```- What the current behavior is```
When the page containing the grid has a scrollbar, the header tab appears to get dragged together with all tabs to it's left
```- What the desired behvaior is```
Only the tab that is being dragged should appear dragged regardless of if there is a scrollbar on the page.
```- (If Bug) Steps to reproduce the issue```
On the [draggable headers example](http://adazzle.github.io/react-data-grid/examples.html#/draggable-header), zoom in until there is a scrollbar on the very right of the page. Drag one of the headers. While dragging, it looks like I am dragging the tabs to the left as well
```- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by martinnov92** [comment]
Hello, I just had the similar issue. I fixed it like this:

```js
let DraggableHeaderCell = (props: DraggableHeaderCellProps) => {
    const {
        connectDragSource,
        connectDropTarget,
        isDragging,
        isOver,
        canDrop
    } = props;

    let classes = [
        isOver && canDrop ? 'rdg-can-drop' : null,
        isOver ? 'is-over' : null
    ].filter((item) => item !== null).join(' ');

    // replace column left offset to correctly display html5 drag layer
    const propsCopy = {
        ...props,
        column: {
            ...props.column,
            left: 0,
        }
    };

    const style = {
        display: 'inline-block',
        height: `${props.height}px`,
        left: `${props.column.left}px`,
        width: `${props.column.width}px`,
        position: 'absolute' as 'absolute',
    };

    // set drag source and drop target on header cell
    return connectDragSource(
        connectDropTarget(
            <div
                style={style}
                className={classes}
            >
                <HeaderCell {...propsCopy} />
            </div>
        )
    );
}
```

Hope it helps.

**Comment by leti-df-mdsol** [comment]
Issue Details
Please include:
- What the current behavior is
When the page containing the grid has a scrollbar, the header tab appears to get dragged together with all tabs to it's left
- What the desired behvaior is
Only the tab that is being dragged should appear dragged regardless of if there is a scrollbar on the page.
- (If Bug) Steps to reproduce the issue
On the draggable headers example, zoom in until there is a scrollbar on the very right of the page. Drag one of the headers. While dragging, it looks like I am dragging the tabs to the left as well
Please let me know if this issue is resolved now?if yes in which version of react-data-grid? If no any work around to resolve this?

**Comment by leti-df-mdsol** [comment]
> Hello, I just had the similar issue. I fixed it like this in file DraggableHeaderCell.js. But you will need to copy DraggableHeader folder to your project or wait until someone fix it. I might do it on the weekend
> 
> ```js
> let DraggableHeaderCell = (props: DraggableHeaderCellProps) => {
>     const {
>         connectDragSource,
>         connectDropTarget,
>         isDragging,
>         isOver,
>         canDrop
>     } = props;
> 
>     let classes = [
>         isOver && canDrop ? 'rdg-can-drop' : null,
>         isOver ? 'is-over' : null
>     ].filter((item) => item !== null).join(' ');
> 
>     // replace column left offset to correctly display html5 drag layer
>     const propsCopy = {
>         ...props,
>         column: {
>             ...props.column,
>             left: 0,
>         }
>     };
> 
>     const style = {
>         display: 'inline-block',
>         height: `${props.height}px`,
>         left: `${props.column.left}px`,
>         width: `${props.column.width}px`,
>         position: 'absolute' as 'absolute',
>     };
> 
>     // set drag source and drop target on header cell
>     return connectDragSource(
>         connectDropTarget(
>             <div
>                 style={style}
>                 className={classes}
>             >
>                 <HeaderCell {...propsCopy} />
>             </div>
>         )
>     );
> }
> ```
> 
> Hope it helps.

Hi ,Please let me know if this fix is moved to the build and which version?
