### ISSUE TITLE
Custom css not rendering

### ISSUE THREAD

**Issue by kevaundray** [adazzle/react-data-grid#1119]
I cannot seem to see a style sheet in the node_modules, I am trying to change the css on the generated table.

**Comment by amanmahajan7** [comment]
Current build process does not generate a separate CSS file at the moment. We have plans to create separate CSS/JS bundles for the next release. Check this [PR](https://github.com/adazzle/react-data-grid/pull/824) for more info. For now if you want a custom styled grid you will need to override the intended classnames.

**Comment by amanmahajan7** [comment]
Feel free to reopen the issue if you have any further questions,

**Comment by mungojam** [comment]
@amanmahajan7

> For now if you want a custom styled grid you will need to override the intended classnames

Unfortunately due to the ordering of style imports in a typical create-react-app this is only possible if using `!important`, which I understand is a nuclear option

**Comment by ekeuus** [comment]
> @amanmahajan7
> 
> > For now if you want a custom styled grid you will need to override the intended classnames
> 
> Unfortunately due to the ordering of style imports in a typical create-react-app this is only possible if using `!important`, which I understand is a nuclear option

Is there any way to bypass this? We went back to a CRA build process again and it breaks for the prod build, but not for the dev one. @amanmahajan7

**Comment by ekeuus** [comment]
@mungojam @amanmahajan7 I was able to resolve it by having the css be injected to the top of the head tag. I think in 2018 there was a different css importing method in use, but even then I think this would be valuable for most users.

https://github.com/adazzle/react-data-grid/pull/2541
