### ISSUE TITLE
Row content disappears when trying to make table height dynamic

### ISSUE THREAD

**Issue by tigran-sedrakyan** [adazzle/react-data-grid#1135]
Hi, thanks for an awesome package!

So I'm trying to change table height, depending on the number of rows, so that the table will always have enough height to fit all the rows without overflowing. The problem is that when trying to do so, rows are being rendered, but they don't have the content they should have. There are only empty cells. If another render is called though, or page is resized, or some windows event is being fired, everything comes into its places and works just fine.

Was it designed to be like this? If not, is there any workaround?

**Comment by amanmahajan7** [comment]
This is a known issue where sometimes the cell content is empty. We are actively working on improving the [cell rendering logic](https://github.com/adazzle/react-data-grid/pull/1123) and v4 should address this issue. In the meantime re-rendering grid seems like a potential solution

```
onTableResize(() => {
   // Re-render grid
   // May be recalculate grid's minHeight
   const minHeight = ....;
   this.setState({ minHeight });
   // Or may be forceUpdate (not a huge fan of this approach)
   this.forceUpdate();
});
```

**Comment by amanmahajan7** [comment]
Closing in favor of #1087

**Comment by vellov** [comment]
This workaround is not working either
