### ISSUE TITLE
when set expanded property , it is not propogating to cellexpand in rdg

### ISSUE THREAD

**Issue by smurugesan2016** [adazzle/react-data-grid#1136]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™

Hi All ..i have an issue with react data grid
we have a react grid with group tree in it
so after add or remove value from the grid
we set the expanded property in state as false
this is honoured in the component
but this state is not propogating to the react-data-grid
meaning..these are the steps
1. add the value to the grid
2.the tree collapses
and sets the expanded state of the component to false
but the carat symbol from the grid stays the same
it will not go to the collapsed state
it is because this change is not propogating to the react cell expand event state

https://files.slack.com/files-pri/T4XV0NYS0-F9KPJELP3/image.png

But when i have 2 tree structure in the same grid..the second one is working as expected
https://files.slack.com/files-pri/T4XV0NYS0-F9MQ8F0CX/image.png

any thoughts please.

**Comment by smurugesan2016** [comment]
@amanmahajan7 i have the screen shot in the issue description. Let me know if u need anything more

**Comment by ranrao** [comment]
@amanmahajan7: I seem to have a similar issue. Did you find a workaround for the problem? Please share if you have a solution. Thanks much!
