### ISSUE TITLE
Context Menu Error(TypeError: Cannot read property 'contains' of undefined)

### ISSUE THREAD

**Issue by OmerAli** [adazzle/react-data-grid#1137]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [*] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [*] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ *] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details
current behavior:
On opening Context menu give errors
![image](https://user-images.githubusercontent.com/9985402/37335458-6887a386-26d0-11e8-824e-8049f99ab65c.png)

Kindly help me in solving. Thank You

**Comment by amanmahajan7** [comment]
`React 16` is not officially supported and some errors/warnings are expected. We are actively working [`v4`](https://github.com/adazzle/react-data-grid/tree/next) and it should fully support React 16. There is no set timeline at the moment but we are targeting next month. In the meantime you can use `react-data-grid@next` if you need immediate `React 16` support but this is still work in progress.

**Comment by OmerAli** [comment]
@amanmahajan7 Thank For your support will try the next version.

**Comment by qili26** [comment]
For context menu migration, please take a look at this [link](https://github.com/adazzle/react-data-grid/blob/master/migrations/v3-v4.md) if the context menu is not working.

Here is the example [link](https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid-examples/src/scripts/example18-context-menu.js). Just FYI, id must be set in the context menu.
