### ISSUE TITLE
How to stop/avoid lazy loading of react-data-grid ?

### ISSUE THREAD

**Issue by rahulchaubisa22** [adazzle/react-data-grid#1138]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [x] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

Hi Team,
     We are using react-data-grid for one of our project. In our grid, we may have record 100-200, by default my rows are rendering dynamically. Please tell me the parameter to stop auto rendering. 
I want to load my all rows onLoad itself into DOM instead of onScroll.

**Comment by rahulchaubisa22** [comment]
Aman, Can you please check and respond. It's little urgent for me.

**Comment by amanmahajan7** [comment]
I think you can change [`overScan`](https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid/src/ReactDataGrid.js#L138) to change the virtual scrolling window.

**Comment by amanmahajan7** [comment]
Closing this issue for good housekeeping. Feel free to reopen if you have any further questions.

**Comment by CharLee-ch** [comment]
@amanmahajan7    
If I don't want to use virtualization ，how to override overscan ? What is the meaning of the default prop oversan : {2,2,2,2} ?
