### ISSUE TITLE
export to excel or pdf?

### ISSUE THREAD

**Issue by ee7klt** [adazzle/react-data-grid#114]
is there currently a feature to export to excel or pdf? if not, can you give me some pointers as to which are the best practices for implementing such a feature? i'd like to contribute by incorporating those features in to this project.

**Comment by bakesteve** [comment]
Excel is a bit harder. Basically you have a few options, the easiest being to send html down to excel but with the appropriate headers. However, excels HTML rendering engine is fairly basic. So it makes exporting a grid like this pretty hard (ie it wont understand floated divs). 

Pdfs are a little easier in principal. We use a node based process internally that, basically, uses phantomJS, grabs a screenshot as an image, and then converts that to a pdf. BUt there are a bunch of other alternatives. 

One more fundamental issue, depending on your use case, is that the grid is designed to only render the rows in view. So if you have 1000 rows, we only show 20 (or whatever you have set for your viewport). Depending on what you are trying to achieve, that may not be correct.

In terms of adding this as a feature, I think it probably sits out of scope for the core library. But an add on to either render the rows and cells in Excel compatible html (basically `<tr>` and `<td>` and / or an add on that pushes out a pdf (ideally browser based, but not seen anything reliable there) would be something we'd consider

@malonecj @jpdriver chip in if anything you'd add here

**Comment by jpdriver** [comment]
for Excel it probably depends on whether or not you need the HTML markup in your resulting spreadsheet. IMO it makes more sense to get the rows from the grid state and pass that a JSON --> CSV converter.

I'm using the grid in a project where I'm doing that the other way (CSV --> React Data Grid) for initial data load so should be easy enough to do the other way, and there are lots of npm packages that do JSON <---> CSV.

for PDF's @bakesteve 's right -- PhantomJS is probably the easiest way to go. It actually natively supports rendering as a PDF (see http://phantomjs.org/screen-capture.html), though as mentioned you might need to fiddle with the styling to display rows beyond what the Viewport is currently rendering.

**Comment by zomars** [comment]
@jpdriver can you recommend a npm package for JSON to CSV? I'm also trying to export a generated table to CSV. Thanks you for any info that you could provide!
