### ISSUE TITLE
Issues identifying genuine bugs are closed without being fixed...

### ISSUE THREAD

**Issue by ianbale** [adazzle/react-data-grid#1142]
I've seen several issues raised by various people that identify genuine issues such as https://github.com/adazzle/react-data-grid/issues/1129 . In this case, Selectors incorrectly handles NULL value. Since NULL values are legitimate and commonplace, not handling them is clearly a bug and ought to be resolved in the Selectors code. 

There is a workaround, as you identified, of simply not using the provided Selectors code and writing your own. Whilst it is great that there is a workaround, using that as a reason to not fix the identified issue is not... After all, surely the point is to have a reusable component, not a component where you have the basics, but need to "roll your own" fixes for common issues with the most basic functionality.

It seems to be a general theme for this component, if there is a workaround for an issue, then that issue is not going to be fixed and the issue will, like https://github.com/adazzle/react-data-grid/issues/1129, simply be closed. Would you agree that this is a fair assessment?

It is an issue and ought to be fixed. I appreciate priorities, and maybe it needs to go into a low priority backlog, but simply closing it does not seem right. Very many users will have NULL values in their data. Surely it makes sense to fix this in one place rather than all those users writing their own code to handle them? That's why we all look for the best reusable components. If the issue was left open with PR then chances are, someone out there will fix the issue for you and provide the fix for you to include for everyone. That's not going to happen if you just close the issue.

We all appreciate the time and effort that people like yourself put into developing and maintaining these components, so please do not think this is a complaint as such. But it is important for users to know, before they invest in integrating a component into their app, that maintenance will always be limited only to bugs with no workaround. If there is any sort of workaround then they're on their own...

Having said all that, this is still a great component and you have done a great job! It is appreciated...even if requests to "make it perfect" seem to suggest otherwise.

**Comment by amanmahajan7** [comment]
Hi @ianbale I understand your concern and like we have acknowledged in the past there were some shortcomings on the management of this project in the last year. This has improved a lot and we are making good progress in resolving issues and moving the grid forward ([v4](https://github.com/adazzle/react-data-grid/tree/next))

Regarding #1129 I personally believe `Selectors.filterRows` should be deprecated as it does not handle all the cases and a quick search resulted in various _sorting_ related issues
#897 #846 #448

These all are valid issues but how the items are sorted or filtered should not be built into the grid or helpers. Again it is my own opinion. Having said that I am happy to reopen the issue as it is indeed a bug. Closing this issue for good house keeping.
