### ISSUE TITLE
On doubleClick show custom editor instead of custom formatter (need example)

### ISSUE THREAD

**Issue by igoriok1994** [adazzle/react-data-grid#1143]
- Have you already searched for similar issues? Please help us out and double-check first!
Yes, haven't found such example
- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [x] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details
Hi,

Have a good question, maybe somewhere exists similar issue (haven't found).

So, I have a custom formatter for a column ( it's icon formatter, that renders icon by value; 0 - no icon, 1 - check icon). I need to show custom editor on doubleClick.
Example:
I have a cell with icon formatter and on doubleClick i need to show checkbox editor to edit this cell.

So, with formatter i see that:
![image](https://user-images.githubusercontent.com/37294916/37587276-8a778d58-2b67-11e8-9e6f-3233978ed6eb.png)
But on cell doubleClick i should see something like that:
![image](https://user-images.githubusercontent.com/37294916/37587323-abd88e34-2b67-11e8-9094-3d7180daec2d.png)

Or I need to use 2 custom formatters? Any suggestions?
```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by madhan-dhamodaran** [comment]
I have raised a PR for this. Awaiting merge. #1449
