### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by grounzero** [adazzle/react-data-grid#1144]
I am looking for a dark theme.  Have been playing with the css but can only skin the mouse hover row when I set the cell background to none which gives a white background.

**Comment by amanmahajan7** [comment]
I do not think this is supported at the moment as react-data-grid does not publish a separate css file.

**Comment by GirishIITM** [comment]
I use thease classes to change themes

```
.rdg-cell {
    background-color: var(--color-bg);
    color: var(--color-text);
}

.rdg-row-even {
    background-color: var(--color-bg);
}

.rdg-row-odd {
    background-color: var(--color-bg);
}
```
