### ISSUE TITLE
Cell autofocus undesirable 

### ISSUE THREAD

**Issue by ChadRehmKineticData** [adazzle/react-data-grid#1146]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [x] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [X] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details
Steps to replicate:
Set up a table that is overflowed in the horizontal direction. 
Select a cell.
Using the horizontal scroll bar move to the other side of the table. 

Current Behavior:
Table refocuses onto the selected cell.  This creates a weird UX. 

![datagrid issue](https://user-images.githubusercontent.com/13987157/37852727-ae01174c-2eb1-11e8-8293-9fa89f49ef05.gif)
This is using a very basic DataGrid

![datagrid issue 2](https://user-images.githubusercontent.com/13987157/37852737-bc11354c-2eb1-11e8-98d5-45869d809b21.gif)
This is the effect in a full implementation.

Attempted Fixes:
Attempted to set enableCellSelect to false on the ReactDataGrid component and that didn't make a change.
Attempted to set cellAutoFocusEnabled to false on the ReactDataGrid component and that didn't make a change.

Desired behavior
Stop the table from "jumping" to the selected cell or have the DataGrid remove the ability to select a cell.

**Comment by amanmahajan7** [comment]
@ChadRehmKineticData I am not able to replicate this issue [here](http://adazzle.github.io/react-data-grid/#/examples/all-features). Can you create a [codesandbox ](https://codesandbox.io/) example.

**Comment by ChadRehmKineticData** [comment]
This behavior can be replicated on the datagrid demo page.  It does however require using a windows machine.  FYI: The machines I checked were using windows 10.  

Steps to replicate:
Make sure there is some horizontal scroll on the grid.
Select a cell that can be scrolled out of view.
Scroll the cell just out of view using the mouse.
Make sure mouse is still over the scroll bar. 
Release the mouse button.

![datagrid issue 3](https://user-images.githubusercontent.com/13987157/40443981-9ae01dfa-5e8d-11e8-93dd-3b84250f3018.gif)

I thought that the issue could be in this conditional:
https://github.com/adazzle/react-data-grid/blob/9b920bd89798a9d56b3b76eb5e07a21fb6b35441/packages/react-data-grid/src/Cell.js#L400

even if I have cellAutoFocusEnabled set to false the behavior still persists.

**Comment by ChadRehmKineticData** [comment]
Found some additional information.  If the scrollbar is manually clicked and dragged document.activeElement in Cell.js checkFocus method returns the container therefore the expression returns true.  

Normally scrollbars do not show on a Mac.  To replicate on a Mac set scrollbars to always show. https://support.apple.com/kb/ph25290?locale=en_US

**Comment by ChadRehmKineticData** [comment]
@amanmahajan7 can you please respond to this issue?  I have followed up on your last request.

**Comment by nwhitmont** [comment]
I ran into a similar issue with multiple tables on a page.  

When an item is selected in one table, sometimes it auto-highlights a table cell in a different table (blue square around table cell) and auto-scrolls the page to that table (not the one that was selected by user).

**Comment by CristianWorkGit** [comment]
@nwhitmont for your case `enableCellAutoFocus={false}` should work
