### ISSUE TITLE
Can't see the code of All-The-Features Grid

### ISSUE THREAD

**Issue by yellowfish1220** [adazzle/react-data-grid#115]
I've seen someone had raised this issue several months ago and the author had closed the issue. But I still can't see the code right now. Thanks for assistance.

**Comment by malonecj** [comment]
Thanks for that. I'll make sure that goes back into the example. For now you can see the code here 
https://github.com/adazzle/react-data-grid/blob/master/examples/scripts/example13-all-features.js

**Comment by malonecj** [comment]
Fiexed in this pull request https://github.com/adazzle/react-data-grid/pull/116
