### ISSUE TITLE
Add (or document) a way to programmatically select a cell

### ISSUE THREAD

**Issue by wibblymat** [adazzle/react-data-grid#1151]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [x] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

We have a feature that lets a user add a new row to a table. We would like for the user to immediately start editing that row without having to click it.

We can determine which row we just added, and we know the index of the first editable column. We would like to use this information to set which cell of the table has focus.

**Comment by spchuang** [comment]
is there currently a way to do this that isn't documented yet?

**Comment by wibblymat** [comment]
@spchuang The work around I used was to get a reference to the data grid and call `gridRef.setState({ selected: { rowIdx: row, idx: column } });`. Which is pretty awful, all things considered.

**Comment by spchuang** [comment]
I see. Yeah that is very hacky but I guess does the job

**Comment by Tarun-1994-Kumar** [comment]
Is there a way to select multiple cells like part of table
