### ISSUE TITLE
Documentation for Dummies. Yes, for Dummies

### ISSUE THREAD

**Issue by melinabering** [adazzle/react-data-grid#1155]
I am new to React, and need exactly one of the grids that you have created : "Custom Filter", but for the love of God, I can not get it to work. The documentation is so foreign to me, and most likely to many who are new to react. Would you happen to have better/easier documentation, or possibly a quick Youtube tutorial or something? That would be great.

**Comment by SteveAquino** [comment]
I second this, there is a serious lack of useful documentation.  For example there is a document for the `<DateRangeFilter />` component, but it doesn't actually show you how to implement it and it's mysteriously missing from the examples.

**Comment by Ben-CA** [comment]
Currently there's the Readme:
https://github.com/adazzle/react-data-grid/blob/main/README.md

The examples:
https://adazzle.github.io/react-data-grid/#/CommonFeatures

And the code behind the examples:
https://github.com/adazzle/react-data-grid/blob/main/website/routes/AllFeatures.lazy.tsx

It appears an effort is being made to improve this:
https://github.com/adazzle/react-data-grid/issues/2575
