### ISSUE TITLE
There's no "Jump to source" file under the Programmatic Scrolling Example.

### ISSUE THREAD

**Issue by Agri** [adazzle/react-data-grid#1159]
https://adazzle.github.io/react-data-grid/scripts/example27-scroll-to-row-index.js

goes to 404 :(

**Comment by amanmahajan7** [comment]
It is a typo, you can access the code at
https://adazzle.github.io/react-data-grid/scripts/example28-scroll-to-row-index.js

**Comment by Agri** [comment]
Thank you very much :) very usefull! May this issue be open till fixed on your site :)
