### ISSUE TITLE
Module "react-data-grid" has no exported member ReactDataGrid

### ISSUE THREAD

**Issue by shilpikanade** [adazzle/react-data-grid#1160]
Hello -

When I import ReactDataGrid (import { ReactDataGrid } from 'react-data-grid')

 I get the following error

Module "react-data-grid" has no exported member ReactDataGrid

Thanks, Shilpi

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [x ] Edge
- [ ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x ] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by kevyu** [comment]
```js
import  ReactDataGrid  from 'react-data-grid'
```

**Comment by shilpikanade** [comment]
Module "react-data-grid" doesn't have any default export. Same error. I am using React(16.3.0).

And also I had to install @types/react-data-grid, which wasn't in the documentation so I am not sure why.

**Comment by amanmahajan7** [comment]
Closing this issue due to lack of examples. Please create a new issue if you are still facing this issue
