### ISSUE TITLE
There is no documentation on the schema of the columns parameter

### ISSUE THREAD

**Issue by Narvey** [adazzle/react-data-grid#1166]
Please document the columns parameter to ReactDataGrid. Its usage is scattered all over your source code so I can't figure it out that way.

In particular, I want to know whether the (undocumented, except in examples) "width" property has to be a number, or if it can be something like "auto" to fill up available room.

But document the whole thing.

**Comment by rorysedgwick** [comment]
Agreed with @Narvey, I'm particularly interested in being able to give percentage widths to each column, so they can be varying in size but also responsive on browser window resize. This may be possible, but at the moment I can't find if it is/isn't from the documentation

**Comment by qili26** [comment]
if you are using typescript. I think this could be a good resource to serve as a "document" (I know it's not comprehensive yet)
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-data-grid/index.d.ts
