### ISSUE TITLE
resize doesn't work, neither do your jsfiddles

### ISSUE THREAD

**Issue by Narvey** [adazzle/react-data-grid#1167]
### Which version of React JS are you using?

✅ Officially supported ✅
- [x] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [x] Edge
- [ ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [x] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

In general, your error handling is terrible. You can tell this by leaving out one of the required props on ReactDataGrid. This should throw an error about the prop being required, but instead it just returns undefined or throws a more obscure error.

But now to this specific error, if you try to import react-data-grid from a .tsx file, the calling (tsx) component will return undefined. 

repro: https://codesandbox.io/s/41qr1j400

Note how that exact same code [works in js](https://codesandbox.io/s/73z2zz5v90).

EDIT: nm about the tsx distinction, the import should have been `import * as DataGrid from 'react-data-grid'` instead of `import DataGrid from 'react-data-grid'`.

**Comment by Narvey** [comment]
Also note that not even your own jsfiddles work.  Bleh! 🤮
(for instance, https://jsfiddle.net/k7tfnw1n/2/)

**Comment by Narvey** [comment]
OK, original issue is no longer a problem, the poor error handling and the two comments with confused reaction still are issues.

**Comment by amanmahajan7** [comment]
Seem like the original issue has been [resolved](https://github.com/adazzle/react-data-grid/issues/1178#issuecomment-384347720). If there are more issues please open a separate issue.
