### ISSUE TITLE
Next Major Release

### ISSUE THREAD

**Issue by madhan-dhamodaran** [adazzle/react-data-grid#1170]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```
Hi All,
@malonecj @diogofcunha @willgates @JamesPortelli @bakesteve @richardware

Just trying to see when you have planned to have a next major release and if you have any road maps on what is planned for the future. Kindly share this information so that we can plan our development activities accordingly .

Appreciate your swift response in advance.

Thanks,
Madhan

**Comment by amanmahajan7** [comment]
Hi @madhan-dhamodaran, we are currently working on it and you can expect the next major release by the end of next week. We will also share the roadmap with the community soon.

Thanks.

**Comment by xiongchen2012** [comment]
awesome , anticipated

**Comment by amanmahajan7** [comment]
We just published the next major release with `React-16` support.

**Comment by amanmahajan7** [comment]
Closing this issue for good housekeeping.
