### ISSUE TITLE
Need sorting column and sorting direction bydefault

### ISSUE THREAD

**Issue by rahulchaubisa22** [adazzle/react-data-grid#1175]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

Team,
      Please help me with below query.
I am using react-data-grid for my project, need to implement sorting at load time itself, not to wait for click. I tried giving sortColumn and sortDirection as props to react-data-grid, but seems its not working. 
Any thoughts.

**Comment by amanmahajan7** [comment]
@rahulchaubisa22 `RDG` does not contain sorting logic and setting `sortColumn` and `sortDirection` will not sort the data. You also need to sort rows manually before it is passed to the grid. You can easily achieve it when you set the initial state (assumings rows are store in a state). In this [example](https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid-examples/src/scripts/example08-sortable-cols.js#L54), you need to call something like this 

```
constructor(props, context) {
 ....
    this.state = { originalRows, rows: sortRows(rows) }
```

**Comment by amanmahajan7** [comment]
Closing this issue for good house keeping.
