### ISSUE TITLE
Cell id or cell metadata inside formatter

### ISSUE THREAD

**Issue by igoriok1994** [adazzle/react-data-grid#1177]
- Have you already searched for similar issues? Please help us out and double-check first!
Yes
- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [x] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details
Hi, i'm trying to get cell ID inside formatter. I have column object, row id, but there no cell id. How can I get it inside my custom cell formatter?
![image](https://user-images.githubusercontent.com/37294916/39230538-7fb5b488-486f-11e8-8b13-6cd744037d76.png)

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by amanmahajan7** [comment]
@igoriok1994 can you elaborate your question. What do you mean by cell id? I think `row` and `column` should provide all the data a `formatter` may need.
