### ISSUE TITLE
Prop `rowSelection` and `enableRowSelect` are creating error.

### ISSUE THREAD

**Issue by rupav** [adazzle/react-data-grid#1180]
- Have you already searched for similar issues? Please help us out and double-check first!
yes.

- Also, please don't be that person who deletes this template. It's here for a reason.
- Thanks!

---

### Which version of React JS are you using?
15.1.0 (checked using React.version)

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?
Firefox, on Ubuntu VM

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

---

### Issue Details
using **rowSelection** property in ReactDataGrid component is creating error, since the opensource project is using webpack to bundle the js files, console error is giving `r.props.renderer is not a function` error, pointing to a line n bundle.min.js which is hard to debugged. But having removed this prop (`rowSelection`) from the component, I am not seeing any error.
Similar goes with `enableRowSelect="multi"` prop, its creating same error too.

As suggested in #1172 , I updated `react-data-grid` and `react-data-grid-addons` to `4.0.7` version from the earlier `3.0.3`.

Here's the dependencies in package.json for the project:
```
"devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "concurrently": "^3.5.1",
    "dotenv": "^4.0.0",
    "json-loader": "^0.5.7",
    "npm-check-updates": "^2.13.0",
    "react-hot-loader": "^3.1.3",
    "uglifyjs-webpack-plugin": "^1.1.4",
    "webpack": "^3.10.0",
    "webpack-jarvis": "^0.1.1"
  },
  "dependencies": {
    "axios": "^0.17.1",
    "classnames": "^2.2.5",
    "create-react-class": "^15.6.2",
    "fuse.js": "^3.2.0",
    "jsonwebtoken": "^8.1.0",
    "lodash.clonedeep": "^4.5.0",
    "lodash.isequal": "^4.5.0",
    "node-sass": "^4.7.2",
    "preact": "^8.2.7",
    "preact-compat": "^3.17.0",
    "prop-types": "^15.6.0",
    "react-data-grid": "^3.0.3",
    "react-data-grid-addons": "^3.0.3",
    "react-docgen": "^2.20.1",
    "react-redux": "^5.0.6",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "react-select": "^1.1.0",
    "react-sortable-hoc": "^0.6.8",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.2.0",
    "shortid": "^2.2.8",
    "socket.io": "^2.0.4",
    "store": "^2.0.12"
  }
```

**Code being used:**
```
<ReactDataGrid
             enableCellSelect={true}
                      columns={props.columns}
                    rowGetter={(index) => { return props.rows[index] }}
                    rowsCount={props.rows.length}
                 rowSelection={{
                  showCheckbox: true,
                   enableShiftSelect: true,
                      onRowsSelected: (rows) => {
                        rows.forEach((meta)  => {
                          const action = row.select(meta.rowIdx, meta.row)

                          props.dispatch(action)
                        })
                      },
                    onRowsDeselected: (rows) => {
                      rows.forEach((meta)  => {
                        const action = row.deselect(meta.rowIdx, meta.row)

                        props.dispatch(action)
                      })
                    },
                            selectBy: { isSelectedKey: 'selected' }
                 }}
            onGridRowsUpdated={({ fromRow, toRow, updated }) => {
              const action = row.update(fromRow, toRow, updated)

              props.dispatch(action)

              props.onChange({ columns: props.columns, rows: props.rows })
            }}/>
```

**Comment by rupav** [comment]
@amanmahajan7

**Comment by rupav** [comment]
Will try to reproduce this today, post it ASAP. 👍

**Comment by amanmahajan7** [comment]
Thank you for confirming! Closing this issue.
