### ISSUE TITLE
Populating Dropdown Values for multi-select

### ISSUE THREAD

**Issue by madhan-dhamodaran** [adazzle/react-data-grid#1181]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```
@amanmahajan7 @rozeskjm @azu 

Hi All,

I have question regarding populating values for the multiselect filter dropdown. The example shows that we are deriving the dropdown values from the data available in the grid. I am able to supply data from the server and get populate values for the dropdown. However, I want to know if in case I need to load thousands of dropdown values, I want to find out if the grid supports when I make a server call once I enter something in the multi-select filter and get matching results and populate only those as dropdown values for that filter. 

Something like a typeAhead filter. 

Kindly advise. 

Thanks,
Madhan

**Comment by amanmahajan7** [comment]
`React Data Grid` filters are quite flexible and creating a typehead filter should be doable. A good starting point is [`AutoCompleteFilter`](https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid-addons/src/cells/headerCells/filters/AutoCompleteFilter.js#L9). All a filter needs to do is call [`props.onChange`](https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid-addons/src/cells/headerCells/filters/AutoCompleteFilter.js#L63) when a new value is selected. This in turn triggers [`onAddFilter`](https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid-examples/src/scripts/example22-custom-filters.js#L118) with new updated filter.

`RDG` is not concerned with how filters load data. You can probably load data on `componentDidMount` and when a value is selected call `props.onChange`

**Comment by madhan-dhamodaran** [comment]
@amanmahajan7,

I have finished adding this and ready to raise a PR. I have been trying to get in touch with a you guys through email, slack etc., but in vain. I have added one more feature as well for customizable columns. I will raise a new issue for that. 

Not sure how to reopen this issue. But, this issue is valid and I will be raising a PR before this weekend

**Comment by madhan-dhamodaran** [comment]
All, 

I am still working on this. I will raise a PR ASAP

Thanks,
Madhan

**Comment by madhan-dhamodaran** [comment]
All,

I am still working on this. I will raise a PR ASAP

Thanks,
Madhan

**Comment by madhan-dhamodaran** [comment]
All,

I am still working on this. I will raise a PR ASAP

Thanks,
Madhan

**Comment by madhan-dhamodaran** [comment]
All,

I am still working on this. I will raise a PR ASAP

Thanks,
Madhan

**Comment by diegohoyola** [comment]
I am having this issue also, can you tell me if the issue has been fixed?

**Comment by madhan-dhamodaran** [comment]
I have raised a PR for this. Awaiting merge. #1449

**Comment by madhan-dhamodaran** [comment]
I have raised a PR for this. Awaiting merge. #1449

**Comment by madhan-dhamodaran** [comment]
I have raised a PR for this. Awaiting merge. #1449

**Comment by madhan-dhamodaran** [comment]
I have raised a PR for this. Awaiting merge. #1449

**Comment by amanmahajan7** [comment]
Starting v7 we are removing any concrete implementations for filters, editors or formatters. We will also remove the `react-data-grid-addons` package. This was done so users can create their own implementations and tweak it however they like. I would recommend coping Typeahead filter in your local repo

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/HeaderFilters.tsx
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--header-filters
