### ISSUE TITLE
Resizable Columns?

### ISSUE THREAD

**Issue by Haemoglobin** [adazzle/react-data-grid#119]
The resizable columns example does not work for me?  
http://adazzle.github.io/react-data-grid/examples.html#/resizable  

Hovering over the column divider in the header does not allow me to resize the columns. Is it done another way?

**Comment by jpdriver** [comment]
hey there @Haemoglobin, it looks like we're missing that missing the `react-grid-HeaderCell__draggable` class the component wants :-1:

i'll have a look at that and get it updated, but in the meantime the draggable components are actually there and work correctly. just click and drag near the right edge of the header cell :smile:
