### ISSUE TITLE
Can't resolve 'react-data-grid' in .tsx file

### ISSUE THREAD

**Issue by AOFind** [adazzle/react-data-grid#1190]
I am implementing react-data-grid in .tsx file but get the error "ERROR in ./ClientApp/components/Grid.tsx
    Module not found: Error: Can't resolve 'react-data-grid' in 'ProjectWeb\ClientApp\components'
     @ ./ClientApp/components/Grid.tsx 13:0-49
     @ ./ClientApp/components/Home.tsx
     @ ./ClientApp/routes.tsx
     @ ./ClientApp/boot-server.tsx
npm ERR! code ELIFECYCLE
npm ERR! errno 2"
 when running the code.

The code is as below.

import * as React from 'react';
import * as ReactDataGrid from 'react-data-grid';

export class Example extends React.Component {
    public render() {
        
        const columns = [{ key: 'id', name: 'ID' }, { key: 'title', name: 'Title' }];
        const rows = [{ id: 1, title: 'Title 1' }];
        const rowGetter = (rowNumber:number) => rows[rowNumber];
        const GridRet = () => {
             return <ReactDataGrid
                columns={columns}
                rowGetter={rowGetter}
                rowsCount={rows.length}
                minHeight={500} />;
        }

        const myVariable = GridRet();
        return <div>Hello guys {GridRet()} </div>;
    }

}

export const GridSample = Example;
export default GridSample;

**Comment by Rohit0510** [comment]
> Got the issue fixed. The problem was that i was just installing "types/react-data-grid" for tsx file and forgot to install react-data-grid for js file support. It worked when i got both the packages installed. Thanks

**Comment by Rohit0510** [comment]
Can you please explain in detail how can you resolve this issue
I have tried to install this package by following command
npm install --save @types/react-data-grid and facing the following error
Failed to load component "f4783611-9758-4073-be66-aa3ef9a23312" (HelloWorldWebPart). Original error: ***Failed to load entry point from component "f4783611-9758-4073-be66-aa3ef9a23312" (HelloWorldWebPart). Original error: Cannot find module 'react-data-grid'
