### ISSUE TITLE
Dymanic options in DropDownEditor

### ISSUE THREAD

**Issue by mdanielcristian** [adazzle/react-data-grid#1191]
### Which version of React JS are you using?

15.6.1

### Which browser are you using?

all

### I'm submitting a ...

- [ ] 🐛 Bug Report

### Issue Details

Please include:
- What the current behavior is: <DropDownEditor options={this.state.arrayOfStrings} />, arrayOfStrings changes, but the options do not change in the UI
- What the desired behvaior is: reload the ddl options if they change

I've also tried to have the grid columns defined on the state, and change the columns on the state when the options should change, still doesn't work.

**Comment by amanmahajan7** [comment]
This is not a grid specific feature, you can customize the editor however you want. You can potentially load custom options in `componentDidMount` lifecyle hook.
