### ISSUE TITLE
How to have a different editing cell value from display cell value?

### ISSUE THREAD

**Issue by rjdecilos** [adazzle/react-data-grid#1196]
I just want to know if there are any ways to do this, because I'm using the grid in the same behavior as an excel sheet. Whenever I put a formula such as "=SUM(A1:B1)" I'll be displaying the value of the sum of the cells, but when I'm going to edit it I'll display the value as "=SUM(A1:B1)". I hope there is such way. Thank you!

**Comment by amanmahajan7** [comment]
You can probably use a custom formatter which can read the formula `=SUM(A1:B1)` and display the calculated value. The editor would just work because it is just displaying the formula. I think a combination of formatter and editor can achieve this result.
