### ISSUE TITLE
DateRangeFilter

### ISSUE THREAD

**Issue by firdausmaarof** [adazzle/react-data-grid#1201]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

Hi,

I just want to know, how to use the DateRangeFilter? I cannot find any documentation on how to use it. Please help. Thanks.

**Comment by SteveAquino** [comment]
I had the same question, I don't think it's actually implemented/exported in the final code.  I wound up implementing my own component.

**Comment by jeznag** [comment]
Seems like you'd need a filterValues function as well:

```

  filterValues = (row, columnFilter, columnKey) => {
    if (columnFilter.filterTerm == null) {
      return true;
    }

    const actualValue = asDate(row[columnKey]);
    const filterStartDate = asDate(columnFilter.filterTerm.startDate);
    const filterEndDate = asDate(columnFilter.filterTerm.endDate);

    return (
      actualValue >= filterStartDate &&
      actualValue <= filterEndDate
    );
  };
```

and adjusted onSubmit:
```
 onSubmit = event => {
    event.preventDefault();

    const { startDate, endDate } = this.state;

    if (!this.isDisabled()) {
      this.setState({ isOpen: false });
      this.props.onChange({
        filterTerm: { startDate, endDate },
        column: this.props.column,
        filterValues: this.filterValues
      });
    }
  };
```

**Comment by drewboardman** [comment]
So is it not implemented?
