### ISSUE TITLE
How to adjust long data in cell?

### ISSUE THREAD

**Issue by nskiro** [adazzle/react-data-grid#1202]
I started using react-data-grid and i noticed that the row heights aren't adjusting when i have a cell with lots of text. The text just gets cut-off. how do i solve this?

Example: say i have text that states "this is a test of long data" then it displays like this...

|-----------------|
|this is a test of |
|-----------------|
Yes, i could make my column wider but in reality i have item descriptions that are 50 words, more or less, that i want to display in a column and so i'd expect the row to be higher and the text to wrap like so...

|-----------------|
|this is a test of |
|long data         |
|-----------------|

**Comment by amanmahajan7** [comment]
@nskiro you should be able to use [`rowHeight` prop](https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid/src/ReactDataGrid.js#L54) to adjust the row height. The default row height is `35`. React data grid does not allow dynamic row heights at the moment.

**Comment by ymihir** [comment]
Any update on this? it is really essential feature. Example: Comments column usually have text in multiple rows, how to fix such kind of scenarios
