### ISSUE TITLE
Typing in the textbox of a locked and filterable header causes the header to shift

### ISSUE THREAD

**Issue by mjosh954** [adazzle/react-data-grid#1204]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [x] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [x] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
We started using your grid in our product and our QA team has identified an interesting issue with the grid in Firefox. When column has locked, resizable, sortable and filterable set to true, the locked column starts scrolling right after typing outside the range of the text box. When I remove the locked property of the column, the header doesn't move after typing outside the range of the text box. Was able to reproduce it in example09-filterable-grid.js in the grid repo.

- What the desired behvaior is
The header should be fixed and not move. 

- (If Bug) Steps to reproduce the issue
Set the column to locked, resizable, sortable and filterable.

- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

![image](https://user-images.githubusercontent.com/5446572/40432275-eb5e15da-5e6e-11e8-841c-05c620101b07.png)

**Comment by monish001** [comment]
Hello stale bot and team, this is a valid issue. Please add this to the roadmap.
