### ISSUE TITLE
how re render component when state update

### ISSUE THREAD

**Issue by Deboracgs** [adazzle/react-data-grid#1206]
Hey Guys,

I create component ListTableComponent, and used in my page UserFormComponent

I put an add button, which when I click opens a modal with the fields, and when saving updates the state of the table, however, the table is not updating automatically, it follows the code.

`import React, { Component } from 'react';
import { connect } from 'react-redux';
import IntlMessages from './../../util/IntlMessages';
import ReactDataGrid from 'react-data-grid';
const { Toolbar, Data: { Selectors } } = require('react-data-grid-addons');

class ListTableComponent extends React.PureComponent {

    constructor(props, context) {
        super(props, context);

        this.state = { rows: props.rows, filters: {}, sortColumn: null, sortDirection: null };
    }
    re

    static getDerivedStateFromProps(nextProps, prevState) {
        console.log("getDerivedStateFromProps", nextProps.rows, prevState);
        if(nextProps.rows.length > 0){
            return {
                rows: nextProps.rows
            }
        }
        return null;
    }

    getRows = () => {
        console.log("getRows", this.state);
        return Selectors.getRows(this.state);
    };

    getSize = () => {
        return this.getRows().length;
    };

    rowGetter = (rowIdx) => {
        const rows = this.getRows();
        return rows[rowIdx];
    };

    handleGridSort = (sortColumn, sortDirection) => {
        this.setState({ sortColumn: sortColumn, sortDirection: sortDirection });
    };

    handleFilterChange = (filter) => {
        let newFilters = Object.assign({}, this.state.filters);
        if (filter.filterTerm) {
            newFilters[filter.column.key] = filter;
        } else {
            delete newFilters[filter.column.key];
        }

        this.setState({ filters: newFilters });
    };

    onClearFilters = () => {
        this.setState({ filters: {} });
    };

    onKeyDown = (e) => {
        if (e.ctrlKey && e.keyCode === 65) {
            e.preventDefault();

            let rows = [];
            this.state.rows.forEach((r) => {
                rows.push(Object.assign({}, r, { isSelected: true }));
            });

            this.setState({ rows });
        }
    };

    onRowClick = (rowIdx, row) => {
        let rows = this.state.rows.slice();
        rows[rowIdx] = Object.assign({}, row );
        this.setState({ rows });
    };

    getCellActions(column, row) {

        if (column.key === 'buttons') {
            return [
                {
                    icon: 'fa fa-eye',
                    callback: () => { this.props.form(row.id) }
                }
            ];
        }
    }

    handleGridRowsUpdated = ({ fromRow, toRow, updated }) => {
        let rows = this.state.rows.slice();

        console.log("rows handle > ", rows);

        for (let i = fromRow; i <= toRow; i++) {
            let rowToUpdate = rows[i];
            let updatedRow = update(rowToUpdate, { $merge: updated });
            rows[i] = updatedRow;
        }

        this.setState({ rows });
    };

    render() {
        return (
            <div className="form-container">
                <ReactDataGrid
                    onGridSort={this.handleGridSort}
                    enableCellSelect={true}
                    columns={this.props.columns}
                    rowGetter={this.rowGetter}
                    rowsCount={this.getSize()}
                    minHeight={500}
                    onGridRowsUpdated={this.handleGridRowsUpdated}
                    toolbar={<Toolbar enableFilter={true} />}
                    onAddFilter={this.handleFilterChange}
                    getCellActions={this.getCellActions.bind(this)}
                    onRowClick={this.onRowClick}
                    onClearFilters={this.onClearFilters} />
            </div>
                    
        );
    }
}

export default connect(null, {
})(ListTableComponent);`

`import React, { Component } from 'react';
import { connect } from 'react-redux';
import PageTitleBar from '../../../../components/PageTitleBar/PageTitleBar';
import IntlMessages from './../../../../util/IntlMessages';
import { FormGroup, Input, Form, Label, Col, InputGroup, InputGroupAddon } from 'reactstrap';
import Toggle from 'react-toggle'
import {RctCard} from './../../../../components/RctCard';
import AppBar from 'material-ui/AppBar';
import Tabs, { Tab } from 'material-ui/Tabs';
import Typography from 'material-ui/Typography';
import Button from 'material-ui/Button';
import Dialog, {
    DialogActions,
    DialogContent,
    DialogContentText,
    DialogTitle,
} from 'material-ui/Dialog';
import TextField from 'material-ui/TextField';
import {
    getUserAPI,
    saveUserAPI,
    removeUserAPI,
    getAccountsAPI,
    getInfosAPI,
    getGroupsAPI
} from './../../../../actions';
import RctPageLoader from './../../../../components/RctPageLoader/RctPageLoader';
import FormComponent from './../../../../components/Form';
import AutoCompleteComponent from './../../../../components/Input/AutoComplete';
import ListTableComponent from './../../../../components/ListTable';

function TabContainer(props) {
    return (
        <Typography component="div" style={{ padding: 8 * 3 }}>
            {props.children}
        </Typography>
    );
}

class UserFormComponent extends Component  {

    constructor(props){
        super(props);

        const { match: { params }, user, loading, emptyUser, mode} = this.props;

        const INITIAL_STATE = {
            id: 0,
            name: '',
            email: '',
            active: true,
            created_at: null,
            created_by: null,
            updated_by: null,
            updated_at: null,
            role: 1,
            password: null,
            account_id: 0,
            infos: [],
            groups: []
        }

        this._columnsInfos = [
            {
                key: 'description',
                name: <IntlMessages id="label.description" />,
                filterable: true,
                sortable: true,
                resizable: true
            },
            {
                key: 'value',
                name: <IntlMessages id="label.value" />,
                filterable: true,
                sortable: true,
                resizable: true
            }
        ];

        this._columnsUserGroups = [
            {
                key: 'description',
                name: <IntlMessages id="label.description" />,
                filterable: true,
                sortable: true,
                resizable: true
            }
        ];
        
        this.state = {
            user: INITIAL_STATE,
            id: params.id,
            activeTab: 0,
            disabledFields: (params.id != undefined ? true : false),
            mode: (params.id != undefined ? 'edit' : 'new'),
            accounts: [],
            infos: [],
            columnsInfos: this._columnsInfos,
            groups: [],
            columnsUserGroups: this._columnsUserGroups,
            modalInformation: false

        }
        
        if (this.state.id != undefined) {
            this.props.getUserAPI(this.state.id);
        }

        this.props.getAccountsAPI();
        this.props.getInfosAPI();
        this.props.getGroupsAPI();
    }

    static getDerivedStateFromProps(nextProps, prevState) {
        
        if (nextProps.match.params.id != undefined) {
            return {
                user: nextProps.user,
                id: nextProps.match.params.id,
                accounts: nextProps.accounts,
                infos: nextProps.infos,
                groups: nextProps.groups,
                mode: "edit"

            };
        }
        return {
            accounts: nextProps.accounts,
            infos: nextProps.infos,
            groups: nextProps.groups,
            mode: "new"
        };
    }

    handleChangeTab = (event, value) => {
        this.setState({ activeTab: value });
    }

    handleChangeUserInputs = (propertyName, event) => {
        const user = this.state.user;
        user[propertyName] = event.target != undefined ? event.target.value : event ;
        this.setState({ user: user});
    }

    renderPasswordField(){
        if (this.state.id == undefined) {
            return (
                <FormGroup row>
                    <Label for="password" sm={3}><IntlMessages id="label.password" /></Label>
                    <Col sm={9}>
                        <Input type="password" className="input-lg"
                            value={this.state.user.password}
                            disabled={this.state.disabledFields}
                            onChange={this.handleChangeUserInputs.bind(this, 'password')}
                        />
                    </Col>
                </FormGroup>
            )
        }

    }

    renderDetails(){
            return (
                <div>
                    <FormGroup row>
                        <Label for="id" sm={1}><IntlMessages id="label.id" /></Label>
                        <Col sm={2}>
                            <Input type="text" className="input-lg"
                                onChange={this.handleChangeUserInputs.bind(this, 'id')}
                                value={this.state.user.id}
                                disabled={true}
                            />
                        </Col>
                    </FormGroup>
                    <FormGroup row>
                        <Label for="name" sm={3}><IntlMessages id="label.name" /></Label>
                        <Col sm={9}>
                            <Input type="text" className="input-lg" 
                                onChange={this.handleChangeUserInputs.bind(this, 'name')}
                                value={this.state.user.name}
                                disabled={this.state.disabledFields}
                                maxLength="50"
                            />
                        </Col>
                    </FormGroup>
                    <FormGroup row>
                        <Label for="email" sm={3}><IntlMessages id="label.email"  /></Label>
                        <Col sm={9}>
                            <Input type="text" className="input-lg" 
                                value={this.state.user.email}
                                disabled={this.state.disabledFields}
                                onChange={this.handleChangeUserInputs.bind(this, 'email')}
                            />
                        </Col>
                    </FormGroup>

                    {this.renderPasswordField()}

                    <FormGroup row>
                        <Label for="id" sm={1}><IntlMessages id="label.account" /></Label>
                        <Col sm={2}>
                            <AutoCompleteComponent 
                                multi={false}
                                onChange={(value) => { return this.handleChangeUserInputs('account_id', value)}}
                                value={this.state.user.account_id}
                                disabled={this.state.disabledFields}
                                suggestion={this.state.accounts}
                                arrValue="id"
                                arrLabel="description"
                            />
                    
                        </Col>
                    </FormGroup>
                   
                    <FormGroup row>
                        <Label for="active" sm={3}><IntlMessages id="label.active" /></Label>
                        <Col sm={9}>
                            <Toggle
                                disabled={this.state.disabledFields}
                                icons={false}
                                onChange={this.handleChangeUserInputs.bind(this, 'active')}
                                value={this.state.user.active == 1 ? "true" : "false"}
                                defaultChecked={this.state.user.active == 1 ? true : false}
                            />
                        </Col>
                    </FormGroup>
                </div>
            )

    }

    showModalInformation(condition =  false){
        this.setState({
            modalInformation: condition
        })
    }

    addInfoToUser(info){
        let infos = this.state.user.infos;
        infos.push(info);
        this.setState({
            users: {
                infos: infos
            }
        });
        this.showModalInformation(false);
    }

    renderInformations() {
        let info = {
            infoId: null,
            value: null,
            description: null
        };
        console.log("infos < ", this.state.user.infos);
        return (
            <div>
                <Button onClick={() => this.showModalInformation(true)}>
                    <IntlMessages id="button.add" />
                </Button>
                <ListTableComponent
                    columns={this.state.columnsInfos}
                    rows={this.state.user.infos}
                />
                <Dialog
                    open={this.state.modalInformation}
                    onClose={() => this.showModalInformation(false)}
                    aria-labelledby="form-dialog-title"
                    fullWidth    
                >
                    <DialogTitle id="form-dialog-title">
                        <IntlMessages id="addInformation" />
                    </DialogTitle>
                    <DialogContent>
                        <FormGroup row>
                            <Label for="id" sm={2}><IntlMessages id="label.information" /></Label>
                            <Col sm={10}>
                                <AutoCompleteComponent
                                    multi={false}
                                    value={info.infoId}
                                    disabled={this.state.disabledFields}
                                    suggestion={this.state.infos}
                                    onChange={(event) => { info = { infoId: event.value, description: event.label }; }}
                                    arrValue="id"
                                    arrLabel="description"
                                />

                            </Col>
                        </FormGroup>

                        <FormGroup row>
                            <Label for="id" sm={2}><IntlMessages id="label.value" /></Label>
                            <Col sm={10}>
                                <Input type="text" className="input-lg"
                                    value={info.value}
                                    disabled={this.state.disabledFields}
                                    onChange={(event) => { info.value = event.target.value}}
                                />

                            </Col>
                        </FormGroup>
                        
                    </DialogContent>
                    <DialogActions>
                        <Button variant="raised" onClick={() => this.showModalInformation(false)} className="btn-danger text-white">
                            <IntlMessages id="button.cancel" />
                        </Button>
                        <Button variant="raised" onClick={() => this.addInfoToUser(info)} color="primary" className="text-white">
                            <IntlMessages id="button.add" />
                        </Button>
                    </DialogActions>

                </Dialog>
            </div>
        )
    }

    renderSecurity() {
        return (
            <div>
            </div>
        )
    }

    renderUserGroup() {
        return (
            <div>
                <ListTableComponent
                    columns={this.state.columnsUserGroups}
                    rows={this.state.user.groups}
                />
            </div>
        )
    }
    renderTitleBar(){
        let title = <IntlMessages id="newUser" />
        if (this.state.id != undefined) {
            title = this.state.user.name
        }
        return <PageTitleBar title={title} match={this.props.match} />
    }

    disabledFields(condition){
        this.setState({
            disabledFields: condition
        })
    }

    onSave(){
        this.props.saveUserAPI(this.state.user, this.props.history);
    }

    onRemove() {
        this.props.removeUserAPI(this.state.id, this.props.history);
    }

    render() {
        const { activeTab } = this.state;
        const { loading, user } = this.props;
        
        if(loading == false){
            return (
                <div className="user-list-wrapper">
                    {this.renderTitleBar()}

                    <FormComponent
                        disabledFields={this.disabledFields.bind(this)}
                        onSave={this.onSave.bind(this)}
                        onRemove={this.onRemove.bind(this)}
                        mode={this.state.mode}
                    >
                        
                            <div className="rct-tabs">
                                <AppBar position="static">
                                    <Tabs value={activeTab} onChange={this.handleChangeTab} scrollable scrollButtons="off">
                                        <Tab icon={<i className="ti-user"></i>} label={<IntlMessages id="details" />} />
                                        <Tab icon={<i className="ti-info"></i>} label={<IntlMessages id="informations" />} />
                                        <Tab icon={<i className="ti-layers-alt"></i>} label={<IntlMessages id="userGroup" />} />
                                        { this.state.id != undefined && <Tab icon={<i className="ti-lock"></i>} label={<IntlMessages id="security" />} /> }
                                    </Tabs>
                                </AppBar>
                                {activeTab === 0 &&
                                    <TabContainer>
                                        {this.renderDetails()}
                                    </TabContainer>}
                                {activeTab === 1 &&
                                    <TabContainer>
                                        {this.renderInformations()}
                                    </TabContainer>}
                                {activeTab === 2 &&
                                    <TabContainer>
                                        {this.renderUserGroup()}
                                    </TabContainer>}
                                {activeTab === 3 &&
                                    <TabContainer>
                                        {this.renderSecurity()}
                                    </TabContainer>}
                            </div>
                            
                    </FormComponent>
                </div>
            );     

        }else{
            return <RctPageLoader />
        }
    }
}

// map state to props
const mapStateToProps = ({ userAPI, accountAPI, infoAPI, groupAPI }) => {
    const { loading, user, mode } = userAPI;
    const { accounts } = accountAPI;
    const { infos } = infoAPI;
    const { groups } = groupAPI;
    return { loading, user, mode, accounts, infos, groups};
}

export default connect(mapStateToProps, {
    getUserAPI,
    saveUserAPI,
    removeUserAPI,
    getAccountsAPI,
    getGroupsAPI,
    getInfosAPI
})(UserFormComponent);`

**Comment by amanmahajan7** [comment]
This does not look like a react-data-grid issue. If you think it is then can you create a https://codesandbox.io/ example.

**Comment by Deboracgs** [comment]
@amanmahajan7 you have an example of force re render when update state rows???
