### ISSUE TITLE
how translate buttons

### ISSUE THREAD

**Issue by Deboracgs** [adazzle/react-data-grid#1207]
Hello,

how translate buttons "filter rows" and others ???

**Comment by Deboracgs** [comment]
@amanmahajan7 any solution?

**Comment by amanmahajan7** [comment]
There is no built it support for translations at the moment. You can however customize [`Toolbar` ](https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid-addons/src/toolbars/Toolbar.js#L19)and pass [custom text props](https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid-examples/src/scripts/example09-filterable-grid.js#L108)
```
toolbar={<Toolbar enableFilter={true} [filterRowsButtonText](url)={translate('FilterRow')}/>}
```

For `Search` you can specify a custom `column.filterRenderer` and [customize the text](https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid/src/cells/headerCells/FilterableHeaderCell.js#L25).

**Comment by Deboracgs** [comment]
@amanmahajan7 you have example to search?

**Comment by Deboracgs** [comment]
@amanmahajan7  i not have idea to translate search field, you have any example for this??

**Comment by vpolimenov** [comment]
@amanmahajan7 thanks for the solution workds perfectly :ok_hand: . One thing though the searchable fields are still not translated and that I suppose will be slightly more difficult to deal with. (and possibly the only solution is to get a custom Toolbar going)

![image](https://user-images.githubusercontent.com/9103498/66714636-ef84de00-edb0-11e9-9b20-3abfef220df4.png)
