### ISSUE TITLE
All the features example is broken on site.

### ISSUE THREAD

**Issue by brekk** [adazzle/react-data-grid#121]
![screen shot 2015-11-30 at 3 24 12 pm](https://cloud.githubusercontent.com/assets/18919/11487767/7af7eaf8-9776-11e5-800e-63063cade51c.png)

Throws `SyntaxError: Unexpected token '('. Expected a ':' following the property name 'getRowAt'.`

**Comment by jpdriver** [comment]
hey @brekk thanks for flagging this. weirdly it doesn't affect Firefox or Chrome -- out of curiosity which browser are you using?

i've done a PR that fixes it here https://github.com/adazzle/react-data-grid/pull/122

**Comment by brekk** [comment]
Hey @jpdriver, I was using Safari on Yosemite. Cheers for the PR!
