### ISSUE TITLE
Sort functionality enhancements

### ISSUE THREAD

**Issue by apoorvaDeodhar** [adazzle/react-data-grid#1213]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [x ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details
Is it possible to know which columns are sortable in the grid i.e. which columns have sort set to true?
May be something like having both up and down arrows. This would help user understand which column headers are clickable. 

![sortableheader](https://user-images.githubusercontent.com/39731680/40656675-ab78758a-6334-11e8-8aae-b08ad5bda9ff.PNG)

**Comment by amanmahajan7** [comment]
I think a custom header cell component can be used to add additional sort icons. Check this [example](https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid-examples/src/scripts/example13-all-features.js#L73). `HeaderCell` component passes[ `column` prop](https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid/src/HeaderCell.js#L67) to custom `renderer` which can be used to show/hide icons.
