### ISSUE TITLE
Selected cell outline not fully visible in IE11

### ISSUE THREAD

**Issue by alexanthony** [adazzle/react-data-grid#1216]
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [X] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [X] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [X] 🐛 Bug Report
- [ ] 💡 Feature Request

---

### Issue Details
Open the examples in IE11 (11.0.9600.19002)
Open an example with selectable cells
Select a cell

On e.g. chrome, the cell selection outline looks right. On IE11, only the top and left outlines are visible.

Also, the selected cell loses all outline while being dragged down (cell drag down example), and the highlight doesn't seem to be visible until the drag and drop is released.

I've added z-index: 10 to .react-grid-Cell:focus which seems to sort the first issue.

**Comment by amanmahajan7** [comment]
Cell drag does not work in IE11 due the way [HTML5 drag and drop](http://mereskin.github.io/dnd/) works but this will be fix in this [PR](https://github.com/adazzle/react-data-grid/pull/1209). We recently merged a [PR ](https://github.com/adazzle/react-data-grid/pull/1123)that improves cell rendering logic and will fix this particular issue. It is a big rewrite and we discovered a few [bugs ](https://github.com/adazzle/react-data-grid/pull/1209)during internal testing. This is being actively worked on but at this moment we do not know when this will be released.
