### ISSUE TITLE
Column auto width is not computed corectly when the grid is loaded in "displayed:none" container

### ISSUE THREAD

**Issue by lavor** [adazzle/react-data-grid#1217]
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [X] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [X] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [X] 🐛 Bug Report
- [ ] 💡 Feature Request

---

### Issue Details

I have 3 columns, the first one doesn't have the width specified, but the second and third they have. In the standard situation the width of first column is computed correctly and the table fits the parent container.

But the problem is when the grid is loaded in `display: none` container. I have tabbed layout with the grid in the first tab and the page is loaded with the second tab visible. After that, when I select the first tab to be visible, I see that the first column width is not computed correctly (min column width is set):

![image](https://user-images.githubusercontent.com/7839054/40708213-2dd0afde-63f3-11e8-8314-f0b53e2f9275.png)

Problem is in the function `.gridWidth()`, where `.grid.parentElement.offsetWidth ` is 0 in case when parentElement or one of its ancestors are styled as `displayed: none`.
```
this.gridWidth = function () {
  return _this3.grid ? _this3.grid.parentElement.offsetWidth : 0;
};
```

**Comment by amanmahajan7** [comment]
I think grid needs to be resized when the container div is displayed. Please check the following issues for a [workaround](https://github.com/adazzle/react-data-grid/issues/1135#issuecomment-372520982)
https://github.com/adazzle/react-data-grid/issues/1135
https://github.com/adazzle/react-data-grid/issues/916

**Comment by lavor** [comment]
Ok, I think, it can be closed, the proposed workaround should solve it.
