### ISSUE TITLE
Copy contents from react data grid to excel spreadsheet

### ISSUE THREAD

**Issue by naindla** [adazzle/react-data-grid#1234]
I am using react data grid to display the contents returned from a web service. I have a requirement where users would like to copy contents from the grid onto an excel spreadsheet or to a notepad. When they copy the contents, the contents are not being copied in a tabular fashion but, they are being copied into a single column. 

Can someone let me know if there is a way to copy the contents from a react grid to excel spreadsheet in a tabular format as its displayed on the grid? 

I am using react 15.6.2

**Comment by joey-siftlogic** [comment]
I think you could achieve this by capturing the copy event and modifying the data (adding commas, spaces, newlines) as desired.

**Comment by MickaToast** [comment]
I have the same issue, would be great.
