### ISSUE TITLE
Providing array to `rowSelection` throws an error saying: "You provided a `checked` prop to a form field without an `onChange` handler"

### ISSUE THREAD

**Issue by SaurabhBayani** [adazzle/react-data-grid#1238]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details
When I try to provide array of indexes to `rowSelection` it breaks and make all checkboxes readonly.

Here is a sample code I am trying

```
render() {
        const rowText = this.state.selectedIndexes.length === 1 ? 'row' : 'rows';
        return (
            <div>
                <span>{this.state.selectedIndexes.length} {rowText} selected</span>
                <ReactDataGrid
                    rowKey="id"
                    columns={this._columns}
                    rowGetter={this.rowGetter}
                    rowsCount={this.state.rows.length}
                    minHeight={500}
                    rowSelection={{
                        showCheckbox: true,
                        onRowsSelected: this.onRowsSelected,
                        onRowsDeselected: this.onRowsDeselected,
                        selectBy: {
                            indexes: [1, 3, 4]   // Getting this array from redux store in real code
                        }
                    }} />
            </div>);
    }
```
for full example please refer https://adazzle.github.io/react-data-grid/#/examples/row-select

When render() gets called I am getting following error
![capture](https://user-images.githubusercontent.com/3132826/42520160-3a734f2a-8483-11e8-96f3-e84ed989d53f.PNG)

How can we fix this issue ?

Actually I am trying to preserve selection on view change of react-router, where I am saving selected rows in store and retrive them again.
I am using
```
    "react": "^16.4.1",
    "react-data-grid": "^4.0.7",
    "react-redux": "^5.0.7",
    "react-router-dom": "^4.2.2",
    "redux": "^4.0.0",
```

**Comment by vellov** [comment]
Same error, why is onClick defined on div instead of input element??

**Comment by polymer940c** [comment]
so basically there are LOTs of issue with this package, just the bot has been closing them due to inactivity even if it is a small fix. 🤦‍♂️
