### ISSUE TITLE
TypeError: _this.cells[i].setScrollLeft is not a function

### ISSUE THREAD

**Issue by RaedsLab** [adazzle/react-data-grid#1241]
### Which version of React JS are you using?

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [x] Chrome
---

### I'm submitting a ...

- [x] 🐛 Bug Report

---

### Issue Details

- What the current behavior is

I have the following column: 

```js
const columns = [
  {
    key: "ref",
    name: "Reference",
    resizable: true,
    filterable: true,
    filterRenderer: DateRangeInput,
    draggable: true,
    locked: true
  }
];
```
I immidiatly get this error: 

`TypeError: _this.cells[i].setScrollLeft is not a function`

- What the desired behvaior is:

Use draggable and locked at the same time

**Comment by jdu3ds** [comment]
I am also interested in a fix for this bug
