### ISSUE TITLE
Using horizontal scrolling causes scrolling issues, where data in cells is not rendered on time.

### ISSUE THREAD

**Issue by colindjk** [adazzle/react-data-grid#1242]
Note that columns themselves load properly, but the data values in the columns do not. 

## Similar Issues: 
| Issue  |  Description  |  
| ------------- | ------------- |
|  #1090   | Related topic, and first place I checked for fixes; the virtualization solution mentioned is a potential fix.  |
|  #729  |  Similar problem where jumpiness occurs when scrolling, disassociation occurs on other browsers (i.e. Firefox) which I understand is not necessarily supported.  |
|  #691   |  Possibly related issue, involves jumpiness when scrolling on IE and Edge  |

---

### Which version of React JS are you using?

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.4.1

Note that I am using the latest react-data-grid package, which should support React 16 according the [CHANGELOG.md](https://github.com/adazzle/react-data-grid/blob/master/CHANGELOG.md).

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome => I primarily use chrome for this project. 

⚠️ Not officially supported, but "should work" ⚠️
- [x] Firefox => Checked to see if the issue happens in Firefox, which is does.
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

---

##### Current Behavior
The columns of _data_ do not get loaded in properly when scrolling to the right _or_ left with a certain number of floating columns. 
- When scrolling to the right the data looks like it simply hasn't loaded in yet, and selecting one of the unloaded cells will do nothing (no table cursor will appear, haven't tested use of the context menu). 
- When scrolling to the left columns of data will _disappear_, and only be loaded if you scroll back to the right. 

##### Desired Behavior
Columns have their data ready by the time they get onto the screen. 

##### Steps to reproduce
- Create a table with a fixed width and enough columns to extend past the said width.
- Mark some left-most columns as fixed.
- Upon scrolling to the right or left you may notice the issue shown below.

![image](https://user-images.githubusercontent.com/15971482/42843574-805d56a6-89de-11e8-9469-948ed1bba6d5.png)
 
So I have a workaround currently, but that only works because of the type of data that I am looking at. As you can see the table displays a range of dates horizontally, which can be modified by a form on the page. If make the _start date_ of the range earlier, the blank boxes issue will happen for a range of dates I won't be looking at anyway. In other words, the lack of visual data only occurs with the first few columns regardless of how many I happen to be viewing. 

A possible solution is virtual columns (mentioned in #1090), but that might be overkill. I figure this issue should just necessitate modification to the specific code determining which cells are currently visible. I plan on looking for fixes myself but would appreciate some direction as to where I might find a solution for this issue. 

Thanks for any help that can be offered. 

EDIT: As user @ben-freenome pointed out, this issue is not restricted to fixed columns, it happens with horizontal scrolling in general. 

![missing_cols](https://user-images.githubusercontent.com/15971482/43547287-cee4d288-95a8-11e8-9fac-8e1f4188f535.png)

**Comment by Digi-Hessam** [comment]
I have posted an imperfect and temporary workaround for this in issue #916.

> Here's a temporary fix. In the first line of getRenderedColumnCount, in react-data-grid.js, props.columnMetrics.totalWidth is used.
> 
> `var remainingWidth = width && width > 0 ? width : props.columnMetrics.totalWidth;`
> 
> Instead use props.columnMetrics.width.
> 
> `var remainingWidth = width && width > 0 ? width : props.columnMetrics.width;`
> 
> This is not the perfect solution.
