### ISSUE TITLE
Custom filter set props in column initialization to 

### ISSUE THREAD

**Issue by JanBN** [adazzle/react-data-grid#1258]
### Which version of React JS are you using?

✅ Officially supported ✅
- [x] v15.4.x

### Which browser are you using?

✅ Officially supported ✅
- [x] Chrome

### I'm submitting a ...
- [x] Question 

### Issue Details
I need to write some custom filters but I would like to change their behaviour based on props. I can't find a way how to set custom filter with props in column initialization.
```
       const col = {
            key: field,
            sortable: true,
            resizable: true,
            name: x.name,
            filterable: true,
            getRowMetaData: (row) => { return row; },
            filterRenderer = CustomNumericFilter,
          };
```
This code works fine. I have created CustomNumericFilter. However I want this 
```
       const col = {
            key: field,
            sortable: true,
            resizable: true,
            name: x.name,
            filterable: true,
            getRowMetaData: (row) => { return row; },
            filterRenderer =<CustomNumericFilter someProps={true}/>,
          };
```
Change:
`filterRenderer = CustomNumericFilter,` vs `filterRenderer = <CustomNumericFilter someProps={true}/>` 
This fails on
`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`

Is this even possible, if so how ?

Thank you

**Comment by matthewdschulman** [comment]
+1

**Comment by dormeier** [comment]
@matthewdschulman @JanBN 

There is work being done to add this functionality in a future update, but in the meantime I have found a way to get this working.

The trick is to add the value as a custom prop on the column itself, then use that value in a custom FilterRenderer by accessing the props.column passed to your component. Then you can call the props.onChange method in the component constructor to apply the initial filter term.

`filterRenderer: InitialStringFilter, filterable: true, initialFilterTerm: 'MyFilterString'`

```
class InitialStringFilter extends React.Component {
  constructor(props) {
    super(props);

    this.state = { filterTerm: props.column.initialFilterTerm || '' };

    props.onChange({filterTerm: this.state.filterTerm, column: props.column, filterValues: this.filterValues});
  }

...
```

**Comment by bincani** [comment]
You can now pass custom props to a custom column filter like so.
```
const columns = useMemo(
    () => [
        {
            Header: 'Brand',
            accessor: 'brand',
            disableSortBy: true,
            Filter: (props) => <SelectColumnFilterApi
                apiEndpoint="/api/referenceTypeReference?id=1" {...props} />,
            filter: 'equals',
        },
```
Example filter.
```
export const SelectColumnFilterApi = ({
    apiEndpoint,
    column: {
        filterValue,
        setFilter,
        preFilteredRows,
        id
    },
}) => {

```
