### ISSUE TITLE
DropDownEditor options cannot be changed when new properties are received

### ISSUE THREAD

**Issue by shilpikanade** [adazzle/react-data-grid#1259]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x ] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
The Drop Down Editor options cannot be changed.

- What the desired behvaior is
I want to change the options when I get new props to the component, so in componentDidUpdate.

- (If Bug) Steps to reproduce the issue

 componentDidUpdate(prevProps, prevState) {
        if (prevProps.abc !== this.props.abc) {
            this._options= [];
            for (let i = 0; i < this.props.abc.length; i++) {
                this._options.push({ 'id': i, title: this.props.abc[i], value: this.props.abc[i] });
            }

            this.createColumn();
        }

 createColumn() {
        var optionsEditor= <DropDownEditor options={this._options} />;
        this._columns = [];
        this._columns = [
            {
                key: 'group',
                name: 'Group',
                resizable: false,
                editor: poptionsEditor
            }
        ]
    }

- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by abolognino** [comment]
Inactivity for 30 days seems a pretty bad reason to close a bug. I'm facing the same problem, what's the point in opening another bug for it?

It this behaviour is intended, just state so and document it.
