### ISSUE TITLE
ReactDataGrid width does not update correctly

### ISSUE THREAD

**Issue by jEnbuska** [adazzle/react-data-grid#1261]
React version v.16.4.2

Browser:
- IE 11
- Chrome

Report type: Bug Report

I'm using Grid beside SideNavigation. 

When SideNavigatio opens and closes the Grids width does not update correctly.

1. When SideNavigation has collapsed the Grid:s width does not expand.
2. When SideNavigation is re-expanded Grid:s width expands to size, that it should have been previously and ends up taking too much space.

Example project: https://github.com/jEnbuska/react-data-grid_bug-report

Demonstration screenshots:

- Initial state before Sidebar closed
<img width="1678" alt="report_initial_state" src="https://user-images.githubusercontent.com/11061511/44299864-f1b2f000-a305-11e8-9c00-2bbde57471cc.png">

- State after sidebar closed (Grid width does not update)
<img width="1680" alt="report_after_sidebar_collaps" src="https://user-images.githubusercontent.com/11061511/44299740-8288cc00-a304-11e8-9f6d-684ecf5e27e2.png">

- State after Sidebar reopened (style: flex-basis: 200px), Grid:s width updates to parents old width
<img width="1680" alt="after_sidebar_re-open" src="https://user-images.githubusercontent.com/11061511/44299742-84eb2600-a304-11e8-9115-729444b6a76f.png">

removing react-grid-Container:s inline width style, from developer tools, fixes the issues (at least partially), but is there a way to prevent this from happening in the first place?

**Comment by tlehtimaki** [comment]
I would hope this issue re-opened. The problem is also that the while the examples sidebar is opened after being closed the table will actually grow out of the container.
