### ISSUE TITLE
Custom Header Menu with hide column ability

### ISSUE THREAD

**Issue by aabadri** [adazzle/react-data-grid#1264]
### Which version of React JS are you using?

✅ Officially supported ✅
- [* ] v15.4.x

### Which browser are you using?

✅ Officially supported ✅
- [ *] Chrome

### I'm submitting a ...

- [ *] 💡 Feature Request

### Issue Details

```
Is there any way to edit header cell and do some operation like renaming the header menu with hiding column ability.
like this:
https://github.com/adazzle/react-data-grid/issues/101

```

**Comment by ogg130** [comment]
Very low tech way to get the job done:

1) Give the column a value of hidden, which will hide the column but not the column header.

2) Give the column an empty name or else you will see text in the header.

3) Give the column a width of -1. A width of 0 leaves a small empty header column, but -1 'hides' it apparently, probably puts it under the previous element, not sure, not a css master.

Regardless, it works.

const columnTemplate = [
  {
    {
      key: "costCenter",
      name: "",
      width: -1,
      hidden: true
    }
