### ISSUE TITLE
How to add custom format for selected cell?

### ISSUE THREAD

**Issue by alex153410** [adazzle/react-data-grid#1265]
This is quesion. Documentation addresses only the event handling https://adazzle.github.io/react-data-grid/#/examples/cell-selection-events and there is no previous question regarding formatting/visual styles.

**Are there any CSS classes that are assigned to the selected cell?** Currently the selected cell has pale blue border but I would like to change this. Such change of style is not possible with ReactDataGrid.onCellSelected, because the formatter.render() event is fired first and only then onCellSelected event is fired. Yes, I can read the coordinates of the selected cell in onCellSelected, but I can not use those coordinates for formatting, because formatter.render is executed before onCellSelected, i.e., coordintates are not available in the time moment when they should be read.

I do not consider this as bug, of course, there shold be another mechanisms how one can format the selectedCell, but at present I can not find this mechanism in documentation. I went through the generated code in web console and I did not managed to find any additional class name that could have been added to the selected cell by the grid.

**So, what is the right mechanism how to format the selected cell?**

_Maybe I can call (somehow) formatter.render() of the selected cell inside onCellSelected somehow? And that would solve my issue?_

**Comment by reebgame** [comment]
do you have try a custom formatter using a wrapper div with an onclick listener ?

**Comment by alex153410** [comment]
Of course, I am using custom formatter for my cell and the code is:
```
class TableCellFormatter extends React.Component {
    render() {
        const textValue = JSON.stringify(this.props.value);
        const cellStyle = this.calcStyle();
        return (
            <div style={cellStyle}>
                {textValue}
            </div>);
    }
}
```
If I could get isSelected (or any other property) from this.props then I would be able to adjust this.calcStatyle() to take into account the selection fact. But, as I said, props does not have property isSelected (or similar one) and formatter.render() happens before onCellSelected and the event of onCellSelected does not contain handle of the selected cell. So - there is no way forward according to my understanding.

**Comment by atacadapp** [comment]
same issue

**Comment by jeffal** [comment]
I would also like to know if my custom formatter component `isSelected`
