### ISSUE TITLE
How to make a specific row non editable? 

### ISSUE THREAD

**Issue by nimesha95** [adazzle/react-data-grid#1274]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [x] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

Like in the title says is it possible to do that for a some rows on the datagrid? Not to the every rows.
I know that it is possible for a each cell. But what i want is to is disable editing for rows

**Comment by pellejacobs** [comment]
@nimesha95 any reason you closed this? I think this is a very valid question.

**Comment by qili26** [comment]
@pellejacobs There is a field called `onCellIsEditable` (or similar) in `<RDG />` component, you can implement your override logic for checking there which will overrides the `columns.editable` result.
