### ISSUE TITLE
How to set color of the text in a cell programatically

### ISSUE THREAD

**Issue by nimesha95** [adazzle/react-data-grid#1276]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [x] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

Is is possible to set color of the text in a cell programatically? 
Well my scenario is i have some numbers filling in the datagrid. I want to color them according to their values. I'm kind of lost here because i didnot found a way to customize a single cell. I've tried the 'rowRender' but it dosen't accomplish my task since it only colors a row. What i want is to color a single cell. 
Is it possible to do this.

**Comment by reebgame** [comment]
try custom Formatter

example :

// define your formatter
class Noteformatter extends React.Component{
  constructor(props){
    super(props);
    this.opts = this.props.options;

  }


  render(){
    var bg = "#FFFFFF";

    switch(this.props.value){
      case 1:
        bg = "#00FF00";
        break;
      case 2:
        bg = "#FFFF00";
        break;
      case 3:
        bg = "#FFA500";
        break;
      case 4:
        bg = "#FF0000";
        break
      default : 
        bg = "#FFFFFF";
    }

    var label = this.props.value;
    for(var i=0;i<this.props.options.length;i++){
      if(this.props.options[i].value == this.props.value){
          label = this.props.options[i].text;
      }
    }

    return (<div style={{backgroundColor:bg}}>{label}</div>);
  }

}    

// declare your formatter with custom params (here "options")
const MyNoteFormatter = <Noteformatter options={notes}/>;

// define yout formatter in column defintion

{
        name : "my column",
        key : "eerr",
        width: 200,
        formatter : MyNoteFormatter
      },{
