### ISSUE TITLE
Possible to sort columns that contain comma's?

### ISSUE THREAD

**Issue by raptoria** [adazzle/react-data-grid#128]
using a D3 num formatter breaks the sorting of table columns..

ex:
let numFormat = d3.format("0,000") 
...
obj[columns[j].key] = isNaN(x) ? x : numFormat(parseInt(x));

**Comment by jpdriver** [comment]
Hey @raptoria -- would you mind posting a gist so I can fully understand what you're trying to do?

Basically, you should avoid using formatted numbers as the underlying Cell values for this reason. The values should always just be the raw numbers, and then each column has a `formatter` property you can set to be a separate React component. eg:
```
var columns = [
    {
      key: 'avatar',
      name: 'Avatar',
      width : 60,
      formatter : ReactDataGrid.Formatters.ImageFormatter,
      resizable : true
    },
    ...
];
```
so the `.render()` method of your formatter component should return your d3 formatted value. Do you need the values to be editable as well?

**Comment by raptoria** [comment]
no, that's all I need. Thanks!
