### ISSUE TITLE
possible to set width of React Data Grid? 

### ISSUE THREAD

**Issue by raptoria** [adazzle/react-data-grid#129]
Is it possible to set the width and height of the table to auto, such that the table scroll bars disappear and I can use the browser's scrollbar to scroll horizontally or vertically instead (if the table is larger than the initial viewport)? 

thanks!!

**Comment by bakesteve** [comment]
I think this will be covered by #133 so maybe worth checking that out? It should get merged soon, so wait till next week if its easier and then you can just npm update

**Comment by mohak1990** [comment]
Which Grid is more complete. Many react grids come up with lots of issues and few customization options.. Which grid should I choose for a business app?
