### ISSUE TITLE
Automatic unexpected scroll back to selected cell

### ISSUE THREAD

**Issue by alonana** [adazzle/react-data-grid#1292]
### Which version of React JS are you using?

 v16.4.1

### Which browser are you using?

Chrome

### I'm submitting a ...

🐛 Bug Report

### Issue Details
The scroll automatically jumps back to selected cell
This can be seen in the official demo site:
https://adazzle.github.io/react-data-grid/#/examples/all-features
Just click once on the down arrow of the scroll, and wait on second.
You can see the table automatically scrolls back up.
I would expect it to remain at the scrolled location, and not to jump back up

**Comment by wojiaofengzhongzhuifeng** [comment]
@alonana hi, are you solve this problem? or just update to lastest version?

**Comment by alonana** [comment]
I cannot reproduce this at the latest version.
Looks like this is solved.
