### ISSUE TITLE
Expand row and provide custom widget

### ISSUE THREAD

**Issue by themre** [adazzle/react-data-grid#1294]
---
### Which version of React JS are you using?
- [x] v16.2.x
---

### Which browser are you using?
- [x ] Chrome
---

### I'm submitting a ...
- [x ] 💡 Feature Request
---

### Issue Details
I'm looking Tree View examples and currently you need to specify children for certain rows. I would like to know if there is a way to expand certain row without knowing in advance what will you have. For example expanding a row and do async call for some additional data. Can this be achieved now somehow?

**Comment by Nodios** [comment]
You can do that! What I did is implement a tree view example and added a flag property to a row that is expanding. Then create a row renderer that will switch between your custom component and built-in row based on your flag property. When you have that, you will be able to do what ever you want in your custom component.

**Comment by themre** [comment]
@Nodios thanks for the info! could you post small snippet on codesandbox or create sample gist with pseudo code so that also others could take similar approach? because I don't know how often new examples are added here.

**Comment by Nodios** [comment]
Yes, if you follow this [example](http://adazzle.github.io/react-data-grid/#/examples/tree-view-no-add-delete) and add this [changes](https://gist.github.com/Nodios/7275be13e55df1c35a7dc9d535993496) you should be able to get the functionality. 

**Warning**: have in mind that you are adding rows in the grid and if you have any calculations (eg. how many items in the grid, etc) you will have to remove all the rows with the _flag_ from those calculations
 Also, locking columns **will not work**

**Comment by themre** [comment]
Perfect,thanks a lot for this guide!

V čet., 18. okt. 2018 17:08 je oseba Dino Repac <notifications@github.com>
napisala:

**Comment by mattnedrich** [comment]
@Nodios your links look broken currently

**Comment by Nodios** [comment]
@mattnedrich  Seems like few things have changed since, here are new links:
custom row renderer: https://adazzle.github.io/react-data-grid/docs/examples/row-renderer
tree view in grid: https://adazzle.github.io/react-data-grid/docs/examples/tree-view
