### ISSUE TITLE
[REACT-14] react-data-grid render issue.

### ISSUE THREAD

**Issue by shekharkul** [adazzle/react-data-grid#132]
Hi,
I am just using react-data-grid in my application to display data in table view, but when i update data using inline update functionality the updated data is not displayed in react-data-grid.
Please find code below.
var  rowGetter = function(i){
                    return _rows[i];
                };
var  griddata = <ReactDataGrid
                enableCellSelect={true}
                columns={columns}
                rowGetter={rowGetter}
                rowsCount={_rows.length}
                onRowUpdated={this.handleRowUpdated}/>
return(
            <div>
             {griddata} 
             {_rows[0].Users}   
            </div>);

Update value is displayed in {_rows[0].Users}  but not in  ReactDataGrid.

Thanks

**Comment by jpdriver** [comment]
hey @shekharkul -- sorry I'm not 100% clear on what you mean here. how are you changing your Users value? do you mean you're changing the values in the cells and something's not working in your `handleRowUpdated` method?

would it be possible for you to share a complete gist of your module so i can fully understand the problem?

thanks! :smile:

**Comment by shekharkul** [comment]
We have changed the value in cell and call  handleRowUpdated method. In handleRowUpdated method we have API call to updated the data and data is successfully updated. After that we have callback method to update state. 
In state variable we get updated data and same we assigned to _row, but react-data-grid is not updated/ refresh.

 render:function()
    {
        var TreeViewDetails=this.state.TableViewDetails;
        var griddata;
        _rows=[];
        columns=[];
        AllGridColumns =[];
        rowGetter = [];
            if( TreeViewDetails != null  && Object.keys(TreeViewDetails).length > 0)
            { 
                this.Addcolumnsrec(TreeViewDetails,0);
                _rows = unique(_rows);
                rowGetter = function(i){
                    return _rows[i];
                };
                griddata = <ReactDataGrid
                enableCellSelect={true}
                columns={columns}
                rowGetter={rowGetter}
                rowsCount={_rows.length}
                onRowUpdated={this.handleRowUpdated}/>
                }
        }
        console.log(_rows); console.log(_rows[0].Users);
        return(
            <div>
                 {griddata} 
                  {_rows[0].Users}
            </div>);
},

Addcolumnsrec - function to add data into _row.
console.log(_rows); console.log(_rows[0].Users); -  printed updated value.

Thanks
