### ISSUE TITLE
Custom column widths (Percentage, minWidth)

### ISSUE THREAD

**Issue by igoriok1994** [adazzle/react-data-grid#1339]
⚠️ Not officially supported, expect warnings ⚠️
- [x] v15.5.x

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome
---
### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request
---

Hi.

Is there any possibility to set different minColWidth to each column?
Eg. I have 3 cols, and 1st min width - 20px, 2nd - 50px, 3rd - 150px

Is there any way to set width in percentage?
Eg. 20%, 20%, 30%, 30% (for each col)

Is there any way to combine pixel width and percentage width?
Eg. first col - 30%, second 20px, third, 20px, last col 70%
And 100% is calculated like 100% minus all pixel width columns (100% - 20px - 20px)

**Comment by KristianLonergan** [comment]
I am surprised that percentage column widths are not supported. Surely this should be supported ?

**Comment by nathanjwtx** [comment]
It's taken me quite a bit of searching to end up here. I think this would be a great feature to have. As it is, I may have to look for an alternative solution; I don't my checkbox column to the be equal in width to the other columns.

**Comment by daniel-refahi** [comment]
why this is closed.... such a basic feature that even the free, community tables have.

**Comment by ThomasPfeiffer** [comment]
> It's taken me quite a bit of searching to end up here. I think this would be a great feature to have. As it is, I may have to look for an alternative solution; I don't my checkbox column to the be equal in width to the other columns.

I think the flex Property on GridColDef will do the Job for you https://mui.com/components/data-grid/columns/#fluid-width

**Comment by egroeg92** [comment]
has anyone found a solution to this?

**Comment by egroeg92** [comment]
> I am surprised that percentage column widths are not supported. Surely this should be supported ?


has anyone found a solution to this?

**Comment by Fi1osof** [comment]
Still waiting for...
