### ISSUE TITLE
adazzale/Demo/Documentation Page Not Found

### ISSUE THREAD

**Issue by evepen1** [adazzle/react-data-grid#1348]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [✅ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [✅ ] Edge
- [✅ ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [✅ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [✅ ] 🐛 Bug Report
- [✅ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

### Issue Details
Hi,

When I'm trying to refer Column Grouping Feature in demos this URL is not working..

[https://adazzle.github.io/react-data-grid/#/examples/grouping](url).  I could see this working, when I opened this page couple of weeks ago.

Feature request: I would like to request the following feature, 

ADD/REMOVE Columns visibility by clicking on a (+) icon in the end the header bar which gives a checklist drop-down.  We can check on Column header to make it visible or unchecked to hide.
```

**Comment by great-handsome** [comment]
url https://adazzle.github.io/react-data-grid/#/examples/cell-actions  from demo is not working too.

**Comment by amanmahajan7** [comment]
The website is currently down and we are working on a fix. This should fix the cell-actions example as well

**Comment by amanmahajan7** [comment]
This has been fixed
