### ISSUE TITLE
Only header column remains locked on custom render scroll, issue reoccurred at latest version

### ISSUE THREAD

**Issue by Thilagm** [adazzle/react-data-grid#1362]
- Have you already searched for similar issues? Please help us out and double-check first!
yes
- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details
Make a column fixed, and when horizontal scroll only column header remains fixed, the rows scroll along for custom Renderer. This was working fine in version 4.0.8
```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by amanmahajan7** [comment]
Can you make sure you are using `renderBaseRow`.
https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid-examples/src/scripts/example12-customRowRenderer.js#L27

**Comment by Thilagm** [comment]
I'm using custom cell renderer also within Row Renderer. so how can i pass call render base row?
