### ISSUE TITLE
X-axis scroll not working!!!!

### ISSUE THREAD

**Issue by anik587** [adazzle/react-data-grid#1367]
react data grid x-axis scroll not working on my browser, my current(70.***) version (crome) but working on previous version(69.***) and working fine 
with other browser. 
My React Version is  "react": "16.4.1",
React-data-grid version is     "react-data-grid": "4.0.8","react-data-grid-addons": "4.0.8",

![capture1211](https://user-images.githubusercontent.com/13942364/47937960-ae334f80-df0c-11e8-93c4-654e2dca2f05.PNG)

![capture123123](https://user-images.githubusercontent.com/13942364/47937965-b25f6d00-df0c-11e8-9308-45868ef51c24.PNG)

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?
Crome 70.0.3538.77 
✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- Scroll Not Working
- Scroll Should Work

**Comment by anik587** [comment]
Worked after i updated my version into 5.0.3. 
Though it was not working due to immutable issue then i user that command `npm install react react-dom immutable`. I don't know what does that mean, though its working

**Comment by amanmahajan7** [comment]
This immuable issue has been fixed in https://github.com/adazzle/react-data-grid/pull/1366. A new patch version will be published soon.
