### ISSUE TITLE
Filtering rows resulting in 0 rows shown disables horizontal scrolling

### ISSUE THREAD

**Issue by iamkennytso** [adazzle/react-data-grid#1371]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

---

### Issue Details
When filtering by a value that does not exist in any rows, no rows are displayed (intended) and horizontal scrollbar disappears. This becomes problematic when the grid's columns overflow. This is reproducible on the example site, http://adazzle.github.io/react-data-grid/#/examples/filterable-sortable-grid. See .gif for reference:
https://gyazo.com/1fe386719ef5e5447606fe30ce3db4cf
In it, I'm filtering the "Expected Completed" by "q", which does not exist in any rows, and the scroll bar disappears, not allowing me to scroll to the right to erase the q.

**Comment by iamkennytso** [comment]
Can someone throw a bug label on this ticket, please?

**Comment by iamkennytso** [comment]
This is still a problem.
http://adazzle.github.io/react-data-grid/docs/examples/column-filtering
Entering `q` in date filter resets the scroll and locks it, essentially locking the grid and requiring a reload to do anything.

**Comment by monish001** [comment]
Facing this same issue. This seems to be a critical bug if filters are required and there are as many columns as to get a horizontal scroll.

**Comment by sontek** [comment]
Still an issue
