### ISSUE TITLE
Horizontal scrolling not working in Chrome

### ISSUE THREAD

**Issue by mcix** [adazzle/react-data-grid#1372]
---

### Which version of React JS are you using?

✅ Officially supported ✅
- [x] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [x] IE 9 / IE 10 / IE 11
- [x] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [x] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Horizontal scrolling is working in IE, Edge and Safari, but not in Chrome.
Would be nice if horizontal scrolling is working in Chrome also.
The example on https://adazzle.github.io/react-data-grid/#/examples/all-features does allow horizontal scrolling in Chrome, so I compared elements to see where the issue might be.

I have narrowed it doen to the following:
If I disable the "contain: layout" style in the react-grid-Row div, horizontal scrolling is working in Chrome!

Since I am new to this project I don't know what this contain style is used for and what implications this would have. If there is something I can do to check what depends on this style, I am keen to do this.

Here is a screen grab of the behaviour:
```

![Screengrab](https://bytesoflife.nl/share/table.gif)

Edit: I just tested this using React 15.4, I see the same behaviour there

**Comment by terolepisto** [comment]
For me, 5.0.4-2 doesn't frozen the cells. The header works like intented but content cells scroll with scrollbar, which is not what they did before update.

**Comment by amanmahajan7** [comment]
In v5 we introduced a `renderBaseRow` prop , please take a look at the `CustomRowRenderer` example
https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid-examples/src/scripts/example12-customRowRenderer.js#L27

**Comment by JamesFast** [comment]
Completely froze on us.  This was a pretty significant user impact without warning.  I would suggest that this isn' defaulted.  It's new and cool, but not mainstream use case to scroll only a row in 1,000 row list.  Thanks for the quick reply Aman!
