### ISSUE TITLE
Flexbox sizing support

### ISSUE THREAD

**Issue by NullVoxPopuli** [adazzle/react-data-grid#1377]
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

it would be super cool to have react-data-grid to support flexible sizing / the ability to to grow to the available space, rather than (currently), only rely on minimum width.

**Comment by NullVoxPopuli** [comment]
Here is some CSS I came up with to make the existing react-data-grid flexible:

![image](https://user-images.githubusercontent.com/199018/48364017-49e35f00-e675-11e8-8e03-ed3f67a67f9c.png)

**Comment by NullVoxPopuli** [comment]
booo

**Comment by piehouserat** [comment]
the stale bot gives the false impression that this plugin is in good shape as there are only a few open issues but the reality is that the bot sweeps serious voids in functionality under the rug without resolution...
