### ISSUE TITLE
implementing formulas

### ISSUE THREAD

**Issue by sandys** [adazzle/react-data-grid#138]
hi,
we are looking at building a spreadsheet that has some cells as computed elements . I'm NOT looking at an Excel-like interface where the formulas are entered by the user and interpreted by the sheet. I'm going to hardcode the computation in the sheet itself.

I'm not sure how to do this in a way that doesnt impact performance. even with 5-6 computed cells, we have a massive slowdown . I'm using the HandleRowUpdate function to recompute the formulas and the initialstate to compute the first time. I'm not sure if this is the right way to do it.

**Comment by bakesteve** [comment]
hi
Yes - this is definitely very possible, and something we do a lot of internally.
A few key pointers:
- make sure that the calculated initial values are set before they get to the grid. We do this in stores. But you will definitely get perf issues if this happens in your rowGetter or in the formatter
- recalculate the data only when values have changed. YOu can do that in handleRows, but you want to try and have soime logic that looks for changes (similar to how you do shouldComponentUpdate). Again, flux helps here. As will immutable data (so you can do row !== updatedRow)

if you have a worked example, happy to take a look

**Comment by dulguun0225** [comment]
Any examples?
