### ISSUE TITLE
resizable column can not work normally 

### ISSUE THREAD

**Issue by lynshir** [adazzle/react-data-grid#1382]
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

Now in version 5.0.4 or 5.0.2  resizable column can not work normally , but It works fine in version 4.0.8

```js
//This is my code，never changed ，Please see the screenshot below
<DraggableHeader.DraggableContainer key='1' onHeaderDrop={handleHeaderDrop}>
          <ReactDataGrid columns={_columns.slice(0)} rowGetter={rowGetter} rowsCount={rowsCount} onGridSort={sortAll ? handleGridSortAll : handleGridSort}
            getSubRowDetails={getSubRowDetails} onCellExpand={onCellExpand} rowSelection={{
              showCheckbox: !!showCheckBox,
              enableShiftSelect: true,
              onRowsSelected: handleRowsSelected,
              onRowsDeselected: handleRowsDeselected,
              selectBy: {
                keys: {
                  rowKey: primaryKeyField,
                  values: selectedKeyValues.slice(0)
                }
              }
            }} onRowClick={onRowClick} rowRenderer={RowRenderer} minHeight={500} />
        </DraggableHeader.DraggableContainer>
```
[please see screenshots ](https://front.runscm.com/react-data-grid-problem.gif)

**Comment by lynshir** [comment]
and now  can't double-click on the cell to select the content. It used to be can work.

**Comment by peonmodel** [comment]
would like to point out that resizable columns doesnt seemed to work on the website itself

http://adazzle.github.io/react-data-grid/docs/examples/column-resizing

the rows can be reordered but columns cannot be resized, there seemed to be a mix up
