### ISSUE TITLE
React datagrid is blinking on the top row

### ISSUE THREAD

**Issue by sontek** [adazzle/react-data-grid#1383]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [X] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [X] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [X] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details
I've got a default grid setup:

```
 <DataGrid
                                columns={this.state.tableColumns}
                                rows={this.state.tableRows}
                                rowGetter={this.rowGetter}
                                rowsCount={this.state.tableRows.length}
                                onAddFilter={this.handleFilterChange}
                                onClearFilters={this.onClearFilters}
                            />
```

and the only style I've customized is the header:
```
.dataGrid {
  :global {
    .react-grid-Grid {
      .react-grid-HeaderCell {
        background: #EFF6FF;
        font-size: 0.9rem;
        font-weight: normal;
        font-family: $font-main-content-heading;
        border-right: 0;
        padding: 0.3rem 1.5rem;
        height: 45px;
        border-bottom: 1px solid #DDD;
        .widget-HeaderCell__value {
          padding: 6px 0px;
        }
      }
    }
  }
}
```

and I'm getting a weird blinking first row:

![nov-15-2018 10-22-59](https://user-images.githubusercontent.com/151924/48558933-d897ec00-e8c0-11e8-9df8-6b942c3ec2bd.gif)

**Comment by sontek** [comment]
Customizing the height caused this.  Setting the `rowHeight` property fixed it

**Comment by blaues0cke** [comment]
I also faced this issue. Seems that its also important to keep any "extra height" away from the table row (wrote some documentation about this here: https://stackoverflow.com/questions/46203926/frozen-columns-jitter-on-horizontal-scroll-in-react-data-grid/57129288#57129288)
