### ISSUE TITLE
AutoCompleteEditor menu does not open upward

### ISSUE THREAD

**Issue by rounakcodes** [adazzle/react-data-grid#1407]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?
- [ ] v16.x.x

---

### Which browser are you using?
- [ ] Chrome

---

### I'm submitting a ...

- [ ] 🐛 Bug Report

---

### Issue Details

```
Please include:
- What the current behavior is
When an entry is made in the bottom row of the grid, 
the cell which contains AutoCompleteEditor opens the menu of options downward 
which makes it difficult to see more than one option.
- What the desired behvaior is
The menu should open upward when it cannot fully show itself

I have done a lot of work using this grid and I have found it very useful for my needs. 
If I had realised this issue earlier, I would not have used it because
 I am not good enough to edit the source code. 

If anyone can fix this, please help.

**Comment by amanmahajan7** [comment]
This is fixed in V6. The editor will still be opened downward but it won't be cut off

http://adazzle.github.io/react-data-grid/blog/#fix-editor-rendering. 

Feel free to open another issue if you are still facing problems
