### ISSUE TITLE
Scrolling data shows an empty space below the header

### ISSUE THREAD

**Issue by eduardosmatheus** [adazzle/react-data-grid#1415]
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

Is this an actual bug or if it stands for some predictable behavior inside the rows rendering implementation?

- Current Behavior
When scrolling data inside a grid, sometimes it's rendering a blank space like in the example below:
![possible bug](https://user-images.githubusercontent.com/12476413/49444692-164cae00-f7b7-11e8-819c-d9c5144b50ad.gif)

- Steps to reproduce
Use any data grid with a bunch of scrollable rows.

**Comment by eduardosmatheus** [comment]
Does anyone here have a clue about it?

**Comment by eduardosmatheus** [comment]
Any thoughts about it lately?

**Comment by elijah89** [comment]
Still a disturbing bug 🙁

**Comment by qili26** [comment]
This gap is a bug, but not that critical comparing with the work we had been working on this year for moving the whole code base to typescript. Maybe this is fixed in `canary` branch as we refined the rows rendering logic. @elijah89
