### ISSUE TITLE
Empty block after scrollable grid..

### ISSUE THREAD

**Issue by delef** [adazzle/react-data-grid#142]
![Image of Bug](https://i.gyazo.com/acdb736a2c7c4174876b334305968d2d.gif)
(rows quite a bit)

Temporary grid are frozen. Solve update page.

**Comment by jpdriver** [comment]
hey @delef -- which browser is this?

**Comment by delef** [comment]
@jpdriver Hi! I use Google Chrome 47.0.2526 (Mac OS 10.11)

**Comment by delef** [comment]
(https://i.gyazo.com/3d7cadf916662e854be9b6c025196129.png)
This is frozen grid..

**Comment by qosmy-michael** [comment]
Seeing same issue

**Comment by stemcc** [comment]
I am seeing this issue as well. Using Chrome version 48.0.2564.109 on El Capitan.

**Comment by ppiekarczyk** [comment]
I'm also seeing this issue!

**Comment by hakunin** [comment]
I am still seeing the issue even after the the fix http://screencast.com/t/3Dvhat4Px1aA

**Comment by rajbits** [comment]
Is there a fix for this issue? Am still seeing it.

**Comment by eduardosmatheus** [comment]
This issue is still happening with me, but now when I have to dynamically resize the grid's height.

e.g. In my case I'm using a split pane, where the grid has to obbey the pane's height

Could someone help me?

**Comment by sammysamx20** [comment]
Definitely not fixed
