### ISSUE TITLE
Using custom editors, the `cellKey` is incorrectly reported `onGridRowsUpdated`

### ISSUE THREAD

**Issue by jeffal** [adazzle/react-data-grid#1420]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is

Using custom editors, the `cellKey` is incorrectly reported `onGridRowsUpdated`, when a user clicks from one editable cell to another cell. The cell key is that of the column that was clicked and not the column that was editable.

- What the desired behavior is

The `cellKey` should be the editable cell, not the cell clicked.

- (If Bug) Steps to reproduce the issue

Please, view the `console.log` here: https://codesandbox.io/s/xl2vrr0234

- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by jeffal** [comment]
Please, view the `console.log` here: https://codesandbox.io/s/xl2vrr0234

**Comment by Allenskywalker92** [comment]
I am facing the same issue. How do you resolve it @jeffal ?

**Comment by jeffal** [comment]
Hi @Allenskywalker92, we ended up developing a solution with https://handsontable.com/. Sorry, that's probably not very helpful...
