### ISSUE TITLE
custom row render doesnt seem to be working

### ISSUE THREAD

**Issue by sandys** [adazzle/react-data-grid#143]
including this example - http://adazzle.github.io/react-data-grid/examples.html#/custom-row-renderer

I'm not able to see or get a custom row example working.

**Comment by jpdriver** [comment]
hey @sandys -- i've updated that example here https://github.com/adazzle/react-data-grid/pull/179. technically it was always working, but the Cell background took precedence over our custom one so it wasn't clear what was happening :flushed:
