### ISSUE TITLE
Cell Action Icon

### ISSUE THREAD

**Issue by sun2rise** [adazzle/react-data-grid#1431]
- [x] v16.x.x
- [x] Chrome

I am looking at [CellAction example](https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md)

And I am wondering how can i use fontawesome or google material icons.
I tried to specify icon action as `<i class="fas fa-edit" />` but didn't work.

Thanks
p.s. new version and website are awesome! thanks again!

**Comment by braxtonb** [comment]
Hey @sun2rise, I was able to get the fontawesome edit icon working in this [code sandbox](https://codesandbox.io/s/mmlvnrv35j) example.

Hope this helps

**Comment by sun2rise** [comment]
Thanks @braxtonb this is just what I was looking for!
