### ISSUE TITLE
Reverse sorting requires extra click

### ISSUE THREAD

**Issue by prasanth1308** [adazzle/react-data-grid#1434]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [x ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ x] IE 9 / IE 10 / IE 11
- [x ] Edge
- [x ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [ x] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit a support request here. Instead, see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
- What the current behavior is
Clicking on the header cell of a sortable column does change the sort direction, NONE -> ASC -> DESC -> NONE,

- What the desired behavior is
When the grid column is sortable, you should be able to click on the column header and change the sort direction, NONE -> ASC -> DESC -> ASC -> DESC -> ASC ..... so on
```

**Comment by prasanth1308** [comment]
Any solution for above Issues?

**Comment by SteveDowsett** [comment]
Im also interested in a solution to the above. At present there is no way to have a sort of ASC/DESC/ASC/DESC and no way to override the rendering of a sortable header cell in order to achieve this.
