### ISSUE TITLE
Column definitions do not support all SyntheticEvents

### ISSUE THREAD

**Issue by vileppanen** [adazzle/react-data-grid#1435]
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Current behavior
RDG v5.0.4 states in documentation, that column events support _any_ SyntheticEvent in React. This seems not to be true, at least onFocus and onKeyPress seem not to respond to related user actions.

### Desired behavior
Columns should respond to onFocus and onKeyPress, if specified in column definitions (or other way around, the documentation should specify correctly the events that are supported in column definitions). Would provide great flexibility if all events would be supported

### Steps to reproduce
1. Change ie. onDoubleClick event in FirstName column to onFocus/onKeyPress event in this example http://adazzle.github.io/react-data-grid/docs/examples/column-events
2. Verify, that nothing is logged in the console, if  any FirstName cell receives focus/key is pressed on the cell

**Comment by tylerklose** [comment]
Was support for keyboard column events dropped intentionally?

**Comment by tylerklose** [comment]
Sorry probably should have tagged someone who is actively working on the project to re-raise the issue (@amanmahajan7)
