### ISSUE TITLE
Re-render changed column

### ISSUE THREAD

**Issue by delef** [adazzle/react-data-grid#144]
Hi! Help me please!

I change a column on onRowUpdated method. I use setState after async request (XMLHttpRequest), when onreadystatechange will be 4, but DOM change after only click on any column on this th.

P.S.
I hope that will understand me. Sorry for my english.

**Comment by delef** [comment]
Without asynchronous query works the same. :(
```
handleRowUpdated: (e) ->
    rows = @state.rows
    Object.assign rows[e.rowIdx], e.updated
    Object.assign rows[e.rowIdx], {issueType: Object.keys(e.updated)[0] + ' dddd'}
    @setState rows: rows
```
I edit code in example (http://adazzle.github.io/react-data-grid/examples.html#/editable)

And get result:
[!Image]
(https://i.gyazo.com/ad06f024efb770cfec3e6eced7465070.gif)

**Comment by jpdriver** [comment]
hey @delef -- this looks like the same problem that i'm having. other cells on the same row won't re-render until you select them. i've done a fix but it isn't in `master` yet.

try cherry picking this commit https://github.com/adazzle/react-data-grid/commit/4c7ce50d7fc75492222ec5f82fdaf3fb07b4e600

**Comment by denispeplin** [comment]
:+1:
Related to #197

**Comment by tranquilize** [comment]
I created a workaround for this and explained it at the end of #197. I neglected to tag this issue when I first wrote it, and Github doesn't seem to be referencing when I edit the comment.

**Comment by diogofcunha** [comment]
Let's keep this discussion in https://github.com/adazzle/react-data-grid/issues/197.

Cheers.
