### ISSUE TITLE
Typeahead Filter #1182

### ISSUE THREAD

**Issue by madhan-dhamodaran** [adazzle/react-data-grid#1441]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

@azu @amanmahajan7 @maiis @txm
@omarish

Hello All,

I am proposing a feature request. And I would like to contribute this feature to the community.

What the current behavior is :
Currently, the dropdown values for a multi-select/auto-select/single-select filters, needs to be loaded all at once. For example, if the dropdown values are amounting to thousands records, and when we happen to have multiple filters in a same grid, the browser hangs because of the load.

What the desired behvaior is :
We should be able to load say 50 drop-down by when the grid loads and anything beyond that, needs to be loaded on the fly. When the user starts typing in the filter box, it makes a server call/ get the matching updated list limited to 50 records again. This way, the browser is not overloaded.

(If Feature) The motivation / use case for the feature :
Like I mentioned earlier, this keeps the grid as efficient as possible by not overloading the browser memory. For example, if we are loading a dictionary and this is getting deployed in a shared environment, any newly added dictionary items in the shared environment gets loaded to the drop down values as we are making the server call to fetch the information.

To be clear, We are not writing making any ajax calls or anything. Typically, we call the handleFilterChange() method with the column key and the filtered value with which, whoever is using it can write their logic to make the server call or to load the drop down values.

**Comment by madhan-dhamodaran** [comment]
Creating a new issue because the old one was closed. Will raise a PR for this before end of January 2019

**Comment by madhan-dhamodaran** [comment]
I have raised a PR for this. Awaiting merge. #1449

**Comment by madhan-dhamodaran** [comment]
I have raised a PR for this. Awaiting merge. #1449

**Comment by madhan-dhamodaran** [comment]
I have raised a PR for this. Awaiting merge. #1449

**Comment by madhan-dhamodaran** [comment]
I have raised a PR for this. Awaiting merge. #1449

**Comment by amanmahajan7** [comment]
Starting v7 we are removing any concrete implementations for filters, editors or formatters. We will also remove the `react-data-grid-addons` package. This was done so users can create their own implementations and tweak it however they like. I would recommend coping Typeahead filter in your local repo

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/HeaderFilters.tsx
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--header-filters
