### ISSUE TITLE
rowGetter receives negative index

### ISSUE THREAD

**Issue by erensahin** [adazzle/react-data-grid#1445]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [x] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

### Issue Details

It seems that rowGetter receives -1 index input in v5.0.5.

Following screenshot shows the logged indices received as index parameter in rowGetter in v5.0.5

![screenshot_19](https://user-images.githubusercontent.com/15085990/50447075-d007ec00-0929-11e9-976c-cfed9f79dc68.png)

To compare, below shows the same console logs for v4.0.8 where rowGetter only receives proper array indices.

![image](https://user-images.githubusercontent.com/15085990/50446954-ec575900-0928-11e9-82f0-da98f959122c.png)

To reproduce the bug, sandbox link: [https://codesandbox.io/s/1op10z9ly4](url)

Thank you!

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by BlaineBradbury** [comment]
I see this as well in my case.  I am making API calls in this.rowGetter to an async getRows function, so on first render the rows array is not yet populated.  When the array is empty, a rowGetter function will receive approximately 2x as many rowIndexes as there would be visible rows given my Grid height, and the very last index sent is -1.  After data is returned and rows exist... the expected rowIndex values are received by rowGetter.

I need real rowIndex values for the logic surrounding my async row-getting, so I just avoid the first go like this:  `rowGetter={rows.length ? this.rowGetter : ()=>null}`
