### ISSUE TITLE
Detailed documentation is needed

### ISSUE THREAD

**Issue by steamhammer** [adazzle/react-data-grid#1448]
- Have you already searched for similar issues? Please help us out and double-check first!
- Also, please don't be that person who deletes this template. It's here for a reason.
- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Documentation request

Hello guys. I appreciate a ton of work you made to develop and maintain such a great grid component.

Recenlty I was looking for a way to set some custom styling for particular cells in grid (to mark invalid ones) and found out that documentation lacks a lot of info. Such as `rowRenderer`, `cellRenderer` (haven't seen this one in code, but found some mentions in previous issues e.g. #852) and so on and so force.
Those documentation articles tha are present by the moment are a bit confusing (e.g. although there is description for `Row` and `Cell` it is totally not clear how to use it and where to use it).

I've looked thru existing open and closed issues, related to documentation requests and it seems that all of them are closed by this moment. #904 , #195, #1155 

So I believe it would be really good to enrich existing documentation with more examples, provide missed descriptions, etc.

**Comment by alexchen1875** [comment]
like this #1447 #1193
in conclusion, how to control the react-data-grid with programming

**Comment by Ben-CA** [comment]
See: https://github.com/adazzle/react-data-grid/issues/2575
