### ISSUE TITLE
EditorPortal can not find document.body

### ISSUE THREAD

**Issue by PenguinOfThunder** [adazzle/react-data-grid#1450]
- Have you already searched for similar issues? Please help us out and double-check first!
Yes, found nothing
- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [X] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [X] IE 9 / IE 10 / IE 11
- [ ] Edge
- [X] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [X] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

Please include:
- What the current behavior is
  When double-clicking on a cell with a custom editor, an error is thrown
- What the desired behavior is
No error
- (If Bug) Steps to reproduce the issue
  The error is thrown from `componentDidMount` and `componentWillUnmount` of [EditorPortal](https://github.com/adazzle/react-data-grid/blob/master/packages/common/editors/EditorPortal.js)
and reads:
```
Exception: TypeError: Cannot read property 'appendChild' of null 
```

It appears to be caused by how the `EditorPortal` component gets the value for `editorRoot`; by accessing `document.body` upon the module being loaded. (Most likely the body doesn't exist at the time that line is executed.) I have confirmed that modifying the code at runtime to populate the editorRoot with document.body fixes the issue.

- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™

**Comment by amanmahajan7** [comment]
A new `editorPortalTarget` prop has been added to handle this case.  We also released an alpha version 6.0.2-0. Please give a shot and lets us know if everything is working as expected. Thanks
