### ISSUE TITLE
Dropdown Editor fires two events when value changes.

### ISSUE THREAD

**Issue by bmakan** [adazzle/react-data-grid#1452]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [x] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```
__Current behavior:__  
When using Dropdown Editor addon to edit a cell value, *onGridRowsUpdated* is called __twice__.

__Expected behavior:__
When using Dropdown Editor addon to edit a cell value, *onGridRowsUpdated* is called only __once__.

I edited CodeSandbox of example from the docs: https://codesandbox.io/s/76korjo91 (check the console).

**Comment by TatiTheFreaK** [comment]
Same here

**Comment by steamhammer** [comment]
Tried with the most recent `react-data-grid@6.1.0-0`. Issue is still there. As a workaround used debounce on passed callback.

```
debouncedGridRowsUpdateCb = _.debounce(() => { ... }, 300);
...
render() {
  return <ReactDataGrid
    ...
    onGridRowsUpdated={this.debouncedGridRowsUpdateCb}
    ...
  />

...
}
