### ISSUE TITLE
Filterable and sortable features, don't work properly when both are used at the same time.

### ISSUE THREAD

**Issue by vmsoftware** [adazzle/react-data-grid#146]
I'm trying to implement all features (or almost all) but when I try to add filterable and sortable features to the same data grid... the behavior is strange and it don't work properly.

Any idea?

Thanks in advance

**Comment by vmsoftware** [comment]
<img width="1219" alt="captura de pantalla 2015-12-19 a las 4 46 50 p m" src="https://cloud.githubusercontent.com/assets/16278865/11915340/2c8592cc-a670-11e5-86dd-57cdbdbc16b9.png">

**Comment by qosmy-michael** [comment]
It would be great to have both - otherwise it turns into an opinionated UX, a lot more limiting.

**Comment by bakesteve** [comment]
Yep - this is one we are aware of (and have hit) - its certainly not by design and is being looked at now.
Will add a link back here once we get the fix done

**Comment by cheahkhing** [comment]
in fact, it is still not working as expected. When you sort 1 column, type some filter, and then remove the filter, you'll see that the previous sorting is not being respected. Basically every filtering will reset the existing 'sort', which is probably an issue for those using sort and filter at the same time.

**Comment by jbgarr** [comment]
+1 Still seems broken.

**Comment by vmsoftware** [comment]
Any news?

**Comment by diogofcunha** [comment]
This is fixed after `1.0.23`

**Comment by avremel** [comment]
Still seems to be an issue for me: https://github.com/adazzle/react-data-grid/issues/846

Can anyone comment?
