### ISSUE TITLE
Feature proposal: Frozen / pinned rows

### ISSUE THREAD

**Issue by vileppanen** [adazzle/react-data-grid#1461]
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

I didn't manage to spot any documentation on this proposed feature, nor did find any existing issues.

It would be nice, if you could define certain rows to be pinned / frozen in the grid. Much like there's a way to define certain columns to be frozen. Ie. by default the header row is pinned to the top, but you could also define which other rows are pinned.

Pinning position could be specified:
- you could pin rows to the top of the grid
- you could pin rows to the bottom of the grid

Here's a brief sandbox, that tries to mimic the pinned row (currently hacked with just css, and only pinning to top demonstrated):
https://codesandbox.io/s/n9947njkl

**Comment by TimYi** [comment]
This is a useful but hard to implement feature. Support both frozen rows and frozen columns may harm the performance.
