### ISSUE TITLE
Resizing column with mouse when matrix is applied to parent div doesn't scale correctly

### ISSUE THREAD

**Issue by Michael-Tajmajer-Emrsn** [adazzle/react-data-grid#1465]
The PR for issue 940 was never applied.

Can this be added to master at some point in time?  I believe that the issue is still outstanding, resizing columns that have matrix's applied to them fails.

PR: https://github.com/adazzle/react-data-grid/pull/941

- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [X] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [X ] IE 9 / IE 10 / IE 11
- [X ] Edge
- [X ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [X] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by Michael-Tajmajer-Emrsn** [comment]
**What the current behavior is:** 
Have grid in div under matrix that has x scale factor, try to resize -- size of column does not match mouse position.

**What the desired behavior is:**
Size of column matches Mouse position.

The pull request is: #941 
https://github.com/adazzle/react-data-grid/pull/941

**Comment by Michael-Tajmajer-Emrsn** [comment]
Any hope that this couple line fix can be merged in?  

It would allow me to not have to maintain my fork so that we can use the grid with a matrix :-)

Anything else that I can provide to make this happen?

**Comment by Michael-Tajmajer-Emrsn** [comment]
Any news about merging in the PR that fixes this issue?

**Comment by Michael-Tajmajer-Emrsn** [comment]
Any updates on this?  It's a simple pull request, will it ever be acted upon?

**Comment by Michael-Tajmajer-Emrsn** [comment]
Any thoughts on merging this bugfix into the code?

It's only a few lines and fixes a pretty bixgissue!

**Comment by Michael-Tajmajer-Bentley** [comment]
Adding a comment for this issue's one year mark.  So, will somebody consider merging this PR?

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.
