### ISSUE TITLE
Edit cell window move up

### ISSUE THREAD

**Issue by kolesnikanton** [adazzle/react-data-grid#1468]
### Version of React JS
16.4
### Browser
Chrome
#### Current behavior
React-data-grid is in div which has position fixed. The page size is larger than size of browser window. When we move page to the end than react-data-grid show edit cell relative to the page and not this div. (See video)

#### Desired behvaior
React-data-grid show edit cell relative to the div which has position fixed.

### Video
https://drive.google.com/file/d/19cvy--cFa6LCU_6BJLgmq-nV94OEPfC8/view?usp=sharing

*It can see in version 5.0.1 and after. In version 5.0.0 it's okay*

**Comment by szogun1987** [comment]
It is fixed in 6.0.0+
