### ISSUE TITLE
Render single cell(s) in row based on row/column index

### ISSUE THREAD

**Issue by chriscarex** [adazzle/react-data-grid#1469]
### Which version of React JS are you using?
☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?
✅ Officially supported ✅
- [ ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox

---

### I'm submitting a ...
- [ ] 💡 Feature Request

---

### Issue Details

I am trying to change the background of a single cell in the row. I used rowRenderer but there's no way to get the column ID at the moment.

Would be nice to get the column ID or to have any other way to style a particular cell based on row/column coordinates.

Also, I should be able to get those coordinates before clicking on the cell.

I looked on the issues and googled around but didn't find anything similar, am I missing something?

**Comment by vickychu** [comment]
You can use the property "formatter". All you need to do is to put the extra messages in the "row" and the "column".
http://adazzle.github.io/react-data-grid/docs/examples/cell-formatting

**Comment by jaggukaka** [comment]
Hello, I tried to achieve this with formatter property, but it only changes the background of the text and not the entire cell, how to change the background of entire cell when data of the grid changes in realtime?
