### ISSUE TITLE
Ability to override sorting indicators via SortableHeaderCell renderer

### ISSUE THREAD

**Issue by sophielevens** [adazzle/react-data-grid#1470]
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ x ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is:
There is no indication that sortable columns are sortable.

- What the desired behavior is:
Enable users to see which columns are sortable. When a column is being sorted, change indicator colour to represent this.

- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

I would like to be able to provide a custom SortableHeaderCell renderer as I require a higher degree of customisation than is possible via CSS. My business requirements state that every sortable column should show both a descending and ascending sort indicator with the actively sorted column showing the sort indicator in a different colour. Currently the only way to achieve the above would be to directly modify the code inside of [SortableHeaderCell.js](https://github.com/adazzle/react-data-grid/blob/f1699777ec5f067aed3d0bee9446d9bdb9e3d661/packages/common/cells/headerCells/SortableHeaderCell.js)

**Comment by khizar** [comment]
is there a solution to this?
