### ISSUE TITLE
Define the scroll state of the grid

### ISSUE THREAD

**Issue by kazlibrowski** [adazzle/react-data-grid#1473]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

There does not seem to be a way to restore the grid to a specific scroll state, so that one can come back to a page with the grid showing precisely the same rows and columns as it was showing when the page was left.
The scrollToRowIndex partially addresses this issue (though it does not seem to work on initial render), but there does not seem to be a corresponding scrollToColIndex.

The motivation is to have a component that can be treated as being purely functional, i.e. defined entirely by its externally settable state.

Could this functionality be added?

**Comment by colindjk** [comment]
I am currently looking into a solution for this for my own project with functional components. I plan on trying to subclass ReactDataGrid and overwriting the `componentDidMount` function to look like this 

```js
  componentDidMount() {
    // below is how scrollLeft normally gets defined
    // this._scrollLeft = this.viewport ? this.viewport.getScroll().scrollLeft : 0;
    this._scrollLeft = this.props.initialScrollPosition ? this.props.initialScrollPosition : 0
    this._onScroll();
  }
```

I could make a pull request to the repo for the change, and see what happens. That being said, did you find another solution to the problem that doesn't involve monkeypatching / making a subclass of the `Grid` class?
