### ISSUE TITLE
Overscan prop not used

### ISSUE THREAD

**Issue by zekehernandez** [adazzle/react-data-grid#1475]
- Have you already searched for similar issues? Please help us out and double-check first!
Yes.
- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [x] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

I tried using the overScan prop on the ReactDataGrid, but changing the values did not accomplish anything. So I looked at the source, and it seems like the overScan prop is passed down to the Viewport, but nothing uses it. It seems like it should be used in utils/viewportUtils, but instead a const, OVERSCAN_ROWS (== 2) is used.

This isn't an urgent issue for me, and I might take a crack at it if I have the bandwidth, but I figure I should post it just as an FYI or something. Also I could be completely wrong about how/if overScan is being used, if that's the case, sorry!

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by BlaineBradbury** [comment]
I just encountered this as well.  Passing in an object for Overscan does not seem to have an effect.
