### ISSUE TITLE
Content Security Policy Issue for css included in Javascript Bundle file

### ISSUE THREAD

**Issue by AnkitCapitalOne** [adazzle/react-data-grid#1477]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ X] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ X] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ X] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
Css is included in Bundled Code file react-data-grid.js under dist folder.
Because of this react-data-grid can not be render-red without using "unsafe-inline" attribute in Content Security Policy Headers. 
Content-security-policy (CSP) settings contain the directive 'unsafe-inline', which effectively disables any protection for standard Cross Site Scripting attacks provided by CSP. 

- What the desired behvaior is
Css should not be there in javascript file.
Alternatively need steps to segregate css from bundled code of react-data-grid.
So, react-data-grid can be rendered without using "unsafe-inline" attribute in Content Security Policy Headers.

- (If Bug) Steps to reproduce the issue

Step 1 . Install react-data-grid with command 
npm install react-data-grid

Step 2. Go to react-data-grid.js file in node_modules at below path
node_modules/dist/react-data-grid.js

Step 3. Search for css included in react-data-grid.js file, example -
.react-grid-header , .react-grid-HeaderRow


- (If Feature) The motivation / use case for the feature
react-data-grid can be passed for Pen testing, which is failing in Content Security Policy Configuration.

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by pablovb** [comment]
Hi,

This is important. Have you taken into consideration re-opening this issue?
