### ISSUE TITLE
Make built in CSS optional?

### ISSUE THREAD

**Issue by zackify** [adazzle/react-data-grid#1480]
I see that this css file is required in 5 places: https://github.com/adazzle/react-data-grid/search?q=react-data-grid-header.css&unscoped_q=react-data-grid-header.css

Is there any way that it can be optional, so that we can customize the styling completely?

Also, I think it only needs to be required one time.

P.S. I looked at similar issues, but they were talking about making bootstrap optional.

Edit: I’ve tested this whole library now and bootstrap isn’t required for anything to work?

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

**Comment by larissa-n** [comment]
Is this on the roadmap?

**Comment by amanmahajan7** [comment]
We will be creating a separate CSS starting version 7. You can start using the alpha releases if you need this immediately 

https://unpkg.com/react-data-grid@7.0.0-alpha.1/dist/

**Comment by zackify** [comment]
Thanks for the heads up. It would be nice if you don’t auto close real issues when they have thumbs up or haven’t been replied to yet. 

Looking forward to v7! Thanks for the awesome work.

**Comment by amanmahajan7** [comment]
This has been fixed in v7 canary

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
