### ISSUE TITLE
Unable to resolve module 'immutable' when trying to import anything from react-data-grid-addons

### ISSUE THREAD

**Issue by liamzhang40** [adazzle/react-data-grid#1481]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
Unable to resolve module 'immutable' erros shows when I try to import anything from react-data-grid-addons. It solved by installing immutable separately. This should be worth mentioning in the README
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by jonnyarnold** [comment]
Just to add a bit more information to this, here's the stack trace I get when running a Webpack build:

```
ERROR in ./node_modules/react-data-grid-addons/dist/react-data-grid-addons.js
Module not found: Error: Can't resolve 'immutable' in '/Users/jonny/[My Project]/node_modules/react-data-grid-addons/dist'
 @ ./node_modules/react-data-grid-addons/dist/react-data-grid-addons.js 1:120-140
 @ ./node_modules/react-data-grid-addons/index.js
 @ ./assets/[My Code Here!].tsx
```

Looking through the code base, there's only one import of Immutable that isn't in a test or script, in [RowGrouperResolver](https://github.com/adazzle/react-data-grid/blob/f1699777ec5f067aed3d0bee9446d9bdb9e3d661/packages/react-data-grid-addons/src/data/RowGrouperResolver.js#L1); my guess is this is the root cause.

**Comment by ekros** [comment]
Same problem here. Is there any workaround for this?

**Comment by jonnyarnold** [comment]
@ekros #1484 should fix this. 

@liamzhang40 mentioned in the original issue that you can `npm install --save immutable` as a workaround for now.

**Comment by ekros** [comment]
Installing that package did the trick, thanks!

**Comment by szogun1987** [comment]
Valid solution is delete package-lock.json and node_modules for every package and then re-install them.
