### ISSUE TITLE
React-data-grid does not play well with other components that have Drag and drop capabilities

### ISSUE THREAD

**Issue by kfranco619** [adazzle/react-data-grid#1482]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

Please include:

**- What the current behavior is**
When using any of the drag and drop capabilities of the react-data-grid along with any another component who also uses drag and drop, an error will be thrown.
"Cannot have two HTML5 backends at the same time"

**- What the desired behvaior is**
I would like the react-data-grid to be imported with its own DndContext or be imported WithoutDndContext so that it can take in any defined DndContext.

**- (If Feature) The motivation / use case for the feature**
This would allow the react data grid to be used with many other components that have dnd capabilities.

**Comment by Brentox** [comment]
Confirming that this issue exists in the current build. Receiving error "Cannot have two HTML5 backends at the same time." when DragDropContext(HTML5Backend) already exists in project. Requesting a fix and/or temporary solution to this ticket. Upon research found other libraries have resolved this issue, so solution may be fairly simple. Please let me know about further details on this ticket.

**Comment by Brentox** [comment]
Found a current work around with this ticket that involves the manipulation of React lifecycle events. In short, you create a state variable that enables/disables the dragndrop components when mounted/unmounted. This method would require you to add this to all pages that have dragndrop components that would create the above error. This is a quick work around that seems to work in my application, and lets you use a defined DragDropContext(HTML5Backend) in your project with the current react-data-grid library. Please let me know if I am missing anything or if a better solution exists.

```
// Add state variable to show/hide dragndrop components
   constructor(props) {
        super(props);
        this.state = {
            show: false
        };
    }

// Upon mounting the component, enable the state variable to show dragndrop component
    componentDidMount() {
        this.setState({ show: true });
    }

// When unmounting, disable the state variable to hide dragndrop component
    componentWillUnmount() {
        this.setState({ show: false });
    }

// Add a check to the render function to allow the dragndrop component to show/hide 
// based on the state variable
    render() {
         return (
            <div>
                {this.state.show &&
                   <INSERT COMPONENTS TO BE RENDERED SUCH AS DATA-REACT-GRID>
                 }
           </div>
         };
    }
```

**Comment by kfranco619** [comment]
Ideally, I would love to be able to use a draggable container that would use the dragDropContext I already provide. Since I need to use multiple components that have Dnd capabilities, I would need to control the DragDropContext myself instead of each component making its own.

**Comment by Brentox** [comment]
> Ideally, I would love to be able to use a draggable container that would use the dragDropContext I already provide. Since I need to use multiple components that have Dnd capabilities, I would need to control the DragDropContext myself instead of each component making its own.

I agree. This is a highly desired feature. Right now, at least for my application, creating/destroying dragDropContext instances works, but it is a very temporary solution. Also found that if you are using react-router, you can simplify this work-around. But if you have multiple Dnd components rendered on one page, with how react-data-grid is working currently, it is not going to work.

**Comment by Brentox** [comment]
bump

**Comment by Brentox** [comment]
Still important and needed

**Comment by Hybueno09** [comment]
bump

**Comment by amanmahajan7** [comment]
`react-data-grid-addons` and hence `react-dnd` dependency will be removed in v7 

Check the changelog and examples on how add draggable columns
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--columns-reordering

https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/ColumnsReordering.tsx

**Comment by nileshlande12** [comment]
what should i do to fix this issue?
I'm on datagrid version 5.0.1
