### ISSUE TITLE
DropDownEditor small issue

### ISSUE THREAD

**Issue by tculig** [adazzle/react-data-grid#1483]
"react-data-grid-addons": "^6.0.2-0"

DropDownEditor doesn't work with onChange prop.
In the source I found:
 render() {
    return (
      select style={this.getStyle()} defaultValue={this.props.value} onBlur={this.props.onBlur} onChange=this.onChange} 
        {this.renderOptions()}
      </select>);
  }

Surely, it should be onChange={this.props.onChange}, no???

**Comment by zuice32** [comment]
Why did it just close this? I'm having the same issue

**Comment by tculig** [comment]
It was closed due to inactivity. I think I should have made a push request or something, but I don't have the time to figure out how to do that. If someone could do it or send me simple instructions...that'd be great.
