### ISSUE TITLE
Scrollbars Showing Up Unexpectedly

### ISSUE THREAD

**Issue by mklannan** [adazzle/react-data-grid#1486]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [X] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [X] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [X] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

The issue I’m experiencing is identical to issue #1042 which was closed due to inactivity. The vertical and horizontal scrollbars pop up at random times and it is tied to the window size. I haven’t set any minimums or maximums that would cause this.

Here is the video from issue #1042 : 
https://youtu.be/kdb9AKIwkwc

**Comment by lynnaeferguson** [comment]
For anyone still having this issue:

`'& .MuiDataGrid-virtualScroller': {
    overflowX: 'hidden',
    overflowY: 'auto'
  },`
