### ISSUE TITLE
Including the git repository in another package.json does not create dist files

### ISSUE THREAD

**Issue by omarish** [adazzle/react-data-grid#150]
When I include react-data-grid in another project's `package.json` with a link to the github URL (not using the npm project), like I have included below, the build process never includes the correct files and does not create a `dist` directory containing the full javascript files when I run `npm install`.

I can get this to work if I run `npm run prepublish`, but then have to commit the `dist` directory inside of `node_modules`.

``` json
{
  "peerDependencies": {
    "react": "~0.13.3"
  },
  "dependencies": {
    "react-data-grid": "adazzle/react-data-grid#master",
  },
  "scripts": {
    "start": "webpack --config config/webpack/development.config.js --watch --colors"
  }
}
```

**Comment by bakesteve** [comment]
yeah - we dont include the dist in git by design, so if you cant use npm, you will need a few extra steps
If you were using gulp, sulp-submodule should help. And sure its do-able via webpack too
https://www.npmjs.com/package/gulp-submodule
