### ISSUE TITLE
scrolling is glitched on iOS

### ISSUE THREAD

**Issue by lstkz** [adazzle/react-data-grid#1519]
### Which version of React JS are you using?

✅ Officially supported ✅
- [x] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [x] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request
---

### Issue Details

open http://adazzle.github.io/react-data-grid/docs/examples/frozen-columns on iPhone.
- Scrolling is without momentum effect. See [this](https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/).
- Fixed columns are shaking/moving by 2-5px when scrolling horiontally.

**Comment by BetterCallSky** [comment]
up

**Comment by brendonboshell** [comment]
I am also seeing this on Chrome (macOS), but (strangely) only when using the built-in display.

**Comment by rtman** [comment]
Would love to see a comment from the dev team on this, this glitching makes it really tough to use on ios.

**Comment by ardok** [comment]
Same like what brendonboshell said. 
I'm seeing it too on Chrome (MacOS) with built-in display.
With external monitor, it doesn't happen somehow.

**Comment by amanmahajan7** [comment]
We have improved the scrolling behavior in v7. Feel free to open a new issue if you are facing the problem

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
