### ISSUE TITLE
Custom CSS 

### ISSUE THREAD

**Issue by escanzanocloudcath** [adazzle/react-data-grid#1534]
I have a need to override a number of the default CSS in the theme directory. What is the recommended way of doing this? I have copied it to my own css file and made changes but they are not being used. Where should the overrides go?

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by amanmahajan7** [comment]
We are working on the next major version and it will have a separate CSS bundle. You can use the latest alpha release if you need it immediately. Also starting next version, we will only be publishing ES6 bundles so a custom bundler is required. 

https://github.com/adazzle/react-data-grid/releases

**Comment by phillipbritain** [comment]
@amanmahajan7 Is there any documentation available for the alpha release? Also, do you have a rough estimate on when the next major version will release?
