### ISSUE TITLE
Actions popup defined in frozen column, shows menu under the column

### ISSUE THREAD

**Issue by frontalicious-martijn** [adazzle/react-data-grid#1540]
- Have you already searched for similar issues? Please help us out and double-check first!
Yes

- Also, please don't be that person who deletes this template. It's here for a reason.
Sure

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

I've encountered that the actions popup is shown below a frozen column, while you'd expect it to be on top of it. If that is hard to do then it should at least show it next to the frozen column so the whole popup is visible.

You can already reproduce it to change the cellActions example on the website:
http://adazzle.github.io/react-data-grid/docs/examples/cell-actions
```
const columns = [
  {
    key: "firstName",
    name: "First Name",
    frozen: true
  },
...
```
![Screenshot 2019-03-27 at 13 56 01](https://user-images.githubusercontent.com/7541513/55077491-2d7e1700-5098-11e9-9cea-55f0b2c1e98b.png)

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by AdriSolid** [comment]
For those who want to quickly solve the issue without extending the library: simply apply the following css rule:

`css
.react-grid-HeaderCell--frozen {
      z-index: 3 !important;
}
`

Cheers!
