### ISSUE TITLE
Cell Range Selection cause an issue with enable cell select for editing

### ISSUE THREAD

**Issue by Moataz-Hammous** [adazzle/react-data-grid#1547]
If you enabled cell range selection and basic cell editing, there's an issue produced when you double click on a cell then select another cell you will find that value of the double-clicked cell override the currently selected cell
you can produce the issue from the following:[https://codesandbox.io/s/m580o3l48]( https://codesandbox.io/s/m580o3l48)

**Comment by mashaod** [comment]
I have the same issue.

**Comment by mashaod** [comment]
I've resolved it in my fork. 
You need to add this code in onSelectCellRangeStarted method (InteractionMasks.js)

`const { isEditorEnabled } = this.state;

if (isEditorEnabled) {
  this.closeEditor();
  return;
}`

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.
