### ISSUE TITLE
DropDownEditor is not working with React Data Grid with Overlay (Z Index and position)

### ISSUE THREAD

**Issue by MPrabhu** [adazzle/react-data-grid#1551]
With React Data Grid version 6.0.0 and 6.1 version, DropDownEditor is not showing in react data grid cell. code is placed at https://codesandbox.io/s/m7v1jnxyl9

**Comment by amanmahajan7** [comment]
`DropdownEditor` and the `Addons` package will be removed in v7. You can use an external component like `react-select`

Here is an example
https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/components/Editors/SelectEditor.tsx
https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/CommonFeatures.tsx#L85
