### ISSUE TITLE
Keyboard navigation on react data grid custom editor with semantic ui calendar date picker

### ISSUE THREAD

**Issue by johnstsai** [adazzle/react-data-grid#1559]
- Have you already searched for similar issues? Please help us out and double-check first!
Yes
- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

As semantic ui calendar official demo (first one)
https://arfedulov.github.io/semantic-ui-calendar-react/
After the calendar pops out, keyboard navigation is enable on the date pick

However, combine with RDG custom editor, somehow the keyboard is bonded with the data grid. I am wondering how can I resolve this issue. Or it is not achievable currently?

```
Please include:
- What the current behavior is
1. double click on date cells pop up the calendar
2. press keyboard arrow keys and the selected cell were changed, calendar disapears
- What the desired behvaior is
1. double click on date cell pop up the calendar
2. press Keyboard arrow keys that navigates on calendar dates and press enter to select
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

See third column for date https://codesandbox.io/embed/8l4jkor19

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.
