### ISSUE TITLE
What is the best way to update columns (name + number of columns)?

### ISSUE THREAD

**Issue by ruthienachmany** [adazzle/react-data-grid#156]
Hey,

Wondering what the best approach would be to update columns using react data grid? Specifically, I'm loading in a JSON and based on that the number of columns and their names should change from the initial state (along with the other data). Given the way columns are determined through props, it seems like this framework isn't built for editable columns based on state, but wondering whether I've understood this correctly, and whether you have any ideas on the best way to do this.

Thanks!

**Comment by malonecj** [comment]
You would need to manage this yourself in a new component wrapping ReactDataGrid. Your custom component should keep `columns` in state and based on your conditions should pass the necessary column set to ReactDataGrid as props.
