### ISSUE TITLE
Column click event is synthetic

### ISSUE THREAD

**Issue by DrogoNevets** [adazzle/react-data-grid#1560]
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [X] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [X] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [X] 🐛 Bug Report
- [ ] 💡 Feature Request

---

### Issue Details

On the column events onClick, the event that is passed is a synthetic event and thus the shift/ctrl key properties are not defined correctly, this is causing issues with a use case I have to behave differently if either of these keys are pressed..

**Comment by amanmahajan7** [comment]
Column events will be removed in v7. Take a look at changelog and examples on how to migrate

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--all-features
https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/AllFeatures.tsx#L205
