### ISSUE TITLE
<CheckboxEditor />, Uncaught TypeError: Cannot read property 'onCellChange' of undefined

### ISSUE THREAD

**Issue by ar2zee** [adazzle/react-data-grid#1562]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [x] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details
I have a problem with `CheckboxEditor` when I trying to change the value,
 
![Problem with `CheckboxEditor`](https://user-images.githubusercontent.com/15669289/55654947-57ca8580-57b8-11e9-9450-930fe5554fbb.png)

My CheckboxEditor component:
```
render() {
    return (
      <CheckboxEditor
        value={!!this.state.checkbox}
        onChange={this.onCellChange}
      />
    );
  }
```

I would like to see examples of work with this Component or better documentation, so it will be ease to understand right way to work with it, thank you.

**Comment by Luis-Palacios** [comment]
so... does anybody have an idea how to I set a checkbox editor on my grid? hopefully that it does not require a double click from the user in order to activate the checkbox?

**Comment by bmakan** [comment]
Yes, it does. I built a couple of custom editors for an internal company app and in order to activate any of them, the user needs to double click on the field, and then click again on the input element (I usually do this programatically via Element.click()).

**Comment by ar2zee** [comment]
> Yes, it does. I built a couple of custom editors for an internal company app and in order to activate any of them, the user needs to double click on the field, and then click again on the input element (I usually do this programatically via Element.click()).

Hello, but the purpose of `CheckboxEditor` you don't have to double click on a cell if you want to change the value... And the problem with it that `onCellChage` prop which seems like no longer exist or something.

**Comment by ar2zee** [comment]
Any thoughts or updates with this one ?

**Comment by ar2zee** [comment]
👀

**Comment by amanmahajan7** [comment]
`CheckboxEditor ` will be removed in v7. Take a look at changelog and examples on how to migrate

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
