### ISSUE TITLE
Calling a event within a React Component

### ISSUE THREAD

**Issue by willyneverdie** [adazzle/react-data-grid#1568]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [X ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ X] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ X] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is: 
rendering a grid from a React Class Component. Within the column onClick event, i'm trying to call a method like this: 
onDoubleClick: function(ev, args) {
                  this.handleOnClick(ev);
}
Getting this error: this.handleOnClick is not a function

- What the desired behvaior is
Execute the method within the Class Component from a column event
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature
Use React Class Component with React-Data-Grid

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by amanmahajan7** [comment]
`column.onClick` event has been remove in canary and we recommend upgrading. Also this issue does not seem to be related to grid. 

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
