### ISSUE TITLE
Not "dist" folder present

### ISSUE THREAD

**Issue by mohak1990** [adazzle/react-data-grid#157]
I am not able to download the grid from npm as my OS is 64 bit..(able to download without issues on 32bit OS) and if i download the zip file (without npm), there is no "dist" folder present.. Kindly suggest me the solution.

**Comment by omarish** [comment]
`npm run prebuild`

**Comment by mohak1990** [comment]
Will that help me to install grid in my 64-bit Processor??

**Comment by mohak1990** [comment]
Please tell me a solution.

**Comment by bakesteve** [comment]
we'll track the no dist folder in #150 but sounds like the root cause was #151 which should all be fixed (if not, we will track there)
