### ISSUE TITLE
Group name not visible when using "rowHeight"

### ISSUE THREAD

**Issue by bmakan** [adazzle/react-data-grid#1570]
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [x] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

When I specify `rowHeight` property, the group name isn't showing. Example below.
https://codesandbox.io/embed/xv9330ok2p

**Comment by amanmahajan7** [comment]
The old grouping API is removed in v7 canary. Please check the new example and let us know if you re still facing the problem
https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/Grouping.tsx 
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--grouping
