### ISSUE TITLE
have api in reat-data-grid v4 to control scroll back to selected cell?

### ISSUE THREAD

**Issue by wojiaofengzhongzhuifeng** [adazzle/react-data-grid#1572]
- Have you already searched for similar issues? Please help us out and double-check first!

https://github.com/adazzle/react-data-grid/issues/1292

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- ✅v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- ✅ Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- ✅ 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

is there any api to control scroll bar not to back to selected cell??

i am using react-data-grid@4.0.9, and this is result that i do not expect:

![](https://raw.githubusercontent.com/wojiaofengzhongzhuifeng/image-host/master/img/Apr-11-2019%2016-32-53.gif)

what i expect is 
![](https://raw.githubusercontent.com/wojiaofengzhongzhuifeng/image-host/master/img/6.gif)

is there any api can do this? or this is just a bug??

**Comment by wojiaofengzhongzhuifeng** [comment]
i can not update my react-data-grid library version. Have some api in v4.0.9 to do this or there is some hack method to do this ??

**Comment by amanmahajan7** [comment]
Unfortunately v4 is no longer supported. We recommend migrating to v7 canary

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
