### ISSUE TITLE
Adding new Columns Headers dynamicly

### ISSUE THREAD

**Issue by 3TanE** [adazzle/react-data-grid#1574]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [X] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ X] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x ] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

So In a Project of mine some user shall create Multiple Header Templates by Adding them to the table.
And than later safe the config. How ever i was only able to add 1 new collumn ,which would be rendered. Further more the state was set Correctly and props of the table has been set right.
I debugged it and this is what i found

line 5804 ff
if (!ColumnMetrics.sameColumns(this.props.columns, nextProps.columns, this.props.columnEquality) || nextProps.minWidth !== this.props.minWidth) {
	          var columnMetrics = this.createColumnMetrics(nextProps);
	          this.setState({ columnMetrics: columnMetrics });
	       }

this.props.columns and nextProps.Columns were already the same 
so createColumnMetrics() was never called. 

Further more in line 6504 ff

if (_this2._cachedColumns === columns) {
	      return _this2._cachedColumns; //#edit _this2._chachedComputedColumns;
	    }

_this2.cachedColumns(should be the old columns) is the same like columns(the newly added Columns) 
so it returned _this2._chachedComputedColumns which weren´t the new added Columns.

I don´t know wether is caused by using Reactjs 16.xx but it surly prevents you from performing a 
more or less rudementary task.

How ever by excluding the if and changing the return you can make it work like intended.
As far as i can tell without "impacting" the other functions

Greetings 
Tan
```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.
