### ISSUE TITLE
Does React Data Grid supports multi cell select and copy paste?

### ISSUE THREAD

**Issue by johnstsai** [adazzle/react-data-grid#1578]
I understand there is cellRangeSelection, however, it seems not be able to copy paste selected cells. Is it able to achieve multi cell select and copy paste on the according cells?

Many thanks

- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by Pohatta** [comment]
I was wondering the same thing. Did you see the solution below by @ZackKnopp? Worked for me.

https://gist.github.com/ZackKnopp/40fc0691feb03f0fba3e25e7353b73ae

**Comment by johnstsai** [comment]
Thanks for the response, yes I did reference that solution, wondering if it can be done not consecutive select

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.

**Comment by sunilbsharma** [comment]
Can you please share the example for copy and paste data from excel to react-data-grid? It will be great help.
thanks.
