### ISSUE TITLE
Resetting the grid after the required columns has been grouped

### ISSUE THREAD

**Issue by praneethpannala** [adazzle/react-data-grid#1579]
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [✅ ] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details
Hi Everyone,

I was trying to implement grouping concept for the columns in the plugin. While doing so, i have come across a bug in the official docs itself. 

Steps:
1. I have grouped 2 or 3 columns in the grid and implemented the concept
2. While trying to undo the implementation and revert the grid into the original state, i am unable to do so. The clickable buttons/column names over the grid to remove them is not working. Hence, we are not getting the flexibility of using the grouping concept in the plugin.
```
Here is Preview Link : [Movie](https://drive.google.com/file/d/1zUwtFZQHCj_21981iJ7SPEV-A8tilmNP/view)


I this a known issue or can some one help me out in resolving this?
The Best Issue Is A Pull Request™
```

**Comment by praneethpannala** [comment]
Fix:
onColumnGroupDeleted={columnKey => setGroupBy(ungroupColumn(columnKey))}


Team, please include this line in the code in order to rectify the issue.

Hope this helps for you guys!

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.
