### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by sandeep-prakash** [adazzle/react-data-grid#158]
Hi,

I see the following error:

Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.

I get this while running the basic example. Looks like it's an issue with multiple react modules being loaded. Is there a way to avoid this?

Regards,
SP

**Comment by jpdriver** [comment]
hey @sandeep-prakash -- hmm strange. there's a similar issue here https://github.com/adazzle/react-data-grid/issues/183

what browser are you using?

**Comment by txm** [comment]
I tried making the App use the same version of React as the react-grid-module.

It didn't help :)

**Comment by txm** [comment]
afaict this is resolved with React 14?

**Comment by bakesteve** [comment]
yep - fixed by #63
