### ISSUE TITLE
Reordering Rows - render issues.

### ISSUE THREAD

**Issue by ewholmes** [adazzle/react-data-grid#1583]
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x ] 🐛 Bug Report
- [ ] 💡 Feature Request

---

### Issue Details

- What the current behavior is
When dragging rows, the UI "breaks" in that it shrinks to seemingly inline elements. As seen in the[ documented examples ](http://adazzle.github.io/react-data-grid/docs/examples/row-reordering). Captured the issue [here](https://monosnap.com/file/z1cxhjCCqPXdNd85fY6DyGeDpJ1C4C).

- What the desired behavior is

Staying similar size of the container. Or, at least documented examples/classes/structure of the element created. It's not possible to inspect it to apply my own styles.

**Comment by amanmahajan7** [comment]
Please check the new re-ordering example in v7 canary and let us know if you are still facing the problem 
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--rows-reordering
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
