### ISSUE TITLE
 the editor position is wrong when the container is scrolled

### ISSUE THREAD

**Issue by hunter-jin** [adazzle/react-data-grid#1592]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

First of all, thank you very much! when the cell is editing, the editor position is wrong when the container is scrolled.

![image](https://user-images.githubusercontent.com/24447994/56470914-8ade6b80-647e-11e9-877d-9cd7a2c59df3.png)

![image](https://user-images.githubusercontent.com/24447994/56471024-04c32480-6480-11e9-98b2-47b2ddd51171.png)

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by amanmahajan7** [comment]
@hunter-jin Can you create a codesandbox example where we can  replicate this issue?

**Comment by hunter-jin** [comment]
[https://codesandbox.io/embed/j2koojo555?fontsize=14](https://codesandbox.io/embed/j2koojo555?fontsize=14)

There are 2 problems. 
1. the editor's z-index is 2, but the modal's z-index is 1000. I have to custome style of z-index 1001. Can I set the z-index property? Because sometimes I hope the editor's z-index is lower than modal(e.g. in normal page). sometimes I hope the editor's z-index is higher than modal(e.g. in modal) 
2. However, the modal is too high. The modal is scrolled when the cell is editing, the editor's position is wrong. 

Thanks!

**Comment by hunter-jin** [comment]
![image](https://user-images.githubusercontent.com/24447994/56711707-6fb17b80-675e-11e9-8d61-be04f1263d62.png)

**Comment by jmangel** [comment]
I added a style rule `.rdg-editor-container { z-index: 10051 !important; }`. Worked for me

**Comment by pradiktabagus** [comment]
> I added a style rule `.rdg-editor-container { z-index: 10051 !important; }`. Worked for me

![image](https://user-images.githubusercontent.com/12893340/74895466-45ebd400-53c4-11ea-9cae-59d8ec1e2025.png)

its work because z-index before my modal.

**Comment by mukesh210** [comment]
@hunter-jin Were you able to solve [https://codesandbox.io/embed/j2koojo555?fontsize=14](https://codesandbox.io/embed/j2koojo555?fontsize=14). We are also facing this problem and trying out various approaches but none of them is working.

**Comment by theonewithcurlyhair** [comment]
I had the same issue. The way I fixed it is by using  `editorTargetPortal` prop of react-data-grid.
I used `document.selectById` at first, and it solved the issue but not completely.  

My solution:

1.  Find the **selector** of the element where you want to display the editable container (I used _copySelectors_ in Chrome Inspector tools)
2. Assign it as a prop in the grid

The value of the props should like this

`editorPortalTarget={document.querySelector("#ID_OF_YOUR_CONTAINER > div > div > div > div:nth-child(2) > div > div > div:nth-child(2)")}`

Hope that helps someone

**Comment by amanmahajan7** [comment]
This is fixed in v7 canary and we recommend upgrading 
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos

**Comment by amanmahajan7** [comment]
If portal is used then the position needs to be manually set via scrolling.
