### ISSUE TITLE
Editable data grid's last row cells are not editable when using on Chrome

### ISSUE THREAD

**Issue by MonaiThang** [adazzle/react-data-grid#1594]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [x] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details
Please include:
#### What the current behavior is
The cells in the last row of an editable datagrid are not editable when these conditions are met:
1. Users are using Chrome or IE11 browser. Edge or Firefox do not have this issue.
2. The editable datagrid must have enough rows so it has a scrollbar.
3. When editing any cell in the last row of the editable data grid, if you press the down arrow key or go to the next cell to the right, you can't edit the current cell anymore, unless you go to any cell in the second to last row and go back to the cell in the last row that you originally wanted to edit.
See the gif below for an animated representation of what I just explained.
![DatagridBugExample](https://user-images.githubusercontent.com/2027837/56540210-659b4b80-65ab-11e9-8acd-37309e40496e.gif)

#### What the desired behavior is
The cells in the last row of an editable datagrid should be editable even when users move cursor downwards or to the right at the last rows in any browsers.

#### (If Bug) Steps to reproduce the issue
1. Create a React app using create-react-app.
2. Add an editable datagrid into the sample page. See code snippets for each file below:
App.js
```javascript
import React from 'react';
import ReactDataGrid from 'react-data-grid';
import logo from './logo.svg';
import './App.css';

const columns = [
    {key: "id", name: "ID", editable: true},
    {key: "title", name: "Title", editable: true},
    {key: "complete", name: "Complete", editable: true}
];

const rows = [
    {id: 0, title: "Task 1", complete: 20},
    {id: 1, title: "Task 2", complete: 40},
    {id: 2, title: "Task 3", complete: 60},
    {id: 3, title: "Task 4", complete: 80},
    {id: 4, title: "Task 5", complete: 90},
    {id: 5, title: "Task 6", complete: 100},
    {id: 6, title: "Task 7", complete: 160},
    {id: 7, title: "Task 8", complete: 260},
    {id: 8, title: "Task 9", complete: 360},
    {id: 9, title: "Task 10", complete: 460},
    {id: 10, title: "Task 11", complete: 560},
    {id: 11, title: "Task 12", complete: 660}
];

class App extends React.Component {
    state = {rows};

    onGridRowsUpdated = ({fromRow, toRow, updated}) => {
        this.setState(state => {
            const rows = state.rows.slice();
            for (let i = fromRow; i <= toRow; i++) {
                rows[i] = {...rows[i], ...updated};
            }
            return {rows};
        });
    };

    render() {
        return (
            <div className="App">
                <header className="App-header">
                    <img src={logo} className="App-logo" alt="logo"/>
                    <p>
                        Edit <code>src/App.js</code> and save to reload.
                    </p>
                    <a
                        className="App-link"
                        href="https://reactjs.org"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        Learn React
                    </a>
                </header>
                <body>
                <ReactDataGrid
                    columns={columns}
                    rowGetter={i => this.state.rows[i]}
                    rowsCount={12}
                    onGridRowsUpdated={this.onGridRowsUpdated}
                    enableCellSelect={true}
                />
                </body>
            </div>
        );
    }
}

export default App;
```
package.json dependencies
```json
{
    "react": "^16.8.6",
    "react-data-grid": "^6.1.0",
    "react-dom": "^16.8.6",
    "react-scripts": "2.1.8"
}
```
3. Run the app, open the app using Chrome or IE browser.
4. When the cell focus is at the last row of the editable datagrid, press either right or down arrow key to make the datagrid scrolls a little downwards further. When this happens, the cell will not be editable until you move the cell focus up to any cells in the second last row (See the gif animation below for the visual explanation).
![DatagridBugExample](https://user-images.githubusercontent.com/2027837/56540210-659b4b80-65ab-11e9-8acd-37309e40496e.gif)

#### (If Feature) The motivation/use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™

**Comment by remyasc** [comment]
I am having the same issue

**Comment by brakon** [comment]
+1, having the same problem

**Comment by yazhik12** [comment]
I'm experiencing the same issue, any workaround or updates?

**Comment by ashiqsultan** [comment]
Facing the same issue but only with the Chrome browser, works fine in Firefox.

**Comment by crabn3bula** [comment]
1. Same issue here. 
2. And also some delays are noticeable when opening the cell editor through a mouse click and they depend on the position of the line, i.e. the closer it is to the end of the list, the more noticeable it is. Sometimes the editor is not opened the first time, sometimes it does not open at all.
But at the same time, if you select a cell through the keyboard and open the editor through the enter key, then there are no delays at all.

**Comment by oktarama96** [comment]
> Not a final solution, but adding margin-bottom saved me.
> ![image](https://user-images.githubusercontent.com/40719338/115423259-f5594c00-a1fd-11eb-9e38-59cdd116fbd7.png)

how to add this custom style ?

**Comment by zdevgn** [comment]
> > Not a final solution, but adding margin-bottom saved me.
> > ![image](https://user-images.githubusercontent.com/40719338/115423259-f5594c00-a1fd-11eb-9e38-59cdd116fbd7.png)
> 
> how to add this custom style ? @zdevgn

`.react-grid-Viewport .react-grid-Canvas > div:last-child{
  margin-bottom: 20px;
}`

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.
