### ISSUE TITLE
This current version of "react-data-grid" is not compatible with latest "React 0.14.5"

### ISSUE THREAD

**Issue by shivkumar-itcube** [adazzle/react-data-grid#160]
This current version of "react-data-grid" is not compatible with latest "React 0.14.5", it’s expects react version 0.13.3. 

So are you planning to release this component to work with latest React 0.14.5. 
I have used component react-data-grid previously with react 0.13.x. Now I have to upgrade the react version to 0.14.5. So please let me know if any release is planned to work with react version 0.14.5 in near future?

**Comment by bakesteve** [comment]
Yep, that's tracked in #132
