### ISSUE TITLE
Value changes in grid are undone when scrolling

### ISSUE THREAD

**Issue by szogun1987** [adazzle/react-data-grid#1609]
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

### Issue Details
Please check [this sample](https://codesandbox.io/s/o9jzxqo7kz)
User changes edits some cell but doesn't confirm change
User scrolls to check something on cell out of visible part of grid
His/Her changes are undone

Bug is caused by componentDidUpdate in EditorContainer. I assume it is added to avoid floating editor out of the grid. I propose to add following code instead of calling commityCancel:
```
if (!this.changeCommitted && !this.changeCanceled) {
   this.commit({ key: 'Enter' });
}
```

**Comment by szogun1987** [comment]
Test that checks this behavior that should be placed in EditorContainer.spec.js
```
    it('should commit change if scrolled', () => {
      wrapper.setProps({scrollLeft: 100});
      expect(props.onCommit).toHaveBeenCalled();
    });
```

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.
