### ISSUE TITLE
new version with React 0.14.3 not working 

### ISSUE THREAD

**Issue by Dhaval8087** [adazzle/react-data-grid#161]
it's not working with new React 0.14.3

**Comment by omarish** [comment]
We're aware - read `package.json` - it's not supposed to yet.

https://github.com/adazzle/react-data-grid/blob/master/package.json#L22

**Comment by bakesteve** [comment]
yep - and anyone who wants to jump in - its (slightly stalled) WIP here #63 
We'll try and get a roadpmap together for when we plan on looking at that soon too
