### ISSUE TITLE
Column header doesn't move along with column data

### ISSUE THREAD

**Issue by benneyman** [adazzle/react-data-grid#1616]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [>] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [> ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ >] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```
When having a lot number of columns and when we horizontal scroll the column headers stay put while only the data moves. 

The column header should move along with the data so that they are in sync at any point.

I worked on this Cell edit example and I can see this issue there. The code is here. 
https://codesandbox.io/s/4j9ww96xjw

Here is a gif of the issue 
![rdg](https://user-images.githubusercontent.com/10482668/56935256-77ca3c00-6b0d-11e9-80d2-417689467631.gif)

**Comment by zekehernandez** [comment]
What is this supposed to do (on line 71)?:
```        
ref={element => {
    if (element !== null) {
        let base = element.base;
        base.onScroll = this.onScroll;
        this.rowOffsetHeight = element.getRowOffsetHeight();
    }
}}
```

I removed it and the scrolling works.

**Comment by amanmahajan7** [comment]
Scrolling and positioning have been improved in v7 canary and we recommend upgrading 

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
