### ISSUE TITLE
react-data-grid npm failing for react 0.14.0 version

### ISSUE THREAD

**Issue by nkiransingh** [adazzle/react-data-grid#163]
react-data-grid npm installation failing for react 0.14.0 version

**Comment by chenxiangxi** [comment]
I have the same problem

**Comment by omarish** [comment]
See https://github.com/adazzle/react-data-grid/issues/161

**Comment by nkiransingh** [comment]
Are there any plans to make it work in 0.14.0 ?

**Comment by jpdriver** [comment]
hi guys -- React 14 support is on our roadmap for support in the future, but we don't have a specific timeframe for it yet.

our minor version numbers mirror the React version, so the current release on npm (0.13.30) uses React 13.

there's an unfinished work-in-progress PR for v0.14.0 here https://github.com/adazzle/react-data-grid/pull/164
