### ISSUE TITLE
Resize column malfunction in v6.1.0

### ISSUE THREAD

**Issue by gmicsa** [adazzle/react-data-grid#1637]
### Which version of React JS are you using?

✅ Officially supported ✅
- [ x] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x ] 🐛 Bug Report
- [ ] 💡 Feature Request

### Issue Details

Hi!

Using version 6.1.0, when you try to shrink a column, instead of the column becoming smaller, the column becomes larger (the right margin of the column moves to the right when you start dragging to the left side).

This does not happen in v5.0.5 and smaller.

See: [https://codesandbox.io/s/yp3j9wv92v](https://codesandbox.io/s/yp3j9wv92v)

where I use v6.1.0 for both grid and addons.

Thanks,
Georgian

**Comment by amanmahajan7** [comment]
The behavior is fixed in v7 canary
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
