### ISSUE TITLE
LESS colors as variables, and LESS files with the distribution

### ISSUE THREAD

**Issue by Ciantic** [adazzle/react-data-grid#1647]
I'm trying to use the react-data-grid with different theme, naturally any theme the package provides does not work for another person.

Thus I suggest 

1. Colors (maybe padding too, or font-sizes if any) should be coded with LESS variables.
2. LESS files is bundled with the NPM distributed package

There is an example with @blueprintjs/core see UNPKG: https://unpkg.com/@blueprintjs/core@3.15.1/src/

They provide the source with the distribution.

This allows each project to recompile the LESS files easily just by rewriting the color variables in own package (no need to copy or edit the LESS files provided by the package, just redefine colors).

In reality there needs to be a one more file `variables.less` and each file import's that, it should not contain CSS itself, just variables. Then provide all less files with the distribution.

**P.S.** I noticed that dropping the LESS files in this project to [CSS2LESS](http://kronus.me/cn/css2less/) converter gets the job almost done (converters tend to collect the colors as variables too).

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.
