### ISSUE TITLE
missing phantom on fresh installs

### ISSUE THREAD

**Issue by jpdriver** [adazzle/react-data-grid#165]
can we just add this as an `npm` package? obviously pretty minor, but could be roadblock to newcomers? i'm all about reducing friction :smile: 

also for what it's worth downloading it manually and adding it to my `~/.bash_profile` didn't work but an `npm install phantomjs -g` did.

<img width="1062" alt="screen shot 2016-01-09 at 1 34 47 pm" src="https://cloud.githubusercontent.com/assets/2393035/12229783/d1fe125e-b842-11e5-9ac2-ac0b1600bd01.png">

**Comment by diogofcunha** [comment]
As we are not using phantom for our testing and it isn't working at all I would recommend to drop it.

@malonecj
