### ISSUE TITLE
Filtering rows resulting in 0 rows shown disables horizontal scrolling

### ISSUE THREAD

**Issue by sontek** [adazzle/react-data-grid#1654]
- Have you already searched for similar issues? Please help us out and double-check first!
Yes!  But its closed even though its not fixed:

https://github.com/adazzle/react-data-grid/issues/1371

### Which version of React JS are you using?

✅ Officially supported ✅
- [X] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [X] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [X] 🐛 Bug Report
- [ ] 💡 Feature Request

---

### Issue Details
When filtering by a value that does not exist in any rows, no rows are displayed (intended) and horizontal scrollbar disappears. This becomes problematic when the grid's columns overflow. This is reproducible on the example site

http://adazzle.github.io/react-data-grid/docs/examples/column-filtering
Entering q in date filter resets the scroll and locks it, essentially locking the grid and requiring a reload to do anything.

**Comment by sontek** [comment]
I hacked it by doing the following:

```
        let rows = this.state.rows;
        let rowGetter = this.rowGetter;

        if (this.state.rows.length === 0) {
            rows = [{}];
            rowGetter = () => rows[0];
        }

```

**Comment by braxtonb** [comment]
I have found adding the following CSS rule is also a potential workaround:

```
.react-grid-Canvas div:nth-child(2) {
  height: 100%;
}
```

https://codesandbox.io/s/oib0o

**Comment by amanmahajan7** [comment]
This behavior is fixed in v7 canary and we recommend upgrading

https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--header-filters (try to reduce the window size)
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
