### ISSUE TITLE
rowGroupRenderer access to grouped rows

### ISSUE THREAD

**Issue by DrogoNevets** [adazzle/react-data-grid#1656]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [X] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [X] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [X] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details
When grouping, the `rowGrooupRenderer` function does not have access to the grouped rows. EG for adding a count of rows within that group.

Can we add this please PDQ?

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by amanmahajan7** [comment]
Old grouping api has been removed. Please check the new example and lets us know if there are any issues

https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--grouping
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
