### ISSUE TITLE
Missing releases from the changelog and missed issue from v6

### ISSUE THREAD

**Issue by JSoet** [adazzle/react-data-grid#1660]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

Hi, this is more a documentation issue, I tried to ask in the slack channel but no one responded... 

I was mostly just wondering about the changelog, it seems like the last couple releases have been missed in the changelog
![image](https://user-images.githubusercontent.com/4523613/57928928-480f8800-78b2-11e9-8ce0-431a801babfc.png)

In particular I was wondering about this issue:
https://github.com/adazzle/react-data-grid/pull/1421

It seems to have been merged into v5 and then a merge was missed or something, and it was merged into vNext?
https://github.com/adazzle/react-data-grid/pull/1564

But I tried on v6 and it's still there... I'm not sure if it's already in the branch and it just needs to be released, or if it was actually missed from v6?

And finally I'll just also ask if there's some kind of roadmap, because I can see that v7 is being released soon (I assume?), I was just wondering what will be changed there and if we should wait to upgrade until it's released...

**Comment by sr1977** [comment]
Is there an update to this at all? Just looking a potentially using RDG, but this bug is a showstopper for us.

**Comment by nstepien** [comment]
Closing in favor of #2575
