### ISSUE TITLE
react data grid render one character

### ISSUE THREAD

**Issue by pat12345** [adazzle/react-data-grid#1662]
Hello,

 ` import ReactDataGrid from 'react-data-grid';
const [rows, setRows] = useState([]);
const columns = [{ key: "", name: "Code", editable: true },
        { key: "delete", name: "Action", editable: false}
    ];
function loadcode(){
........service call.... setRows(codes.Tcode.split(','));
}
    function rowGetterTest(index) {
      //  console.log(rows[index]);
        return rows[index];
    };
return( <ReactDataGrid
                columns={columns}
                rowGetter={rowGetterTest}
                rowsCount={rows.length}              
                rowSelection={true}
                onGridRowsUpdated={onGridRowsUpdated}
            />);`

I see single character in the data grid.
I also see column names and data grid with two rows (this is expected - but value is single character).
my array looks like this
(2) ["CKT", " RH"]
0: "CKT"
1:" RH"

My datagrid look like below
 code     Action
K
R

Any idea - why is it not printing whole string?

react version 16.8.4
react data grid  6.1.0

**Comment by pat12345** [comment]
I have created function and exactly mimic the format described in this example - of service object and it is working now.
So i am closing this issue.


![rarray](https://user-images.githubusercontent.com/6570215/58124757-faaa5800-7bdc-11e9-8b9b-17bc6032200c.PNG)



![rdatagrid](https://user-images.githubusercontent.com/6570215/58124779-06961a00-7bdd-11e9-83fb-31e652a446a0.PNG)

**Comment by priyankalxi** [comment]
I am facing same issue , please let me know the solution

**Comment by priyankalxi** [comment]
@pat12345  https://github.com/pat12345  
I am facing same issue , please let me know the solution
