### ISSUE TITLE
V6 no longer have columns virtualized

### ISSUE THREAD

**Issue by dangxquang** [adazzle/react-data-grid#1665]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ x ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ x ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ x ] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
Generally, I tried both RDG v4 and v6. V4 have a semi-virtualized column that is not visible in the viewport. But v6 just render all columns. That makes v6 suffer from performance when there are too many columns
- What the desired behvaior is
V6 should also have column-virtualized for better performance
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by dangxquang** [comment]
@amanmahajan7 can you confirm this behaviour of v6?

**Comment by amanmahajan7** [comment]
It is the same behavior in v6 and we have improved virtualization in v7 canary
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--a-million-cells
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
