### ISSUE TITLE
Add row with blink effect

### ISSUE THREAD

**Issue by ivanrogh** [adazzle/react-data-grid#1673]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [x ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ x ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ x] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

Hello, i really like react data grid and i am new in development react, i am trying to make a test and i did some search on the net and i didnt find nothing about this. 

1) I created a button to add new row each . It is  (random data even id)
2) i tried to add blink on row (like exchange order book) when the row appears.
3) everything works till i click on button more than 1 time, cause the blink effect is on index row and when i add new row sort by random id the index change for the row added before.

I really dont know how to add effect class css and the effect track the id row even index change, that driving me crazy.

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.
