### ISSUE TITLE
Blank page is rendered on Internet Explorer 11. 

### ISSUE THREAD

**Issue by Dev-rahul** [adazzle/react-data-grid#1675]
Blank page is getting rendered while running on IE 11. It works fine on all other browsers.

`import React from "react";
import ReactDataGrid from 'react-data-grid';

const columns = [
  { key: "id", name: "ID" },
  { key: "title", name: "Title", show: true },
  { key: "complete", name: "Complete" }
];

const rows = [
  { id: 0, title: "Task 1", complete: 20 },
  { id: 1, title: "Task 2", complete: 40 },
  { id: 2, title: "Task 3", complete: 60 }
];

class DataTable extends React.Component {
  state = { columns, rows };

  onChangeShow = () => {
    /* let newColumn = [...this.state.columns]; */
    let newColumn = columns.filter(column => column.show === true);
    this.setState({ columns: newColumn });
  };

  render() {
    return (
      <div onClick={this.onChangeShow}>
        <ReactDataGrid
          columns={this.state.columns}
          rowGetter={i => this.state.rows[i]}
          rowsCount={3}
          enableCellSelect={true}
        />
      </div>
    );
  }
}

export default DataTable;`

**Comment by amanmahajan7** [comment]
`react-data-grid` v7 canary no longer supports IE11

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
