### ISSUE TITLE
Can't find variable: document

### ISSUE THREAD

**Issue by LukyiiN** [adazzle/react-data-grid#1676]
I can't get the library running. The error code on emulator writes Can't find variable: document. I tried to google everywhere and i didn't find any situation with it. 
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/51359146/58861471-bd4ecb80-86ae-11e9-9733-c0789b6447f1.png">

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.
