### ISSUE TITLE
Disable horizontal scrolling

### ISSUE THREAD

**Issue by neelmanisehgal** [adazzle/react-data-grid#1677]
Hey,

I am trying to display multiple tables on the same row horizontally. I want to disable the horizontal scroll of the table and let the outer div containing all components handle scrolling.

How to approach this issue?

Thanks!

![image](https://user-images.githubusercontent.com/8106057/58879218-74f6d400-86d5-11e9-9f1e-b558df450c21.png)

![image](https://user-images.githubusercontent.com/8106057/58879201-66102180-86d5-11e9-8a2a-f44e2ebedc48.png)

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [X ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [X] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by amanmahajan7** [comment]
Scrolling is controller by the number of columns grid need to display and there is no easy way to disable it. It may be better to use a plain html table for your use case
