### ISSUE TITLE
react-data-grid-addons@next ships without type declarations

### ISSUE THREAD

**Issue by MxFr** [adazzle/react-data-grid#1678]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

---

### Issue Details

The addons module for the `next` version does not contain types, while the regular `react-data-grid` ships with them.

A very short glance at the source code shows that the ̀ react-data-grid-addons`  `package.json` does not contain a `types` field. Is in possible that that might be the issue?

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by amanmahajan7** [comment]
Typescript migration is still WIP in progress and we do not officially support types yet. Keep and eye on the @next branch as we will add types soon
