### ISSUE TITLE
BUG: Freezing Columns breaks Filter rendering

### ISSUE THREAD

**Issue by LBWright** [adazzle/react-data-grid#1679]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

Freezing a column breaks AutoComplete, MultiSelect and SingleSelect filters. The filters still function appropriately, however the dropdown is hidden behind the frozen columns. 

Expected behavior:
The dropdown filter menu appears over the column. I've attached screenshots.
To reproduce, set `frozen` to `true` when defining columns and set your filter to `AutoComplete`, `MultiSelect`, or `SingleSelect`. 

Screenshot attached. The column to the left is frozen. The Column on the right is not frozen.
![Screen Shot 2019-06-04 at 3 12 05 PM](https://user-images.githubusercontent.com/36030324/58954170-01e57000-875e-11e9-8162-1d3f52063c97.png)
![Screen Shot 2019-06-04 at 3 12 13 PM](https://user-images.githubusercontent.com/36030324/58954171-027e0680-875e-11e9-9111-ff972a768c75.png)

**Comment by kentrh** [comment]
From what I can tell they both have `z-index: 2;` when this combination occurs.

**Comment by amanmahajan7** [comment]
This behavior should be fixed in v7 canary. Feel free to open a new issue if your run into more issues

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
