### ISSUE TITLE
Pressing hyphen while cell is selected will not trigger edit mode

### ISSUE THREAD

**Issue by niklas-heeros** [adazzle/react-data-grid#1682]
- Have you already searched for similar issues? Please help us out and double-check first!
**Yes**
- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [X] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [X] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [X] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

Please include:
- What the current behavior is
Pressing hyphen while cell is selected won't trigger edit mode. Even though we are using React 16.X, this bug occurs in https://adazzle.github.io/react-data-grid/docs/examples/simple-grid
- What the desired behvaior is
The hyphen key triggers edit mode as other keys do
- (If Bug) Steps to reproduce the issue
1. Select a cell
2. Press hyphen - the cell won't go into edit mode and hyphen is not entered into the cell
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™

**Comment by niklas-heeros** [comment]
I did a little bit more investigation and noticed that in Firefox hyphen/dash keyCode is 173, but it's 189 on other browsers. Could be the reason.

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.
