### ISSUE TITLE
Multi-select with shift stopped working in v5

### ISSUE THREAD

**Issue by JSoet** [adazzle/react-data-grid#1686]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [x] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

- What the desired behaviour is
Starting in v5 the shift select of multiple rows stopped working. Previously in v4 if you selected an item, and then hit shift and clicked on another item then it would select all the items in between. In v5 this functionality disappeared and I couldn't find any evidence in the changelog that this was done on purpose.

- What the current behaviour is
Now when you hit shift nothing happens, it works just like when you didn't hit shift

You can see this in the codesandboxes here... Here is the row selection sandbox example from the docs:
https://codesandbox.io/s/v0zj8qmw6y?from-embed
and here is a fork of it with the version of RDG changed to 4.0.8:
https://codesandbox.io/s/rdg-row-selection-y4m1b
There you can see how the shift select works
But you can try and upgrade to 5.0.0 and you'll see that the shift select is gone

**Comment by amanmahajan7** [comment]
This should work as expected in v7 canary
https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/HeaderFilters.tsx
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
