### ISSUE TITLE
Console error after Empty rows view rendered with i18n translations

### ISSUE THREAD

**Issue by Thilagm** [adazzle/react-data-grid#1692]
- Have you already searched for similar issues? Please help us out and double-check first!
  yes
- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [x] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details
Using empty rows view along with i18n translations (used i18nNext) throws console error when row added and clicked

index.js:2178 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in t (created by Canvas)
    in div (created by Canvas)
    in Canvas (created by Viewport)
    in div (created by Viewport)
    in Viewport (created by Grid)
```
Please include:
- What the current behavior is
 console error is thrown
- What the desired behvaior is
console error should not be thrown
- (If Bug) Steps to reproduce the issue
  1. Render react data grid with row in it,
  2. through application delete the row and empty rows view is rendered. 
  3. Add row to the grid through application and click on the row, 
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by Thilagm** [comment]
Code sand box example https://codesandbox.io/s/rdg-cell-editing-h47c6

**Comment by Wstrueber** [comment]
> Code sand box example https://codesandbox.io/s/rdg-cell-editing-h47c6

It looks like the problem has nothing to do with i18n translations. The issue occurs when EmptyRowsView is rendered.

Following the code sandbox example:
1. Open the embedded sandbox console
2. Click the button Render "Empty Rows View"
3. Click on any column (I.E. ID)

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.
