### ISSUE TITLE
Create better documentation for sorting

### ISSUE THREAD

**Issue by oliverwatkins** [adazzle/react-data-grid#1693]
Can you please document how to implement sorting without using the new react hooks? 

Last time I used this grid component it took me five minutes to implement the sorting. Now it is taking me over five hours to implement this feature because of these new react hooks.

Improvements to React is not supposed to make it 10 times slower to implement things.

Please document clearly and give various examples.

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ *] v16

### Which browser are you using?

✅ Officially supported ✅
- [*] Chrome

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by saulfrank** [comment]
I cannot get sorting to work - all the examples use function and the rest of the examples use class. Its near impossible to work it out.

**Comment by amanmahajan7** [comment]
This will be address when we release v7 stable. You can check the example in the meantime. Thanks for your patience 
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
