### ISSUE TITLE
Feature request: Better extendable/configurable filters

### ISSUE THREAD

**Issue by blaues0cke** [adazzle/react-data-grid#1694]
### Which version of React JS are you using?

☣️ Not officially supported, expect warnings and errors ☣️
- v16.8.6

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [X] Chrome

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [X] 💡 Feature Request

---

### Issue Details

It would be great to have more extendable/configurable filters. For example: Just to change the `placeholder` of [NumericFilter.js](https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid-addons/src/cells/headerCells/filters/NumericFilter.js) by keeping as much code as possible from the original filter, I have to do something like this:

```
import React       from 'react';
import { Filters } from 'react-data-grid-addons';
import I18n        from 'i18next';

Filters.NumericFilter.prototype.render = function () {
    const inputKey = 'header-filter-' + this.props.column.key;

    return (
        <div>
            <input
                key={inputKey}
                type={'text'}
                placeholder={I18n.t('numberFilterPlaceholder')}
                onChange={this.handleChange}
                onKeyPress={this.handleKeyPress}
            />
        </div>
    );
};

export default TableNumericFilter;
```

It would be great to get an easier access to this values using something like a factory method or at least something like `getPlaceholderText` to avoid overwriting the whole `render`method.

Also it would be great to have a simple `TextFilter` to make it easier to extend this one. I had to write this filter on my own since I also wanted to edit the placeholder text there (but I am not able to set the `PropType` of `column` to a more concrete value:

```
import React     from 'react';
import PropTypes from 'prop-types';
import I18n      from 'i18next';

class TableTextFilter extends React.Component {
    filterValues (row, columnFilter, columnKey) {
        const lowerCaseSearchTerm   = columnFilter.rawValue.toLowerCase();
        const lowerCaseSearchTarget = row[columnKey].toLowerCase();

        return lowerCaseSearchTarget.indexOf(lowerCaseSearchTerm) > -1;
    }

    handleChange = (event) => {
        const value = event.target.value;

        this.props.onChange({
            filterTerm:   value.length > 0,
            column:       this.props.column,
            rawValue:     value,
            filterValues: this.filterValues
        });
    };

    render () {
        const inputKey = 'header-filter-' + this.props.column.key;

        return (
            <input
                key={inputKey}
                type={'text'}
                placeholder={I18n.t('enterTextPlaceholder')}
                onChange={this.handleChange}
            />
        );
    }
}

TableTextFilter.propTypes = {
    onChange: PropTypes.func.isRequired,
    column:   PropTypes.any
};

export default TableTextFilter;
```

What do you think?

**Comment by amanmahajan7** [comment]
Filters have been re-written in v7 canary and we have removed `react-data-grid-addons` package so uses must create their own filter components now

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--header-filters
https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/HeaderFilters.tsx
