### ISSUE TITLE
Range Collumn sorting not work with negative numbers

### ISSUE THREAD

**Issue by thejdavid** [adazzle/react-data-grid#1695]
- Have you already searched for similar issues? Please help us out and double-check first!
yes
- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ x] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x ] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

Hello,

There seems to be an issue when storing negative number on a range. Not sure if bug or enhancement. 
The normal pattern for inputing range on number filtering is " 1-10" 
```
- What the current behavior is
Works for 1-10
Works for -1-0
Doesn't work for -1-10
Doesn't work for -10-(-1)

- What the desired behvaior is
I'd expext to be able to range on negative value ranges.
- (If Bug) Steps to reproduce the issue
Populate a column with both positive and negative numbers and try to :
Range from negative to positive
Range from a high negative to a low negative

```

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.
