### ISSUE TITLE
cellRangeSelection with Filter conflict, use cellRangeSelection can't use Filter

### ISSUE THREAD

**Issue by ruohone** [adazzle/react-data-grid#1698]
cellRangeSelection with Filter conflict, use cellRangeSelection can't use Filter

**Comment by Gitii** [comment]
I think, I am expericing a similar issue: 
If the prop `cellRangeSelection` is populated, the filter dropdown closes on the first mouse up event. A selection of items in dropdown is not possible. The dropdown just closes itself after opening.

Workaround:
Press and hold the left mouse button and select the dropdown item by right clicking.

**Comment by CoverNetIT** [comment]
Is it auto blur?

**Comment by functionportal** [comment]
cellRangeSelection fundamentally breaks this otherwise excellent grid. Using the cellRangeSelection attribute hijacks all focus making any other input fields unusable across the page. Additionally, using cellRangeSelection makes editing cell content impossible.

**Comment by simhallq** [comment]
Any fixes?

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.
