### ISSUE TITLE
Re-ordering(sorting) is not working

### ISSUE THREAD

**Issue by suryarsp** [adazzle/react-data-grid#1699]
I am currently using React version **15.6.2** and react data grid version **^5.0.4-2**.
I couldn't sort the items (re-order) and its behavior is not working as expected.

![image](https://user-images.githubusercontent.com/21018485/60015380-fa502180-96a0-11e9-9c1b-50e9f0dad876.png)

**Comment by amanmahajan7** [comment]
v5 is not longer supported. Please check the latest demos

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
