### ISSUE TITLE
Register package with bower

### ISSUE THREAD

**Issue by aidanlister** [adazzle/react-data-grid#17]
It doesn't seem registered at the moment:
```
bower install --save react-data-grid
bower                        ENOTFOUND Package react-data-grid not found
```

Installing with ```bower install adazzle/react-data-grid --save``` also does not work, the src files are ignored.

**Comment by malonecj** [comment]
yeah sorry, just realised the new project is no longer registered with bower. We don't want to include the dist folder in the git repo so we will probably look to publish the dist folder to a new repository and register that one on bower.

Until we get that one done, the package is only available via npm

**Comment by scvnc** [comment]
So, I feel you on including the dist folder in the git repo.. seems messy.  However I discovered a trick which makes that workflow a little cleaner. https://gist.github.com/scvnc/c5d36731661d5933abf1

bower (and jspm) support would be greatly appreciated

**Comment by SerialVelocity** [comment]
@malonecj Following the page @scvnc linked, it seems like this could be done for all releases quite easily. It would be great for bower to be supported by your library.

**Comment by bakesteve** [comment]
yeah - nice trick, we'll take a look
