### ISSUE TITLE
Editable input moving out of place when window size adjusted

### ISSUE THREAD

**Issue by kasbah** [adazzle/react-data-grid#1701]
### Which version of React JS are you using?

- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [x] Firefox

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

---

### Issue Details

When updating the [simple editable cells example](https://adazzle.github.io/react-data-grid/docs/examples/default-editor) to react-data-grid@6.1.0 ([forked sandbox](https://codesandbox.io/s/rdg-cell-editing-owv2d)) the focused input stops adjusting width/position properly. 

v5.0.1: https://cloud.monostable.co.uk/rdg1.webm ([mp4](https://cloud.monostable.co.uk/rdg1.mp4))
v6.1.0: https://cloud.monostable.co.uk/rdg2.webm ([mp4](https://cloud.monostable.co.uk/rdg2.mp4))

EDIT: latest version that works at all with the example is v7.0.0-alpha5 and that seems to have the same issue.

**Comment by alexchen1875** [comment]
when Scroll up and down got the same result. 5.x or 6.x

**Comment by ManalLiaquat** [comment]
I was wondering that this happens only in modal, but when I render it without modal, this problem occurs there too. Need a fix for it

**Comment by SteveDowsett** [comment]
I have just noticed this issue also when scrolling up and down the page, is there any way to resolve this. We arnt it a position to update to the latest canary version right now as too many breaking changes from v6.

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.
