### ISSUE TITLE
Last Frozen column overlaps first none frozen column.

### ISSUE THREAD

**Issue by ronenmalka** [adazzle/react-data-grid#1703]
version:

- "react-data-grid": "^6.1.0"
- "react": "^16.8.6"
 

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

### Issue Details

```
When using frozen columns, the last frozen column overlaps and hide some of the next column.

![image](https://user-images.githubusercontent.com/47978855/60801999-a6edd100-a180-11e9-9230-0cbbb6d97fa0.png)

Not using any formater for the cells.
```

**Comment by yazhik12** [comment]
I'm having the same issue

**Comment by qili26** [comment]
What's the img exactly? The img link is in a code block which doesn't display in the page.

**Comment by yazhik12** [comment]
It's this one, i downloaded it through the link in issue details
![github_issue_#1703](https://user-images.githubusercontent.com/29010046/68693680-8a95e280-052c-11ea-81fd-f6355bfdcc2d.png)

**Comment by qili26** [comment]
@yazhik12 
Did you use a customized row renderer? It seems like the general cell position is not calculated correct. Currently if you use `master` (v6) or `next` (latest alpha), you need to use `this.props.renderBaseRow` for proper `ref` setting to be used by RDG.

**Comment by yazhik12** [comment]
Hi @qili26 , thank you for helping me. i'm not using any customized row renderer. I tried renderBaseRow (for v6), but couldn't make it work . Due to the deadline, i just added an empty non-editable column to make some space.

**Comment by amanmahajan7** [comment]
This behavior should be fixed in v7 canary and we recommend upgrading 

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
