### ISSUE TITLE
Are the docs for contributing up to date?

### ISSUE THREAD

**Issue by marcusegues** [adazzle/react-data-grid#1704]
### Which version of React JS are you using?
☣️ Not officially supported, expect warnings and errors ☣️
- [ x] v16.x.x

### Which browser are you using?
✅ Officially supported ✅
- [x] Chrome

### I'm submitting a ...
- [x] 💡 Feature Request

### Issue Details

I would like to contribute a PR for a small feature request. I followed the instructions [in the docs](https://adazzle.github.io/react-data-grid/docs/contributing) but I seem to be missing something. Where is the npm script that I am supposed to run, `dev-server`?
The available scripts are in `package.json` are:
```
  "scripts": {
    "docs": "node docs/utils/docsGen.js",
    "test": "jest",
    "test-dev": "jest --watch",
    "postinstall": "lerna bootstrap --no-ci",
    "prebuild": "node tools/buildStylesheets.js",
    "build": "lerna run build",
    "build-commonjs": "lerna run build-commonjs",
    "start": "node webpack-dev-server.js",
    "eslint": "eslint --report-unused-disable-directives --ext js,ts,tsx --max-warnings 0 -f codeframe --cache --color packages/react-data-grid/src packages/react-data-grid-addons/src tests examples",
    "fix-eslint": "npm run eslint -- --fix",
    "web": "cd website && npm run start"
  },
```
If I run `yarn run start`, I get a server at port 8080 showing nothing.

**Comment by marcusegues** [comment]
By the way, the feature request is for [this](https://github.com/adazzle/react-data-grid/issues/644)

Being able to define the `key` in `columns` definition to support nested objects. The linked issue does offer a way to do it and it works, but I think it breaks things like grouping.

**Comment by yusunglee2074** [comment]
npm run start

gave me about all example folders,
```
ERROR in ./examples/scripts/example0*-built-in-editors.js
Module not found: Error: Can't resolve 'react-data-grid-addons' in '/Users/yusunglee2074/Desktop/study/temp/react-data-grid/examples/scripts'
 @ ./examples/scripts/example06-built-in-editors.js 10:0-61 13:21-28 14:24-34
 @ ./examples/components/Examples.js
 @ ./examples/components/App.js
 @ ./examples/index.js
 @ multi webpack-dev-server/client?http://localhost:8080/ webpack/hot/dev-server ./examples ./packages/react-data-grid/style/react-data-grid.less ./packages/react-data-grid-addons/style/react-data-grid-addons.less ./packages/react-data-grid-addons/node_modules/react-select/dist/react-select.css
```

**Comment by qili26** [comment]
@yusunglee2074 
Try run `npm run build` once and then `npm start`. I remember it could fix the issue.

**Comment by nstepien** [comment]
Closing in favor of #2575
