### ISSUE TITLE
If user has scrollbars set to ‘always’ in macOS, react-data-grid automatically shows a vertical scroll bar, even if none is required.  Is there a way to prevent this?

### ISSUE THREAD

**Issue by Matt-Hill-Harness** [adazzle/react-data-grid#1708]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

react-data-grid: 3.0.11
react: 15.6

If user has scrollbars set to ‘always’ in macOS, react-data-grid automatically shows a scroll bar, even if none is required.  Is there a way to prevent this?
![image](https://user-images.githubusercontent.com/29221369/60929314-b0049e00-a265-11e9-9793-595d954996e7.png)

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [x] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

react-data-grid: 3.0.11
react: 15.6

If user has scrollbars set to ‘always’ in macOS, react-data-grid automatically shows a vertical scroll bar, even if none is required.  Is there a way to prevent this?
![image](https://user-images.githubusercontent.com/29221369/60929314-b0049e00-a265-11e9-9793-595d954996e7.png)

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.
