### ISSUE TITLE
custom rowRenderer row flickrs when partially shown

### ISSUE THREAD

**Issue by ppaul** [adazzle/react-data-grid#1712]
just checked this example https://adazzle.github.io/react-data-grid/docs/examples/row-renderer
and noticed that there are some flickering visual issues when the first row is only partially shown (half hidden by scrolling vertically)
```

**Comment by xpacman** [comment]
Still no progress with this? It makes my life kinda hard...

**Comment by deanp70** [comment]
@xpacman @ppaul I just had this issue myself, and it was caused by setting rowsCount prop to a number larger than the amount of rows that actually existed (i.e. setting `rowsCount={20}` when `rows.length=17`).

Making it so the rowCount doesn't exceed the actual row length fixed it for me.
