### ISSUE TITLE
Optional configuration to move to next cell on commit by pressing enter

### ISSUE THREAD

**Issue by niklas-heeros** [adazzle/react-data-grid#1715]
- Have you already searched for similar issues? Please help us out and double-check first!
yes
- Also, please don't be that person who deletes this template. It's here for a reason.
sure
- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [x] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [x] v15.5.x
- [x] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [x] IE 9 / IE 10 / IE 11
- [x] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [x] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

It would be nice to have a way to configure grid to navigate to next cell on pressing enter to commit a cell. Currently moving can be done only with tab and arrow key(s).

This could be accomplished by adding something like `onCellCommitNavigationKeys` configuration on grid level or alternatively enabling onCommit event handlers on cells.

Seems like at least accountants are used to navigate to next cell by pressing Enter. Most likely because they are mostly using numpad when filling data into grids.

**Comment by avalanche1** [comment]
Would be really nice to have two options: 'down' and 'left'

**Comment by avalanche1** [comment]
@amanmahajan7 , is this maybe possible right now? (I'm on `7.0.0-canary.16`)
This has become a strong requirement in our project.

**Comment by amanmahajan7** [comment]
This can be achieved using the new `onCellJeyDown` prop
