### ISSUE TITLE
'enableShiftSelect' does not work.

### ISSUE THREAD

**Issue by moory** [adazzle/react-data-grid#1716]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [*] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [*] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [*] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

[enableShiftSelect]
Officially provided demo does not work:
https://adazzle.github.io/react-data-grid/docs/examples/row-selection

**Comment by underfisk** [comment]
Same issue here, and also disabling is not working (i'm looking to disable the shift selection in my table)

**Comment by partynikko** [comment]
It seems to have stopped working when v5.0 was released. Latest v4 it was working properly.
Might dig into it.

**Comment by ggcatu** [comment]
Same issue? https://github.com/adazzle/react-data-grid/issues/1686

**Comment by amanmahajan7** [comment]
This will be fixed in V7
https://github.com/adazzle/react-data-grid/pull/1762

**Comment by rzwc** [comment]
I was wondering if this ever ended up being implemented in version 7?

**Comment by amanmahajan7** [comment]
This is fixed in v7 canary and we recommend upgrading 
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos

**Comment by jmjuanico** [comment]
@amanmahajan7 i can't seem to find from the demos how to enableShiftSelect. is this still supported on your latest version?
