### ISSUE TITLE
Based on URL parameters, how we can apply the filter to table

### ISSUE THREAD

**Issue by rakeshmanjunatha** [adazzle/react-data-grid#1718]
For example:

URL- **https://localhost:8000?name=rakesh&id=2**

based on above params **name** and **id**, i need to filter the table.

Thanks in advance.

**Comment by keymastervn** [comment]
@rakeshmanjunatha Depending on _how_ you gonna fetch the params value to your React Component's store using `componentDidMount`, then, you can trigger `handleFilterChange` at the time.

Please take a look on the example https://codesandbox.io/s/r57ox1p39q
ref: https://reactjs.org/docs/state-and-lifecycle.html

**Comment by rakeshmanjunatha** [comment]
Thanks for the suggestions, but how we can trigger/call **handleFilterChange** manually.
For this **handleFilterChange** function we need to pass **filter** property right? @keymastervn

**Comment by keymastervn** [comment]
@rakeshmanjunatha although I am not using `react-data-grid`, the documentation seems achievable for filters on mounting.

In this demo, they are using react hooks for setting filter (L107) 
> https://codesandbox.io/s/qqlxyk43j9

It means we can `setState` to update filters, but first you should get its data structure.
```
componentDidMount() {
  this.setState({
    filters: {} // your structure here
  })
```

IMO it is better to ask for bugs or improvements in a FOSS repo, this case folks on stackoverflow can support you really well, this issue should be closed.

**Comment by amanmahajan7** [comment]
We have updated the filter implementation. Please check the demo

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--header-filters
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
