### ISSUE TITLE
How can I override the Enter key handler when editing a cell with a custom editor?

### ISSUE THREAD

**Issue by ssebs** [adazzle/react-data-grid#1719]
### Which version of React JS are you using?

✅ Officially supported ✅
- [x] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details
I'm trying to use react-select as an editor for one of my columns, and it works using the mouse, but I want to be able to type and hit enter to save the result. 

To do this, I'd like to have the enter handler work for react-select, but the react-data-grid editor enter handler takes over and keeps the value as it was.

I'd like for this to work with arrow keys as well, since it just moves the cell instead of selecting in the react-select.

Example below.

![Example](https://i.imgur.com/5ReXJfw.gif)

**Comment by amanmahajan7** [comment]
This needs to be handled in the editor
- It needs to call `onCommit` when enter is pressed.

https://github.com/adazzle/react-data-grid/blob/26f4dafe68fbebef312ea7c146b44f039d48c1b9/docs/examples/custom-editors.md#editor-props

**Comment by ssebs** [comment]
Am I doing this correctly? It doesn't seem to commit the changes. 

Would it be possible to show me an example?

Part of the column definition
```javascript
...
{
    key: "ContactID",
    name: "Contact",
    width: 200,
    resizable: true,
    editable: true,
    formatter: <OwnerColRender contacts={contacts} />,
    editor: <OwnerEditor contacts={contacts} {...props} />
},
...
````

Editor
```javascript
class OwnerEditor extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            contacts: [...this.props.contacts],
            value: this.props.value
        };
    }
    getValue() {
        return { ContactID: this.state.value };
    }
    getInputNode() {
        return ReactDOM.findDOMNode(this).getElementsByTagName("input")[0];
    }
    handleChange = id => {
        this.setState({ ...this.state, value: id.value });
    };
    render() {
        return (
            <Select
                options={this.state.contacts}
                name="dropdown"
                defaultValue={
                    this.state.contacts[
                        this.state.contacts.indexOf(
                            this.state.contacts.filter(
                                option => option.value === this.props.value
                            )[0]
                        )
                    ]
                }
                onChange={this.handleChange}
                onKeyDown={e => {
                    if (e.key === "Enter") {
                        console.log("Hit enter");
                        this.props.onCommit();
                    }
                }}
            />
        );
    }
}
```

Rendering of the ReactDataGrid
```javascript
<ReactDataGrid
    columns={columns}
    rowGetter={i => runSteps[i]}
    rowsCount={runSteps.length}
    minHeight={gridHeight}
    onGridRowsUpdated={onGridRowsUpdated}
    enableCellSelect={true}
    dragable={false}
/>
```

Thank you!

**Comment by grassick** [comment]
@ssebs Did you ever figure out how to embed a react-select and have the keys work? I'm stuck on the same issue.

**Comment by ssebs** [comment]
@grassick I didn't, I ended up just using the browser default select box with some CSS to make it look like react-select.

**Comment by grassick** [comment]
@ssebs Got a solution! I make escape actually commit and then override the rest of the keys:

```
    return <BlockKeys onEscape={this.props.onCommit}>
      <CreatableSelect 
        options={options} 
        value={option} 
        ref={(rs) => this.selectRef = rs } 
        onChange={this.handleChange}
        isClearable={false}
      />
    </BlockKeys>
  }
}

/** Blocks arrow keys and enter from propagating to allow react-select to handle keys */
const BlockKeys: React.FC<{ onEscape: () => void }> = (props) => {
  const handleKeyDown = useCallback((ev: React.KeyboardEvent<HTMLDivElement>) => {
    // On escape, do commit
    if (ev.keyCode == 27) {
      ev.stopPropagation()
      props.onEscape()
    }
    if ([37, 38, 39, 40, 13].includes(ev.keyCode)) {
      ev.stopPropagation()
    }
  }, [])
  return <div onKeyDown={handleKeyDown}>
    {props.children}
  </div>
}

```
