### ISSUE TITLE
Lack of migration documentation and off. page bugs.

### ISSUE THREAD

**Issue by igoriok1994** [adazzle/react-data-grid#1720]
- Have you already searched for similar issues? Please help us out and double-check first!
---> Yes. No results
- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [x] IE 9 / IE 10 / IE 11
- [x] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

Hi,

1. I can't find migration documents from V4 to V6. Maybe somewhere they exists?
2. Why on off. page version of react-data-grid is 5.0.4, when npm version is 6.1.0?
![image](https://user-images.githubusercontent.com/37294916/61458005-4d508800-a972-11e9-86cf-13f41c7e416e.png)
3. Why major count of URL's (inside github and adazzle.github.io) is not working?

**Comment by ShantanuNair** [comment]
Also curious—what does the page version of react-data-grid mean? On our project we are working on v5 as that's what the documentation was reflecting. Now I'm wondering about migrating to v6, or if that's been abandoned (some clarification here??) v7 directly, depending on how stable it is.

**Comment by nstepien** [comment]
Closing in favor of #2575
