### ISSUE TITLE
If items are deselected from another component, select-all button stays checked

### ISSUE THREAD

**Issue by LBWright** [adazzle/react-data-grid#1721]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

Please include:
- What the current behavior is
If I deselect all selected items from a different component, or an external button or anything that causes the grid to re-render with no selected items, the select-all button at the top of the grid stays checked when no items are selected
- What the desired behavior is
The selected button at the top should not be selected if there are no children selected
- (If Bug) Steps to reproduce the issue

Use RDGs codesandbox

https://codesandbox.io/s/rdg-row-selection-85ptx
add a `refresh` class method
```
  refresh = () => {
    this.setState({ selectedIndexes: [] });
  };

```
Add a button with a click handler to the render method

```
       <span>
          <button onClick={this.refresh}>reset</button>
          {this.state.selectedIndexes.length} {rowText} selected
        </span>
        <ReactDataGrid ... />
```

Select all Items using the select-all button, then click the refresh button

- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™

![Screen Shot 2019-07-22 at 9 48 26 AM](https://user-images.githubusercontent.com/36030324/61643348-4c687080-ac68-11e9-8fbd-f5c69a81b1ff.png)

**Comment by amanmahajan7** [comment]
This is a known bug

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.
