### ISSUE TITLE
ReactDataGrid is not updating when changing `rowsCount`

### ISSUE THREAD

**Issue by kaminskypavel** [adazzle/react-data-grid#1722]
- Have you already searched for similar issues? Please help us out and double-check first!
Yup

- Also, please don't be that person who deletes this template. It's here for a reason.
😆

- Thanks!

---

### Which version of React JS are you using?
```    "react": "^16.8.6" ```

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [X] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [X] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

Please include:
- What the current behavior is
when dynamically adding rows and updating `rowsCount={this.state.rows.length}`
then grid seems to have a hard time recalculate height and rerender.

- What the desired behvaior is
should rerender just fine. current workaround it to force it by adding `key={Math.random()}`
to ReactDataGrid component

- (If Bug) Steps to reproduce the issue
Attached a video showing the issue.
you can see in the console the row (on state) are growing, but the component is not rerendering until I change the viewport, which fore a re render
![2019-07-22_22-26-12](https://user-images.githubusercontent.com/4253088/61659592-78b7d780-acd0-11e9-82e1-0dc6735011da.gif)

- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™

**Comment by kaminskypavel** [comment]
after second review, adding `key={Math.random()}` will drive you insane 🤪, since each time the rdg renders the focus jumps to the first cell on the first row, which makes it impossible to work with. 

a better solution is  `rowsCount={this.state.rows.length && 1000}`

**Comment by nirpeled** [comment]
@kaminskypavel I used your solution and it seems to be working but feels like a real hack, any chance you found a better solution since then?

**Comment by amanmahajan7** [comment]
`rowsCount` prop will be removed in favor of a new `rows`prop. Please check with v7 canary if you still facing any issues

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
