### ISSUE TITLE
Remove the title prop in SimpleCellFormatter

### ISSUE THREAD

**Issue by Alienover** [adazzle/react-data-grid#1723]
https://github.com/adazzle/react-data-grid/blob/4e9efe98907c0bed0da07ecfdd5ef7f579601db5/packages/react-data-grid/src/formatters/SimpleCellFormatter.tsx#L7-L9

Once you set the title prop to sth, there would be a tooltip while hovering the element. I think it's better to remove it or add a props to toggle it.

**Comment by amanmahajan7** [comment]
I think the best solution is to create a separate `formatter` without a title. I am sure there are some projects that need a title and it would not be possible to support both in the default formatter

**Comment by Alienover** [comment]
OK, thanks for that.
