### ISSUE TITLE
Input (type=file) field closes the custom editor 

### ISSUE THREAD

**Issue by Pigmalion** [adazzle/react-data-grid#1725]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by Pigmalion** [comment]
When opening an input (type=file) dialog for file browsing on a custom editor, the editor closes yet the browse window for the file system appears OK. I assumed that this is sort of onBlur or the onClickOutside functionality. Any workarounds?

**Comment by Pigmalion** [comment]
When opening an input (type=file) dialog for file browsing on a custom editor, the editor closes yet the browse window for the file system appears OK. I assumed that this is sort of onBlur or the onClickOutside functionality. Any workarounds?

**Comment by ShantanuNair** [comment]
Experiencing the same issue on Canary, using 3rd party react-dropzone component.

```

        <Dropzone noDragEventsBubbling onDrop={acceptedFiles => this.setState({currentFile: acceptedFiles})} multiple={false} minSize={1} maxSize={100000000}>
        {({getRootProps, getInputProps, isDragActive, isDragAccept, isDragReject}) => (
          <div {...getRootProps()}>
            <input {...getInputProps()} /> 
            <p>Drag 'n' drop some files here, or click to select files</p>
            <div>{this.state.currentFile && this.state.currentFile.map(file => (
                <li>{file.path} - {file.size} bytes</li>
            ))}
            </div>
          </div>)}
        </Dropzone>
```

Here, with the props required for dropzone to work, on opening the file dialog box, the editor closes - preventing me from uploading the file.

However, without the props for dropzone, the editor stays open (unlike what OP experienced). How do I enforce this behavior while using dropzone props?
