### ISSUE TITLE
Examples not loading?

### ISSUE THREAD

**Issue by mjackstone6** [adazzle/react-data-grid#1731]
- Have you already searched for similar issues? Please help us out and double-check first!
Yes

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [x] IE 9 / IE 10 / IE 11
- [x] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

Examples doesn't seem to be loading on the github.io page.
Tried on all browsers both with and without extensions such as adblock.
There isn't any errors in the console either so not quite sure whats wrong.

For example, https://adazzle.github.io/react-data-grid/docs/examples/simple-grid looks like this:
![Image](https://i.imgur.com/571C4h5.png)

**Comment by amanmahajan7** [comment]
Checkout the new examples 
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
