### ISSUE TITLE
Grouping example is broken(no row expanding + can't delete group)

### ISSUE THREAD

**Issue by schvabodka-man** [adazzle/react-data-grid#1733]
---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [x] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [ ] 💡 Feature Request
---

### Issue Details

```
Hi, i've tried to implementing a grouping and for me expanding(hiding/showing rows) in grouping didn't worked. I entered RDG examples(https://adazzle.github.io/react-data-grid/docs/examples/drag-cols-to-group) and - SURPRISE, expanding rows in official example doesn't work too(and deleting too). I've tried it on both chrome and firefox and got the same results
```

**Comment by vineshkumar87** [comment]
Yes. We are also facing the same issue.

As @schvabodka-man  said, the example given for grouping is not working as expected. 

I would like to have a look to fix it ourself. But i couldn't find the git source for react-data-grid-addons. If anyone knows where i can get the complete source code react-data-grid-addons, kindly please let me know.

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.
