### ISSUE TITLE
Custom cell editors causing "extra click" and commit problem on IE11

### ISSUE THREAD

**Issue by christopherhill** [adazzle/react-data-grid#1738]
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.8.6

---

### Which browser are you using?

✅ Officially supported ✅
- [x] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

---

### Issue Details
I'm working with an enterprise application that is using react-data-grid and has, in particular, quite a lot of custom cell editors. We recently upgraded to `6.1.0` but we are now running into an issue with IE11.

Initially, the grid was throwing an exception on `EditorContainer` line 234 (screenshot attached).`getEditor()` was null and thus causing the chained `.getValue()` to fail.

<img width="535" alt="Screen Shot 2019-08-22 at 10 20 20 AM" src="https://user-images.githubusercontent.com/1033564/63535647-cfc6ed00-c4c6-11e9-8cea-bb0ffc16490b.png">

After a deep dive, I found that an extra `commit()` was taking place after navigation to another cell. I tracked the issue down to the `<ClickOutside onClickOutside={this.commit} />` component recently introduced in `EditorContainer`.

The problem seems to be that (at least in our case using IE11), in `ClickOutside.js` the `document.removeEventListener...`(line 66) is either not removed at all, or is not being removed fast enough. It may be that `componentWillUnmount` is sluggish in this environment. I was able to reproduce the exact issue that I'm experiencing in all modern browsers by commenting out the `document.removeEventListener...`.

For now, I have resolved the problem by downgrading to `6.0.1`, however this is not ideal.

I'm not sure as to the best way to solve this. One obvious solution is to check whether this.getEditor() is valid in the `commit()` method. I found that solved the problem. But in reality, the issue seems to be with the `<ClickOutside>` component listeners.

```

**Comment by christopherhill** [comment]
I added a PR (above). Not sure this really fixes the underlying behavior, but it stops the grid from throwing. Ultimately, the downgrade left us in too broken a state. For anyone else who may be suffering from this issue, I solved the problem by intercepting the `onClickCapture` event used in the new wrapper. You can add this to all column definitions:
```
    events: {
      onClickCapture: function (e: React.SyntheticEvent) {
        e.stopPropagation()
      },
```

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.
