### ISSUE TITLE
Unresponsive Script in #/all-features-immutable

### ISSUE THREAD

**Issue by littlebee** [adazzle/react-data-grid#174]
To reproduce:
goto http://adazzle.github.io/react-data-grid/examples.html#/all-features-immutable
select "Add Row"
tab to county
enter: King
tab to title
enter: Dr.
tab to first name
enter: Bee
tab to last name
enter: W
then click out of the field to another cell without hitting enter, and...

beachball

OSX 10.10.5
Firefox 36.0

**Comment by jpdriver** [comment]
hey @littlebee, thank you v. much! :100: for including the exact steps to reproduce this :smile:

**Comment by diogofcunha** [comment]
Hi @littlebee.

Is this still affecting you? 
Cheers
