### ISSUE TITLE
Cell tooltip

### ISSUE THREAD

**Issue by semihucari** [adazzle/react-data-grid#1745]
Hi,

I saw that cell has a tooltip prop. I have columns and rows objects. I also have a couple of formatters, but I have no idea how to use the tooltip. I also couldn't find any examples about it. Can you please give me an example about cell tooltip?

**Comment by GBincaz** [comment]
I also had some cell renderers where the displayed tooltip was "[Object, object]".
Surrounding it with a span with a title attribute solves the issue:

```
<span title="New tooltip">
    <MyCellRenderer/>
</span>
```

**Comment by qili26** [comment]
The RDG cell tooltip is being deprecated, so your options will be 
1. just use html `title`
2. wrap your own tooltip (tons of 3rd lib you can use) within the cell.

**Comment by diez-esteban** [comment]
Has anyone succeed to insert a tooltip on grid's cell? Thank you.

**Comment by amanmahajan7** [comment]
As @qili26 mentioned you can use a custom formatter and add a toolip

```
columns: [
  { 
    key: 'tooltipColumn',
    formatter(props) {
     return <Tooltip value={...}>{props.row.value}</Tooltip>},  
  }
]
```
