### ISSUE TITLE
Select all checkbox doesn't update when all the individual checkboxes are selected.

### ISSUE THREAD

**Issue by dufferzafar** [adazzle/react-data-grid#1746]
This is a dupe of #1256 which was closed due to lack of inactivity. I don't know what the right protocol in this situation is. Commenting on the older issue or filing a new one.

### Which version of React JS are you using?

✅ Officially supported ✅
- [x] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [x] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is

Select all checkbox doesn't update when all the individual checkboxes are selected.

- What the desired behvaior is

The select all checkbox should update its state from the individual boxes as well.

- (If Bug) Steps to reproduce the issue

+ Suppose there are 3 rows all containing check boxes, and 1 "Select all" checkbox, and all of these boxes are unchecked.
+ Check the boxes of all 3 rows one by one
+ The "Select all" box will still be unchecked.

```

**Comment by amanmahajan7** [comment]
This will be fixed in v7
https://github.com/adazzle/react-data-grid/pull/1762

**Comment by amanmahajan7** [comment]
This should be fixed now
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
