### ISSUE TITLE
Updated Docs for v6.x

### ISSUE THREAD

**Issue by tlyon3** [adazzle/react-data-grid#1752]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

I'm trying to implement this in a React app I'm creating but I can' t seem to use any of the add ons (specifically the Context Menu). The docs, I've noticed, are for v5.0.4.

Are there docs for v6.x? If so, where can they be found?

Thanks in advance!

**Comment by alexchen1875** [comment]
+1
but....From the issue and changelog, this project seems to have been abandoned.

**Comment by coljung** [comment]
@alexchen1875 was it ?

**Comment by mklosterboer** [comment]
6.x was abandoned. A couple of guys are slowly working on 7.x.

**Comment by ShantanuNair** [comment]
> 6.x was abandoned. A couple of guys are slowly working on 7.x.

Just curious - has this been documented anywhere explicitly?

**Comment by mklosterboer** [comment]
https://github.com/adazzle/react-data-grid/pull/1658#issuecomment-494959941

@ShantanuNair

**Comment by nstepien** [comment]
Closing in favor of #2575
