### ISSUE TITLE
disappearing bottom rows on variable row heights

### ISSUE THREAD

**Issue by semihucari** [adazzle/react-data-grid#1753]
Hi;

I use 30px and 60px row heights depending on the row, i.e., some are sub-headers and they are narrow compared to the regular ones. I realized that scrolling upwards causes a couple of bottom rows to disappear. As I change the parameters like 'rowCount' or 'rowHeight', I either get this behavior or constant flicking on the scrollbar.

To repeat this behavior, you can just edit the row intercepting example with 'height' instead of 'color'.

I attached a gif to visualize the problem.
![rdg-bug](https://user-images.githubusercontent.com/38683246/65043355-6de19200-d963-11e9-8fed-d210a500a374.gif)

**Comment by amanmahajan7** [comment]
`react-data-grid` does not support variable row heights. It is possible to use a `rowRenderer` and change `rowHeight` but scrolling does not work correctly. At  this moment we do not have plans to support variable row heights.
