### ISSUE TITLE
Disable checkbox per individual rows

### ISSUE THREAD

**Issue by CPedrini** [adazzle/react-data-grid#1754]
### Which version of React JS are you using?

✅ Officially supported ✅
- [X] v15.4.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [X] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [X] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [X] 💡 Feature Request

---

### Issue Details

Hi, currently I have a simple grid with rowSelection implemented. For some business reason I need to be able to remove or, preferably, disable the checkbox on a few specific rows.

I would like to be able to implement this by using the default checkbox implementation but I couldn't found any specific property that allow me to get the desired behavior.

In the meantime, should I just simply implement a specific frozen column with a custom cell action?

**Comment by marshallcool** [comment]
so what is next ?

**Comment by igoriok1994** [comment]
Also you can write custom cell formatter instead of using standard checkboxes. There you can access whole row object and write a if-else statement (show/hude your custom checkbox for individual rows)

**Comment by amanmahajan7** [comment]
You can achieve this in v7 using a custom select column

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--all-features
https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/CommonFeatures.tsx#L45 (you can modify the `SelectColumn`)
https://github.com/adazzle/react-data-grid/blob/canary/src/Columns.tsx#L7
