### ISSUE TITLE
Cell editable even if set to false while having an editor

### ISSUE THREAD

**Issue by partynikko** [adazzle/react-data-grid#1758]
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

If a column has `editable: false` but also has a custom editor via the `editor` prop, the cell will be editable anyway.
I expect the cell to not be editable even if it has an `editor` prop.

Code example:
https://codesandbox.io/s/rdg-editors-dropdown-editor-8nsl4?fontsize=14

**Comment by qili26** [comment]
https://github.com/adazzle/react-data-grid/blob/next/packages/react-data-grid/src/ReactDataGrid.tsx#L158

Have you tried taking a look at this attr?

**Comment by perusopersonale** [comment]
Found same issue

> https://github.com/adazzle/react-data-grid/blob/next/packages/react-data-grid/src/ReactDataGrid.tsx#L158
> 
> Have you tried taking a look at this attr?

This will surely work, but I think editable option should work also with custom editors

**Comment by qili26** [comment]
@perusopersonale legacy code for checking editable is messy, 1) editable can be boolean, () => boolean, 2) we also can use global function as I pointed out to check if this can be editable. Moreover they have precedence order. 😞

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.
