### ISSUE TITLE
Row Selection, Sorting and Filtering don't interact correctly

### ISSUE THREAD

**Issue by draukadin** [adazzle/react-data-grid#1761]
- Have you already searched for similar issues? Yes

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [X] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [X] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [X] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is: When you apply a filter to find some rows to select the and check the boxes for all the rows shown by the filter the selectedIndcies in state is populated with [0, 1, 2, 3].  After you clear the filters, the rows you selected are actually in indices [0,2,4,6]  So the rows you selected and rows that are actually selected no longer match
- What the desired behavior is: The indices should get re balanced to match where the rows are after a filter is applied or removed.  The same issues applies to sorting.
- All my rows have an attribute called 'id' and the rowKey property on the ReactDataGrid is set to `id`
- The id is unique for every row in the table
- (If Bug) Steps to reproduce the issue.  

We especially love screenshots / videos of problems, and remember

The Best Issue Is A Pull Request™
```

- Animated GIF showing the issue ![FilterSortRowSelectionBug](https://user-images.githubusercontent.com/9981693/66011588-391d2100-e4b3-11e9-9e1e-57a1300468d1.gif)

**Comment by NamJuPark** [comment]
I got the same problem. But I solve to use other options in selectBy.
You can use this way to keep track of selected rows! 
I used "keys" instead of "indexes".  it works well in my case.
#1565

**Comment by amanmahajan7** [comment]
This is fixed in v7 canary. Please check the examples and let us know if the issue still exists

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
