### ISSUE TITLE
Excel-like bottom to top

### ISSUE THREAD

**Issue by mookiejones** [adazzle/react-data-grid#1765]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [x ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ x] Edge
- [ x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x ] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

When dragging a value from the bottom to the top, the fromRow still starts with the lowest number to the highest..

i.e. 

if i drag from row 1 to row 10 top to bottom, i would expect the value to go from 1 to 10.
but if i drag from row 10 to row 1, it still displays row 1 as the starting row number.

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.
