### ISSUE TITLE
Entering a textarea cell editor with "Enter" adds a newline to the value

### ISSUE THREAD

**Issue by tomo-hyperscience** [adazzle/react-data-grid#1770]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ x ] v16.5.2

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ x ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ x ] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

Current Behavior:
When entering the cell editor with enter and the custom input is a text area, a new line is added. 

Desired Behavior:
When entering the cell editor with enter and the custom input is a text area, the value is not changed.  

Steps to reproduce the issue:
You can reproduce the problem here: https://codesandbox.io/s/rdg-custom-editors-icpnt by going to the color column, and pressing enter to activate the editor.  

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.

**Comment by thalmann-christof** [comment]
This issue is still open for the latest version (`7.0.0-beta.11`). 

As I needed to get this working I found a workaround (which is not beautiful but right now the only way to solve this). 

When you build the custom editor for the react-data-grid cell and use the `textarea` input and add ref:
```
<textarea
  ...
  ref={_removeLineBreak}></textarea>
```

and:
```
const _removeLineBreak = (input: HTMLTextAreaElement | null) => {
  if (!input) {
    return;
  }

  setTimeout(() => {
    const val = input.value;
    input.value = val.replace('\n', '');
  }, 0);
};
```

This works fine. If anybody finds a better workaround - or if this issue gets solved - let me know.
