### ISSUE TITLE
top row doesn't show at top of grid

### ISSUE THREAD

**Issue by littlebee** [adazzle/react-data-grid#178]
Just wondering if you guys have seen anything like the attached shot.  

Don't know where to begin figuring out what is going on.  Probably more likely a chrome or react rendering issue as the :hover css is off and double clicking in the empty space will activate one of the cells below.    

This is on 
OSX 10.10.5
Chrome 47
React 0.14.0   

I merged the jp-v14 branch into master.  Without jp-v14, I think everything worked except edits.  I'll try this with what's in master (without jp-v14).  Looks like I'm a couple patches behind on react, I'll try that too.

Sorry, know you guys are busy, just wondering if this is a known thing

This happens after scrolling down a ways and then scrolling really really fast to the top.  This was using the two finger touchpad scroll;  I was unable to reproduce using scroll nub dragging.  
  

![buyer_goals_and_untitled__zulily_bp_calendar_01132016_copy_2___page_1_of_3_](https://cloud.githubusercontent.com/assets/593784/12542986/300ed5bc-c2df-11e5-903f-d15b3d911ffb.png)
.

**Comment by littlebee** [comment]
update:  testing with react 0.14.6:  not as easy to reproduce.  Takes a lot of scrolling up and down, but still happens occasionally

**Comment by malonecj** [comment]
HI, thanks for creating the issue. Yes, I have seen that happening one or twice on chrome on mac before. We'll take a look and see if we can find the route cause

**Comment by nqbao** [comment]
I am seeing this often too, keep scroll up and down it will happen like the above screenshot. Here is mine. I think it is easier to reproduce with Mac trackpad, just scroll down then scroll up immediately.

![scroll bug](https://cloud.githubusercontent.com/assets/177742/12872354/c9617392-cdd3-11e5-81fe-5f16e17ef6eb.gif)

**Comment by bakesteve** [comment]
Few quick questions as we try and get to the root cause on this:
1. does that stay blank, or sometimes start blank but tehn render (we enqeue the render when you scroll quickly for better perf, but we have seen it appear after ~500ms, but also render, but out of position)
2. Do you see it render out of position (screengrab below)? Have had this a couple of times, and what is very strange, is that the dom in chrome devtools looks ok, but for some reason the render is out of place.

![image](https://cloud.githubusercontent.com/assets/605712/12974782/8241b6ba-d0ae-11e5-8d99-02e050efa013.png)

**Comment by nqbao** [comment]
Here are my answers:

(1) Once the blank appears, it stays there forever. I can make it to restore to original position by using the right scrollbar.

(2) Yes, sometime it is out of position like your screenshot.

**Comment by littlebee** [comment]
I am not currently able to reproduce the problem with the lastest code in master.

**Comment by littlebee** [comment]
Also had the same experience @bakesteve.  Stays blank, and not only does the DOM look right but chrome thinks the mouse is over the DOM elements that are out of place.

I had done an ultra hacky to work around that I've since taken out.  I think it went something like triggering a slightly delayed execution method whenever my row renderer was called that would check to the scroll top of the viewport and if it was a zero, it would set scrolltop to 1 on the viewport and that would cause it to fix itself and correctly paint everything.

**Comment by nqbao** [comment]
Yeah, i can't not reproduce the issue on master anymore, but now when I scroll fast using trackpad the grid will stay blank until the scroll stops.

![scroll](https://cloud.githubusercontent.com/assets/177742/13031863/c1927cde-d30e-11e5-86ee-7ae42a72ddd6.gif)

**Comment by bakesteve** [comment]
yes - we added a delayed render when scrolling past the rendered rows. Basically avoids rendering a load of DOM elements that you are just scrolling past. You can turn that off using `rowScrollTimeout={0}`

**Comment by nqbao** [comment]
@bakesteve thanks, i will try that.
