### ISSUE TITLE
Data filtering issue for non matching records

### ISSUE THREAD

**Issue by hevendrasingh-pearson** [adazzle/react-data-grid#1783]
### Issue Details
I'm getting an UI issue while filtering data for non matching records. The issue is exist in library filter example also. Please follow the below sandbox link to replicate this issue:
https://codesandbox.io/s/w6jvml4v45?from-embed

STEPS:
1. Scroll to right
2. click on filter button
3. search Job Area for 'tes'
4. press back button

Now, You will see the data grid doesn't retain the scrolled position.

```

**Comment by amanmahajan7** [comment]
Filtering API has been changed in v7 canary and we recommend upgrading. Filtering logic is not controlled by the user

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--header-filters
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
