### ISSUE TITLE
tooltip for NumericFilter of react-data-grid-addons

### ISSUE THREAD

**Issue by masakimu** [adazzle/react-data-grid#1795]
Hi,

Could you replace 'Then' with 'Than' for a following tooltip text of Numerical Filter (react-data-grid-addons/src/cells/headerCells/filters/NumericFilter.js):

     tooltipText = 'Input Methods: Range (x-y), Greater Then (>x), Less Then (<y)'

Thank you.

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [x] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [x] Firefox
- [x] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

**Comment by sivani96** [comment]
Hi I have taken this up and here is the [PR](https://github.com/adazzle/react-data-grid/pull/1799)

**Comment by masakimu** [comment]
> Hi I have taken this up and here is the PR

Thanks!

**Comment by masakimu** [comment]
close because of approval of PR
