### ISSUE TITLE
Cant see the code for the 'all the features grid' 

### ISSUE THREAD

**Issue by binualexander** [adazzle/react-data-grid#18]
I am trying to  to see the code for the 'all the features grid'

the site http://adazzle.github.io/react-data-grid/
shows example code for all other variants of the grid .

Can I get the code for that ?

Thanks

**Comment by malonecj** [comment]
Hi, yes I will try and update the examples this week

**Comment by binualexander** [comment]
Thanks ... looking forward to that

**Comment by bakesteve** [comment]
code is up now - have a look at http://adazzle.github.io/react-data-grid/examples.html#/all-the-features and  http://adazzle.github.io/react-data-grid/examples.html#/all-features-immutable

**Comment by binualexander** [comment]
Thanks ! Good work
