### ISSUE TITLE
When second row is selected and is top-most visible row, pressing the up arrow key selects first row but does not scroll it into view

### ISSUE THREAD

**Issue by adamlangsner** [adazzle/react-data-grid#1805]
### Which version of React JS are you using?

✅ Officially supported ✅
- [x] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

#### Current Behavior
The issue is related to navigating the grid using the arrow keys on the keyboard to scroll the grid. Specifically, when the selected cell is in the second to the top row (`rowIdx==1`) and the user presses the up arrow key, it does not scroll the first row (`rowIdx==0`) into view. When the user presses the up arrow again, it does scroll the first row into view. So, to summarize, when selecting the second row, the user has to press the up arrow key twice to see the top row. 

#### Desired Behavior
The desired behavior would be to scroll the top row into view when the user press the up arrow key the first time.

#### Recreating the Issue
I was able to reproduce this in one of the live examples: https://codesandbox.io/s/5vy2q8owj4?from-embed
I edited that example by adding more rows (to get the grid to scroll). You can play with my tweaked example here: https://l464w.csb.app (not sure how long-lived that URL is)
Also, here's a gif recreating the bug:
![2019-10-23 15 09 38](https://user-images.githubusercontent.com/915091/67500078-292ad400-f650-11e9-96ee-64e82b3d042e.gif)
If you look closely, you can see that when I move from row ID 1 to row ID 0 it doesn't scroll and you can see the blue box in the bottom right corner of the select border sticks out under the ID header. When I press up again you can see that row ID 0 scrolls into view.
I was able to recreate this in both React 15.4.2 and 16.5.2

#### Potential Source of the Bug
I spent some time tracking down the source of the issue in the RDG codebase. It seems like the bug is in the `isCellAtTopBoundary` function in the `InteractionMasks` component.
link: https://github.com/adazzle/react-data-grid/blob/next/packages/react-data-grid/src/masks/InteractionMasks.tsx#L336

When the user has the second row  selected and presses the up arrow key, the `rowIdx` is decremented from `1` to `0` and then `isCellAtTopBoundary` is called. The `cell.rowIdx !== 0` condition in `isCellAtTopBoundary` causes it to return `false` and therefore it doesn't scroll the first row into view. When the user presses the up arrow key again, the `rowIdx` is decremented from `0` to `-1` and the `cell.rowIdx !== 0` causes `isCellAtTopBoundary` to return `true` and the first row *does* scroll into view.
I removed the `cell.rowIdx !== 0` condition from that function and it did fix the issue, but I'm not familiar enough with the codebase to be sure that it is ok to remove this condition.

Generally, I think the `isCellAtTopBoundary` doesn't need to concern itself with whether the row index is at the beginning of the entire grid (`cell.rowIdx !== 0`) but rather only concern itself with whether the current row index is at the beginning of the visible rows. (`cell.rowIdx <= rowVisibleStartIdx - 1`).

cc @tomo-hyperscience @nlazarov

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.
