### ISSUE TITLE
Help with editable grid

### ISSUE THREAD

**Issue by burton666** [adazzle/react-data-grid#1807]
Is it possible to get an working example of how to construct the editable [table-grid example](https://codesandbox.io/s/5vy2q8owj4?from-embed)  using the "new" react hooks ?

**Comment by qili26** [comment]
Like @partynikko mentioned, here is what you need to do.
1. convert the `class component` to a `functional component` by using `useState`, `useImperativehandle` (for `getInputNode` and `getValue`).
2. use `forwardRef` to make sure your `functional component` can be passed a ref from parent component

**Comment by dgdosen** [comment]
Can you go into a bit more detail on using hooks?

I'm getting an error 'Cannot read property 'length' of undefined' and I'm unsure of the context.

![image](https://user-images.githubusercontent.com/75257/79987527-638bf700-8462-11ea-95e4-6456b6ac5ad9.png)

**Comment by qili26** [comment]
@dgdosen 
In what stage did you see the issue? After editing? Upon Grid loading? etc?

**Comment by dgdosen** [comment]
FYI - I'm using typescript and react hooks. 
This error is a runtime error.

I think I'm looking for more detail on if/why of forwardRef is needed...

**Comment by dgdosen** [comment]
I found my issue - I added types (@types/react-data-grid) to my project separately from react-data-grid - and it had an older api - which made me write code like in the current docs, which isn't similar to the current code.  

I removed types from my package, and followed the lead from CommonFeatures.tsx

**Comment by dcsan** [comment]
@dgdosen thanks for this comment, i had the same issue.

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.
