### ISSUE TITLE
Fixed columns and headers are jerky

### ISSUE THREAD

**Issue by txm** [adazzle/react-data-grid#181]
When scrolling vertically or horizontally the fixed column and the header are jerky and do not scroll smoothly with the data.

http://adazzle.github.io/react-data-grid/examples.html#/fixed

Is it even possible to be fixed with current standards?  For a bounty :)

Other methods aren't jerky, but they aren't comparable like-for-like, also they favour tables http://jsfiddle.net/c3mqfukj/

**Comment by txm** [comment]
This is a Safari thing.

**Comment by RikkiGibson** [comment]
I'm interested in this question as well. I like the solution in the fiddle, but would like to note that it doesn't allow scroll events to be received under the fixed column. That's a small disadvantage from my point of view.

**Comment by jmangel** [comment]
This still seems to be an issue, at least in safari, why is it closed? http://adazzle.github.io/react-data-grid/docs/examples/frozen-columns

**Comment by jmangel** [comment]
Though the example works fine in chrome, I'm also seeing a milder version of the same issue in my own app in chrome

**Comment by RikkiGibson** [comment]
I see pretty much the same problem in firefox. I think to some degree it's innate to fixed column solutions that are driven by handling scroll events in js :/
