### ISSUE TITLE
Example for "rendering hundreds of thousands of rows with no lag"

### ISSUE THREAD

**Issue by slonix** [adazzle/react-data-grid#1812]
### Which version of React JS are you using?

✅ Officially supported ✅
- [x] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

Hi, at some point of your library development you showed example of "rendering hundreds of thousands of rows with no lag" in examples on your page (the link still exists in your repo README - https://adazzle.github.io/react-data-grid/#/examples/one-million-rows). Right now I cannot find it anywhere on the website nor in the repo. Have you removed this feature? Do you plan to support this feature in latest versions of react-data-grid?

**Comment by amanmahajan7** [comment]
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--a-million-cells
https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/MillionCells.tsx

The above example is from v7 canary
