### ISSUE TITLE
[Canary] DraggableContainer and SelectColumn (row selection) breaks header

### ISSUE THREAD

**Issue by jwallet** [adazzle/react-data-grid#1814]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x (16.8.0)

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [x] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

Please include:
- What the current behavior is
> Canary.5
> If we combine `SelectColum` (selectedRows/onSelectRowsChange) and addon `DraggableContainer` the header breaks, it moves outside of the element
- What the desired behvaior is
> Just to let you know if you don't have any test that combined both
- (If Bug) Steps to reproduce the issue

 <DraggableContainer onHeaderDrop={handleHeaderDrop}>
      <ReactDataGrid
       // other props
        selectedRows={selectedRows}
        onSelectedRowsChange={handleSelectedRowsChange}
      />
    </DraggableContainer>

- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
> same result on chrome and firefox
![image](https://user-images.githubusercontent.com/23088305/68091931-d1604a00-fe53-11e9-8d57-5e117166858e.png)

The Best Issue Is A Pull Request™

**Comment by jwallet** [comment]
### Solved
I forgot to import `react-data-grid-addons` style to my project. I compared DOM lines using the example-13 in `/demos`

**Comment by ShantanuNair** [comment]
This issue just popped up for me. My screenshot would look identical to yours. I just have SelectColumn and the draggable add-on enabled. 

So I tried doing what @jwallet did, but I wanted to be sure—you import the react-data-grid-addons style into your component file? Or does webpack do it automatically here, since I couldn't find any such import for the examples. Or did you just manually add the class name to the header?

**Comment by ShantanuNair** [comment]
> ### Solved
> I forgot to import `react-data-grid-addons` style to my project.

How did you do this? I don't see a styles folder in my node-modules' dist. I'm on the canary addons version btw.
