### ISSUE TITLE
onCommit() closes editor

### ISSUE THREAD

**Issue by ShantanuNair** [adazzle/react-data-grid#1815]
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [X] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [X] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [X] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details
Currently when onCommit is called within an editor, the editor is closed after committing. My use case is as follows: I'm using [https://www.npmjs.com/package/react-tag-autocomplete](react-tag-autocomplete) to create an editor for tags. I've stopped propagation of onKeyDown events when 'Enter', 'Tab', or 'Space' has been pressed. As a result the user can enter tags intuitively, but has to press escape in order to exit the editor. However, since onCommit needs to be called on each tag addition (I do not wan't to have a 'save' button in the editor), the user can only add one tag at a time.

I've read the custom editor documentation, as well as the Implementation Details pages, but nowhere is it mentioned that every time onCommit is called, the editor is to be closed.

Expected behavior:
onCommit simply commits to the rdg, without closing the editor.

Current behavior:
onCommit closes the editor everytime onCommit is called.

**Comment by qili26** [comment]
For you case, you should not call `onCommit` each time when you change the value. `onCommit` means you want to populate the update event from RDG outside (your app global store or state). I would recommend you to have an editor local state to hold the data that you input from the autocomplete, and wrap the whole data that you want to populate in `getValue` function. Please notice that at the moment, you have to make your editor a `class component` or `functional component` with `forwardRef` as the RDG needs the `ref.current.getValue()` to wrap the update events with the data you want to pass.

Example code (just to explain the gist)
```javascript
class YourEditor extends React.Component {
  ref = React.createRef();
  state = {
      tags: [
        { id: 1, name: "Apples" },
        { id: 2, name: "Pears" }
      ],
      suggestions: [
        { id: 3, name: "Bananas" },
        { id: 4, name: "Mangos" },
        { id: 5, name: "Lemons" },
        { id: 6, name: "Apricots" }
      ]
    }

  handleDelete = (i) => {
    const tags = this.state.tags.slice(0)
    tags.splice(i, 1)
    this.setState({ tags })
  }
 
  handleAddition = (tag) => {
    const tags = [].concat(this.state.tags, tag)
    this.setState({ tags })
  }
 
  getInputNode = () => this.ref.current ? this.ref.current.querySelector('input or select') : null; // needed by RDG

  getValue = () => ({
    [some key you defined, typically column key]: { ...this.state }; // or some other values you want to put from this.state.
  })

  render () {
    return (
      <ReactTags
        ref={this.ref}
        tags={this.state.tags}
        suggestions={this.state.suggestions}
        handleDelete={this.handleDelete.bind(this)}
        handleAddition={this.handleAddition.bind(this)}
       />
    )
  }
}
```

**Comment by ShantanuNair** [comment]
Hi @qili26 , thanks so much for taking the time out and even providing sample code. My editor component looks largely the same as what you have posted, except that I don't have any refs on my react tag. However, my getValue() still functions to update the grid, just not on tag addition, and only when (I believe) onCommit is called. Does that make 


```
export class TagEditor extends React.Component<ITagEditorProps>{
  state = {
    tags: this.props.value? this.props.value.split(" ").map((tag, idx) => ({name: tag, id: idx})) : []
  }

  inputRef = React.createRef()

  getValue() {
    return { [this.props.column!.key]: this.state.tags.map((tagObj) => tagObj.name).join(" ") };
  }
  
  getInputNode() {
    let domNode = ReactDOM.findDOMNode(this)!;
    return (domNode as HTMLElement).querySelector('input');
  }
  
  handleKeyDown(e){
    if (e.key === 'Enter' || e.key === 'Tab') {
      e.stopPropagation();
   }
  }

  handleDelete (i) {
    const tags = this.state.tags.slice(0)
    tags.splice(i, 1)
    this.setState({ tags })
  }
 
  handleAddition (tag) {
    const tags = Array().concat(this.state.tags, tag)
    this.setState({ tags })
  }

  render() {
    console.log(this.props.value)
    const tagsInput = <ReactTags
      tags={this.state.tags}
      tagComponent={Tag}
      delimiters={[" ", "Tab", "Enter"]}
      addOnBlur={false}
      allowNew={true}
      onDelete={this.handleDelete.bind(this)}
      onAddition={this.handleAddition.bind(this)} />
    
    return (
          {tagsInput}
    )
  }
}

export default TagEditor;
```

I'm not using any autocomplete functionality, just tags as input. So the code I've posted works, _if_ I have a save button that calls on commit. 

However, say I want to see the result of the tags I'm adding live, as I'm adding them in the editor—say a graph plotting all the things I'm adding to the editor. In this case, I _would_ want each tag addition to reflect in my global app state correct? So I think my question comes down to "how would I go about committing changes while still keeping the editor open?"

**Comment by qili26** [comment]
My apology for not being clear about the `ref` thing. Inside the Editor, ref is not a must. However the editor itself has to be a class component or functional component with `forwaredRef`. On the other hand, if you want the RDG to select the input automatically when the editor is open, then you have to add this `ref` inside your component, otherwise RDG will not know your `<input />` or `<select />` dom.

Back to your component, just to be sure, you want the editor change to be reflected outside of the grid while the editor is still open, right? First, for RDG itself, `onCommit` closes the editor should be an intuitive behavior. As the `onCommit` in the editor should just mean all the editing status is done. So for your case, I believe you cannot use the `onCommit`,  instead of having a local state, I believe it's better for you to lift the state to global, i.e. inside the Editor, you can connect to outside.

For example.
```javascript
import { useSelector, useDispatch } from 'react-redux';

export const TagEditor = forwardRef(function (props, ref) {
  const editorValue = useSelector(tagEditorSelector);
  const dispatch = useDispatch();

  const updateValue = (value) => dispatch(action(value));

  useImpremativehandle(ref, () => ({
   getInputNode() { xxx },
   getValue() {xxx}
  }))
  
  ...
   
  return <InputComponent onChange={updateValue} />
})
```

Just be sure the `editorValue` in global store is a completely separate value in your app, otherwise I believe when you change anything, the RDG would refresh as the row data is changed which results in some unpredictable bugs. In addition, call `onCommit` only when your editing status is finished.

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.
