### ISSUE TITLE
[canary] need a way to set SelectColumn width, to be always the same size.

### ISSUE THREAD

**Issue by jwallet** [adazzle/react-data-grid#1816]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [x] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---
In `columns` array if we add `SelectColumn` to add a checkbox to the row : 
- we can't specify a width to SelectColumn to use
- SelectColumn is affected by `minColumnWidth`

```
// does nothing, it's still 60px
this.columns = [
     {...SelectColumn, width: 40},
     // { ... }
];
```
adding `minColumnWidth={200}` to <ReactDataGrid />` will give a width of 200px to the checkbox, which makes no sense

```

**Comment by amanmahajan7** [comment]
This should be fixed in v7 canary 16
