### ISSUE TITLE
[Warning] Warning: owner-based and parent-based contexts differ (values: `undefined` vs `[object Object]`) for key (metricsComputator) while mounting Viewport (see: http://fb.me/react-context-by-parent) (bundle.js, line 1708)

### ISSUE THREAD

**Issue by txm** [adazzle/react-data-grid#182]
http://adazzle.github.io/react-data-grid/examples.html#/basic

Using     "react": "^0.13.3"

[Warning] Warning: owner-based and parent-based contexts differ (values: `undefined` vs `[object Object]`) for key (metricsComputator) while mounting Viewport (see: http://fb.me/react-context-by-parent) (bundle.js, line 1708)

**Comment by bakesteve** [comment]
this was fixed as part of #63
