### ISSUE TITLE
There is a gap between row (header or data) and sum of cells' widths

### ISSUE THREAD

**Issue by vasilii-kovalev** [adazzle/react-data-grid#1821]
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [X] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [X] Edge
- [X] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [X] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details
There is a gap between row (header or data) and sum of cells' widths.
![image](https://user-images.githubusercontent.com/10310491/68657036-f899d400-0543-11ea-859d-f8f11c87ac14.png)
You can see it [in this demo](https://codesandbox.io/s/rdg-cell-editing-5v135).
Its size can vary depending on columns count.
Since there is no any property for ReactDataGrid to set up its width (not `minWidth`), I used some wrappers for it, that I often see in the component's issues discussions.
You can also find the problem in examples on the official page, if you look at it closely in full version.
For example, https://codesandbox.io/s/5vy2q8owj4
and its full version https://5vy2q8owj4.csb.app/

It seems that the cells' width is calculated incorrectly.

Versions of the library:
* My example: 6.1.0
* Official page example: 5.0.1

It's important for our app so if any workarounds exist, please provide me with them.
Thanks in advance.

**Comment by Javo-blip** [comment]
I'm experiencing this exact issue as well

**Comment by nsequeira87** [comment]
Well, I don't know if this is still an issue for you but I was having a similar problem and solved this adding the following css:
```
.react-grid-HeaderRow {
    width: 100% !important;
}
```

Hope this works for you.
Cheers

**Comment by amanmahajan7** [comment]
This is fixed in v7 canary and we recommend upgrading 
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
