### ISSUE TITLE
[Performance] rowGetter being called too many times.

### ISSUE THREAD

**Issue by ShantanuNair** [adazzle/react-data-grid#1826]
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [x] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

So I was trying to optimize performance on our project, when I realized that rowGetter was being called way too many times and I'm not sure why. I understand it's called on scrolling to create a buffer for the view, but it seems like it's being called a lot more than required.

Example (boilerplate taken from the sorting example in docs):
Notice the console that logs the row number as well as the count of the number of times rowGetter has been called. This example has only 50 rows. Furthermore, even a tiny scroll, one that doesn't bring any new rows into the view causes a massive re-render. 

https://codesandbox.io/s/rdg-column-sorting-let2k?fontsize=14&hidenavigation=1&theme=dark

**Comment by amanmahajan7** [comment]
`rowGetter` will be removed in v7 in favor of a new `rows` prop. 

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
