### ISSUE TITLE
Unpredictable behavior "DropTargetRowContainer" with custom Row

### ISSUE THREAD

**Issue by RogovArtem** [adazzle/react-data-grid#1828]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [✅ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [✅ ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [✅ ] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

Yesterday i wrote my custom Row like this
![image](https://user-images.githubusercontent.com/12447382/69407987-e4f62680-0d16-11ea-8b9c-27279f1c5570.png)
And when i was started drag i saw this 
![image](https://user-images.githubusercontent.com/12447382/69408497-14f1f980-0d18-11ea-9932-adf91cbad796.png)

If i understand correctly, this line of code do this
https://github.com/adazzle/react-data-grid/blob/26f4dafe68fbebef312ea7c146b44f039d48c1b9/packages/react-data-grid-addons/src/draggable/DropTargetRowContainer.js#L21
![image](https://user-images.githubusercontent.com/12447382/69408788-ae211000-0d18-11ea-84bf-16b3e7aa77ca.png)

I saw simular code in a lot of datagrid sources. 
I think there we need use class with border-bottom on div above <Row ..../> or on <Row.../>
![image](https://user-images.githubusercontent.com/12447382/69409269-a01fbf00-0d19-11ea-96d4-6aa77ebd0d38.png)
But a lot of datagrid do this. 

### **Question:** 
Why a lot of people and command do this on data grid? 
I think i just dont know this feature. 
What the reason?

- What the current behavior is - when i use my custom Row, line for display drop target not display correctly
- What the desired behvaior is - if write my custom Row, this line was display on default row or under Container
- (If Bug) Steps to reproduce the issue - create custom row like this 
```
<div>
    <ReactDataGrid.Row ref={(node) => this.row = node} {...this.props}/>
    <div className="data-cell" ref={refTarget}>
          <div className="data">{data}</div>
    </div>
    </div>
```
- (If Feature) The motivation / use case for the feature

**Comment by amanmahajan7** [comment]
`react-data-grid-addons` will be removed in v7 and we recommend copying the relevant code from `react-data-grid-addons` package to your local repository and tweak it as necessary

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary
