### ISSUE TITLE
Guide on how to upgrade from version 6 to 7

### ISSUE THREAD

**Issue by ssargon** [adazzle/react-data-grid#1829]
Hi!

I am trying to find a guide on how to upgrade from version 6 (since we have having quite a few issues with that version) to version 7 alpha to see if some of our issues are resolved. Does any such guide exist or is there a page where I can read up on the changes on how to use the grid in version 7 in contrast to version 6?

**Comment by dsadaka** [comment]
I would love to see a README on improvements from 6 to 7 as well.

**Comment by phamsang119** [comment]
They do not even have documents for version 6, how can we find doc for version 7 :D

**Comment by qili26** [comment]
I believe v6 to v7 alpha doesn't have any break changes other than the typescript support. If you have typescript already, you just need to fix the types after upgrades.

**Comment by Thihup** [comment]
I tried to upgrade but the styles are incorrect.
It's possible simulate [here](https://codesandbox.io/embed/rdg-row-selection-g1y5v?fontsize=14&hidenavigation=1&theme=dark).

**Comment by dgdosen** [comment]
Is there any guidance on how to upgrade/change styles?  My data is overlapping and aligned to the left of my grids.

**Comment by lizraeli** [comment]
Experiencing the same issue as on a fresh install

**Comment by simplecode-io** [comment]
Same issues here on a fresh install. Using any version above Alpha 6.0.0 causes data to overlap and align to the left.

**Comment by amanmahajan7** [comment]
Here is the changelog and some details on how to migration. We will publish a migration guide once the api is finalized. RDG now creates a css bundle `react-data-grid/dist/react-data-grid.css` that must be included

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md

**Comment by simplecode-io** [comment]
Thanks! That was it. thanks for this awesome package!
