### ISSUE TITLE
Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs.

### ISSUE THREAD

**Issue by txm** [adazzle/react-data-grid#183]
http://adazzle.github.io/react-data-grid/examples.html#/basic

Using     "react": "^0.13.3"

Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.

**Comment by jpdriver** [comment]
hey @txm -- do you mean the example isn't working for you? what browser are you on?

**Comment by txm** [comment]
Sorry, yes.  Safari 9.0.3.

I'd rather use react 0.14.x anyway, so if todays release of react-data-grid works with that, then I'll upgrade both packages and close this issue.
