### ISSUE TITLE
DataGrid not rerender cells when minHeight changes and scroll position > 0

### ISSUE THREAD

**Issue by vanRepin** [adazzle/react-data-grid#1832]
- Have you already searched for similar issues? Please help us out and double-check first!
yes
- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
  some rows disapear. (it apears they are over the viewport)
- What the desired behvaior is
rows render correctly
- (If Bug) Steps to reproduce the issue
1) go to https://codepen.io/vanrepin/pen/wvvVoBQ
2) Scroll somewhere inside DataGrid
3) Resize browser
4) rows disapear
5) Scroll again - rows repear

- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by amanmahajan7** [comment]
This behavior should be fixed in v7 canary. Feel free to open a new issue if you still facing problems

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
