### ISSUE TITLE
Columns reordering doesn't work without Immutable

### ISSUE THREAD

**Issue by vasilii-kovalev** [adazzle/react-data-grid#1838]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [X] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [X] Edge
- [X] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [X] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

Steps to reproduce:
1. Make demo from the official site using `react-data-grid` and `react-data-grid-addons` v. 6.1.0 without using `Immutable` ([Sandbox](https://codesandbox.io/s/react-data-grid-reordering-issue-nxnel)).
2. Try to reorder the columns.

**Expected result:** columns are reordered.
**Actual result:** columns are not reordered.

I investigated the bug and found out that [here in `componentWillReceiveProps`](https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid/src/ReactDataGrid.js#L277) there is a check of current and next props via `ColumnMetrics.sameColumns` method. I've created a [Sandbox](https://codesandbox.io/s/react-data-grid-columns-comparison-j2nq1) with the working part of this method (`compareEachColumn`, because `areColumnsImmutable` returns `false` if `Immutable` is not used) to play around with it and better understand what's going on here.
It seems, that this algorithm compares the columns structures (that are the same of course), but doesn't take into account their order.

Maybe a snippet like this may solve the problem:
```javascript
function compareEachColumn(prevColumns, nextColumns, isSameColumn) {
  let i;
  let len;
  let column;
  const prevColumnsByKey = {};
  const nextColumnsByKey = {};

  if (getSize(prevColumns) !== getSize(nextColumns)) {
    return false;
  }

  // Possible solution.
  for (i = 0, len = getSize(prevColumns); i < len; i++) {
    column = prevColumns[i];
    const nextColumn = nextColumns[i];
    if (!isSameColumn(column, nextColumn)) {
      return false;
    }
  }

  // the rest code.
}
```

I'd like to create a pull request, but I'm afraid that I don't know enough about the library and if it may break something down anywhere/in any corner cases.

**Comment by amanmahajan7** [comment]
We have removed ImmutanleJS dependency in v7 canary. Please give it a try and lets us know if there are any issues


https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
