### ISSUE TITLE
Support for react:  ^0.14.6

### ISSUE THREAD

**Issue by txm** [adazzle/react-data-grid#184]
Could react-data-grid support React 0.14.6

Warning: ReactDataGrid is accessing isMounted inside its render() function. render() should be a pure function of props and state. It should never access something that requires stale data from the previous render, such as refs. Move this logic to componentDidMount and componentDidUpdate instead.

Warning: Grid: type specification of prop `columnMetrics` is invalid; the type checker function must return `null` or an `Error` but returned a function. You may have forgotten to pass an argument to the type checker creator (arrayOf, instanceOf, objectOf, oneOf, oneOfType, and shape all require an argument).

Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

**Comment by jpdriver** [comment]
hey @txm -- we're working on support for v14 here https://github.com/adazzle/react-data-grid/pull/164

hopefully we should have an announcement shortly :+1:
