### ISSUE TITLE
Master/Detail or nested grids

### ISSUE THREAD

**Issue by e-a** [adazzle/react-data-grid#1840]
Hi Everyone,

I need a nested master/detail grid (similar to this one https://www.ag-grid.com/javascript-grid-master-detail/) and wanted to know if there is already anything I can continue working on. I was thinking that the easiest (and probably a bit messy) would be if I can possibly use custom row renderer to add another instance of the grid inside which can be linked using parent and child grid ids. Any thought on this s appreciated. Will start working on it anyway and share the results if there was any success or a proper failure.

Thanks
---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by mohsenomidi** [comment]
Hi, 

This is fantastic feature and usable for many people who wants to show details as a text or slideshow or any other type of information as details in grids
Foe example in the grid you want to show persons, there are lots of data such as picture, social id, gender, father name passport id and so on, the important data can be show in grid and if user needs to get more details, he can expand the row and in that time, the all data can be fetch from server and shows in any style that the detail part design.

**Comment by amanmahajan7** [comment]
Unfortunately rdg does not support this feature and we do not have this feature on our roadmap. We will happy to accept a PR
