### ISSUE TITLE
Humongous amounts of data

### ISSUE THREAD

**Issue by pjebs** [adazzle/react-data-grid#1846]
Can this library handle HUMONGOUS rows of data in a memory-reasonable manner?

**Comment by pjebs** [comment]
@power-f-GOD

**Comment by power-f-GOD** [comment]
Hm. Worth checking out. I'd have to give it a test.

Can you give an estimate of the number of columns and rows of data we could be expecting?

@pjebs

**Comment by power-f-GOD** [comment]
PS: Doesn't support on scroll load (yet).

@adazzle

**Comment by Javo-blip** [comment]
I'm facing a similar problem with huge datasets, the horizontal scroll becomes lagged and drops to less than 10fps. 

For reference, the dataset I'm dealing with has around 150 columns, and 2000 rows.

Vertical scrolls seems to be unaffected and scrolls relatively smoothly.

Every scroll action seems to be triggering roughly ~70 calls on the rowGetter function.

**Comment by qili26** [comment]
This lib is current under a refactoring for typescript support and better performance.

1. If you are using v6 from npm, then the performance would not be that great for the large data set like you mentioned.
2. If you are using typescript, v7 alpha would be the version you might want to use, however, the performance remains similar like v6, it only added typescript support.
3. If you are fine with somehow not stable but a better performance, I would recommend you to use the canary version. It refined the row / column virtualization logic, which only renders minimum cells in the view now, as well as the scrolling performance. However, the caveat is that some APIs are potentially subject to be refined again.

**Comment by amanmahajan7** [comment]
v7 can handle huge amount of data
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--a-million-cells
https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/MillionCells.tsx

Feel free to open a new issue if you are still experiencing performance issues

**Comment by pjebs** [comment]
@amanmahajan7 In https://github.com/adazzle/react-data-grid/issues/1846#issuecomment-570608459, @qili26 wrote that v7 only provides typescript support and the performance was still same as v6.

Is that still the case or are you saying that v7 also includes that performance benefits mentioned in canary version?
