### ISSUE TITLE
add default CSS to README

### ISSUE THREAD

**Issue by txm** [adazzle/react-data-grid#185]
Could you add this line to your README?

require('react-data-grid/themes/react-data-grid.css')

Would have saved me an hour ;)

**Comment by willbreitkreutz** [comment]
+1

**Comment by mnesler** [comment]
Where would i put this 'require' in my app?  
new person here...

**Comment by jpdriver** [comment]
hey @mnesler -- where exactly depends on your specific setup.. Are you using Webpack? 🙂

**Comment by mnesler** [comment]
I am not.

At this point, i think I should be...

I installed the 'create-react-app' package, then this one.

Seems there is no Webpack in the 'create-react-app' package.

**Comment by jpdriver** [comment]
Ahh awesome! create react app does use Webpack, but "under the hood"..

If you want to keep using it, you need to run npm eject first. That will expose Webpack and all the other underlying tech it uses.

BUT after that, you'll need to add a special Loader to get Webpack to handle CSS files..

Sadly the truth is there's a bunch of ways of doing this, and Dan (the guy who created create-react-app) didn't want to force the community to adopt a specific one..

Maybe it would be helpful if Adazzle included an end-to-end guide on starting React Data Grid + create-react-app from scratch?

**Comment by mnesler** [comment]
This good news, and explains a bit of my own confusion.  

+1 for some style documentation from Adazzle 

@jpdriver thank you for your time.

**Comment by diogofcunha** [comment]
This is no longer necessary in v2, All the styles are shifted with the grid.

Cheers.
