### ISSUE TITLE
[Feature] Sub tables and/or grouping

### ISSUE THREAD

**Issue by txm** [adazzle/react-data-grid#186]
e.g.

fruits, banana
fruits, pineapple
fruits, apple
vegetables, carrot
vegetables, peas
vegetables, sweetcorn 

becomes:

fruits, banana
        , pineapple
        , apple
vegetables, carrot
                  , peas
                  , sweetcorn 

extra points for show/hide based on click fruits/vegetables

**Comment by bakesteve** [comment]
yep - and we are looking at soem / all of these scenarios:
- group by (as above)
- child data (same column headers etc, just having some expand / collapse on children)
- sub grids (fully independent sub grids to allow master detail style views

tracked under #11
