### ISSUE TITLE
Audit warning: Regular Expression Denial of Service in react-data-grid-addons > ron-react-autocomplete > socket.io-client > engine.io-client > parsejson

### ISSUE THREAD

**Issue by mschaaf** [adazzle/react-data-grid#1864]
### Which version of React JS are you using?

✅ Officially supported ✅
- [x] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

---

### Issue Details

```
Please include:
- What the current behavior is
Added dependency data-grid and data-grid-addon version 6.1.0 to my project.
If I run `yarn audit` I get the following security warning

┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ parsejson                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ react-data-grid-addons                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ react-data-grid-addons > ron-react-autocomplete >            │
│               │ socket.io-client > engine.io-client > parsejson              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/528                         │
└───────────────┴──────────────────────────────────────────────────────────────┘

- What the desired behavior is
No audit warnings about data-grid-addon dependencies.

- (If Bug) Steps to reproduce the issue
1. add version 6.1.0 as a project dependency
```

**Comment by vileppanen** [comment]
Struggling with the same issue, and as it seems that there is no patch available for `ron-react-autocomplete`, this troubles one's mind enough. In my case, I would only need the d&d functionality from the addons, hence would suspect I wouldn't even need the autocomplete package.

https://adazzle.github.io/react-data-grid/docs/addons#installing-react-data-grid-addons-package it is stated here, that the addon components would be split into separate npm packages "in the future", but I'd expect it not to happen anytime soon?

I'd see one option in my case would be to fork the addons repo and do customizations there, but wouldn't want to part ways too much from the main project at this point

**Comment by amanmahajan7** [comment]
`react-data-grid-addons` package has been deprecated and will be removed in v7
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
