### ISSUE TITLE
Feature request: Row & column span (merging cells)

### ISSUE THREAD

**Issue by adamerose** [adazzle/react-data-grid#1872]
### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

### Issue Details
Would like the ability to make cells or headers span across multiple columns/rows, like the cells highlighted in yellow below.

![image](https://user-images.githubusercontent.com/10884874/72098289-33be4680-32ec-11ea-8cbb-a259565273ab.png)

Easiest implementation would be in the underlying data to just consider the spanning cell to be part of the top row and leftmost column of those which it spans, and simply have it cover up any cells that it spans over... so it's just a matter of configuring the css like z-index and width/height of that cell and it's associated components like the border and editor. I believe this is how it's done in ag-grid.

**Comment by amanmahajan7** [comment]
Unfortunately we do not this on our roadmap but we will be happy to accept a PR
