### ISSUE TITLE
Where is the vertical scrollbar ?

### ISSUE THREAD

**Issue by chprome** [adazzle/react-data-grid#188]
I am testing this component, and **I can't see the vertical scrollbar** on any example.

Here is what I get :
![capture d ecran de 2016-01-27 22-23-14](https://cloud.githubusercontent.com/assets/1465463/12628692/ab694938-c544-11e5-9172-19cd05c8090e.png)

The horizontal scrollbar is correctly displayed though.

I have tested with Firefox 44, Chrome 46 and Chromium 48 under Linux (Ubuntu Gnome 15.10) and with Internet Explorer 11 and Chrome 42 under a Windows 7 VM.

Is it a standard behaviour or am I facing an issue ?

Cheers,
Christophe

**Comment by bakesteve** [comment]
hmm.. looks like a bug, getting the same for me on http://adazzle.github.io/react-data-grid/examples.html#/million-rows
we'll check (though I suspect its an issue with the long awaited react 14 version)

**Comment by txm** [comment]
I get the slider one when I slide, then if I mouseover I get the complete vertical scroller.  I assumed this was standard?  react 0.14, osx, ff

The examples show most of the button/slider.  react unknown, OSX, safari.

not sure if this helps...
