### ISSUE TITLE
Row Selection Via Row Key With Immutable Rows Not Working

### ISSUE THREAD

**Issue by amber-cd** [adazzle/react-data-grid#1903]
#419 # Which version of React JS are you using?

✅ Officially supported ✅
- [x] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ x ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

---

### Issue Details

Current behavior: when I set up a react-data-grid instance using Immutable rows and set up selectBy to use the 'id' key, it works when the rows are Arrays but not when they're Immutable Lists.

Desired behavior: React data grid should support key usage for Immutable rows

Steps to reproduce: see this sandbox here: https://codesandbox.io/s/rdg-row-selection-vrmg3 (See the commented-out code in rowGetter to toggle behavior)

Due to the general support for Immutable rows in Lists, I believe this is a bug and not a feature request.

Please let me know if I've just made a mistake in my code, as I had some difficulty finding documentation for the selectBy rowKey feature, but it seems to me like this should work.

I know that I can selectBy indexes instead, but I would prefer to use recordIds in order to avoid some unnecesary recalculation when sorting a list with records already selected.

**Comment by amanmahajan7** [comment]
`selectBy` will be removed in V7 and we recommend using the new selection API
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/CommonFeatures.tsx#L45
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
