### ISSUE TITLE
row select check box doesn't work if no data loaded in initial load

### ISSUE THREAD

**Issue by hippasus** [adazzle/react-data-grid#192]
Initialize the grid with empty data, and then load some data to it with `enableRowSelect` property to `true`. The checkbox on each row doesn't work.

The reason is that `state.selectedRows` is initialized based on `rowsCount` in the getInitialSelectedRows method, and in the `handleRowSelect` method, if `state.selectedRows` is null or empty, nothing will happen.

Sorry I don't know any coffee script, or I'll send a pull request.

**Comment by hippasus** [comment]
BTW, the current way to store which rows are selected is not suitable for grid that needs to receive new data at all.

Let's say row 1 is selected, and then load new data to the grid, row 1 is still selected.

**Comment by bakesteve** [comment]
Yep. We have been evaluating how we can do this. The current implementation has the advantage that it doesn't mutate any row data, but as you say, can get thrown out by data manipulation of row data / order. Ie sort.

Well  move this over to using a row key on your data (defaulting to row.id but passed as a prop) and use a key/pair know that to store selected state.

Does mean you'll need to provide pseudo ids if you are using server side ids for your data but then adding new rows on the client (to be saved later).

Let us know if that would cause any issues for your use case, but from what you describe, this  should meet what you need

**Comment by malonecj** [comment]
We have changed row selection such that it is based off a unique id of each row rather than the index. Check out the example here
http://adazzle.github.io/react-data-grid/examples.html#/multi-row-select
