### ISSUE TITLE
component doesn't work like the basic example

### ISSUE THREAD

**Issue by njacob1001** [adazzle/react-data-grid#1925]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ✔️] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ ✔️] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [✔️ ] Safari

---

### I'm submitting a ...

- [✔️ ] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit a support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/docs/CONTRIBUTING.md

---

### Issue Details

[![Edit dazzling-moon-47jpm](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dazzling-moon-47jpm?fontsize=14&hidenavigation=1&theme=dark)

**Comment by venkatraman96** [comment]
I too face the same issue with latest version

**Comment by wontwon** [comment]
Yeah things are definitely broke in the latest version via yarn add react-data-grid. Hoping to see a fix in soon for this. Thanks for the hard work!

**Comment by rahulchavan30** [comment]
hi i too faced the same issue , but found a work around all i had to do is to import the css styles
import 'react-data-grid/dist/react-data-grid.css' ones i included this css all was working as expected

**Comment by njacob1001** [comment]
thanks!

**Comment by amanmahajan7** [comment]
Looks like issue has been resolved. Please check the changelog for more details
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
