### ISSUE TITLE
Frozen Columns - Freezing first and last columns

### ISSUE THREAD

**Issue by wontwon** [adazzle/react-data-grid#1937]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [x] v16.12.0

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [X] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [X] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit a support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/docs/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behavior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

Currently the documentation states that to freeze a column, add the key of frozen set to true, and the column will freeze. However, if I try to freeze the first and last columns, the scroll right becomes infinite and nothing freezes.

**Comment by wontwon** [comment]
Anything here? Any updates?

**Comment by rahulchavan30** [comment]
HI @wontwon i tried reproducing your issue but i was unable to do it , as of now when u freeze the first and last column , the columns that you set frozen:true is rendered first and then the remaining columns are rendered .

**Comment by amanmahajan7** [comment]
Can you create an codesandbox example? It is working as expected in examples
https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/CommonFeatures.tsx
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features

**Comment by amanmahajan7** [comment]
Closing as the examples are working as expect. Please create a new issue if you are still having problems
