### ISSUE TITLE
Feature Request: Allow i18n overrides of hard-coded strings

### ISSUE THREAD

**Issue by DanEastBentley** [adazzle/react-data-grid#1942]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [X ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [X ] Edge
- [X ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [X ] Firefox
- [X ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [X ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit a support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/docs/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behavior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

react-data-grid and react-data-grid-addons contain some hard-coded strings. Our product that uses react-data-grid needs to be able to provide localized/i18n overrides for these strings via props similar to the noColumnsSelected and panelDescription props for GroupedColumnsPanel. These are the nonadjustable hard-coded strings I've found so far.

* react-data-grid\src\common\cells\headerCells\FilterableHeaderCell.tsx:        placeholder="Search"
* react-data-grid-addons\src\cells\headerCells\filters\AutoCompleteFilter.js:    this.state = { options: this.getOptions(), rawValue: '', placeholder: 'Search' };
* react-data-grid-addons\src\cells\headerCells\filters\NumericFilter.tsx:        placeholder="e.g. 3,10-15,>20"
* react-data-grid-addons\src\cells\headerCells\filters\NumericFilter.tsx:  const tooltipText = 'Input Methods: Range (x-y), Greater Than (>x), Less Than (<y)';

**Comment by amanmahajan7** [comment]
`react-data-grid-addons` will be removed in v7 and any hard coded strings will be removed. We recommend copying the old components in your project and tweak them as needed
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
