### ISSUE TITLE
[Feature] Create a new line when enter pressed on the last row.

### ISSUE THREAD

**Issue by izanf** [adazzle/react-data-grid#1945]
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [X] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [X] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [X] 💡 Feature Request

### Issue Details
I need implement a feature to create a new line when I press enter on a cell input focused on last row.
```
Please include:
- What the current behavior is
Currently when I press enter on the last row cell, the cell is saved.
- What the desired behavior is
When press enter on cell input focused of last row, create a new line and move to below.
- (If Feature) The motivation / use case for the feature
Favor the creation of new lines and navigation
```

**Comment by AhmedAbdelfaheem** [comment]
any updates about this feature I want to stop enter from closing the cell editor
