### ISSUE TITLE
Usage documentation

### ISSUE THREAD

**Issue by sbhaktha** [adazzle/react-data-grid#195]
Hi,

I couldn't find much usage notes in your github README page. Do you have a pointer to a simple description of what one needs to do to create an (editable) data grid and populate it with values? Can they reference a local file to write changes to?

Thanks,
Sumithra

**Comment by bakesteve** [comment]
here you go: fully working examples of various features of the grid - this one is editable:
http://adazzle.github.io/react-data-grid/examples.html#/editable

We dont have anything showing how you load / persist your data store, but would highly recommend using some form of flux framework. As for local file storage, guess you could use (LocalStorage)[http://www.w3schools.com/html/html5_webstorage.asp] but essentially the grid will work whether you are storing it up on your servers through apis, local storage, or some form of offline sync

Hope that helps

**Comment by sbhaktha** [comment]
Thank you very much! What is the license to use your data grid implementation?
