### ISSUE TITLE
None of the examples are opening in Chrome

### ISSUE THREAD

**Issue by ymihir** [adazzle/react-data-grid#1956]
No examples are working here: https://adazzle.github.io/react-data-grid/docs/examples/simple-grid

I am trying in google chrome. In chrome only not working. Opening properly in edge. Below is console error i am getting
![image](https://user-images.githubusercontent.com/7568187/74606353-6b5fa180-5095-11ea-80e5-12b9c0d537a3.png)

**Comment by gcurbelo123** [comment]
This is not a problem with the data grids themselves. This is a problem with Chrome settings. 
See here: https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document

To fix this, try opening your Chrome settings, type "third" in the search box, click the Content Settings button, and there should be an option called "Block third-party cookies and site data." If it's checked, third-party cookies are not allowed and the exception you are getting will be thrown.

**Comment by amanmahajan7** [comment]
Please check the new examples 
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
