### ISSUE TITLE
V.7 release

### ISSUE THREAD

**Issue by ggcatu** [adazzle/react-data-grid#1957]
Hello guys, our team is currently using this package, and we are wondering if you have any planned date for the release of a new stable version.

**Comment by igoriok1994** [comment]
Yea, it is a good question 👍 I'm waiting for V7 so long :)

**Comment by cramatt** [comment]
Is there a document / readme / wiki page that covers what's new in V7? I didn't see anything mentioned in the migration guides or changelog 😢

**Comment by amanmahajan7** [comment]
Here is the changelog
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md

We are still finalizing v7 API and do not have a planned date yet. You can start using canary in the meantime. We will keep you posted as soon as we have a better idea.

**Comment by lishine** [comment]
guys, do you have one working example ?
I took the example from the readme and it says
```
TypeError
Cannot read property 'NONE' of undefined
DataGrid
https://woebc.csb.app/node_modules/react-data-grid/lib/DataGrid.js:39:612
```

**Comment by lishine** [comment]
After forking the locally the storybook works. So it is some problem with the build/-publish.

**Comment by christiantigre** [comment]
Any solutions, today install npm i react-data-grid and copy the code example, result 
TypeError
Cannot read property 'NONE' of undefined
https://codesandbox.io/s/datgrid-4i9sm?file=/src/App.js

**Comment by nstepien** [comment]
We don't have an explicit release date scheduled, but we're closer than ever to a stable 7.0.0 release, and you're invited to try out the latest beta versions.

Closing in favor of #2575
