### ISSUE TITLE
how do we implement and  RESET Button for Filter Rows

### ISSUE THREAD

**Issue by pitla-df-mdsol** [adazzle/react-data-grid#1964]
i want functionality like this.can anyone help ?
<img width="761" alt="Screen Shot 2020-02-24 at 12 47 15 PM" src="https://user-images.githubusercontent.com/58412797/75134281-d3e8f700-5703-11ea-8938-88559a774e61.png">

**Comment by emsi-iggy** [comment]
Toolbar accepts children so, change from:
``` toolbar={<Toolbar enableFilter={true} />} ```

to this:
```
toolbar={<Toolbar enableFilter={true}>
        {child component responsible for clearing filter}
      </Toolbar>
```

for example if you have functional component:
```
<button type="button" class="btn" onClick={() => setFilters({})}>Filter Rows</button>
```
But this will leave the text inside search fields...

**Comment by pitla-df-mdsol** [comment]
If i click "Reset filter" clears all the filters, but the filter mode is still on

**Comment by pitla-df-mdsol** [comment]
can you suggest the best approach for this ?
 Thanks !

**Comment by amanmahajan7** [comment]
We have deprecated `toolbar` prop in V7 and improved the filter API. Please check this example on how to use filters and customize it. 

https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/HeaderFilters.tsx#L166
