### ISSUE TITLE
CSS not being imported on clean install

### ISSUE THREAD

**Issue by samselfridge** [adazzle/react-data-grid#1967]
Version: "react-data-grid": "^7.0.0-alpha.29"

Installed to test out and none of the CSS is imported so my grid looks like this:

![TbmMy](https://user-images.githubusercontent.com/58707346/75398487-a55b4f80-58ae-11ea-8a58-1de5c0defec3.png)

By manually importing the css from ./node_modules/react-data-grid/dist/react-data-grid.css things appear as they should.

Appears to be a new issue since this stackoverflow user downgraded to get things working properly:
https://stackoverflow.com/questions/60213221/react-data-grid-shows-bad/60295257#comment106553019_60214089

**Comment by amanmahajan7** [comment]
css file now must be imported separately to add styles. This is needed to customize styles

 Please check the change log
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md#master-to-alpha

**Comment by samselfridge** [comment]
Thanks, missed the new example on the docs here, was going off the quick-start on the website: https://adazzle.github.io/react-data-grid/docs/quick-start

But it looks like thats for version 5.0.4, thanks for the clarification

**Comment by ab1nash** [comment]
Hey
It would be very helpful if you could update the same on the quick-start page.

**Comment by samselfridge** [comment]
https://github.com/adazzle/react-data-grid/pull/1971
