### ISSUE TITLE
selector.getRows is not working as expected

### ISSUE THREAD

**Issue by rodrigorevuelta** [adazzle/react-data-grid#1970]
**I'm submitting a 🐛 Bug Report**
**Issue Details**
I have unexpected filtering when I use Data.Selectors.getRows({rows,filters}). In my example, I have a column with two values (NOT_RUNNING and RUNNING). When I choose NOT_RUNNING as my filter I get the rows with the value RUNNING and NOT_RUNNING.
The example is: [https://codesandbox.io/s/exciting-hugle-y1u56](https://codesandbox.io/s/exciting-hugle-y1u56)

**Comment by amanmahajan7** [comment]
`react-data-grid-addons` will be removed in v7 and we recommend copying the relevant code from `react-data-grid-addons` package to your local repository and tweak it as necessary 

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
