### ISSUE TITLE
React-data-grid version 6.1.0 files

### ISSUE THREAD

**Issue by emsi-iggy** [adazzle/react-data-grid#1972]
Does anyone know where i can find files for package react-data-grid@6.1.0 ?
I found the package on the npm site but there is everything compiled to one file
which is react-data-grid.js
I can't find the tag or release responsible for it (on the Github).
The existing releases are:
v5.0.4
v6.0.0-alpha.0
v7.0.0-alpha.0
but where can i find v.6.1.0 which i'm currently using ?

The contents of "react-data-grid" in node_modules:
![image](https://user-images.githubusercontent.com/44373848/75900318-08179280-5e3d-11ea-9ce5-565786785864.png)
But in react-data-grid-addons there is "src" folder next to dist.
Is it possible to get it ?

**Comment by amanmahajan7** [comment]
`react-data-grid v6` is no longer supported and we recommend upgrading 
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
