### ISSUE TITLE
v7 used in modal? How to?

### ISSUE THREAD

**Issue by oxodesign** [adazzle/react-data-grid#1973]
Hi
I have tried everything (that I can think of) but I cant get this working inside a modal!

Any suggestion or short code snippet on how to implement this?

Thank in advance anyone who can help

**Comment by rahulchavan30** [comment]
Same here inside material ui modal the grid renders but its not editable ..

**Comment by nstepien** [comment]
You can set the `editorPortalTarget` prop to render your editor in a specific DOM node.
It defaults to `document.body`, so your modal probably covers the editors.

**Comment by amanmahajan7** [comment]
Feel free to open a new issue if you are still facing problemns
