### ISSUE TITLE
v7 Feature request: Initial filters

### ISSUE THREAD

**Issue by simonpal** [adazzle/react-data-grid#1974]
Is there any way, or will there be a way, to set initial filters?
I want to store the filters and sort order in react context & localstorage to be able to set them initially if page is reloaded/navigated to.

Sort order works just fine as it is right now but I can't manage to get the filters to work. I've tried to store the filter state variable as is, and set on render but nothing happens. I'm really not keen on finding the fields by DOM (column index) and manually change them.

**Comment by amanmahajan7** [comment]
It is supported in v7 canary. Please check this example
https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/HeaderFilters.tsx
