### ISSUE TITLE
How to stopPropagation when grid is scrolling left?

### ISSUE THREAD

**Issue by owiki** [adazzle/react-data-grid#1976]
I want to stopPropagation in mobile use when the grid is scrolling left.
I just found a property which is called [onScroll](https://adazzle.github.io/react-data-grid/docs/ReactDataGrid#onscroll) in `ReactDataGrid`，but it can't get domEvent，what should i do.
And my local version is `v5.0.4`.

**Comment by amanmahajan7** [comment]
The domEvent event should be available in v7 canary 16
https://github.com/adazzle/react-data-grid/pull/2011
