### ISSUE TITLE
`react-data-grid.css` excluded from production builds; missing "sideEffects"

### ISSUE THREAD

**Issue by ssorallen** [adazzle/react-data-grid#1977]
**Likely fix:**

add the following to package.json

```json
"sideEffects": [
  "*.css"
]
```

**Issue:**

When using Webpack 4 with the alpha branch, building in production mode ends up stripping `'react-data-grid/dist/react-data-grid.css'` because it is not listed in the the `"sideEffects"` array in package.json.

Webpack 4's tree shaking means packages must list exports that have [side effects](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free) so they will be skipped by the shaker. The example in Webpack's docs show `"*.css"` too because typically a library user does a bare import like `import 'react-data-grid/dist/react-data-grid.css';` and expects the CSS to be included.

**Current workaround:**

```js
import rdg from 'react-data-grid/dist/react-data-grid.css';
// the default export is referenced, so Webpack will not exclude it in prod
console.log(rdg);
```

**Comment by amanmahajan7** [comment]
This is fixed in the canary branch and we recommend using v7 canary moving forward
https://github.com/adazzle/react-data-grid/blob/canary/package.json#L22

**Comment by ssorallen** [comment]
@amanmahajan7 Great thanks a lot, I'll switch to the canary build.
