### ISSUE TITLE
Issue with V7, grid only visible after rerender?

### ISSUE THREAD

**Issue by Sappher** [adazzle/react-data-grid#1978]
Hello,

and first, thank you for this awesome component!

I've used V6 and trying to migrate to V7 to get rid of the warning messages to console about depricated lifecycle method usages. I use react-bootstrap as by app's layouting, and V6 worked well with that. Now with V7-alpha I've faced an issue. If I place the grid inside react-bootstrap Container, it only renders as 1px line at first. When I rerender it (I have button in my app to change through a table view (which uses react-data-grid) and another view) it works fine. This behavior didn't occur with V6. and I'm not sure where to start looking for a solution. I'm not sure if this is something to do with react-bootstrap's layout mechanics or something that react-data-grid needs to fix?

**Comment by Sappher** [comment]
Trying to identify to cause, and I ran into a reproducible way to raise this issue.

If I render it like this, it works:
`<Container hidden={hidden_test}>
	<Row>
		<Col>
			<DataGrid
			columns={columns}
			rowGetter={i => rows[i]}
			rowsCount={3}
			height={150}
			/>
		</Col>
	</Row>
</Container>`

But in my production usage the container is hidden by default, and only visible after the user selects to open the continents of the container. So I was able to reproduce this bug with a following component:

`const TestComponent = (props) => {
	const [hidden, setHidden] = React.useState(true);
	
	React.useEffect(() => {
		setHidden(false);
	}, []);
	
	return(
	<Container hidden={hidden}>
		<Row>
			<Col>
				This container is now visible
			</Col>
		</Row>
		<Row>
			<Col>
				<DataGrid
				columns={columns}
				rowGetter={i => rows[i]}
				rowsCount={3}
				height={150}
				/>
			</Col>
		</Row>
	</Container>
	);
}

`

So it starts of as hidden, but after initial render the useEffect is ran which sets it to visible. The rendered component looks like this (the line you see is the DataGrid component)

![image](https://user-images.githubusercontent.com/57065537/77079735-2070db00-6a01-11ea-92d4-64b966d38ded.png)

**Comment by qili26** [comment]
It seems like the issue with bootstrap col. Have you tried to add a wrapper to the RDG and put the fixed height and width outside?

**Comment by Sappher** [comment]
Thank you for a comment!

I tried wrapping the RDG in a div with static height. No change. I've also tried to set a static height to the RDG itself with the minHeight prop, but that didn't work either. Just a reminder, this doesn't happen with earlier version of RDG, so something seems to have changed regarding this.

I'm using version 7.0.0-alpha.29 btw, not sure if the canary version is worth a try to see if this happenes there?

**Comment by qili26** [comment]
First, take a look at the examples here. (this is the latest canary version, https://github.com/adazzle/react-data-grid/releases/tag/v7.0.0-canary.13)
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features

You can find the examples code in this link https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/AllFeatures.tsx#L1.

The alpha version that you are using is a intermediate version between v6 and v7 canary, which only contains the typescript support. The v7 canary version has the latest fixes like performance but with some break changes.

**Comment by amanmahajan7** [comment]
We recommend using the canary version moving forward. Alpha version is kept of easier migration from v6 to v7. In v7 we changed [how width is calculated](https://github.com/adazzle/react-data-grid/blob/canary/src/DataGrid.tsx#L204) and it seems like `Container` component is still rendering the children when it is hidden so the width is not calculated correctly. There are two ways to fix this problem 
- Render the grid when container is visible
```
<Container hidden={hidden}>

  ....
  {!hidden && <DataGrid ... />}
```

- Set the width prop on the grid

**Comment by Sappher** [comment]
Thank you, rendering the grid only when the parent container is visible is a viable fix. I tried this yesterday myself and it worked fine. I will also update to the latest canary version, thank you qili26 for the examples!
