### ISSUE TITLE
[Q] - How can I show all my rows in a table?

### ISSUE THREAD

**Issue by avalanche1** [adazzle/react-data-grid#1984]
I'm using v.7.canary.
For now the table shows 10 rows; the others are scrolled. My table has 30. How can I show the whole table at once?

**Comment by dmbankhead** [comment]
You can change the DataGrid height to show more rows. See below:
 <DataGrid
        columns={columns}
        rows={rows}
        onRowsUpdate={onRowsUpdate}
        height={500}
        rowHeight={25}
      />

**Comment by dmbankhead** [comment]
<**DataGrid
        columns={columns}
        rows={rows}
        onRowsUpdate={onRowsUpdate}
        height={500}
        rowHeight={25}
        enableCellSelect={true}
      />**

**Comment by avalanche1** [comment]
I wish there was an option to do it automatically, w\o hard-coding the value.

**Comment by amanmahajan7** [comment]
Grid cannot automatically calculate the height and you can use a component like [AutoSizer](https://github.com/bvaughn/react-virtualized/blob/master/docs/AutoSizer.md)to adjust the  height
