### ISSUE TITLE
showCheckbox not working

### ISSUE THREAD

**Issue by mcgtech** [adazzle/react-data-grid#1987]
I have tried to get showCheckbox to work with no success.
I setup following https://adazzle.github.io/react-data-grid/docs/quick-start - this installed 7.0.0-canary.13
I then followed the sandbox code from https://adazzle.github.io/react-data-grid/docs/examples/row-selection.
The Checkbox column simply does not appear.
Can anyone help?

Code that I used in App.js

`import React, {Component} from 'react'
import ReactDataGrid from 'react-data-grid';
import 'react-data-grid/dist/react-data-grid.css';

const columns = [
  { key: 'id', name: 'ID' },
  { key: 'title', name: 'Title' }
];

const rows = [
  { id: 0, title: 'Example' },
  { id: 1, title: 'Demo' }
];

class App extends React.Component {
  constructor(props) {
    super(props);
    this._columns = [
      {
        key: "id",
        name: "ID"
      },
      {
        key: "title",
        name: "Title"
      },
      {
        key: "count",
        name: "Count"
      }
    ];

    let rows = [];
    for (let i = 1; i < 1000; i++) {
      rows.push({
        id: i,
        title: "Title " + i,
        count: i * 1000
      });
    }
    this.state = { rows, selectedIndexes: [] };
  }

  rowGetter = i => {
    return rows[i];
  };

  onRowsSelected = rows => {
    this.setState({
      selectedIndexes: this.state.selectedIndexes.concat(
        rows.map(r => r.rowIdx)
      )
    });
  };

  onRowsDeselected = rows => {
    let rowIndexes = rows.map(r => r.rowIdx);
    this.setState({
      selectedIndexes: this.state.selectedIndexes.filter(
        i => rowIndexes.indexOf(i) === -1
      )
    });
  };

  render() {
    const rowText = this.state.selectedIndexes.length === 1 ? "row" : "rows";
    return (
      <div>
        <span>
          {this.state.selectedIndexes.length} {rowText} selected
        </span>
        <ReactDataGrid
          rowKey="id"
          columns={this._columns}
          rows={rows}
          rowGetter={this.rowGetter}
          rowsCount={rows.length}
          minHeight={500}
          rowSelection={{
            showCheckbox: true,
            enableShiftSelect: true,
            onRowsSelected: this.onRowsSelected,
            onRowsDeselected: this.onRowsDeselected,
            selectBy: {
              indexes: this.state.selectedIndexes
            }
          }}
        />
      </div>
    );
  }
}
export default App`

**Comment by amanmahajan7** [comment]
Row selection API has changed in canary and `showCheckbox` prop is no longer supported. Here is the changelog
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md

Here is an example on how to implement selection
https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/CommonFeatures.tsx#L45

**Comment by igoriok1994** [comment]
> Row selection API has changed in canary and `showCheckbox` prop is no longer supported. Here is the changelog
> https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
> 
> Here is an example on how to implement selection
> https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/CommonFeatures.tsx#L45

It is not mentioned in changelog...
