### ISSUE TITLE
only rows and columns props working... not getting full ReactDataGrid API

### ISSUE THREAD

**Issue by PhilippeBnt** [adazzle/react-data-grid#1990]
I installed ReactDataGrid using yarn and used the code of the most basic example from the website. However i only get results using the props: columns={columns} rows={this.state.rows}.
If i try to use rowGetter instead of rows ReactDataGrid fails as if the props row would be required (type error rows undefined). Apparently I am only accessing a simplified API. 
Hereafter the leel of dependencies after installations:
"dependencies": {
    "@blueprintjs/core": "^3.24.0",
    "@blueprintjs/docs-theme": "^3.4.0",
    "@blueprintjs/table": "^3.8.3",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "@trendmicro/react-sidenav": "^0.5.0",
    "cors": "^2.8.5",
    "react": "^16.13.0",
    "react-data-grid": "^7.0.0-canary.14",
    "react-dom": "^16.13.0",
    "react-scripts": "3.4.0"

**Comment by amanmahajan7** [comment]
`rowGetter` prop is removed in canary and will not work. Here is the changelog 
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md

**Comment by bajran** [comment]
Changelog link is not working
