### ISSUE TITLE
Clicking on Editor (dropdown/textbox etc) not working

### ISSUE THREAD

**Issue by ankitsalu** [adazzle/react-data-grid#1992]
just to start with, i copied the code with noting fancy in it....(i wanted to make the field editable with dropdown/textbox), the grid renders fine...but the moment i double click on editable field, the whole page blanks out and i get the below errors in console:
1) static/js/1.chunk.js:211496 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: <SimpleTextEditor />. Did you accidentally export a JSX literal instead of a component?
    in EditorContainer (created by InteractionMasks)

2) **Uncaught Error: Element type is invalid**: expected a string (for built-in components) or a class/function (for composite components) but got: object.
Check the render method of `EditorContainer`

i literally copied the code from example and nothing changed in it...please help

**Comment by dmbankhead** [comment]
I had the same issue however I changed the editor from "editor: <DropDownEditor options={blah}/>" to "editor: () => <DropDownEditor options={blah}" but now I can select a value but as soon as I double click on another cell, it resorts to the original value.... Please help!  Thanks in advance!

**Comment by ankitsalu** [comment]
> I had the same issue however I changed the editor from "editor: " to "editor: () => <DropDownEditor options={blah}" but now I can select a value but as soon as I double click on another cell, it resorts to the original value.... Please help! Thanks in advance!

thanks - i can now see the options to select, but now facing the same issue as you i.e. when I double click on another cell, it resorts to the original value.... I am not sure if the documentation is out of date or what...its difficult to work with grid like this...

please if someone can help...

**Comment by 3pns** [comment]
same here, cant update the value of any cell, onGridRowsUpdated is never triggered

**Comment by ankitsalu** [comment]
I think i have found the issue. the problem is we are using the latest version of this grid which is still in beta mode i think and the documentation is still not updated yet...,also the working examples on site are of previous version. Try installing the below and then your code would work.

Update the version of below in your package.json and then do NPM install. It should update everything to previous version. Afterwards, it should work. It has started working for me now. 

"immutable": "3.8.2",
 "react-data-grid": "5.0.1",
  "react-data-grid-addons": "5.0.1",
