### ISSUE TITLE
Write Docs for v7

### ISSUE THREAD

**Issue by legonigel** [adazzle/react-data-grid#1997]
It seems like all the docs were removed from the canary branch, so there exists no documentation for v7.

Before 7 is released, we need documentation and an updated website.

**Comment by Emp2612** [comment]
The case of the introduction of the V5 document has been reported to the new project and has always reported errors

**Comment by amanmahajan7** [comment]
Please take a look at the change log and examples
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos

We will work on the documentation before the final v7 release
