### ISSUE TITLE
How to enable text Copy to clipboard??

### ISSUE THREAD

**Issue by Shubham-DK** [adazzle/react-data-grid#1998]
The user wants to copy the text, how to enable this feature, which props to use.
I need only copy functionality no editing of cells.

**Comment by jhoneybee** [comment]
mark

**Comment by hangaoke1** [comment]
mark

**Comment by sergeyzenchenko** [comment]
mark

**Comment by Shubham-DK** [comment]
Currently I am doing this by overriding CSS !!

**Comment by ecoleman** [comment]
@Shubham-DK What's the CSS solution look like?

**Comment by Shubham-DK** [comment]
@ecoleman 
I am using this piece of code now, to enable text select for user

            ```
/* To enable user select values in the grid*/
            .react-grid-Grid {
              -webkit-user-select: text !important;
              -webkit-touch-callout: default !important;
              -webkit-user-select: text !important;
              -moz-user-select: text !important;
              -ms-user-select: text !important;
              user-select: text !important;
            }
```

**Comment by amanmahajan7** [comment]
There is a new `onCopy` prop that can be used. Check the PR for more details
https://github.com/adazzle/react-data-grid/pull/2749
