### ISSUE TITLE
TypeError: rows is undefined | 7.0.0-canary.14

### ISSUE THREAD

**Issue by zraineri** [adazzle/react-data-grid#2003]
Following the support docs example [here](https://adazzle.github.io/react-data-grid/docs/examples/default-editor)

I get he following error:

```
TypeError: rows is undefined
DataGrid
.../.../DataGrid.tsx:268

  265 | lastFrozenColumnIndex={columnMetrics.lastFrozenColumnIndex}
  266 | draggableHeaderCell={props.draggableHeaderCell}
  267 | onHeaderDrop={props.onHeaderDrop}
  > 268 | allRowsSelected={selectedRows?.size === rows.length}
  269 | onSelectedRowsChange={onSelectedRowsChange}
  270 | sortColumn={props.sortColumn}
  271 | sortDirection={props.sortDirection}
```

**Version**: Default | ^7.0.0-canary.14
**Using Addons**: No - Just the base package

It looks like the support docs is using version 5.0.1

**Comment by amanmahajan7** [comment]
Please take a look at the change log for canary
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
