### ISSUE TITLE
Custom row renderer

### ISSUE THREAD

**Issue by guifavere** [adazzle/react-data-grid#2021]
Hey guys. First, congrats for the library, it's awesome.

Just a question, is there a method that render a base row, that i could use inside the prop: **rowRenderer**? Sorry if it's a duplicated issue, i've searched for e i didn't find anything related to this.

I'm using the version: **^7.0.0-canary.14**. I remeber that there is something like that on version: **^6.1.0**.

Thanks

**Comment by amanmahajan7** [comment]
You can use the following 

```JSX
import DataGrid, { Row } from 'react-data-grid';

<DataGrid
    ...
    rowRenderer={(props) => {
        return <Row {...props} className={customClass} />;
   }}
/>
```

**Comment by guifavere** [comment]
Thanks!
