### ISSUE TITLE
Feature request: Freezing rows

### ISSUE THREAD

**Issue by jakehjung** [adazzle/react-data-grid#2022]
Is there any way to freeze rows like we can with columns?

**Comment by amanmahajan7** [comment]
Unfortunately we do not have this feature on our roadmap but we are happy to accept a pr. You can use summary rows as a workaround

https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/CommonFeatures.tsx#L289

**Comment by maniyalraj** [comment]
Do we have any workaround for freezing rows?

Requirement:
- Cell Editing should not happen on freezed rows
- The Data should not be allowed to copy and paste
