### ISSUE TITLE
Sorting state classname is missing

### ISSUE THREAD

**Issue by guy032** [adazzle/react-data-grid#2024]
On SortableHeaderCell.js

return (React.createElement("span", { className: `rdg-header-sort-cell rdg-header-sort-${sortDirection}`, onClick: onClick },

I needed to add manually the sortDirection as a classname in order to set a custom icon from CSS.

Please consider add the state of sortDirection to this element.

**Comment by nstepien** [comment]
We recommend implementing your own `Column.headerRenderer` instead.
