### ISSUE TITLE
V7 Container height

### ISSUE THREAD

**Issue by igoriok1994** [adazzle/react-data-grid#2026]
Hi,

Why in V7 is still no availability to use height='100%'?

It would be very convenient, if react-data-grid container height could be dynamic.

**Comment by Cin316** [comment]
You can achieve this with an `AutoSizer` from the "react-virtualized" module.  See the example below:

https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/CommonFeatures.tsx#L275

I do find it odd that this is not built-in though.

**Comment by igoriok1994** [comment]
> You can achieve this with an `AutoSizer` from the "react-virtualized" module. See the example below:

Thanks for advice. I thought about Measure from 'react-measure', but since react-virtualized will be a better decision.

**Comment by qili26** [comment]
https://github.com/bvaughn/react-window#related-libraries

It's better to use `react-virtualized-auto-sizer` if you only need this 1 component rather than the bloated package.

**Comment by emsi-iggy** [comment]
In v6 i did it with css only, so maybe in v7 it is also possible?

**Comment by igoriok1994** [comment]
> In v6 i did it with css only, so maybe in v7 it is also possible?

Me too, but in V7 you cant.
