### ISSUE TITLE
"DragItemTypes" not exported by react-data-grid

### ISSUE THREAD

**Issue by vadManuel** [adazzle/react-data-grid#2027]
Versions:
`"react-data-grid": "^7.0.0-canary.16"`
`"react-data-grid-addons": "^7.0.0-alpha.24"`

Problem:
`react-data-grid-addons/lib/draggable/DraggableHeaderCell.js`   
`react-data-grid-addons/lib/toolbars/GroupedColumnsPanel.js`
Those two files in react-data-grid-addons import DragItemTypes from react-data-grid, but DragItemTypes is not exported by react-data-grid.

Fix (for now):
Change `DragItemTypes.Columns` to `"columns"` in their respective default exports.

**Comment by amanmahajan7** [comment]
`react-data-grid-addons` package will be removed in v7. We recommend copying the relevant components from `react-data-grid-addons` into your local repository and tweak it as needed.

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md

**Comment by biocyberman** [comment]
Will the example be updated accordingly? https://codesandbox.io/s/qqlxyk43j9?from-embed=&file=/src/index.js

Consider the example, are you telling that users should copy content of `Toolbar, Data, Filters ` and remove the following line:

`import { Toolbar, Data, Filters } from "react-data-grid-addons";`

It will be helpful to provide the rationale of the removal.

**Comment by PedrinhowVieira** [comment]
I'm trying to implement DropDownEditor in a table.
```
import * as DataGridAddons from 'react-data-grid-addons';

const typeEditor = <DataGridAddons.DropDownEditor options={typeOptions} />;
```

But I'm getting the same issue:
```
/node_modules/react-data-grid-addons/lib/toolbars/GroupedColumnsPanel.js
Attempted import error: 'DragItemTypes' is not exported from 'react-data-grid'.
```

Those examples from the official page are not working with the new changes so I'm looking here:
[https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/AllFeatures.tsx](https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/AllFeatures.tsx)

If `react-data-grid-addons` will be removed, how the implementation of drop down inside tables will be made?
I did not manage to make it work, do you have any fix or suggestion for these?

**Comment by vadManuel** [comment]
I'm using [Material-UI](https://material-ui.com), but you can change the dropdown to whatever UI framework you want (if any).

```
import React from 'react'
import PropTypes from 'prop-types'
import TextField from '@material-ui/core/TextField'
import Autocomplete from '@material-ui/lab/Autocomplete'

export class DropdownCell extends React.Component {
  constructor(props) {
    super(props)

    this.state = { value: props.value }

    this.ref = React.createRef()
    this.onChange = this.onChange.bind(this)
  }

  getValue() {
    return { [this.props.column.key]: this.state.value }
  }

  getInputNode() {
    return this.ref
  }

  onChange(_, value) {
    this.setState({ value })
    // This will close the dropdown as soon as an option is selected
    // this.props.onCommit()
  }

  render() {
    return (
      <Autocomplete
        ref={this.ref}
        autoHighlight
        value={this.state.value}
        options={['option 1', 'option 2', 'option 3']}
        getOptionLabel={s => s}
        getOptionDisabled={s => this.state.value === s}
        onChange={this.onChange}
        renderInput={params => (
            <TextField
                {...params}
                size='small'
                fullWidth
            />
        )}
      />
    )
  }
}

DropdownView.propTypes = {
  value: PropTypes.any,
  onCommit: PropTypes.func
}
```

**Comment by PedrinhowVieira** [comment]
@vadManuel Thanks for the answer. One thing tho, how would I add this `DropdownCell` to the react-data-grid table?
Currently in those examples they use
```
{
      key: 'title',
      name: 'Title',
      editor: React.forwardRef((props, ref) => <DropDownEditor ref={ref} {...props} options={titles} />),
      width: 200,
      resizable: true,
      formatter(props) {
        return <>{props.row.title}</>;
      }
 },
```

**Comment by vadManuel** [comment]
@PedrinhowVieira 

Create a reusable function instead of what they did.
```
export const ObjectFormatter = (props) => {
  return <div>{props.row[props.column.key]}</div>
}

ObjectFormatter.propTypes = {
  column: PropTypes.shape({
    key: PropTypes.string
  })
}
```

Then put it on one of your columns like so...

```
columns = [
  { name: 'Column Name', key: 'columnKey', width: 128, defaultEntry: null, formatter: ObjectFormatter, editor: DropdownCell }
]
```

Remember that if you want to pass anything to that specific column you can add it as a field.
For example: `{ name: 'Column Name', ..., editor: DropdownCell, otherStuff: { hi: 'im other stuff', stuff: 123 }}`
Now this is accessable via `props.column.otherStuff`.

**Comment by PedrinhowVieira** [comment]
@vadManuel Thank you for the help!
