### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined DataGrid src/DataGrid.tsx:247

### ISSUE THREAD

**Issue by rajeevAgilehub** [adazzle/react-data-grid#2030]
244 |   - (summaryRows?.length ?? 0) * rowHeight
  245 |   - (totalColumnWidth > viewportWidth ? getScrollbarSize() : 0);
  246 | 
> 247 | const [rowOverscanStartIdx, rowOverscanEndIdx] = getVerticalRangeToRender(
      | ^  248 |   clientHeight,
  249 |   rowHeight,
  250 |   scrollTop,

**Comment by gds3k3** [comment]
Same error.
Here go an example:

`
var rows = [
		{ name: 'Tito', _id: '234543534', groups: 'casa', hab: 'si' },
		{ name: 'Pepe', _id: '2345432429', groups: 'taller', hab: 'si' },
		{ name: 'Cacho', _id: '2345348233', groups: 'oficina', hab: 'si' }
	]; 

const columns = [
	{ key: '_id', name: 'ID' },
	{ key: 'name', name: 'Nombre' },
	{ key: 'groups', name: 'Grupos' }, 
	{ key: 'hab', name: 'Hab' }, 
];
	return (    
			<ReactDataGrid
			        columns={ columns }
				rowGetter={ i => rows[i] }
				rowsCount={ 3 }
			/>
          )

`

**Comment by patrick-salvatore** [comment]
The example in the docs resolves to this error message. 

https://adazzle.github.io/react-data-grid/docs/examples/default-editor

![Screen Shot 2020-05-11 at 9 55 47 PM](https://user-images.githubusercontent.com/44264255/81629998-78f5a080-93d2-11ea-9d2f-b87c95422c16.png)


```
import React, { useState } from 'react';
import ReactDataGrid from 'react-data-grid';

const columns = [
  { key: 'id', name: 'ID', editable: true },
  { key: 'title', name: 'Title', editable: true },
  { key: 'complete', name: 'Complete', editable: true },
];

const rows = [
  { id: 0, title: 'Task 1', complete: 20 },
  { id: 1, title: 'Task 2', complete: 40 },
  { id: 2, title: 'Task 3', complete: 60 },
];

const grid = () => {
  const [gridState, setGridState] = useState<any>(rows);

  const onGridRowsUpdated = ({ fromRow, toRow, updated }) => {
    setGridState(gridState => {
      const rows = gridState.slice();
      for (let i = fromRow; i <= toRow; i++) {
        rows[i] = { ...rows[i], ...updated };
      }
      return { rows };
    });
  };

  return (
    <ReactDataGrid
      columns={columns}
      rowGetter={i => gridState[i]}
      rowsCount={3}
      onGridRowsUpdated={onGridRowsUpdated}
      enableCellSelect={true}
    />
  );
};

export default grid;

```

**Comment by eren0613** [comment]
try 
   return (
        <ReactDataGrid rows={rows}
                       columns={columns}/>
    );

**Comment by eren0613** [comment]
try
```
return (
        <ReactDataGrid rows={rows}
                       columns={columns}/>
    );
```

**Comment by gds3k3** [comment]
> 
> 
> try
> 
> ```
> return (
>         <ReactDataGrid rows={rows}
>                        columns={columns}/>
>     );
> ```

Yes it works thank you. Not even a mention of rows prop in documentation, that seems out outdated, btw. Now the grid exhibit a strange "vertical" style. V7 looks as a inmature release.

**Comment by amanmahajan7** [comment]
Please take a look at the changelog and examples. V7 stable version has not been released yet

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos

**Comment by rajeevAgilehub** [comment]
Thanks,
here is working example 
https://codesandbox.io/s/react-data-grid-typescript-hwwth?file=/src/index.tsx

**Comment by rickcha** [comment]
blocker

**Comment by rickcha** [comment]
Try this is your package.json. This commit worked fine.
"react-data-grid": "https://registry.yarnpkg.com/react-data-grid/-/react-data-grid-7.0.0-alpha.29.tgz#9e52f4d61dc7818f6cd4ef83d8bb296743b4e903",

**Comment by RobsonSilveira** [comment]
Had the same error and I just resolved that installing react-data-grid version 5.0.1.

I ran:
npm i react-data-grid@5.0.1

code:
/* eslint-disable react/jsx-boolean-value */
/* eslint-disable react/destructuring-assignment */
/* eslint-disable no-plusplus */
/* eslint-disable no-shadow */
import React from 'react';
import ReactDataGrid from 'react-data-grid';

const columns = [
    { key: 'id', name: 'ID', editable: true },
    { key: 'title', name: 'Title', editable: true },
    { key: 'complete', name: 'Complete', editable: true },
];

const rows = [
    { id: 0, title: 'Task 1', complete: 20 },
    { id: 1, title: 'Task 2', complete: 40 },
    { id: 2, title: 'Task 3', complete: 60 },
];

export default class Example extends React.Component {
    state = { rows };

    onGridRowsUpdated = ({ fromRow, toRow, updated }) => {
        this.setState(state => {
            const rows = state.rows.slice();
            for (let i = fromRow; i <= toRow; i++) {
                rows[i] = { ...rows[i], ...updated };
            }
            return { rows };
        });
        console.log('')
    };

    render() {
        return (
            <ReactDataGrid
                // rows={rows}
                columns={columns}
                rowGetter={i => this.state.rows[i]}
                rowsCount={3}
                onGridRowsUpdated={this.onGridRowsUpdated}
                enableCellSelect={true}
            />
        );
    }
}

Hope I can help someone! \o.

**Comment by monicaecastillo** [comment]
@RobsonSilveira it worked for me!! Thanks! Additionally I had to install _immutable_ dependency due to an error of "undefined" after installing the 5.0.1 version. ( npm install --save immutable)

**Comment by ronaldzx** [comment]
> Had the same error and I just resolved that installing react-data-grid version 5.0.1.
> 
> I ran:
> npm i react-data-grid@5.0.1
> 
> code:
> /* eslint-disable react/jsx-boolean-value _/ /_ eslint-disable react/destructuring-assignment _/ /_ eslint-disable no-plusplus _/ /_ eslint-disable no-shadow */
> import React from 'react';
> import ReactDataGrid from 'react-data-grid';
> 
> const columns = [
> { key: 'id', name: 'ID', editable: true },
> { key: 'title', name: 'Title', editable: true },
> { key: 'complete', name: 'Complete', editable: true },
> ];
> 
> const rows = [
> { id: 0, title: 'Task 1', complete: 20 },
> { id: 1, title: 'Task 2', complete: 40 },
> { id: 2, title: 'Task 3', complete: 60 },
> ];
> 
> export default class Example extends React.Component {
> state = { rows };
> 
> ```
> onGridRowsUpdated = ({ fromRow, toRow, updated }) => {
>     this.setState(state => {
>         const rows = state.rows.slice();
>         for (let i = fromRow; i <= toRow; i++) {
>             rows[i] = { ...rows[i], ...updated };
>         }
>         return { rows };
>     });
>     console.log('')
> };
> 
> render() {
>     return (
>         <ReactDataGrid
>             // rows={rows}
>             columns={columns}
>             rowGetter={i => this.state.rows[i]}
>             rowsCount={3}
>             onGridRowsUpdated={this.onGridRowsUpdated}
>             enableCellSelect={true}
>         />
>     );
> }
> ```
> 
> }
> 
> Hope I can help someone! \o.

worked for me

**Comment by tripleplayj** [comment]
Did anyone ever get this example working with hooks? I see @patrick-salvatore attempted this but I don't see a solution besides downgrading the version and using the original structure of components for React.

**Comment by Aadilmusavir** [comment]
In the newer Versions they have change the syntax and functions now for the latest version which is 7 .0 beta version , it should be like this

import DataGrid from 'react-data-grid';

const columns = [
  { key: 'id', name: 'ID' },
  { key: 'title', name: 'Title' }
];

const rows = [
  { id: 0, title: 'Example' },
  { id: 1, title: 'Demo' }
];

function App() {
  return <DataGrid columns={columns} rows={rows} />;
}
