### ISSUE TITLE
Excel-like Header Group for Columns

### ISSUE THREAD

**Issue by mohsenomidi** [adazzle/react-data-grid#2031]
Dear Contributors, 

Hope you are doing well, I am using react data grid to manage the complex data grid with grouping header, for example in some complex business models we need to define the group of header columns like image below: 

![fa9ca028-3a4f-11e7-99b8-3b3cc96797a7](https://user-images.githubusercontent.com/47596867/81648628-43899b00-9444-11ea-846c-771da9a2c5cd.jpg)

currently i can not find any way to handle this Excel-Like grouping header. 
There are some request issue, like #765 , #1066, #1287, #458, #410, but there is no any helpful answer or any solution for it. 

i would like to kindly ask, Is there possibility to add this useful behavior in your wonderful library ?

Regards,

**Comment by ggcatu** [comment]
Our team would also benefit from this.

**Comment by ravipatel2293** [comment]
Guys, Have you found any workaround for this?

**Comment by ekeuus** [comment]
I made a initial MVP proposal here - https://github.com/adazzle/react-data-grid/issues/2031

The more feedback we get for it, the more likely it is to be what everyone needs?
