### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by nkkollaw** [adazzle/react-data-grid#2034]
I was trying to figure out how to use this library (looks awesome BTW), but the doc site is on 5.something, and the library is on version 7.

It also looks like the API is not compatible with newer versions.

I think there should be up-to-date documentation somewhere. Also, removing links to the website could help, since if you follow that things will break.

**Comment by amanmahajan7** [comment]
Related issue: https://github.com/adazzle/react-data-grid/issues/1957

Please check the changelog and examples. We are still working on v7 and will update the docs when the stable version is out 

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos

**Comment by nkkollaw** [comment]
Ah, awesome! Thanks.

I think linking to these files in the meantime would be useful.
