### ISSUE TITLE
DragItemTypes' is not exported from 'react-data-grid'

### ISSUE THREAD

**Issue by Sshahzad14** [adazzle/react-data-grid#2035]
I am trying to create dynamic table with option to filter columns using React-Data-Grid and "react-data-grid-addons". I have imported react-data-grid (version 6.0.0) and react-data-grid-addons (version 7.0.0-alpha.30). Whenever i try to compile the code it fails with this error. 
react version is 16.12.0

`import ReactDataGrid from "react-data-grid";
import { Toolbar, Data, Filters } from "react-data-grid-addons"; //importing this gives compilation error 

./node_modules/react-data-grid-addons/lib/toolbars/GroupedColumnsPanel.js
Attempted import error: 'DragItemTypes' is not exported from 'react-data-grid'.`

**Comment by amanmahajan7** [comment]
`react-data-grid-addons` package will be removed in v7. We recommend copying the relevant components from react-data-grid-addons into your local repository and tweak it as needed.

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos

**Comment by vadManuel** [comment]
Go to #2027
