### ISSUE TITLE
Inline editing with strange behavior when grid is inside accordion

### ISSUE THREAD

**Issue by philxavier** [adazzle/react-data-grid#2036]
Hello Folks,

I'm rendering the grid inside an accordion from Chakra UI. I open the accordion and everything is ok until I try to edit some data. Then, what happens is this weird behavior in which the editing cells shows up at the bottom of the page. I'm pretty sure this is related to the overflow created by the rendering of the grid. Was not able to come up with a solution and was not able to find any issue related to this. Has anyone dealt with this before?

![image](https://user-images.githubusercontent.com/7192635/81847700-f2e86f80-9521-11ea-89f0-dd1b7b70b3ad.png)

Thanks a lot!!

**Comment by emsi-iggy** [comment]
Firstly you should say which version you are using.
Secondly it looks like css problem.

**Comment by amanmahajan7** [comment]
Can you please try v7 canary and create a codesandbox example if the issue still exists?
