### ISSUE TITLE
RDG V7 Cell Editor bug

### ISSUE THREAD

**Issue by igoriok1994** [adazzle/react-data-grid#2037]
Hi,

Default cell editor is not working well. It is always "under the grid" and not visible...

Version - v7 canary.16

![image](https://user-images.githubusercontent.com/37294916/82427380-b40e6880-9a91-11ea-88ab-2520f3a2a70a.png)

**Comment by igoriok1994** [comment]
Tried to modify style:

```
rdg-editor-container {
z-index: 1000 !important;
}
```

... results is the same...

**Comment by igoriok1994** [comment]
Btw, maybe someone know how to get column metrics from RDG V.7? Column actual widths, etc...

**Comment by qili26** [comment]
1. As far as I know, there is no such function for exporting the column metrics.
2. For the editor issue, you can check this `prop`. Based on my observation, you are trying to display the grid in a modal, right? If so, you have to make sure the editor portal is rendering next to the grid.
https://github.com/adazzle/react-data-grid/blob/canary/src/DataGrid.tsx#L142

**Comment by igoriok1994** [comment]
> 1. As far as I know, there is no such function for exporting the column metrics.
> 2. For the editor issue, you can check this `prop`. Based on my observation, you are trying to display the grid in a modal, right? If so, you have to make sure the editor portal is rendering next to the grid.
>    https://github.com/adazzle/react-data-grid/blob/canary/src/DataGrid.tsx#L142

Yes, portal target - document.body. I have added z-index: 1 for rdg-editor-container globally, and all is working fine.

**Comment by igoriok1994** [comment]
About col metrics - it is a bit strange. 
Somewhere grid should have information about column sizes (default and after resize).
https://github.com/adazzle/react-data-grid/blob/canary/src/DataGrid.tsx#L213
