### ISSUE TITLE
V7 public methods

### ISSUE THREAD

**Issue by igoriok1994** [adazzle/react-data-grid#2038]
Hi,

Now in V7 only few public methods are available: **scrollToRow, scrollToColumn, selectCell**...

I think it would be useful to have getters for grid ref (html element), **column metrics** and maybe some other data (such as widths, heights and other...)

**Comment by igoriok1994** [comment]
Up

**Comment by nstepien** [comment]
The grid element is accessible via the ref object.
I don't think we'll add more as we don't want to have too many APIs to support.
