### ISSUE TITLE
Undefined Error and Odd Deprecation Warnings after upgrading from v4 to v6

### ISSUE THREAD

**Issue by amber-cd** [adazzle/react-data-grid#2039]
I recently upgraded from v4 to v6. Seeing two strange behaviors.

The first is a "enableRowSelect has been deprecated and will be removed in a future version. Please use rowSelection instead " warning, despite the fact that I'm not using that prop anywhere. I suspect it may be caused by the default props... was [this PR](https://github.com/adazzle/react-data-grid/pull/1538) ever implemented for v6? I know it mentioned being in v7, but as that's still a canary version, I'd rather not upgrade to it.

My bigger issue, however, is that I'm getting an odd error and I have no idea if it should concern me or what could be causing it...

![image](https://user-images.githubusercontent.com/30151077/82461089-00ed4180-9a88-11ea-8bbe-9b195c14e5cb.png)

The stacktrace points to somewhere in the checkPropTypes method?

![image](https://user-images.githubusercontent.com/30151077/82461338-51649f00-9a88-11ea-8726-dfd90ed8d3f4.png)

Not sure if this might also be due to a default prop issue... I'd like to give more information but I'm honestly not quite sure where to start.

**Comment by amanmahajan7** [comment]
Old versions of `react-data-grid` are no longer supported and we recommend upgrading 
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
