### ISSUE TITLE
V7 Editor API (need examples)

### ISSUE THREAD

**Issue by igoriok1994** [adazzle/react-data-grid#2041]
Hi everyone,

Can somebody show example of working **editor**? 

Eg. Checkbox editor:

When you double clicking the cell - checkbox appears and after onChange value is committed to grid (or like that).

**Comment by igoriok1994** [comment]
Seems, that **onCommit** function is not working. 
Btw, can somebody explain HOW forwardRef api should be used with editors?

**Comment by jhoneybee** [comment]
```tsx
React.forwardRef((
                    eProps: EditorProps<T[keyof T], T, unknown>,
                    ref,
) => {
                    // eslint-disable-next-line react-hooks/rules-of-hooks
                    const domRef = useRef<any>(null);
                    // eslint-disable-next-line react-hooks/rules-of-hooks
                    useImperativeHandle(ref, () => ({
                        getValue: () => domRef.current.getValue(),
                        getInputNode: () => domRef.current.getInputNode(),
                    }))
                    return <CustomEditor ref={domRef} node={TempEditor} extProps={eProps}/>
})
```
implement 

- getValue
- getInputNode 

example

- https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/components/Editors/DropDownEditor.tsx

**Comment by amanmahajan7** [comment]
Please check the examples for the new editor API

https://github.com/adazzle/react-data-grid/pull/2102
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/CommonFeatures.tsx#L85

**Comment by amanmahajan7** [comment]
Old editor will be removed in v7
