### ISSUE TITLE
Override rdg-cell-action

### ISSUE THREAD

**Issue by diez-esteban** [adazzle/react-data-grid#2043]
Hi all,

I'm getting into customizing CellActions and added a couple of actionable images to my grid rows. What I'm seeing is that react-data-grid adds a default height/width for those icons thru the rdg-cell-action class.

How can I possibly override that css so that I can determine the size for my own icons? 

Thank you.

**Comment by amanmahajan7** [comment]
`CellActions` props have been removed from `react-data-grid` as it can be easily implemented with a custom formatter. Please check the latest example, the formatter can be customized as needed. This approach should also work in the old versions of rdg

https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/CellActions.tsx
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--cell-actions
