### ISSUE TITLE
What is the support availability of pre V7 versions?

### ISSUE THREAD

**Issue by Ragzzy-R** [adazzle/react-data-grid#2044]
Hello, 

I'm seeing a lot of older bugs getting addressed in v7 which is a good thing but unfortunately, many are using v5 or even v2 in production and upgrading to v7 is not practical for many. So is any pre V7 versions are automatically deprecated/not supported anymore. or are they still maintained/supported?

**Comment by amanmahajan7** [comment]
Unfortunately due to lack of resources we are unable to support the old versions but we will accept PRs
