### ISSUE TITLE
cellClass function with row information

### ISSUE THREAD

**Issue by Viker94** [adazzle/react-data-grid#2045]
Hi all,

It would be very useful if cellClass function could get row information such as row index (something similar to formatter arguments). I'm doing validation for grid and without row index I can't find proper error row.

**Comment by amanmahajan7** [comment]
We want to keep the API simple and `rowIdx` would not work well with [grouping](https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--grouping). I would recommend using `rows.indexOf(row)`
