### ISSUE TITLE
Attempted import error: 'DragItemTypes' is not exported from 'react-data-grid'.

### ISSUE THREAD

**Issue by jaggu07** [adazzle/react-data-grid#2047]
`"react-data-grid": "^7.0.0-canary.16",
    "react-data-grid-addons": "^7.0.0-alpha.24",`
When i import react-data-grid-addons 
tried `import * as DataGridAddons from 'react-data-grid-addons';` and `import { Data, Toolbar} from 'react-data-grid-addons';`
it throws 
![Screenshot 2020-05-28 at 7 42 58 PM](https://user-images.githubusercontent.com/24666863/83152476-7954a200-a11b-11ea-9417-6758a772f133.png)

**Comment by amanmahajan7** [comment]
`react-data-grid-addons` package has been deprecated and it is no longer supported. We recommend copying the relevant code in your project
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
