### ISSUE TITLE
Double-click or click and drag to set filter values?

### ISSUE THREAD

**Issue by biocyberman** [adazzle/react-data-grid#2048]
Been searching for a while but haven't found it, therefore I am sorry if this has been asked before. What I want: 
when the table/grid has filter rows enabled, besides typing values in to the input boxes on top of each column, is there a way to double click or click and drag a cell value to the input boxes?

**Comment by nstepien** [comment]
We do not support filters anymore.
We suggest implementing custom filter rows yourself with custom formatters and row types.
