### ISSUE TITLE
Expected Row state to match memoized state before processing the update queue

### ISSUE THREAD

**Issue by tysoncadenhead** [adazzle/react-data-grid#2053]
I'm getting a ton of these:

```index.js:1 Warning: Expected Row state to match memoized state before processing the update queue. This might either be because of a bug in React, or because a component reassigns its own `this.props`. Please file an issue.index.js:1 Warning: Expected Row state to match memoized state before processing the update queue. This might either be because of a bug in React, or because a component reassigns its own `this.props`. Please file an issue.````

I'm running version `6.1.0` with React `16.12.0`.

As far as I can tell, there are no side-effects happening anywhere. Could this be a compatibility issue or something else?

**Comment by amanmahajan7** [comment]
Can you test the code with v7 canary.

**Comment by amanmahajan7** [comment]
Closing due to lack of response
