### ISSUE TITLE
Text double-paste in empty cell

### ISSUE THREAD

**Issue by Tatabakbak** [adazzle/react-data-grid#2054]
I have a bug, which can be easyly reproduced in demo (https://adazzle.github.io/react-data-grid/docs/examples/simple-grid).

To reproduce try double-click empty cell and paste some text from clipboard using ctrl+v.

For example, if you have "Task 3" in clipboard - text "Task 3Task 3" will be pasted in cell.

If you copy some text (e.g. "Task3"), then copy some whole cell (e.g. with text "Task1" in it), and then perform double-click and ctrl+v in emty cell - "Tak3Task1" will be pasted.

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.
