### ISSUE TITLE
Row width not adjusted to parent component

### ISSUE THREAD

**Issue by mielsi30** [adazzle/react-data-grid#2055]
Hello, I've browsed through the issues ad haven't found a similar problem. 
I have a react data grid with 2 columns inside a Card component of 300px width. However the rows on the data grid have an inline style of 500px, which causes the columns to be displayed as below (basically overflowing the card):

<img width="604" alt="div screenshot" src="https://user-images.githubusercontent.com/17486082/84478837-402b3e80-ac92-11ea-8e69-c42ad2a5d222.png">

<img width="1022" alt="elements screenshot" src="https://user-images.githubusercontent.com/17486082/84478854-47524c80-ac92-11ea-90f2-306457a1081c.png">

From my understanding the react data grid should adjust to the parent's width, but I'm not sure why this isn't happening. I already tried using different values for `minColumnWidth` but this didn't help.

- Using version 5.0.5.

Any help is greatly appreciated :)

**Comment by amanmahajan7** [comment]
Version 5.0.5 is no longer supported. Can you try with the latest version of rdg
https://github.com/adazzle/react-data-grid/releases

Feel free to open a new issue if the issue still exists
