### ISSUE TITLE
Update Docs on Website

### ISSUE THREAD

**Issue by pabloimrik17** [adazzle/react-data-grid#2056]
Hi guys,

im trying to figure out if your component have all the features i need on the current project im working on, but the component seems to have changed a lot from version 5 to 6 and i cant find everything just looking at the definitions on *.d.ts files that component haves one i installed it on my project.

**Comment by axmccx** [comment]
I noticed this too when I started using version 7 of the component a few weeks ago. I ended up cloning the repo, and running the storybook. It's not as useful as proper documentation, but I found it helpful in understanding how the component works.

**Comment by pabloimrik17** [comment]
> I noticed this too when I started using version 7 of the component a few weeks ago. I ended up cloning the repo, and running the storybook. It's not as useful as proper documentation, but I found it helpful in understanding how the component works.

Well its something, thank you for the idea ;)

**Comment by ScreamZ** [comment]
+1

**Comment by daniel-butler** [comment]
+1

**Comment by amanmahajan7** [comment]
We will update documentation once the final version of V7 is released
https://github.com/adazzle/react-data-grid/issues/1957#issuecomment-596028903
