### ISSUE TITLE
Header row wrapping

### ISSUE THREAD

**Issue by ScreamZ** [adazzle/react-data-grid#2060]
Hello,

I searched but I'm not sure if there is a specific way to deal with that.

**My problem**: I have Header column with very long text and I would like to know if there is an easy way to make the text wrap for the column (in the header only) to render the header on two lines ? Within the box it has.

Instead of just overflowing in the void

I started with `headerRenderer` but maybe there is an easier way ?

Regards

**Comment by amanmahajan7** [comment]
I believe you can set the `headerRowHeight` and use a custom `headerRenderer` with a different `line-height`
https://github.com/adazzle/react-data-grid/blob/canary/src/DataGrid.tsx#L86

Example of custom header rendered
https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/ColumnsReordering.tsx#L75
