### ISSUE TITLE
Support for Multiple sorting

### ISSUE THREAD

**Issue by Stratoff** [adazzle/react-data-grid#2063]
**I'm submitting a ... (check one with "x")**
```
[ ] bug report
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```
**Current behavior**
Single column sorting

**Expected/desired behavior**
Multiple columns sorting

It could be very useful.

**Comment by jhoneybee** [comment]
mark

**Comment by nstepien** [comment]
This feature got implemented in https://github.com/adazzle/react-data-grid/pull/2365
