### ISSUE TITLE
Cell range selection in more recent versions of lib

### ISSUE THREAD

**Issue by flipmokid** [adazzle/react-data-grid#2064]
Hello,

I've looked through the code and documentation but I'm not 100% sure if range selection still works. I saw in recent release notes that cell selection range props had been removed. Is it still possible to select ranges now, and if so, would it be possible to point me to how it should now be done?

Regards

**Comment by amanmahajan7** [comment]
Duplicate issue https://github.com/adazzle/react-data-grid/issues/1930
