### ISSUE TITLE
Custom headerRenderer does not receive props to implement sorting

### ISSUE THREAD

**Issue by ShantanuNair** [adazzle/react-data-grid#2065]
I would expect `onSort, sortColumn, sortDirection` to be passed on to the supplied HeaderRenderer by SortableHeaderCell to allow custom implementation of marking/triggering sort. However it seems like the current implementation of SortableHeaderCell does not allow us to customize the sorting functionality like, say, changing the way the sort state (ASC/DESC/NONE) is indicated. 

Is this going to change, or is there a workaround/way to do it in the current canary?

**Comment by nanandn** [comment]
Will this be supported soon?
