### ISSUE TITLE
DropDownEditor not found

### ISSUE THREAD

**Issue by zillemarco** [adazzle/react-data-grid#2067]
I'm trying to implement a data grid where some column have a custom editor which is a drop down.

Looking at the stories, the `AllFeatures.tsx` story, uses a `DropDownEditor` but I can only find `SimpleTextEditor`.
Then I found that it could be contained inside the `react-data-grid-addons` module but after its installations, the compiler says `Could not find a declaration file for module 'react-data-grid-addons'` so I tried to run `npm install @types/react-data-grid-addons` but `@types/react-data-grid-addons` can't be found in the registry.

Any hint on how I can use a drop down editor, or import the addons?

I installed both `react-data-grid` and `react-data-grid-addons` with npm recently so I'm using these versions:
- `react-data-grid`: 7.0.0-canary.16
- `react-data-grid-addons`: 7.0.0-alpha.24

**Comment by amanmahajan7** [comment]
`react-data-grid-addons` package has been deprecated. We recommend copying old editors from the addons package and modifying as needed. This was done as it hard to support custom editors and handle various needs 

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
