### ISSUE TITLE
Problem with Optional chaining and Next.js

### ISSUE THREAD

**Issue by beegweeg** [adazzle/react-data-grid#2069]
I have demo next.js application and trying to add react data grid 7.0.0-canary.17 version.
Canary.16 works fine. There is a source with a problem: https://github.com/beegweeg/NextDataGridIssue

[ error ] ./node_modules/react-data-grid/lib/Cell.js 10:19
Module parse failed: Unexpected token (10:19)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     function handleCellClick() {
|         selectCell();
>         onRowClick?.(rowIdx, row, column);
|     }
|     function handleCellContextMenu() {

**Comment by amanmahajan7** [comment]
It seems like an issue with the configuration. Check how storybook build handles it
https://github.com/adazzle/react-data-grid/blob/canary/babel.config.json
https://github.com/adazzle/react-data-grid/blob/canary/.storybook/webpack.config.js

**Comment by connor4312** [comment]
I'm also running into this on the latest Canary. I believe Storybook does some magic with passing everything through Babel. However, in general I would not expect that I have to use Babel at runtime to load dependencies -- I've built dozens of apps and never needed to do so 🙂 

Downgrading to Canary 16 resolved this.

**Comment by SimonErich** [comment]
+1

**Comment by SimonErich** [comment]
We just solved this problem in next by using the following package:
https://github.com/martpie/next-transpile-modules

The problem was, that - while we are transpiling in our code - the node_modules were not transpiled and therefore did not allow for es syntax > 5.
By using this package, we told nextjs to transpile react-data-grid package and now everything works fine.

**Comment by connor4312** [comment]
Generally you should not have to transpile modules, though. That increases build time and requires everyone to add additional configuration to use the library which is not desirable.

cc @amanmahajan7

**Comment by SimonErich** [comment]
@connor4312 yeah, I completely agree.
Just wanted to post my solution for others in the meantime.
