### ISSUE TITLE
Shoudnt the website docs be updated to the newest code or atleast have a message in bold

### ISSUE THREAD

**Issue by KPpuria** [adazzle/react-data-grid#2070]
After pushing the v7 update the website documentation is not updated and there is no message on the website that the documentation is absolute for the newest version. I just spent the entire day implementing features only to realize i will have to read the change log and refactor the code.

**Comment by amanmahajan7** [comment]
Duplicate issue

https://github.com/adazzle/react-data-grid/issues/2056#issuecomment-653230295
