### ISSUE TITLE
V7 Docs

### ISSUE THREAD

**Issue by KPpuria** [adazzle/react-data-grid#2071]
Hi, i just wanted to get a sense of when the documentation is planned to be uploaded. As i am trying to implement the project on a pretty large scale i wanted some help figuring out if I have the time to wait till your docs and library are updated or should i go looking for another library. Thanks in advance. Big fan of the library BTW, good job!

**Comment by jhoneybee** [comment]
Looking at the source code is a great way to learn compared to documentation。

**Comment by amanmahajan7** [comment]
Duplicate issue https://github.com/adazzle/react-data-grid/issues/2171
