### ISSUE TITLE
Cell editing via Dialog is left uncompleted because it gets dismissed

### ISSUE THREAD

**Issue by repl-ullas-ml** [adazzle/react-data-grid#2076]
The scenario is I have a cell and when the user tries to edit it, I need to pop a material UI Dialog. The dialog contains a dropdown ie a material ui select component. When the user intends to select a option from the dropdown situated on the dialog, the grid simply force closes the dialog.

https://codesandbox.io/s/rdg-custom-editors-y07i1?file=/src/DropdownEditor.js:152-166

**Comment by amanmahajan7** [comment]
v5 is no longer supported. Can you try the latest canary version.
