### ISSUE TITLE
Not compiling after install

### ISSUE THREAD

**Issue by ad798** [adazzle/react-data-grid#2077]
./node_modules/react-data-grid/lib/DataGrid.js 102:37
Module parse failed: Unexpected token (102:37)
File was processed with these loaders:
 ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   const totalHeaderHeight = headerRowHeight + (enableFilters ? headerFiltersHeight : 0);
|   const clientHeight = height - 2 // border width
totalHeaderHeight - (summaryRows?.length ?? 0) * rowHeight - (totalColumnWidth > viewportWidth ? getScrollbarSize() : 0);
|   const [rowOverscanStartIdx, rowOverscanEndIdx] = getVerticalRangeToRender(clientHeight, rowHeight, scrollTop, rows.length);
|   /**

As you can see this error shows up when trying to run and compile the example in the docs. Thanks for your help.

**Comment by sergeyt** [comment]
@ad798 you have to adjust babel config to support es2020, react-data-grid by some reason [targets es2020](https://github.com/adazzle/react-data-grid/blob/canary/tsconfig.json#L17)

**Comment by igoriok1994** [comment]
> @ad798 you have to adjust babel config to support es2020, react-data-grid by some reason [targets es2020](https://github.com/adazzle/react-data-grid/blob/canary/tsconfig.json#L17)

IMHO, It is not possible for everyone, eg I'm using Babel 6 and can't support ES2020. Big project, a lot of dependencies. 
It will be painful to update ENV to Babel 7 (some day it will happen, but not soon).  So I believe, that this lib must be compiled to ES5 for compatibility.

**Comment by ad798** [comment]
Thank you @sergeyt. I have not tried it yet but could be a solution. I'll keep this issue open to get more answers.
@igoriok1994 For sure is a good idea.

**Comment by sergeyt** [comment]
@ad798 as workaround you can fork this repo, change target in tsconfig.json to ES2015 at least. put compiled files to git and use your fork as npm dependency. we are using this way to use this library with custom fixes

**Comment by sergeyt** [comment]
@igoriok1994 agree this lib should be compiled at least to ES2015

**Comment by igoriok1994** [comment]
Btw, related with #2074

**Comment by sprutner** [comment]
I also have this issue after following the quick start guide.

**Comment by jhoneybee** [comment]
@sprutner  

Configure webpack include, or editor tsconfig.json to "target": "es5".

or use the version I built lowered the target.

```
npm install react-data-grid-temp
```

**Comment by Lakshmy84** [comment]
Any udates on this thread. Even I am facing the same issue
./node_modules/react-data-grid/lib/DataGrid.js 136:37
Module parse failed: Unexpected token (136:37)
You may need an appropriate loader to handle this file type.
|   var totalHeaderHeight = headerRowHeight + (enableFilters ? headerFiltersHeight : 0);
|   var clientHeight = height - 2 // border width
>   - totalHeaderHeight - (summaryRows?.length ?? 0) * rowHeight - (totalColumnWidth > viewportWidth ? getScrollbarSize() : 0);
| 
|   var _getVerticalRangeToRe = getVerticalRangeToRender(clientHeight, rowHeight, scrollTop, rows.length),

**Comment by diez-esteban** [comment]
Hi everyone. Has anyone managed to resolve this? I'm getting the same error even trying to set up the simplest getting started example.
Also, which would be the right version to user for 'react-data-grid-addons'? Thank you

**Comment by jhoneybee** [comment]
> Hi everyone. Has anyone managed to resolve this? I'm getting the same error even trying to set up the simplest getting started example.
> Also, which would be the right version to user for 'react-data-grid-addons'? Thank you

configure your webpack

```js
{
    include: [/react-data-grid/]
 },

```

**Comment by igoriok1994** [comment]
> > Hi everyone. Has anyone managed to resolve this? I'm getting the same error even trying to set up the simplest getting started example.
> > Also, which would be the right version to user for 'react-data-grid-addons'? Thank you
> 
> configure your webpack
> 
> ```js
> // babel-loader
> {
>     include: [/react-data-grid/]
>  },
> ```

Probably this will work only if you are using Babel 7. 
With Babel 6 error will be the same. I'll test it next week.

**Comment by diez-esteban** [comment]
Thank you @igoriok1994  , I appreciate your help!
About the addons, which version should work with react-data-grid?

**Comment by igoriok1994** [comment]
> About the addons, which version should work with react-data-grid?

I have no idea. In my project i'm using react-data-grid 4 with same version addons (for old modules).
For new modules I've created custom wrapper with react-data-grid 7 canary16 (npm alias) without addons. For all custom features you can create your own formatters/editor (so did I)

**Comment by diez-esteban** [comment]
Hi everyone. I'm a newbie in react. Created my app using create-react-app. Can anyone give me a hand and walk me through the process of setting up webpack?

Also tried downgrading to react-data-grid v5.0.1 and got the same error as I did with the latest version.

Any help will be appreciated. Thank you.

Full error trace:

```
/Users/xxx/node_modules/react-data-grid/lib/DataGrid.js 102:37
Module parse failed: Unexpected token (102:37)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   const totalHeaderHeight = headerRowHeight + (enableFilters ? headerFiltersHeight : 0);
|   const clientHeight = height - 2 // border width
>   - totalHeaderHeight - (summaryRows?.length ?? 0) * rowHeight - (totalColumnWidth > viewportWidth ? getScrollbarSize() : 0);
|   const [rowOverscanStartIdx, rowOverscanEndIdx] = getVerticalRangeToRender(clientHeight, rowHeight, scrollTop, rows.length);
|   /**
```

**Comment by igoriok1994** [comment]
> Also tried downgrading to react-data-grid v5.0.1 and got the same error as I did with the latest version.

Just remove react-data-grid, delete node_modules, then install install it again (v7 canary 16 or v5 or v6)
Then do npm install

**Comment by diez-esteban** [comment]
Hi @igoriok1994 , thanks. I Followed these steps:

- Uninstalled react-data-grid by running npm uninstall react-data-grid --save
- Checked react-data-grid is not on node_modules: OK
- Installed version 6.10 --> npm install react-data-grid@6.1.0
- Run my app and got the same error

```
/Users/xxx/node_modules/react-data-grid/lib/DataGrid.js 102:37
Module parse failed: Unexpected token (102:37)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   const totalHeaderHeight = headerRowHeight + (enableFilters ? headerFiltersHeight : 0);
|   const clientHeight = height - 2 // border width
>   - totalHeaderHeight - (summaryRows?.length ?? 0) * rowHeight - (totalColumnWidth > viewportWidth ? getScrollbarSize() : 0);
|   const [rowOverscanStartIdx, rowOverscanEndIdx] = getVerticalRangeToRender(clientHeight, rowHeight, scrollTop, rows.length);
|   /**

```
This how my package.json file looks now.
```
{
  "name": "ordssl",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "axios": "^0.19.2",
    "bootstrap": "^4.5.0",
    "formik": "^2.1.4",
    "local-storage-fallback": "^4.1.1",
    "moment": "^2.27.0",
    "react": "^16.13.1",
    "react-bootstrap": "^1.0.1",
    "react-data-grid": "^6.1.0",
    "react-dom": "^16.13.1",
    "react-redux": "^7.2.0",
    "react-router-dom": "^5.2.0",
    "react-scripts": "3.4.1",
    "react-select": "^3.1.0",
    "redux-saga": "^1.1.3",
    "reselect": "^4.0.0",
    "rsuite": "^4.7.5",
    "yup": "^0.29.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {}
}

```

**Comment by workatease** [comment]
Hi guys,
I was able to solve this issue by configuration my webpack to include the react-data-grid as mentioned in [README.md](https://github.com/adazzle/react-data-grid/blob/canary/README.md)  in Webpack configuration with babel-loader

**Comment by igoriok1994** [comment]
> Hi guys,
> I was able to solve this issue by configuration my webpack to include the react-data-grid as mentioned in [README.md](https://github.com/adazzle/react-data-grid/blob/canary/README.md) in Webpack configuration with babel-loader

It works only with Babel 7.

**Comment by kkokiev** [comment]
I have the same issue, i'm using create-react-app with the typescript template.
I will be grateful for advice on how to fix it.

**Comment by langebangen** [comment]
Seems to a issue in 7.0.0-canary.16 and forward. Installing react-data-grid@7.0.0-canary.15 solves this issue for me, so I guess I will stay at this version until the issue is solved

**Comment by GuyPaddock** [comment]
Also see: https://github.com/adazzle/react-data-grid/issues/2091#issuecomment-693166142

**Comment by HeavenlyEntity** [comment]
> Seems to be an issue in 7.0.0-canary.16 and forward. Installing react-data-grid@7.0.0-canary.15 solves this issue for me, so I guess I will stay at this version until the issue is solved

Yes this will fix the issue. Can a contributer please revert the commit updating the ES compliance that is too new for even the react apps to even use this. As you guys are getting a lot more user base due to mui-datatables breaking styles.

**Comment by amanmahajan7** [comment]
We published a new bundle to address this issue. Please let us know if it is still not working for anyone

**Comment by ishtiak-ahmed** [comment]
If your project is running in old nodejs version, installing older version react-data-grid might work. It worked for me.

**Comment by Metodija92** [comment]
Hi @amanmahajan7, I am still having issues with RDG 7.0.0-beta.19

ERROR in ../ut-react-common/node_modules/react-data-grid/lib/bundle.js 61:16
Module parse failed: Unexpected token (61:16)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   useLayoutEffect(() => {
|     if (!isSelected) return;
>     ref.current?.focus({
|       preventScroll: true
|     });
 @ ../ut-react-common/dist/ut-react-common.esm.js 1:1793-1855 219:27254-27267 219:27374-27378 219:27392-27397
 @ ./client/app/utils/getDailyReachAvg.js
 @ ./client/app/utils/index.js
 @ ./client/app/main.js
 @ multi webpack-hot-middleware/client ./client/app/main.js
