### ISSUE TITLE
How to make grid responsive?

### ISSUE THREAD

**Issue by Shubham-DK** [adazzle/react-data-grid#2079]
How to make grid responsive so that it occupies the space based on the screen size, and all it contents, font size automatically fits in.

Is there any props for that?

**Comment by qili26** [comment]
Check this out.

https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/CommonFeatures.tsx#L275

**Comment by amanmahajan7** [comment]
I think Autosizer would work as recommended earlier
