### ISSUE TITLE
Selection mask stays over frozen columns

### ISSUE THREAD

**Issue by maniyalraj** [adazzle/react-data-grid#2085]
![image](https://user-images.githubusercontent.com/19779810/87642487-39975780-c767-11ea-8ca9-0deb196cee10.png)

Steps to re-produce:
1. Freeze initial 2 columns.
2. Select a cell from 3rd+ column
3. Scroll to right so that the selected cell will go past frozen column

The selected cell mask stays over frozen column cell.

How to make it go under the frozen cell. 

Tried z-index it didn't work

**Comment by amanmahajan7** [comment]
This is fixed in the latest version of canary
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
