### ISSUE TITLE
bug:  when the scroll bar appears, the position of the edit box is displayed incorrectly.

### ISSUE THREAD

**Issue by jhoneybee** [adazzle/react-data-grid#2087]
## Environment

- Window 10 
- Google Chrome  84.0.4147.89 (latest version)

## GIF

![BUG](https://user-images.githubusercontent.com/24241052/87738394-d7def800-c80f-11ea-9e25-cfffc0da103d.gif)

## Steps

1. run cmd
```
git clone https://github.com/adazzle/react-data-grid.git
yarn 
yarn start
```
> git commit is `f5c1000abfe83f27263cf14562ac59729fe1d876`

2. editor source code `file: react-data-grid\stories\demos\AllFeatures.tsx` , insert code   `<div style={{ paddingTop: 2000}}/>`
in 227 line

- https://github.com/adazzle/react-data-grid/pull/2061

**Comment by amanmahajan7** [comment]
Thank you for the bug report. It has been fixed
