### ISSUE TITLE
Feature: Multi column sorting

### ISSUE THREAD

**Issue by noel123007** [adazzle/react-data-grid#2088]
Would love to see multi column sorting feature.

**Comment by jhoneybee** [comment]
see https://github.com/adazzle/react-data-grid/pull/2062

**Comment by noel123007** [comment]
@jhoneybee thanks for the responses. I've looked in to the issue you referenced. But what I noticed is the code seems to tell how the sortDirection props has to be sent for multi column sorting. But is the internal logic for multi column sorting has been implemented? 

And I am not able get the example running referenced in the issue #2062. Can you please confirm if this feature is released and in which version?

**Comment by jhoneybee** [comment]
```sh
// lock version  "react-data-grid-temp": "7.0.0-canary.17.5",
npm install react-data-grid-temp
```

```jsx
const sort = (newSortDirection) => {
     // set sort row
     setRows(.....)
}

<DataGrid
        columns={columns}
        sortDirection={sortDirection}
        onSort={(columnKey, direction) => {
          const newSortDirection = [];
          let existence = false;
          sortDirection.forEach(ele => {
            if (ele.columnKey === columnKey) {
              existence = true;
              newSortDirection.push({
                sortDirection: direction,
                columnKey
              });
            } else {
              newSortDirection.push({
                sortDirection: ele.sortDirection,
                columnKey: ele.columnKey
              });
            }
          });
          if (!existence) {
            newSortDirection.push({
              sortDirection: direction,
              columnKey
            });
          }
          setSortDirection(newSortDirection);
          sort(newSortDirection)
        }}
        rows={rows}
      />
```

It is just a sort status mark, and the sorting logic needs to be implemented by itself.

You can see an example of this place .

demo https://rwpjs.vercel.app/components/base/table
code https://github.com/jhoneybee/rwpjs/blob/master/packages/react-ui/src/table/index.tsx#L358-L388


> I'm very sorry, my mother tongue is not English, this is machine translation
