### ISSUE TITLE
Unable to open drop down editor for cells on last row when table is scrolled all the way

### ISSUE THREAD

**Issue by zillemarco** [adazzle/react-data-grid#2090]
As the title suggest, when a table is scrolled to the last row and I try to edit a cell which has a drop down editor attached to it, the drop down gets closed right away canceling the edit.

I tracked it down begin the following check of `scrollTop` due to the auto sizer chaning the size and thus the scroll of the table.
https://github.com/adazzle/react-data-grid/blob/a2f8ff38236ba3ed3517f644b2c40f3ba0244ea5/src/editors/EditorContainer.tsx#L58

The issue can be reproduced directly on the demos, for example by disabling incremental rows loading on scroll of `AllFeatures.tsx` and disabling the row click that opens the drop down right away.

**Comment by zillemarco** [comment]
It seems the problem is not entirely due to the auto sizer, in fact it occurs when `enableCellDragAndDrop` is set.
`enableCellDragAndDrop` adds the little square on the bottom right corner of the cell that gets hidden when entering "edit mode" which triggets the scroll and the edit gets canceled,

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.
