### ISSUE TITLE
Table Outlines not showing and all data in one cell

### ISSUE THREAD

**Issue by dakshsaraf** [adazzle/react-data-grid#2092]
I ran the code for CommonFetures.tsx in the story book, in my own project and table that is being outputted is without borders. It also seems like all the columns are displaying in one cell.

![Screenshot from 2020-07-18 15-54-48](https://user-images.githubusercontent.com/25619616/87850629-65edd800-c90f-11ea-8f07-c294f70d6a01.png)

A preview of this is attached above

**Comment by amanmahajan7** [comment]
Please make sure css file is included
https://github.com/adazzle/react-data-grid#usage

**Comment by dakshsaraf** [comment]
Thank you, if I include the css file. The AutoSizer stops working
It sets the height to 0px. What could be the reason for this?
