### ISSUE TITLE
[question] How does the v6 version implement head scrolling 

### ISSUE THREAD

**Issue by HSunboy** [adazzle/react-data-grid#2095]
I am very confused.
Why the header can scroll when the parent element is set to visible: hidden

![image](https://user-images.githubusercontent.com/14886044/88019094-8dd17b80-cb5b-11ea-8e8e-202a6cfa3537.png)

**Comment by amanmahajan7** [comment]
v6 is no longer supported. You can check the master branch for further details
https://github.com/adazzle/react-data-grid/tree/master/packages/react-data-grid
