### ISSUE TITLE
Cell-Drag to Fill horizontally across rows

### ISSUE THREAD

**Issue by L-U-C-K-Y** [adazzle/react-data-grid#2098]
Hi all

Great project!

Currently, cell-drag down/up to fill is supported within a column.

What would it take to enable  cell-drag left/right to fill across rows, dragging them horizontally?
Is there a starting point where I could look into? I was not able to find anything in the repo related to this.

Thanks

**Comment by amanmahajan7** [comment]
Duplicate issue https://github.com/adazzle/react-data-grid/issues/1930
