### ISSUE TITLE
v7 Initial filter does not work with Numeric filter

### ISSUE THREAD

**Issue by JanBN** [adazzle/react-data-grid#2099]
Hello how to make initial filters when filtering logic is in filter like in NumericFilter ?
I would like to set up filter like this:
```
 const [filters, setFilters] = useState<Filters>({
    complete: '15'
  });
```

but it fails here:
```
 const filteredRows = useMemo(() => {
    return rows.filter(r => {

      return (
        ...
        && (filters.complete ? filters.complete.filterValues(r, filters.complete, 'complete') : true)   <---------
      );
    });
  }, [rows, filters]);
```

```
TypeError: filters.complete.filterValues is not a function
```

all the code is from your storybook from HeaderFilters.tsx

What is the correct way of adding initial filters when logic is in the filter component ?

**Comment by amanmahajan7** [comment]
`NumericFilter` uses the old api and it is not compatible with v7 canary. We recommend copying the code over and modify as needed

Also check https://github.com/adazzle/react-data-grid/issues/2150#issuecomment-696662737
