### ISSUE TITLE
Babel 6 support for 7.0.0-canary.17

### ISSUE THREAD

**Issue by maniyalraj** [adazzle/react-data-grid#2100]
The current 7.0.0-canary.17 requires ES2020.

Migrating to ES2020 maybe not feasible for large legacy projects.

Just wanted to know if there is any workaround to use 7.0.0-canary.17 with older react projects?

**Comment by axmccx** [comment]
I'm also having this issue. Current workaround is to stay put at 7.0.0-canary.16.

**Comment by maniyalraj** [comment]
Canary.16 is a great release and would have not thought of upgrading it to 17.

But, there's a strange selection mask bug which is fixed in 17.

Hope to find a workaround for the bug or a Babel6 support for 17 soon.

**Comment by igoriok1994** [comment]
Any news?

**Comment by maniyalraj** [comment]
No progress from my end. As of now staying put on 16. 

@amanmahajan7 might be able to help.

**Comment by igoriok1994** [comment]
> No progress from my end. As of now staying put on 16.

Eah... Babel 6 compatibility is important. 

I've tryed to clone this repo and build with ES2015 target but got error from YARN.

**Comment by igoriok1994** [comment]
**Any answers from React-data-grid developers?**

**Comment by igoriok1994** [comment]
Bwt, compiled as fork of canary.20 as ES2015

```
npm install react-data-grid-igvi
```

**Comment by kimim** [comment]
I'm using react-data-grid from clojurescript. after canary.16, everything breaks.

**Comment by zveljkovic** [comment]
This is my new phrase for difference between being smart and wise. Smart knows that we need to move to es2020 but wise person delays the move until Create React App allows babel config editing.

**Comment by amanmahajan7** [comment]
Is this still an issue? Please check the installation guide 
https://github.com/adazzle/react-data-grid#install
