### ISSUE TITLE
Large space between header and rows.

### ISSUE THREAD

**Issue by ryan-rushton** [adazzle/react-data-grid#2103]
Upon upgrading from canary.16 to canary.17 I am seeing a large gap between the header and the first row. It appears that the following div element is creating that gap,

```
<div style={{ height: Math.max(rows.length * rowHeight, clientHeight) }} />
```

https://github.com/adazzle/react-data-grid/blob/canary/src/DataGrid.tsx#L748

**Comment by amanmahajan7** [comment]
All the examples seem to work fine. Can you create an example?
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features

**Comment by ryan-rushton** [comment]
I will try and get something up in the next few days.

**Comment by amanmahajan7** [comment]
Closing as there is no response. Feel free to create a new issue if you this issue still exists

**Comment by ryan-rushton** [comment]
Yeah sorry about that, I have been a bit busy. If I ever get around to updating again and it's still broken I will sort something out.
