### ISSUE TITLE
On every column click if we want to filter particular columns, then how we can achieve it with react-data-grid

### ISSUE THREAD

**Issue by Ashwini-Kadam** [adazzle/react-data-grid#2105]
want something like tooltip or dropdown on click of column to filter that particular column. please suggest a solution.

**Comment by Ashwini-Kadam** [comment]
@amanmahajan7 @nstepien please suggest solution for this one.

**Comment by maniyalraj** [comment]
Hey @Ashwini-Kadam ,

Did you check out https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features.

**Comment by amanmahajan7** [comment]
You should be able to create a custom `headerRenderer` with dropdown to filter values. Here is an example 
https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/ColumnsReordering.tsx#L75
