### ISSUE TITLE
Scroll Bar vibrating when setting a margin (top, bottom) to the row

### ISSUE THREAD

**Issue by FatehAK** [adazzle/react-data-grid#2107]
When setting margin (top, bottom) for each row which results in the scroll bar vibrating when there are a large number of rows. It is probably row  height computation issue which doesn't consider the margins applied. Any help with this would be great. Thanks in advance.

**Comment by amanmahajan7** [comment]
Setting margin or using `RowRenderer` is not supported as we need the dimensions for the windowing logic. I would recommend using `rowHeight` prop (if that helps) or changing the row renderer for alternate rows
