### ISSUE TITLE
Unmount cell editor outside viewport

### ISSUE THREAD

**Issue by AlexK89** [adazzle/react-data-grid#2109]
Is it a native behaviour for RDG or it can be fixed somehow? 

When I'm editing a cell and then scroll to lose it from viewport, editor component will be unmounted. I believe this is performance optimisation. Us there a way to keep it mounted so I can scroll back and continue to edit?

**Comment by amanmahajan7** [comment]
This is the default behavior but it will be fixed in the next editor2 API
https://github.com/adazzle/react-data-grid/pull/2102/files#diff-41df78d86ed4de80aae9b0b9560feb2bR52

**Comment by amanmahajan7** [comment]
You can use editor2 now
https://github.com/adazzle/react-data-grid/pull/2102
