### ISSUE TITLE
Locked (frozen) columns move with track pad hz scroll

### ISSUE THREAD

**Issue by littlebee** [adazzle/react-data-grid#211]
see screen cap.  

This only happens when using the Mac touch pad to scroll horizontally.  When I use the horizontal scroll bar it doesn't do this.

I've tried stripping off my css and it also happens with the react-data-grid.css from the themes folder.  I don't see that behavior in the frozen columns example.  

![scrollusingtouchpad](https://cloud.githubusercontent.com/assets/593784/13028781/f5b032cc-d22d-11e5-88de-bd32dbc76ab0.gif)

**Comment by masterfung** [comment]
I see the same issue on my end, running on react 15.2.1

**Comment by keshavkaul** [comment]
Any updates on this?

**Comment by singharpit94** [comment]
I am also facing the same issue. Any update on this or suggestions how it can be fixed?

**Comment by mikol-styra** [comment]
I am seeing the same behavior.

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

React: 16.0.0
React Data Grid: 2.0.60

The frozen cells are styled with `position: "absolute"` and their left offset relative to their parent (the grid canvas) is set (using `transform: translate3d(...)`) on every scroll event. Using `position: "fixed"` and dropping the `transform` does the trick when scrolling horizontally – even when the cell style is updated on every scroll event.

_However_, scrolling vertically does not interact well with `position: "fixed"` cells so it’s not a sufficient fix. And I haven’t dug deeper than that.

**Comment by singharpit94** [comment]
Hi,
Thanks for the response ,I will look into it.

**Comment by rtman** [comment]
@singharpit94 @malonecj 

I still see this issue in the frozen column example and its a pretty big issue imo when it comes to UX. What can be done to fix this?

**Comment by rtman** [comment]
Can anybody speak to this?
