### ISSUE TITLE
Unable to implement row selection (7.0.0 canary 0.20)

### ISSUE THREAD

**Issue by joshenlim** [adazzle/react-data-grid#2122]
Really not sure if I'm missing something, but I've added the `selectedRows` and `onSelectedRowsChange` props but the checkboxes aren't showing up? I'm trying it with the 7.0.0 canary 0.20 with the codesandbox URL below.

https://codesandbox.io/s/adoring-cori-k3418?file=/src/App.js

I was referring to the Storybook references when building this ^ (https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/CommonFeatures.tsx)

**Comment by amanmahajan7** [comment]
You need to import the `SelectColumn`. Here is the updated example
https://codesandbox.io/s/hungry-maxwell-hlf1h?file=/src/App.js

Also check the examples
https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/CommonFeatures.tsx#L48

**Comment by joshenlim** [comment]
Awesome, thank you so much for the quick reply! Really appreciate it 👍
