### ISSUE TITLE
Programatically Adding Columns Require Window Resize to Render

### ISSUE THREAD

**Issue by qruzz** [adazzle/react-data-grid#2123]
## What is the problem

I am trying to programatically add columns to a table. In short terms, I am holding the columns in a state, and using that state as the `columns` property in the `DataGrid`. When a button is clicked, I add an empty column to the state, which should now rerender that part of the table.

This works, in part. When I add one column, it works by rendering as expected. However, if I try to add another column after, the overall table wrapper rerenderes, however the column is not actually added. (see the [Context](#context) section for a visual explaination of this.

Here is a minimized version of the code that I am using:

```tsx
const defaultColumns = [
  { key: '0', name: '', width: 5 },
  { key: '1', name: 'Column 1', width: 160, editable: true },
];

function App() {
  const [rows, setRows] = React.useState(defaultRows);
  const [columns, setColumns] = React.useState(defaultColumns);

  // This is the function that handles adding the column to the state
  const handleAddColumn = React.useCallback(() => {

    // It takes the columns currently in state and adds a new empty one
    const newColumns = [
      ...columns,
      {
        key: `${columns.length}`,
        name: `Column ${columns.length}`,
        width: 160,
        editable: true,
      },
    ];

    // Setting the new columns in state
    setColumns(newColumns);
  }, [columns]);

  return (
    <Flex sx={{ width: '100vw' }}>
      <div className="App">
        <DataGrid
          columns={columns}
          rows={rows}
        />
      </div>
      <Flex
        sx={{
          height: 35,
          width: 100,
          justifyContent: 'center',
          border: '1px solid #ddd',
        }}
      >
        <Button
          variant="ghost"
          sx={{ width: '100%' }}
          onClick={handleAddColumn}
        >
          +
        </Button>
      </Flex>
    </Flex>
  );
}
```

Any pointers or ideas on how to solve this would be hightly appreciated, as I am a little perplexed by it so far. Thank you in advance!

## Versions

Package Versions:
- `react-data-grid` : `7.0.0-canary.15`
- `react` : `16.13.1` *(includes `react-dom`)*

Browsers:
- Firefox Developer Edition 80.0b8 *(latest)*
- Google Chrome 84.0.4147.135 (Official Build) (64-bit) *(latest)*

## Context

Here is a sequence of events to help illustrate what it is I am trying to say:

Initial state of the application - we have an a single column with a + button next to it, which adds a new column to the state.
<img width="824" alt="image" src="https://user-images.githubusercontent.com/2365111/90761285-15391880-e2db-11ea-9730-4eca62b7ad47.png">

When the button is clicked the first time, a new column appears as we would expect.

<img width="824" alt="image" src="https://user-images.githubusercontent.com/2365111/90761530-7365fb80-e2db-11ea-99a8-24b2f12f0cd7.png">

However, if we were to click the + button again (any number of times), the overall table wrapper does resize as if the columns were added, however the clumns are not rendered, as can be seen below

<img width="824" alt="image" src="https://user-images.githubusercontent.com/2365111/90761210-fcc8fe00-e2da-11ea-8369-bc5c1735d4c2.png">

Once you resize the browser window (even just a pixel), the columns appear

<img width="824" alt="image" src="https://user-images.githubusercontent.com/2365111/90761679-aa3c1180-e2db-11ea-83a5-e2fe7bd97a69.png">

**Comment by amanmahajan7** [comment]
Thank you reporting the issue. We made some changes to how grid calculates the available width. Can you try `7.0.0-canary.21` and check if the issues still exists. Thanks

**Comment by adnaanbheda** [comment]
@qruzz Hey did you find a solution to this ?

Also, I'm trying your code and whenever I click on the add button, the height of the button grows infinitely (?), no idea why.

**Comment by amanmahajan7** [comment]
Closing due to lack of response. Feel free to open a new issue if it still exists
