### ISSUE TITLE
Window should scroll with cell focus

### ISSUE THREAD

**Issue by avalanche1** [adazzle/react-data-grid#2124]
Say, I have a long vertical table that occupies several screens.
When I get to the bottom cell of current screen and press Down - I expect window to scroll down one row height. Exactly like Excel does it.
In `^7.0.0-canary.20` it dont work that way. Cell focus simply goes beyond the screen.

**Comment by amanmahajan7** [comment]
The grid is not designed to handle focus like you mentioned. For this particular case, I would recommend handling `onScoll` event and manfully adjusting the window scroll position.

**Comment by avalanche1** [comment]
That's very sad.
