### ISSUE TITLE
DropDownEditor items

### ISSUE THREAD

**Issue by ahazut** [adazzle/react-data-grid#213]
How to reload the DropDownEditor items?
Thanks.

**Comment by jpdriver** [comment]
hey @ahazut -- do you mean you want to add / remove options after rendering a grid?

**Comment by ahazut** [comment]
I need to have a key and a value for the DropDownEditor to be the same as the AutoComplete on the sample.
Thanks again

**Comment by txm** [comment]
https://github.com/adazzle/react-data-grid/pull/208

On 16 February 2016 at 10:51, ahazut <notifications@github.com> wrote:

> I need to have a key and a value for the DropDownEditor to be the same as
> the AutoComplete on the sample.
> Thanks again
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adazzle/react-data-grid/issues/213#issuecomment-184624428>
> .
>



-- 
Andrew McGregor
07940 22 33 11

**Comment by ahazut** [comment]
Hello txm,
I was trying to do it with 'options' like the sample you provided but with no luck..

this.props.categories.forEach((c) => categoryTypes.push(<option key={c.id} value={c.name}>{c.name}</option>));
DropDownEditor = ReactDataGrid.Editors.DropDownEditor;
CategoryEditor = <DropDownEditor options={categoryTypes}/>

Thanks again.

**Comment by txm** [comment]
Did you apply the patch?

https://github.com/adazzle/react-data-grid/pull/208/files

On 16 February 2016 at 11:09, ahazut <notifications@github.com> wrote:

> Hello txm,
> I was trying to do it with 'options' like the sample you provided but with
> no luck..
>
> this.props.categories.forEach((c) => categoryTypes.push({c.name}));
> DropDownEditor = ReactDataGrid.Editors.DropDownEditor;
> CategoryEditor =
>
> Thanks again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adazzle/react-data-grid/issues/213#issuecomment-184632900>
> .
>



-- 
Andrew McGregor
07940 22 33 11

**Comment by ahazut** [comment]
No I didn't. Can you please show me where I should add it?

**Comment by txm** [comment]
Maybe just persuade @adazzle to accept the PR ;)

On 16 February 2016 at 12:44, ahazut <notifications@github.com> wrote:

> No I didn't. Can you please show me where I should add it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adazzle/react-data-grid/issues/213#issuecomment-184667523>
> .
>



-- 
Andrew McGregor
07940 22 33 11

**Comment by malonecj** [comment]
Has been implemented in https://github.com/adazzle/react-data-grid/pull/214

**Comment by txm** [comment]
Bah, when I made this PR I foolishly thought the Grid was a form.

When you edit the Cell you get the ID, but calling rowGetter() gets the row Values no the row ID's.

It looks like a reasonable task to me to change rowGetter() and the underlying data structure to return ID's (if they exist).

Should I be looking for a different method to get ID's from the DropDown?
