### ISSUE TITLE
Changelog changes

### ISSUE THREAD

**Issue by Javo-blip** [adazzle/react-data-grid#2133]
Can the changelog have better versioning!

It seems to be with every canary release, the changelog itself is getting modified directly. This is very confusing for seeing the changes between different canary releases and seems to be more of a migration guide rather than a changelog.

Sorry for the critical comment, but other than that great library! Keen to see it continue to evolve!

**Comment by joshenlim** [comment]
I second this too, it'd be really helpful if the changes were outlined under each version header like 7.0.x as you guys did in the past versions before 6.0.0
