### ISSUE TITLE
context menu for Table header

### ISSUE THREAD

**Issue by MCyan01** [adazzle/react-data-grid#2134]
Are we supporting context menu for the table headers?
Could you please assist on this?
@malonecj 
@nstepien 
@amanmahajan7 
@tenpaiyomi 
@azu 
@txm 
@omarish

**Comment by d4rkm3z** [comment]
You'll can implement header's context menu via wrapping your `HeaderComponent` to `ContextMenuTrigger` and usage `ContextMenu` from `react-contextmenu` package.

**Comment by igoriok1994** [comment]
You can do it by yourself. Just create custom header renderer and pass it to columns configuration.

**Comment by amanmahajan7** [comment]
Like mentioned above, you can use a custom `headerRenderer` to add a context menu. Here is an example of using custom `headerRenderer`
https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/ColumnsReordering.tsx#L75

**Comment by addijhaq** [comment]
@d4rkm3z @amanmahajan7 can you please elaborate a little more with a code snippet on how to achieve wrapping the `ContextMenuTrigger` and  `ContextMenu` and then passing this into the headerRenderer?
