### ISSUE TITLE
how to remove scroll bar 

### ISSUE THREAD

**Issue by Shubham-DK** [adazzle/react-data-grid#2145]
Hi 

Our requirement is to construct small tables with fixed no. of rows to show data.
Since the no of rows is fixed , we no longer need scroll bar.

I have hidden the scroll bar by overriding the CSS, but it is resulting in empty space. which is not looking good.

Is there any props or methods by which we can remove the scroll bar and give its width to the columns

![image](https://user-images.githubusercontent.com/58040775/92204849-0d17d600-eea2-11ea-8f7d-958d1fe02ce6.png)

**Comment by kimim** [comment]
You can specify the css style with 
```css
.rdg
{
overflow-y: hidden;
}
```

**Comment by Shubham-DK** [comment]
@kimim  I tried but its still not getting removed.

https://codesandbox.io/s/rdg-cell-editing-forked-90duf

Can you check the code and let me know where exactly I am going wrong.

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.
