### ISSUE TITLE
AutoComplete render after mouse hover

### ISSUE THREAD

**Issue by ahazut** [adazzle/react-data-grid#215]
When I update the items in the AutoComplete editor I see the changes just when I hover them with the mouse. Does anyone know why?
Thanks.

**Comment by diogofcunha** [comment]
The only thing that comes to my mind for this one is that you can have a `shouldComponentUpdate` returning `false` in you implementation or you are making some kind of hack to get the editor value that is not allowing react-data-grid to figure out that it needs to re-render,
