### ISSUE TITLE
NumericFilter on Advanced Filtering is not working correctly

### ISSUE THREAD

**Issue by fazamutash** [adazzle/react-data-grid#2150]
If I try to search `<3`, it will include the 3 as well which is a bit confusing because it's not `<=3`
See the example on the official doc below:
![image](https://user-images.githubusercontent.com/23185628/92854347-262d0380-f41b-11ea-900d-8da7fe6f630d.png)

**Comment by igoriok1994** [comment]
You can create your own column filter with your custom logic. Use `filterRenderer` key inside column configuration.

**Comment by amanmahajan7** [comment]
As mentioned above you can use a custom filter to archive the desired result. We will also remove `react-data-grid-addons` package in the next major release.

Here is an example with v7 canary
https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/HeaderFilters.tsx
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--header-filters
