### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by cleandevcode** [adazzle/react-data-grid#2157]
Now I am using the latest version of react-data-grid.
Then I see this error.
This is my package.json.
```
{
...
"react-data-grid": "^7.0.0-canary.22",
"react": "^16.13.1",
"react-dom": "^16.13.1",
...
}
```
![error](https://user-images.githubusercontent.com/52365167/93355360-a651cf80-f846-11ea-9420-6ba140f889d1.png)

Please help me.
Thanks.

**Comment by cleandevcode** [comment]
I downgraded the version of `react-data-grid` to `"react-data-grid": "^6.1.0",` and working well without error.
Seems like there is a problem with the new version.
So now I am closing this issue here.

**Comment by olliiiver** [comment]
I had the same issue I've figured out that the new version just works fine. However, old examples or old properties do not work anymore. Also old type packages like @types/react-data-grid need to be removed.

**Comment by BorodinDK** [comment]
I had the same problem. Install `"react-data-grid": "^6.1.0"` work for me.
