### ISSUE TITLE
custom row renderer causes visual flagging during scroll and significantly interferes with scroll progress

### ISSUE THREAD

**Issue by gearye** [adazzle/react-data-grid#2159]
Fond using recent Chrome for Mac: Version 85.0.4183.102 (Official Build) (64-bit)

The sample code linked from the docs has this issue:
https://codesandbox.io/s/o9qo7zwjxq?from-embed=&file=/src/index.js

Repro: Scroll down slowly and the top row starts flagging as it scrolls off. Continue to scroll and it gets worse and starts to impede the scrolling, rows bounce back down instead of scrolling off.

Video of issue:
[customRowRenderer.mov.zip](https://github.com/adazzle/react-data-grid/files/5266045/customRowRenderer.mov.zip)

**Comment by amanmahajan7** [comment]
v5 is not longer supported. Please try with v7 canary

**Comment by amanmahajan7** [comment]
Closing due to lack of response. Please create a new issue if you are still facing the problem
