### ISSUE TITLE
Is pagination supported?

### ISSUE THREAD

**Issue by rahul1059** [adazzle/react-data-grid#216]
Is there any way to implement pagination with this component.

**Comment by jpdriver** [comment]
hey @rahul1059 -- we don't support pagination right now but plan to in future. more info here https://github.com/adazzle/react-data-grid/issues/152

**Comment by slackday** [comment]
For anyone looking to implement pagination I can recommend https://www.npmjs.com/package/react-paginate

It was really easy to implement together with ReactDataGrid by handling current page and what items to view in component state.

Obviously a little more effort has to be but in if you also want to support sorting but I havn't come across anything that can't be solved with a little tweaking.

Worth noting might be I'm currently not familiar with all features and components of react-data-grid so there might be something that doesn't work together with react-paginate.

**Comment by KalpanaPagariya** [comment]
When is the plan to support pagination?

**Comment by kontactsagar** [comment]
Hi...I have used Reactdatagrid in my code however want to implement pagination for the same..could you please help me with that as i am unable to achieve this. Thanks

**Comment by jstray** [comment]
I implemented this in getRow here: https://github.com/adazzle/react-data-grid/issues/152#issuecomment-336747776

**Comment by Niyass** [comment]
Hi ! When is the plan to support pagination?

**Comment by jitenderchand1** [comment]
Any news on pagination?

**Comment by artista7** [comment]
nope, no news

**Comment by artista7** [comment]
from 2016 to 2019, no pagination implementation could be put forward

**Comment by jeffsupancic** [comment]
Any news on pagination?

**Comment by s-kris** [comment]
Pagination support would be very helpful.

**Comment by xXGoziXx** [comment]
bump

**Comment by nguyenvannghi** [comment]
2020, pagination please!

**Comment by Rohit0510** [comment]
I have used React Data grid but for now I want to implement pagination in the same.
I am unable to achieve the same 
Could you please share the suggestions to implement it.
Thanks in advance for your help.

**Comment by KhadeerUI** [comment]
Is it any update on client-side pagination for react-data-grid?

**Comment by osmancakir** [comment]
> 
> 
> 2020, pagination please!

2021, pagination please!

**Comment by JafarSynergie** [comment]
28-06-2021 Pagination please.....!
