### ISSUE TITLE
Column editor2 does not save input when Enter is hit or clicked outside of cell

### ISSUE THREAD

**Issue by joshenlim** [adazzle/react-data-grid#2163]
Hey there, I'm using the version 7.0.0-canary.22 and am referencing [this example](https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/CommonFeatures.tsx) to create a cell text editor via the editor2 key as [such](https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/components/Editors/TextEditor.tsx).

Upon hitting enter or clicking outside of the cell, it doesn't call onRowsUpdate, as how the default text cell editor does if no editor is specified in the column config - wondering if this might be a bug.

**Comment by amanmahajan7** [comment]
`editor2` calls `onRowsChange` instead of `onRowsUpdate`. `onRowsUpdate` will be removed in the future
https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/CommonFeatures.tsx#L281

**Comment by joshenlim** [comment]
Gotcha on this thanks so much!
