### ISSUE TITLE
Table height continuously growing

### ISSUE THREAD

**Issue by kimim** [adazzle/react-data-grid#2165]
There is one div, whose height is continuously growing. This cause the table cells disappear. 
This error is happen after 7.0.0.canary.17.
Version 7.0.0.canary.16 is fine.
<img width="512" alt="table-error" src="https://user-images.githubusercontent.com/5523431/94758094-d2d12400-03ce-11eb-8732-a2dcb6fde7b3.PNG">

**Comment by kimim** [comment]
https://github.com/adazzle/react-data-grid/blob/eb8bb1ec40238d10d18193b1f0ada7c4cc902414/src/DataGrid.tsx#L948
This line causes the height style continuously growing, so the content of the table is pushed to the end.

**Comment by amanmahajan7** [comment]
The examples seem to work fine. Can you create a codesandbox example?
https://adazzle.github.io/react-data-grid/canary/

**Comment by kimim** [comment]
This is the example: http://40.73.112.202:3001
the code is here: https://github.com/kimim/cljs-react-data-grid
As you can find from the inspection, the height of one <div> is growing...
If I switch version to 7.0.0-canary.16. The data grid displays well.

**Comment by kimim** [comment]
The same code, with different react-data-grid versions:

7.0.0-canary.16: http://40.73.112.202:3002/
7.0.0-canary.22: http://40.73.112.202:3002/

**Comment by amanmahajan7** [comment]
The [`height` prop](https://github.com/kimim/cljs-react-data-grid/blob/master/src/cljs/vorstellung/data_grid.cljs#L84) is not longer supported. You can use `style: { height }` to set the height now.

https://github.com/adazzle/react-data-grid/pull/2130
