### ISSUE TITLE
Importing react data grid addons not rending any component

### ISSUE THREAD

**Issue by avrpaduru** [adazzle/react-data-grid#2166]
I have tried to import the below css:

`import 'react-data-grid-addons/dist/react-data-grid-addons.css';`

Tried react-data-grid-addons as below:

```
import * as DataGridAddons from 'react-data-grid-addons';
const { DropDownEditor } = DataGridAddons.Editors;
const { DropDownFormatter } = DataGridAddons.Formatters;

const titles = ['Dr.', 'Mr.', 'Mrs.', 'Miss', 'Ms.'];

const columns = [
{
editor: <DropDownEditor options={titles} />,
formatter: DropDownFormatter
}
]

```

The issue is mainly with importing react-data-grid-addons. If I remove all the code and just keep the import statement, still react is not rendering anything (white screen).

If I remove the import statement, everything is getting rendered normally.

Versions that I am using:

```
"react": "^16.13.1",
"react-data-grid": "^7.0.0-canary.22",
"react-data-grid-addons": "^7.0.0-alpha.24",

```

What is the reason why importing react-data-grid-addons is causing rendering issue?

Somewhere I saw react-data-grid-addons is not supported for react version 16.* versions, not able to find the source again now.

I have the below errors:

```
client:135 ./node_modules/react-data-grid-addons/lib/draggable/DraggableHeaderCell.js 47:26-39
"export 'DragItemTypes' was not found in 'react-data-grid'
warnings @ client:135
eval @ socket.js:47
sock.onmessage @ SockJSClient.js:67
EventTarget.dispatchEvent @ sockjs.js:170
eval @ sockjs.js:888
SockJS._transportMessage @ sockjs.js:886
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2962
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/react-data-grid/lib/index.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

**Comment by amanmahajan7** [comment]
`react-data-grid-addons` is removed and no longer supported. We recommend copying the code over and modify it as needed
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md

**Comment by avrpaduru** [comment]
@amanmahajan7 
Do you mean instead of importing react-data-grid-addons and working on it, we should copy the code from react-data-grid-addons and modify it as needed?

I want to use DropDown and Draggable features from react-data-grid-addons.

**Comment by Randhir01** [comment]
Is it possible we can apply filter and other features without using react data grid addons?
