### ISSUE TITLE
Where are the canary docs?

### ISSUE THREAD

**Issue by kellyfreet** [adazzle/react-data-grid#2171]
There's great documentation for pre-canary releases [with react jsx examples](https://adazzle.github.io/react-data-grid/docs/quick-start), but migrating to canary is a huge headache because there doesn't seem to be any documentation that I'm aware of, [only these typescript examples](https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features) (I'd love to learn typescript, of course, but gotta prioritze). I'd love to be proven wrong!

**Comment by joshenlim** [comment]
Seems like V7 docs will only be out after the final version of V7 is released (no exact timeline)

https://github.com/adazzle/react-data-grid/issues/1957#issuecomment-596028903

**Comment by amanmahajan7** [comment]
Duplicate issue
