### ISSUE TITLE
Can we use the MIT license of adazzle/react-data-grid for commercial use?

### ISSUE THREAD

**Issue by avrpaduru** [adazzle/react-data-grid#2172]
I am not able to find any pricing of licenses. I can only find that adazze/react-data-grid has MIT license as mentioned here:
https://www.npmjs.com/package/react-data-grid

If we are going to deploy our app for commercial use which uses adazzle/react-data-grid, should we buy a license or will we be good with MIT license?

**Comment by devChedar** [comment]
You should read a bit about MIT licence. But the basic answer is yes it's free for commercial use. 

[https://opensource.org/licenses/mit-license.html](https://opensource.org/licenses/mit-license.html)

**Comment by avrpaduru** [comment]
> You should read a bit about MIT licence. But the basic answer is yes it's free for commercial use.
> 
> https://opensource.org/licenses/mit-license.html

Thanks
