### ISSUE TITLE
--row-width is not correctly calculated

### ISSUE THREAD

**Issue by kimim** [adazzle/react-data-grid#2173]
--row-width is about 13px larger, which makes the horizontal scrollbar appear.

**Comment by kimim** [comment]
Example:
http://40.73.112.202:3001

**Comment by amanmahajan7** [comment]
The above link is not working

**Comment by kimim** [comment]
sorry the server was restarted. Here is the new link: http://52.130.91.102:3001

**Comment by FPDK** [comment]
@kimim did you figure out a solution?

**Comment by FPDK** [comment]
The calculation of --row-width seems to cause an issue in Firefox (85.0b3 (64-bit)). It works fine in Chrome and Edge.

Chrome:
![image](https://user-images.githubusercontent.com/1729717/102688717-d10e4400-41f8-11eb-8713-4ac00432b27f.png)

Edge:
![image](https://user-images.githubusercontent.com/1729717/102688722-d79cbb80-41f8-11eb-86c9-c361707e425f.png)

Firefox:
![image](https://user-images.githubusercontent.com/1729717/102688735-e5ead780-41f8-11eb-98cf-bd41d3e00193.png)

**Comment by kimim** [comment]
Not yet. But thank you for the solution!
