### ISSUE TITLE
Header disappears when scrolling in Safari

### ISSUE THREAD

**Issue by kchupakhin** [adazzle/react-data-grid#2174]
Hello. I'm faced with a problem on Safari with the header while scrolling

Safari - v14
react - 16.13.1
react-data-grid - v7.0.0-canary.24

Steps to reproduce:
1) Open any [demo](https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--all-features) example in Safari
2) Scroll to the bottom

Expected results:
-everything works fine
Actual results:
-header disappears sometimes

![safari_header](https://user-images.githubusercontent.com/40485391/95856775-40803700-0d63-11eb-8436-d6ef690a302d.gif)

**Comment by amanmahajan7** [comment]
This seems like a bug in safari. We are using position sticky and it works fine in other browsers. I am closing this issue for now but we will accept PRs to improve this behavior
