### ISSUE TITLE
Column width not working properly

### ISSUE THREAD

**Issue by arditnurcaj** [adazzle/react-data-grid#2175]
Why column width cannot be set less than 80px, is there any workaround for this problem?

**Comment by Waqqars987** [comment]
I have the same issue. I did set the **minColumnWidth** to **40** hoping that after doing this it would allow me to set a particular column's width to **below 80**, but it does not work.

**Comment by arditnurcaj** [comment]
@amanmahajan7 https://codesandbox.io/s/friendly-shadow-l5it1?file=/src/DataTable.js look closely at line 23 I have set width 40 but if you inspect the id column it has still the width 80px.

**Comment by arditnurcaj** [comment]
@Waqqars987 I fixed it, basically what you need to set is width & maxWidth to properly define the width.

**Comment by baijifeilong** [comment]
You should overload the default `minWidth` property
