### ISSUE TITLE
Is multi cell selection supported in 7.0.0-canary.26?

### ISSUE THREAD

**Issue by omfgitsjack** [adazzle/react-data-grid#2183]
With the removal of cellRangeSelection, is there a way to select a range of cells?

**Comment by amilich** [comment]
+1

**Comment by lucassarcanjo** [comment]
Any updates?

**Comment by NoobTW** [comment]
+1 for multi cell selection.

**Comment by nstepien** [comment]
Closing as duplicate of #2260
