### ISSUE TITLE
Dynamic row height and related features

### ISSUE THREAD

**Issue by Shihao-Zhong** [adazzle/react-data-grid#2188]
https://github.com/adazzle/react-data-grid/issues/671

Same as above issues, when we dynamically change the row height through RowRenderer function, if we use the vertical scrollbar it will always run into an infinite loop and will not render the grid properly. 

I think this is a serious issue, the reason why we use grid/cell based UI instead of the traditional table UI is because we are trying to allow customer to make update easier and better display the content in the grid. For now, RDG works great for small amount of data in each cell with large numbers of cells(the 1m cell example). But the support for the large data in each cell is also valuable for potential users. 

I think the following features may can bu put in consideration.
1. Dynamic row height by the data in a row. 
2. Allow put line break in a cell.
3. Dynamic line break if the data is too long. 

For anyone who have the same issue with me. I have the temporary thing here.

Use the following css to allow oversize line break with space and disable the vertical scrollbar()

white-space: normal !important;
overflowY: 'hidden'!important;

reset the height in RowRenderer by your own rules

 RowRenderer = ({ renderBaseRow, ...props }) => {
        if (props.height != this.state.rows[props.idx].title.length * 10) {
            props.height = this.state.rows[props.idx].title.length * 10
        }
        return renderBaseRow(props);
    };

add rowRenderer={this.RowRenderer} in your RDG component properties.

It will not drop in the infinite loop issues but it will still have some layout issue when updating

**Comment by Shihao-Zhong** [comment]
Otherwise, I tried to use Row component to made the grid line by line, but for some reason even if I filled all the require props in the <Row> component, it still have some compile issue, but that maybe another way to fix that.

**Comment by Shihao-Zhong** [comment]
Seems like nobody maintain this project anymore, I switched to Handsontable@6.2.2 with MIT license and seems like all the issues fixed

**Comment by preetilht** [comment]
Facing the same issue and I am struggling from a long time to get this fixed , but I don't think anyone from the team is active now as I don't see new issues getting assigned to someone.

**Comment by amber-cd** [comment]
Is there a way to do this in the Canary version? We are considering upgrading to Canary, but would like to have this option.

**Comment by amanmahajan7** [comment]
RDG now support variable row heights. Please check the changelog and example 
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--variable-row-height
