### ISSUE TITLE
Column drag double click updates wrong column when row select is enabled

### ISSUE THREAD

**Issue by tranquilize** [adazzle/react-data-grid#219]
The column index received in the cell drag double click event includes the "Row select checkbox" column, but the column index on update does not start from the "Row select checkbox" column. 

Thus, on column cell drag double click when row select is enabled, it will always update one column to the right.

**Comment by malonecj** [comment]
thanks for reporting this. We will take a look and fix

In the meantime we have implemented a new `handleGridRowsUpdated` function which we recommend using that gets triggered on all updates, either via cell editor, cell drag, copy/paste or dragHandleDoubleClick.

This saves you from having to implement 4 different update methods. You can see an example here
http://adazzle.github.io/react-data-grid/examples.html#/all-the-features

and the column drag handle does not update the wrong column in this case

**Comment by diogofcunha** [comment]
This is fixed in the current release.

Cheers.
