### ISSUE TITLE
Controlled frozen columns via checkbox. 

### ISSUE THREAD

**Issue by arditnurcaj** [adazzle/react-data-grid#2192]
Hi guys,

I have this case when I need to set/reset some frozen columns. It all works well on Edge, Chrome, Safari but only on Firefox setting/resetting frozen columns for some reason it doesn't work as expected, do we have some functions to set columns functionality? 

Here is the working example: https://codesandbox.io/s/friendly-shadow-l5it1?file=/src/DataTable.js.

Thanks,
Ardit

**Comment by nstepien** [comment]
Looks like a bug in Firefox, as the grid fixes itself automatically when resizing the container/window.

You can force Firefox to do a style/layout recalculation with a snippet like this:
```js
(() => {
  const rdg = document.querySelector('.rdg');
  rdg.style.minWidth = '0px'; // update style
  rdg.getBoundingClientRect(); // force the browser to do a style/layout recalc
  rdg.style.minWidth = null; // reset style
})()
```

Please file a bug report to Mozilla (if it hasn't been reported already...): https://bugzilla.mozilla.org/buglist.cgi?quicksearch=sticky

**Comment by arditnurcaj** [comment]
> Looks like a bug in Firefox, as the grid fixes itself automatically when resizing the container/window.
> 
> You can force Firefox to do a style/layout recalculation with a snippet like this:
> 
> ```js
> (() => {
>   const rdg = document.querySelector('.rdg');
>   rdg.style.minWidth = '0px'; // update style
>   rdg.getBoundingClientRect(); // force the browser to do a style/layout recalc
>   rdg.style.minWidth = null; // reset style
> })()
> ```
> 
> Please file a bug report to Mozilla (if it hasn't been reported already...): https://bugzilla.mozilla.org/buglist.cgi?quicksearch=sticky

Perfect, thanks a lot :)
