### ISSUE TITLE
Set a focus on the grid on a specific cell

### ISSUE THREAD

**Issue by ronenmalka** [adazzle/react-data-grid#2199]
Hi,
I'm trying to set a focus on a specific cell from outside the grid.
When user click on a button on the menu, I apply a function on the grid, but then I want to set back the focus on the grid:
`gridRef.grid.focus()` but this does not set the focus on the grid.
Any workaround?

**Comment by amanmahajan7** [comment]
You can use `gridRef.selectCell({ rowIdx, columnIdx })` to select a cell 
https://github.com/adazzle/react-data-grid/blob/canary/src/DataGrid.tsx#L66

**Comment by ronenmalka** [comment]
Thanks @amanmahajan7, `gridRef.selectCell({ rowIdx, columnIdx })` set the focus on the cell but in **Edit** mode. I just want to set the focus on the cell so the user can navigate the grid with the arrows keys,
