### ISSUE TITLE
Scrolling horizontally while editing on a frozen cell

### ISSUE THREAD

**Issue by arditnurcaj** [adazzle/react-data-grid#2202]
When scrolling horizontally while editing on a frozen cell, the cell goes along with the row instead of staying frozen left.
This only happens on Mozilla Firefox :/

Case: Try editing e.g Task cell and while editing scroll horizontally on the demo https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features

Thanks,
Ardit

**Comment by amanmahajan7** [comment]
Looks like a bug. We will investigate

**Comment by nstepien** [comment]
This is more or less the same issue that was reported here: https://github.com/adazzle/react-data-grid/issues/2192
Sticky support in Firefox seems somewhat buggy in edge cases.

**Comment by arditnurcaj** [comment]
> This is more or less the same issue that was reported here: #2192
> Sticky support in Firefox seems somewhat buggy in edge cases.

Yes, it seems they are related, thanks for the response :).

**Comment by amanmahajan7** [comment]
Closing this for now as it a browser bug
