### ISSUE TITLE
Not working with the latest version

### ISSUE THREAD

**Issue by bpolimetla** [adazzle/react-data-grid#2203]
https://codesandbox.io/s/gracious-pascal-ygj7v

1) Not able to align icon 
2) Not working with the latest versions. 
Please let me know how to solve this?

**Comment by amanmahajan7** [comment]
RDG v6 is no longer supported. Please try the latest canary and open a new issue if you are still facing issues

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--cell-actions
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
