### ISSUE TITLE
p.onRowChange is not a function

### ISSUE THREAD

**Issue by dailycodee** [adazzle/react-data-grid#2206]
`setColumns([...columns, {
      key: 'type', name: 'Type', editable: true, editor: p => (
        // console.log(p)
        <Select value={type} onChange={event => p.onRowChange(event.target.value, true)}>
          {response.data.recordset.map(item => (
            <MenuItem key={item.id} value={item.name}>{item.name}</MenuItem>
          ))}
        </Select>
      )
    }]);`

I find this function in ts sources and in samples, but it doesn`t work

**Comment by dailycodee** [comment]
init columns:
`[
        SelectColumn,
        {key: 'id', name: 'ID', editable: false},
        {key: 'name', name: 'Name', editable: true, editor: p => (
            console.log(p);
          )}
      ]`

why p doesn't have the onRowChange function?

![image](https://user-images.githubusercontent.com/35529406/98173004-c8dd9c00-1f0b-11eb-9532-5714cb39770c.png)

**Comment by amanmahajan7** [comment]
It seems like you are on an old version of RDG. Please try with rdg.canary.30

**Comment by dailycodee** [comment]
Failed to compile.

./node_modules/react-data-grid/lib/bundle.mjs
Can't import the named export 'Fragment' from non EcmaScript module (only default export is available)

I use create-react-app

**Comment by dailycodee** [comment]
react-app-rewired solve my problem.
npm i react-app-rewired
create "config-overrides.js" in root directory

config-overrides.js:

`module.exports = function override(webpackConfig) {
  webpackConfig.module.rules.push({
    test: /\.mjs$/,
    include: /node_modules/,
    type: "javascript/auto"
  });

  return webpackConfig;
}`
