### ISSUE TITLE
Looking for debouncing certain cells for auto complete / select options 

### ISSUE THREAD

**Issue by livehop** [adazzle/react-data-grid#2209]
Hi, 
I am loving the data grid -- was just wondering how I can debounce while the user is typing to allow him to select from the list of options ... (along with paging) 

Please suggest if this is possible; since it will save me a ton! --- many thanks for you efforts on this.

**Comment by amanmahajan7** [comment]
This question is more suited for stackoverflow as it is not related to actual grid functionality.
