### ISSUE TITLE
Failed propType: Required prop `value` was not specified in `EditorContainer`. Check the render method of `Cell`.

### ISSUE THREAD

**Issue by tobias-kuendig** [adazzle/react-data-grid#221]
Go to https://adazzle.github.io/react-data-grid/examples.html#/editors and edit a cell via double click.

The following warning is printed to the console:

```
Failed propType: Required prop `value` was not specified in `EditorContainer`. Check the render method of `Cell`.
```

**Comment by UngaWunga** [comment]
This might have been handled in issue #77 . Looking into this myself.

**Comment by timwis** [comment]
I'm getting this warning as well, using v0.14.29. I can't see how #77 could resolve it. Did you reference the wrong issue? (Also, for the life of me I can't tell what the difference is in the response to #77 other than reordering lines)

**Comment by marafee1243** [comment]
@timwis. did you resolve that issue. as i am having the same issue.

**Comment by timwis** [comment]
I think it worked when I downgraded react. Personally, I switched to the [choo](https://GitHub.com/yoshuawuyts/choo) framework. Much easier and transparent

**Comment by giko45** [comment]
change
	      return React.createElement(EditorContainer, { rowData: this.getRowData(), rowIdx: this.props.rowIdx, idx: this.props.idx, cellMetaData: this.props.cellMetaData, column: col, height: this.props.height });
	    }

to
	      return React.createElement(EditorContainer, { rowData: this.getRowData(), rowIdx: this.props.rowIdx, value: this.props.value, idx: this.props.idx, cellMetaData: this.props.cellMetaData, column: col, height: this.props.height });
	    }
