### ISSUE TITLE
Cannot read property 'Column' of undefined

### ISSUE THREAD

**Issue by bpolimetla** [adazzle/react-data-grid#2212]
Trying to migrate to a new version 7.x, getting this error.
Cannot read property 'Column' of undefined

Code - https://codesandbox.io/s/rdg-editors-dropdown-editor-7x-z9smb?file=/src/index.js
-----
Gone through this, but not able to apply
https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/components/Editors/DropDownEditor.tsx
-----

**Comment by arditnurcaj** [comment]
> Trying to migrate to a new version 7.x, getting this error.
> Cannot read property 'Column' of undefined
> 
> ## Code - https://codesandbox.io/s/rdg-editors-dropdown-editor-7x-z9smb?file=/src/index.js
> ## Gone through this, but not able to apply
> https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/components/Editors/DropDownEditor.tsx

Look at the examples provided in the storybook & source code at stories/demos you will find multiple examples provided for your case.

**Comment by amanmahajan7** [comment]
Please check the example and demos. The api for canary is different from V6
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
