### ISSUE TITLE
Missing require('react-dom') in AutoCompleteEditor

### ISSUE THREAD

**Issue by mgolinelli** [adazzle/react-data-grid#222]
const React                   = require('react');
**const ReactDOM      = require('react-dom');**
const ReactAutocomplete       = require('ron-react-autocomplete');
const ExcelColumn             = require('../grids/ExcelColumn');

**Comment by jpdriver** [comment]
hey @mgolinelli thanks for flagging that. see https://github.com/adazzle/react-data-grid/pull/223
