### ISSUE TITLE
Failed to compile with npm install

### ISSUE THREAD

**Issue by TechSupportPlugnotes** [adazzle/react-data-grid#2223]
Failed to compile with npm install global

./node_modules/react-data-grid/lib/bundle.mjs
Can't import the named export 'Fragment' from non EcmaScript module (only default export is available)

But if you remove from package json make npm install then add npm install react-data-grid@7.0.0-canary.29 in terminal

You can build or start, but not when a fresh install.

**Comment by amanmahajan7** [comment]
This has been in rdg.canary.32
https://github.com/adazzle/react-data-grid/pull/2221
