### ISSUE TITLE
Summary rows above content

### ISSUE THREAD

**Issue by ekeuus** [adazzle/react-data-grid#2229]
Is there a possibility to have fixed summary rows also above the content? I am willing to also create a PR if it is not available yet.

**Comment by peetjvv** [comment]
@ekeuus , I came across this issue looking for something else relating to the summary rows.
I believe this has been implemented. Can probably close this issue.

**Comment by ekeuus** [comment]
Indeed, it's now available. https://github.com/adazzle/react-data-grid/blob/main/website/demos/CommonFeatures.tsx#L347C1-L348C38
