### ISSUE TITLE
Can't resolve 'react/jsx-runtime'

### ISSUE THREAD

**Issue by matine** [adazzle/react-data-grid#2230]
Hi. I'm using create-react-app with typescript and storybook and I've just installed `react-data-grid` and `@types/react-data-grid` which went smoothly. But when I create a very basic data grid component based on your example on your website and added it to storybook, my code doesn't compile and I get the following error

```ERROR in ./node_modules/react-data-grid/lib/bundle.js
Module not found: Error: Can't resolve 'react/jsx-runtime' in '/node_modules/react-data-grid/lib'
```

I tried to update to the latest CRA but that didn't help.

I also found this commit from 4 days ago that could be something to do with it https://github.com/adazzle/react-data-grid/commit/5d75c6aa3cfca7c443a011e398edd7b9da2a9e18

**Comment by nstepien** [comment]
Depends on https://github.com/facebook/react/issues/20235
We might have to revert to the old jsx runtime if it cannot be fixed upstream quickly enough.

**Comment by matine** [comment]
Thanks for your speedy response. The older version works for now 👍

**Comment by ziperfal123** [comment]
Hey. I am facing the same issue. Tried to downgrade the version to `7.0.0-canary.30 ` as mentioned above, but i am still getting the same error. Any other solution? can't really understand why it is still happening.

Thanks!!

**Comment by ckeboss** [comment]
Any update on this?

**Comment by ekeuus** [comment]
> Any update on this?

I fixed it by updating react to 16.14

**Comment by behuf** [comment]
same problem.

**Comment by maximborisov** [comment]
[That ](https://github.com/facebook/react/issues/20235#issuecomment-750911623) fixed problem to me

**Comment by nomanoff** [comment]
I had the same issue with react-dnd. 
The solution was to use older version of react-dnd 
this:
![image](https://user-images.githubusercontent.com/60359425/110423417-5a406300-80e4-11eb-8acd-029740b925ce.png)

**Comment by denis-597** [comment]
Well, I solved my problem by replacing the versions of these dependencies in the package.json file: 
`
    "react-dom": "latest",
    "react": "latest",
    "@mui/material": "latest",
    "@emotion/styled": "latest",
    "@emotion/react": "latest"
`

**Comment by F3RN4ND02** [comment]
> Well, I solved my problem by replacing the versions of these dependencies in the package.json file:
> 
> ```
>     "react-dom": "latest",
>     "react": "latest",
>     "@mui/material": "latest",
>     "@emotion/styled": "latest",
>     "@emotion/react": "latest"
> ```

This helped me out

**Comment by shayan2601** [comment]
> > Well, I solved my problem by replacing the versions of these dependencies in the package.json file:
> > ```
> >     "react-dom": "latest",
> >     "react": "latest",
> >     "@mui/material": "latest",
> >     "@emotion/styled": "latest",
> >     "@emotion/react": "latest"
> > ```
> 
> This helped me out

This solution is showing an error "Invalid hook call...." in react app
