### ISSUE TITLE
While filtering, the screen goes blank for null values

### ISSUE THREAD

**Issue by amudigoudar-df-mdsol** [adazzle/react-data-grid#2235]
When there are some null values returned in a column and if we try to filter the column with blanks, the grid breaks and the screen goes blank with the following error:
  **Uncaught TypeError: Cannot read property 'toString' of null**

Can anyone please provide a solution for this.

**Comment by amanmahajan7** [comment]
Grid does not handle filtering logic and it seems like a code in the custom code. I am closing this for now. If you are still facing issues then can you create a codesandbox example.
