### ISSUE TITLE
canary : columns reordering

### ISSUE THREAD

**Issue by TechSupportPlugnotes** [adazzle/react-data-grid#2238]
Hello, I recently started using your project.

For technical reasons, I am using your canary version.

However, I am having a little trouble understanding how to use columns reordering.

Do you have an example of use because reading the code of the demos, I am a little lost on this point.

And without that, I can't get feedback to the project.

**Comment by arditnurcaj** [comment]
Hi @TechSupportPlugnotes, I think what are you looking is:
 - Example: https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--columns-reordering
 - Source Code: https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/ColumnsReordering.tsx

Here are the example and the source code for column reordering, everything relating with the source code you have it in the demos folder.

Regards,
Ardit.

**Comment by TechSupportPlugnotes** [comment]
Ok i'm watching this a few days ago, but my problem was , what i really need for this ?

Just add himself react-dnd and attach the data grid and then ? Or it's in the plugin ?

My problem concern analyse demo code, 

I didn't know this plugin before so it's not easy to understand everything without a simplified example

**Comment by arditnurcaj** [comment]
I think you should install these two libraries `react-dnd`, `react-dnd-html5-backend` to your project and then import them like in the example and try to translate and adapt the demo to your project.

**Comment by TechSupportPlugnotes** [comment]
ok , thx, i'm glad that confirm the first step, i'm working in big project but i was alone and it's great that can answer me , take care of you and thank a lot ;).

**Comment by arditnurcaj** [comment]
Nothing, glad I can help :)

**Comment by TechSupportPlugnotes** [comment]
@arditnurcaj , hello i found a solution with canary.29, and it's working.
Now , i'm waiting a answer about .33 in another issue, but i'm very happy that's all working at this time :).
Thank you again for your time and help.
