### ISSUE TITLE
how to edit a single row, not the whole table?

### ISSUE THREAD

**Issue by dcsan** [adazzle/react-data-grid#2240]
is there a way to get just the **changed** row when rows are edited?

using v7 canary, I followed ts example, and added 

onRowsChange={onRowsChange}

but this only gets called with ALL the data from the FULL table.
there used to be an `onGridRowsUpdated` method

https://adazzle.github.io/react-data-grid/docs/examples/default-editor#enabling-cell-edit

```ts
  onGridRowsUpdated = ({ fromRow, toRow, updated }) => {
...
```

but this seems removed in v7

with a large data table, this means sending out the whole table to the server for updates / DB writes every time.
surely I'm missing something?

perhaps I need to create special method with cell actions? like this:

https://codesandbox.io/s/r57ox1p39q?file=/src/index.js:1465-1476

by the cell... is more granular than I wanted. I just want to update a single DB record, not a field.

**Comment by vitpekarek** [comment]
Hi, I am doing this by checking objects inside old and new row array.

Maybe this little fuction can help you:

`const getChanges = (originalArray, newArray) =>
    newArray.filter((newRow, index) => originalArray[index] !== newRow);`

this way I get only updated rows...

Idk if this is the best solution, but it's only one I found by myself ...

**Comment by dailycodee** [comment]
Exactly the same problem

**Comment by dcsan** [comment]
@vitpekarek thanks for the comment. doing client side diffs is a bit risky really, esp if you have some nested or not displayed data... but it's an option.

I was thinking about another way to keep track of rows that are being edited as "dirty" with a single column. 
I did that in the `SelectCellFormatter` like this. I'm not sure 

```
      return (
        <SelectCellFormatter
          tabIndex={-1}
          value={formatOpts.row.hidden}
          onChange={() => {
            formatOpts.onRowChange({
              ...formatOpts.row,
              dirty: true,  /// <= this assumes you have a `dirty` field on all data
              hidden: !formatOpts.row.hidden
            });
          }}
          onClick={stopPropagation}
          isCellSelected={formatOpts.isCellSelected}
        />
      );
```

Perhaps a modified `TextEditor` component [based on this](https://github.com/adazzle/react-data-grid/blob/canary/src/editors/TextEditor.tsx#L19) could also modify the returned row in a similar way?

**Comment by dcsan** [comment]
there's also the method when you click on a row to change the `selectedRows` ... 

so maybe the selectedRows could be used as a background, which could give the benefit of highlighting edited rows if you wanted to batch saves/commits.

there's also clicking on rows, could trigger a `dirity=>true`, but you don't know if something is actually changed unless you track changes inside the editor /formatter method. which is a lot of code to write on top.

```
const [selectedRows, setSelectedRows] = useState(() => new Set<React.Key>());


      <DataGrid
        rowKeyGetter={rowKeyGetter}
        columns={columns}
        rows={rows}
        selectedRows={selectedRows}
        onSelectedRowsChange={setSelectedRows}
        onRowsChange={onRowsChange}
        className="fill-grid"
        defaultColumnOptions={{
          sortable: true,
          resizable: true,
        }}
      />

```

**Comment by dcsan** [comment]
ok so I went ahead and created a new `DirtyTextEditor` (maybe it could have a better name 😏  )


```ts
import type { EditorProps } from 'react-data-grid';

function autoFocusAndSelect(input: HTMLInputElement | null) {
  input?.focus();
  input?.select();
}

export default function DirtyTextEditor<TRow, TSummaryRow = unknown>({
  row,
  column,
  onRowChange,
  onClose
}: EditorProps<TRow, TSummaryRow>) {
  return (
    <input
      className="rdg-text-editor"
      ref={autoFocusAndSelect}
      value={row[column.key as keyof TRow] as unknown as string}
      onChange={(event) => onRowChange({
        ...row,
        dirty: true,
        [column.key]: event.target.value
      })
      }
      onBlur={() => onClose(true)}
    />
  );
}

```

use it like this in your `columns`
```ts
const columns: any = [
  {
    key: 'text',
    name: 'text',
    width: 400,
    editable: true,
    editor: DirtyTextEditor
  },
]
```

and then I have a function client side to only send dirty rows

```ts
  async postQuestions(params: any) {
    let { rows, query } = params
    log('postQuestions', rows)
    rows = rows.filter((row: IQuestion) => row.dirty)

    return axios.post('/api/questions', { data: rows, query })
```

**Comment by dcsan** [comment]
on the response I modify `dirty: false` so it looks like this:

![rowedit](https://user-images.githubusercontent.com/514002/100580003-04188400-329a-11eb-8c5e-1c4759b3f687.gif)

since I also have some calculations server side, I didn't want to send the whole big table if nothing changed.

**Comment by dcsan** [comment]
hope that helps someone else. @nstepien let me know if I can add to any docs in case someone else wants to use this method. or maybe I could add an example? if helpful I will do a PR (tho, this does also require some mock response to update)

**Comment by archletekke** [comment]
This was available in canary v24, but not in the newer versions for some reason. The old prop used to be called `onRowsUpdate`

**Comment by dcsan** [comment]
@archletekke there is `onRowsChange` as a param to the DataGrid itself, but not for each row. Is that what you meant?
but this gives data for the whole table, not a row by row basis.

**Comment by ekeuus** [comment]
From my other account - but no, that's not what I meant. There used to be a onRowsUpdate prop, which worked just like you seem to describe it - https://github.com/adazzle/react-data-grid/blob/v7.0.0-canary.24/src/DataGrid.tsx#L101.

I was able to implement a solution to "re-create" that logic outside of the table by checking which cell (row and column index will show us the row and column.key will give us the edited field - https://github.com/adazzle/react-data-grid/blob/canary/src/DataGrid.tsx#L140) is active during editing, which allows to check which row an which column was edited.

**Comment by dcsan** [comment]
@ekeuus thanks! so you mean each time a cell is clicked/edited, you separately keep track of the row/column and then filter that row out when you do a save?

I was also thinking about an idea like that as in the cellActions codepen I linked above, with `cellActions`

```
function getCellActions(column, row) {
  const cellActions = {
    firstName: firstNameActions
  };
  return row.id % 2 === 0 ? cellActions[column.key] : null;
}
```

I think your approach is better. It means only have to put the code once in the DataGrid component to intercept and track the changes there. Can you share any other code of what you did?

```ts
  /** Function called whenever selected cell is changed */
  onSelectedCellChange?: (position: Position) => void;
```

so like
```jsx
<DataGrid 
   onSelectedCellChange: function(pos: Position) { // track it } 
... />
```

I also wanted to update the `selected rows` to hilight editing/dirty lines

**Comment by tboyer42** [comment]
An other problem with onRowsChange is that it will create a new copy of the data; if you have one million rows, it is time and memory consuming.
Worse, if your data is backed by a proxy that calls an api, react-data-grid will ignite all the calls necessary to retrieve the whole dataset (and if you have millions of rows in your database, an edit might take some long minutes...).

**Comment by archletekke** [comment]
I could try to implement the smaller onChange logic at some point this week. Will post here if I have a PR.

**Comment by ekeuus** [comment]
Added a method for a single row change - not sure if it covers all required cases, but using the rowIdx it should be possible to implement what you need. https://github.com/adazzle/react-data-grid/pull/2275

**Comment by nstepien** [comment]
Hi, we've `7.0.0-canary.34` which has an updated `onRowsChange` signature: its second parameter contains the indexes of the changed rows, along with the column which triggered the change.

**Comment by amanmahajan7** [comment]
Closing as the issue was resolved.
