### ISSUE TITLE
rowKeyGetter : Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by TechSupportPlugnotes** [adazzle/react-data-grid#2242]
Hello, i'm in trouble when i use rowKeyGetter, because i have this warning:

`Warning: Each child in a list should have a unique "key" prop`

I want to have the select column, it's work fine but  i don't how to resolve this warning.

**Comment by arditnurcaj** [comment]
Hi @TechSupportPlugnotes, the rowKeyGetter accepts a function with a parameter 'row', not a string. rowKeyGetter should be specified in DataGrid component table, for e.g <DataGrid rowKeyGetter: (row) => row.id /> or something unique instead of id.

**Comment by TechSupportPlugnotes** [comment]
ok i understand, i do write this code   rowKeyGetter={(row) => row.hash || ''}, certainly during pre-load data was not realy in memory stack.

**Comment by arditnurcaj** [comment]
@TechSupportPlugnotes If the data is not really in the memory yet then you can handle it in data={data || []} in DataGrid component. Glad it worked :)

**Comment by TechSupportPlugnotes** [comment]
Thanks ;)
