### ISSUE TITLE
headerRenderer Breaking change between canary.29 vs canary.33

### ISSUE THREAD

**Issue by TechSupportPlugnotes** [adazzle/react-data-grid#2243]
Hello, it's me again,
I'm in trouble, i would like to update react-data-grid canary to lastest,
But my custom headerRendered not working fine anymore, cannot resize and cannot sortable ...
So i continue to use .29, but i would like to understand or know if have change about this.

```
const headerIdView = (object) => {
        return ( 
              <div style={{ color : "#58C3C1" }}
                className="flex_display_direction_column"
            >
                <span> {object.column.name} </span>
            </div>
        );
    }
```

`            columns.push({ key: "userindex", name: "N°",
                resizable: true,
                sortable : true,
                item : 1,
                headerRenderer: headerIdView,
                formatter : specialAction,
            });
`

**Comment by amanmahajan7** [comment]
You need to manually add `SortableHeaderCell` to custom `headerRenderer`
https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/components/HeaderRenderers/DraggableHeaderRenderer.tsx#L46
