### ISSUE TITLE
Select rows by clicking on them

### ISSUE THREAD

**Issue by forgetmenot377** [adazzle/react-data-grid#2246]
Hi. I'm currently using this example for bulk actioning:

 https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/CommonFeatures.tsx#L45. 

Is there a way to select a row not only by clicking on `SelectColumn` but also on any cell of the row?

**Comment by amanmahajan7** [comment]
`onRowClick` event can be be used to make this change.
https://github.com/adazzle/react-data-grid/blob/canary/src/DataGrid.tsx#L151

**Comment by AmirHosein20** [comment]
> `onRowClick` event can be be used to make this change. https://github.com/adazzle/react-data-grid/blob/canary/src/DataGrid.tsx#L151

This address currently not found

**Comment by iamrakhmatov** [comment]
> `onRowClick` event can be be used to make this change. https://github.com/adazzle/react-data-grid/blob/canary/src/DataGrid.tsx#L151

is this still possible?
