### ISSUE TITLE
Necessary cell rerendering does not happen

### ISSUE THREAD

**Issue by gernotkogler** [adazzle/react-data-grid#2247]
Cells are not rerendered in the following scenario:

- initialize the grid with 3 columns and an empty row
- write a paste handler that maps the clipboard data from eg excel to the grid rows
- copy from Excel into the clipboard (1 row with three values)
- click into the first cell and paste

The selected cell shows the pasted value but the other two cells are not rerendered immediately. You need to focus them to force the rerender and show the row value

**Comment by gernotkogler** [comment]
See the bug in action: https://codesandbox.io/s/headless-browser-c98r0

**Comment by amanmahajan7** [comment]
https://codesandbox.io/s/react-data-grid-clipboard-paste-forked-0jnnm?file=/src/App.js

Row must be cloned before updating it otherwise React cannot register the change

**Comment by gernotkogler** [comment]
I agree that it's good functional programming style to always return something new from functions. Anyways, I still think that memoizing Cells is an overly aggressive optimization that leads to subtile, unexpected behaviour in perfectly valid code. The performance impact ist zero btw, even in the A Million Cells story.

**Comment by amanmahajan7** [comment]
The code has a bug and it can lead to unexpected errors. Please check
https://reactjs.org/docs/state-and-lifecycle.html#do-not-modify-state-directly

**Comment by gernotkogler** [comment]
Thanks for the link, I guess I learned something!
