### ISSUE TITLE
"^7.0.0-canary.33", doesn't work

### ISSUE THREAD

**Issue by ryanwtyler** [adazzle/react-data-grid#2249]
i have the most simple example you can imagine and it just renders the column headers and the height of the container div just increases infinitely.

```
import React, { ReactElement } from 'react'

import DataGrid from 'react-data-grid'

export default function WorkoutsTest(props): ReactElement {
    const columns = [
        { key: 'id', name: 'ID' },
        { key: 'title', name: 'Title' },
    ]

    const rows = [
        { id: 0, title: 'Example' },
        { id: 1, title: 'Demo' },
    ]

    return (
        <>
            <DataGrid columns={columns} rows={rows} h></DataGrid>
        </>
    )
}
```

**Comment by jamrsim** [comment]
Add ...
`import 'react-data-grid/dist/react-data-grid.css'`
... just after the import DataGrid line and see if that doesn't fix your issue.  I was experiencing the same trouble.

**Comment by jamrsim** [comment]
[CodeSandbox example working and not](https://codesandbox.io/s/intelligent-firefly-b9wi4?file=/src/App.js)

**Comment by nstepien** [comment]
@jamrsim that example works fine for me, what's happening on your side?

**Comment by jamrsim** [comment]
> @jamrsim that example works fine for me, what's happening on your side?

// Comment out the following line to see the described behavior
import "react-data-grid/dist/react-data-grid.css"; // Uncommented fixes the problem

The example I created ... if you wish to see the original problem comment out the import line.  If you wish to see the problem fixed, uncomment the import line.

Commented recreates the initial problem as described.  Simply adding the .css file fixes the problem/symptom.

Thank you

**Comment by nstepien** [comment]
Ah right. Yes it needs its styles to work properly indeed.

**Comment by jamrsim** [comment]
[v7.0.0-canary.35](https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md#v700-canary35)
Migrate to css-in-js with linaria (PR). RDG now internally uses linaria to manage styles. The stylesheets are automatically injected and there is no stylesheet to manually import anymore.

With this release the need to import the react-data-grid.css is no longer needed.  In fact, if you do, it will not compile, that happened to me and I had to remove the import.  Prior to *.35, this needs imported.

**Comment by jamrsim** [comment]
@amanmahajan7 or @nstepien I recommend closing this issue.  The original example as provided will now successfully work on or after v7.0.0-canary.36. Thank you.

cc: @ryanwtyler
