### ISSUE TITLE
Dragging to fill down redirects Mac OS Firefox to dummy.com

### ISSUE THREAD

**Issue by moodysalem** [adazzle/react-data-grid#225]

**Comment by moodysalem** [comment]
Actually it even happens in the demo
http://adazzle.github.io/react-data-grid/examples.html#/editable

**Comment by moodysalem** [comment]
And it happens with or without a drag handler

**Comment by ibrahima** [comment]
Happens on Firefox on Linux too, this is really bizarre!

**Comment by adeboni** [comment]
It also happens on Firefox on Windows

**Comment by chris-brannen-alps** [comment]
Just wondering if anyone had been able to fix this, if not is there a way to disable the drag functionality?

**Comment by LiranV** [comment]
I've encountered the same behavior on Firefox (Linux).

**Comment by thomas-shares** [comment]
I am seeing this as well and I can also recreate it at http://adazzle.github.io/react-data-grid/examples.html#/cell-drag-down with the latest FireFox 50.1.0 on Mac OS and also on Linux (with the same FireFox version).

Would there be a way to work around this, for instance by disabling dragging for instance?

**Comment by thomas-shares** [comment]
I have made a PR for issue #600, but that, unfortunately, doesn't work around this issue. Any advice on how to deal with this would be greatly appreciated.
Thank you
