### ISSUE TITLE
how to prevent editable on row double click

### ISSUE THREAD

**Issue by vaddisiva5034** [adazzle/react-data-grid#2250]
Hi i am using the react-data-grid  version "^6.0.1",

- currently editor is getting enabled upon double click on row 
- But i want to do other event on row double click, i am able to implement that by prop onRowDoubleClick
- But i want to prevent the editable on double click instead of that i want to make edit when the user click `shift+ click`
- is there any way to do that please suggest some solutions 
- it is blocking my current development

i am able to see these editorOptions on column in the on version 7.0.0-canary.33 can we have any similar options
editorOptions = {
                        editOnClick: true,
                        editonDoubleClick: false
                    };

**Comment by amanmahajan7** [comment]
`react-data-grid version "^6.0.1"`is no longer supported and we recommend migrating to the latest canary version
