### ISSUE TITLE
How do I set table height?

### ISSUE THREAD

**Issue by avalanche1** [adazzle/react-data-grid#2251]
In prev canary versions RDG used to accept `height` prop. Not it's ignored (canary 16-33).
My table doesnt render all the rows that I supply to it.

**Comment by stonestecnologia** [comment]
I need to ! tnks

**Comment by amanmahajan7** [comment]
you can use the `style` or the `className` prop

```
<DataGrid
  style={{ height }}
  className
```

**Comment by dcsan** [comment]
className doesn't seem to get passed in, see #2252
