### ISSUE TITLE
How do I set table height automatic

### ISSUE THREAD

**Issue by stonestecnologia** [adazzle/react-data-grid#2252]
I need to configure my RDG so that the height is automatic
`className="fill-grid"`
does not work

**Comment by dcsan** [comment]
yep same here, spent a bunch of time screwing around with this.

one odd thing is that when deployed it does have some effect. So it maybe something with development mode (I'm using create-react-app) not providing the CSS files at the right time, where final build does.

anyway it's very annoying.

**Comment by dcsan** [comment]
`style={{ height: '100%' }}`

this seems to be the only way, the className is ~ ignored?
100% of your parent container at least.

**Comment by arditnurcaj** [comment]
@stonestecnologia I do this `style={{
        maxHeight: '40vh',
        height:
          !rows || rows.length === 0 ? undefined : (rows.length + 1) * 27 + 42,
      }}` assuming the rowHeight is 27 and headerRowHeight is 50, move these values around as you have your rowHeight values.

**Comment by dcsan** [comment]
magic numbers! what is 42? header row height?

**Comment by arditnurcaj** [comment]
This 42 is like change it until it works for you haha

**Comment by dcsan** [comment]
jeez, there isn't a way to pin bottom of it to the bottom of the container with CSS? like `bottom: 100%`  ?

**Comment by arditnurcaj** [comment]
Then I think you should go with height: 100% as mentioned before by you, based on what you are saying.

**Comment by stonestecnologia** [comment]
Thanks guys, I'm going to test.

**Comment by nstepien** [comment]
`fill-grid` is only a class we use in our examples, you'll have to set the height yourself using custom css via the `className` or `style` props.

**Comment by karthikeyan676** [comment]
style={{ height: "100%", contain: "none" }}

Try this one

**Comment by liangxiwei** [comment]
> headerRowHeight

default is 35,so if you not set custom row height and column height, you can use this style
```
style={{ height: !rows || rows.length === 0 ? undefined : (rows.length + 1) * 35 }}
```
