### ISSUE TITLE
V7.0.0-canary.22 upwards Grid fails to render when AutoSizer is used

### ISSUE THREAD

**Issue by paul-altyfc** [adazzle/react-data-grid#2254]
It appears that a breaking change has been implemented in canary.22 

My code renders correctly using canary.21 but I have tried all later version and it fails to render. If I remove AutoSizer then the grid will render correctly.

`    return (
        <AutoSizer>
            {({ height, width }) => (
                <DataGrid
                    rowKey="id"
                    rowHeight={ROW_HEIGHT}
                    columns={columns}
                    rows={sortedRows}
                    // rows={filteredRows}
                    width={width}
                    height={height}
                    sortColumn={sortColumn}
                    sortDirection={sortDirection}
                    onSort={handleSort}
                    emptyRowsRenderer={emptyRowsRenderer}
                    // enableFilters={enableFilters}
                    // filters={filters}
                    // onFiltersChange={setFilters}
                    // summaryRows={summaryRows}
                    onRowClick={(rowId, row) => rowClicked(row)}
                    rowClass={row => {
                        //console.log(row)
                        return (
                            row[rowClassColumn] === valueToCheck ? 'highlight' : undefined
                            )
                    }}
                />
            )}
        </AutoSizer>
    )
`

**Comment by nstepien** [comment]
You'll need to use the `style={{ width, height }}` prop instead.

**Comment by amanmahajan7** [comment]
Please open a new issue if you are still facing issues.
