### ISSUE TITLE
Bug: Row checkbox is focused every time it is rendered.

### ISSUE THREAD

**Issue by ph-legacy** [adazzle/react-data-grid#2257]
Because of this https://github.com/adazzle/react-data-grid/blob/5d75c6aa3cfca7c443a011e398edd7b9da2a9e18/src/formatters/SelectCellFormatter.tsx#L29 line (usage of `inputRef`) every time the the row is rendered the checkbox is focused.

This interfere with filtering use-case.

1. Having a fill-text filtering.
2. I first select some row and the deselect it.
3. Now I start to filter
4. Once the selected row (on given index) is replaced by other row (effectively is filtered out, the row is re-rendered.
5. The focus is now on the row-checkbox and **user who was typing the filter query loses focus on filter input**.

![image](https://user-images.githubusercontent.com/383295/102523628-1830f380-4098-11eb-908d-2d10be47dd82.png)

**Comment by amanmahajan7** [comment]
Can you create a codesandbox example?
