### ISSUE TITLE
Grid does not change when new columns are passed

### ISSUE THREAD

**Issue by moodysalem** [adazzle/react-data-grid#226]
I need a list of options in the dropdown editor of one column to depend on the values of a column in another grid

Thus I'm passing a new array of columns to the columns prop whenever the list of values in the other grid changes, with the new dropdown editor

However the grid is not changing

The workaround to this is changing the key whenever the columns change so a new grid is rendered

**Comment by bakesteve** [comment]
Seems like an alternate approach would be just to have state that sits in a container above both grids, and pass an editor to the 2nd grid for the column you want to be dependant, that looks at this state (via a prop)
Better still, use flux / stores (we’d recommend redux)

**Comment by moodysalem** [comment]
What if I wanted the user to be able to customize which columns are displayed?

This has little to do with the architecture IMO-the grid should handle new props in componentWillReceiveProps to update the state for the new columns

**Comment by bakesteve** [comment]
sure - I was talking about your specific use case, but absolutely, if you mutate columns (user changes them, re-arrange, master-detail means you want different  columns, not just different options in an editor, etc), it should re-render.

There is a check in shouldComponentUpdate, but its probably making a bit too much of an assumption on immutability (doing `props.columns !== nextProps.columns`)
As long as we can get a test on this, we could then add a deep check of some form where you are not using immutable columns (assuming that this is the root of the problem)

**Comment by moodysalem** [comment]
I'm not sure that's the root of the problem, I'm providing a new array when the dropdown options change so `props.columns !== nextProps.columns` should return true. The component even when re-rendered (editing another column for example) is still showing the old dropdown

**Comment by moodysalem** [comment]
I haven't looked at the code much but my guess is the component keeps track of the list of columns in a state variable, so that it can handle width adjustments and reordering. Merging the user changes that are not controlled and a new list of columns in the columns prop is probably just not done.

**Comment by bakesteve** [comment]
those are (mostly) kept in columnMetrics vs columns, but we'll get a

**Comment by BDiehr** [comment]
For what it's worth, I have a use case as well which requires `columns` prop update to be reflected, and I confirmed that this is the case even when `prevProps.columns !== props/columns //true`

**Comment by lynnard** [comment]
This is affecting me as well - annoying as sometimes it works. There are also other random problems where it calls attributes on `undefined` columns when the columns change.

**Comment by willgates** [comment]
I've created a [JSFiddle](https://jsfiddle.net/h00a2naw/) (forked from the basic example) that reflects changes to the columns prop. Is this still an issue?

**Comment by tizzle** [comment]
Hey @willgates ,

can we please reopen this as the issue persists? It works, wehen items are added or removed from the columns array, but not if e.g. the name of a column or the sorting of array changes. I've updated your fiddle with a second button:

https://jsfiddle.net/h00a2naw/3/

Can you please have a look into this? This makes using DraggableHeader impossible for me atm.

Thanks a lot!

Till

**Comment by JimTheMan** [comment]
I'm also having issues when data is ain a Redux store. Like @tizzle, if I add / remove columns it updates but not if I reorder columns in the array. I've tried many hacks with Object.assign and JSON.parse(JSON.stringify(, but nothing is working correctly for me. :(

**Comment by loehx** [comment]
me too

``` 
    "react-data-grid": "^2.0.54",
    "react-data-grid-addons": "^2.0.54",
```

```
const {Toolbar, Data: {Selectors}, DraggableHeader: {DraggableContainer}} = require('react-data-grid-addons');
...
<DraggableContainer onHeaderDrop={ this.onHeaderDrop.bind(this) }>
    <ReactDataGrid onGridSort={ this.handleGridSort.bind(this) } enableCellSelect={ true } columns={ columns } rowGetter={ i => processes[i] } rowsCount={ processes.length }
        minHeight={ 400 } toolbar={ <Toolbar enableFilter={ true } /> } onAddFilter={ this.handleFilterChange.bind(this) } onClearFilters={ this.onClearFilters.bind(this) } />
</DraggableContainer>
```

**Comment by Jake1996** [comment]
Hey @JimTheMan here is a quick fix : 
Add/Delete an empty column whenever there isn't a change in the number of the newColumns
```
if(newColumns.indexOf(column=>column.key==='1')!==-1)
   newColumns = newColumns.filter(column=>column.key!=='1')
else
   newColumns = [...newColumns,{ width: 0, id: '1', key: '1' }]

```
Just make sure that the length gets altered every time there is a change in the order of columns, to force react-data-grid to update.

**Comment by Ragzzy-R** [comment]
can we reopen it? or has there been a fix for this? Im currently using.

    "react-data-grid": "5.0.5",
    "react-data-grid-addons": "6.1.0",


my column definitions are updated immutably and the new columns are added to the grid but the data are not refreshed. all the new columns shows up blank. sorting the column brings up the data.


> Just make sure that the length gets altered every time there is a change in the order of columns, to force react-data-grid to update.

change in columndef size didn't work for me. 

I have n columns initially. i have a column chooser(custom component that updates what columns to display). which updates columns from n to n+1 (immutably). 

happy to give a PR if someone can direct me where to start.

**Comment by Ragzzy-R** [comment]
@willgates  in your fiddle, can u have data for that column and check if they are reflected? for example in ur initial column should only have 

`    var columns = [
      { key: 'id', name: 'ID' },
      { key: 'title', name: 'Title' } ];` 

but keep the rows same (i.e) have data for "count" even though count is not yet in Columndefs.

then dynamically add count as a new column. now the grid should show up count column with the row data for count. This is what im trying to achieve. the columns are added to me but the data is not reflecting.

a little bit context on why im doing this:

we get data from the backend for the entire table(ofcourse not all the rows just rows needed for first page but just all columns). then based on user input, we manipulate column definitions to show and hide columns(but no change in state.records).
