### ISSUE TITLE
Frequently update grid's data (with background color changes)

### ISSUE THREAD

**Issue by buglessir** [adazzle/react-data-grid#2262]
This grid works well to show the data after one API call. but in this case we have a frequently data refresh with a socket data streamer and should update the grid after each changes. we need change the cells background to green/red/yellow for prices update...

So, Is there any trick to handle cells background with any changes from the socket service? I need to select that changed cell and change background to those colors.

Thanks

**Comment by amanmahajan7** [comment]
This is outside the scope of react-data-grid but you can potentially compare data and use `column.cellClass` and `rowClass` to highlight the cells. 

```
cellClass(row) {
  return previousRow.value > row.value ? 'red': 'green'
}
```
