### ISSUE TITLE
"^7.0.0-canary.30", doesn't support copy/paste

### ISSUE THREAD

**Issue by ggkrishkumar** [adazzle/react-data-grid#2264]
Hi Team,

I was using react data grid 6.0.1. It supports copy/paste functionality. But when I updated to latest one, copy/paste functionality is not working. Is that because of latest version. Anyone facing such issue?

**Comment by amanmahajan7** [comment]
It is supported since v7 canary 28
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md#v700-canary28
https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/AllFeatures.tsx#L244
