### ISSUE TITLE
Having Issues using ^7.0.0-canary.33 with React code when trying to implement drag and drop.

### ISSUE THREAD

**Issue by yashjais18** [adazzle/react-data-grid#2265]
Hello Team. 
I'm having issues when I'm using react-data-grid with React Code. 
useCombinedRefs is not working with React Code. 
The issue is 'useCombinedRefs' is not exported and we need it pass it in Row in rowRenderers.
Sanbox link [here](https://codesandbox.io/s/rdg-row-reorder-700-canary33-ed0mu?file=/src/App.js).

Any one else having this [issue](https://stackoverflow.com/questions/65627739/can-someone-help-me-to-convert-typescript-code-to-react-code/65627915#65627915)?

**Comment by LudicrousLiam** [comment]
@yashjais18 I am having a similar issue as described here: 

https://github.com/adazzle/react-data-grid/issues/2267

**Comment by amanmahajan7** [comment]
Closing as it is [duplicate issue](https://github.com/adazzle/react-data-grid/issues/2267#issuecomment-762813472)
