### ISSUE TITLE
Not able to type character "1" more than once in all cells for the first time.

### ISSUE THREAD

**Issue by ggkrishkumar** [adazzle/react-data-grid#2271]
Hi Team,

Facing problem when I tried to type/enter character "1" it is not accepting more than once. But if I enter any character other than "1" it accepts. Anyone facing same issue?

https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features

**Comment by nstepien** [comment]
Seems like an issue with the storybook actually, if you open the page without the storybook frame then it works fine:
https://adazzle.github.io/react-data-grid/canary/iframe.html?id=demos--common-features&viewMode=story

**Comment by ggkrishkumar** [comment]
Yay! You are correct. @nstepien.

> Seems like an issue with the storybook actually, if you open the page without the storybook frame then it works fine:
> https://adazzle.github.io/react-data-grid/canary/iframe.html?id=demos--common-features&viewMode=story

**Comment by amanmahajan7** [comment]
Closing as this is a storybook issue.
