### ISSUE TITLE
rowClass is not added to the row

### ISSUE THREAD

**Issue by hatrena** [adazzle/react-data-grid#2280]
Hi, 

I am using `7.0.0-canary.15` and following https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/AllFeatures.tsx#L230 to apply `rowClass`. But rows won't get assigned any class name I set.

Am I missing something here?

**Comment by nstepien** [comment]
`canary.15` doesn't have `rowClass`, you'll need to upgrade.

**Comment by amanmahajan7** [comment]
Please check the changelog for more details
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
