### ISSUE TITLE
Styleissue with Dropdown behavior in editor / editor2

### ISSUE THREAD

**Issue by SO-Eng** [adazzle/react-data-grid#2281]
I allready answered here #2266 , the Popper from MaterialUI is hidden in the new editor in canary.30 what was the editor2 in versions before.

This is the look in editor2 / editor (>=canary.30):

![image](https://user-images.githubusercontent.com/45681404/104739685-4cefa380-5747-11eb-90a2-e1547510535c.png)

and it should look like this in canary.26 with editor:

![image](https://user-images.githubusercontent.com/45681404/104744104-c63dc500-574c-11eb-97df-17b97e73f0df.png)

I need the behavior from the new editor with p.onRwoChange(), with the style from old editor. Or what was the opinion to change this?

**Comment by amanmahajan7** [comment]
Can you check with the latest version of canary and create a codesandbox example?
