### ISSUE TITLE
custom row splash screen

### ISSUE THREAD

**Issue by lynshir** [adazzle/react-data-grid#2287]
demo
https://front-static-files.oss-cn-hangzhou.aliyuncs.com/customer-source/test_bg/2021-01-19%2017.51.54.gif
code
https://adazzle.github.io/react-data-grid/docs/examples/row-renderer

Now this happens when  an image in a row

**Comment by amanmahajan7** [comment]
`rowRenderer` does not support variable height. We recommend upgrading to canary that supports variable height rows
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--variable-row-height
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
