### ISSUE TITLE
React-Data-Grid Custom cell formatter not working properly. How to resolve?

### ISSUE THREAD

**Issue by KhadeerUI** [adazzle/react-data-grid#2291]
React-Data-Grid Custom cell formatter not working properly. How to resolve?

I am using cell data modified with formatter, initial stage(API Axios call) working fine but when I update rows and columns next time not working as expected same as an initial stage. value comes empty in that formatter. How to resolve it? please help me, anyone.

![cell_formatter_not_working](https://user-images.githubusercontent.com/9943610/105368001-11614780-5c27-11eb-8506-8e1fb55eb553.png)
![cell_formatter_working](https://user-images.githubusercontent.com/9943610/105368012-12927480-5c27-11eb-8e79-d0bff3e55dc4.png)

**Comment by Ciph3rzer0** [comment]
No clue, value doesn't work for me at all.  Some of the examples provided didn't work.  Such as this example: https://adazzle.github.io/react-data-grid/docs/examples/cell-formatting

I looked into the story book ([story](https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--all-features), [source](https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/AllFeatures.tsx#L69)), and while the approach is useful in some cases, I imagine 99.9% of the time you just want the key that matches for the column you're on and this process is overkill:
```js
js formatter: ({ row }) => <ImageFormatter value={row.avatar} />
```
So I just calculated the value myself.
```js
function ImageFormatter(props: FormatterProps) {
  const value = props.row[props.column.key];
  return value ? <img src={value}></img> : null;
}
```
Then I don't have to have crazy functions in the column data:
```js
{
  key: 'photoURL',
  name: 'Image',
  width: 40,
  resizable: true,
  formatter: ImageFormatter,
}
```

**Comment by amanmahajan7** [comment]
`value` prop has been canary and we recommend upgrading. 
 https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
