### ISSUE TITLE
Get column key in cellClass method for column 

### ISSUE THREAD

**Issue by varsha-teckchandani** [adazzle/react-data-grid#2292]
I want to highlight a particular cell based on validations but within the cellClass I am only able to get row. Unless I have the column key too or any way to identify which column is it. Note that I am trying to create columns within a for loop.

` for(var index in this.props.data){                    
                                         columns.push({ key: index, name: "blah blah blah", editor: this.props.isReadOnly ? null : DirtyTextEditor, resizable : true,
                                         cellClass(row) { 
                                         console.log(index, row) 
                                         return row.errors[index] ? "background-coral" : "" }})
                                         }
                }`

Also, I can't access "this" within cellClass.

**Comment by varsha-teckchandani** [comment]
I used the column.formatter property instead to achieve the same

**Comment by TonyVeigel** [comment]
How did you do that? row.column.cellClass = "" ? That doesn't seem to work very well.

**Comment by varsha-teckchandani** [comment]
> How did you do that? row.column.cellClass = "" ? That doesn't seem to work very well.

I ended up using formatter property of column instead. "formatter" property gives access to information for column and row both. See https://github.com/adazzle/react-data-grid/blob/0443b5ade6622b3fe573218f59f905fbef1c6c64/stories/demos/AllFeatures.tsx#L76 for reference
