### ISSUE TITLE
All Column Not Show

### ISSUE THREAD

**Issue by njhalaRhudara** [adazzle/react-data-grid#2295]
HI.....

Thanks for Great Tool

I have 30+ column but only show 13 column and also i am  check this demo
[https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--cell-actions](url)  here is same problem

**Comment by TonyVeigel** [comment]
Same here. All the demos don't show all the columns either.

**Comment by nstepien** [comment]
We've published `7.0.0-canary.36` with a fix which should resolve the issue.

**Comment by amanmahajan7** [comment]
https://github.com/adazzle/react-data-grid/pull/2297
