### ISSUE TITLE
Summary row height

### ISSUE THREAD

**Issue by JanBN** [adazzle/react-data-grid#2308]
Hi,

when I set rowHeight 
```
<DataGrid
...
 rowHeight={rowHeight}
....
/>
```

the summary row is also affected by this setting. Is it possible to have different height for summary row ? 

My motivation:
When I have pictures in the grid I want to have a little higher rows so the picture can be seen better. But I do not want to have big summary row.

Thank you

**Comment by amanmahajan7** [comment]
Fixed in 
https://github.com/adazzle/react-data-grid/pull/2325
https://github.com/adazzle/react-data-grid/pull/2335

This is available in canary.38
