### ISSUE TITLE
onSelectedRowChange and rowKeyGetter always return multiple row object

### ISSUE THREAD

**Issue by rakakhrl** [adazzle/react-data-grid#2309]
Hi, I use the version `^7.0.0-canary.36` and use [https://codesandbox.io/s/hungry-maxwell-hlf1h?file=/src/App.js](url) as an example. But the onSelectedRowChange and rowKeyGetter always return multiple row object even when i click only on one row.

This is my simplified code.
```javascript
const ServiceUnitListPage = () => {
  const [selectedRows, setSelectedRows] = useState(() => new Set());

  const columns = [...];

  const rows = [...];

  const PageWrapper = styled.div`
    width: 80vw;
    min-width: 80vw;
  `;

  const rowKeyGetter = (row) => {
    console.log(row.id);
  };

  return (
    <PageWrapper>
      <DataGrid
        style={{ height: "70vh" }}
        selectedRows={selectedRows}
        rowKeyGetter={rowKeyGetter}
        onSelectedRowsChange={setSelectedRows}
        columns={columns}
        rows={rows}
        rowHeight={40}
      />
    </PageWrapper>
  );
};

export default ServiceUnitListPage;
```

**Comment by nstepien** [comment]
I'm not sure I understand what the issue is.
`onSelectedRowChange` does not return "row objects".
`rowKeyGetter` must return a unique row id.
You might also want to define `PageWrapper` outside the component so it's not re-created on each render.

**Comment by amanmahajan7** [comment]
Closing due to lack of response
