### ISSUE TITLE
Cannot edit a column

### ISSUE THREAD

**Issue by Sashkan** [adazzle/react-data-grid#2310]
I simply copy/pasted the basic example from the `examples` page, and made sure to set `editable` to `true` in my column property, but still, double-clicking on the cell does nothing. 

EDIT: A little bit more on this: I was using the old version of the documentation.

I updated my code to match new props, but I still don't understand how to catch the update events.

I've got a column which looks like this:
```
import { TextEditor } from 'react-data-grid'

{
	id: 'name',
	editor: TextEditor,
}
```
I tried using the `onRowsUpdate` prop, but it raises an error, something about an uncontrolled component.

**Comment by andrew-oxenburgh** [comment]
You need the `editable` flag as well

```{
	id: 'name',
	editor: TextEditor,
        editable: true
}```

**Comment by victorvaldez5** [comment]
Adding the `editable` flag didn't do anything for me

**Comment by amanmahajan7** [comment]
Please check the[ editable example](https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/CommonFeatures.tsx#L291) and as it is mentioned earlier, `onRowsChange` is needed for editing

**Comment by TroySK** [comment]
The link is a 404. What worked for me with `7.0.0-beta.16` was adding `textEditor` as the editor for every column I needed edited. It is textEditor and not TextEditor and also no addons package. Eg.
```
import ReactDataGrid, { textEditor } from 'react-data-grid'

const columns = [
  { key: 'segment', name: 'Segment Number', editable: true, editor: textEditor },
  { key: 'alloted_time', name: 'Alloted Time', editable: true, editor: textEditor },
  { key: 'activity', name: 'Activity', editable: true, editor: textEditor },
  { key: 'notes', name: 'Notes', editable: true, editor: textEditor },
  { key: 'public', name: 'public', editable: true, editor: textEditor }
]
```
