### ISSUE TITLE
If the last column is frozen and you resized any column the frozen column floats back to the beginning.

### ISSUE THREAD

**Issue by IAlamro** [adazzle/react-data-grid#2313]
Hi, I'm trying to mark the last column as frozen, but after resizing any column it floats to the beginning and the columns order is being changed, as you mentioned, this issue has been fixed in v7 but I can see it there please check https://github.com/adazzle/react-data-grid/issues/1703 .
Please check the sandbox example for more info.
https://codesandbox.io/s/frozen-column-floats-back-to-the-beginning-9cjzo
Reproducing steps:
1. Resize any resizable column.
2. You will find the last column became the first column (to the left) regardless of the order of the columns.

**Comment by amanmahajan7** [comment]
Can you please check with the lastest canary version?

**Comment by amanmahajan7** [comment]
Can you check with the latest version of canary?
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
