### ISSUE TITLE
SyntaxError in bundle.js

### ISSUE THREAD

**Issue by Hamza-abughazaleh** [adazzle/react-data-grid#2315]
Hi
I'm trying to use data-grid with webpack but I get this error in the bundle file
and the babel-loader is es2015
SyntaxError in bundle.js
```
ERROR in ./node_modules/react-data-grid/lib/bundle.js
Module build failed: SyntaxError: Unexpected token, expected ( (210:10)

  208 |       children: props.row[props.column.key]
  209 |     });
> 210 |   } catch {
      |           ^
  211 |     return null;
  212 |   }
  213 | }
```

**Comment by amanmahajan7** [comment]
Is this still an issue? Please check the installation guide
https://github.com/adazzle/react-data-grid#install

**Comment by amanmahajan7** [comment]
Closing as there is no response
