### ISSUE TITLE
Scrolling from RIGHT to LEFT in REACT grid is not showing the first column

### ISSUE THREAD

**Issue by RamyaSudhakar** [adazzle/react-data-grid#2318]
When we are scrolling from RIGHT to LEFT using keyboard React data grid is not showing the first column.
Check the below example :- 
https://codesandbox.io/s/x393m83l3o?from-embed=&file=/src/index.js

**Comment by victorvaldez5** [comment]
It looks like your first column is ID. The sandbox you linked is correctly showing that column when using the window scrollbar and the keyboard.

Are you maybe referring to setting `frozen: true`? This will lock lock rows when you move right to left

**Comment by RamyaSudhakar** [comment]
No I am not using frozen: true setting. Please refer to the screen shot below 
<img width="956" alt="Scroll" src="https://user-images.githubusercontent.com/23333793/109755974-ff52cb80-7c0c-11eb-9f49-4972fe53ffa7.PNG">

When I am trying to move to RIGHT to LEFT using left arrow key scroll bar is not moving to first column. But with window scrollbar it is working fine problem is with only when we use arrow key

**Comment by rajankapadia** [comment]
@victorvaldez5 : any help on this issue? are this issue is currently planned for fix?

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.
