### ISSUE TITLE
getInitialState / selectedRows: [ ] does not select a row

### ISSUE THREAD

**Issue by txm** [adazzle/react-data-grid#232]
Use the Live JSX Editor in http://adazzle.github.io/react-data-grid/examples.html#/multi-row-select

Edit line:

  getInitialState: function() {
    return {selectedRows: []}
  },

To:

  getInitialState: function() {
    return {selectedRows: [5]}
  },

"0 rows selected" changes correctly to "1 rows selected", however, the Row's checkbox does not get checked.

**Comment by moodysalem** [comment]
@txm the selected rows aren't actually passed to the grid as a property. This is an issue I'm having myself-I can't create a button for example that selects or unselects all rows because the selected rows is not a 'controlled' property

**Comment by malonecj** [comment]
I think we should change this functionality to pass the selectedRows in as props rather than managing them in state, that way you should be able to load initial selected rows, and unselect them as desired.

In the meantime you could get a reference to your ReactDataGrid component and set the state manually like ```this.refs.grid.setState({selectedRows: {[id: 1, isSelected: true}])```

**Comment by moodysalem** [comment]
selectedRows should definitely be a property, not a state variable

IMO, selectedRows should be implemented as an array of row indexes, and onRowSelect should just be called with the selected row index. That way enableRowSelect is just a boolean (no possibility of 'multi'), and the owning component can determine if multiple rows can be selected or not in the onRowSelect handler

**Comment by txm** [comment]
Should I be able to do something like this?  Or have I missed the point ... ?

 42   getInitialState: function(){
 43     //this.refs.grid.setState({selectedRows: [ {id: 1, isSelected: true} ] });
 44     return {
 45       originalRows: this.props.rows.slice(0),
 46       rows: this.props.rows,
 47       height: window.innerHeight-heightOffset,
 48       selectedRows: [ {id: 1, isSelected: true} ],
 49       filters: {}
 50     };
 51   },

**Comment by diogofcunha** [comment]
Fixed in `1.0.19`
