### ISSUE TITLE
Header col-resize cursor broken since v7.0.0-canary.35

### ISSUE THREAD

**Issue by nikiosna** [adazzle/react-data-grid#2320]
The css after element which is responsible to render the col-resize cursor is broken since v7.0.0-canary.35.
https://github.com/adazzle/react-data-grid/blob/canary/src/HeaderCell.tsx#L8
Element should be rendered at pos1 but is "absolute" for every row at the end (pos2)

![test](https://user-images.githubusercontent.com/5426070/109813087-28835400-7c2d-11eb-9533-ce7f1989c569.png)

**Comment by amanmahajan7** [comment]
Can you create a codesandbox example?

**Comment by nikiosna** [comment]
Maybe it's just a problem with a custom style. I fixed it with this css:
```
.rdg-cell[role="columnheader"] {
    position: relative;
}
```
