### ISSUE TITLE
Resizable Rows

### ISSUE THREAD

**Issue by naishe** [adazzle/react-data-grid#2323]
Is there a way to resize the rows the way we do it for the columns? I could not find an example in the documentation or the Storybook or by searching the web.

Here is what I meant by row resize.

![row_resize](https://user-images.githubusercontent.com/845424/109965948-a753bc00-7d15-11eb-9155-8e681ef311b2.gif)

My current project requires me displaying/editing upto 2000 character in a cell, the users may want to expand the rows containing the large text by increasing the row-size appropriately. Any workaround, suggestion, example is welcome.

Thanks for reading. I recently started using this library and I really appreciate the amount of customization I am able to do.

**Comment by amanmahajan7** [comment]
It is currently not supported and this feature is not prioritized yet. We will accept a PR
