### ISSUE TITLE
I can't find the way to scroll to any row

### ISSUE THREAD

**Issue by Gen0106** [adazzle/react-data-grid#2326]
Hi.
I am using react-data-grid version 6.1.0
and I need to scroll to any row on the react data grid
but I can't find the way.
Please let me know it.
Thanks in advance.

**Comment by amanmahajan7** [comment]
`react-data-grid version 6.1.0` is not longer supported. In canary, we can use `gridRef.scrollToRow`
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--scroll-to-row

**Comment by amanmahajan7** [comment]
https://github.com/adazzle/react-data-grid/blob/main/packages/react-data-grid/src/ReactDataGrid.js#L134 can probably be used
