### ISSUE TITLE
how to focus a cell

### ISSUE THREAD

**Issue by Gen0106** [adazzle/react-data-grid#2327]
Hi. I am using react-data-grid version 6.1.0
I need to focus on a cell programmatically but I have no idea
I already used grid.setState({selected: {rowIdx: row, idx: col} }) but doesn't work
please help me
Thanks

**Comment by amanmahajan7** [comment]
`react-data-grid version 6.1.0` is no longer supported and we recommend upgrading to v7 canary. In canary `gridRef.selectCell` method can be used.
