### ISSUE TITLE
Header Cell doesn't move with input box when user uses TAB button to navigate towards right

### ISSUE THREAD

**Issue by Shubham-DK** [adazzle/react-data-grid#2330]
While using filtering feature in grid, if user types in one of the search box and then uses TAB to navigate to next input search box, the header of the column doesn't move with input box, which creates confusion.

This issue happens when the number of column is huge and some of them is not visible . means horizontal scroll bar is present

![image](https://user-images.githubusercontent.com/58040775/110925395-231ebb80-8349-11eb-87fd-cecdec069fd5.png)

**Comment by amanmahajan7** [comment]
`react-data-grid v6` and we recommend upgrading to the latest canary version. It is a complete re-write does not have all the old bugs 
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--header-filters
