### ISSUE TITLE
replaceAll is only available on Node.js v15

### ISSUE THREAD

**Issue by phamhieu** [adazzle/react-data-grid#2331]
When building `react-data-grid` on machine with node.js version older than v15. It will throw error:
```
[!] (plugin linaria) Error: ../react-data-grid/src/Cell.tsx: 
classNameSlug option must return a string
```

[replaceAll is available from node.js v15](https://nodejs.org/en/blog/release/v15.0.0/#v8-8-6-35415)

Need to update `rollup.config.js` to fix the error.
```
// From: 
return `${hash}${pkg.version.replaceAll('.', '')}`;

// To: 
return `${hash}${pkg.version.replace('.', '')}`;
```

**Comment by nstepien** [comment]
For development we'll keep requiring the `current` version of Node.js, as it's an extra maintenance burden otherwise.
We'll update the `CONTRIBUTING.md` guide eventually to mention this.
