### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by ojnc** [adazzle/react-data-grid#2332]
There is a need for column chooser using check boxes

Ref issue https://github.com/adazzle/react-data-grid/issues/917

This is a working demo of column choosing using checkboxes

[https://drive.google.com/file/d/13esqen5Df_Hv8qT9nZWhpOTG3XZaWUuy/view?usp=sharing](url)

If OK you may consider including it in https://adazzle.github.io/react-data-grid/docs/examples

**Comment by nstepien** [comment]
Closing in favor of #2575
