### ISSUE TITLE
Up/Down arrows for sorting not removed after row update.

### ISSUE THREAD

**Issue by aziz1234** [adazzle/react-data-grid#2336]
Hi,

So for the initial data in the grid the functionality works perfectly fine but when the row data is updated then the arrow in the header still remains. 

Eg if I click on column 1 and data is sorted in descending order then suppose the data is updated after an API call back then the column 1 will still have the down arrow with data not sorted so either the data should be sorted or at least the arrow should be removed. 

Thanks,
Aziz.

**Comment by amanmahajan7** [comment]
Sorting is controlled outside the grid so these props can be reset when needed
```
sortColumn,
sortDirection
```

Check the example on how to implement sorting
https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/CommonFeatures.tsx#L281
