### ISSUE TITLE
onGridRowsUpdated send different data between key press vs mouse click

### ISSUE THREAD

**Issue by Allenskywalker92** [adazzle/react-data-grid#2340]
I'm using "react-data-grid": "^6.1.0". 
When I edit a cell and focus out using a mouse click, the data I received in onGridRowsUpdated is the target cell which is not correct. 
If I use a keypress, it works perfectly.

**Comment by amanmahajan7** [comment]
`react-data-grid": "^6.1.0` is no longer supported. We recommend upgraded to v7 canary
