### ISSUE TITLE
Possible typo?

### ISSUE THREAD

**Issue by chrmcg** [adazzle/react-data-grid#2341]
https://github.com/adazzle/react-data-grid/blob/canary/src/HeaderCell.tsx#L81

```
function onPointerUp() {
      if (event.pointerId !== pointerId) return;
```

Since there's no `event` parameter on this function, the `event` variable gets inherited from the outer scope:
```function onPointerDown(event: React.PointerEvent<HTMLDivElement>)```

But that's also where `pointerId` is destructured from, so `event.pointerId` should always equal `pointerId`.

Is this a typo? Or a behavior I'm not aware of where `event.pointerId` can change between the down event and the up event?

**Comment by amanmahajan7** [comment]
Fixed in https://github.com/adazzle/react-data-grid/pull/2371. Thanks for reporting!
