### ISSUE TITLE
onRowDoubleClick doesn't exist

### ISSUE THREAD

**Issue by mohkale** [adazzle/react-data-grid#2344]
There seems to have been a few issues a while back about adding this (#159) and it looks like it was actually added (#1025) but I can't find it in the code base now. Was it removed and is there any intention to re-introduce it?

**Comment by ankit--sethi** [comment]
My guess is since double-click is connected with editing a cell, what you want to do can be accomplished by creating a `CustomEditor` for the columns of interest, and implementing the action inside that.

**Comment by mohkale** [comment]
Could you share a demo? There's also a few of them in previous issues but they don't seem compatible with the current version.
