### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by pvilalta** [adazzle/react-data-grid#2345]
Hello everyone,

I'm trying to handle react-data-grid, but I can't manage to start.

At the beginning I had the "react/jsx-runtime" issue, resolved by this [ticket](https://github.com/adazzle/react-data-grid/issues/2230)

Now, I get this error 

```
./src/web/components/ResumesTable/index.js
Error: ENOENT: no such file or directory, scandir '/Users/x2cheese/Desktop/dev/darejs/koopt/node_modules/react-data-grid/lib'
```

In fact, my node_modules file is empty of react-data-grid folder.

Any idea ?

Thanks in advance,

Paul

**Comment by nstepien** [comment]
>In fact, my node_modules file is empty of react-data-grid folder.

Sounds like an npm/yarn issue rather than react-data-grid.
I'd suggest clearing the `npm` cache and reinstalling.
