### ISSUE TITLE
How can I completely override the CSS?

### ISSUE THREAD

**Issue by ankit--sethi** [adazzle/react-data-grid#2346]
I would like to replace the default look and feel of `DataGrid` to something close to Material UI's `DataGrid`. Is there any way to override the linaria css stuff at a granular level?

**Comment by amanmahajan7** [comment]
You can use a `className` on the grid and each grid component has classes that can be overridden, for example
```
rdg-cell,
rdg-row
etc
```
Please check the [styles ](https://github.com/adazzle/react-data-grid/tree/canary/src/style)for more info
