### ISSUE TITLE
Please allow to add customer sort item

### ISSUE THREAD

**Issue by windatang** [adazzle/react-data-grid#2347]
please add a props or class name allow to use the customer icon

**Comment by windatang** [comment]
/**
.rdg-header-sort-cell {
      .rdg-header-sort-name + span{
        display: none;
      }
      .rdg-header-sort-name {
        .sort-icon svg{
          display: inline-block;
          transform-origin:center;
        }
        .DESC svg{
          transform: rotate(0deg) translateX(-3px) scale(1.2);
        }
        .ASC svg{
          transform: rotate(180deg) translateX(-3px) scale(1.2);
        }
        .NONE svg{
          transform: rotate(90deg) translateX(-3px) scale(1.2);
        }
        
      }
**/
export interface LoopringTBHeaderProps<R> extends HeaderRendererProps<R>   {
  // onColumnsReorder: (sourceKey: string, targetKey: string) => void;
}

export function DirectionIconHeader<R>({ sortDirection,sortColumn,onSort,column,...props }: HeaderRendererProps<R>) {
  function getCell() {
    if (column.sortable) {
      return (
          <SortableHeaderCell
              {...{props}}
              column={column}
              sortColumn={sortColumn}
              onSort={onSort}
              sortDirection={sortDirection}
          >
            {column.name}  <span className={`sort-icon ${sortColumn === column.key ? sortDirection : 'NONE'}`}><DropDownIcon/></span>
          </SortableHeaderCell>
      );
    }

    return column.name;
  }
  return <>{getCell()}</>;
}
/***
....
 const  customerColumns= React.useMemo(() => {
        function HeaderRenderer(props: LoopringTBHeaderProps<R>) {
            console.log(props)
            return <DirectionIconHeader {...props}  />;
        }
        return columns.map(c => {
            //if (c.key === 'id') return c;
            return { ...c, headerRenderer: HeaderRenderer };
        });
    }, [columns]);

    return (
            <DataGrid

                columns={customerColumns}
                

                .../>
 ***/               
`

**Comment by amanmahajan7** [comment]
It can be achieved using a custom `headerRenderer` and `SortableHeaderCell`. Check the following `headerRenderer`
https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/components/HeaderRenderers/DraggableHeaderRenderer.tsx#L46
