### ISSUE TITLE
Add `Select all` checkbox in the selection column header

### ISSUE THREAD

**Issue by kgunbin** [adazzle/react-data-grid#235]
Is it possible to have 'Select all' functionality on the table?

**Comment by jpdriver** [comment]
hey @kgunbin -- we should have a checkbox in the header row but it looks like it's stopped working.. i'll have a look now because i need it for a feature :smile:

**Comment by jpdriver** [comment]
@kgunbin just opened a PR to fix. thanks for flagging it! :smile:

**Comment by kgunbin** [comment]
Great, thank you!

**Comment by jpdriver** [comment]
@kgunbin that's been both merged into `master` and published on npm now. update to v0.14.15 :smile:
