### ISSUE TITLE
Cannot delete input content in NumericFilter

### ISSUE THREAD

**Issue by neotan** [adazzle/react-data-grid#2352]
**Describe the bug**
In NumericFilter, cannot delete (by pressing the Backspace or Delete button) input content.

**Current behavior**
In NumericFilter, cannot delete (by pressing the Backspace or Delete button) input content.

**Expected behavior**
In NumericFilter, can delete (by pressing the Backspace or Delete button) input content.

**Environment**
- `standard-version` version(s): Canary
- Node/npm version: v14.15.3
- OS: Windows 1

**Possible Solution**
Allow Backspace and Delete's behaviors.

**Additional context**
Example: https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--header-filters

![3814f5f7-de79-41fe-80aa-f799ad6e4a52](https://user-images.githubusercontent.com/10399087/113880472-17120680-97ee-11eb-83d2-5a595e1a430f.gif)

**Comment by amanmahajan7** [comment]
We have removed `NumericFilter` example and I would recommend [copying the code](https://github.com/adazzle/react-data-grid/blob/2f6181d9234fd81ea2f4ad15b1145e4b2cdf08ab/stories/demos/components/Filters/NumericFilter.tsx) and tweaking it as needed.
