### ISSUE TITLE
ReactJs - MaterialTable pagination, row per page not working

### ISSUE THREAD

**Issue by JayDee02** [adazzle/react-data-grid#2359]
I'm currently using [Material-table](https://material-table.com) . It displays data normally however, Pagination and Row per Page dropdown is not working. Nothing happens upon clicking, next button and selected number of rows.

See below codes:
`import MaterialTable from 'material-table'

const tableIcons = {
 /*table icons*/
}

function Test(){
  const [data, setData] = useState([]);
  
  const getDatas = async() => {
    await axios.get('/API')
    .then(response => {
      setData(response.data)
    }
  }

const columns = [
  {.....} //columns
]

return(
  <div>
    <MaterialTable
      icons = {tableIcons}
      columns = {columns}
      data = {data}
      title = 'List of data'
      actions = {[{
        //add button properties
      }]}
    >
    </MaterialTable>
  </div>
)

}
export default Test;`

I'm getting the following error on console upon onload and clicking pagination buttons.

On load:
![Capture](https://user-images.githubusercontent.com/82564548/114820140-1f230500-9df1-11eb-91b3-cf35187fa9cb.PNG)

On click of next button
![Capture1](https://user-images.githubusercontent.com/82564548/114820180-2fd37b00-9df1-11eb-9ca9-702edd72c34e.PNG)

Please help me with this. Thank you in advance.
Apologies for the format, I'm new here.

**Comment by amanmahajan7** [comment]
This issue is posted on the wrong repo. You probably need https://github.com/mbrn/material-table
