### ISSUE TITLE
[Need Help] ReactDataGrid | Inline edit functionality of ReactDataGrid is not working on Tab page

### ISSUE THREAD

**Issue by priyankalxi** [adazzle/react-data-grid#2376]
**Current Behavior:**
I have created sample page in react js to implement **inline edit** functionality as per given example on "https://adazzle.github.io/react-data-grid/docs/examples/default-editor" and it is working but same page if I am calling on Tab control then inline edit functionality is not working.
I am using NavPills Tab control and this page will be a one **tabcontent** in my application.
In my sample page I am able to select cell and and edit it but when I do the same in tab page then it is not selecting cell and if I press characters then it is taking only one character for cell edit. Please refer attached **screenshot** over here.

**Expected Behavior:**
Inline edit should work on tab control or tab pages also

**Environment:**
I am using "react-data-grid": "^6.1.0"

**Working screenshot**
![image](https://user-images.githubusercontent.com/82876278/115956676-d0294e00-a51b-11eb-8d0c-b968537f2961.png)

Not working on tab page. Only one character is updated in below screenshot and not able to select cell on double click
![image](https://user-images.githubusercontent.com/82876278/115956707-f949de80-a51b-11eb-9b03-bbc3d6cf9ad1.png)

VS code and node js version
![image](https://user-images.githubusercontent.com/82876278/115956719-08c92780-a51c-11eb-9a1f-cd189bee4961.png)

**Comment by priyankalxi** [comment]
Can anyone help on this?

**Comment by amanmahajan7** [comment]
React data grid v6 is no longer supported we recommend upgrading to canary 
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
