### ISSUE TITLE
Disable Tab Key On Grid

### ISSUE THREAD

**Issue by blessonabrahamah** [adazzle/react-data-grid#2377]
We are using react-data-grid v6.1.0  and we have a requirement to disable tab key on grid.

Tried making changes directly to library like this https://github.com/blessonabrahamah/react-data-grid/commit/2dd2b10c35cae93eeb836a09fa63bc2f31d09409

Just wanted to know, if its the right approach and do we have any other solution?

**Comment by amanmahajan7** [comment]
Fixed in https://github.com/adazzle/react-data-grid/pull/2833
