### ISSUE TITLE
react-data-grid/addon is not working with react-data grid.

### ISSUE THREAD

**Issue by priyankalxi** [adazzle/react-data-grid#2378]
If I import react-data-grid-addons as

**import { Editors } from "react-data-grid-addons";**

I am getting below error at compile time -

**./node_modules/react-data-grid-addons/lib/draggable/DraggableHeaderCell.js
Attempted import error: 'DragItemTypes' is not exported from 'react-data-grid'.**

Can anyone help on this?
or please let me know how to add check box, dropdown into react data grid cells.

**Comment by amanmahajan7** [comment]
`react-data-grid-addons` has been removed and no longer supported. We recommend migrating to canary 

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos

**Comment by priyankalxi** [comment]
Thank you for response. Is this released version of canary? I mean is it trial version or released version?
Can we use it like react-data-grid. I am using React Data Grid from "https://adazzle.github.io/react-data-grid/ "  
I am using "react-data-grid": "^6.1.0" so should I install canary to replace it. Please guide.

I wanted to use grid with following functionality 
- cells having dropdown editor, checkbox etc
- inline edit
- sorting
- paging
- filtering
- column resizing
- copy paste row
