### ISSUE TITLE
Programmatic selection of cells?

### ISSUE THREAD

**Issue by meet-rs-api** [adazzle/react-data-grid#2382]
I have a use case where after a user completes entering the data I need to send focus to the next cell or to make it more abstract is there a way to do something like

`
grid.selectCell(rowIndex, colIndex);
`

**Comment by amanmahajan7** [comment]
https://github.com/adazzle/react-data-grid/blob/canary/src/DataGrid.tsx#L384 can be used
```
gridRef.selectCell
SelectCellFn = (position: Position, enableEditor?: boolean | null) => void;
```

**Comment by kunal886496** [comment]
Hi @amanmahajan7 ,

I am obliged to work on this tool you made.
Really thankful.

One bug which i am facing is 

dataGridRef.current.selectCell({ idx:1,rowIdx:location.rowIdx } ,true) 

is not opening the cell, instead it is just highlighting or focusing on the position.

Is this a known bug ?

Help will be appreciated.

Thanks in advance.
