### ISSUE TITLE
Avoid grid rerender on same cell click multiple times

### ISSUE THREAD

**Issue by mkirithika** [adazzle/react-data-grid#2388]
When the same cell is clicked again and again, the selected position state is getting update and which causes grid to get rerendered on each click. To avoid this a condition can be checked like this 

`function selectCell(position, enableEditor = false) {
    if (!isCellWithinBounds(position)) return;
    commitEditorChanges();

    if (enableEditor && isCellEditable(position)) {
      const row = rows[position.rowIdx];
      setSelectedPosition({ ...position,
        mode: 'EDIT',
        key: null,
        row,
        originalRow: row
      });
    } else if (position.idx !== selectedPosition.idx || position.rowIdx !== selectedPosition.rowIdx || selectedPosition.mode !== 'SELECT') {
      setSelectedPosition({ ...position,
        mode: 'SELECT'
      });
    }

    onSelectedCellChange == null ? void 0 : onSelectedCellChange({ ...position
    });
  }`

Please check the else if condition. Let me know your thoughts

**Comment by Kannndev** [comment]
Is there an update on this. I am also facing an similar issue, @amanmahajan7
