### ISSUE TITLE
I need to use To data grids in same page  React Dnd issue

### ISSUE THREAD

**Issue by itsmeganesh-cse-iiit** [adazzle/react-data-grid#2391]
issue : React DnD - “Cannot have two HTML5 backends at the same time.”

Please suggest me to solve this issue

**Comment by amanmahajan7** [comment]
Old versions of rdg are no longer supported and we recommend upgrading. This is no longer an issue with canary as the dependency has been removed 

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
