### ISSUE TITLE
React data grid v5.04 color editor slider unselectable  

### ISSUE THREAD

**Issue by wpsaputra** [adazzle/react-data-grid#2396]
![Color-slider](https://user-images.githubusercontent.com/29251295/118061876-6688bb00-b3c8-11eb-94c1-0b3d86010b66.png)
In React data grid v5.04 color editor slider is unselectable . After clicking the slider, the dialog is closed

**Comment by wpsaputra** [comment]
![react-datepicker](https://user-images.githubusercontent.com/29251295/118062173-f9c1f080-b3c8-11eb-8914-b68b340f0eda.png)
This issue also happened with Year Dropdown in react-datepicker (other button except year dropdown work as expected), any solution?
`<DatePicker value={this.state.color} onChange={this.onChange} showYearDropdown={true} />`

**Comment by peasonokay** [comment]
@wpsaputra Any reason why you are passing {this.state.color} to a date control? Also can you share your onChange event - this should contain a callback to commit your change. Something like the following:
this.setState({dateTime: selectedDate}, () => this.props.onCommit);

**Comment by wpsaputra** [comment]
My bad, I just edited color editor example and change it to date use react-datepicker but to lazy to change the variable name (just give a quick try for react-data grid).. the state is indeed use new Date() despite the name.. Everything work as expected until I use showYearDropdown={true}.. As showed in image above, the red box is unselectable like color picker slider (other button is working though).

**Comment by wpsaputra** [comment]
@peasonokay could you give it a quick try for react-datepicker "showYearDropdown={true}". I already use this.setState({dateTime: selectedDate}, () => this.props.onCommit); in the past but the year dropdown not showing when clicked

**Comment by wpsaputra** [comment]
For someone that have problem with year dropdown from react-datepicker with React data grid v5.04 maybe https://projects.wojtekmaj.pl/react-date-picker/ can be a good alternative, tried it and work well for me..

**Comment by amanmahajan7** [comment]
react-data-grid v5 is no longer supported we recommend upgrading to canary 

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
