### ISSUE TITLE
Unfilterable columns get duplicate Header Cells instead of inputs

### ISSUE THREAD

**Issue by jpdriver** [adazzle/react-data-grid#240]
after removing `filterable: true` from the Id column on the example..

![image](https://cloud.githubusercontent.com/assets/2393035/13527124/c0884904-e204-11e5-9298-353f540ed172.png)

**Comment by diogofcunha** [comment]
This was fixed a long time ago, will milestone it as 1.0.23 as it implements a new filter behaviour
