### ISSUE TITLE
Change column editor based on row content: Cannot enable SImpleTextEditor

### ISSUE THREAD

**Issue by peasonokay** [adazzle/react-data-grid#2408]
Hi all , I am dealing with row data that can be very long so i have implemented two DataGrids - a viewer and an editor.
in the viewer Ive added a glyphicon for user edit click which opens the editor. This transforms the rowdata into column data.
Now whenever a timestamp or datetime field is encountered i want to display a calender control which i have working but for other fields i want the simpleTextEditor to be used. Ive tried to implement the below in my column definitions field but am getting SimpleTextEditor is undefined. CustomEditors is my working implementation of a custom calander entry. Ive also tried moving the SimpleTextEditor into the CustomEditors class and returning the SimpleTextEditor there in my render and have the same issue. I dont get any compilation error in the import statement. NB I also tried importing EditorBase and still have the same issue. Hence need help on how to implement the SimpleTextEditor manually in the column definitions

**import SimpleTextEditor from "react-data-grid";**

let EDIT_GRID_COLS= [
    { name : "column_name",
        key : "column_name",
        editable: false,
        width: 200},
    {name : "column_value_before",
        key : "column_value_before",
        editable: false },
    {name : "column_value_after",
        key : "column_value_after",
        editable: true,
        editor: function(rowData) {
            let editor=rowData && rowData.rowData["column_name"].endsWith("_ts") ? CustomEditors: SimpleTextEditor;
            return editor;
        }

**Comment by peasonokay** [comment]
sorry i should have clarified i am using V6 - V7 seems to unstable at the moment

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.
