### ISSUE TITLE
rowClass is not a function | ^7.0.0-canary.47

### ISSUE THREAD

**Issue by masbaehr** [adazzle/react-data-grid#2411]
Getting this error lately. Any idea?

![image](https://user-images.githubusercontent.com/38694044/118684943-f2547a00-b802-11eb-9430-90d48041e465.png)

**Comment by nstepien** [comment]
What's the value of the `rowClass` prop you're passing to `<DataGrid />`?

**Comment by masbaehr** [comment]
Just a regular string which is defined in a plain CSS:      rowClass="myClass123"

Is this ok or should it be used differently?

this is what it seems to expect: 

rowClass?: ((row: R) => string | undefined | null) | null;

**Comment by nstepien** [comment]
Yeah right now `rowClass` is used to set `className` specific to each rows.
If you want to apply a style to all rows, I'd suggest instead to set a `className` on the data grid itself, like so:
```tsx
<DataGrid className="myClass123" />
```
then in css:
```css
.myClass123 .rdg-row {
  // ...
}
```

**Comment by masbaehr** [comment]
Ah ok thanks that is a viable solution for now, and assuming i want to use rowClass correctly how would that be done? :) Thanks again

**Comment by nstepien** [comment]
If you really want to use `rowClass` then create a static function that returns the class name, i.e.
```tsx
function rowClass() { return 'myClass123'; }

function MyGrid() {
  return <DataGrid {...props} rowClass={rowClass} />;
}
```
We could add support for strings directly to `rowClass`, it's just overkill to apply the same class name to all rows when 1 class name on the root is enough. 🤔

**Comment by masbaehr** [comment]
ah okay no it was just for simplicity, i was trying to set the string by using a too simple expression. Now i've done something like that and it works fine :) 

```
   rowClass={row => {
                  var colorclass = "defaultRow";
                  if(row.type === "XXXX"){
                    colorclass = "blueRow";
                  }
                  return colorclass ;
                }}
```

**Comment by nstepien** [comment]
If possible, I'd suggest keeping the function static, or "memoized" via `useCallback` for example, to avoid some row re-renders.
