### ISSUE TITLE
Select All rows header checkbox (for multi-row select) gets duplicated when trying to apply filters

### ISSUE THREAD

**Issue by jpdriver** [adazzle/react-data-grid#242]
after adding `enableRowSelect='multi'` to the props we pass to grid on the Filterable example..

![image](https://cloud.githubusercontent.com/assets/2393035/13577188/1ecaf576-e489-11e5-84c3-9d19cf4be621.png)

**Comment by ppiekarczyk** [comment]
+1

**Comment by txm** [comment]
afaik this has been fixed?

**Comment by txm** [comment]
+2

**Comment by diogofcunha** [comment]
Was Fixed in `0.14.28`
