### ISSUE TITLE
Click Handler

### ISSUE THREAD

**Issue by vedran-maestral** [adazzle/react-data-grid#244]
Is there a event handler on Row click?

**Comment by jpdriver** [comment]
hey @vedran-maestral -- we don't have anything built-in for this but you can handle row clicks outside of the grid by using a custom row renderer with an `onClick` event.

for example, go to http://adazzle.github.io/react-data-grid/examples.html#/custom-row-renderer and do something like
```
var RowRenderer = React.createClass({
 render: function() {
   return (<div style={this.getRowStyle()} onClick={console.log(e)}><ReactDataGrid.Row ref="row" {...this.props}/></div>)
 }
});

var Example = React.createClass({
  render: function() {
    return  (<ReactDataGrid
    columns={columns}
    rowGetter={rowGetter}
    rowsCount={_rows.length}
    minHeight={500}
    rowRenderer={RowRenderer}/>);
  }
});
```

**Comment by txm** [comment]
I'm after a columnClick, or even cellClick, I've tried the following:

let MatrixDetailed = React.createClass({

  onCellSelect: function (cell) {
    console.error({ rowIdx: cell.rowIdx, idx: cell.idx, a: 3 });
  },
  onCellClick: function (cell) {
    console.error({ rowIdx: cell.rowIdx, idx: cell.idx, a: 2 });
  },
  onSelect: function (cell) {
    console.error({ rowIdx: cell.rowIdx, idx: cell.idx, a: 1 });
  },
  handleRowSelect: function (cell) {
    console.error({ rowIdx: cell.rowIdx, idx: cell.idx, a: 4 });
  },

I guess I'm missing something fundamental as my next task is to save User Edits.

**Comment by jpdriver** [comment]
hey @txm -- what props are you passing to your grid? do you have `enableCellSelect={true}`?

**Comment by txm** [comment]
Hello!  Yes, I am. TIA.

let MatrixDetailed = React.createClass({
  propTypes: {
  },
  getInitialState: function(){
    return {
      originalRows: this.props.rows.slice(0),
      rows: this.props.rows,
      height: window.innerHeight-heightOffset,
      filters: {}
    };
  },
  rowGetter: function(rowIdx){
    return this.state.rows[rowIdx]
  },
  getSize: function() {
    return this.state.rows.length;
  },
  handleRowUpdated : function(e){
    let rows = this.state.rows;
    Object.assign(rows[e.rowIdx], e.updated);
    this.setState({rows:rows});
  },
  handleResize: function(e) {
    this.setState({height: window.innerHeight-heightOffset});
  },
  componentDidMount: function() {
    window.addEventListener('resize', this.handleResize);
  },
  componentWillUnmount: function() {
    window.removeEventListener('resize', this.handleResize);
  },
  handleGridSort: function() {
    //
  },
  onCellSelect: function (cell) {
    console.error({ rowIdx: cell.rowIdx, idx: cell.idx, a: 3 });
    //this.onSelect({ rowIdx: cell.rowIdx, idx: cell.idx });
  },
  onCellClick: function (cell) {
    console.error({ rowIdx: cell.rowIdx, idx: cell.idx, a: 2 });
    //this.onSelect({ rowIdx: cell.rowIdx, idx: cell.idx });
  },
  onSelect: function (cell) {
    console.error({ rowIdx: cell.rowIdx, idx: cell.idx, a: 1 });
    //this.onSelect({ rowIdx: cell.rowIdx, idx: cell.idx });
  },
  handleRowSelect: function (cell) {
    console.error({ rowIdx: cell.rowIdx, idx: cell.idx, a: 4 });
    //this.onSelect({ rowIdx: cell.rowIdx, idx: cell.idx });
  },
/*
  onRowSelect: function(rows) {
    this.setState({selectedRows: rows});
  },
*/
  filterRows : function(originalRows, filters) {
    let rows2 = originalRows.filter(function(r){
      let include = true;
      for (let columnKey in filters) {
        if(filters.hasOwnProperty(columnKey)) {
          let rowValue = r[columnKey].toString().toLowerCase();
          if(rowValue.indexOf(filters[columnKey].toLowerCase()) === -1) {
            include = false;
          }
        }
      }
      return include;
    });
    return rows2;
  },
  handleFilterChange : function(filter){
    this.setState(function(currentState) {
      if (filter.filterTerm) {
        currentState.filters[filter.columnKey] = filter.filterTerm;
      } else {
        delete currentState.filters[filter.columnKey];
      }
      currentState.rows = this.filterRows(currentState.originalRows, currentState.filters);
      return currentState;
    });
  },
  render: function() {
    return (
      <div className="testpro-main-container">
        <ReactDataGrid
          rowKey='CNFG_ID'
          onGridSort={this.handleGridSort}
onCellSelect={this.onCellSelect}
onRowSelect={this.onRowSelect}
onRowClick={this.onRowClick}
handleRowSelect={this.handleRowSelect}
onSelect={this.onSelect}
onCellClick={this.onCellClick}
          enableCellSelect={true}
          rowsCount={this.state.rows.length}
          columns={this.props.columns}
          rowGetter={this.rowGetter}
          minHeight={this.state.height}
          emptyRowsView={EmptyRowsView}
          onRowUpdated={this.handleRowUpdated}
          onAddFilter={this.handleFilterChange}
          rowRenderer={RowRenderer}
        />
        <InfoContainer />
        <ToggleMatrixViewContainer />
      </div>
    );
  }

**Comment by jason-henriksen** [comment]
This is pretty damn silly.   I'm handling my own state.  All I want to know is what cell was clicked.
I do NOT want to know what row is selected!  Because I get the event the first time I click the cell (selection event) but when I click again, I don't get the event a second time, because the row is already selected.

I've got an onRowClick, but no way to specify an onCellClick?    throw new WTFException();

Here is the inconceivably hacky way I had to work around this:
In my row getter I have to pass 'valueNeeded.rowIndex'
Then in my row formatter, I have to split the value on the dot.  Display the value I want in the formatted data, but also add an onClick handler that is passed to the row.    Then I have to have a separate onClick handler for each column.   

react-data-grid is by far the best of the data grids available on github.  
But this is a woeful oversight.  Please fix it, ASAP.

**Comment by pavinduLakshan** [comment]
To know more about custom row renderers, check here: https://adazzle.github.io/react-data-grid/docs/examples/row-renderer   
( The above mentioned link is broken )

**Comment by ved-systango** [comment]
> This is pretty damn silly. I'm handling my own state. All I want to know is what cell was clicked. I do NOT want to know what row is selected! Because I get the event the first time I click the cell (selection event) but when I click again, I don't get the event a second time, because the row is already selected.
> 
> I've got an onRowClick, but no way to specify an onCellClick? throw new WTFException();
> 
> Here is the inconceivably hacky way I had to work around this: In my row getter I have to pass 'valueNeeded.rowIndex' Then in my row formatter, I have to split the value on the dot. Display the value I want in the formatted data, but also add an onClick handler that is passed to the row. Then I have to have a separate onClick handler for each column.
> 
> react-data-grid is by far the best of the data grids available on github. But this is a woeful oversight. Please fix it, ASAP.

can you share your approach
