### ISSUE TITLE
Bug: Scroll-Y table with  No background  header, header and row Overlap。

### ISSUE THREAD

**Issue by windatang** [adazzle/react-data-grid#2442]
<img width="3594" alt="WeChat4d250a4c91a89412af14a3eb1b22da2e" src="https://user-images.githubusercontent.com/1582816/120268130-d909fe00-c2d7-11eb-9aab-c935480eecd0.png">

**Comment by nstepien** [comment]
What browser and browser version are you using?

**Comment by windatang** [comment]
I used the chrome, the reproduce way is deleted header row css background color in your storybook demo

**Comment by nstepien** [comment]
It works fine here, can you make sure your browser is up to date?

![image](https://user-images.githubusercontent.com/567105/120459560-32356880-c390-11eb-8d4f-8f5a7cc2e1df.png)

![image](https://user-images.githubusercontent.com/567105/120459516-2ba6f100-c390-11eb-9d30-8a8dbdba2506.png)

**Comment by windatang** [comment]
Our productor have a special whole page background design, the totally table should be transparent. but when header background set as  transparent, the content info will overlap.      
![1623030894708](https://user-images.githubusercontent.com/1582816/120949365-ef500800-c776-11eb-82d4-72f2c40dc7b6.jpg)

**Comment by nstepien** [comment]
Rows and cells are rendered under the header, that's not gonna change.
Best thing I can suggest is to set the background color to match the background of your page.
