### ISSUE TITLE
Cell rendering optimisation upon scrolling.

### ISSUE THREAD

**Issue by crashnick16** [adazzle/react-data-grid#2443]
I am having a rather feature rich grid to build whereby we require complex cells to be rendered resulting in a very slow scrolling experience as it appears the grid is destroying rows and then cells once they are scrolled out of view which causes custom react components to unmount and then mount again.

Now that begs the question: when custom renderers are used as react components why do we need to destroy the row and cells by mounting / unmounting them, could we just not really on REACT props to at the cell component level to figure out if the cell needs to be redrawn or not? 

In a lot of the cases, you may have repeating data between the rows, hence you would like to avoid redrawing in that scenario. would this be possible with this grid?

**Comment by nstepien** [comment]
Are you suggesting that, instead of unmounting rows we should "recycle" them?
i.e. right now we render row `1, 2, 3`, then you scroll and we render row `2, 3, 4`, and what you suggest is we reuse row `1` to render row `4`?

**Comment by crashnick16** [comment]
exactly, I feel that by doing that we could squeeze quite a bit of performance for repeating data, in a lot of the cases that would be the case and the win will be huge for complex cell display.

**Comment by crashnick16** [comment]
> Are you suggesting that, instead of unmounting rows we should "recycle" them?
> i.e. right now we render row `1, 2, 3`, then you scroll and we render row `2, 3, 4`, and what you suggest is we reuse row `1` to render row `4`?

exactly, I feel that by doing that we could squeeze quite a bit of performance for repeating data, in a lot of the cases that would be the case and the win will be huge for complex cell display.

**Comment by nstepien** [comment]
I've opened #2455 to test this out, it looks like it can work. Feel free to clone the repo, checkout the branch, then try it out locally with `npm i` + `npm start`.

**Comment by amanmahajan7** [comment]
@crashnick16 can you confirm the rdg version you are using?

**Comment by crashnick16** [comment]
> I've opened #2455 to test this out, it looks like it can work. Feel free to clone the repo, checkout the branch, then try it out locally with `npm i` + `npm start`.

briliant, i will take a look!

**Comment by crashnick16** [comment]
> @crashnick16 can you confirm the rdg version you are using?

I am trying things out on the latest canary version as I am considering to upgrade soon.

**Comment by ChengranYan** [comment]
> I've opened #2455 to test this out, it looks like it can work. Feel free to clone the repo, checkout the branch, then try it out locally with `npm i` + `npm start`.

I think the reason why this problem is difficult to solve is the concept of windowing。rdg use useViewportRows by default to calculate the viewport rows to display, but this behavior should be configurable,  It should only happen in when there is a large amount of data。

In this case， it can be ignored the viewport rows or use pagination is better。

**Comment by crashnick16** [comment]
I've done some testing but I cannot see a massive improvement in terms of rendering times. Will give it another go once I come up with a better test.

**Comment by nstepien** [comment]
@ChengranYan You can set `enableVirtualization={false}` to disable virtualization.

@crashnick16 try reverting this commit: https://github.com/adazzle/react-data-grid/pull/2455/commits/7103ee90bb4dc9c9e6659c24f778025eac3f5dc4

**Comment by nstepien** [comment]
I don't think we'll go with this idea.
It has drawbacks like a focused element staying unexpectedly focused as you scroll through the grid.
If you sort the rows it'll re-render all of the as well.
Dynamic row heights also means we can un/mount rows as we scroll.
