### ISSUE TITLE
Export CSV for Tree View is not working properly

### ISSUE THREAD

**Issue by akash-intellemo** [adazzle/react-data-grid#2447]
After exporting the CSV file should contain the subRows instead of  ▶ this arrow icon

**Comment by amanmahajan7** [comment]
Export is not controlled by the grid and it is upto to the users to handle cells containing images or icons. I would recommend updating [cellValue ](https://github.com/adazzle/react-data-grid/blob/main/stories/demos/exportUtils.tsx#L12)before exporting

**Comment by amanmahajan7** [comment]
Closing as the issue can be fixed by changing the data before exporting.
