### ISSUE TITLE
[Bug] Running `npm run build` locally doesn't compile css in bundle.js

### ISSUE THREAD

**Issue by MildTomato** [adazzle/react-data-grid#2453]
Currently trying to run `npm run build` locally.

This creates a `lib` directory as normal, with `bundle.js` inside it, however the css is not compiled in js, but rather it trys to import a css file.
Rather than having css in variables, it trys to import them with `import @linaria:/Users ...`

This is the output locally of `bundle.js`

![Screenshot 2021-06-10 at 14 13 43](https://user-images.githubusercontent.com/8291514/121474033-12d4b600-c9f6-11eb-8bc0-0c12fb4ded9b.png)

And this is `bundle.js` from the library installed via npm.

![Screenshot 2021-06-10 at 14 14 01](https://user-images.githubusercontent.com/8291514/121474055-1bc58780-c9f6-11eb-8787-d9cefb8a20fb.png)

Wondering what I'm doing wrong, is there something we need to change locally so it compiles properly?

**Comment by nstepien** [comment]
Thanks for the report, I've opened a PR to fix it, and reported the bug upstream https://github.com/callstack/linaria/issues/778
