### ISSUE TITLE
On initial load grid overflows outside of the container

### ISSUE THREAD

**Issue by danfernand** [adazzle/react-data-grid#246]
When my grid loads into its container width percentage with it overflows outside. If there is a resize of the window then it auto-adjusts correctly to what its with should be.

I believe that the problem is a file called src/DOMMetrics.js

In it's componentDidMount method it does this

``` javascript
componentDidMount() {
    if (window.addEventListener) {
      window.addEventListener('resize', this.updateMetrics);
    } else {
      window.attachEvent('resize', this.updateMetrics);
    }
    this.updateMetrics();
  },
```

I think that the issue could be solved by

``` javascript
setTimeout(() => {
    this.updateMetrics();
}, 0);
```

Im having a hard time testing this because it for some reason breaks a bunch of tests and the test runner doesn't expose those test easily.

**Comment by diogofcunha** [comment]
Hi @danfernand, are you still struggling with this?
Cheers.

**Comment by yassine-be** [comment]
Hi
has anyone solved this yet ??
