### ISSUE TITLE
Cell data verification with a popover

### ISSUE THREAD

**Issue by ChengranYan** [adazzle/react-data-grid#2461]
Do you plan to inherit cell validation into datagrid? when verification passed,   trigger row change, it can be Configurable。

like this?
![image](https://user-images.githubusercontent.com/22503258/121763900-10976680-cb72-11eb-8aef-acc9d7755d70.png)

**Comment by nstepien** [comment]
I don't think we'll add a validation API into react-data-grid v7, it would be better implemented as needed by the user.

**Comment by amanmahajan7** [comment]
Closing this as it should be implemented outside the react-data-grid. You can probably use `cellClass` to highlight the invalid cell

```
cellClass(row) {
 return validate(row, column) ?  'error': undefined;
}
```
