### ISSUE TITLE
react-data-grid-addons depends on material-ui

### ISSUE THREAD

**Issue by pablovb** [adazzle/react-data-grid#2470]
I want to upgrade to the latest versions of react-data-grid and react-data-grid-addons, so I have my dependencies defined this way in my package.json:

```
"react-data-grid": "^7.0.0-canary.49",
"react-data-grid-addons": "^7.0.0-alpha.24",
```

When starting the app, I have this error message:

```
Module not found: Error: Can't resolve '@material-ui/icons' in 'xxx/node_modules/react-data-grid-addons/lib/toolbars'
 @ xxx/node_modules/react-data-grid-addons/lib/toolbars/GroupedColumnButton.js 2:0-44 9:28-34
```

According to react-data-grid-addons package.json, it does not depend on material-ui, but it does, indeed. Note that the dependency is only for `import { Delete } from '@material-ui/icons';`

Could you remove that dependency on such a heavy package? Is there any workaround to make my app not depend on material-ui?

Thanks

**Comment by amanmahajan7** [comment]
`react-data-grid-addons` has been removed and we recommend copying component to your local repository as needed. 
Please check the [changelog](https://github.com/adazzle/react-data-grid/blob/main/CHANGELOG.md#changelog) for more info
