### ISSUE TITLE
Preserving scroll position.

### ISSUE THREAD

**Issue by alvaro1728** [adazzle/react-data-grid#250]
Hi,

I have a page with two grids that show the same data in different layouts, depending on the user's preference (selectable on the page).  So the render logic is basically:

```
render() {
  {this.props.showGridA && 
       <MyReactDataGrid optionsA...>
  }
  {!this.props.showGridA && 
       <MyReactDataGrid optionsB...>
  }
}
```

This works fine except that when the user has scrolled down on grid A and switches to B and then back to A, the scroll position in A is lost and he's back at the top.  Is there any way to preserve the scrolled position between renders?

Thanks,
Alvaro

**Comment by OliverOliverOliverAnders** [comment]
Hi,

I also would be interested in this feature.

Kind Regards,
Oliver

**Comment by alexemorris** [comment]
So would I
