### ISSUE TITLE
Difference between blur and change?

### ISSUE THREAD

**Issue by dmuldoon** [adazzle/react-data-grid#251]
When I double click on a cell in an editable grid it becomes editable.  When I complete my edit, if I press `Enter` the grid is updated just as I'd expect.  If instead I tab to the next cell, my `onRowUpdated` callback is invoked (again, as I'd expect) and all underlying data structures are updated appropriately but the grid still displays the previous value.  My theory was that React did not detect the change and thus the full rendering was short circuited somewhere but I did add a `key` to my row, e.g.,:

`<ReactDataGrid.Row key={row.id} ref="row" {...this.props}/>`

Is this a bug?  A feature?  Is there any control over which event makes the cell editable?  Double-click vs. click, etc.?

Side note - I'm using a custom row renderer as described here:

https://github.com/adazzle/react-data-grid/issues/249

**Comment by bakesteve** [comment]
might be an issue on the custom RR
to be sure if that's the route or not, check the demo and see if you get the same behaviour?
http://adazzle.github.io/react-data-grid/examples.html#/all-the-features
Trying that for me all seems fine, I can commit an edit by clicking away, enter, or tab, with enter or double click opening the editor

**Comment by dmuldoon** [comment]
Anything look odd in my RR:

```
const RowRenderer = React.createClass({
  propTypes: {
    columns: React.PropTypes.array.isRequired,
    row: React.PropTypes.object.isRequired
  },

  setScrollLeft: function (scrollBy:number) {
    this.refs.row.setScrollLeft(scrollBy);
  },

  render: function ():React.Element {
    const {row, columns} = this.props;

    if (row.controlled && columns.length > 2) {
      var DropDownEditor = ReactDataGrid.Editors.DropDownEditor;
      columns[2].editor = <DropDownEditor options={row.codeListItems}/>;
    } else {
      columns[2].editor = null;
    }

    return (<ReactDataGrid.Row key={row.id} ref="row" {...this.props} />);
  }
});
```

**Comment by jpdriver** [comment]
hey @dmuldoon -- if after committing your edit you select the cell (only clicking once) does the value update?

**Comment by dmuldoon** [comment]
@jpdriver - that's exactly what is happening.  In fact, I didn't even realize that the entire row suffers from this.  Scenario:

* I make an edit to row 1, column 1
* The results of my edit should update row 1, column 1, column 2 and column 3 (because column 2 and column 3 are related to column 1 in my data model, and the row's data structure reflects this)
* When I press enter, row 1 and column 1 are updated (good) but column 2 and column 3 are not (bad)
* When I click on column 2, column 2 and column 3 are updated

**Comment by jpdriver** [comment]
ok cool. please can you stick breakpoints in `shouldComponentUpdate()` for Row and Cell and see if they return `true`? From the way you're describing it it sounds like Row will return true but the Cell in question won't..

hey also which version of the package are you using?

**Comment by jpdriver** [comment]
related: https://github.com/adazzle/react-data-grid/commit/c180102862b56706ff5921601ac0c7e77ea71f28

**Comment by dmuldoon** [comment]
I am using version `0.13.34`

**Comment by jpdriver** [comment]
ok -- this one's on me but that change is missing from 0.13.x :flushed: 

it's in 0.12.x and 0.14.x (long story...) -- so it might be as simple as including that one extra line from the above commit?

**Comment by dmuldoon** [comment]
@jpdriver - confirmed that `shouldComponentUpdate` is returning `false` for the *other* values in the row.  (I see my updated values flying by but, alas, `false` is returned)

**Comment by jpdriver** [comment]
cool, grab the change above and i think that'll be it :smile:

**Comment by dmuldoon** [comment]
@jpdriver - when you say "grab" that change, how exactly should I apply it?

**Comment by jpdriver** [comment]
so just add `|| this.props.value !== nextProps.value;` to the end of `shouldComponentUpdate()` in Cell.js

**Comment by dmuldoon** [comment]
This is a little tricky for me, I think, as we use webpack, etc. and don't have static module copies.  I'm looking into the logistics of this...recommendations?

**Comment by dmuldoon** [comment]
@jpdriver - is there any way this could be patched into 0.13.x?

**Comment by jpdriver** [comment]
hey @dmuldoon have opened a PR for this into 0.13.x -- see above. once that's merged in we'll publish a new version.

**Comment by bakesteve** [comment]
Sure. We will patch that and push an update tomorrow

**Comment by dmuldoon** [comment]
Hey, thanks much guys...appreciate it :+1: 

@jpdriver @bakesteve

**Comment by bakesteve** [comment]
That's done, v0. 13.35 though some issues between our build server and npm so may need to wait till tomorrow for it to be publicly accessible
Cheers
Steve

**Comment by dmuldoon** [comment]
Excellent - thanks again @bakesteve 

cc @jpdriver

**Comment by jpdriver** [comment]
@dmuldoon we've published that to npm now https://github.com/adazzle/react-data-grid/releases/tag/v0.13.35

**Comment by dmuldoon** [comment]
Thank you @jpdriver - grabbing it now.
