### ISSUE TITLE
Loop over columns cell navigation

### ISSUE THREAD

**Issue by rbutl0215** [adazzle/react-data-grid#2520]
I would like `CellNavigationMode` to support looping through a column in addition to looping through rows. This can allow for easier data entry on tasks like taking inventory. I made a branch that can support this feature and attached a video of the updated Storybook. 

I've read through the contribution docs, but I am still a little confused on how to open a PR for this feature. Is the only way to contribute through the adazzle npm account?

https://user-images.githubusercontent.com/67930786/125492488-a90a2643-9f9d-4847-9cf8-1d676635a8e5.mov

**Comment by amanmahajan7** [comment]
Fixed in https://github.com/adazzle/react-data-grid/pull/2833
