### ISSUE TITLE
When modal / popup based editors open the cell value is not displayed

### ISSUE THREAD

**Issue by chirayuchiripal** [adazzle/react-data-grid#2522]
Currently, when we use modal based editor (out of cell editors). For e.g. completion column in [storybook example](https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features). If you open the editor for any cell on that column, the current displayed value of the cell goes blank. It would be nice to have the current value continue to be displayed in such cases.

**Comment by amanmahajan7** [comment]
This will be fixed in https://github.com/adazzle/react-data-grid/pull/2440
