### ISSUE TITLE
Can't use it in SPFx because TSC error that does not make sense

### ISSUE THREAD

**Issue by Ofer-Gal** [adazzle/react-data-grid#2523]
when running gulp serve I get errors 
```
Error - [tsc] node_modules/react-data-grid/lib/index.d.ts(1,13): error TS1005: '=' expected.
Error - [tsc] node_modules/react-data-grid/lib/index.d.ts(1,26): error TS1005: ';' expected.
Error - [tsc] node_modules/react-data-grid/lib/index.d.ts(2,13): error TS1005: '=' expected.
Error - [tsc] node_modules/react-data-grid/lib/index.d.ts(2,35): error TS1005: ';' expected.
Error - [tsc] node_modules/react-data-grid/lib/index.d.ts(3,13): error TS1005: '=' expected.
Error - [tsc] node_modules/react-data-grid/lib/index.d.ts(3,36): error TS1005: ';' expected.
```
the 3 lines are :
`
import type { Key } from 'react';
import type { ReactElement } from 'react';
import type { RefAttributes } from 'react';
`
Which look right to me.
React is 16.9 @microsoft/rush-stack-compiler-3.7 is "0.2.3"
Is there any way I can use it with SPFx 1.12.1?

**Comment by amanmahajan7** [comment]
https://github.com/adazzle/react-data-grid/blob/main/package.json#L109 The minimum supported version is 16.14. Can you try updating react? If there is still an issue then can you create a codesandbox example?

**Comment by robertabenassi** [comment]
I have the same problem, but I am using React > 16.14, so it should be supported.
I am trying to integrate react-data-grid into a create-react-app application and the error is
TypeScript error in node_modules/react-data-grid/lib/index.d.ts(1,13):
'=' expected.  TS1005

  > 1 | import type { Key } from 'react';
      |             ^
    2 | import type { ReactElement } from 'react';
    3 | import type { RefAttributes } from 'react';

**Comment by nstepien** [comment]
Looks like "@microsoft/rush-stack-compiler-3.7" is using an old version of TypeScript, this is probably the source of your issues. Please try with the latest version of TypeScript.
