### ISSUE TITLE
"frozen: true" doesn't work when column key have dot

### ISSUE THREAD

**Issue by gormonn** [adazzle/react-data-grid#2527]
"frozen: true" doesn't work when column key have dot

i use keys with dot to use one formatter for all columns because can be nested values, like that:
```
import get from "lodash/get";
const formatter = (
  props: PropsWithChildren<FormatterProps<MyData, unknown>>
) => <CellView>{get(props.row, props.column.key)}</CellView>;
```

i found that:
https://github.com/adazzle/react-data-grid/blob/50c5302754a60198894042369570813a0efdcf5c/src/utils/index.ts#L21-L30
https://github.com/adazzle/react-data-grid/blob/50c5302754a60198894042369570813a0efdcf5c/src/hooks/useCalculatedColumns.ts#L181-L184

I think that i have that bug because we can't use dots in variable-name:
```--frozen-left-${column.key}```

but, types said:
https://github.com/adazzle/react-data-grid/blob/50c5302754a60198894042369570813a0efdcf5c/src/types.ts#L8-L9

so...

i think we can go two other ways:
1. documentation - warn about it in type definition
2. use .replace(/\./g,'-') - poor performance?

**Comment by nstepien** [comment]
Thanks for the bug report!
