### ISSUE TITLE
can any one give example for filterable with dynamic data its not working (i am using axios for api calls)

### ISSUE THREAD

**Issue by abhishek-jaiswal** [adazzle/react-data-grid#253]
can any one give example for filterable with dynamic data its not working (i am using axios for api calls)

**Comment by txm** [comment]
Did you figure this one out?  I've a bug on my list which might be related.

On 19 March 2016 at 11:45, Abhishek Jaiswal <notifications@github.com>
wrote:

> can any one give example for filterable with dynamic data its not working
> (i am using axios for api calls)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/adazzle/react-data-grid/issues/253>
>



-- 
Andrew McGregor
07940 22 33 11

**Comment by abhishek-jaiswal** [comment]
no

**Comment by luminousmen** [comment]
I've got the same

**Comment by luminousmen** [comment]
This works for me:
```
/* custom filtering rows */
const filterRows = (filters, rows = []) => {
    return rows.filter(r => {
        let include = true;
        for (let columnKey in filters) {
            if (filters.hasOwnProperty(columnKey)) {
                if (!r[columnKey]) {
                    include = false;
                }
                else {
                    let rowValue = r[columnKey].toString().toLowerCase();
                    if (rowValue.indexOf(filters[columnKey].toLowerCase()) === -1) {
                        include = false;
                    }
                }
            }
        }
    return include;
    });
};
class List extends Component {
...
    handleFilterChange(filter){
    ...
    let getFilteredRows = filterRows(newFilters, this.state.originalRows)
            this.setState({rows: getFilteredRows, filters: newFilters})
    }
...
}
```

**Comment by diogofcunha** [comment]
@luminousmen solution should work fine.

You can also check our [custom filters example](http://adazzle.github.io/react-data-grid/examples.html#/custom-filters) and [Filterable sortable example](http://adazzle.github.io/react-data-grid/examples.html#/filterable-sortable-grid)
