### ISSUE TITLE
column fields are defined as readonly inside the d.ts file index.d.ts in 7.0.0-beta.0? 

### ISSUE THREAD

**Issue by behuf** [adazzle/react-data-grid#2530]
Hello,

in the prev version 7.0.0-canary.49 the type definition was ok. 

in the beta.0 it is not possibile for me to set the column properties because of the readonly field types.

is there a reason for this ?

thank you.

**Comment by amanmahajan7** [comment]
This change was made to avoid accidental mutations to the columns prop. For example grid won't rerender if we do the following
 
`column[0].name = 'new name'`

How are you setting columns?

**Comment by behuf** [comment]
I inherited my own Column Object from yours.
`
  export interface BhEditTableColumn<TRow, TSummaryRow = unknown> extends Column<TRow, TSummaryRow> {
  
    bhColumn?: BhClientColumn;
    showIsNewIcon?: boolean;
  
  }`

I create the columns within my own table control and add values ​​to them.

Actually also what is in your examples.

I use typescript, 

![image](https://user-images.githubusercontent.com/2044858/127276692-a460368a-f9ac-4742-a76a-cf5f93976758.png)

**Comment by behuf** [comment]
i rewrote my code. and now it works again. Thanks very much. it makes sense that the properties are readonly.
