### ISSUE TITLE
Headers disappear when vertically scrolling

### ISSUE THREAD

**Issue by mainfraame** [adazzle/react-data-grid#2531]
first off, fabulous job on this library! I’m really hoping to use this instead of ag grid going forward.

Actual:

Given a user is vertically scrolling
When the top of the viewport is showing part of an out of view row
Then the headers are not visible.

![23917CDA-71B8-4712-B26E-B5B517E48CAD](https://user-images.githubusercontent.com/5190439/126793583-e87164a8-08eb-488f-8dea-94d37a4469b3.png)
![1AA861EC-4895-4845-90F3-D8A20DC94C26](https://user-images.githubusercontent.com/5190439/126793586-6171d7ac-9685-4e0f-abaf-7a4d3da961a9.png)

Expected:

Given a user is vertically scrolling
When the top of the viewport is showing part of a row
Then the header is visible.

* header should never be hidden

**Comment by amanmahajan7** [comment]
Which browser/version are you using? We are using position sticky and it is buggy in some browsers
