### ISSUE TITLE
Using prop formatter - element inside don't stop rendering

### ISSUE THREAD

**Issue by FelipeBattistotti** [adazzle/react-data-grid#2532]
Hello,
I'm using prop formatter in a column, to render a children element. And it's not working properly.

The element inside formatter, don't stop rendering. This blocks the event of the element inserted into the formatter.

Like this:
![image](https://user-images.githubusercontent.com/61482397/126908635-7f9c3230-76f4-471b-8a75-2e7a2bcf8cdd.png)

My code:

```
const columns: any[] = [
    {
      key: _moreOptionsAbbrevKey,
      name: _moreOptionsAbbrevDesc,
      width: 40,
      maxWidth: 40,
      resizable: false,
      sortable: false,
      frozen: true,
      formatter({ row }) {
        return (
          <>
            <div
              onClick={() => handleShowMoreOptions(row)}
            >
              {row.id}
            </div>
          </>
        );
      }
    },
    {
      key: 'id',
      name: 'Código',
      width: 200
    },
```

I'm using Next.js with TailwindCSS.

If anyone can help I appreciate it.

**Comment by nstepien** [comment]
Can you perhaps debug with the React Devtools' profiler? It should tell why a component get re-rendered

**Comment by amanmahajan7** [comment]
Closing due to lack or response.
