### ISSUE TITLE
View port is off by a few pixels

### ISSUE THREAD

**Issue by nqbao** [adazzle/react-data-grid#255]
I am using Mac + Chrome 49 and the data grid on the [example page](http://adazzle.github.io/react-data-grid/examples.html#/basic) is off by a few pixel as in screenshot

<img width="1121" alt="screenshot 2016-03-24 10 47 17" src="https://cloud.githubusercontent.com/assets/177742/14025998/f1b35aa6-f1ad-11e5-9d88-ad63a4e9e74e.png">

**Comment by malonecj** [comment]
thanks, we will take a look at that

**Comment by jpdriver** [comment]
hey @nqbao -- that's coming from the border styling. Have opened a PR to fix here https://github.com/adazzle/react-data-grid/pull/259

**Comment by nqbao** [comment]
Cool!
