### ISSUE TITLE
inline editing doesn't works at mobile

### ISSUE THREAD

**Issue by 99937272** [adazzle/react-data-grid#256]
such as iPhone or iPad

**Comment by slmille4** [comment]
Any information on this? No editing on mobile limits the grid's usefulness.

**Comment by diogofcunha** [comment]
Just tested on my phone and the issue seems to be sorted now.

Any problem feel free to report.

Cheers.

**Comment by DaveOke** [comment]
Still doesn't seem to work. Cannot inline edit combo box / text fields
 - using iPad emulator in Chrome
 - Using Safari on a real iPad

**Comment by jper92** [comment]
+1 It doesn't work neither in the demo nor in my implementation (v2.0.58) using iPhone 5S and Chrome iPhone emulator

**Comment by whatsrupp** [comment]
+1 Not working for the examples on the chrome browser emulator, or actual phone. 

I think it's something to do with the necessity for a double-click. On the 'All the features grid' example, accessing the editing feature works fine in the 'County' column as it must be tied into a single click event in the autocomplete editor.

Is there any way to tie in the cell editing state to a single click event?

**Comment by urbinopescada** [comment]
I have the same issue. 
The solution for this can be as simple as: If cell is active, on next click enter in edit mode. I'm I seeing it wrong, or missing something?
