### ISSUE TITLE
Selection disappears when I select a cell's value in FireFox.

### ISSUE THREAD

**Issue by MalyshevKirill** [adazzle/react-data-grid#2561]
I`m trying to apply **user-select: text** property for **.rdg-cell** but in FireFox selection disappears.

**Comment by chirayuchiripal** [comment]
+1. This is possibly due to re-render of the grid/cell on click which is fixed by (#2597)

**Comment by amanmahajan7** [comment]
Looks like the issue has been resolved. Fee free to open a new bug if you are still having issues
