### ISSUE TITLE
onSortColumnsChange not firing in 7.0.0-beta.2

### ISSUE THREAD

**Issue by mikkelking** [adazzle/react-data-grid#2567]
I was on v7.0.0-canary.49, and clicking on column headings works fine. After upgrading to 7.0.0-beta.2, I found the event handler `onSortColumnsChange` is not firing any more.

I have had a look at the diff between the 2 releases, and can't see anything obvious, but there are some changes in this area

**Comment by nstepien** [comment]
Looks fine, do you use custom header formatters via `Column.headerRenderer`?

**Comment by mikkelking** [comment]
Here is the code. I am not using `headerRenderer` at all

```
          <DataGrid
            rowKeyGetter={rowKeyGetter}
            columns={[SelectColumn, ...columns]}
            defaultColumnOptions={{
              sortable: true,
              resizable: true,
            }}
            selectedRows={selectedRows}
            onSelectedRowsChange={setSelectedRows}
            rows={calculatedRows}
            onRowsChange={rowChange}
            sortColumns={sortColumns}
            onSortColumnsChange={(sorts) => {
              if (sorts && sorts.length) {
                setSortColumns(sorts)
              } else if (sortColumns[0]?.columnKey === 'updatedAt') {
                setSortColumns([{ columnKey: 'updatedAt', direction: 'ASC' }])
              } else {
                setSortColumns(defaultSortColums)
              }
            }}
          />

```

**Comment by nstepien** [comment]
Dunno what's wrong on your side.
Can you try and create a minimal reproducible example on codesandbox/in a repo?
https://codesandbox.io/

**Comment by amanmahajan7** [comment]
Closing due to lack of response. Please open a new issue if you are still facing problems.
