### ISSUE TITLE
Ugly warnings from adding a "delete" column.

### ISSUE THREAD

**Issue by alvaro1728** [adazzle/react-data-grid#258]
I've added a "Delete" header and column that just shows a trash can icon, like this:

`{ key: 'delete', name: (<i className="fa fa-trash-o"></i>), width: 30, sortable: false }`

It works fine but I'm getting a warning on the browser log:

warning.js:45 Warning: Failed propType: Invalid prop `column.name` of type `object` supplied to `HeaderCell`, expected `string`. Check the render method of `HeaderRow`.

The same for individual cells:
warning.js:45 Warning: Failed propType: Invalid prop `column.name` of type `object` supplied to `Cell`, expected `string`. Check the render method of `Row`.

Is there a way around these ugly warnings?  I'm trying to avoid them.

Thanks,
Alvaro

**Comment by txm** [comment]
You could delete the prop type ;)

or better replace

name: React.PropTypes.string,

with

name: React.PropTypes.object,

On 29 March 2016 at 03:29, alvaro1728 <notifications@github.com> wrote:

> I've added a "Delete" header and column that just shows a trash can icon,
> like this:
>
> { key: 'delete', name: (<i className="fa fa-trash-o"></i>), width: 30,
> sortable: false }
>
> It works fine but I'm getting a warning on the browser log:
>
> warning.js:45 Warning: Failed propType: Invalid prop column.name of type
> object supplied to HeaderCell, expected string. Check the render method
> of HeaderRow.
>
> The same for individual cells:
> warning.js:45 Warning: Failed propType: Invalid prop column.name of type
> object supplied to Cell, expected string. Check the render method of Row.
>
> Is there a way around these ugly warnings? I'm trying to avoid them.
>
> Thanks,
> Alvaro
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/adazzle/react-data-grid/issues/258>
>



-- 
Andrew McGregor
07940 22 33 11

**Comment by alvaro1728** [comment]
Thanks @txm.  This did it:

`ReactDataGrid.propTypes.name = React.PropTypes.object;`

**Comment by alvaro1728** [comment]
@txm I thought my solution had worked but I just realized that it didn't.  By the way, the problem is with the prop type for the `HeaderCell` and `Cell` types, which I don't know how to access from my code.

Thanks,
Alvaro

**Comment by ppiekarczyk** [comment]
:wave: @alvaro1728 can you please let me know how you handled the `onDelete` event? Thanks!

**Comment by alvaro1728** [comment]
@ppiekarczyk Inside my grid's record mapper, I set the _delete_ "key" like this:

```
return {
...,
delete: (<span className="app-delete-link" title="Click to Delete" onClick={() => this.setState({projectToDelete: project})}><i className="fa fa-trash-o"></i></span>)
};
```

Then in my render function I check for this.state.projectToDelete being set and then I show a modal box asking for confirmation.  If they click OK, then the actual delete happens.  Something like this:

          ```
{projectToDelete &&
            <OKCancelModal
              title="Delete Project"
              onOK={() => this.delete(projectToDelete)} 
              onCancel={() => this.setState({projectToDelete: null})}
  
              <p>Please confirm that you want to permanently delete this project:</p>
              <p className="app-top-spacing text-center"><strong>{projectToDelete.name}</strong></p>
            </OKCancelModal>
          } 
```

**Comment by ppiekarczyk** [comment]
Hey @alvaro1728 thank you for the quick response! What do you mean by `record mapper`?

Would you mind expanding on this a little more? I'm just getting started with react-data-grid.

Where does `projectToDelete` live? do you have a separate `rowRenderer` and `cellRenderer`?

Thanks again

**Comment by alvaro1728** [comment]
Oh, a record mapper is basically a callback function I use to map each record received from the API into a row that the grid can show.  So for example, I might wanna show the "name" column as a link.  So my record mapper converts record.name like this:

    this.recordMapper = (record) => {
      return {
        name: (<a title={record.description} onClick={() => this.showType(record.name)}>{record.name}</a>),
        column2: etc.
      }
    }

I pass it as a property to my Grid's wrapper.  Then inside it I can do something like this:

componentWillMount() {
  const rows = this.props.records.map(this.props.recordMapper);
  this.setState({rows});
}

To answer your question about projectToDelete, it lives in the **state** of the component that renders the grid.  Let me show you more of the render method, which should clear that up:

  render() {
    const {projectToDelete} = this.state;
    ....
    return (
         <MyGridWrapper records={resultFromAPIcall} recordMapper={this.recordMapper} ... />
         ...
          {projectToDelete &&
            <OKCancelModal
              title="Delete Project"
              onOK={() => this.delete(projectToDelete)} 
              onCancel={() => this.setState({projectToDelete: null})}>
              <p>Please confirm that you want to permanently delete this project:</p>
              <p className="app-top-spacing text-center"><strong>{projectToDelete.name}</strong></p>
            </OKCancelModal>
          } 
   );
}

**Comment by ppiekarczyk** [comment]
Ah ok cool!

So `MyGridWrapper` passes props down to `ReactDataGrid` 

So the ability to delete a project lives outside of `ReactDataGrid` right?

**Comment by alvaro1728** [comment]
Right, deleting is independent of the grid but once you've successfully deleted, you'll need to refresh the grid so that the deleted row goes away.

projectToDelete lives in the **state** of the main component, the one that renders the grid wrapper.  It only needs to live there since he's the one in charge of showing the confirmation box and triggering the delete.  The grid is just for showing the existing records.  (recordMapper and records also live inside the main component, in case it wasn't clear.  They just get passed as properties to the grid wrapper because the grid needs them to display the rows.)

Play with it and things will start to clear up, hopefully.  Cheers!

**Comment by ppiekarczyk** [comment]
Do you render the delete button directly to the left of the table then? Is that what you mean?

Thanks,

Peter Piekarczyk

https://twitter.com/peterpme
http://github.com/ppiekarczyk

On Wed, Mar 30, 2016 at 11:15 PM alvaro1728

<
mailto:alvaro1728 <notifications@github.com>
> wrote:

Right, deleting is independent of the grid but once you've successfully deleted, you'll need to refresh the grid so that the deleted row goes away.

projectToDelete lives in the

state

of the main component, the one that renders the grid wrapper. It only needs to live there since he's the one in charge of showing the confirmation box and triggering the delete. The grid is just for showing the existing records. (recordMapper and records also live inside the main component, in case it wasn't clear. They just get passed as properties to the grid wrapper because the grid needs them to display the rows.)

Play with it and things will start to clear up, hopefully. Cheers!

**Comment by ppiekarczyk** [comment]
@alvaro1728 I'm sorry, I just can't figure it out. Would you mind showing more of your code for how you did it? No problem if you can't. I've just tried several different things. 

I've tried adding an `onClick` handler to my header/columns row:

```es6
const COLUMNS = [
  {
    key       : '_id',
    name      : 'X',
    width     : 60,
    editable  : false,
    onClick   : (id) => handleDelete.bind(this, id),
    formatter : <DeleteButton />
  },```

The formatter consumes the `onClick` handler from `columns` (`columns.onClick`) and I'm calling the correct id, but I can't get it to bind to the context of the grid, so this won't communicate with Redux

I've also tried coming up with my own custom `RowRenderer`, and I got deleting working but it was an `onClick` event for the ENTIRE row, so no matter where you clicked, the row was deleted.

Thanks again

**Comment by alvaro1728** [comment]
Hi @ppiekarczyk, I understand it can be confusing.  I've taken a few minutes to show you **part** of the  code for both of my components -- that's all I can show you but it should be enough to help you.

`@connect(state => ({projects: state.projects }), {loadProjects, deleteProject})
export default class Projects extends React.Component {
  static propTypes = {
    projects: PropTypes.object.isRequired,
    loadProjects: PropTypes.func.isRequired,
    deleteProject: PropTypes.func.isRequired
  };

  constructor(props) {
    super(props);

    this.columns = [
      { key: 'id', name: 'ID', width: 55, sortable: true },
      { key: 'name', name: 'Name', sortable: true },
      { key: 'delete', name: (<i className="fa fa-trash-o"></i>), width: 30, sortable: false }
    ];

    this.recordMapper = (record) => {
      return {
        id: record.id,
        name: (<a title={record.name} href={`/projects/${record.id}`}>{record.name}</a>),
        delete: (<span className="app-delete-link" title="Click to Delete" onClick={() => this.startDelete(record)}><i className="fa fa-trash-o"></i></span>)
      };
    };

  startDelete(project) {
    this.setState({projectToDelete: project});
  }

  delete(project) {
    this.props.deleteProject(project).then(() => this.props.loadProjects());
    this.setState({projectToDelete: null});
  }

  render() {
    const {data, error: loadError, pending: loadPending = false} = this.props.projects.loadAll || {};
    const {projectToDelete} = this.state;

    return (
      <div>
          <MyGridWrapper
            columns={this.columns}
            records={data.projects}
            recordMapper={this.recordMapper}
          />
          {projectToDelete &&
            <OKCancelModal
              title="Delete Project"
              onOK={() => this.delete(projectToDelete)} 
              onCancel={() => this.startDelete(null)}>

              <p>Please confirm that you want to permanently delete this project:</p>
              <p className="app-top-spacing text-center"><strong>{projectToDelete.name}</strong></p>
            </OKCancelModal>
          }          
      </div>
    );
  }
}

export default class MyGridWrapper extends React.Component {
  static propTypes = {
    columns: PropTypes.array.isRequired,
    records: PropTypes.array.isRequired,
    recordMapper: PropTypes.func
  };

  componentWillMount() {
    this.setState(this.getStateToRefresh(this.props));
  }

  getStateToRefresh(props) {
    // Use the mapper function to get the records -- filter out any null (invalid) records
    const records = props.records.map(props.recordMapper).filter(record => record !== null);

    // Store the original rows array, and make a copy that can be used for modifying eg.filtering, sorting
    return {
      originalRows: records,
      rows: records
    };
  }  

  render() {
    return (
      <ReactDataGrid
        ref="grid"
        columns={this.props.columns}
        rowGetter={(rowIndex) => this.state.rows[rowIndex]}
        rowsCount={this.state.rows.length}
      />
    );    
  }
}
`

**Comment by ppiekarczyk** [comment]
This makes so much sense! Thank you @alvaro1728 :)

**Comment by malonecj** [comment]
Closing this issue as appears to be resolved
