### ISSUE TITLE
Call onRowsChange when using keyboard navigation(arrows).

### ISSUE THREAD

**Issue by keepyourarrow** [adazzle/react-data-grid#2611]
Currently when I'm editing a cell, I'm able to call onRowsChange when I press **enter** or **tab** Is it possible to do the same behavior for arrows? ↑ ↓ currently they don't make you are just stuck in the cell editing.

**Comment by tbantle22** [comment]
I could use this as well

**Comment by amanmahajan7** [comment]
You can use `column.editorOptions.onNavigation` to override the [default behavior](https://github.com/adazzle/react-data-grid/blob/main/src/utils/keyboardUtils.ts#L65). 

something like 
```
function onEditorNavigation({ key, target }: React.KeyboardEvent<HTMLDivElement>): boolean {
  if (
    key === 'Tab' &&
    (target instanceof HTMLInputElement ||
      target instanceof HTMLTextAreaElement ||
      target instanceof HTMLSelectElement)
  ) {
    return target.matches(
      '.rdg-editor-container > :only-child, .rdg-editor-container > label:only-child > :only-child'
    );
  }
  return false;
}


 editorOptions={{
   onNavigation(event) {
     return onEditorNavigation(event) || event.key.startsWith('Arrow')';
   }
}}
```

**Comment by keepyourarrow** [comment]
> You can use `column.editorOptions.onNavigation` to override the [default behavior](https://github.com/adazzle/react-data-grid/blob/main/src/utils/keyboardUtils.ts#L65).
> 
> something like
> 
> ```
> function onEditorNavigation({ key, target }: React.KeyboardEvent<HTMLDivElement>): boolean {
>   if (
>     key === 'Tab' &&
>     (target instanceof HTMLInputElement ||
>       target instanceof HTMLTextAreaElement ||
>       target instanceof HTMLSelectElement)
>   ) {
>     return target.matches(
>       '.rdg-editor-container > :only-child, .rdg-editor-container > label:only-child > :only-child'
>     );
>   }
>   return false;
> }
> 
> ...
> const columns = [{
>  ...
>  key: 'name',
>  editor: TextEditor,
>  editorOptions={{
>    onNavigation(event) {
>      return onEditorNavigation(event) || event.key.startsWith('Arrow')';
>    }
> }]
> ```

thanks, it helped!
