### ISSUE TITLE
Demos-Context Menu can't hide context menu when click the left mouse button. You can hide the menu only by clicking on menu item.

### ISSUE THREAD

**Issue by DangJinling** [adazzle/react-data-grid#2638]
![image](https://user-images.githubusercontent.com/9940532/132442365-9f7d43cd-192d-4228-a3f1-6f17e4e2a49e.png)

**Comment by amanmahajan7** [comment]
`react-contextmenu` was removed from the repo and the example is now using custom context menu
https://adazzle.github.io/react-data-grid/#/context-menu
