### ISSUE TITLE
How to change default darkmode style

### ISSUE THREAD

**Issue by Mhde96** [adazzle/react-data-grid#2639]
how to change style table to brightmode or any thing

 ```
<DataGrid
          style={{background:'white' }}
          columns={columns}
          rows={values}
          onRowsChange={onRowsChange}
/>
```

i don't find any document for style table 
and tried to use   style={{background:'white' }} but didn't work

**Comment by SO-Eng** [comment]
You need to set the className with rdg-MODE like below.
Further styles you can adjust with the style={{}} prop

<DataGrid
         className={"rdg-light"} // "rdg-dark"
         columns={columns}
         rows={values}
         onRowsChange={onRowsChange}
/>
