### ISSUE TITLE
onRowUpdated is not being called

### ISSUE THREAD

**Issue by vedran-maestral** [adazzle/react-data-grid#266]
I have this code:
(react is 0.14.7)

    var statusTypes = ['Not defined', 'Pending', 'Approved'];
    var DropDownEditor = ReactDataGrid.Editors.DropDownEditor;
    var StatusTypesEditor = <DropDownEditor options={statusTypes}/>

    var columns = [
       {
           key: 'id',
           name: 'ID',
           width: 80
       },
      {
           key: 'Status',
           name: 'Status',
           resizable : true,
          sortable : true,
          filterable: true,
         editor : StatusTypesEditor
      },
  ]

                 <ReactDataGrid
                    onGridSort={this.handleGridSort}
                    columns={columns}
                    rowGetter={this.rowGetter}
                    enableCellSelect={true}
                    rowsCount={this.state.rows.length}
                    enableRowSelect='multi'
                    onRowSelect={this.onRowSelect}
                    onAddFilter={this.handleFilterChange}
                    toolbar={<Toolbar enableFilter={true}
                    onRowUpdated={this.handleRowUpdated}
                    />}

When I make a change in the grid, it never updates. To be more precise the handleRowUpdated function is never called at all.

Wha tmight be the issue?

**Comment by malonecj** [comment]
Hi 

Not sure if you have pasted the correct markup but you are missing a closing `/>` on the toolbar prop. `toolbar={<Toolbar enableFilter={true}/>`
