### ISSUE TITLE
How to export existing functions from react data grid package ?

### ISSUE THREAD

**Issue by evbargavi** [adazzle/react-data-grid#2665]
I want to export below functions  in order achieve row render : 
SO i have manually exported in node module  - package code . 

 - \node_modules\react-data-grid\lib\index.d.ts
 
export declare const RowSelectionProvider : any;
export declare const groupRowSelectedClassname : any;
export declare const rowClassname : any;
export declare function getColSpan : any;
export declare function isCellEditable : any;
export declare function getCellClassname : any;

and in  - node_modules\react-data-grid\lib\bundle.js
export {RowSelectionProvider, getColSpan, groupRowSelectedClassname, rowClassname, isCellEditable , getCellClassname};

(or)
How to implement above functionalities without exporting from node package ? 
Note : I cant use the componenet

**Comment by evbargavi** [comment]
Hi,

Is it possible to look into it ?

I need this asap in order to do row rendering in mobile responsive.

**Comment by amanmahajan7** [comment]
We are not exporting internal classes and functions by design. Please create a separate issue with a use case and reprodible example if applicable
