### ISSUE TITLE
columnMinWidth not working

### ISSUE THREAD

**Issue by ssjogus** [adazzle/react-data-grid#268]
hi,

thanks for nice plugin. somehow i am not able to use one feature of min-width

i am giving it as:

....
  columns.push({
                            key:CombinedGridViewColumns[index].Name,
                            name:CombinedGridViewColumns[index].Name,
                            title:CombinedGridViewColumns[index].DisplayName,
                            columnMinWidth:50,
                            width : 200,
                            resizable : true,
                            editable : false
                        });
....

but when i resize the columns, it is allowing me to resize till 1px. it is not stoppping at 50px. can you please guide me how to do that?

thanks for help in advance

**Comment by martinnov92** [comment]
Hi @ssjogus I think you should set columnMinWidth as a property on ReactDataGrid, but for me, this is not working well either ... :/ Sometimes it is working and sometimes it is not...

**Comment by muriloferes** [comment]
Does any one knows how to set "columnMinWidth" to ReactDataGrid?
I trying to set less than 80px as min-width to columns, but I having no success.

**Comment by BlaineBradbury** [comment]
This is old, but for future reference, the prop is "minColumnWidth", and it does go on the data grid as opposed to being a column property.

I noticed my 65px columns with "resizable=true" would grow in size as soon as the resizing begins and you could not drag them smaller... default value for this prop is 80.  See docs here:  https://adazzle.github.io/react-data-grid/docs/ReactDataGrid
