### ISSUE TITLE
Header parent columns

### ISSUE THREAD

**Issue by alexey-koran** [adazzle/react-data-grid#2683]
Hi. I need a parent column functionality 

I saw that it might be implemented, and you had the discussion before.
https://github.com/adazzle/react-data-grid/pull/2393
https://github.com/adazzle/react-data-grid/pull/2350

So do you have a plans to implement this feature in a near future?

**Comment by amanmahajan7** [comment]
This is supported now 
https://adazzle.github.io/react-data-grid/#/column-grouping
