### ISSUE TITLE
[bug] handleColumnResize is too laggy - put it into requestAnimationFrame maybe?

### ISSUE THREAD

**Issue by gormonn** [adazzle/react-data-grid#2685]
Resizing columns is very expensive for now. It's lagging on MacOS 2019

Because that code will trigger rerender all grid too often.

Code:
https://github.com/adazzle/react-data-grid/blob/20fc7d7bac584b94de4cfc3f98e23130308bd229/src/DataGrid.tsx#L400-L414
https://github.com/adazzle/react-data-grid/blob/20fc7d7bac584b94de4cfc3f98e23130308bd229/src/HeaderCell.tsx#L79-L84

Explanation:
Because resize events can be fired at a high rate, the event handler does not need to perform expensive operations such as DOM modifications. Instead, it is recommended that you regulate the event using requestAnimationFrame, setTimeout, or customEvent.

**Comment by amanmahajan7** [comment]
Can you create a reproducible example? It is quite response on the [website](https://adazzle.github.io/react-data-grid/#/common-features). When column is resized, we change the column size using `grid-template-columns` so it should not trigger any row or cell update if they are memoized correctly. Are you using a custom `RowRenderer`?

**Comment by nstepien** [comment]
Events are already synced to the display refresh rate, so adding `requestAnimationFrame` would make the user interaction delayed.

You might have noticed performance issues when having the devtools open though, that's unfortunately a Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=992954

**Comment by amanmahajan7** [comment]
Closing due to lack of response. Feel free to open a new issue if you are facing this problem.
