### ISSUE TITLE
hidden colums

### ISSUE THREAD

**Issue by malonecj** [adazzle/react-data-grid#27]
setting `column.hidden` should not render that column

**Comment by txm** [comment]
Does column.hidden go in the column data structure?

I've just tried it, but the app doesn't load.

OSX/FF/React Plugin Debugger

"Unable to find React on the page."

**Comment by afong94** [comment]
Does this work? I'm having issues implementing this.

**Comment by pgeeh** [comment]
It appears this should be reopened. The following fiddle, forked from the basic example fiddle, shows that the cells for the data rows are not rendered, but the header cell is rendered still.

https://jsfiddle.net/3jb4cojx/

**Comment by audiolion** [comment]
agreed, I am having the same issue

**Comment by DhanaTontanahal** [comment]
Here is the working example of the React data grid wrapper example for hiding the columns dynamically.

Hiding the columns dynamically using the column chooser

https://github.com/DhanaTontanahal/reactdatagrid_hidecolumns_dynamically

Please star it if it is useful for you.

Thank you
