### ISSUE TITLE
Component in headerRenderer not rendering properly

### ISSUE THREAD

**Issue by anilkumarmr** [adazzle/react-data-grid#2709]
## Describe the bug 

I need to show  filters on the table header. For that purpose I am using  react-multi-select-component (https://www.npmjs.com/package/react-multi-select-component ). The issue I am facing is the dropdown component of the filter is not displaying properly in the header.

react-select seems to be working but I cannot use it here.

## To Reproduce 

1.Click on the filter comonent, u will see the dropdown goes under the header
2.

Link to code example: https://codesandbox.io/s/react-data-grid-custom-filter-q2bb7

## Expected behavior 
The dropdown shold be visible completely

## Environment

- `react-data-grid` version: 7.0.0-beta.7
- `react`/`react-dom` version:17.0.2

**Comment by amanmahajan7** [comment]
It is happening because the select menu is rendered inside the header cell. I would recommend using a library that support portal  for example 
https://react-select.com/advanced#portaling

**Comment by DVGY** [comment]
> @amanmahajan7 - can you please explain why is it not working if it is rendered inside the cell?

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_positioned_layout/Understanding_z-index/Stacking_context
