### ISSUE TITLE
minHiegth and overflow hidden issues

### ISSUE THREAD

**Issue by josefkvist** [adazzle/react-data-grid#272]
I have set minHeight to 485. If I have 14 rows plus headers I have to scroll some to see the last line. The canvas height (div with className react-grid-Canvas) is calculated to 448px but when I remount the grid, i.e change route and then back, the canvas height is 485px and then I can't reach the last line because the height exceeds my outer div.

**Comment by AbhishekCode** [comment]
Hi @josefkvist did you found any solution to this, I'm facing same issue.

**Comment by josefkvist** [comment]
Hi @AbhishekCode 
I did a workaround, kind of ugly, like this:
.react-grid-Canvas {
    height: 448px !important;
}

just inspect when its loaded the first time to get the proper height.
