### ISSUE TITLE
Hidden header-row but has Keyboard Navigation

### ISSUE THREAD

**Issue by vivaslj1** [adazzle/react-data-grid#2724]
## Describe the bug 
I have to hide the header-row of the grid

but keyboard navigation still works, so Focus Element disappears on screen.

## To Reproduce 

1. Hide header-row, I have try like this
   a. .rdg-header-row { display : none } 
   b. <ReactDataGrid {...otherProps} headerRowHeight={0} />

2. then use keyboard navigation

## Expected behavior 

Choice: 1. I would need a prop to set if Header-Row is disabled navigational element
Choice: 2. If the component detects headerRowHeight=0, disable Header-Row navigation

## Environment

react-data-grid version: 7.0.0-beta.7
react/react-dom version: 16.14.0

Any help greatly received!

**Comment by alamothe** [comment]
It's weird to have navigable header. E.g. Google Sheet or Microsoft Excel don't have it.

**Comment by amanmahajan7** [comment]
Fixed in https://github.com/adazzle/react-data-grid/pull/2833
