### ISSUE TITLE
Column formatter is not called on passive change

### ISSUE THREAD

**Issue by isaacdalmarco** [adazzle/react-data-grid#2727]
## Describe the bug 

I am upgrading data-grid to the latest version and I am having a issue.
I need to convert a grid with 2 selector columns as follows, but when i check the header checkbox is not changing the checkbox in the cells. 
Debugging I realized that formatter function is not called if the cell is not selected. It happens with any rows change made in a not selected cell.

![Peek 02-11-2021 18-14](https://user-images.githubusercontent.com/18038261/139956611-55778092-47fe-4add-bc8e-4b86ca354292.gif)

My column:

{
  key: 'checked',
  name: 'Apontar',
  resizable: true,
  draggable: true,
  editable: true,
  formatter: (props) => (
    <DataGridCheckbox
      {...props}
      value={props.row && props.row[props.column.key]}
      field="checked"
      onChange={this.handleChangeOp}
      style={{ margin: '0px 0px 0px 26px' }}
    />
  ),
  width: 92,
  frozen: true,
  headerRenderer: (props) => (
    <DataGridCheckbox
      {...props}
      field="Apontar"
      onChange={(x, y, value) => this.handleCheckAll(value)}
      style={{ marginBottom: 0 }}
      header
    />
  ),
}

Is there any way to force the formatter to be called?

## To Reproduce 

1. Add a column with the formatter prop
2. Modify the value of the column of all rows

## Expected behavior

![Peek 02-11-2021 18-23](https://user-images.githubusercontent.com/18038261/139956629-ea904eae-b44c-4e1e-ac0b-caa9d3ef65a9.gif)

It is in an older version.

## Environment

- `react-data-grid` version: 7.0.0-beta.7
- `react`/`react-dom` version: 16.12.0

**Comment by amanmahajan7** [comment]
Can you create a reproducible codesandbox example?

**Comment by amanmahajan7** [comment]
Closing due to lack of response. Feel free to create a new issue if you are facing this issue
