### ISSUE TITLE
 prop for enabling / disabling edit on keypress

### ISSUE THREAD

**Issue by mikestone24** [adazzle/react-data-grid#274]
There should a prop to enable or disable edits on keypress

**Comment by malonecj** [comment]
Could you explain further please? Pressing a key, or hitting enter on an editable cell will open the editor for that cell.

Do you mean a way of making the cell readonly?

**Comment by txm** [comment]
If you use the arrows to highlight a cell, then press Enter, the cell
Editor pops up.  To trigger an update you can press up or down, select with
mouse, or select somewhere else with the mouse, you cannot press left/right
as the screen will scroll.

If you mean a select box with readonly/disabled?

-- 
Andrew McGregor
07940 22 33 11

**Comment by jpdriver** [comment]
not read only. *only* open editors on double-click, instead of pressing a key or hitting enter on an editable cell. basically a prop that disables keyboard edits.
