### ISSUE TITLE
Don't commit blank edits 

### ISSUE THREAD

**Issue by mikestone24** [adazzle/react-data-grid#275]
Unless you press DELETE on a cell, never allow edits on cell to be blank . For example:

if you type h into a cell, and then you are like opps didn't mean to do that, and you delete the h and press enter, the cell should return to its previous content.

**Comment by malonecj** [comment]
We want to keep the ability to commit blank edits. However, your desired behaviour can be acheived by pressing `ESCAPE` when within an editor
