### ISSUE TITLE
context-menu  The right-click menu is not closed

### ISSUE THREAD

**Issue by reai99** [adazzle/react-data-grid#2761]
## To Reproduce 

1.grid to right-click
2. Click elsewhere in the grid
3. The right-click menu is not closed
Link to code example:https://adazzle.github.io/react-data-grid/#/context-menu

## Environment

- `react-data-grid` version: 4.0.8 
- `react`/`react-dom` version:^15.6.2

## Additional context 
![image](https://user-images.githubusercontent.com/45794057/145773393-46274b45-8db8-4bf0-b691-c90bb1b3842e.png)

**Comment by jayakrishnancn** [comment]
Anyone working on this? I have a fix. can I take this?

**Comment by reai99** [comment]
Click inside the grid the menu is not closed

**Comment by reai99** [comment]
I have a solution
1、ContextMenu getting component instances
const props = {
      ref: e => this.contextMenu = e,
      id: "grid-context-menu",
    }
2、listen for table row clicks，do the following
this.contextMenu?.setState({
      isVisible: false
    })

**Comment by JokerMartini** [comment]
Can someone merge this fix into the master branch?

**Comment by reai99** [comment]
> Can someone merge this fix into the master branch?
Wait for the publisher to update @jayakrishnancn

**Comment by JokerMartini** [comment]
Understandable. Are there not multiple people that manage the repo or is it just the one guy who verifies all the pull requests and merges
