### ISSUE TITLE
Property 'rows' does not exist in GridProps<T>

### ISSUE THREAD

**Issue by Mulperi** [adazzle/react-data-grid#2772]
I am not able to use react-data-grid with create-react-app and typescript.
I installed react-data-grid and @types/react-data-grid but when I try to just paste in the simple example, I get error that there is no "rows" prop in DataGrid:
```

import DataGrid from "react-data-grid";

const columns = [
  { key: "id", name: "ID" },
  { key: "title", name: "Title" },
];

const rows: any = [
  { id: 0, title: "Example" },
  { id: 1, title: "Demo" },
];

function MyComponent(props: any) {
  return (
      <DataGrid columns={columns} rows={rows} />
  );
}
```

<img width="605" alt="image" src="https://user-images.githubusercontent.com/16062307/147098019-753bc5e1-312a-46d8-b63b-8f7abb6d88b3.png">

## Environment
VSCode

- `react-data-grid` version: 7.0.0-beta.7
- `react`/`react-dom` version: 17.0.2

**Comment by bdecarne** [comment]
Do not install `@types/react-data-grid` with the last version of `react-data-grid` : it is not compatible and typescript types are now included.

**Comment by kartset** [comment]
@bdecarne Which version of @types/react-data-grid we should install so that it functions properly
