### ISSUE TITLE
ERROR in ./node_modules/react-data-grid/lib/bundle.js (React with Typescript)

### ISSUE THREAD

**Issue by iqasim-com** [adazzle/react-data-grid#2773]
## Describe the bug
Created a new project using
`npx create-react-app my-app --template typescript`

Installed react-data-grid same as mentioned in the quick start section but after running my app i am getting following error

![image](https://user-images.githubusercontent.com/23281307/147383367-695b79b4-acd8-4a0c-b3fd-02f90260208b.png)

## To Reproduce 

Couldn't found anything to reproduce it

## Expected behavior 

i have tried the Quick start section instructions so it should be come up with the basic table.

## Environment

- `react-data-grid` version: 7.0.0-beta.7
- `react`/`react-dom` version: 17.0.2 / 17.0.2

![image](https://user-images.githubusercontent.com/23281307/147383382-0544d7f9-d67b-40da-8db9-a1efc02cc7dd.png)

## Additional context

I have tried some stackoverflow answers but couldn't succeed.

**tsconfig file**
![image](https://user-images.githubusercontent.com/23281307/147383392-dc4d41d7-d941-48bd-bfa7-05f2a20d1a32.png)

**Comment by mars10786** [comment]
I updated react to the latest available version today and the issue has gone.
react-data-grid is now using react/jsx-runtime for jsx transformation described as follows:

[https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html](url)

but i think it's kind of braking change so it needs to be considered.

my current environment is as follows. hope it helps.

```
# diff -uwB package.json.save package.json
--- package.json.save   2021-12-26 15:59:58.220000000 +0900
+++ package.json        2021-12-26 16:11:51.650000000 +0900
@@ -11,7 +11,7 @@
     "chartist": "^0.11.4",
     "jquery": "^3.6.0",
     "jsdom": "^19.0.0",
-    "react": "^17.0.2",
+    "react": "^18.0.0-rc.0-next-f2a59df48-20211208",
     "react-chartist": "^0.14.4",
     "react-data-grid": "^7.0.0-beta.7",
     "react-dom": "^17.0.2",
```

**Comment by RikuVan** [comment]
Had the same issue today trying to use in new Next project. Oddly it seem to work briefly then this error started.

**Comment by RikuVan** [comment]
Ok, this is duplicate for #2568 it seems. Since this is only for a demo/lib evaluation I upgraded to React 18 to get it working.

**Comment by amanmahajan7** [comment]
Closing at this is a duplicate issue. Please check https://github.com/adazzle/react-data-grid/issues/2787#issuecomment-1071978035
