### ISSUE TITLE
Scroll-y overlaps header row

### ISSUE THREAD

**Issue by danielpaz6** [adazzle/react-data-grid#2776]
## Describe the bug 

When you scroll, the starting position of the scrollable starts above the header, instead of the body of the table.

1. Take a look at the official doc example: https://adazzle.github.io/react-data-grid/#/common-features
2. Try to scroll down and you will notice your scrollable starts from the header

Link to code example:
https://adazzle.github.io/react-data-grid/#/common-features

## Expected behavior 
The scroll bar should start from table's body, this is the behavior in all other scrollable tables I've seen.

## Environment

- `react-data-grid` version: 7.0.0
- `react`/`react-dom` version: 17.0.2

## Additional context 
Is there a fast solution to the problem? temporary css fix I can make?

**Comment by Love-YGX-and-D** [comment]
I think this can't be counted as a bug，because use sticky characteristic。scroll content is all，scroll bar show in top is normal。

**Comment by amanmahajan7** [comment]
This is by design. We are using one container and header row is made sticky so the scrollbar starts from the header. I am not sure if there is way to change this behavior.
