### ISSUE TITLE
+    "react-data-grid": "^0.14.24",

### ISSUE THREAD

**Issue by txm** [adazzle/react-data-grid#278]
+    "babel-plugin-transform-es3-member-expression-literals": "^6.5.0",
+    "babel-plugin-transform-es3-property-literals": "^6.5.0",

Just upgraded to 0.14.24, I needed a couple of babel plugins.

**Comment by malonecj** [comment]
This is to continue support for IE8 after Babel was upgraded to version 6

IE8 support will discontinue when we move to react-data-grid v 1.0.0
