### ISSUE TITLE
Permanent Filter

### ISSUE THREAD

**Issue by vedran-maestral** [adazzle/react-data-grid#279]
I would like to have filter text boxes opent all the time, without having to click "Filter rows" button.

Is that possible without dirty tricks?

**Comment by txm** [comment]
I don't think it is.

On 12 April 2016 at 09:39, Vedran Maricevic <notifications@github.com>
wrote:

> I would like to have filter text boxes opent all the time, without having
> to click "Filter rows" button.
>
> Is that possible without dirty tricks?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/adazzle/react-data-grid/issues/279>
>



-- 
Andrew McGregor
07940 22 33 11

**Comment by malonecj** [comment]
No, this is not currently possible. We will accept a pull request though if you would like to try implement

**Comment by vedran-maestral** [comment]
I figure how to do it on react side:
1. Give the component a ref. Something like this:
  <ReactDataGrid
                    ref="testingstuff"
                       ...

2. In the component that renders the ReactDataGrid, and in its componentDidMount, add this:
componentDidMount: function () {
        this.refs.testingstuff.setState({canFilter: true});
      ...
    },

Works :)

**Comment by davewthompson** [comment]
The only problem with the recommended answer from @vedran-maestral is that invoking this state change will impact the sizing of the grid.

I used:
`setTimeout(() => {
            this.refs.dataGrid.setState({canFilter: true});
        }, 50);`
