### ISSUE TITLE
Allow to customize Cell renderer

### ISSUE THREAD

**Issue by alamothe** [adazzle/react-data-grid#2799]
Currently, it's only possible to customize (whole) row renderer or column formatter, but not cell formatter.

We could add a property in `Column`:
```tsx
cellRenderer?: Maybe<React.ComponentType<CellRendererProps<R, SR>>>;
```
(interestingly, `CellRendererProps` already exists in types)

If not set, it would use the default one. 

One use case is expander column in master detail example: https://adazzle.github.io/react-data-grid/#/master-detail. Currently, it renders a span which captures keyboard events. But it would be better to capture keyboard events directly on the cell itself (it already has focus). So one definite use case is to be able to capture keyboard events on the cell (which already has focus), instead of trying to focus an element inside a cell.

Let me know what you think. I can send a PR if you would consider it

**Comment by amanmahajan7** [comment]
It is supported now
https://github.com/adazzle/react-data-grid/blob/main/src/types.ts#L316
