### ISSUE TITLE
Upgrade React to v15

### ISSUE THREAD

**Issue by malonecj** [adazzle/react-data-grid#280]

**Comment by jpdriver** [comment]
:+1: -- why 1.0.0 though, and not 15.0.0?

**Comment by tetiogit** [comment]
+1

**Comment by DOMZE** [comment]
+2

**Comment by shadow-identity** [comment]
+3

**Comment by tommiley** [comment]
+1, difficult to use react-data-grid on new projects until it supports React v15

**Comment by CraigNielsen** [comment]
+1

**Comment by jsCTim** [comment]
👍  Any thoughts on a timeline for this?

**Comment by zachguo** [comment]
related #321 #326

**Comment by batjko** [comment]
Some idea of a timeline would really be appreciated. 
I've just tried using this in a Meteor app, where the data for the table would get loaded reactively from the back-end. I loved the idea of making changes in editable fields reactive as well.
Unfortunately, Meteor's React integration requires v15, I couldn't make it work with anything lower than that.

For now, I'm falling back onto Griddle, but once this data-grid is updated for v15, I'm all over it. :fireworks:

**Comment by nicolaspeixoto** [comment]
Is there any timeline for this? We need to use react v15.

**Comment by shadow-identity** [comment]
I've moved to react-bootstrap-table, it's really cool, easy and updated.

**Comment by diogofcunha** [comment]
We need to have in mind that react 15 [doesn't actively support IE8](https://facebook.github.io/react/blog/2016/01/12/discontinuing-ie8-support.html) so the change will not be as straigth forward as some of you may expect.

**Comment by larrxu** [comment]
I also tried to use this in meteor, and ran into another issue with importing the react-data-grid module. I am using version 1.0.7. Could someone point me to the right direction?

```
Unable to resolve some modules:

  "src/index.js" in /C/Users/Larry/git/civeno-instance/node_modules/react-data-grid/package.json (web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save src
```
My code:
```
import React from 'react';
import ReactDataGrid from 'react-data-grid';
import ReactDataGridPlugins from 'react-data-grid/addons';

class Table extends React.Component {
  render() {
    var _rows = [];
    for (var i = 1; i < 1000; i++) {
      _rows.push({
        id: i,
        title: 'Title ' + i,
        count: i * 1000
      });
    }

    //A rowGetter function is required by the grid to retrieve a row for a given index
    var rowGetter = function(i) {
      return _rows[ i ];
    };


    var columns = [
      {
        key: 'id',
        name: 'ID'
      },
      {
        key: 'title',
        name: 'Title'
      },
      {
        key: 'count',
        name: 'Count'
      }
    ]

    return (
      <ReactDataGrid
        columns={columns}
        rowGetter={rowGetter}
        rowsCount={_rows.length}
        minHeight={500}
      />
    );
  }
}
```

**Comment by slashwhatever** [comment]
*sigh* +1

**Comment by slashwhatever** [comment]
> We need to have in mind that react 15 doesn't actively support IE8 

Neither do Microsoft. It's time to move on :)

**Comment by jpdriver** [comment]
I don't think the syntax actually changed that much between RCT 14 and RCT 15 though?

This might be mental but could we potentially have `react: ^14.0.0 || ^15.0.0` in our package.json?

That way Adz peeps can keep IE 8 support until you guys are ready, and the rest of us who have already taken the plunge can keep using it too...

Thoughts? 😁

**Comment by dulguun0225** [comment]
+1

**Comment by alvaro1728** [comment]
+1

**Comment by sekmet** [comment]
+1

**Comment by lixapopescu** [comment]
+1

**Comment by wangtun** [comment]
+1

**Comment by batjko** [comment]
Guys, please use the reaction feature on this issue, instead of adding +1 posts! It's a pointless waste of your time which generates notifications to everyone watching the issue.
Thanks.

**Comment by soundwire** [comment]
I was using the component in React 15.2.1, and I just discovered that the addons don't work when I tried to use filterable columns :(

It has already been asked but, is there any idea about the support timeline? 

Thanks

**Comment by winkler1** [comment]
We've been using react-data-grid at my company but think we'll have to ditch it for something else... we are starting to have major pain because everything wants React 15 so nothing will install.

**Comment by alvaro1728** [comment]
I switched to FB's fixed-data-table, which took some effort to make it functionally equivalent.  On the positive side, I gained the ability to have rows of different heights, which came in handy.

**Comment by dkwin** [comment]
@alvaro1728 I'm just curious, I may go the same route...which features did you implement?  Like column resizing, column locking?

**Comment by alvaro1728** [comment]
@dkwin Column resizing is already supported... which reminds me of fixed-data-table's _flexRow_ feature, which is also nice.  

So to answer your question, I had to implement column sorting which is not supported out of the box but they give you an example to help you add it.  I also had to add code to show an empty "No data" row when no data is available.  Finally, I added code to automatically change the width and height when the window resize event is detected.

**Comment by winkler1** [comment]
@malonecj Is there a rough timeframe for upgrading? (Looks like IE8 is at 2.88% per https://www.netmarketshare.com/browser-market-share.aspx?qprid=2&qpcustomd=0)

**Comment by rpasta42** [comment]
I understand the need to support users with outdated hardware, but you cannot disregard support for newer versions of software just to support an ancient browser.

I have invested dozens of hours integrating react-data-grid, only to find out it doesn't work with majority of the latest react libraries that I need to use.

The community keeps moving forward and the longer you wait, the less relevant your project becomes.

**Comment by batjko** [comment]
So uh... I assume that's done now? Full 15.4 compatibility?

**Comment by diogofcunha** [comment]
Hi @batjko, react-data-grid version 2.0.0 supports react 15

**Comment by batjko** [comment]
Ah, I missed the actual release of 2.0.0, despite watching this repo.
Ok thanks, @diogofcunha!
