### ISSUE TITLE
Summary row height wrong when row grouping is active

### ISSUE THREAD

**Issue by james1050** [adazzle/react-data-grid#2809]
## Describe the bug 
On upgrading from 7.0.0-beta.7 to 7.0.0-beta.8, summary row height is wrong when row grouping is enabled. 

## To Reproduce 
1. Install 7.0.0-beta.8
2. Use a summary row for e.g. total row count, use row groupBy
3. When rows are grouped, the --rdg-grid-row-start on the summary row will increment and the row will take up a seemingly arbitrary height of the table. 

## Expected behavior 
The summary row should keep the same height always regardless of groupBy state. 

## Environment
- `react-data-grid` version: 7.0.0-beta.8
- `react`/`react-dom` version: 17.0.2

**Comment by amanmahajan7** [comment]
Thank you for reporting the issue. It is fixed in beta 9
