### ISSUE TITLE
onRowClick not working in Safari

### ISSUE THREAD

**Issue by armiiis** [adazzle/react-data-grid#2813]
## Describe the bug 
`onRowClick` event is not triggered in Safari after upgrading to `beta-8`
## To Reproduce 

1. Provide any function to `onRowClick`.
2. Click on any row.
2. Function is not called.

Link to code example:
codesanbox link: https://codesandbox.io/s/frosty-tess-njewr?file=/src/App.js
## Expected behavior 
`onRowClick` should be triggered when clicking on row.
## Environment

- `react-data-grid` version: `7.0.0-beta-8`
- `react`/`react-dom` version: `17.0.2`
- `safari` version `14.1`

## Additional context 
It was working fine on `beta-7` version. After updating to `beta-8` I saw more changes around `rdg row`. Row looks invisible now, which made me to make additional changes to have same functionality as in `beta-7` version. For example I was adding `border-bottom` property on `.rdg-row` and now border became invisible. Had to move `border-bottom` to each column of the row.
Also I had transition animations on row height. Height property was also removed and I can't implement transitions anymore when collapsing rows. Looks like height is controlled by `grid-template-rows` which can't be animated with current browsers.

But the main issue is  that `onRowClick` has stopped working.

**Comment by amanmahajan7** [comment]
Which version of safari are you using? Can you try with the latest version or technology preview (which seems to support [display:contents](https://caniuse.com/css-display-contents))? It may be a browser bug

**Comment by amanmahajan7** [comment]
We are now using a single CSS grid and row has `display: contents` style which basically means row does not generate a box anymore and some of the styles cannot be applied on the row and cell must be styled instead. Check the [PR ](https://github.com/adazzle/react-data-grid/pull/2361)for more details

**Comment by ArminasTelesoftas** [comment]
> ~Which version of safari are you using?~ Can you try with the latest version or technology preview (which seems to support [display:contents](https://caniuse.com/css-display-contents))? It may be a browser bug

Thanks for the response. You are right, that's a browser bug. Unfortunately I need to support `safari-13`. I guess I'll have to stay on `beta-7` for now.

**Comment by amanmahajan7** [comment]
I am closing it for now as it is a browser bug.

**Comment by reload07** [comment]
Just work out a hacked solution for Safari (not fully tested yet), please give me your feedback if you find any issues.
`
import { isSafari } from 'react-device-detect';
  
useEffect(() => {
    const gridElem = document.querySelector('.rdg[role="grid"') as HTMLDivElement;
    if (isSafari && gridElem) {
      gridElem.addEventListener('click', onSafariMouseEventRelay);
      gridElem.addEventListener('dblclick', onSafariMouseEventRelay);
      gridElem.addEventListener('contextmenu', onSafariMouseEventRelay);
    }

    return () => {
      if (isSafari && gridElem) {
        gridElem.removeEventListener('click', onSafariMouseEventRelay);
        gridElem.removeEventListener('dblclick', onSafariMouseEventRelay);
        gridElem.removeEventListener('contextmenu', onSafariMouseEventRelay);
      }
    };
  }, []);

  const onSafariMouseEventRelay = (evt: MouseEvent) => {
    if ((evt as any).data !== 'custom-relay') {
      const elementsUnderClick = document.elementsFromPoint(evt.clientX, evt.clientY);
      const cellElem = elementsUnderClick.find((elem) => elem.classList.contains('rdg-cell')) as any;
      if (cellElem && cellElem.ownerDocument) {
        evt.preventDefault();
        evt.stopPropagation();

        const e = cellElem.ownerDocument.createEvent('MouseEvents');
        // TODO: initMouseEvent is obsoleted, find alternative API!
        e.initMouseEvent(
          evt.type,
          true,
          true,
          cellElem.ownerDocument.defaultView,
          evt.type === 'contextmenu' ? 1 : evt.detail,
          evt.screenX,
          evt.screenY,
          evt.clientX,
          evt.clientY,
          false,
          false,
          false,
          false,
          evt.button,
          null
        );
        e.data = 'custom-relay';
        cellElem.dispatchEvent(e);
      }
    }
  };

`
