### ISSUE TITLE
Data import demos

### ISSUE THREAD

**Issue by reviewher** [adazzle/react-data-grid#2822]
## Use case

All of the demos "precompute" the data before creating the grid.  This is probably not how most people use the grid.  It is common to access the data through an API and load a grid once the data is available.

## Proposed solution 

It would be great for the demos page to include an example of what the project maintainers consider idiomatic usage of the data grid, including displaying a message while waiting for data and updating the grid once data has arrived.

For inspiration, here's an example of fetching an Excel file, parsing in browser, and adding the first worksheet to the grid:

```js
import { useEffect, useState } from "react";
import DataGrid from "react-data-grid";
import { read, utils } from "xlsx";

const url = "https://oss.sheetjs.com/test_files/RkNumber.xls";

export default function App() {
  const [columns, setColumns] = useState([]);
  const [rows, setRows] = useState([]);
  useEffect(() => {(async () => {
    const wb = read(await (await fetch(url)).arrayBuffer(), { WTF: 1 });
    const data = utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]], { header: 1 });
    setColumns(data[0].map((r) => ({ key: r, name: r })));
    setRows(data.slice(1).map((r) => r.reduce((acc, x, i) => {
      acc[data[0][i]] = x;
      return acc;
    }, {})));
  })(); });

  return <DataGrid columns={columns} rows={rows} />;
}
```

It would also make sense to have some more demos working with a database server or other resource with an API endpoint.

**Comment by mikkelking** [comment]
Another approach is to render a loading spinner until the data has been fetched...

Declare a loading state variable (you probably need one for your data too)

```
  const [loading, setLoading] = React.useState(true)
```

In your `useEffect` callback, do a `setLoading(false)`

and then your grid will render:
```
  if (loading) return <div>Loading...</div>
  return (
    <Datagrid ...
```

Does this work for you?
