### ISSUE TITLE
Element :before in div role="grid" in Safari

### ISSUE THREAD

**Issue by Leningram** [adazzle/react-data-grid#2823]
Element :before in div role="grid" has a transparent :before pseudo-element which covers all the content and doesn't allow to interact with it. The :before pseudo-element is in every browser but only in safari it covers the content and doesn't allow to click on elements in the table.
Link to code example:

## Environment

- `react-data-grid` version: 7.0.0-beta.10
- `react`/`react-dom` version:17.0.2

**Comment by nstepien** [comment]
Does it help if you add `z-index: -1` to the pseudo element?

**Comment by Leningram** [comment]
> Does it help if you add `z-index: -1` to the pseudo element?

I don't know. I changed the version to cannary and it helped. :before dissapeared in this version.

**Comment by nstepien** [comment]
You can try in the demo website: https://adazzle.github.io/react-data-grid/

**Comment by amanmahajan7** [comment]
We have made some changes to how the height and width is set. Can you try in the demo website again?

**Comment by amanmahajan7** [comment]
Closing due to no response. Feel free to create a new issue if you still facing this issue.
