### ISSUE TITLE
column ts error

### ISSUE THREAD

**Issue by psilva21** [adazzle/react-data-grid#2826]
trying to use the datagrid bug getting this error . someone knows how to fix it?

```
(JSX attribute) columns: readonly Column<unknown, unknown>[]
An array of objects representing each column on the grid

No overload matches this call.
  Overload 1 of 2, '(props: { rows: readonly unknown[]; selectedRows?: Maybe<ReadonlySet<Key>>; ref?: Ref<DataGridHandle> | undefined; className?: string | undefined; style?: CSSProperties | undefined; ... 31 more ...; 'data-testid'?: Maybe<...>; } & { ...; } & { ...; }): ReactElement<...>', gave the following error.
    Type 'readonly Column<SpedManagerEfdResponse, unknown>[]' is not assignable to type 'readonly Column<unknown, unknown>[]'.
```

## Environment

- `react-data-grid` version:  7.0.0-beta.11
- `react`/`react-dom` version: 17.0.2

**Comment by micpog** [comment]
Same here for exact same env setup

**Comment by amanmahajan7** [comment]
> Type 'readonly Column<SpedManagerEfdResponse, unknown>[]' is not assignable to type 'readonly Column<unknown, unknown>[]'.

This looks like a type mismatch issue and not related to RDG. Please check the [examples](https://github.com/adazzle/react-data-grid/blob/main/website/demos/CommonFeatures.tsx#L75)

**Comment by amanmahajan7** [comment]
I am closing this as it looks like a type issue. Feel free to open a discussion if you are still facing issues.
