### ISSUE TITLE
Persistent column widths

### ISSUE THREAD

**Issue by lesliev** [adazzle/react-data-grid#283]
I'd like to be able to save column widths so that they persist after a refresh. My first thought was that there would be an onColumnResize callback that I could use to save, then during the initial load I could provide those back as width: properties for each column. But there does not seem to be an onColumnResize accessible from outside ReactDataGrid. Looking at the code there are internal onColumnResize handlers. 

Is there another (better) way to save column widths, or should I be going down the path of trying to add an external callback to ReactDataGrid?

**Comment by jpdriver** [comment]
hey @lesliev -- nice idea! To me, this doesn't sound like it should be a callback thing (unless you need some event to trigger on resize)?

I guess we wouldn't want to mutate the column Array prop itself though, so we'd probably need some kind of representation of `currentColWidths` in the grid state? And then on render it takes either the initial width value from the column Array prop, or looks it up from the grid state using the `col.key` if they've since been resized..

Thoughts? :smile:

**Comment by lesliev** [comment]
Sure, but how would you save those currentColWidths on the server so they'd persist with the next refresh? Surely you'd need to save those in a callback, or how would you save them as soon as they are changed?

**Comment by jpdriver** [comment]
Ah sorry -- I'm thinking from a redux angle.. Are you using anything like that?

**Comment by lesliev** [comment]
No. But how would that work? Even if you use Redux you'd still need to send updates to the server when the column sizes change so that they could be persisted? I suppose local storage is an option but I'd prefer the widths to persist across browsers.

**Comment by bakesteve** [comment]
we store the column size state in `ReactDataGrid.state.ColumnMetrics`
currently, while you could sniff the data out from that, we dont expose the event you need. Like you said, we have `onColumnResize` on the grid itself, so we just need to expose that out from ReactDataGrid too
so:
- short term, grab from state
- we'll add that prop (or always happy to take a PR) and if its set, call out within onColumnResize (either in ColumnMetricsMixin, or we can wrap the call through to that inside ReactDataGrid)

**Comment by lesliev** [comment]
Ok, perhaps I can provide a PR for that. I'll give it a try.

**Comment by bakesteve** [comment]
should just be a matter of adding the prop to proptypes in columnMetricsMixin, and calling `if(this.props.onColumnResize) { this.props.onColumnResize(index, width); }` inside `columnMetricsMixin.onColumnResize`

**Comment by lesliev** [comment]
Thanks for the tip, that made it easy. I'll prepare a PR.

**Comment by lesliev** [comment]
https://github.com/adazzle/react-data-grid/pull/291

**Comment by lesliev** [comment]
Thanks for merging!
