### ISSUE TITLE
Exports from src/hooks/index.ts not included in npm package 

### ISSUE THREAD

**Issue by micheal-w-wells** [adazzle/react-data-grid#2834]

**Comment by micheal-w-wells** [comment]
We use it to replicate the field filtering and/or sorting stuff you guys did on your demo page.  Using just what's exported it's not possible to replicate the demo.

**Comment by TeeWallz** [comment]
@amanmahajan7 How would someone implement the demo in [HeaderFilters.tsx](https://github.com/adazzle/react-data-grid/blob/d24ee7c45b62eabfdd6f56d71fa24ad01147c278/website/demos/HeaderFilters.tsx#L8) if **useFocusRef** isn't exported?

**Comment by jasopolis** [comment]
Seconded -- the demos seem to rely on internal imports, and we'd love to build off of those but can't without exporting more

**Comment by marisancans** [comment]
I also just stumbled on this problem. I don't understand the point of demo if you can''t reproduce it quickly without going into the source code and copying out the parts needed to run the code.
