### ISSUE TITLE
Default width in `defaultColumnOptions` prop

### ISSUE THREAD

**Issue by peetjvv** [adazzle/react-data-grid#2837]
## Use case 

In our implementation we are setting a default width on all our columns. We are having to set this manually in every column since it is not supported by the DataGrid component's `defaultColumnOptions` prop.

## Proposed solution 

Add support for a default width in the DataGrid component's `defaultColumnOptions` prop so that the width doesn't have to be set manually for every column.

**Comment by amanmahajan7** [comment]
Fixed in https://github.com/adazzle/react-data-grid/pull/2838
