### ISSUE TITLE
Components cannot render over cells in the data grid

### ISSUE THREAD

**Issue by bsShoham** [adazzle/react-data-grid#2840]
## Describe the bug 

When trying to render a component (a tooltip) over the table, it doesn't render it.

## To Reproduce 

1. Set a cell formatter for a column, that renders a tooltip / other component on hover 
2. Hover over the cells and see that it doesn't render

Link to code example:
https://codesandbox.io/s/react-data-grid-tooltip-not-visible-yfb3d6

## Expected behavior 
components / tooltip should render over the table

## Environment
- Microsoft Edge (chromium) - 98.0.1108.56
- `react-data-grid` version: 7.0.0-beta.11
- `react`/`react-dom` version: 17.0.2

## Additional context 
I believe this has something to do with the `contain` css property, but I might as well be wrong.

**Comment by nstepien** [comment]
We suggest creating a portal in cases like this.
```tsx
      {visible &&
        createPortal(
          <div {...props} ref={setTooltipRef}>
            {content}
          </div>,
          document.body
        )}
```

**Comment by bsShoham** [comment]
> We suggest creating a portal in cases like this.
> 
> ```tsx
>       {visible &&
>         createPortal(
>           <div {...props} ref={setTooltipRef}>
>             {content}
>           </div>,
>           document.body
>         )}
> ```

Thank you, that's how I fixed it locally as well, I opened the issue because I assumed it's contradictive to the expected behavior, and will affect other possible usages and features, but if it is the wanted behavior, than I'll close the issue :)

**Comment by amanmahajan7** [comment]
Closing this issue as it is the expected behavior.
