### ISSUE TITLE
Not a bug: Unable to get bundle.js to work

### ISSUE THREAD

**Issue by iramtay** [adazzle/react-data-grid#2858]
First, i am new to ReactJS and this is the first project so need a lot of assistance.

I am trying to create the bundle version so that i can use the grid library.

1. Use "npm run build" 

2. Web browser is complaining that the jsx-runtime cannot be found.
        import { jsxs, jsx, Fragment } from 'react/jsx-runtime';

Tried a version for jsx-runtime but it needs require.js which is a complication that i wanted to avoid.

Can someone help to highlight how you prepare the bundle version?

**Comment by Wolf-Quiteque** [comment]
1. delete ' react-data-grid ' in the node module directory. 
2. go to your package.json and change "react-data-grid" to `"react-data-grid": "7.0.0-canary.30"`
3.npm installl
4. in your project do as follows `import DataGrid from "react-data-grid";`
5. and `import "react-data-grid/dist/react-data-grid.css";`

```

**Comment by amanmahajan7** [comment]
Closing as this is a duplicate issue. Please check https://github.com/adazzle/react-data-grid/issues/2787#issuecomment-1071978035
