### ISSUE TITLE
Add event listener for internal grid selection state

### ISSUE THREAD

**Issue by pwang347** [adazzle/react-data-grid#2884]
## Use case 
We would like to consume the grid selection state (i.e. selected cell column and row) to update styling in custom renderers (more complicated styling than CSS), as well as to use as state for certain operations.

See https://github.com/adazzle/react-data-grid/discussions/2881

Specifically, the proposed change should handle all selection state events, e.g. clicking, keyboard navigation, programmatic and so forth.

## Proposed solution 

Add API `onSelectionChange` on the `DataGridProps` interface exposing the `selectedPosition` [state](https://github.com/adazzle/react-data-grid/blob/main/src/DataGrid.tsx#L258) (and possibly `prevSelectedPosition`).

**Comment by adityatoshniwal** [comment]
@pwang347 I achieved this by using onRowClick prop

```js
  const onRowClick = useCallback((row, column)=>{
      onSelectedCellChange && onSelectedCellChange([row, column]);
  }, []);
```

**Comment by pwang347** [comment]
@adityatoshniwal Hey, thanks for the response! The main concern I had was for keyboard navigation and programmatic selection events. Are you aware of any workarounds for those aside from manual handling?

**Comment by adityatoshniwal** [comment]
@pwang347 Even I'm looking for keyboard navigation selection. Thanks for raising this.

**Comment by adityatoshniwal** [comment]
I found a way. I created an external context to wrap DataGrid, with a CustomRow.
```js
const DataGridExtrasContext = React.createContext();
<DataGridExtrasContext.Provider value={{onSelectedCellChange}}>
  <ReactDataGrid
    components={{
      rowRenderer: CustomRow,
    }}
    {...props}
  />
<DataGridExtrasContext.Provider />
```
and the CustomRow would be:
```js
function CustomRow(props) {
  const rowRef = useRef();
  const dataGridExtras = useContext(DataGridExtrasContext);
  if(props.selectedCellIdx >= 0) {
    dataGridExtras.onSelectedCellChange?.([props.row, props.viewportColumns[props.selectedCellIdx]]);
  }
  return (
    <RowInfoContext.Provider value={rowInfoValue}>
      <Row ref={rowRef} {...props} />
    </RowInfoContext.Provider>
  );
}
```

**Comment by pwang347** [comment]
@adityatoshniwal this is a great find! Thanks for figuring this out. For some reason I didn't notice that the selected cell index was a prop.
