### ISSUE TITLE
Dropdown menu showing inside cell

### ISSUE THREAD

**Issue by luisleong** [adazzle/react-data-grid#2887]
## To Reproduce 
1. install any dropdown menu (tested with '@szhsin/react-menu' and coreui components)
2. open dropdown items list (it won't be shown)

Link to code example:
{ 
    key: "options", 
    name: "Options",
    formatter(props) {
                const { row } = props;
                return (<Menu menuButton={<MenuButton>Overflow</MenuButton>}
                    overflow={'visible'} position={'auto'}>
                    {new Array(50).fill(0).map(
                        (_, i) => <MenuItem key={i}>Item {i + 1}</MenuItem>)}
                </Menu>)
            }
}

## Environment

- `react-data-grid` version: "react-data-grid": "^7.0.0-beta.11",
- `react`/`react-dom` version: "^17.0.1",

## Additional context 
![image](https://user-images.githubusercontent.com/18541440/162341223-bd936f4c-bdb1-4768-8655-bc19489bcc64.png)

**Comment by amanmahajan7** [comment]
Please check https://github.com/adazzle/react-data-grid/issues/2709#issuecomment-1010239549.

**Comment by luisleong** [comment]
> Please check [#2709 (comment)](https://github.com/adazzle/react-data-grid/issues/2709#issuecomment-1010239549).

The way I solved, was really ugly, but still did solve it. With css, remove the contain and overflow of the entire cell.

```
div[role="gridcell"][aria-colindex="1"] {
  contain: none !important;
  overflow: visible !important;
}
```

**Comment by vine1993** [comment]
I did resolve with css as well.
`.rdg .rdg-row .rdg-cell.rdg-editor-container {
    padding:0;
    overflow: visible;
    contain: size style;
}`

**Comment by ding-si-han** [comment]
For those attempting to have a dropdown for the column header, changing the rdg-header-row class does the fix (kudos to @vine1993 for the css! 🎉 )

`.rdg .rdg-header-row .rdg-cell { padding:0; overflow: visible; contain: size style; }`

**Comment by amanmahajan7** [comment]
Closing as this is not bug in RDG.
