### ISSUE TITLE
Delete Button Per Row 

### ISSUE THREAD

**Issue by pouriamolaee** [adazzle/react-data-grid#2891]
## Use case
The ability to add a custom-designed button to each row to delete that row.
## Proposed solution 
If possible, I want its functionality to be under the formatter option of the column. There should be a way to mutate the primary state of the rows to an updated one that excludes the deleted row.

**Comment by amanmahajan7** [comment]
It can be implemented using a custom formatter that renders a button. Upon click you can delete the row.
