### ISSUE TITLE
Missing every second horizontal divider at 90% and 110% browser zoom

### ISSUE THREAD

**Issue by SO-Eng** [adazzle/react-data-grid#2901]
## Describe the bug 
When Browser is zoomed to 90% or 110%, Datagrid does not show every second horizontal divider line.

## To Reproduce 

1. Open [Example Page](https://adazzle.github.io/react-data-grid/#/common-features)
2. Zoom to 90% or 110%

## Environment

- `react-data-grid` version: Example Page should be newest?
- `react`/`react-dom` version: See example page

## Additional context:
This is irritating for user when they allways work in browser with 90% or 110% zooming.
They raised a ticket to fix that, but this is not in our responibility.
So they saw at neighbour's place, they have all dividers, but not themself. So we also took a time to figure out is caused by zooming.

**Comment by peetjvv** [comment]
I've also noticed this on certain screens. Suspect in our case it is due to Windows' display scaling.

**Comment by hatem-marzougui** [comment]
i fix that by overriding contain property in rdg-cell className

'.rdg-cell': {
      contain: 'none !important',
    },

**Comment by nstepien** [comment]
I've opened a PR to address this, and opened a Chromium issue upstream so hopefully it'll be fixed upstream without needing a workaround in react-data-grid.
Thanks for reporting and finding a clue.

**Comment by nstepien** [comment]
I've published `7.0.0-beta.13` with the fix
