### ISSUE TITLE
Unable to load more than 100000 rows.

### ISSUE THREAD

**Issue by yogeshmahajan-1903** [adazzle/react-data-grid#2903]
## To Reproduce 

1.Clone react-data-grid repo.
2.Run yarn install.
3.Use infinite scroll example from [here](https://github.com/adazzle/react-data-grid/blob/main/website/demos/InfiniteScrolling.tsx) 
4.Modify loadMoreRows to 10000 [here](https://github.com/adazzle/react-data-grid/blob/main/website/demos/InfiniteScrolling.tsx#L101)
5.Modify createRows to 100000 [here](https://github.com/adazzle/react-data-grid/blob/main/website/demos/InfiniteScrolling.tsx#L93)
6.Run ppm start
7.Open infifnte scroll example.

Link to code example:

## Environment

- `react-data-grid`  7.0.0-beta.12 version:
- `react`/`react-dom` 18.0.0 version:

## Additional context 
<img width="1787" alt="Screenshot 2022-05-04 at 4 08 13 PM" src="https://user-images.githubusercontent.com/16016019/166667646-90f86e7d-7b1c-4a42-bc93-9141fda2ba2f.png">

**Comment by adityatoshniwal** [comment]
@amanmahajan7 @nstepien the current implementation uses `grid-template-rows: 22px repeat(20000, 22px);` (22px height of row from million cells example) to set scrollable height of the grid. But, there is a limitation of 100,000 rows in Chrome and similar in FF. So the scrollable height always max out to 100,000 x 22 = 2200022. Beyond that, the scrollbar doesn't go and rows cannot be loaded.

**Comment by adityatoshniwal** [comment]
@amanmahajan7 @nstepien I don't think grid-template-rows is suitable and not the way to go ahead because of its limitations.

**Comment by adityatoshniwal** [comment]
This is a nice example of how it can be done - https://codepen.io/ykadosh/pen/ZdxeYY

**Comment by amanmahajan7** [comment]
It is by design to use `grid-template-rows`. Without `grid-template-rows`, it won't be possible to implement features like [auto column resize](https://github.com/adazzle/react-data-grid/pull/2793), [flex width columns](https://github.com/adazzle/react-data-grid/pull/2839), and [rowSpan](https://github.com/adazzle/react-data-grid/pull/2801). I would recommend opening a bug in chrome and FF and use pagination for now.

**Comment by adityatoshniwal** [comment]
@amanmahajan7 Proposal is not to remove `grid-template-columns`, but only `grid-template-rows`. Display will still be `grid`. Can you take a look at the PR - https://github.com/adazzle/react-data-grid/pull/2906  once ? The features you mentioned are working with PR as well.

**Comment by adityatoshniwal** [comment]
I have raised a bug with chromium as well - https://bugs.chromium.org/p/chromium/issues/detail?id=1325307
