### ISSUE TITLE
how to combine filtering and sorting in a column

### ISSUE THREAD

**Issue by hatem-marzougui** [adazzle/react-data-grid#2909]
i would like to combine filtering and sorting features to a column using the latest version of react-data-grid
this is my "FilterRenderer" component
![FilterRenderer](https://user-images.githubusercontent.com/66776531/168560593-15e02b59-08f6-4a4a-bee0-9f3044b33f9e.png)
  
this is how i pass headerRenderer
![headerRenderer](https://user-images.githubusercontent.com/66776531/168561085-6ed786a8-9291-4278-a8d9-c1590616f531.png)

i would like to make something like that
![Screenshot from 2022-05-16 10-13-45](https://user-images.githubusercontent.com/66776531/168559924-fa940042-bc7a-4f2c-ad4a-9bc066c3031f.png)

**Comment by shulamitco** [comment]
Where did you import "useFocusRef" from?

**Comment by hatem-marzougui** [comment]
i declare it like in the source code
![useFocusREf](https://user-images.githubusercontent.com/66776531/168783032-601656d4-af45-4f91-a467-5f7677f0b55e.png)

**Comment by hatem-marzougui** [comment]
i added i HeaderRenderer component  imported from 'react-data-grid' and it works 
![headerRender](https://user-images.githubusercontent.com/66776531/168783575-b5f7c275-5691-4051-bfda-dff9d3ba2b43.png)

**Comment by Randhir01** [comment]
> i would like to combine filtering and sorting features to a column using the latest version of react-data-grid this is my "FilterRenderer" component ![FilterRenderer](https://user-images.githubusercontent.com/66776531/168560593-15e02b59-08f6-4a4a-bee0-9f3044b33f9e.png)
> 
> this is how i pass headerRenderer ![headerRenderer](https://user-images.githubusercontent.com/66776531/168561085-6ed786a8-9291-4278-a8d9-c1590616f531.png)
> 
> i would like to make something like that ![Screenshot from 2022-05-16 10-13-45](https://user-images.githubusercontent.com/66776531/168559924-fa940042-bc7a-4f2c-ad4a-9bc066c3031f.png)

Could you please share the full souce code for filter and sorting features?

**Comment by Shubhanglilly** [comment]
@Randhir01 Any update on full source code for combining filter and sorting features together ?
