### ISSUE TITLE
scrollToColumn not working

### ISSUE THREAD

**Issue by miracle0930** [adazzle/react-data-grid#2910]
## Describe the bug 
When a column is out side current viewport, using ```scrollToColumn``` is not bring that column into the viewport
## To Reproduce 

1. Using the ```CommonFeature``` file.
2. Setting a ref to ```<DataGrid>```
3. let it scroll to column 10
4. not scrolling

Link to code example:

## Expected behavior 
Bring that column into the viewport
## Environment

- `react-data-grid` version: 7.0.0-beta12
- `react`/`react-dom` version: 18

## Additional context 
![image](https://user-images.githubusercontent.com/15270493/168569027-0f5e0d19-311d-4e3c-a832-30fb342de2c4.png)
I briefly went through the source code and found this may be the reason (maybe I am wrong). I guess we should remove the ```!```. It does not make sense to ```return``` when the cell is not within selection bounds (because this is why to want to use ```scrollToColumn```).

**Comment by hyusetiawan** [comment]
I am facing the same issue, I am not sure if this is fixed or not, I am testing this on 7.0.0-beta.19
