### ISSUE TITLE
Rows don't fill entire width of grid causing double right border

### ISSUE THREAD

**Issue by sansSpoon** [adazzle/react-data-grid#2934]
## Describe the bug 
Rows don't fill entire width of grid causing double right border.
I noticed this when working on my local project. I double checked some of the examples and it's showing there too:

https://adazzle.github.io/react-data-grid/#/columns-reordering
https://adazzle.github.io/react-data-grid/#/context-menu
https://adazzle.github.io/react-data-grid/#/grouping

## To Reproduce 

1. Reproduced on the examples site

### Local environment
- `react-data-grid` version: 7.0.0-beta.12
- `react`/`react-dom` version: 18.0.0

## Additional context 
This is happening in both Chrome and FF. Not sure if this is an intended gap or bug. I've seen earlier reports of this in the issues log, but it was for earlier versions. Maybe a regression?

Is it possible to fix this so there is no gap?

<img width="631" alt="Screen Shot 2022-06-19 at 9 35 46 pm" src="https://user-images.githubusercontent.com/22439699/174483826-74fd6485-f138-4cbc-9b67-e28a59a4b0a5.png">
<img width="632" alt="Screen Shot 2022-06-19 at 9 35 58 pm" src="https://user-images.githubusercontent.com/22439699/174483830-119c0191-39b2-4b36-a8d4-2d578f41f2c1.png">

**Comment by amanmahajan7** [comment]
Can you check if this is still an issue with the latest version? I am not able to reproduce it

**Comment by amanmahajan7** [comment]
Closing due to lack of response.
