### ISSUE TITLE
How to update width or the grid?

### ISSUE THREAD

**Issue by IAkumaI** [adazzle/react-data-grid#295]
For example, I have a side menu, which changes main content width.
After menu hide grid in the main content do not change width automaticaly.
So, how can I trigger width update manually?

**Comment by IAkumaI** [comment]
Oh, I found it.

Just call grid's ```updateMetrics``` method.
Maybe you should add this to the documentation?

**Comment by AlexSugak** [comment]
+ 1 for documentation.
Spent a lot of time on this.

**Comment by bakesteve** [comment]
sure - happy to take a pull on that, or we'll add it in.
Also looking to add per component docs on the API soon. At the moment, the docs are very heavily based around the examples, rather than around the API and/or flow for updates that happen outside the grid

**Comment by kamalbennani** [comment]
Can you please tell me how to call `updateMetrics`, knowing that a have only a reference to `ReactDataGrid Component`

**Comment by IAkumaI** [comment]
@kamalbennani justc call this.refs.grid.updateMetrics();

**Comment by brian-gates** [comment]
FWIW, this also works:

```
window.dispatchEvent(new Event('resize'));
```

**Comment by tiagofernandez** [comment]
Just FYI, a possible hack in case `window.dispatchEvent(new Event('resize'));` fails would be:
`$('.react-grid-Cell').click();`

**Comment by Matschick** [comment]
this.refs.grid.updateMetrics(); doesn´t works for me. 
Any other tips to call updateMetrics ? Expand the Grid works but decrease doesn´t work.

**Comment by lavor** [comment]
@Matschick I solved the problem with not resizing a grid on decrease by wrapping the grid with absolute positioned div (inside the relative positioned one):
```
.relativeWrapper {
  position: relative;
}
.absoluteWrapper {
  position: absolute;
  width: 100%;
}


<div class="relativeWrapper">
  <div class="absoluteWrapper">
    <ReactDataGrid />
  </div>
<div>

**Comment by Matschick** [comment]
Thanks, that solves my problem. 
I have to set the height of the relativWrapper and it works now fine ;)

**Comment by erensahin** [comment]
I have noticed that grid's updateMetrics method no longer exists in v4. 
Instead, you should use metricsUpdated method.

**Comment by rishabh0206** [comment]
This worked for me - 

setTimeout(() => {
            window.dispatchEvent(new Event('resize'));
}, 1000);
