### ISSUE TITLE
Inconsistent max # of row handling across browsers

### ISSUE THREAD

**Issue by jzombie** [adazzle/react-data-grid#2950]
## Describe the bug 

![2022-07-10_16-17](https://user-images.githubusercontent.com/1139657/178164020-1d7e6e11-14f4-46af-8c53-29b0131c8ec0.png)

## To Reproduce 

1. Create a 9,999.999 rows.

Chrome will skip the row indexes at the end, and only render ~100,000 rows.  Firefox will do the same, and only render nearly ~10,000 rows.  Safari is the closest thing to making the goal, but has the worst performance.

Link to code example:

## Environment

- `react-data-grid` version: 7.0.0-beta.13
- `react`/`react-dom` version: 18.2.0

**Comment by amanmahajan7** [comment]
This is due to browser limitation of handling max number of rows in CSS grid. Please check https://github.com/adazzle/react-data-grid/issues/2903

**Comment by jzombie** [comment]
I wonder if the virtualization strategy being used is not really virtualizing.
