### ISSUE TITLE
Cannot add sort functionality

### ISSUE THREAD

**Issue by JayYoungman** [adazzle/react-data-grid#2955]
Trying to implement sorting into our grid.

Looking at the docs and the commonFeatures.tsx file, it seems to use an OnSortColumnChange prop which takes a setState action.

Trying to use this throws a TS error

Property 'onSortColumnsChange' does not exist on type 'IntrinsicAttributes & GridProps<Row, any>'.\

When inspecting the types in node modules i don't see this anywhere?

Also, adding the sortable: true, to the column the markup for the column header is not correct. The span it creates which should have an svg for the arrow is an empty element. so its not even showing the arrow when clicking the header cell.

Can someone direct me to the correct documentation for implementing sort functionality in the grid.

I'm using "react-data-grid": "7.0.0-canary.47",

Thanks

**Comment by amanmahajan7** [comment]
I am closing this ticket as there are many examples of adding sort functionality. This seems like a TS error in your project
https://github.com/adazzle/react-data-grid/blob/main/website/demos/ColumnsReordering.tsx#L72
https://github.com/adazzle/react-data-grid/blob/main/website/demos/CommonFeatures.tsx#L314

**Comment by paustint** [comment]
Nice, thank you so much!
