### ISSUE TITLE
onRowsChange column is undefined on first execution

### ISSUE THREAD

**Issue by zakaryan2004** [adazzle/react-data-grid#2963]
## To Reproduce 

1. Start with the MasterDetails.tsx example.
2. Make a minor change in line 113 (add a new column variable to RowsChangeData argument decoupling):
`function onRowsChange(rows: DepartmentRow[], { column, indexes }: RowsChangeData<DepartmentRow>) {`
3. Observe the value of the column variable
`console.log(column);`
4. The value is `undefined` on the first table change, while on subsequent changes it's populated as expected.

Link to code example:
https://github.com/adazzle/react-data-grid/blob/main/website/demos/MasterDetail.tsx

## Expected behavior 

The variable should always be populated with the column where the change happened.

## Environment

- `react-data-grid` version: master
- `react`/`react-dom` version: 18.1.0

**Comment by nstepien** [comment]
Thanks for the bug report!
This is now fixed in `7.0.0-beta.14`
