### ISSUE TITLE
Column Width Resize Bug

### ISSUE THREAD

**Issue by faithod** [adazzle/react-data-grid#2978]
Hi, I have found a bug where every time I manually resize a column and then update the grid column props (changing the width), the width doesn't change. It seems as if the the grid only listens to that width property when you haven't manually resized it.

**Steps To Reproduce:**

1. set the column width from props e.g. 

```
columns = [{
...
      resizable: true,
      width: 200,
},...]
```
2. manually resize the grid with your mouse
3. update grid props (changing the width property)

Expected: column widths should change accordingly
Actual behaviour: the column widths stay the same, completely ignoring the width property

I am using react-data-grid version 7.0.0-canary.47, react/react-dom version ^16.13.1

**Comment by faithod** [comment]
is it possible to get this looked at urgently please?

**Comment by m1lka** [comment]
Hello! we have a similar problem. Is there any deadline for a decision?

**Comment by amanmahajan7** [comment]
Duplicate issue https://github.com/adazzle/react-data-grid/issues/2042
