### ISSUE TITLE
Exception is thrown for old versions of Chrome

### ISSUE THREAD

**Issue by mctep** [adazzle/react-data-grid#2994]
## Describe the bug 

When I open react data grid in Chrome 81.0.4044.133 exception is thrown:

```
Uncaught TypeError: Cannot read property '0' of undefined
```

## To Reproduce 

1. Open main page in Chrome version less than 84
2. Look at console

## Expected behavior 

There should not be the exception.

## Environment

- `react-data-grid` version: [7.0.0-beta.15](https://www.npmjs.com/package/react-data-grid/v/7.0.0-beta.15)
- `react`/`react-dom` version: [18.2.0](https://www.npmjs.com/package/react/v/18.2.0)

## Additional context 

This exception is thrown by `contentBoxSize` property usage in [useGridDimensions.ts](https://github.com/adazzle/react-data-grid/blob/625fad550d7457612bea00af668787711fd3f518/src/hooks/useGridDimensions.ts#L31).
This property is [not available](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry/contentBoxSize#browser_compatibility) in Chrome versions less than 84.

**Comment by tlehtimaki** [comment]
I have thought that it is a security risk to use old versions of browsers? Why would it be important to support chrome versions other than latest?

**Comment by amanmahajan7** [comment]
RDG only supports [evergreen browsers](https://github.com/adazzle/react-data-grid/blob/main/browserslist) so closing this issue.
