### ISSUE TITLE
A way to customize `priority` number component on multi-sort

### ISSUE THREAD

**Issue by godon019** [adazzle/react-data-grid#3000]
## Use case 
When you customize sort icon through `<DataGridDefaultComponentsProvider />`, you might also want to customize/access to `priority` number shown up in multi-sort

For example
- you want to give some color that match to custom icon
- you want to give space between custom sort icon and `priority` number only when the `priority` number is shown

You can kind of see the problems [here](https://codesandbox.io/s/eager-butterfly-qp15x4?file=/src/App.tsx:1438-1471)

## Proposed solution 
maybe provide a prop `sortPriority` just like the way `sortIcon` does ?

**Comment by amanmahajan7** [comment]
I think this makes sense. We can add `sortPriority` renderer
