### ISSUE TITLE
Column spanning in summary row

### ISSUE THREAD

**Issue by peetjvv** [adazzle/react-data-grid#3005]
## Use case 

If you have very narrow columns (e.g. the `SelectColumn` which has a width of 35px) you need to put the content of your summary row in the second/third/etc. column (see screenshot below), because it won't fit in those narrow columns. It would be nice if we can span that text across columns in the summary row as we can do in the table itself like you've done in [the column spanning demo](https://adazzle.github.io/react-data-grid/#/column-spanning). That way the summary row text can always start from the far left regardless of the size of the columns.

![image](https://user-images.githubusercontent.com/22648295/187390356-f85e33c8-690e-4b15-a5b0-e28817f2ad19.png)

## Proposed solution 

Have the option to specify that the content of a column in the summary row should span across multiple columns. So that it can look something like this:

![image](https://user-images.githubusercontent.com/22648295/187391031-74640fb2-cea1-42ee-baa6-e8151f73be0d.png)

**Comment by amanmahajan7** [comment]
This is already supported
https://github.com/adazzle/react-data-grid/blob/main/src/types.ts#L243

**Comment by peetjvv** [comment]
Thank you. I'll take a look at this when I get to work on this part of our webapp again.
