### ISSUE TITLE
Can you make a documentation?

### ISSUE THREAD

**Issue by samislam** [adazzle/react-data-grid#3015]
## Use case
Learn this module 

## Proposed solution
Can you make up documentation for the module? I can't find any way I can learn this library except the npm page which doesn't include enough helpful information.

for such a rich amount of effort, it's a shame to publish a great package like that without documentation. 
how am I going to use it then?

**Comment by tlehtimaki** [comment]
I see that there is https://github.com/adazzle/react-data-grid/issues/2575 about ongoing documentation efforts. Maybe you can help the maintainers and chip in your effort? The current https://adazzle.github.io/react-data-grid/ site offers quite a lot of examples too, but the documentation is not yet complete.

**Comment by tlehtimaki** [comment]
Also the code for those demos https://github.com/adazzle/react-data-grid/tree/main/website/demos might help you out.

**Comment by shusiner** [comment]
I am also looking at documentation for this library but I guess the demo code looks like it can be of great help. I think we should explicitly put the link to the demo code in README.md and tell people that they can copy those code and try it out. It didn't occur to me at the very beginning as I am used to looking for documentation

**Comment by amanmahajan7** [comment]
Closing in favor of https://github.com/adazzle/react-data-grid/issues/2575

**Comment by Ben-CA** [comment]
Currently there's the Readme:
https://github.com/adazzle/react-data-grid/blob/main/README.md

The examples:
https://adazzle.github.io/react-data-grid/#/CommonFeatures

And the code behind the examples:
https://github.com/adazzle/react-data-grid/blob/main/website/routes/AllFeatures.lazy.tsx
