### ISSUE TITLE
Not working in the Safari browser

### ISSUE THREAD

**Issue by abince** [adazzle/react-data-grid#3033]
## Describe the bug 
The grid does not work in Safari
## To Reproduce 

1. Open [the link](https://adazzle.github.io/react-data-grid/#/common-features) through the Safari browser

Link to code example:

## Expected behavior 

Should work like other browsers

## Environment

- `react-data-grid` version: 7.0.0-beta.14 (Same issue even in 7.0.0-beta.18)
- `react`/`react-dom` version: 18.1.0

## Additional context 
![image](https://user-images.githubusercontent.com/51189054/191427862-482d9bcc-9cee-4375-8953-d90c425cac5d.png)
![image](https://user-images.githubusercontent.com/51189054/191428056-dd8b1e4e-e446-4024-a06d-cd1adb06ba03.png)

**Comment by amanmahajan7** [comment]
Which version of safari are you using?

**Comment by paustint** [comment]
This works fine in Safari for me with the provided link and from my local project.

![image](https://user-images.githubusercontent.com/5461649/197445073-868af51b-025a-44eb-87b2-618bb267a372.png)

**Comment by csulit** [comment]
Mine is working.

**Comment by xuyunan** [comment]
Same issue in 钉钉app, any updates?

**Comment by damnitrahul** [comment]
I see the same issue on `Version 14.1.1 (16611.2.7.1.4)`.

**Comment by amanmahajan7** [comment]
Please ensure you are importing `styles.css`.
`import 'react-data-grid/lib/styles.css';`

Also, only latest version of safari is supported.

**Comment by medvedev-da** [comment]
Hi guys!

You've developed the great grid that fits my project requirements up to 90%, but... Seems like it stopped working correctly right after 7.0.0.-beta-16 in Safari and on Huawei tablets (Huawei browsers).

I see it's working more or less in 7.0.0-beta-16, but not in later versions. **Do you have any plans to fix it?**

Starting from 7.0.0.-beta-17 I needed to add the import _import "react-data-grid/lib/styles.css"_, and starts crashing... Before I haven't had this import at all.

**Comment by isacvale** [comment]
I'm getting this bug on Safari 14.1, but not on earlier versions. I believe it is because of browser issues with `display: contents`.
The `grid` defines template columns, then there's `row`s - divs with display contents-, then comes the `cell`s.

Any workaround?

**Comment by amanmahajan7** [comment]
We need `display:contents` and I am not sure if there is a workaround. I am closing this issue as it is working in the latest version of safari

**Comment by rahulserver** [comment]
I am on safari latest version and grid is not working. I have correctly imported the style.css file. It works fine in chrome, but not in safari.
<img width="1062" alt="image" src="https://github.com/adazzle/react-data-grid/assets/5101740/1a48cb1c-4581-421c-ac68-2d8c20d81cbf">

my safari version: 16.4
<img width="276" alt="image" src="https://github.com/adazzle/react-data-grid/assets/5101740/13007a3b-5142-47f5-af47-40528e2906e9">

**Comment by rahulserver** [comment]
also if this helps, here is my code(next js app index.ts)

```
import 'react-data-grid/lib/styles.css';
import DataGrid from 'react-data-grid';
const columns = [
  { key: 'id', name: 'ID' },
  { key: 'title', name: 'Title' }
];

const rows = [
  { id: 0, title: 'Example' },
  { id: 1, title: 'Demo' }
];


export default function Home() {
  return (
    <>
      <DataGrid columns={columns} rows={rows} />
    </>
  )
}

```

package.json:
```

{
  "name": "errorv13",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@types/node": "20.11.19",
    "@types/react": "18.2.57",
    "@types/react-dom": "18.2.19",
    "next": "14.1.0",
    "react": "18.2.0",
    "react-data-grid": "^7.0.0-beta.42",
    "react-dom": "18.2.0",
    "typescript": "5.3.3"
  }
}

```

**Comment by superlucky84** [comment]
@rahulserver After struggling with Safari 16.x for a while, I upgraded to 17.5 and it worked fine. good luck
