### ISSUE TITLE
Toggling the table filter clears the text value, but the filter is still in place

### ISSUE THREAD

**Issue by jbgarr** [adazzle/react-data-grid#304]
If you filter a column, then toggle the filter row off by clicking the "Filter Rows" button, then click the button again to bring back the filter row the text is cleared, but the columns remain filtered. Either the text should stay in the filter inputs or the filters should be reset when the filter row is toggled off and all rows should be shown again.

**Comment by mttomorowicz** [comment]
'Filterable grid' and' Custom filters' example js code has now been updated - clearing all existing filters in ReactDataGrid component's 'onClearFilters' hook enables required behavior (unfiltered set of rows is loaded).
