### ISSUE TITLE
[v7-beta] Datepicker Editor issue

### ISSUE THREAD

**Issue by farooq7124** [adazzle/react-data-grid#3042]
Hi Team

I am trying to use custom editor for Date column, Where i want to have a date picker on cell edit. 

The issue is it is not showing the date picker due to zindex or position relative property of the cell css. Please suggest how to fix this issue.

[Sample Example](https://codesandbox.io/s/react-data-grid-v7-beta-forked-znr9ww?file=/src/App.tsx
)

Thanks in advance

**Comment by thinhbg2812-2** [comment]
lol ???
