### ISSUE TITLE
cannot install my fork using "npm install" ?

### ISSUE THREAD

**Issue by eladbui** [adazzle/react-data-grid#305]
Hi,

I forked my own copy of react-data-grid and clone it but every time I'm trying to install it using "npm install" command I got the same error 

Error: ./src/addons/grids/ReactDataGrid.js
Module parse failed: C:\webstudio\import-cp\client\node_modules\react-data-grid\src\addons\grids\ReactDataGrid.js Unexpected token (16:5)
You may need an appropriate loader to handle this file type.

[npm-debug.txt](https://github.com/adazzle/react-data-grid/files/246450/npm-debug.txt)

Can you please tell was I'm doing wrong ? I attached npm-debug.log for more info

Thanks!
Elad

**Comment by ryan4888** [comment]
Update npm
