### ISSUE TITLE
Data grid row selection issue

### ISSUE THREAD

**Issue by Rk1131** [adazzle/react-data-grid#3052]
When we select row one by one to all, the all row selector checkbox does not get checked.
I have the rowSelection function as it was mentioned in the documentation.
```
const rowSelection = {
    showCheckbox: true,
    enableShiftSelect: true,
    onRowsSelected: onRowsSelected,
    onRowsDeselected: onRowsDeselected,
    selectBy: {
      keys: {
        rowKey: 'id',
        values: selectedRows
      }
    }
  };
```
These are my custom functions :- 
 const onRowsSelected = rowArr => {
    let rws = [],
      sd = [...selectedRows, ...rowArr.map(r => r.row.id)];
    setSelectedRows(sd);
  };

  const onRowsDeselected = rowArr => {
    let rws = [],
      sd = selectedRows.filter(
        i => rowArr.findIndex(r => r.row.id === i) === -1
      );
    setSelectedRows(sd);
  }; 

I have using the version : "react-data-grid": "5.0.4"

**Comment by amanmahajan7** [comment]
react-data-grid v5 is no longer supported we recommend upgrading to v7. beta

https://github.com/adazzle/react-data-grid/tree/main/website
https://adazzle.github.io/react-data-grid/#/common-features
