### ISSUE TITLE
Data grid re-sizing issue

### ISSUE THREAD

**Issue by Rk1131** [adazzle/react-data-grid#3053]
When i resize the columns it takes extra space around the data grid. It does not auto resize as per the page size.
I am not using any custom css for grid, its the default.
I am using the version :- "react-data-grid": "5.0.4"

**Comment by amanmahajan7** [comment]
react-data-grid v5 is no longer supported we recommend upgrading to v7. beta

https://github.com/adazzle/react-data-grid/tree/main/website
https://adazzle.github.io/react-data-grid/#/common-features

**Comment by Rk1131** [comment]
I am still facing the issue after updating the version.
Current version :- "react-data-grid": "7.0.0-beta.12",

**Comment by vishal-vc** [comment]
@amanmahajan7

**Comment by amanmahajan7** [comment]
Can you please create a reproducible example?

**Comment by Rk1131** [comment]
@amanmahajan7 Are you able to reproduce it?

**Comment by darren10201** [comment]
> https://adazzle.github.io/react-data-grid/#/columns-reordering

+1 
@amanmahajan7  if the side panel is a drawer, this bug will make the list unusable. setting the last column's minWidth:'auto' will solve this but it disables resizing on everything
