### ISSUE TITLE
Styles for 6

### ISSUE THREAD

**Issue by andrewvlgafc** [adazzle/react-data-grid#3072]
Hello. Where I can find styles.css for grid 6 version. There is import 'react-data-grid/lib/styles.css' no file. And in lib folder no any css files
Thanks

**Comment by amanmahajan7** [comment]
RDG version 6 is not longer supported and we recommend upgrading to 7 beta.

**Comment by ybrikeeg** [comment]
@amanmahajan7 What css file should we import on v7 beta? Shouldn't it still be the same?

I'm importing `import 'react-data-grid/lib/styles.css'` in my `_app.tsx` but the CSS styles aren't being applied on deployments (they are on localhost however).
