### ISSUE TITLE
Grid can not display over 10k rows on FireFox

### ISSUE THREAD

**Issue by levuhao1993** [adazzle/react-data-grid#3087]
data rendered, but grid only show maximum 10k records on firexfox browser (Chrome / Eagle browser testing ok).
Please check attach img.

## Environment

- `react-data-grid` version: 7.0.0-beta.19
- `react`/`react-dom` version: 18.0.0

## Additional context 
- before sorting (scroll to end of grid)
![ảnh](https://user-images.githubusercontent.com/118587842/202836278-e9e643d8-ebfd-45de-a2da-8a42a3817883.png)
- after sorting (scroll to end of grid)
![ảnh](https://user-images.githubusercontent.com/118587842/202836337-39671a1e-c5ae-4fa0-8de7-b2528121e66a.png)

**Comment by dvmoritzschoefl** [comment]
Hi @levuhao1993. I had a similiar problem but I think this is no bug. This library uses a real CSS grid layout in the background to virtualize the cells. The limits on how many cells can be displayed in a grid seems to be up to the browser and different between FF/Chrome

In my tests I got values of 1 million cells for FF and 10 million for Chrome

Hope that helps

**Comment by amanmahajan7** [comment]
This is by design. Please check https://github.com/adazzle/react-data-grid/issues/2903
