### ISSUE TITLE
columns-reordering problem on NextJS

### ISSUE THREAD

**Issue by phonyman** [adazzle/react-data-grid#3099]
## Describe the bug 
Table does not generate on NextJS with sample code columns-reordering

## To Reproduce 

1.Create new project NextJS with commend 
                       npx create-next-app@latest 
2. install package
                          npm install react-data-grid
                          npm installreact-dnd react-dnd-html5-backend

I'm copy code from your example and modify a little bit for run this sample  (change import from "src" to import form "react-data-grid"
[Link to code example:](https://github.com/adazzle/react-data-grid/blob/main/website/demos/ColumnsReordering.tsx)

but table does not generate. Please advise for the way for fix this problem,
![ColumnOrder](https://user-images.githubusercontent.com/41562472/205023384-2eac68e9-78de-4524-bd67-61ca7b433c90.jpg)

## Environment

"@types/node": "18.11.10",
    "@types/react": "18.0.25",
    "@types/react-dom": "18.0.9",
    "eslint": "8.28.0",
    "eslint-config-next": "13.0.5",
    "next": "13.0.5",
    "react": "18.2.0",
    "react-data-grid": "^7.0.0-beta.20",
    "react-dnd": "^16.0.1",
    "react-dnd-html5-backend": "^16.0.1",
    "react-dom": "18.2.0",
    "typescript": "4.9.3"

**Comment by darren10201** [comment]
show your code not other people's code that clearly works

**Comment by phonyman** [comment]
@darren10201, I'm newbie for reactjs, I saw sample of react-data-grid: https://adazzle.github.io/react-data-grid/#/common-features  is very exciting, but I can't find full document or example code for run with full function. Could you advise for find example code for my learning?

**Comment by aitorllj93** [comment]
@phonyman you can find exactly what you want [here](https://github.com/adazzle/react-data-grid/blob/main/website/demos/CommonFeatures.tsx). Also, for the issue you were facing, I think you forgot to load the styles with `import 'react-data-grid/lib/styles.css';`

**Comment by roquib** [comment]
> @phonyman you can find exactly what you want [here](https://github.com/adazzle/react-data-grid/blob/main/website/demos/CommonFeatures.tsx). Also, for the issue you were facing, I think you forgot to load the styles with `import 'react-data-grid/lib/styles.css';`

I was upgrading my project from the next 12 to 13, it solves the issue.

**Comment by phonyman** [comment]
@roquib , @aitorllj93 
It's working, Thank you very much for your support. :)
