### ISSUE TITLE
Headers with colSpan change columns when scrolling horizontally

### ISSUE THREAD

**Issue by paustint** [adazzle/react-data-grid#3101]
## Describe the bug 
When headers span multiple columns, the headers change columns when scrolling vertically.

## To Reproduce 

1. Create a table that has a decent number of columns (enough to have to scroll horizontally)
2. Create headers that span multiple columns (e.x. `colSpan: (args) => (args.type === 'HEADER' ? 4 : undefined),`)
3. Ensure the viewport/window is setup where there is horizontal scrolling required to view all the columns
4. Scroll and notice that the headers move around and change which columns they span 

Link to code example: https://codesandbox.io/s/tender-colden-dp7p0p?file=/src/App.tsx

## Expected behavior 
Headers should never change columns

## Environment

- `react-data-grid` version: `7.0.0-beta.20`
- `react`/`react-dom` version: `17` and `18`

## Additional context 

Here are some screenshots that show the problem when scrolling horizontally:

![image](https://user-images.githubusercontent.com/5461649/205449706-b9d4cc5f-e6aa-46b8-b81b-cf93c8303ba0.png)

After scrolling to the right a little bit, the header changes spanned columns

![image](https://user-images.githubusercontent.com/5461649/205449760-c4ed0769-899f-4a07-9caf-6b5f03953e6e.png)

colSpan for normal rows appears to be correctly calculated and stable

![image](https://user-images.githubusercontent.com/5461649/205451056-eafd632c-04ae-405c-b126-8a9b71f1263d.png)

**Comment by amanmahajan7** [comment]
The colspan values were incorrect. If a column spans another column then the spanned column should not have colspan. Check the updated example
https://codesandbox.io/s/tender-stallman-0zxqlv?file=/src/App.tsx

**Comment by paustint** [comment]
Nice, thank you so much!
