### ISSUE TITLE
Support for React 16 + 17

### ISSUE THREAD

**Issue by kycutler** [adazzle/react-data-grid#3111]
## Use case

React 18 reached stable less than a year ago. Many projects have legacy dependencies that do not yet claim support for React 18. By removing support for the older (but generally compatible) React versions in #3012, these projects must now take a risk in consuming RDG by ignoring the react>=18 peer requirement.

## Proposed solution

Unless there is a change in RDG that truly requires React 18, please re-add support for React 16 and 17 in the package dependencies.

**Comment by mihbel** [comment]
Agree with @kycutler. We started the project a year ago with React 17. Upgrading to version 18 is now almost impossible. It would be great to get support for React 17 again.

**Comment by amanmahajan7** [comment]
RDG uses [React 18 APIs](https://github.com/adazzle/react-data-grid/blob/main/src/DataGrid.tsx#L3) so unfortunately older versions are not supported.

**Comment by amanmahajan7** [comment]
I am closing this issue for now as it at this point supporting older versions is not possible.
