### ISSUE TITLE
Hide/Show columns over context menu in header

### ISSUE THREAD

**Issue by Silvallis** [adazzle/react-data-grid#3127]
## Use case
Right-clicking the header of a column will open a context menu with the option to hide this column. Alternatively, there is a point 'Columns' which opens a submenu with a checkbox followed by the column name for every column. Here you can check/uncheck several columns. 

## Proposed solution
Adding two new column options:

- hideable
- hidden

When the hideable options is set to true, you can open the mentioned context menu to hide the columns with this option. This will toggle the hidden state of the column.
When rendering the grid it will skip all columns where hidden is true.

**Comment by amanmahajan7** [comment]
We do not have plans to support this feature. However, this can be implemented using custom `renderHeaderCell` which can implement the context menu. Upon click you should be able to hide the column manually.

```
const visibleColumns = columns.filter(c => !hiddenColumns.has(c.key));
```

**Comment by iamrakhmatov** [comment]
but do we still can have filter for this column? if we just remove it from columns list?
I have a use case where user can hide the column but still be able to filter by hidden column as well?

**Comment by paustint** [comment]
In that case you will need to manage state of all columns and filters along with the visible columns and ensure that your filtering logic does not honor just the visible columns.
