### ISSUE TITLE
element?.scrollIntoView is not a function

### ISSUE THREAD

**Issue by jozsefs** [adazzle/react-data-grid#3138]
I've recently ran into this issue as I've upgraded the component version in our project from beta-10 to beta-22.
If you are firing click events in your jest tests you might run into it as well.
I've created this ticket so it's easier to find the solution as one would search first in issues I guess (at least I did).

You'll need to mock it, e.g. in this project's https://github.com/adazzle/react-data-grid/blob/c8a083e0e3220c0f004725449aa96c788ba91893/test/setup.ts#L21

**Comment by MariuszApptension** [comment]
Updating library to version: ""7.0.0-canary.49" helps me to resolved this problem.

**Comment by jozsefs** [comment]
> Updating library to version: "7.0.0-canary.49" helps me to resolved this problem.

that version is from May 26, 2021 so I guess "downgrading" is a better word in terms of version

**Comment by amanmahajan7** [comment]
JSDOM does not support `scrollIntoView` so this is needed in the test setup file
