### ISSUE TITLE
Scroll gets stuck when a cell is selected

### ISSUE THREAD

**Issue by marrouchi** [adazzle/react-data-grid#3146]
## Describe the bug 
When a cell is selected, it's not possible to scroll anymore within the data grid.

## To Reproduce 

1. Select a cell
2. Scroll down

Example:
```
      <DataGrid
        defaultColumnOptions={{
          sortable: true,
          resizable: true,
        }}
        className="fill-grid"
        rowKeyGetter={({ name }) => name}
        columns={columns}
        rows={filteredRows}
        selectedRows={selectedColumns}
        onSelectedRowsChange={handleRowSelect}
      />
```
## Expected behavior 
It should allow to scroll in data grid even when a cell is selected.

## Environment

- `react-data-grid` version: 7.0.0-beta.22
- `react`/`react-dom` version: 18.2.0

**Comment by ravi714** [comment]
How You can solve this
