### ISSUE TITLE
Vertically oriented grid

### ISSUE THREAD

**Issue by ioanachi** [adazzle/react-data-grid#3171]
Hi all, 

I was wondering if it supports a vertically oriented table. I mean if the headers would be vertically oriented like so
![vertical table](https://user-images.githubusercontent.com/30567873/224294773-ab3c001e-d08b-43a5-b083-870e2bf13a9b.JPG)

Does it have this functionality or would there be a way to achieve this?
Thank you!

**Comment by DevTGhosh** [comment]
The library won't be able to do that but you can achieve it using js yourself. https://stackoverflow.com/questions/4492678/swap-rows-with-columns-transposition-of-a-matrix-in-javascript

**Comment by amanmahajan7** [comment]
This is not supported and we do not have plans to add this feature. A custom implementation like the probably the best solution
