### ISSUE TITLE
Rendering performance can be improved

### ISSUE THREAD

**Issue by peterpme** [adazzle/react-data-grid#320]
After doing some basic profiling and comparing to https://bvaughn.github.io/react-virtualized/, there are several improvements that can take place to rendering performance.

Not only does ever row get re-rendered on scroll, it's not limited to what's inside the container.

This is super prevalent when you `Trace React updates`:

![image](https://cloud.githubusercontent.com/assets/1211905/15301791/30f8b8f0-1b75-11e6-8bc2-3b906e51d618.png)

Whether I end up PR'ing this myself or not, would just like to keep track of this somewhere :)

Thanks!

**Comment by malonecj** [comment]
Thanks for creating the issue. Yes, I strongly agree on this one. The grid didn't always render every row on scroll. Would be great to have a set of test cases to ensure the grid is rendering the minimum set of elements that it needs to. It's not something that we are going to be able to look at the very near future, but will absolutely accept PR's on this one

**Comment by malonecj** [comment]
https://github.com/adazzle/react-data-grid/pull/483

**Comment by th3fallen** [comment]
this would be amazing if you could pull in react-virtualized like suggested above, the perf gains for large datasets would be astronomical

**Comment by malonecj** [comment]
Superceded by https://github.com/adazzle/react-data-grid/issues/1090
