### ISSUE TITLE
Editor - Single click editor not working

### ISSUE THREAD

**Issue by farooq7124** [adazzle/react-data-grid#3214]
### Describe the bug

Single Click editor not working in beta-28 version. It was working in beta-18 version.

Requirement - Show the editor on single click

**### Environment**

react-data-grid version: 7.0.0-beta.28
react/react-dom version: 18.2.0

**Comment by farooq7124** [comment]
@nstepien i am handling single click edit onRowClick

`onRowClick={(row, column)=>{
    const rowIdx = row.rowId
    if (column && column.isDropdown) {
      this.grid.selectCell({ rowIdx: row.id, idx: column.idx }, true)
    }
}}`

**Comment by nstepien** [comment]
I would suggest using `onCellClick` like this:
```ts
      onCellClick={(args, event) => {
        if (args.column.isDropdown) {
          event.preventGridDefault();
          args.selectCell(true);
        }
      }}
```

**Comment by farooq7124** [comment]
@nstepien  it is working 👍  .. Thanks for your swift support 

Closing this bug.
