### ISSUE TITLE
Not showing sort icon

### ISSUE THREAD

**Issue by farooq7124** [adazzle/react-data-grid#3216]
## To Reproduce 

1.Click on header to sort
2.Grid data is sorted but no icon indicates sort is applied
 

https://user-images.githubusercontent.com/12643480/236204070-6a745a39-7dfa-403a-a5c6-d29b8091cfb8.mov

## Environment

- `react-data-grid` version: 7.0.0-beta.29
- `react`/`react-dom` version: 17

**Comment by godon019** [comment]
I couldn't reproduce it. do you have any reproduction repo?

**Comment by farooq7124** [comment]
Closing this bug.. It is working as expected by using attribute sortColumns to grid
