### ISSUE TITLE
Date editor not working

### ISSUE THREAD

**Issue by farooq7124** [adazzle/react-data-grid#3220]
## Input Date is not working due to zindex

 

Link to code example: https://codesandbox.io/s/react-data-grid-v7-beta-forked-gcpn4z?file=/src/App.tsx
 

- `react-data-grid` version: beta-29
- `react`/`react-dom` version: 17

**Comment by nstepien** [comment]
You'll need to render the dropdown in a react portal outside the grid

**Comment by farooq7124** [comment]
@nstepien Can you please share some sample code

**Comment by DevTGhosh** [comment]
@farooq7124  Check how the key: 'progress', is done here 

https://github.com/adazzle/react-data-grid/blob/main/website/demos/CommonFeatures.tsx

@nstepien  are there no plans of having a way so that  components can be rendered just below the cell? Very weird that a date picker would open up outside the grid.

**Comment by nstepien** [comment]
@farooq7124 you can also use popperjs to place an element relative to another.

@DevTGhosh Even if it could overflow the cell, it may also have to overflow the grid. Rendering overflowing elements outside the grid is fine.

![image](https://github.com/adazzle/react-data-grid/assets/567105/a8df3291-6ac3-4126-8b5c-2d2b6ddbae1d)

**Comment by farooq7124** [comment]
@nstepien Will this open on same position ? I mean selected cell position editor will show ?   Can you please share this code block for reference. It helps me to build multiple custom editors

**Comment by farooq7124** [comment]
@nstepien  i have used createPortal but it looks odd.. Can you please help how to use popperjs and show on edited cell.

https://github.com/adazzle/react-data-grid/assets/12643480/29f3ac6e-d4e4-4a59-b480-976c22b43a5d

**Comment by farooq7124** [comment]
Closing this defect as i have used[ react-datepicker ](https://www.npmjs.com/package/react-datepicker) and it is working as per my requirement.

**Comment by thinhbg2812-2** [comment]
> Closing this defect as i have used[ react-datepicker ](https://www.npmjs.com/package/react-datepicker) and it is working as per my requirement.

Can you provide the example of DRG with react-datepicker sir?
