### ISSUE TITLE
[Bug] Table scrolls upward when select column and header filters are combined

### ISSUE THREAD

**Issue by roniemartinez** [adazzle/react-data-grid#3228]
## Describe the bug 

**This table has select column and header filters combined.**

Issue 1: Table scrolls upward when selecting a checkbox.
Issue 2: When the number of rows change (increased), the table also scrolls upward

https://github.com/adazzle/react-data-grid/assets/2573537/ede545d9-adfa-4202-b198-a92b69799060

## To Reproduce 

1. Start with a table with header filters (https://adazzle.github.io/react-data-grid/#/header-filters)
2. Add select column
3. Select a row

Link to code example: https://adazzle.github.io/react-data-grid/#/header-filters

## Expected behavior 

1. The scroll should stay on the same place

## Environment

- `react-data-grid` version: `^7.0.0-beta.30`
- `react`/`react-dom` version: `^18.2.0`

**Comment by godon019** [comment]
I follows the step but couldn't reproduce it. could you provide a repo for this?
