### ISSUE TITLE
Inline Cell Edit Templates

### ISSUE THREAD

**Issue by imperium2335** [adazzle/react-data-grid#323]
Is it possible to have different editors for cells? i.e. select dropdown with options, date picker etc and have it save on change/close?

**Comment by bakesteve** [comment]
as in different editor for different rows but the same column? rather than just different editor per column (as we have here: http://adazzle.github.io/react-data-grid/examples.html#/all-features)

**Comment by imperium2335** [comment]
Strange, when I visit the documentation at [http://adazzle.github.io/react-data-grid/documentation.html#/apireference](http://adazzle.github.io/react-data-grid/documentation.html#/apireference) I can only see three events listed and no other docs. Thanks for your link, per column is what I meant.

**Comment by bakesteve** [comment]
ok - yeah, the docs on the api are lacking right now (were working on radically improving them), the examples are much more substantive

**Comment by crazy4groovy** [comment]
Is there a date picker example? I dug deep into the addons and found one, but not clear how to use it. An "all-features" date picker column would be swell.
