### ISSUE TITLE
Issue with Virtualisation when testing React Data Grid

### ISSUE THREAD

**Issue by RHarfordKitmanLabs** [adazzle/react-data-grid#3232]
## Describe the bug 

Testing the react data grid in react data testing the lack of window width is causing virtualisation to only display one or two columns.

I have been able to patch a fix by 
1. either disabling Virtualisation
2. Hardcoding a screen window width 

1). isn't ideal as it causes me to add additional props to components using the Table I have built with React Data Grid simply for testing purposes. 
2). Isn't ideal as it will negatively affect anything else that will use screen size unless perhaps rather then window I can set the React Data Grid directly itself?

```
  const { ResizeObserver } = window;
  beforeEach(() => {
    delete window.ResizeObserver;
    window.ResizeObserver = ResizeObserverPolyfill;
    window.HTMLElement.prototype.getBoundingClientRect = jest.fn(() => {
      return {
        width: 1000,
        height: 1000,
      };
    });
  });

  afterEach(() => {
    window.ResizeObserver = ResizeObserver;
    jest.resetAllMocks();
  });
```

I am writing this bug as I couldn't find any other similar issues and wondering has anyone else experienced it or potentially fixed it another way

**Comment by amanmahajan7** [comment]
You can try using the same approach we use for testing `react-data-grid`
https://github.com/adazzle/react-data-grid/blob/main/test/setup.ts#L35
