### ISSUE TITLE
Grid does not resize correctly after collapsing/expanding sidebar

### ISSUE THREAD

**Issue by JanBN** [adazzle/react-data-grid#3238]
![AdazzleDataGridResizeBug](https://github.com/adazzle/react-data-grid/assets/7447593/1a6a3b0e-6225-4e09-b673-8a0e055fceb6)

## Describe the bug
When I collapse the sidebar, the grid and all columns are resized correctly. However, when I expand the sidebar, the grid is not resized to its original state, and a scrollbar is shown at the bottom. Please refer to the attached GIF.

## To Reproduce 
I have forked the repository and made changes to the layout using flexbox. I have also added a button to collapse and expand the sidebar. The code is here: https://github.com/JanBN/react-data-grid?organization=JanBN&organization=JanBN

## Expected behavior
The grid should resize correctly when I expand or collapse the sidebar, and no scrollbar should be shown.

## Environment
- `react-data-grid` 7.0.0-beta.31

Any help is welcomed and if you point me to some direction it would also be helpful.

Thank you

**Comment by nstepien** [comment]
That's an issue with your CSS, if you add `min-width: 0` [here](https://github.com/JanBN/react-data-grid/blob/main/website/root.tsx#L42) then it'll work fine.

```patch
-      <div style={{ display: 'flex', flexDirection: 'row', flexGrow: 1 }}>
+      <div style={{ display: 'flex', flexDirection: 'row', flexGrow: 1, minWidth: 0 }}>
```

**Comment by JanBN** [comment]
Thank you very much. It indeed works.
