### ISSUE TITLE
Select child object as key on columns

### ISSUE THREAD

**Issue by aindong** [adazzle/react-data-grid#325]
Hello I've the follow object
`[
    {
        id: 1,
        email: test@test.com,
        profile: {
              first_name: test
        }
    }
]`

how will I be able to get the `first_name` on profile and assign it to keys? Thank you so much

**Comment by malonecj** [comment]
You would need a custom formatter for that, if I think that is what you mean

```javascript
var ProfileFormatter = React.createClass({
  render:function(){
    var profile = this.props.value;
    return (
      <div>{profile.firstName}
      </div>);
    }
  });
```

**Comment by jcarva** [comment]
@malonecj or anyone, using the above solution to nested object properties, is there a way to sort my columns using the column's `formatter` key?

**Comment by jcarva** [comment]
@malonecj or anyone, using the above solution to nested object properties, is there a way to sort my columns using the column's `formatter` key? Mentioned at #889
