### ISSUE TITLE
`renderCell`, `renderEditCell` are not available

### ISSUE THREAD

**Issue by azamuddin** [adazzle/react-data-grid#3253]
## Describe the bug 

`renderCell`, `renderEditCell` are not available 

## To Reproduce 

1. run `npm i react-data-grid -S` (installed version 7.0.0-beta.31)
2. use `DataGrid` component with the simplest example 
3. on the column definition, use `renderCell` or `renderEditCell`, it won't affect anything. 
    (and if you're using typescript, you'll get type error because `renderCell` nor `renderEditCell` property is not available on type `Column` 

Link to code example: https://codesandbox.io/s/zealous-mccarthy-zk1wzr?file=/src/App.tsx

## Expected behavior 
`renderCell` and `renderEditCell` should be available in the column definition just like demonstrated in the demo source code.

## Environment

- `react-data-grid` version: version 7.0.0-beta.31
- `react`/`react-dom` version: React 18.2.0, ReactDOM 17.2.0

**Comment by godon019** [comment]
the code example shows `"react-data-grid": "7.0.0-beta.28"`
[with lastest version it works as expected ](https://codesandbox.io/s/awesome-mclean-x8s63s?file=/src/App.tsx)

**Comment by azamuddin** [comment]
@godon019 on my machine I use version `beta.31` and not working. But I have tested with `beta.32` and it seems to working properly. 

Thank you.
