### ISSUE TITLE
Add empty column: react.js:18782 Warning: Failed propType: Required prop `value` was not specified in `Cell`. Check the render method of `Row`.

### ISSUE THREAD

**Issue by nina-zhang** [adazzle/react-data-grid#326]
When i add a new column but not key ,will show error: 
react.js:18782 Warning: Failed propType: Required prop `value` was not specified in `Cell`. Check the render method of `Row`.

**Comment by michielboekhoff** [comment]
This is quite simple: `value` cannot be required, as it will be `null` for empty cells. I'll create a PR for that.

**Comment by jstray** [comment]
I'm getting the same error (react 15). Did that PR ever happen?

**Comment by vincentlabatut** [comment]
Hi, same error here, react 0.15.4

**Comment by coffenbacher** [comment]
Same here, any workarounds??

**Comment by moraleslos** [comment]
Same error here.  react 15.6.1 and react-data-grid 2.0.53

**Comment by jcarva** [comment]
I'm getting the same error here, using react 15.4.2 and react-data-grid 2.0.54.

**Comment by adamdonahue** [comment]
I get `The prop `value` is marked as required in `SimpleCellFormatter`, but its value is `null``

**Comment by amanmahajan7** [comment]
This is changed in #948
