### ISSUE TITLE
Issue with index.d.ts file in npm package

### ISSUE THREAD

**Issue by rolfheij-sil** [adazzle/react-data-grid#3260]
## Describe the bug 

There seems to be an issue with the `react-data-grid/lib/index.d.ts` file in the npm package for version 7.0.0-beta.33.
The import on line 3, `import { JSX as JSX_2 } from 'react';` is not resolving.
VS Code says that `Module '"react"' has no exported member 'JSX'.ts(2305)`

The issue can be resolved by removing the import on line, and replacing all occurences of `JSX_2` with `JSX`, as the `JSX` namespace is exported globally from React.

## Environment

- `react-data-grid` version: 7.0.0-beta.33
- `react`/`react-dom` version: 18.2.0

**Comment by nstepien** [comment]
What version of `@types/react` are you on?

**Comment by nstepien** [comment]
Could you update to the latest version of at least `@types/react`?

**Comment by rolfheij-sil** [comment]
Updating to the latest version of `@types/react` resolves the issue. Thanks for your help!
