### ISSUE TITLE
renderEditCell: textEditor doesn't work correctly

### ISSUE THREAD

**Issue by Thomas-Lacomblez** [adazzle/react-data-grid#3266]
Hello,

I am trying to make a simple DataGrid with editable cell. From the example source code I find out that to perform that I had to use `renderEditCell: textEditor` to make cell editable as text input. The issue I get with that is, when I validate the data I edited, it doesn't take it into account. As soon as I press enter or else to validate the old value is automatically set back and I can't edit it.

## To Reproduce 

1. You may try my code even if he is similar to the example code

Link to code example:

```javascript
import React, { useState } from 'react';
import 'react-data-grid/lib/styles.css';
import './styles.css';
import DataGrid, { textEditor } from 'react-data-grid';
import { groupBy as rowGrouper } from 'lodash';

const ExampleGrid = () => {
  const rowKeyGetter = row => row.id;
  const [expandedGroupIds, setExpandedGroupIds] = useState(new Set());
  const [rows, setRows] = useState([
    { id: 1, firstName: 'John', lastName: 'Doe' },
    { id: 2, firstName: 'Alice', lastName: 'Smith' },
    // Other rows...
  ]);
  const columns = [
    {
      key: 'firstName',
      name: 'firstName',
      width: 200,
    },
    {
      key: 'lastName',
      name: 'lastName',
      editable: true,
      renderEditCell: textEditor,
      width: 200,
    },
    // Other columns...
  ];

  return (
    <DataGrid
      columns={columns}
      rows={rows}
      groupBy={['firstName']}
      rowGrouper={rowGrouper}
      rowKeyGetter={rowKeyGetter}
      expandedGroupIds={expandedGroupIds}
      onExpandedGroupIdsChange={setExpandedGroupIds}
      defaultColumnOptions={{
        sortable: true,
        resizable: true,
      }}
    />
  );
};

export default ExampleGrid;
```

## Expected behavior 
When I finished to edit the cell (by pressing enter, clicking outside the cell, etc ...) I want it to keep the value , and if possible update the value in the rows array or at least the possibility to handle it myself on change

## Environment
- `react-data-grid` version: ^7.0.0-beta.34
- `react`/`react-dom` version: 18.2.0

**Comment by godon019** [comment]
seems like you are missing `onRowsChange={setRows}` on the DataGrid props
this is the working [demo](https://codesandbox.io/s/delicate-dew-7v6vc3?file=/src/App.tsx:833-855)

**Comment by Thomas-Lacomblez** [comment]
oh >< sorry for this it indeed works. I thought onRowsChange was for the whole row only.
