### ISSUE TITLE
freeze column on the right

### ISSUE THREAD

**Issue by matrixd2** [adazzle/react-data-grid#3271]
## Use case 

I want to freeze a column of actions on the right side of the table, but i can not find any way for this.

**Comment by perfectyang** [comment]
![image](https://github.com/adazzle/react-data-grid/assets/8724828/23e36262-2260-4f11-a7ca-c4faed9b961f)
I have already  implemented the the right side of the table, you can view below picture that the way I do

![image](https://github.com/adazzle/react-data-grid/assets/8724828/d063bb73-9101-4654-b973-c2deb8ae2d72)
![image](https://github.com/adazzle/react-data-grid/assets/8724828/d7fd2a11-df2c-4f5f-ba63-057ec81879b3)

**Comment by amanmahajan7** [comment]
This is not supported at the moment but we will accept a PR

**Comment by amanmahajan7** [comment]
Duplicate issue https://github.com/adazzle/react-data-grid/issues/2873
