### ISSUE TITLE
Cell highlight not working for custom class applied to cell or row

### ISSUE THREAD

**Issue by DVGY** [adazzle/react-data-grid#3274]
## Describe the bug 

In your demo example for ALL Features, if you fill handle cell which has some custom row class, (there is custom row class applied), then the `rdg-cell-dragged-over`  does not show `#cccff` as bg color. 

This also happens if you have a custom cell class, then the drag over class bg color does not seems to apply. 

Is there a way to applied drag-over-css by us ?

<img width="532" alt="image" src="https://github.com/adazzle/react-data-grid/assets/46158826/a6cb593c-7134-4b82-8a8c-b70e8a624178">

**Comment by godon019** [comment]
Hello again DVGY
I believe you can simply override it by
```css
.rdg-cell-dragged-over {
  background-color: #ccccff;
}
```
for example with the 'All Feature' demo. you can insert the code [here](https://github.com/adazzle/react-data-grid/blob/main/website/demos/AllFeatures.tsx#L15) in the custom class and see that it properly change the color
<img width="265" alt="image" src="https://github.com/adazzle/react-data-grid/assets/10363850/bc7f0aa1-6ac1-4fe9-b261-f5aaada973b5">

<img width="327" alt="image" src="https://github.com/adazzle/react-data-grid/assets/10363850/75bc7a75-0bbc-4029-87e4-a7450ea804b0">

**Comment by DVGY** [comment]
makes sense thanks
