### ISSUE TITLE
onCellContextMenu missing from type definitions

### ISSUE THREAD

**Issue by georgiosd** [adazzle/react-data-grid#3276]
Is it me or is `onCellContextMenu` (and probably other callbacks) missing from the type definitions? I see it in the source code and yet it's not there in the package.

On 7.0 beta 43

**Comment by godon019** [comment]
I can see that the prop is defined in index.d.ts file
https://codesandbox.io/s/gracious-http-px27qv?file=/src/App.tsx
here when you click the `onCellContextMenu` with cmd key in the line number 35 you can navigate into index.d.ts file properly.

**Comment by georgiosd** [comment]
I guess my yarn is drunk... shrug

**Comment by amanmahajan7** [comment]
`onCellContextMenu` is supported
https://github.com/adazzle/react-data-grid/blob/main/src/DataGrid.tsx#L168
