### ISSUE TITLE
HeaderRenderer property in column is not working while typing, focus goes away

### ISSUE THREAD

**Issue by rohit-squirrel** [adazzle/react-data-grid#3281]
Focus does not keep on when we type any input, i am using to filter by using headerRenderer property.

Using react version : 7.0..0-cananry.30
React version : 17.0.2

**Comment by godon019** [comment]
that is an old version of RDG and I don't think it supports react 17. I would recommend you to update packages. otherwise maintainer wouldn't be able to support it as the version is 2 years old

**Comment by amanmahajan7** [comment]
Closing due to lack of response
