### ISSUE TITLE
onPress enter go to next cell (Downward direction)

### ISSUE THREAD

**Issue by DVGY** [adazzle/react-data-grid#3290]
Is it possible somehow to add feature to the cell, such that, if user press Enter, it should commit the value to the current cell and move to next cell in downward direction ?

**Comment by amanmahajan7** [comment]
I think this can be implemented with a custom using `onCellKeyDown` prop. You can check the `mode` field and call `selectCell` on `Enter`
https://github.com/adazzle/react-data-grid/blob/main/website/demos/CellNavigation.tsx#L117

**Comment by DVGY** [comment]
Thanks for adding this.

**Comment by DVGY** [comment]
@amanmahajan7 the demo version does not seems to working ?
