### ISSUE TITLE
Attempted import error: 'useFocusRef' is not exported from 'react-data-grid' in NEXTJS

### ISSUE THREAD

**Issue by adarsh-drishya** [adazzle/react-data-grid#3343]
## To Reproduce 

1.Create a nextjs project with v13.4.19 of next
2.Use a rollup component library that uses 'react-data-grid' and useFocusRef in one of the file.
3.Run npm run dev and you will see the bug.

Link to code example:

## Environment

- `react-data-grid` version: latest
- `react`/`react-dom` version: >=16.8.0 react

## Additional context

![image](https://github.com/adazzle/react-data-grid/assets/108795907/ef5f8564-cad5-4d26-8c05-e69375661e5f)

**Comment by adarsh-drishya** [comment]
^7.0.0-beta.16

**Comment by amanmahajan7** [comment]
Please upgrade to the latest version

**Comment by adarsh-drishya** [comment]
i did that, still  is the same issue. @amanmahajan7

**Comment by amanmahajan7** [comment]
Can you create reproducible example

**Comment by adarsh-drishya** [comment]
just clone it 
https://github.com/adarsh-drishya/rdg-issue
What i did?
 created a latest next app. used latest rdg version. run npm run dev @amanmahajan7

**Comment by nstepien** [comment]
There's no `useFocusRef` in the RDG codebase, maybe we replaced it at some point

**Comment by adarsh-drishya** [comment]
undestood
