### ISSUE TITLE
onAllRowsSelectionChange is not defined in renderHeaderCell for Select Column

### ISSUE THREAD

**Issue by shashi-drishya** [adazzle/react-data-grid#3361]
Hello @nstepien and @amanmahajan7,

Could you please confirm whether the onAllRowsSelectionChange function, which was available in the previous version of react-data-grid, has been removed or renamed in the current version?

In the previous version, we were able to access this function through the headerRenderer formatter for the Select Column. However, in the current version, it appears that the function is not present in the Select header cell. I've also checked the GitHub ticket at https://github.com/adazzle/react-data-grid/pull/3239, but I couldn't find any information about it being renamed or removed.

Thank you for your assistance in clarifying this matter.

**Comment by amanmahajan7** [comment]
Check this PR https://github.com/adazzle/react-data-grid/pull/3117. You can now use `useRowSelection` hook.
