### ISSUE TITLE
Unresponsive Column Resizing in Firefox for Draggable Columns

### ISSUE THREAD

**Issue by jereze** [adazzle/react-data-grid#3370]
Describe the bug

When using Firefox, a column with both resizable: true and draggable: true properties set does not appear to be resizable. See video attached for demonstration.

https://github.com/adazzle/react-data-grid/assets/4386500/ec9a2e91-f3be-482c-8769-1ae699a89fba

To Reproduce:
https://adazzle.github.io/react-data-grid/#/columns-reordering

react-data-grid version: 7.0.0-beta.40
firefox version: 118.0.2

**Comment by jereze** [comment]
Thanks!

**Comment by amanmahajan7** [comment]
Thanks for reporting.
