### ISSUE TITLE
HTML in column headers

### ISSUE THREAD

**Issue by imperium2335** [adazzle/react-data-grid#338]
Is this possible?

For instance I would like to do:

```
...
{
                key: 'comcode',
                name: 'Com\' code <span className="fa fa-bolt"></span>',
                width: 80
            },
...
```
Which currently just shows the html as text.

**Comment by imperium2335** [comment]
BTW I got around this by doing:

```
...
headerRenderer: this.headerRenderer('Condition', <span onClick={this.setAll('condition')} className="pull-right fa fa-bolt"></span>),
...
```

**Comment by diogofcunha** [comment]
Passing html into a column header name doesn't seem like the best idea/best practice to adopt. Header name is a string as you can check in the source code.

The way we recommend in this one is to use a **header renderer** as you did. that way you have full control over what will be displayed in the header.
