### ISSUE TITLE
TreeDataGridProps has wrong type for columns 

### ISSUE THREAD

**Issue by tom-weiss** [adazzle/react-data-grid#3404]
## TreeDataGridProps has wrong type for columns 

Is currently set to: readonly Column<R, SR>[];

Should be readonly ColumnOrColumnGroup<R, SR>[];

## To Reproduce
1. Instantiate a TreeDataGrid with grouped columns

I am happy to create a PR with a fix if you want.

**Comment by amanmahajan7** [comment]
`TreeDataGrid` does not support column groups at the moment and the types are correct.

**Comment by paustint** [comment]
And FYI, this change was made here https://github.com/adazzle/react-data-grid/pull/3287/files where row grouping was removed from the core Grid and moved into TreeGrid was titied up.

I ended up having to review the diff of releases to identify and fix all the breaking changes [when I upgraded](https://github.com/jetstreamapp/jetstream/commit/ab36f99b5c0ff2002bb5d4f70a757293af656509) from `7.0.0-beta.34` to `7.0.0-beta.41`.

**Comment by amanmahajan7** [comment]
Column grouping is not supported in `<TreeDataGrid />`. I am closing this issue as there is no plan to add it for now. We will a accept a PR
