### ISSUE TITLE
Column auto size not working on Firefox

### ISSUE THREAD

**Issue by holospice18** [adazzle/react-data-grid#3409]
## Describe the bug 
Auto size on Firefox does not work unless 'size' is defined

On Chrome column size is defined by cell content
On Firefox column size is defined by Grid

Chrome
![image](https://github.com/adazzle/react-data-grid/assets/145089013/7d8de4ad-2cff-4905-be6d-94516f9af6eb)

Firefox
![image](https://github.com/adazzle/react-data-grid/assets/145089013/4ff4c363-e714-4ed5-b587-6bf091832ac2)

**Comment by amanmahajan7** [comment]
`react-data-grid` uses `auto` as the default width. This looks like a bug in FF and not in react-data-grid.

**Comment by jcharry** [comment]
@amanmahajan7 even if it is a browser bug, any ideas how to work around this? We're currently witnessing the same behavior. I've tried setting `min-width: fit-content` on the gridcell and column header and that actually seems to fix things on safari and firefox, but then it breaks on chrome.

**Comment by amanmahajan7** [comment]
You can try using `<DataGrid defaultColumnOptions={{ width: ''max-content' }} ... `
