### ISSUE TITLE
NODE_ENV not replaced in minified version

### ISSUE THREAD

**Issue by psurrey** [adazzle/react-data-grid#341]
Hi,

with the minified version of your files (version 0.14.42 installed via npm) I get the following error in the console of my browser: 

> You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.

The file I am including is `dist/react-data-grid.min.js`.

Would it be possible for you to deliver the minified versions with NODE_ENV properly replaced? Or can I as a consumer of your library do something about it in my build process?

Thanks in advance!

**Comment by malonecj** [comment]
This happened when we added the code for context menu. Rather than bundling all of the redux library, I think we will remove this from the main dist file and have the code for this in another `.js` file. I'll also set the NODE_ENV variable correctly

**Comment by psurrey** [comment]
@malonecj awesome, thanks! Looking forward to it 👍

**Comment by psurrey** [comment]
Just updated to version 1.0.4 which seems to include the fix!

**Comment by psurrey** [comment]
Ok, I was wrong: `react-data-grid.ui-plugins.min.js` still contains NODE_ENV variable in version 1.0.4.

@malonecj Any updates on this?

**Comment by psurrey** [comment]
https://npmcdn.com/react-data-grid@1.0.4/dist/react-data-grid.ui-plugins.min.js
