### ISSUE TITLE
Crash on click on grouping row when `onFill` is set

### ISSUE THREAD

**Issue by TimoStaudinger** [adazzle/react-data-grid#3477]
## Describe the bug 

In a grouped `TreeDataGrid` that has `onFill` specified, the application crashes when the user clicks on a grouping row.

## To Reproduce 

See the minimal reproduction here: https://codesandbox.io/p/sandbox/rdg-group-crash-vn3ddv?file=%2Fsrc%2FApp.js

1. Click on a grouping row, see the screenshot below.
2. Note the exception.

![image](https://github.com/adazzle/react-data-grid/assets/5621996/cc1d1710-a036-48ef-a93c-20d609adc4f9)

![image](https://github.com/adazzle/react-data-grid/assets/5621996/48e52916-1f84-4058-b271-90493af50bd5)

## Expected behavior 

Clicking on the grouping row should not crash the application.

## Environment

- `react-data-grid` version: 7.0.0-beta.43
- `react`/`react-dom` version: 18.0.0

**Comment by amanmahajan7** [comment]
`onFill` is not supported at the moment on `TreeDataGrid`. We will accept PR
https://github.com/adazzle/react-data-grid/blob/main/src/TreeDataGrid.tsx#L28
