### ISSUE TITLE
Is there a notes for an updates?

### ISSUE THREAD

**Issue by yaazzik** [adazzle/react-data-grid#3495]
### Discussed in https://github.com/adazzle/react-data-grid/discussions/3482

<div type='discussions-op-text'>

<sup>Originally posted by **yaazzik** April  1, 2024</sup>
I have this library with version 7.0.0-beta-28 and after an update it lost all functionality, something happened between beta-31 and beta-32. It would be nice to know what exactly :^)</div>

**Comment by kennarddh** [comment]
https://github.com/adazzle/react-data-grid/blob/main/CHANGELOG.md

**Comment by robinrt124** [comment]
I am facing an issue with my Next.js app where the React Data Grid table UI
crashes after building and deploying with npm run build and npm run start.
During development (npm run dev), everything works fine. I'm seeking
assistance to identify and resolve this issue.

**Comment by kennarddh** [comment]
> I am facing an issue with my Next.js app where the React Data Grid table UI crashes after building and deploying with npm run build and npm run start. During development (npm run dev), everything works fine. I'm seeking assistance to identify and resolve this issue.

why post message in other's issue...
