### ISSUE TITLE
vertical scroll is not working as expected when first column is frozen

### ISSUE THREAD

**Issue by pavankalyankolla** [adazzle/react-data-grid#3497]
When first column is frozen, when performing vertical scroll the frozen column in the grid is jitter 
## To Reproduce 

1. When the first column is frozen
2. When we manually perform vertical scroll
3. Frozen column is jitter (Frozen column is not in the fixed poistion)

- `react-data-grid` version: ^6.1.0
- `react`/`react-dom` version: 18.2.0

**Comment by amanmahajan7** [comment]
`react-data-grid 6.1.0` is not longer supported and we recommend upgrading to the latest beta version
