### ISSUE TITLE
How can we use the original editOnClick API or implement similar functionality with an existing version?

### ISSUE THREAD

**Issue by nqsjd178559344** [adazzle/react-data-grid#3513]
**##** Use case 
![image](https://github.com/adazzle/react-data-grid/assets/43981368/819d126c-5f04-4c2f-8902-1c8da209219d)

**Comment by dalmolinz** [comment]
There's an example here:

https://github.com/adazzle/react-data-grid/blob/b667cec545666308ec59d74580b695e344380379/website/demos/AllFeatures.tsx#L215-L219

**Comment by amanmahajan7** [comment]
The above solution is the right way to enable single select editing
