### ISSUE TITLE
Columns are sorted when space key is down during typing in filters

### ISSUE THREAD

**Issue by Kosssma** [adazzle/react-data-grid#3535]
## Describe the bug 

When user type key word in filter when he hit space instead of space char as next sign he trigger column sorting functionality. User can not enter space from keyboard, he can only paste it into filter to be able to use it.

## To Reproduce 

1. Create a header with a filter like the the [Header filters](example https://adazzle.github.io/react-data-grid/#/header-filters)
2. Enable sorting like in the [Columns reordering[(example https://adazzle.github.io/react-data-grid/#/columns-reordering)

Link to code example:

## Expected behavior 
when typing in filter sign user hit space this should not trigger column sorting 

## Environment

- `react-data-grid` version: ^7.0.0-beta.44
- `react`/`react-dom` version: ^18.2.0

## Additional context 

code line responsible for effect:
https://github.com/adazzle/react-data-grid/blob/b667cec545666308ec59d74580b695e344380379/src/HeaderCell.tsx#L280
https://github.com/adazzle/react-data-grid/blob/9aa46269793cda576f60d2c6fb03d250028444a3/src/HeaderCell.tsx#L202

**Comment by ronneldavis** [comment]
This seems to be related to this issue as well: https://github.com/adazzle/react-data-grid/issues/3439

**Comment by holaChaitanya** [comment]
![image](https://github.com/user-attachments/assets/cf8240ee-c308-46b0-9cea-0d7bd6dec449)

why not try something like - stop event propagation inside the `renderHeaderCell` itself?

**Comment by amanmahajan7** [comment]
The above recommended approach (using `stopPropagation`) is the right way to resolve this issue
https://github.com/adazzle/react-data-grid/blob/main/website/routes/HeaderFilters.lazy.tsx#L72-L82
