### ISSUE TITLE
Can react-data-grid-addons be released for react 18 !!

### ISSUE THREAD

**Issue by LogiMateenSA** [adazzle/react-data-grid#3542]
Getting below error while installing react-data-grid-addons. Looks like its not released for react 18

npm install react-data-grid-addons
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: react-data-grid-test@0.1.0
npm ERR! Found: react@18.3.1
npm ERR! node_modules/react
npm ERR!   react@"^18.3.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8" from react-data-grid-addons@7.0.0-alpha.24
npm ERR! node_modules/react-data-grid-addons
npm ERR!   react-data-grid-addons@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\masyed\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\masyed\AppData\Local\npm-cache\_logs\2024-07-15T08_39_00_438Z-debug.log

**Comment by LogiMateenSA** [comment]
FYI.. my package.json looks like below

{
  "name": "react-data-grid-test",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "clsx": "^2.1.1",
    "faker": "^6.6.6",
    "react": "^18.3.1",
    "react-data-grid": "^7.0.0-beta.42",
    "react-dom": "^18.3.1",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
  "devDependencies": {
    "@faker-js/faker": "^8.4.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

**Comment by amanmahajan7** [comment]
`react-data-grid-addons` has been removed and there is not plan to support it. We recommend copying the old package and tweak it as per your needs
