### ISSUE TITLE
@layer compatibility issues

### ISSUE THREAD

**Issue by TalentSmallPanda** [adazzle/react-data-grid#3562]
What should I do if @layer does not work in some lower versions of Chrome browsers, For example, the following CSS code does not take effect in browsers with Chrome kernel 99 or so?

.rnvodz57-0-0-beta-44 {
  @layer rdg.Defaults {
    *,
    *::before,
    *::after {
      box-sizing: inherit;
    }
  }

  @layer rdg.Root {
    --rdg-color: #000;   --rdg-border-color: #ddd;   --rdg-summary-border-color: #aaa;   --rdg-background-color: hsl(0deg 0% 100%);   --rdg-header-background-color: hsl(0deg 0% 97.5%);   --rdg-header-draggable-background-color: hsl(0deg 0% 90.5%);   --rdg-row-hover-background-color: hsl(0deg 0% 96%);   --rdg-row-selected-background-color: hsl(207deg 76% 92%);   --rdg-row-selected-hover-background-color: hsl(207deg 76% 88%);   --rdg-checkbox-color: hsl(207deg 100% 29%);   --rdg-checkbox-focus-color: hsl(207deg 100% 69%);   --rdg-checkbox-disabled-border-color: #ccc;   --rdg-checkbox-disabled-background-color: #ddd;
    --rdg-selection-color: #66afe9;
    --rdg-font-size: 14px;
    --rdg-cell-frozen-box-shadow: calc(2px * var(--rdg-sign)) 0 5px -2px rgba(136, 136, 136, 0.3);

    display: grid;

    color-scheme: var(--rdg-color-scheme, light dark);

    /* https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context */
    /* We set a stacking context so internal elements don't render on top of external elements. */
    /* size containment is not used as it could break "width: min-content" for example, and the grid would infinitely resize on Chromium browsers */
    contain: content;
    content-visibility: auto;
    block-size: 350px;
    border: 1px solid var(--rdg-border-color);
    box-sizing: border-box;
    overflow: auto;
    background-color: var(--rdg-background-color);
    color: var(--rdg-color);
    font-size: var(--rdg-font-size);

    /* needed on Firefox to fix scrollbars */
    &::before {
      content: '';
      grid-column: 1/-1;
      grid-row: 1/-1;

> }

**Comment by maxorrs** [comment]
Hi. I encountered the same thing, as a solution to the problem try to use [@csstools/postcss-cascade-layers](https://github.com/csstools/postcss-plugins/blob/main/plugins/postcss-cascade-layers/INSTALL.md) polyfill

my-react-data-grid.tsx
```
...
import ReactDataGrid from 'react-data-grid';
import './my-react-data-grid.scss';

const MyReactDataGrid = (props) => {
  ...
  return <ReactDataGrid {...props} />;
};
```
my-react-data-grid.scss
```
@import 'react-data-grid/lib/styles.css';
```

I use create-react-app config, in webpack.config.js I added plugin @csstools/postcss-cascade-layers in postCss options – getStyleLoaders func

then try to build your project

**Comment by TalentSmallPanda** [comment]
> Hi. I encountered the same thing, as a solution to the problem try to use [@csstools/postcss-cascade-layers](https://github.com/csstools/postcss-plugins/blob/main/plugins/postcss-cascade-layers/INSTALL.md) polyfill
> 
> my-react-data-grid.tsx
> 
> ```
> ...
> import ReactDataGrid from 'react-data-grid';
> import './my-react-data-grid.scss';
> 
> const MyReactDataGrid = (props) => {
>   ...
>   return <ReactDataGrid {...props} />;
> };
> ```
> 
> my-react-data-grid.scss
> 
> ```
> @import 'react-data-grid/lib/styles.css';
> ```
> 
> I use create-react-app config, in webpack.config.js I added plugin @csstools/postcss-cascade-layers in postCss options – getStyleLoaders func
> 
> then try to build your project

**Comment by TalentSmallPanda** [comment]
> Hi. I encountered the same thing, as a solution to the problem try to use [@csstools/postcss-cascade-layers](https://github.com/csstools/postcss-plugins/blob/main/plugins/postcss-cascade-layers/INSTALL.md) polyfill
> 
> my-react-data-grid.tsx
> 
> ```
> ...
> import ReactDataGrid from 'react-data-grid';
> import './my-react-data-grid.scss';
> 
> const MyReactDataGrid = (props) => {
>   ...
>   return <ReactDataGrid {...props} />;
> };
> ```
> 
> my-react-data-grid.scss
> 
> ```
> @import 'react-data-grid/lib/styles.css';
> ```
> 
> I use create-react-app config, in webpack.config.js I added plugin @csstools/postcss-cascade-layers in postCss options – getStyleLoaders func
> 
> then try to build your project


> Hi. I encountered the same thing, as a solution to the problem try to use [@csstools/postcss-cascade-layers](https://github.com/csstools/postcss-plugins/blob/main/plugins/postcss-cascade-layers/INSTALL.md) polyfill
> 
> my-react-data-grid.tsx
> 
> ```
> ...
> import ReactDataGrid from 'react-data-grid';
> import './my-react-data-grid.scss';
> 
> const MyReactDataGrid = (props) => {
>   ...
>   return <ReactDataGrid {...props} />;
> };
> ```
> 
> my-react-data-grid.scss
> 
> ```
> @import 'react-data-grid/lib/styles.css';
> ```
> 
> I use create-react-app config, in webpack.config.js I added plugin @csstools/postcss-cascade-layers in postCss options – getStyleLoaders func
> 
> then try to build your project

I tried to configure the @csstools/postcss-cascade-layers plugin in webpack, but it didn't work. The styles in it were crossed out and did not take effect!

**Comment by TalentSmallPanda** [comment]
> What should I do if @layer does not work in some lower versions of Chrome browsers, For example, the following CSS code does not take effect in browsers with Chrome kernel 99 or so?
> 
> .rnvodz57-0-0-beta-44 { @layer rdg.Defaults { *, *::before, *::after { box-sizing: inherit; } }
> 
> @layer rdg.Root { --rdg-color: #000; --rdg-border-color: #ddd; --rdg-summary-border-color: #aaa; --rdg-background-color: hsl(0deg 0% 100%); --rdg-header-background-color: hsl(0deg 0% 97.5%); --rdg-header-draggable-background-color: hsl(0deg 0% 90.5%); --rdg-row-hover-background-color: hsl(0deg 0% 96%); --rdg-row-selected-background-color: hsl(207deg 76% 92%); --rdg-row-selected-hover-background-color: hsl(207deg 76% 88%); --rdg-checkbox-color: hsl(207deg 100% 29%); --rdg-checkbox-focus-color: hsl(207deg 100% 69%); --rdg-checkbox-disabled-border-color: #ccc; --rdg-checkbox-disabled-background-color: #ddd; --rdg-selection-color: #66afe9; --rdg-font-size: 14px; --rdg-cell-frozen-box-shadow: calc(2px * var(--rdg-sign)) 0 5px -2px rgba(136, 136, 136, 0.3);
> 
> ```
> display: grid;
> 
> color-scheme: var(--rdg-color-scheme, light dark);
> 
> /* https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context */
> /* We set a stacking context so internal elements don't render on top of external elements. */
> /* size containment is not used as it could break "width: min-content" for example, and the grid would infinitely resize on Chromium browsers */
> contain: content;
> content-visibility: auto;
> block-size: 350px;
> border: 1px solid var(--rdg-border-color);
> box-sizing: border-box;
> overflow: auto;
> background-color: var(--rdg-background-color);
> color: var(--rdg-color);
> font-size: var(--rdg-font-size);
> 
> /* needed on Firefox to fix scrollbars */
> &::before {
>   content: '';
>   grid-column: 1/-1;
>   grid-row: 1/-1;
> ```
> 
> > }
