### ISSUE TITLE
An absolute element inside the grid header cannot extend outside the grid.

### ISSUE THREAD

**Issue by jooyoni** [adazzle/react-data-grid#3571]
## Describe the bug 
I used the renderHeaderCell method in the columns props to add an element inside the grid header. This element contains a filter button (yellow area in the picture), and clicking this button opens the blue area shown in the picture. However, the blue area cannot extend outside the overall grid area. I tried setting overflow: visible on the .rdg class, but it doesn't work.

## To Reproduce 
1. Use the renderHeaderCell method in the array for the columns props to input an element into the header.

2. Add a button to the header element added in step 1, and when this button is clicked, an element with the position: absolute property is rendered inside the header.

3. Ensure that the element rendered in step 2 is not clipped even if it extends outside the grid area.

Link to code example:

## Environment

- `react-data-grid` version:^7.0.0-beta.44
- `react`/`react-dom` version:^18.2.0

## Additional context 

![KakaoTalk_Photo_2024-08-06-11-19-21](https://github.com/user-attachments/assets/635cdb9e-d7a2-4ff3-98ed-23154c22356e)

**Comment by amanmahajan7** [comment]
Please see
https://github.com/adazzle/react-data-grid/issues/2709#issuecomment-1010239549
https://github.com/adazzle/react-data-grid/issues/3272
