### ISSUE TITLE
When clicking on the table header, onSelectedCellChange is called with row as undefined

### ISSUE THREAD

**Issue by Bartmr** [adazzle/react-data-grid#3580]
## Describe the bug 

When clicking on the table header that is not sortable, `onSelectedCellChange` is called with `row` set as `undefined`

## To Reproduce 

1. Click on a table header cell that is not sortable
2. log the arguments coming in `onSelectedCellChange`

Link to code example:

![Screenshot from 2024-08-21 11-29-44](https://github.com/user-attachments/assets/99b34953-454d-470a-8953-67156638e664)

```tsx
const columns: Column<Accountant>[] = [
    {
      key: "name",
      name: "Name",
      resizable: true,
      renderCell: (args) => {
        return args.row.name;
      },
    },
    {
      key: "email",
      name: "Email",
      resizable: true,

      renderCell: (args) => {
        return args.row.email;
      },
    },
  ];

return <ReactDataGrid
      className={`rdg-light`}
      rows={props.accountants}
      columns={columns}
      rowKeyGetter={(r) => r.id}
      onSelectedCellChange={(args) => {
        props.onAccountantSelect(args.row.id);
      }}
    />
```

## Expected behavior 

Either:
- don't call `onSelectedCellChange` when a table header is selected
- type `row` argument in `onSelectedCellChange` as possibly `undefined`

## Environment

- `react-data-grid` version: 7.0.0-beta.46
- `react`/`react-dom` version: 18

**Comment by amanmahajan7** [comment]
Can you create a reproducible example?

**Comment by amanmahajan7** [comment]
Closing due to lack of response.
