### ISSUE TITLE
ResizeObserver loop completed with undelivered notifications. when reducing the browser width

### ISSUE THREAD

**Issue by bbenami** [adazzle/react-data-grid#3582]
## Describe the bug 
I have a basic data grid that spans the full width of the window. When I reduce the width of the browser window, I encounter the following error message: "ResizeObserver loop completed with undelivered notifications." This issue doesn't occur when I increase the browser width or adjust the height.

## To Reproduce 

1. Reduce the width of the browser window.
Link to code example:

```typescript

import React from "react";
import DataGrid from "react-data-grid";
import { data } from "../datasource";

import "react-data-grid/lib/styles.css";

const About: React.FC = () => {
  const datas: object[] = data(10);

  const columns = [
    {
      key: "TaskID",
      name: "Task Id",
    },
    { key: "Engineer", name: "Engineer" },
    { key: "Designation", name: "Designation" },
  ];

  return <DataGrid columns={columns} rows={datas} />;
};

export default About;
``` 

## Expected behavior 
Not to throw an exception when resizing the browser
## Environment

- `react-data-grid` version: 7.0.0-beta.46
- `react`/`react-dom` version: 18.3.1

**Comment by balaji-sivasakthi** [comment]
This is duplicate issue of #3583

**Comment by amanmahajan7** [comment]
Closing as this is a duplicate issue
