### ISSUE TITLE
`Error: useRowSelection must be used within DataGrid cells`  bunping `7.0.0-beta.44` => `7.0.0-beta.47`

### ISSUE THREAD

**Issue by softmarshmallow** [adazzle/react-data-grid#3597]
I have this custom leading header  column renderer, worked fine until .44, after bumping to .47, it no longer works with following error.

```
Error: useRowSelection must be used within DataGrid cells
```

Perhaps the contributor know what this is about?

```

export const SelectColumn: CalculatedColumn<any, any> = {
  key: "__gf_select",
  name: "",
  idx: 0,
  width: 65,
  maxWidth: 65,
  resizable: false,
  sortable: false,
  frozen: true,
  renderHeaderCell: (props: RenderHeaderCellProps<unknown>) => {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const [isRowSelected, onRowSelectionChange] = useRowSelection();

    return (
      <SelectCellHeader
        aria-label="Select All"
        tabIndex={props.tabIndex}
        value={isRowSelected}
        onChange={(checked) =>
          onRowSelectionChange({ type: "HEADER", checked })
        }
      />
    );
  },
....
```

<img width="1058" alt="Screenshot 2024-09-13 at 3 02 14 AM" src="https://github.com/user-attachments/assets/e60d79d2-b828-466e-8ace-8e57c4fae224">

**Comment by amanmahajan7** [comment]
We have tweaked the selection hook and `useHeaderRowSelection` should be used for header cells now
https://github.com/adazzle/react-data-grid/blob/main/src/Columns.tsx#L8
https://github.com/adazzle/react-data-grid/pull/3577
