### ISSUE TITLE
expose `indeterminate` in ts typings for `RenderCheckboxProps`

### ISSUE THREAD

**Issue by softmarshmallow** [adazzle/react-data-grid#3598]
The `indeterminate` property from `RenderCheckboxProps` is not exposed, cannot render custom checkbox based on indeterminate with ts

```
function renderCheckbox({ onChange, ...props }: RenderCheckboxProps) {
  console.log("props", props.indeterminate);
  return (
    <Checkbox {...props} onCheckedChange={(v) => onChange(v === true, false)} />
  );
}
```

<img width="873" alt="Screenshot 2024-09-13 at 3 23 54 AM" src="https://github.com/user-attachments/assets/82b4c8e0-8e86-4a7d-b9ea-b03f56c973f4">

<img width="523" alt="Screenshot 2024-09-13 at 3 24 03 AM" src="https://github.com/user-attachments/assets/082a1b34-9edd-422c-b4ba-747d2fc5abda">

**Comment by amanmahajan7** [comment]
It is available 
https://github.com/adazzle/react-data-grid/blob/main/src/types.ts#L307
https://unpkg.com/browse/react-data-grid@7.0.0-beta.47/lib/index.d.ts
