### ISSUE TITLE
Enter key does not advance to next row

### ISSUE THREAD

**Issue by winkler1** [adazzle/react-data-grid#36]
Thanks for the great work on this component. This is the best editable spreadsheet-like component I've seen so far.

In most spreadsheets (Excel/google spreadsheets), the cells are all editable. Tabbing moves between them, and [Enter] moves to the next row.

In react-data-grid, Enter seems to always toggle cell editing on/off, which feels awkward from a bulk data-entry perspective. Is there some way to have the cells be editable, and [Enter] does the expected thing of moving to the next row?

**Comment by malonecj** [comment]
Having the cells editable by default does not really fit our use case as we use quite a lot of complex editors which we don't want to render upon tabbing into cell. 

This would be a nice option though. However it  would not be high on the the list of our priorities. 

If you could show that this is possible through a config option, as well as a way a way to extract out how the keyboard commands are mapped, we would be happy to help get the pull request merged into master
