### ISSUE TITLE
Deselecting a row in single select mode

### ISSUE THREAD

**Issue by BorisKozo** [adazzle/react-data-grid#360]
Is there a way to deselect a row in single select mode?
Currently the default state is that no row is selected but once you selected some row you can't (or at least I haven't found a way) to return to the default state where no row is selected via user interaction.

**Comment by malonecj** [comment]
Currently, no.

But in the next release we are changing how we handle row selection, which should solve your problem. This change will be backwards compatible with the current method, but we will then deprecating that in favor of the new way defined here. The new row selection functionality allows the user to manage the selection themselves as defined here https://github.com/adazzle/react-data-grid/issues/315

**Comment by diogofcunha** [comment]
@BorisKozo the improvements on row selection fixed this issue, you can get them after version `1.0.19`

**Comment by BorisKozo** [comment]
Thanks you.
Unfortunately your component was not customizeable enough for our requirements so I had to create a wrapper around Datatables instead.

**Comment by diogofcunha** [comment]
But it wasn't associated with this issue itself was it?

Fell free to open an issue talking about the limitations that you have found, we are always aiming to make the grid more extensible.

If we believe that some of your requirements will make sense in the grid context we will either accept a PR or make some effort to implement them in the future.

Cheers,
Diogo

**Comment by BorisKozo** [comment]
This was one of the issues that eventually led to the switch. The bigger issue was the focus stealing I talked with you about in Slack. 
I could not work around that.
