### ISSUE TITLE
Event like onRowClick and getting the index of the clicked row

### ISSUE THREAD

**Issue by liamkar** [adazzle/react-data-grid#3611]
I would need to attach an event handler on clicking any part of the row and get the index value of the clicked row. I can see there used to be a property onRowClick in the past that did exactly that, but I cannot see any replacement for that, but if a work-around exists  already, I would love to hear about that.

I already tried onCellClick, but unfortunately it seems not to be passing the  index of the clicked row to the clickHandler.

Looking at the examples, I can see there are checkboxes on the left side of the grid on some examples. My hunch is that it might be possible to attach event handler receivng row index on that component? Then again, I would like to avoid  adding any checkboxes on rows as basically no need for checkboxes exists.

**Comment by amanmahajan7** [comment]
We can tweak the params 
https://github.com/adazzle/react-data-grid/blob/main/src/types.ts#L170
https://github.com/adazzle/react-data-grid/blob/main/src/Cell.tsx#L69
