### ISSUE TITLE
Check what formatter a column is using

### ISSUE THREAD

**Issue by Hannesfornell** [adazzle/react-data-grid#363]
I want to attach a light box (featherlight) to get manually activated on cell double click (enter and double click). The problem is that I only want to do this when the column has the imageFormatter attached. In the beginning as a trial I hardcoded a check into the setActive function. if(keyPressed=='Enter'&&this.state.selected.idx==2){
	  		$.featherlight('testurl.thisisnotreal.jpg');
                         }
And this worked (it's ugly as I don't know what but it worked), the real problem arises when I have multiple grids and it's no longer possible to have a hardcoded check, where you would like something like;

 if(column.formatter == imageFormatter){
DO STUFF;
}

Is there any way to do this? I'm a newbie when in comes to React and React-Data-Grid.

**Comment by diogofcunha** [comment]
Hi @Hannesfornell .

The best way to implement that behaviour is to use column events to attach a certain action to a column or a group of columns.

You don't need to check the formatter as you can attach it to the columns you want in the first place.

You can see an example [in here](http://adazzle.github.io/react-data-grid/examples.html#/column-events)
