### ISSUE TITLE
useless forceUpdate prop

### ISSUE THREAD

**Issue by chadi-kazan** [adazzle/react-data-grid#368]
I see there's a forceUpdate prop defined in both Cell.js and Row.js. Although Canvas passes all the props to Row, leading me to think Canvas also receives a forceUpdate prop and just passes it along, looking at ViewPort, i see nowhere this prop passed to Canvas or any mention to it in either ViewPort or Grid.js.
i can see from Cell.js's shouldComponentUpdate that the grid does not refresh the cell if it's not selected (or if its value has not changed - among other conditions), in the case of which, forceUpdate could provide an alternative to that to allow us to refresh a non selected cell. only in its current state it is useless. could someone please clarify?

**Comment by txm** [comment]
It could be that ReactDataGrid isn't passing forceUpdate - however, ReactDataGrid.Row does:

 55 const RowRenderer = React.createClass({
 56   propTypes: {
 57     columns: React.PropTypes.array.isRequired,
 58     row: React.PropTypes.object.isRequired
 59   },
 60   setScrollLeft: function(scrollBy) {
 61     //if you want freeze columns to work, you need to make sure you implement this as apass through
 62     this.refs.row.setScrollLeft(scrollBy);
 63   },
 64   render: function ():React.Element {
 65     const {row, columns} = this.props;
 66     let CleanseActions = getCleanseActions(dimensions,row);
 67     this.props.columns[9].editor = <DropDownEditor options={CleanseActions}/>;
 68     return (<ReactDataGrid.Row key={this.props.row.id} ref="row" {...this.props} forceUpdate={true} />);
 69   }
 70 });

**Comment by malonecj** [comment]
This was designed to be passed to Row or Cell directly to bypass it's shouldComponentUpdate function and force an update

eg. 
```javascript 
class customRowRenderer extends Component {
   render() {
     return (<ReactDataGrid.Row key={this.props.row.id} ref="row" {...this.props} forceUpdate={true} />
   }
}
```

**Comment by dkwin** [comment]
How would I apply a forceUpdate on a cell?  I have customer cell renderers but not sure where to actually set the prop for a cell.
