### ISSUE TITLE
Error: ./src/addons/data/RowGrouper.js

### ISSUE THREAD

**Issue by brentjm** [adazzle/react-data-grid#381]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
Error: ./src/addons/data/RowGrouper.js
Module not found: Error: Cannot resolve module 'lodash/groupby'

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.
after fresh clone
running gulp produces the following error:
Error: ./src/addons/data/RowGrouper.js
Module not found: Error: Cannot resolve module 'lodash/groupby'

By deleting the first line 
import groupBy from 'lodash/groupby';
in RowGrouper.js, everything worked as expected.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Comment by diogofcunha** [comment]
Hi @brentjm.

For how long do you have your local repo? Looks like you need to run a `npm install` or `npm update` to update your packages.

Loadash was added in Version `1.0.12`

**Comment by brentjm** [comment]
I had just cloned it this morning. I ran npm update and then npm install again (log attached). lodash is loaded in several places.

. On running gulp, I receive:
`/home/userfiles/brent/Downloads/react-data-grid/gulp/tasks/bundle.js:5
  throw new gutil.PluginError(ctx, err);
  ^
Error: ./src/addons/data/RowGrouper.js
Module not found: Error: Cannot resolve module 'lodash/groupby' in /home/userfiles/brent/Downloads/react-data-grid/src/addons/data
resolve module lodash/groupby in /home/userfiles/brent/Downloads/react-data-grid/src/addons/data
  looking for modules in /home/userfiles/brent/Downloads/react-data-grid/node_modules
    resolve 'file' or 'directory' groupby in /home/userfiles/brent/Downloads/react-data-grid/node_modules/lodash
      resolve file
        /home/userfiles/brent/Downloads/react-data-grid/node_modules/lodash/groupby doesn't exist
`
[npm-debug.log.zip](https://github.com/adazzle/react-data-grid/files/373636/npm-debug.log.zip)

If I comment out the one import, all seems to work fine. Hopefully, I don't need addons, so maybe there won't be a problem?
Great spreadsheet overall. Hopefully, it will soon work with React15.
Thank you.
