### ISSUE TITLE
how to use this data grid in react es5 

### ISSUE THREAD

**Issue by buchikey** [adazzle/react-data-grid#383]
my code is like this 
import React from 'react';
import ReactDataGrid from 'react-data-grid';
import ReactDataGridPlugins from 'react-data-grid/addons';
var Editors             = ReactDataGridPlugins.Editors;
var Toolbar             = ReactDataGridPlugins.Toolbar;
var AutoCompleteEditor  = ReactDataGridPlugins.Editors.AutoComplete;
var DropDownEditor      = ReactDataGridPlugins.Editors.DropDownEditor;
it says that cannot read property Editors of undefined..................plese tell me how to use thiss

**Comment by malonecj** [comment]
Try
```import {Editors} from 'react-data-grid/addons';```

**Comment by thorakmedichi** [comment]
Got the same problem happening with the Toolbar. Tried to apply the above suggestion to Toolbar and now it gives me the following error:

Warning: Unknown props onGridSort, columns, rowGetter, rowsCount, minHeight, onRowUpdated, toolbar, onAddFilter, minColumnWidth, columnEquality, enableCellSelect, rowHeight, enableRowSelect, rowKey, rowScrollTimeout, cellNavigationMode, headerRows, columnMetrics, cellMetaData, selectedRows, rowSelection, expandedRows, rowOffsetHeight, sortColumn, sortDirection, onSort, totalWidth, onViewportKeydown, onViewportKeyup, onViewportDragStart, onViewportDragEnd, onViewportDoubleClick, onColumnResize on tag. Remove these props

**Comment by dnbr2002** [comment]
As the above poster mentioned, this seems to resolve the issue.  

     import{ Editors, Toolbar, AutoCompleteEditor, DropDownEditor } from 'react-data-grid/addons';
