### ISSUE TITLE
how to use Dropdown editor with value and text

### ISSUE THREAD

**Issue by marafee1243** [adazzle/react-data-grid#386]
In 
http://adazzle.github.io/react-data-grid/examples.html#/built-in-editors

var issueTypes = ['Bug', 'Improvement', 'Epic', 'Story'];
var DropDownEditor = ReactDataGridPlugins.Editors.DropDownEditor;
var IssueTypesEditor = <DropDownEditor options={issueTypes}/>

how can i use, its option values and text for dropdown like blow

var issueTypes = [{'buh': 'Bug'}, {'improvement': 'Improvement'}, {'epic':'Epic'}, {'story':'Story'}];

I tried using

var issueTypes = [{id:'bug', value:'bug', name:'Bug', title:'Bug'}, {id:'improvement', value:'improvement', name:'Improvement', title: 'Improvement'}];

but this doesnt work.

**Comment by diogofcunha** [comment]
Hi @marafee1243.

You have several options for that particular case.

1. You can build your own custom editor using for example `react-select` or other select library that uses react;
2. You can use our `DropDownEditor` that accepts `{ id: string, title: string, value: string }`, it's a simple dropdown that will render the value as the label for the option ([you can check the source code](https://github.com/adazzle/react-data-grid/blob/f5656244c18c287aee5c7a14e73d56f11365e7f9/src/addons/editors/DropDownEditor.js#L28)).

**Comment by marafee1243** [comment]
@diogofcunha i have seen the code but it doesnt diferentiate between a value and text
`options.push(<option key={name.id} value={name.value} title={name.title}  >{name.value}</option>);`

it should be something
options.push(<option key={name.id} value={name.value} title={name.title}  >{name.title}</option>);

thats what i am expecting..

**Comment by achillesrasquinha** [comment]
I agree with @marafee1243. [this](https://github.com/adazzle/react-data-grid/blob/f5656244c18c287aee5c7a14e73d56f11365e7f9/src/addons/editors/DropDownEditor.js#L32) should be `{name.title}` instead `{name.value`}

No?

**Comment by Hagafny** [comment]
Agreed with @marafee1243 and @achillesrasquinha . The current implementation doesn't make any sense.

**Comment by mashaod** [comment]
DropDownEditor supports name.text
options.push(<option key={name.id} value={name.value} title={name.title}  >{name.text || name.value}</option>);
