### ISSUE TITLE
Sorting and filter doesn't work properly with select

### ISSUE THREAD

**Issue by Marswang92** [adazzle/react-data-grid#387]
I defined `onGridSort`, `OnAddFilter` and `onRowSelect` as following, but after sorting or filtering, the select function doesn't work as expected. When I click the checkbox, the table will select the row in the same position originally instead of the row being sorted or filtered. Any thought?

        const handleGridSort = (sortColumn, sortDirection) => {
            var state = Object.assign({}, this.state, { sortColumn: sortColumn, sortDirection: sortDirection });
            this.setState(state);
        }

        const handleFilterChange = filter => {
            let newFilters = Object.assign({}, this.state.filters);
            if (filter.filterTerm) {
                newFilters[filter.columnKey] = filter.filterTerm;
            } else {
                delete newFilters[filter.columnKey];
            }
            this.setState({ filters: newFilters });
        }

        const onRowSelect = rows => {
            this.setState({ selectedRows: rows });
        }

**Comment by diogofcunha** [comment]
Hi @Marswang92 are you still in a struggle on this? We have made some changes in the filters recently that I believe will cover your use case.

**Comment by Marswang92** [comment]
Thanks, buddy. Now it's perfectly solved!

**Comment by hakobtorosyan** [comment]
hello azizner jan, sorting does not work properly.when i have columns with same value, after click on header of it, table sorted by anasun algoritm.please help
