### ISSUE TITLE
Using react datepicker component in react-data-grid

### ISSUE THREAD

**Issue by giko45** [adazzle/react-data-grid#389]
Hi @diogofcunha 
You suggest in #331 writing a custom editor.  How do i hook that into a colum and replace the normal editors?
Could you give an example of a custom editor and how to hook that onto a column?

**Comment by diogofcunha** [comment]
[Here](http://adazzle.github.io/react-data-grid/examples.html#/all-features) you can see the way you can attach an editor to a column (`...editor: <Component />`).

React data grid exports some editors, [check this example](https://github.com/adazzle/react-data-grid/blob/master/src/addons/editors/AutoCompleteTokensEditor.js).

Don't forget to implement `getInputNode` and `getValue`.
getInputNode will be used for the editor to know where he needs to focus when edit mode is enabled. getValue will be the function that gets the editor value before commit.

**Comment by giko45** [comment]
needed the follwoing to get value back in the grid

  handleSelectChange(value) {
    this.setState({value:value},function () {
        this.props.onCommit();    
    });
  }

**Comment by giko45** [comment]
also needed the follwing 

```
constructor(props) {
    super(props);
    this.state = {
      value: this.props.rowData[this.props.column.key]
    };
    this.handleSelectChange = this.handleSelectChange.bind(this);
  }




```

**Comment by dimonge** [comment]
@giko45 are you able to fix the focus issue with the calendar component in the react-datepicker. can you provide a example code snippet  of your integration with react-data-grid?

**Comment by soma83** [comment]
@giko45 

> Hi @diogofcunha
You suggest in #331 writing a custom editor. How do i hook that into a colum and replace the normal editors?
Could you give an example of a custom editor and how to hook that onto a column?

Did you get this working? If so, please share the way you did it.
