### ISSUE TITLE
Invariant Violation: Duplicate React loaded

### ISSUE THREAD

**Issue by cwbuecheler** [adazzle/react-data-grid#394]
**I'm submitting a ...**  (check one with "x")

```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
We're adding react-data-grid to an existing react application. When working in a development environment, we get the following error:

![image](https://cloud.githubusercontent.com/assets/1482810/17260889/ebe22254-55a0-11e6-9329-d6013203b984.png)

It seems the issue is that we're already loading React 15.0.1 as a module in the main app. Manually going into react-data-grid's node_modules folder and removing the react folder solves the issue, but that's not really tenable given how often `npm install` is re-run during development between multiple team members.

**Expected/desired behavior**
Not getting the error. :)

**Reproduction of the problem**
The best way to duplicate it would be to add react-data-grid to an existing react application and then:

``` jsx
import React, { PropTypes } from 'react';
import ReactDataGrid from 'react-data-grid';
```

in a component.

**What is the expected behavior?**
The module should work with the existing react app, and thus not need to load its own copy of react.

**What is the motivation / use case for changing the behavior?**
I'm not quite sure why the module requires React as a dependency. It seems there are many React-based modules that work and can be worked on without having a React dependency. That said, I'm not asking you to remove the dependency! Just curious if there's something we're doing wrong or some other way to mitigate this issue. Is it possibly a flaw with our webpack build?

Apologies if this isn't a bug and should've been reported elsewhere, and thanks for your time.

**Comment by SupernaviX** [comment]
I'm using ReactDataGrid with webpack, and I resolved this issue by adding React and ReactDOM as externals in the webpack settings:

```javascript
module.exports = {
    ...
    externals: {
        'react': 'React',
        'react-dom': 'ReactDOM'
    }
}
```

In my case, React is already included in a separate webpack bundle; does this work for you too?

**Comment by cwbuecheler** [comment]
I'm actually no longer seeing this error (it was on another machine so something may have been installed wrong, there). I do get some complaints about missing required dependencies when I run `npm install` because I'm on React 15.0.1 and React-Dom 15.0.1, and the package wants older versions of React, but I'm aware that migration to React 15 is forthcoming (and it seems to work for what we're doing, at the moment, anyway).

So, I guess I'm all good here. Thanks @SupernaviX for the suggestion. If the error returns, I'll give it a shot.

**Comment by willgates** [comment]
FYI @cwbuecheler React v15 is now supported
