### ISSUE TITLE
Possible to remove vertical scrollbar ?

### ISSUE THREAD

**Issue by daniel1943** [adazzle/react-data-grid#404]
Searched and can't find any solution, I'd like to display all rows at once without the vertical scrollbar.

**Comment by diogofcunha** [comment]
Hi @daniel1943 to remove the vertical scrollbar override the `react-grid-Canvas` style with `overflowY: 'hidden'!important`.

Check the source [in here](https://github.com/adazzle/react-data-grid/blob/45edf6a4572f6722141b6146d5b6917e2d98d812/src/Canvas.js#L344).

**Comment by BorisKozo** [comment]
It doesn't help because it renders the lines too long and you can see the grid line extend beyond the grid area.
![image](https://cloud.githubusercontent.com/assets/1912858/20960653/263a9974-bc6a-11e6-911a-7cfd162a668b.png)

**Comment by sophielevens** [comment]
Hey @diogofcunha, I'm having the same issues at @BorisKozo with this when I hide it or make it ```overflowY: auto !important``` , is there a fix for this bug in the pipeline at all? 
Thanks!
