### ISSUE TITLE
Headers custom component

### ISSUE THREAD

**Issue by emaldonadoc** [adazzle/react-data-grid#410]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
Normal headers rendered, now.

**Expected/desired behavior**

I want to pass a custom component into the header or is there  a way to build a header with super header?, example :

|------------|---------------|
|---column--| other column |
| ly | cy | cly  |---------------|

I hope my example could be helpful.

**What is the motivation / use case for changing the behavior?**

I guess that this feature should be helpful to others developers to create or give style in the datagrid.

**Comment by malonecj** [comment]
You can create a Custom header renderer, passing it in as `headerRenderer` property of your column definition. There are no examples for this yet, but this is the code that handles that

https://github.com/adazzle/react-data-grid/blob/master/src/HeaderRow.js#L80

**Comment by emaldonadoc** [comment]
I couldn't find it in the docs, or some discussion trait.

Thank you!!!

**Comment by cicloid** [comment]
@malonecj I think the intention of this is more akin to column grouping, not so much using a react component as a custom renderer for the header cell

Like this: 
![rangos](https://cloud.githubusercontent.com/assets/1833/17487976/d6bd3fda-5d5c-11e6-9aa5-23e6bf48328b.jpg)

**Comment by malonecj** [comment]
@cicloid ok I see what you mean. Looks like a good feature to me. We dont have any capacity to implement this at the moment, but I'll think about how we can do it and write some info on this issue.

**Comment by cicloid** [comment]
I think @emaldonadoc and I can work on this, we wanted to give you a heads up mostly because we want to have some feedback on how the configuration of the columns should look like. So expect a pull request over the week :)

**Comment by chrismiceli** [comment]
@emaldonadoc,@cicloid Was there a pull request? I don't see one attached to this issue. Are there plans to accept this feature request?

**Comment by cicloid** [comment]
@chrismiceli sadly resources for this effort have been diverted 👎

**Comment by VEDA95** [comment]
I think I might've found a way to implement sub columns into tables however I'm having trouble implementing sorting and filtering through the `headerRenderer` property? Is there a way to implement sorting filtering manually through the headerrenderer?

**Comment by joshparolin** [comment]
@VEDA95 - Do you have a screenshot / example of your solution here? Curious to see the route you took.

**Comment by LuisGerardoAngel** [comment]
@malonecj do you have any example for this: "You can create a Custom header renderer, passing it in as headerRenderer property of your column definition"?. The link you provide is now broken.

**Comment by oliverwatkins** [comment]
Can someone explain to me how to use the headerRenderer? There is zero documentation for this

**Comment by jpstrikesback** [comment]
https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid/src/HeaderRow.js

**Comment by kaushal4340** [comment]
@oliverwatkins 
this is worked for me,
const CustomHeader = React.createClass({
    render() {
        return (
            <div>I m custome Header</div>
        )
    }
});
const columnData = [
    { key: 'id', name: 'Country Code', headerRenderer: <CustomHeader /> },
    { key: 'country', name: 'Country', sortable: true , editor: idEditor},
    { key: 'week1', name: 'CW 02/17' ,editor: IssueTypesEditor,
        formatter: IssueTypesFormatter },
    { key: 'week2', name: 'CW 01/17',  editable: true },
    {
        key: 'week3', name: 'Actions', formatter: delButtonFormatter, events: {
            onClick: function (e,f) {
                alert("clicked on row :"+f.rowIdx);
            }
        }
    },
]

See how <CustomHeader /> component is used.

**Comment by GlebDolzhikov** [comment]
Is it possible to render sort buttons inside CustomHeader?

**Comment by OmerAli** [comment]
@jpstrikesback Hi can you give me any example of custom group header example mention above any help would me appreciated Thanks Peace! :)

**Comment by hanord** [comment]
@omerali I just made a custom header renderer like this:
` .   column[2] = {key: 'age', name: 'Age', headerRenderer = CustomFormatter('Alder','blue','center) };
...
const CustomFormatter = (text,color=null,align=null) => {
    let style = {};
    if ( color )
        style.color = color;
    if ( align )
        style.textAlign = align;
    return (color || align) ? (<div style={style}>{text}</div>) : (<div>{text}</div>);
};`

You can make the same renderer to render individual cells:
` .   column[2].formatter = props => CustomFormatter(props.value,'lightgray',null);`

This simple formatter allows you to change the color or alignment of the text.

**Comment by Se0ng11** [comment]
Is it possible to increase the height of the column?

**Comment by olidacombe** [comment]
I have a branch in my fork which adds a "superHeaders" prop.

https://github.com/olidacombe/react-data-grid/tree/super-headers

See the README, essentially you specify an additional set of column headers, with a span property, specifying how many column headings to envelop.

I hope this helps someone.
