### ISSUE TITLE
Columns should be filled with data in the row groupers also

### ISSUE THREAD

**Issue by phkavitha** [adazzle/react-data-grid#411]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**

Currently, the row grouper acts like a label with no data filled in the columns

**Expected/desired behavior**

The data should be filled in the columns for a row grouper so that it can be used for displaying the total (sum of all the values in the columns)

**What is the motivation / use case for changing the behavior?**

I would like to use this library for displaying complex financial data. Though the grid supports most of the requirements, it does not allow row groupers to have data filled in (similar to financial ember-table: http://opensource.addepar.com/ember-table/#/financial)

**Comment by diogofcunha** [comment]
The grid supports that, you just need to create your own selector and row grouper, after that you can use a `rowGroupRenderer`.

Take a look at the [selector used in the example](https://github.com/adazzle/react-data-grid/blob/master/src/addons/data/Selectors.js#L28), and the [row grouper](https://github.com/adazzle/react-data-grid/blob/master/src/addons/data/RowGrouper.js#L19), if you pass the data that you need in `__metaData` you will be able to access it in the `rowGroupRenderer` (you can check the props available in the renderer [in here](https://github.com/adazzle/react-data-grid/blob/master/src/Canvas.js#L263)).

**Comment by phkavitha** [comment]
@diogofcunha , Can you tell me how to pass the data in __metaData? My requirement is: I've a checkbox in the grouper row. Clicking the checkbox should select all the child rows. To track the status of whether the row grouper checkbox is checked or not, I want to add a flag `isSelected` in the grouper row __metaData. But, I don't know how to do it. Can you please help me?

**Comment by DrogoNevets** [comment]
This is exactly what I am after, but can find no examples online on how to do this. Can someone shed some light on it please?
