### ISSUE TITLE
Hidding scrollbar on ie leaves empty space

### ISSUE THREAD

**Issue by nicomfe** [adazzle/react-data-grid#426]
**I'm submitting a ...**  (check one with "x")

```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
![screen shot 2016-08-12 at 3 43 52 pm](https://cloud.githubusercontent.com/assets/7051173/17612232/c47b96ce-60a3-11e6-8798-448b197e79a8.png)

**Reproduction of the problem**
When hidding the scroll bar for .react-grid-Canvas as follows:

.react-grid-Canvas {
  overflow-y: hidden !important;
}

It looks ok in chrome but IE 11 leaves an empty space

**Comment by diogofcunha** [comment]
Looks like a legit bug to me, we will have a look asap.

**Comment by ViciEnzo** [comment]
@nicomfe We are not able to replicate the bug.

**Comment by nevace** [comment]
This is still the case, anyone fix it?

**Comment by rlreamy** [comment]
I am also having this issue when I have set overflow-y to auto and the table does not need a scrollbar.  Has anyone looked into this?

**Comment by jamesajones** [comment]
Am stuck with a react-data-grid with no vertical scrollbar yet all the examples have one how do I get it enabled for some number of rows?

**Comment by doljura** [comment]
Hi! I have the same issue in Chrome on Windows. I have set overflow-y to auto. There is no vertical scroll but there is still empty space for scroll.

**Comment by rlreamy** [comment]
This is still an open issue for us.
