### ISSUE TITLE
Install error npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

### ISSUE THREAD

**Issue by AlexMistVrn** [adazzle/react-data-grid#429]
Node v6.3.1 
npm v3.10.3
error npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

**Comment by tg-adz** [comment]
react-data-grid doesn't use this component as its client side js.
