### ISSUE TITLE
(Question)How to set the height of a header row

### ISSUE THREAD

**Issue by dparmar74** [adazzle/react-data-grid#436]
Is there a way to control the height of a  header row?  I have a multi line header row and I don't want to display a scroll-bar and the entire header row should be visible

**Comment by diogofcunha** [comment]
Hi @dparmar74.

There is no way of doing that at the moment, the header width is tied with the row width.

We will have someone looking into this in the future.

**Comment by gaurav-quasar** [comment]
You can control header height with below prop. (Maybe recently added) 

headerRowHeight={number}

**Comment by willgates** [comment]
Hi @dparmar74, as @gaurav-quasar said you can now set the header row height by setting the `headerRowHeight` prop of `ReactDataGrid`.

**Comment by lusa** [comment]
Hello @willgates, this property doesn't seem to work for me. I have tried setting ```headerRowHeight={400}``` and the header row remains unchanged. I also tried setting the ```height``` property of the div inside of ```headerRenderer```. I don't see any examples of this in the documentation. Is this feature available?
