### ISSUE TITLE
Nav broken on example page.

### ISSUE THREAD

**Issue by weshicks** [adazzle/react-data-grid#438]
The primary dropdown navigation appears to be broken on [http://adazzle.github.io/react-data-grid/examples.html](http://adazzle.github.io/react-data-grid/). 

I realize this is probably not the appropriate place to report this, but I haven't seen any mention of it anywhere and wanted to make sure someone was aware.

**Comment by tg-adz** [comment]
Thanks we'll look into this!

**Comment by bakesteve** [comment]
all appears to be working (at least in chrome and IE11)
closing for now, but @weshicks  if you still get this please let us know what os / browser
