### ISSUE TITLE
EditorBase imported as undefined

### ISSUE THREAD

**Issue by mayk93** [adazzle/react-data-grid#439]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**

Using ES6 syntax, with "react-data-grid": "^1.0.39"

import { Editors } from 'react-data-grid/addons';
var EditorBase = Editors.EditorBase;
console.log("EB: ", EditorBase);

Looking at the console, EditorBase appears as "undefined"

This works with non base editors, for example:

import { Editors } from 'react-data-grid/addons';
var CheckboxEditor = Editors.CheckboxEditor;

CheckboxEditor is not undefined.

Both the structure in /src/ (here on GitHub) and the path in /docs/api/docs.json show EditorBase being on the same level as the other editors ( From /docs/api/docs.json  "src\\addons\\editors\\EditorBase.js"  and "src\\addons\\editors\\DropDownEditor.js" )

**Expected/desired behavior**

Being able to import EditorBase the same way I import CheckboxEditor.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.

1. Start a react project
2. npm install --save react-data-grid ( or npm install --save react-data-grid@1.0.39 )
3. Import EditorBase like this:

import { Editors } from 'react-data-grid/addons';
var EditorBase = Editors.EditorBase;
console.log("EB: ", EditorBase);

**What is the expected behavior?**

You should see in the console this: "EB:  undefined"

**What is the motivation / use case for changing the behavior?**

I need to write a custom editor.

**Comment by tg-adz** [comment]
hey @mayk93 EditorBase isn't exported in the index.js (under Editors) so it's not available publicly.  However this wasn't the best idea anyway.  Normal inheritance isn't supported in React components as the life-cycle methods wont fire correctly.  Composition and higher-order components are recommended to create re-usable code. I've attached some code for a basic editor. I'm not sure where the custom editor example went but will investigate!

The main things you need are the `getValue` and `getInputNode` functions.

```
import React from 'react';

class UpDownEditor extends React.Component {

  constructor(props){
    super(props);

    this.state = {value: this.props.value}
    this.onUpClick = this.onUpClick.bind(this);
    this.onDownClick = this.onDownClick.bind(this);
  }
  getValue() {
    return {
      [this.props.column.key]: this.state.value
    };
  }

  getInputNode() {
    return this.refs.ButtonsWrapper;
  }
  getStyle() {
    return {
      width: '100%'
    };
  }
  inheritContainerStyles() {
    return true;
  }
  onUpClick() {
    this.setState({value: this.state.value + 1})
  }
  onDownClick() {
    this.setState({value: this.state.value - 1});
  }
  render() {
    return(
      <div>
        {this.state.value}
        <div ref="ButtonsWrapper" style={{float: 'right'}}>
          <button type="button" onClick={this.onUpClick}>Up</button>
          <button type="button" onClick={this.onDownClick}>Down</button>
        </div>
      </div>
    )
  }
}

UpDownEditor.propTypes = {
  value: React.PropTypes.number.isRequired,
  column: React.PropTypes.shape({
    key: React.PropTypes.string.isRequired
  }).isRequired
}

export default UpDownEditor;
```
