### ISSUE TITLE
how to display a bootstrap dropdown button in a cell ?

### ISSUE THREAD

**Issue by rundis** [adazzle/react-data-grid#44]
Firstly: react-data-grid looks great !

I'm trying to render a bootstrap dropdown button (using react-bootstrap) in a cell. The button renders ok, but the dropdown menu doesn't display though. I guess my css foo isn't up to scratch. Any ideas on how I can bring the dropdown menu to display ?

cheers
Magnus

**Comment by bakesteve** [comment]
Thanks – glad you like it!

That all sounds possible, and we use react-bootstrap + react-data-grid elsewhere
Could you drop a screen shot in here of what you get? And if you have a working branch on your fork we could look at to see if there is anything obvious

**Comment by rundis** [comment]
Cheers !

Seems that adding `cellClass: "editing"` to the column in question did the trick. Inspired by the autocomplete editor example in: http://adazzle.github.io/react-data-grid/examples.html#/editors

**Comment by bakesteve** [comment]
glad it worked.
