### ISSUE TITLE
Autocomplete Editor sometimes selects entries when you click off grid.

### ISSUE THREAD

**Issue by abernet2** [adazzle/react-data-grid#440]
**I'm submitting a ...**  (check one with "x")

```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
The current autocomplete click handling is somewhat buggy. If you render the editor and then click off the grid, the editor will not unmount until you select another cell. 

Additionally, if you click off (it can be on/off the grid) and a suggestion is highlighted, when the component unmounts, that highlighted value will be selected and considered an update. 

**Expected/desired behavior**
Clicking off the autocomplete input and its suggestions should submit whatever is currently in the input. 

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.

Double click an autocomplete field so the editor appears. Click off the editor anywhere, but make sure your mouse flies over the suggestion box. Hovering over the suggestions will highlight an item, when you click off it will be set to the value of that cell.

If you don't see the value change, click on the original box again, it should immediately change to the highlighted value.

**What is the expected behavior?**
The highlight should either go away when the mouse leaves, or the highlighted entry should not be submitted on a click event.

**What is the motivation / use case for changing the behavior?**

**Comment by tg-adz** [comment]
hi@abernet2 we're aware of this one and have a couple of ideas, maybe adding a handler to the window to detect this case.  will be working on this shortly.
