### ISSUE TITLE
Fuzzy searching across react data grid - not per column.

### ISSUE THREAD

**Issue by switmer** [adazzle/react-data-grid#443]
**I'm submitting a feature request**  

[ ] bug report
[X] feature request
[ ] support request

**Current behavior**
Filter/search happens across all visible columns

**Expected/desired behavior**
One search input for fuzzy searching across data set.

**Example:**
"Don't make the user think - "Which column exactly do i need to search?"
![image](https://cloud.githubusercontent.com/assets/1544957/18333936/3c295ef2-7528-11e6-8e6f-6b0e22e87cbe.png)
![image](https://cloud.githubusercontent.com/assets/1544957/18333905/faf2bc9e-7527-11e6-8a53-b826e0bdd2af.png)

Different states of the search functionality...
![image](https://cloud.githubusercontent.com/assets/1544957/18333890/f00741d8-7527-11e6-801d-36601f33a91f.png)

vs.

"Making the user think: Which column do I need to search on?"
![image](https://cloud.githubusercontent.com/assets/1544957/18333862/bdadea48-7527-11e6-908d-e18591d79bbd.png)

**What is the motivation / use case for changing the behavior?**
The motivation is having a better User Experience for searching through data. People are becoming more and more accustomed to one search box to query many different pieces of data.

The current react data grid filtering example is lacking in terms of user experience in this area...so I thought I'd leave a feature request. If this is the wrong place to leave this, feel free to close the issue. 👍 

Sincerely,
A dedicated react data grid designer (non engineer)

**Comment by phkavitha** [comment]
@diogofcunha , Is there any work around to support this requirement using the existing code base? Is there any way to overwrite only the function `filterRows` function alone without touching any other selectors (https://github.com/adazzle/react-data-grid/blob/621b74a8f2740c55b255281ca2e4ad9c8722772c/src/addons/data/Selectors.js#L14). I too need this functionality very badly :(.

**Comment by diogofcunha** [comment]
Hi @phkavitha.

You can always create your own selectors and use them, you can create a selector that does a fuzzy search using your rows, to do that you can implement something similar to our selectors.

Although we don't promise performance on that.
