### ISSUE TITLE
Very slow sorting

### ISSUE THREAD

**Issue by lynnard** [adazzle/react-data-grid#448]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**

Very slow sorting in `Data.Selectors.getRows`.

**Expected/desired behavior**

Fast sort.

Basically, in <https://github.com/adazzle/react-data-grid/blob/master/src/addons/data/RowSorter.js#L4> 0 is never returned for equality - this makes sorting really slow as the algorithm would potentially keep swapping the same things back and forth.

You could try creating a big array and test the sorting with your comparator vs something that returns 0.

**Comment by willgates** [comment]
Fixed in v1.0.51
