### ISSUE TITLE
Drag down now works on many rows

### ISSUE THREAD

**Issue by IAkumaI** [adazzle/react-data-grid#451]
**I'm submitting a bug report**

Check the Cell Drag Down Example: http://adazzle.github.io/react-data-grid/examples.html#/cell-drag-down

Try to drag row to a 3-4 down - all works fine.
But try to drag row to a 20-30 rows down - not works with no errors. Event event not fired.

**Comment by diogofcunha** [comment]
Hi @IAkumaI.

This was fixed in `1.0.43`.

Cheers.
