### ISSUE TITLE
problem on the first example

### ISSUE THREAD

**Issue by ofirk12** [adazzle/react-data-grid#452]
i am try the basic example and i see the table but no the css and get this on the console 
http://adazzle.github.io/react-data-grid/examples.html#/basic

app.js:1855 Warning: Unknown props `rowIdx`, `column`, `formatter`, `rowData`, `selectedColumn`, `isRowSelected`, `expandableOptions`, `isExpanded` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Cell)
    in Cell (created by Row)
    in div (created by Row)
    in Row (created by Canvas)
    in div (created by SimpleRowsContainer)
    in SimpleRowsContainer (created by RowsContainer)
    in RowsContainer (created by Canvas)
    in div (created by Canvas)
    in Canvas (created by Viewport)
    in div (created by Viewport)
    in Viewport (created by Grid)
    in div (created by Grid)
    in div (created by Grid)
    in Grid (created by ReactDataGrid)
    in div (created by ReactDataGrid)
    in div (created by ReactDataGrid)
    in ReactDataGrid (created by Example)
    in Example (created by Datatablesjs)
    in div (created by Col)
    in Col (created by Col)
    in Col (created by Datatablesjs)
    in div (created by Row)
    in Row (created by Datatablesjs)
    in div (created by Grid)
    in Grid (created by Grid)
    in Grid (created by Datatablesjs)
    in div (created by PanelBody)
    in PanelBody (created by Datatablesjs)
    in div (created by Panel)
    in div (created by Panel)
    in Panel (created by Datatablesjs)
    in div (created by PanelContainer)
    in div (created by PanelContainer)
    in PanelContainer (created by Datatablesjs)
    in div (created by Grid)
    in Grid (created by Grid)
    in Grid (created by Datatablesjs)
    in div (created by PanelBody)
    in PanelBody (created by Datatablesjs)
    in div (created by Panel)
    in div (created by Panel)
    in Panel (created by Datatablesjs)
    in div (created by PanelContainer)
    in div (created by PanelContainer)
    in PanelContainer (created by Datatablesjs)
    in div (created by Col)
    in Col (created by Col)
    in Col (created by Datatablesjs)
    in div (created by Row)
    in Row (created by Datatablesjs)
    in Datatablesjs (created by RouterContext)
    in div (created by Col)
    in Col (created by Col)
    in Col (created by App)
    in div (created by Row)
    in Row (created by App)
    in div (created by Grid)
    in Grid (created by Grid)
    in Grid (created by App)
    in div (created by App)
    in div (created by MainContainer)
    in MainContainer (created by App)
    in App (created by RouterContext)
    in RouterContext (created by FetchData)
    in FetchData (created by Connect(FetchData))
    in Connect(FetchData) (created by Router)
    in Router
    in Provider
    in WrapperComponent
    in AppContainer

**Comment by diogofcunha** [comment]
Hi @ofirk12.

That is not enough information to reproduce your problem or to have an idea of what's wrong.

Please post the code snippet of your react-data-grid usage so that we can help you out.

**Comment by diogofcunha** [comment]
Closing do to inactivity

**Comment by sunny-g** [comment]
This is the same bug as in #468, all you have to do to reproduce it is `npm i react-data-grid` and copy and paste the basic example code.
