### ISSUE TITLE
creating sub columns

### ISSUE THREAD

**Issue by VEDA95** [adazzle/react-data-grid#458]
Is it possible to create sub-columns for a header column? Some of my data has sub-columns in it and I would like to display the sub columns along with their respective parent columns. If there is a way of doing what would be the best way of going about it?

**Comment by diogofcunha** [comment]
Hi @VEDA95.

You mentioned on #410 that you were able to implement sub columns.

You still need some help in this?

Cheers.

**Comment by VEDA95** [comment]
Sort of. I'm having trouble implementing sorting and filtering for the sub columns. I saw there were some components in the in the addons directory that could be used to implement sorting and filtering but it's not completely functioning.

**Comment by matolsen** [comment]
The react data grid look awesome, but I need to add column groups for some of my columns. It just needs to be a label above the sortable records. Is this possible? [see this example](http://facebook.github.io/fixed-data-table/example-column-groups.html) 

![image](https://cloud.githubusercontent.com/assets/7564489/19945150/3e802884-a115-11e6-957e-0b0786205583.png)

**Comment by eladfrn** [comment]
Hi, was anybody able to implement this? column groups will be very helpful.
Thanks

**Comment by shalinibajpai0310** [comment]
Hi, is anybody able to implememt column grouping as mentioned in the snapshot posted by matolsen.
Even the github link provided in #410 is not reachable.
https://github.com/adazzle/react-data-grid/blob/master/src/HeaderRow.js#L80

**Comment by shalinibajpai0310** [comment]
React Data Grid is having all the features needed in our applications but column grouping is the most important feature to implement. Guys can you please help us .

**Comment by jpstrikesback** [comment]
Now:

https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid/src/HeaderRow.js#L88

Then (Aug 1 2016 commit):

https://github.com/adazzle/react-data-grid/blob/45edf6a4572f6722141b6146d5b6917e2d98d812/src/HeaderRow.js#L80

**Comment by gazickil** [comment]
@jpstrikesback can you elaborate more about your comment? How do we implement column grouping.
I'm considering using react-data-grid instead of ag-grid but this feature is a must in our project.

**Comment by jpstrikesback** [comment]
Hey @gazickil I'm just updating the link left above, I should have said that in my post :)

**Comment by royneilfranco** [comment]
+1
