### ISSUE TITLE
Scrollbar incorrect with toolbar added and dynamic minHeight

### ISSUE THREAD

**Issue by gkourupes** [adazzle/react-data-grid#460]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**

Grid:

```
<div style={{height:'100%'}}>
    <ReactDataGrid
        minHeight={this.state.height}
        rowKey='_id'
        onGridSort={this._handleGridSort}
        columns={this._columns}
        rowGetter={this._getRow}
        rowsCount={this._getRowCount()}
                toolbar={<Toolbar enableFilter={true}/>}
                onAddFilter={this.handleFilterChange}
                onClearFilters={this.onClearFilters}
        enableRowSelect='single'
        onRowSelect={this._selectRow} />
</div>
```

Height change:

```
componentDidMount() {
    window.addEventListener('resize', this.handleResize);
},
componentWillUnmount() {
    window.removeEventListener('resize', this.handleResize);
},
handleResize() {
    this.setState({height: window.innerHeight-143}); // regrettable magic number for testing.
},
```

On initial render, it's just right.  But when the browser is resized, the 'react-grid-Canvas' div is always 37px taller than the containing 'react-grid-Viewport' div, which means the user cannot see the bottom rows of the grid.

**Suggested solution**

I found that in the render method that produces react-grid-Canvas:

```
...
var style = {
  position: 'absolute',
  top: 0,
  left: 0,
  overflowX: 'auto',
  overflowY: 'scroll',
  width: this.props.totalWidth,
  height: this.props.height,
  transform: 'translate3d(0, 0, 0)'
};

return React.createElement(
  'div',
  {
    style: style,
    onScroll: this.onScroll,
    className: joinClasses('react-grid-Canvas', this.props.className, { opaque: this.props.cellMetaData.selected && this.props.cellMetaData.selected.active }) },
  React.createElement(_RowsContainer2['default'], {
    width: this.props.width,
    rows: rows,
    contextMenu: this.props.contextMenu,
    rowIdx: this.props.cellMetaData.selected.rowIdx,
    idx: this.props.cellMetaData.selected.idx })
);
```

If I change the style as follows:

```
var style = {
  position: 'absolute',
  top: 0,
  left: 0,
  overflowX: 'auto',
  overflowY: 'scroll',
  width: this.props.totalWidth,
  bottom: 0,
  transform: 'translate3d(0, 0, 0)'
};
```

It works nicely for my case.  I'm not sure in all cases if having the react-grid-Canvas fit snugly to the react-grid-Viewport is okay or not... you guys probably know better.  But this worked well for me.

Kind regards,

**Comment by mattisborgen** [comment]
I'm new to react-data-grid and I want my ReactDataGrid to always fit the parent element's size (fill it). Am I supposed to calculate the parent size and set minHeight?

**Comment by slackday** [comment]
I am also a bit lost. Is it possible to let the width be size of the wides column? 
And height as tall as there are rows? I'd like this behaviour as default in my implementation somehow.. that is without scrollbars.. (only show scrolls if content is wider than page.

**Comment by slackday** [comment]
I am able to combat vertical scroll with this:
```
        <ReactDataGrid
          columns={columns}
          rowsCount={rows.length}
          rowGetter={this.rowGetter}
          onGridSort={this.handleGridSort}
          minHeight={((rows.length + 1) * rowHeight) + scrollBarSize}
        />
```
rows.length + 1 for header
rowHeight = 35
and scrollbarsize 20 (for safty if vertical scroll is active..

Now I only need to figure out how to hack so each column is the size of the widest cell in its column.. help would be much appreciated. I see a lot of closed issues and PRs on the problem but no solutions. Im writing here since you seems to have figured this out :) hope you dont mind..
