### ISSUE TITLE
how can i set the number of the rows loaded lazily?

### ISSUE THREAD

**Issue by azl397985856** [adazzle/react-data-grid#462]
i have a datalist of 280 rows. but renderd 44 rows once, how can i set the number of the rows loaded lazily? change 44 to 20 for example

**Comment by azl397985856** [comment]
![image](https://cloud.githubusercontent.com/assets/12479470/18701175/d7ef8088-800d-11e6-9059-0a2a9e873c98.png)

**Comment by diogofcunha** [comment]
Hi @azl397985856.

Lazy loading is not something we support at this stage. It's definitively something that we want to support in the future.

Let's keep this conversation on #302 and if you fell comfortable enough to propose a solution for lazy loading on a new PR we will look into it.
