### ISSUE TITLE
Allow cellNavigationMode to specify the starting column for 'changeRow'

### ISSUE THREAD

**Issue by buddyp450** [adazzle/react-data-grid#466]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report
[X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
Cell navigation directs focus to the first column of the next row when set to 'changeRow'

**Expected/desired behavior**
Would like to specify a starting column index that is used for when changeRow navigates to the next row.

**What is the motivation / use case for changing the behavior?**
The first column of my table is non-editable so it doesn't make sense to focus.

**Comment by diogofcunha** [comment]
Hi @buddyp450, thanks for this.

Looks like a reasonable thing to support, we will put it on our road map but in the meantime if you don't want to wait you can always open a new PR that will be merged in.
