### ISSUE TITLE
Support for external data loading?

### ISSUE THREAD

**Issue by lrhazi** [adazzle/react-data-grid#47]
How would you use this component for server side generated data?

**Comment by bakesteve** [comment]
you just need to wire up your data into the row getter
For most of our use cases, we use flux and a store, with a creator action to initially load the data in from the server, though no requirement to use flux, as long as your row getter can access the data, you'll be fine. 

We haven't used it for infiite scroll style scenarios, though there is no reason you cant load the data in chunks. to do that you'd just kick off your load inside the rowGetter, so something like:
- on load, load in a sensible initial chunk. Say 100 rows.
- in your [row getter](https://github.com/adazzle/react-data-grid/blob/master/examples/scripts/example01-basic.js#L8) if you are nearing the edge of your fetched data, go load some more
- one note, you'll need to either know your estimated rowCount, or keep updating it as you fetch more data

**Comment by oliverwatkins** [comment]
does the grid come with support for a spinner?
