### ISSUE TITLE
CSS not loaded 

### ISSUE THREAD

**Issue by bushan1891** [adazzle/react-data-grid#485]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
all table loaded without any styling 

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Comment by willgates** [comment]
Hi @bushan1891 - could you please provide a screenshot?

**Comment by jpdriver** [comment]
we don't include the CSS by default -- if you want the Bootstrap styling the Examples use, you need to import https://github.com/adazzle/react-data-grid/blob/master/themes/react-data-grid.css separately

**Comment by bushan1891** [comment]
issue resolved after importing react-data-grid.css separately.
Thank you :)
