### ISSUE TITLE
Unable to install - npm install react-data-grid --save

### ISSUE THREAD

**Issue by venkat-vs-id** [adazzle/react-data-grid#486]
when tried to 
npm install react-data-grid --save

got the following errors
npm WARN package.json django@1.0.0 No description
npm WARN package.json django@1.0.0 No repository field.
npm WARN package.json django@1.0.0 No README data
npm WARN peerDependencies The peer dependency react@~0.14.6 included from react-data-grid will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency react-dom@~0.14.6 included from react-data-grid will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency react@~0.14.6 included from ron-react-autocomplete will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency react-dom@~0.14.6 included from ron-react-autocomplete will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN optional dep failed, continuing fsevents@1.0.14
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@15.1.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-dom@15.1.0 wants react@^15.1.0
npm ERR! peerinvalid Peer react-router@2.5.0 wants react@^0.14.0 || ^15.0.0
npm ERR! peerinvalid Peer react-redux@4.4.5 wants react@^0.14.0 || ^15.0.0-0
npm ERR! peerinvalid Peer react-data-grid@1.0.50 wants react@~0.14.6

npm ERR! Please include the following file with any support request:
npm ERR!     D:\python\Django\reactjs\npm-debug.log

**Comment by willgates** [comment]
Hi @venkat-vs-id. We're currently not supporting React v15. Please see #280 for any updates on this.
