### ISSUE TITLE
Make rows default checked

### ISSUE THREAD

**Issue by paweljurczynski** [adazzle/react-data-grid#490]
Hi, Can anyone tell me how to set rows as default checked? I set this in constructor but this error appears:

warning.js:45 Warning: Failed form propType: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`. Check the render method of `CheckboxEditor`.

**Comment by diogofcunha** [comment]
Hi @paweljurczynski.

If you are using the recommended row selection all you will need to do is having the rowKeys that you want to be checked passed as prop, and use that for the row selection.

A small example of a use case based on [this example](http://adazzle.github.io/react-data-grid/examples.html#/row-select)

```
class Grid extends Component {
   constructor(props) {
      super(props);
      const { selectedIndexes} = props;
      this.onRowsSelected.bind(this);
      this.onRowsDeselected.bind(this);
      this.state = { selectedIndexes }
   }
   
   onRowsSelected(rows) {
      this.setState({selectedIndexes: this.state.selectedIndexes.concat(rows.map(r => r.rowIdx))});
   }

   onRowsDeselected(rows) {
      let rowIndexes = rows.map(r => r.rowIdx);
      this.setState({selectedIndexes: this.state.selectedIndexes.filter(i => rowIndexes.indexOf(i) === -1 )});
   }
   
   ...

   render() {
      return (<ReactDataGrid
         ...
         rowSelection={{
            showCheckbox: true,
            enableShiftSelect: true,
            onRowsSelected: this.onRowsSelected,
            onRowsDeselected: this.onRowsDeselected,
            selectBy: {
              indexes: this.state.selectedIndexes
            }
          }}
   }
}
```
