### ISSUE TITLE
Possible for Formatter's props to include column info?

### ISSUE THREAD

**Issue by dkwin** [adazzle/react-data-grid#492]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

Was wondering if it was possible to include column info in the props passed to the Formatter.  It'd be nice to have so that the formatter knows more about the column

**Comment by diogofcunha** [comment]
Hi @dkwin you can do that injecting the formatter as a `element`.

If you render an element and pass it as a prop it will be cloned and the dependentValues will be concatenated to your props. (you can check the code [in here](https://github.com/adazzle/react-data-grid/blob/master/src/Cell.js#L435)).

Cheers.
Diogo
