### ISSUE TITLE
Add ability to add column reordering [Feature]

### ISSUE THREAD

**Issue by dkwin** [adazzle/react-data-grid#495]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**

As of right now, column reordering is not supported but row reordering is.

**Expected/desired behavior**

User should be able to reorder columns via drag and drop or some other means to designate the new order of the columns.

**Reproduction of the problem**
N/A

**What is the motivation / use case for changing the behavior?**

Ability to re-order columns would be a huge UX boon to the component.

**Comment by akhildhargave** [comment]
Is there any work done on this, or any timeline when this will be available?

**Comment by diogofcunha** [comment]
Thanks for your feedback.

We will implement this somewhere in the future, in the meantime if someone opens a PR we will review and merge it.

Cheers.
Diogo

**Comment by jlarso11** [comment]
Did this ever get implemented?

**Comment by pmchugh3** [comment]
+1 to this. It is the kind of feature you don't want to have to tack on to a 3rd party library so it could be the difference between this library being used in projects and not.

**Comment by martinnov92** [comment]
Here is more info https://github.com/adazzle/react-data-grid/issues/103

**Comment by martinnov92** [comment]
Pull request was made https://github.com/adazzle/react-data-grid/pull/702

**Comment by malonecj** [comment]
Merged in https://github.com/adazzle/react-data-grid/pull/702
