### ISSUE TITLE
Is there an event on Mouse Scroll?

### ISSUE THREAD

**Issue by vedran-maestral** [adazzle/react-data-grid#496]
I am implementing endless scrolling, and it would be great to have an event on the mouse scroll.

An event that is fired every time I do the scroll, and when there is no more data to show then fill the grid with more data.

**Comment by vedran-maestral** [comment]
Or at least is there an option to see what rowas are displayed currently on the screen. For example I have 500 rows, and showing 450-500... then I might be able to implement on scroll in native react.js

**Comment by vedran-maestral** [comment]
I have found there is an event on mouse scroll:
onScroll={this.onScroll}
And that works, however, how can I see the position of the scroll bar in the grid viewport?

**Comment by vedran-maestral** [comment]
I could not implement infinite scrolling, but I implemented infinite "buttoning". When the user reaches the end of the list, a Load Mmore button is shown. clicking it, it will load another data set and append it to the grid.

This implementation involved many workaround, if someone is interested how to achieve it, please ask here and we can discuss.

**Comment by tobyhede** [comment]
I'd love to see the code if you can, I am attempting to get something similar working.

**Comment by stevelacy** [comment]
@vedran-maestral Do you have a diff of the changes you added?
