### ISSUE TITLE
Disabling a specific cell on the grid

### ISSUE THREAD

**Issue by nicomfe** [adazzle/react-data-grid#498]
[ ] bug report
[X] feature request
[ ] support request

Is it possible to disable a specific cell on the grid?

**Comment by diogofcunha** [comment]
Hi @nicomfe, what do you mean by disabling?

Hide a cell? Make it readonly?

**Comment by nicomfe** [comment]
make it readonly

**Comment by pidupuis** [comment]
Any workaround?

**Comment by dg92** [comment]
@nicomfe @pidupuis  any updates?

**Comment by pidupuis** [comment]
@dg92 Nope :/

**Comment by amanmahajan7** [comment]
You can use [`onCheckCellIsEditable`](https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid/src/ReactDataGrid.js#L117) prop to make some cells readonly.

```
checkCellEditable = ({ column, row }) => {
   // Return true/false
};

render() {
  return(
     <ReactDataGrid ... 
        onCheckCellEditable={this.checkCellEditable}
     />
  );
}
```

**Comment by zebralight** [comment]
> You can use [`onCheckCellIsEditable`](https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid/src/ReactDataGrid.js#L117) prop to make some cells readonly.
> 
> ```
> checkCellEditable = ({ column, row }) => {
>    // Return true/false
> };
> 
> render() {
>   return(
>      <ReactDataGrid ... 
>         onCheckCellEditable={this.checkCellEditable}
>      />
>   );
> }
> ```

when defining `checkCellEditable` like so to make all cells editable:
```
checkCellEditable = ({ column, row }) => true
```
All cells are still read only.

**Comment by dongapplyboard** [comment]
This disables the entire row, what about just particular cells (eg. A cell at column 1, row 2)

**Comment by dongapplyboard** [comment]
> > > You can use [`onCheckCellIsEditable`](https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid/src/ReactDataGrid.js#L117) prop to make some cells readonly.
> > > ```
> > > checkCellEditable = ({ column, row }) => {
> > >    // Return true/false
> > > };
> > > 
> > > render() {
> > >   return(
> > >      <ReactDataGrid ... 
> > >         onCheckCellEditable={this.checkCellEditable}
> > >      />
> > >   );
> > > }
> > > ```
> > 
> > 
> > when defining `checkCellEditable` like so to make all cells editable:
> > ```
> > checkCellEditable = ({ column, row }) => true
> > ```
> > 
> > 
> > All cells are still read only.
> 
> @zebralight This disables the entire row, what about just particular cells (eg. A cell at column 1, row 2)

Nevermind found out that you can utilize the editable prop in columns that takes the rowData prop and disable that certain column and row (cell) when the data changes. 

```
columns = [
      {
        key: 'id',
        name: 'ID'
      },
      {
        key: 'location_id',
        name: 'Location ID',
        editable: function(rowData) {
          return rowData.allowEdit === true;
        }
      }
]
```

**Comment by Talamantez** [comment]
> You can use [`onCheckCellIsEditable`](https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid/src/ReactDataGrid.js#L117) prop to make some cells readonly.
> 
> ```
> checkCellEditable = ({ column, row }) => {
>    // Return true/false
> };
> 
> render() {
>   return(
>      <ReactDataGrid ... 
>         onCheckCellEditable={this.checkCellEditable}
>      />
>   );
> }
> ```

Hi - Thanks for the solution. There is a typo in this example.  In the ReactDataGrid JSX component, the 'onCheckCellEditable' prop should be 'onCheckCellIsEditable'.
Thanks!

**Comment by naishe** [comment]
### This has changed since [v7.0.0-canary.27](https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md#v700-canary27)

[Link to PR](https://github.com/adazzle/react-data-grid/pull/2016)

You need to specify editability where you configure your column

```typescript
Column<YourRowType, unknown>.editable?: boolean | ((row: ExtendedCurationRow) => boolean) | undefined
```
