### ISSUE TITLE
TypeError: _addons2.default is undefined

### ISSUE THREAD

**Issue by andy2046** [adazzle/react-data-grid#499]
**I'm submitting a ...**  (check one with "x")

```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
Built-In Cell Editor Example DropdownEditor

TypeError: _addons2.default is undefined

TypeError: w.default is undefined

...e:"story",text:"Story",title:"Story"}],C=w["default"].Editors.DropDownEditor,E=f...

**Expected/desired behavior**

No error

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

//options for IssueType dropdown editor
//these can either be an array of strings, or an object that matches the schema below.
var issueTypes = [
  { id: 'bug', value: 'bug', text: 'Bug', title: 'Bug' },
  { id: 'improvement', value: 'improvement', text: 'Improvement', title: 'Improvement' },
  { id: 'epic', value: 'epic', text: 'Epic', title: 'Epic' },
  { id: 'story', value: 'story', text: 'Story', title: 'Story' }
];
var DropDownEditor = ReactDataGridPlugins.Editors.DropDownEditor;
var IssueTypesEditor = <DropDownEditor options={issueTypes}/>;

var DropDownFormatter = ReactDataGridPlugins.Formatters.DropDownFormatter;
var IssueTypesFormatter = <DropDownFormatter options={issueTypes}/>;

//helper to create a fixed number of rows
function createRows(numberOfRows){
  var _rows = [];
  for (var i = 1; i < numberOfRows; i++) {
    _rows.push({
      id: i,
      task: 'Task ' + i,
      priority : ['Critical', 'High', 'Medium', 'Low'][Math.floor((Math.random() \* 3) + 1)],
      issueType : issueTypes[Math.floor((Math.random() \* 3) + 1)].value,
      startDate: randomDate(new Date(2015, 3, 1), new Date())
    });
  }
  return _rows;
}

//Columns definition
var columns = [
{
  key: 'id',
  name: 'ID',
  width: 80
},
{
  key: 'task',
  name: 'Title',
  editable : true
},
{
  key: 'priority',
  name: 'Priority',
  editable : true
},
{
  key : 'issueType',
  name : 'Issue Type',
  editor : IssueTypesEditor,
  formatter: IssueTypesFormatter,
  editable : true
},
{
  key: 'startDate',
  name: 'Start Date',
  editable : true
}
]

**Comment by diogofcunha** [comment]
The problem is in your imports, can you show us the you're import `ReactDataGridPlugins`?

**Comment by DaisukeOtaka** [comment]
Hi @andy2046.
I also had the same error.
It probably caused by your import as diogofcunha commented.

Please referrer my sample code. I hope it will help you.
https://gist.github.com/DaisukeOtaka/123d1a9fdef29fe22a7fffe587491214

**Comment by andy2046** [comment]
@DaisukeOtaka @diogofcunha it's import issue, solved, thanks
