### ISSUE TITLE
Add Column to table in editor

### ISSUE THREAD

**Issue by yarnball** [adazzle/react-data-grid#500]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
I have a would like an ability to add columns on the fly (similar to how your "AllFeatures" example works with rows).

**Expected/desired behavior**
I should be able to click "Add column" and another colum will appear

**My attempt to create this feature**

    handleAddCol : function(e){
      var newCol = {
        value: e.newCoIndex,
        userStory: '',
        developer : ol
        epic : ''};
        var rows = React.addons.update(this.state.cols, {$push : [newCol]});
        this.setState({cols : cols});
    },

**Comment by kdymowski** [comment]
This would be a useful feature.

**Comment by willgates** [comment]
Forking the react-data-grid basic example I've created a [JSFiddle with an Add Column button](https://jsfiddle.net/h00a2naw/)
