### ISSUE TITLE
Delete a row Or Empty the table

### ISSUE THREAD

**Issue by basketballislife** [adazzle/react-data-grid#503]
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support request here, instead see 
**Current behavior**
The toolbar of the table only has one button which is "Add Row"

**Expected/desired behavior**
1. Delete the row which isSelect
2. Empty the whole table
PS:  Or there have already been the ways to solve my problems??? But I didn't find out???

**Comment by diogofcunha** [comment]
Hi @basketballislife.

The toolbar is exposed as an addon, you can either use it or not it's up to you.

The grid is supposed to be a powerful core to support multiple use cases, I don't think it makes much sense to implement that as the rows themselves are handled outside the grid, is something that you have full control of and the grid doesn't need to know about the way you're storing you're rows.

What you can do is create your own toolbar (or extend the one we offer in the addons) and create a new button to clear all the rows. The best way to do it will depend on the way you're storing the rows but basically what you will need to do is pass an empty row object (array, immutable whatever) and re-render the grid.

For the deletion the concept is the same, you handle the way the rows are stored outside the grid, get the new rows object after deletion and re-render
Cheers
