### ISSUE TITLE
Adding a new record under the heading table

### ISSUE THREAD

**Issue by Sebszty** [adazzle/react-data-grid#505]
Is it possible to create tables in such a way to add a new record under the heading together with the button Add?
![table custom](https://cloud.githubusercontent.com/assets/8779655/20071300/3a391ec6-a524-11e6-91da-b845cd7f2744.JPG)

**Comment by G710** [comment]
You should be able to do this by using the ```handleAddRow``` callback of the ReactDataGrid component. See the [full feature example](http://adazzle.github.io/react-data-grid/examples.html#/all-features) to see how to use the callback. Then instead of adding a new row, make the new input mask visible.

**Comment by diegomurakami** [comment]
@Sebszty did you manage to solve your issue with @G710 explanation?

**Comment by vpolimenov** [comment]
the link is broken

**Comment by G710** [comment]
Yeah, it's been three years and a lot has changed since then. 

I haven't used this library in quite some time but looking at the docs you might be able to intercept a row and use a custom row renderer to achieve the same result. Just append an empty object and the instead of showing a normal row you can render the form for the new entry.

**Comment by Fareedbaba** [comment]
> Yeah, it's been three years and a lot has changed since then.
> 
> I haven't used this library in quite some time but looking at the docs you might be able to intercept a row and use a custom row renderer to achieve the same result. Just append an empty object and the instead of showing a normal row you can render the form for the new entry.

would you be able to add any sample code block for the same, if it was implemented

**Comment by G710** [comment]
Sorry, I don't have access to my computer for the next month. If it's still an open issue I can take a look at it in a few weeks.
