### ISSUE TITLE
Dragging up reverses "to" and "from" rows in unexpected way.

### ISSUE THREAD

**Issue by patrick-jones** [adazzle/react-data-grid#507]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
When using the drag handle, if the user drags up rather than down, the event uses the last (top) row as the "from" row, and the first (bottom) row as the "to" row. This results in copying down from the last dragged-to cell to the origin cell, rather than copying up from the origin cell.

**Expected/desired behavior**
When dragging up, the bottom cell should be the "from" index and the top cell should be the "to" index.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.
In the [cell drag down example](http://adazzle.github.io/react-data-grid/examples.html#/cell-drag-down), select the Priority cell for row 10, then drag the handle up until you reach a value different from what is in row 10. Rather than copying row 10's value up, it will copy the uppermost cell's value down.

**What is the expected behavior?**
That you will copy up from the origin to the destination.

**What is the motivation / use case for changing the behavior?**
The current behavior is surprising and contrary to the way spreadsheets work. Besides, sometimes it would be handy to copy up.

**Comment by willgates** [comment]
@patrick-jones I can't reproduce this on any browser
