### ISSUE TITLE
How  inserting button from event in cell

### ISSUE THREAD

**Issue by Sebszty** [adazzle/react-data-grid#508]
Hey,
is there a way to insert the button(eg. button edit and delete) into the cell and click to get the whole row? 
I tried, but such is not working:
```
{
             key: 'dontReading',
             name: ' ',
             width : 100,
             resizable: true,
             formatter : <span className = "btn-group  btn-group-sm"> <button type = "button" className="btn btn-primary custom-button-crud" onClick = {this.handleDontReading.bind(this) } > Edit page </button></span>
}
```
```
handleDontReading(e){
        console.log(e);
}
```

![image](https://cloud.githubusercontent.com/assets/8779655/20170306/07c5147c-a72c-11e6-8fa5-6e5609682c49.png)

**Comment by GenoD** [comment]
If you want to access the props of that specific row there is a solution under this past issue.

#42

**Comment by diogofcunha** [comment]
Closing this one, @GenoD replied correctly

**Comment by shubhi1990** [comment]
Hi,
Is there a way to add 2 buttons in the react data grid column like approve and reject which can be hidden for certain users(that can be checked through some other method).
I have one of my column as:
{
        key: 'redirectAction',
        name: 'Redirect Action',
        filterable: true,
        sortable: false,
        editable: false,
        locked: true,
        resizable: true,
      }

**Comment by shubhi1990** [comment]
Hi,
Is there a way to add 2 buttons in the react data grid column like approve and reject which can be hidden for certain users(that can be checked through some other method).
I have one of my column as:
{
key: 'redirectAction',
name: 'Redirect Action',
filterable: true,
sortable: false,
editable: false,
locked: true,
resizable: true,
}
