### ISSUE TITLE
rowSelection with onRowUpdated

### ISSUE THREAD

**Issue by heks** [adazzle/react-data-grid#514]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

How can I get ```rowSelection``` to work with ```onRowUpdated```. So basically I want to be able to update row data with a custom selection.

**Comment by GenoD** [comment]
When you say "custom selection" do you mean a dropdown?

**Comment by heks** [comment]
no "custom selection" as in this example:

[custom row selection](http://adazzle.github.io/react-data-grid/examples.html#/row-select
)

I want to work with this:

[built in editors](http://adazzle.github.io/react-data-grid/examples.html#/built-in-editors)

currently you can only use one or the other, is there a way where they can both work together?

**Comment by GenoD** [comment]
So you want to update the "custom selection" of selected rows?

**Comment by heks** [comment]
No you misunderstood. I want to be able to use "custom selection" with "built in editors"

Please see [this example](http://adazzle.github.io/react-data-grid/examples.html#/row-select) and read:

`Note: These props supercede the existing enableRowSelect and onRowUpdated props which will be removed in a later release.`

You cannot use both of these features at the same time. Does that make sense?

**Comment by diogofcunha** [comment]
Hi @heks.

That is possible, you need to use `onGridRowsUpdated`, onRowUpdated it's legacy and should be avoided.

To understand the use case of `onGridRowsUpdated`, check [All the features example](http://adazzle.github.io/react-data-grid/examples.html#/all-features)
