### ISSUE TITLE
Column Headers Do Not Adjust Properly after a Column Resize

### ISSUE THREAD

**Issue by adamdriscoll** [adazzle/react-data-grid#521]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**

Column resize handles and column headers are misaligned after adjusting re-sizable column widths.

**Expected/desired behavior**

Column handles and headers should line up with row data. 

**Reproduction of the problem**

I have a data grid in a Materialize CSS modal and it is behaving very strangely when I resize columns. See the below picture of the result of changing a column size. I resized the first column in the table. The result is that the row data is resized but not the column headers and the resize handle disappears. 

![image](https://cloud.githubusercontent.com/assets/1256531/20342384/779ff114-abea-11e6-9fb3-904231e6582d.png)

If I then resize the last column, you can see it resizes the header and data but the first two headers are still incorrect. 

![image](https://cloud.githubusercontent.com/assets/1256531/20342443/b1cc856e-abea-11e6-91dc-41ed6ad94832.png)

I'm bringing in the data grid script as a script tag. 

`   <script type="text/javascript" src="~/lib/react-data-grid/react-data-grid.js"></script>`

I'm using react 15.4.0-rc.3.

My columns are defined pretty simply. 

```
    const columns = [
            {
                key: 'path',
                name: 'Object Name',
                resizable: true
            },
            {
                key: 'attribute',
                name: 'Attribute',
                resizable: true
            },
            {
                key: 'value',
                name: 'Value',
                resizable: true
            }
        ];
```

And my usage of the component is pretty straight forward. 

```
                <div className="row">
                    <div className="col s12">
                        <ReactDataGrid columns={columns} rowGetter={this.loadRow.bind(this)} rowsCount={this.state.rowCount} minHeight={300} />
                    </div>
                </div>
```

**What is the expected behavior?**

The column headers adjust properly. 

**What is the motivation / use case for changing the behavior?**

It becomes very difficult to use when this happens.

**Comment by adamdriscoll** [comment]
I think this is similar to #85. I'll look at the solutions in that issue.

**Comment by jpdriver** [comment]
hey @adamdriscoll -- this is a known issue with React 15 😞 for now the best option is probably to stick with `resizable: false` on your columns, though if you do end up investigating it please share your findings with everyone!

**Comment by adamdriscoll** [comment]
Thanks for the quick feedback, @jpdriver! I'll do some investigation and update this issue if I find anything useful.

**Comment by jpdriver** [comment]
looks like there was actually a seemingly related fix done yesterday https://github.com/adazzle/react-data-grid/pull/517

are you on the latest version of react-data-grid?

**Comment by adamdriscoll** [comment]
I was on 1.0.57 and upgrading to 1.0.60 fixed the issue. Thanks!

**Comment by jpdriver** [comment]
amazing hopefully that's fixed all of the resize issues even on RCT 15 then! 😄
