### ISSUE TITLE
Missing cell data after opening the filter fields 

### ISSUE THREAD

**Issue by dimonge** [adazzle/react-data-grid#525]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
After update to the v1.0.61, the cell component is replaced with ComponentWrapper after clicking the filter button. Thus, my data disappeared from the cells

**Expected/desired behavior**
The expected behavior is that I should see the filter fields at the top, and the data in the cells

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Comment by diegomurakami** [comment]
Hi @dimonge,

Could you send your code here so we can help you better ?

Cheers~
