### ISSUE TITLE
react-data-grid/addon is not working with react-data grid.

### ISSUE THREAD

**Issue by KalpanaPagariya** [adazzle/react-data-grid#530]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
import ReactDataGridPlugins from 'react-data-grid/addons'; Whenever use this, it failes to load any class within it. even as per guidenline, this should provide data grid also. But its not working

If I try to use data grid from addons, below error comes up:

warning.js:36Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `MyDataGrid`.printWarning @ warning.js:36warning @ warning.js:60createElement @ ReactElementValidator.js:167AvayaDataGrid_render @ MyDataGrid.js:103(anonymous function) @ ReactCompositeComponent.js:793measureLifeCyclePerf @ ReactCompositeComponent.js:74_renderValidatedComponentWithoutOwnerOrContext @ ReactCompositeComponent.js:792_renderValidatedComponent @ ReactCompositeComponent.js:819performInitialMount @ ReactCompositeComponent.js:361mountComponent @ ReactCompositeComponent.js:257mountComponent @ ReactReconciler.js:47performInitialMount @ ReactCompositeComponent.js:370mountComponent @ ReactCompositeComponent.js:257mountComponent @ ReactReconciler.js:47mountComponentIntoNode @ ReactMount.js:105perform @ Transaction.js:138batchedMountComponentIntoNode @ ReactMount.js:127batchedUpdates @ ReactDefaultBatchingStrategy.js:61batchedUpdates @ ReactUpdates.js:98_renderNewRootComponent @ ReactMount.js:321_renderSubtreeIntoContainer @ ReactMount.js:402render @ ReactMount.js:423openUserTable @ MenuDashboard.js:60onTouchTap @ Menu.js:219EnhancedButton._this.handleTouchTap @ EnhancedButton.js:147ReactErrorUtils.invokeGuardedCallback @ ReactErrorUtils.js:70executeDispatch @ EventPluginUtils.js:89executeDispatchesInOrder @ EventPluginUtils.js:112executeDispatchesAndRelease @ EventPluginHub.js:44executeDispatchesAndReleaseTopLevel @ EventPluginHub.js:55forEachAccumulated @ forEachAccumulated.js:25processEventQueue @ EventPluginHub.js:231runEventQueueInBatch @ ReactEventEmitterMixin.js:18handleTopLevel @ ReactEventEmitterMixin.js:29handleTopLevelImpl @ ReactEventListener.js:73perform @ Transaction.js:138batchedUpdates @ ReactDefaultBatchingStrategy.js:63batchedUpdates @ ReactUpdates.js:98dispatchEvent @ ReactEventListener.js:150
invariant.js:38Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `MyDataGrid`.

Code:

import React from 'react';
import ReactDataGrid from 'react-data-grid/addons';

render:function(){
    return(
      <ReactDataGrid
      ref='grid'
        enableRowSelect={true}
      //  enableCellSelect={true}
        onGridSort={this.handleGridSort}
        columns={columns}
        rowGetter={this.rowGetter}
        rowsCount={this.state.rows.length}
        minHeight={500}
        onRowUpdated={this.handleRowUpdated} />
    )
  }

**Comment by G710** [comment]
Your imports are not correct. You have to import ReactDataGrid from "react-data-grid"

Example:

```
import React from 'react'; 
import ReactDataGrid from 'react-data-grid';
```

You import the addons to use advanced features like formatters, the toolbar, etc. Take a look at the quick start section for more infos: http://adazzle.github.io/react-data-grid/index.html

**Comment by nionis** [comment]
```javascript
import React, { Component } from 'react'
import ReactDataGrid from 'react-data-grid'
import ReactDataGridPlugins from 'react-data-grid/addons'

console.log(ReactDataGridPlugins) //undefined
```
React version: 15.3.2
