### ISSUE TITLE
Clicking to sort column does not update the sort direction icon, and only the first click sorts the data, introduced between (inclusive) 1.0.57, before 1.0.62

### ISSUE THREAD

**Issue by supamanda** [adazzle/react-data-grid#531]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
Clicking on the header cell of a sortable column does not update the sort direction icon, and only the first click sorts the data

**Expected/desired behavior**
When grid column is sortable, you should be able to click on the column header and change the sort direction, NONE -> ASC -> DESC -> NONE, which was the previous behaviour

**Reproduction of the problem**

Go to http://adazzle.github.io/react-data-grid/examples.html#/sortable-cols
Click on the Title column once

Expected: Title data is sorted ascending, Title column should show ASC arrow
Actual: Title data is sorted ascending. Title column shows no arrow

Click on the Title column again

Expected: Title data is sorted descending, Title column should show DESC arrow
Actual: Title data is still sorted ascending. Title column shows no arrow

**Comment by ocularrhythm** [comment]
Just noticed this behavior as well since updating to 1.0.64
