### ISSUE TITLE
Show tree like style on group by column

### ISSUE THREAD

**Issue by OliverKK** [adazzle/react-data-grid#534]
**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[X] v0.14.x
```

```
Community Supported:
[ ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[X] Edge
[X] Chrome
```

```
Should work:
[X] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
The react-data-grid can group by columns, but does not display the grouped columns
in an tree like shape. See: [https://picload.org/image/ragclwap/listview_tree.png](https://img1.picload.org/image/ragclwap/listview_tree.png)

**Expected/desired behavior**
If a grouping by a column takes place the tree like shape should be displayed

**What is the motivation / use case for changing the behavior?**
The tree like shape is a well known pattern which users know and like.

**Comment by malonecj** [comment]
The link for that image does not work. Could you re-upload please?

**Comment by willgates** [comment]
@OliverKK Here's an [example](http://adazzle.github.io/react-data-grid/examples.html#/grouping) of react-data-grid grouped by two columns, which shows those columns in a tree view. This should solve your problem?
![image](https://cloud.githubusercontent.com/assets/11860584/23031590/750d7292-f469-11e6-976c-bda0798b61ce.png)
