### ISSUE TITLE
Error: Can't resolve './node_modules/react-select/less/select.less'

### ISSUE THREAD

**Issue by ganapativs** [adazzle/react-data-grid#535]
**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[x] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[x] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
ERROR in ./~/css-loader?-discardDuplicates!./~/react-data-grid/themes/react-data-grid.css
Module not found: Error: Can't resolve './node_modules/react-select/less/select.less' in '/Users/guns/tracxn/tracxnportal/node_modules/react-data-grid/themes'
 @ ./~/css-loader?-discardDuplicates!./~/react-data-grid/themes/react-data-grid.css 3:10-114
 @ ./~/react-data-grid/themes/react-data-grid.css

Issue: @import './node_modules/react-select/less/select.less' in 'themes/react-data-grid.css'

**Expected/desired behavior**
Ideally react-data-grid.css shouldn't import .less file in relative node module folder as latest npm uses plain module directory structure and I have react-select module installed.
or should it be @import '../../node_modules/react-select/dist/react-select.css' ?

**Reproduction of the problem**
Using react-data-grid@1.0.65 + webpack with css + style loader (No less loader).

**Comment by anujit** [comment]
Facing the same issue. Is there any solution other than just commenting out the import?

**Comment by dpastoor** [comment]
it works by removing the relative path, so 

`/node_modules/...etc`, as of now it is looking for the node modules relative to the themes folder.

**Comment by kzde** [comment]
This import is really necessary? Variables initialized in imported less file aren't used in this css file.
No regressions founded in local environment when i remove this import

**Comment by MathieuMz** [comment]
select.less just initialize variables, but also import others .less file, with css directives. The question is : Does react-data-grid project became less dependant ? Or is it an "oblivion" ?
