### ISSUE TITLE
Wrapping cell and responsive

### ISSUE THREAD

**Issue by Sebszty** [adazzle/react-data-grid#536]
Is there any possibility to wrap text in cells? How to make a large table she would appear on the tablet, phone? Below please find a template:
![image](https://cloud.githubusercontent.com/assets/8779655/20648318/a8ca81d4-b4a3-11e6-812d-d8e571cf4235.png)

**Comment by diogofcunha** [comment]
Please read the docs before asking,
Check the [basic example](http://adazzle.github.io/react-data-grid/examples.html#/basic)

**Comment by JimTheMan** [comment]
What was the answer for how to wrap text in cells?

**Comment by email2vimalraj** [comment]
@diogofcunha : I'm not able to find any of the doc talks about text wrapping. Could you please help us to find the doc for text wrapping?

**Comment by ryarasi** [comment]
In the basic example width is not specified (see 'Jump to source code' on the example page - http://adazzle.github.io/react-data-grid/scripts/example01-basic.js). If you don't specify the width, it will automatically resize columns. 

But I don't believe text wrapping happens. So not sure why this is closed.

**Comment by nwhitmont** [comment]
Apparently text wrapping is not a feature.

**Comment by fanatov37** [comment]
use formatter 
for example :

```
columns : [
                {
                    key: 'text',
                    name: 'Text',
                    formatter : WrapperFormatter
                },
               
            ];
```
```
import React from 'react'


export default class WrapperFormatter extends React.Component {
    static propTypes = {
        value: React.PropTypes.number.isRequired
    };
    static defaultProps = {
        value : 0
    }
    /**
     *
     * @returns {*}
     */
    render() {
        return (<p style={{whiteSpace:'pre-wrap'}}>{this.props.value}</p>)
    }
}

```
