### ISSUE TITLE
Navigation dropdowns stop working in examples section of documentation

### ISSUE THREAD

**Issue by ocularrhythm** [adazzle/react-data-grid#543]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[v0.14.7 ] v0.14.x
```

```
Community Supported:
[ ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ x] IE 9 / IE 10 / IE 11
[ ] Edge
[ x] Chrome
```

```
Should work:
[x ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
When you visit the examples section of the documentation, the navigation dropdowns stop functioning. 

**Expected/desired behavior**
The navigation items to display their dropdowns respectively.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.

1. Visit [the documentation](http://adazzle.github.io/react-data-grid/index.html)
2. Click on Examples
3. Select any example item
4. After page load, click on documentation or examples and the dropdowns do not appear

**What is the expected behavior?**
The navigation items to display their dropdowns respectively.

**What is the motivation / use case for changing the behavior?**
It is an annoyance when trying to navigate throughout the website.  I'm sure there is an easy fix, but am unable to devote time to this effort currently.

**Comment by willgates** [comment]
This was fixed in v2
