### ISSUE TITLE
rowRenderer is a react component but loses state on viewport scroll.

### ISSUE THREAD

**Issue by chrismiceli** [adazzle/react-data-grid#551]
**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[ ] v15.0.x
```
```
Other:
[x] v15.3.2
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[x] IE 9 / IE 10 / IE 11
[x] Edge
[x] Chrome
```

```
Should work:
[x] Firefox
[x] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
rowRenderer can be a react component, but state is lost when the rowRenderer is scrolled out of view.

**Expected/desired behavior**
As a component, I expect my state to remain on scroll, even if I am virtualized.

**Reproduction of the problem**
Here is an example that logs the state of the first row every render. Each row also has a button that changes the state. If you click the button, then scroll around for the first row, you can see the state is lost.

```javascript
var _rows = [];
for (var i = 1; i < 1000; i++) {
  _rows.push({id: i, task: 'Task ' + i});
};

//function to retrieve a row for a given index
var rowGetter = function(i){
  return _rows[i];
};

//Columns definition
var columns = [
{key: 'id', name: 'ID'},
{key: 'task', name: 'Title'}
]

var RowRenderer = React.createClass({
 getInitialState: function() {
   return {logState: false};
 },
  
 render: function() {
   if (this.props.idx === 0) {
     console.log(JSON.stringify(this.state));
     }
   return (<div><button onClick={() => {this.setState({logState: true}); }}>Hi</button><ReactDataGrid.Row ref="row" {...this.props}/></div>)
 }
});

var Example = React.createClass({
  render: function() {
    return  (<ReactDataGrid
    columns={columns}
    rowGetter={rowGetter}
    rowsCount={_rows.length}
    rowRenderer={RowRenderer}/>);
  }
});
ReactDOM.render(<Example />, mountNode);
```

**What is the expected behavior?**
I expect the state of my component to not go away on scroll. I understand why this is happening, but it was unexpected as a react component. This should probably just be a functional stateless component only since state is not supported correctly. 

**What is the motivation / use case for changing the behavior?**
The motivation is to make the data grid component intuitive and predictable.

**Comment by malonecj** [comment]
The behavior is correct. The component becomes unmounted when it is virtualized, and so does not maintain state. Only the rows that remain in the viewport (viewable and non viewable) maintain their state.

**Comment by chrismiceli** [comment]
I understand it is by design and correct behavior. However, it is not obvious based on the documentation. The consumer of the data-grid believe a component is a valid input as a rowRenderer, but in actually, only the stateless variety of components is supported. Should we update the documentation to be more clear on this matter?
