### ISSUE TITLE
Setting focus on the first row/cell

### ISSUE THREAD

**Issue by GenoD** [adazzle/react-data-grid#552]
**WHICH VERSION OF REACT ARE YOU USING?**
```
Community Supported:
[ x ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[ x ] Chrome
```

```
Should work:
[ x ] Firefox
[ x ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**

**Expected/desired behavior**
I am trying to move from an inputField to the first cell/row of the datagrid on tab keypress.

**Reproduction of the problem**

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**
Typing in the prior inputField will cause matching rows to be presented on grid. Tabbing into the table will allow them to directly select which item they wish to choose.

My users will primarily be using the number pad and arrows (no mouse). So I would like to focus in on the table after the inputField as to avoid navigation via mouse.

**Comment by diogofcunha** [comment]
Hi @GenoD.

I think that shouldn't be the grid responsibility as it is a specific use case.

The best think for you to do in this case is to add a `onKeyDown` or `onBlur` event to your input field, after that you can find the first cell in the dom and force the focus in that node.
