### ISSUE TITLE
SelectAll checkbox selects data in wrong grid

### ISSUE THREAD

**Issue by GenoD** [adazzle/react-data-grid#554]
**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[ X ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[ X ] Chrome
```

```
Should work:
[ X ] Firefox
[ X ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
Clicking on edge (or accidentally miss clicking) of SelectAll checkbox causes the wrong grid to be updated.

**Expected/desired behavior**
SelectAll checkbox should only affect respective table.

**Reproduction of the problem**
![bug](https://cloud.githubusercontent.com/assets/5068500/20910776/87d6b74c-bb18-11e6-89ca-ebd6b36df6b2.gif)

**Comment by G710** [comment]
I have also experienced this bug. I'm currently using ```react-data-grid v1.0.55```.

**Comment by nunoleong** [comment]
We are also experiencing this exact issue. Using `react-data-grid v1.0.54`

**Comment by Nikhdy** [comment]
could className props be added and appended to all the className of the inner elements will this sort the issue?

**Comment by koustubhmoharir** [comment]
I reported the same issue in #643 

The issue is that the check box has a hard coded id of 'select-all-checkbox' and there is a label which uses the same id. Clicking on this label triggers the first occurrence of the checkbox which may be in a different grid.

**Comment by TommiHo** [comment]
Datagrid seems to use "Select all" checkbox's class to identify it's pressed. You have to change checkbox's classname manually like this: 

1. Refer to grid like this: 
```
        <ReactDataGrid
          ref={grid => {
            this.grid = grid;
          }}
```
2. change checkbox id: 
 ```
 render() {
    if (this.grid) this.grid.selectAllCheckbox.className = "checkbox-classname";
```

Then you have to create the styles for the new class of course. I know this approach isn't the best but atleast it works.
