### ISSUE TITLE
Filter text box loses focus while user is typing

### ISSUE THREAD

**Issue by supamanda** [adazzle/react-data-grid#556]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x 
```

```
Community Supported:
[x ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[x ] Chrome
```

```
Should work:
[x ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
Filter text box loses focus while user is typing

**Expected/desired behavior**
Filter text box keeps focus while user is typing

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.

Go to the filterable example http://adazzle.github.io/react-data-grid/examples.html#/filterable-grid
Click on the Filter Rows button
Click on the filter box for the title column, and start typing

**What is the expected behavior?**
Expected: I can type as much as I want in the filter box
Actual: focus moves to the first cell in the table

**What is the motivation / use case for changing the behavior?**

**Comment by malonecj** [comment]
hi @supamanda. Which version are you using? I think this should be fixed with this PR
https://github.com/adazzle/react-data-grid/pull/549

**Comment by supamanda** [comment]
hi @malonecj, I'm looking at the latest version 1.0.71, and it still has this issue.
