### ISSUE TITLE
Upgrade to React 15

### ISSUE THREAD

**Issue by diogofcunha** [adazzle/react-data-grid#558]
The long waited React 15 update is coming soon. It will be part of grid 2.0 release and will be carried out after the multiple package implementation ([Issue](https://github.com/adazzle/react-data-grid/issues/557), [PR](https://github.com/adazzle/react-data-grid/pull/541))

**Comment by tranquilize** [comment]
Firstly, thank you all for the updates and effort.

Secondly, do you have an idea of the changes we'll have to make as we update to react-data-grid 2.0?

**Comment by diogofcunha** [comment]
Hi @tranquilize.

With the update we will create some release notes with key aspects for a smooth update.

**Comment by robogroves** [comment]
Great Job!  Thank you for updating to React 15 and for a professional quality data grid.  Please consider working on data grouping function called for each row in a group. An example can be found @ http://reactjsexample.com/react-pivot-data-grid-component-with-pivot-table-like-functionality-for-data-display/.  This will provide a way to count or sum all the records in a group.  Thanks you again for your commitment to a great data grid for react.  -Brent  Groves - brent.groves@gmail.com

**Comment by gmjw** [comment]
Hi there,

Thank you very much for your work on updating react-data-grid to work with React 15. The react-data-grid seems like a great library and I know loads of people will appreciate having it available in React 15.

I'm really keen to try out this 2.0 React 15 branch, so I have tried installing it by adding

`    "react-data-grid": "git+https://github.com/adazzle/react-data-grid.git#bd55afa",`

to my package.json. I then deleted the `node_modules/` directory, ran `npm install` again, and restarted my app, but I'm finding I get the following error message:

> Failed to compile.
> 
> Error in ./~/react-data-grid/index.js
> Module not found: ./dist/react-data-grid in /home/gareth/Code/ReactProjects/data-grid-test/node_modules/react-data-grid
> 
>  @ ./~/react-data-grid/index.js 1:17-50

And indeed there is no `dist/` directory at all in `node_modules/react-data-grid/`. I'm wondering if there is something simple I'm doing wrong here? Do I need to run some script to create this `dist/` directory and the files that should be there?

Many thanks,

Gareth Williams

**Comment by jpdriver** [comment]
hey @gmjw -- unfortunately we're not quite ready for people to start trying V2 yet. it's still very early in development and currently contains breaking changes, so you'll need to wait a bit longer! sorry about that..

ps. you'll never have the built `dist` folder if you reference a specific commit as we don't include it in our source 🙂

**Comment by gmjw** [comment]
Hi @jpdriver,
Thanks for your reply - ah I see, that makes sense now. Ok, no problem to wait a bit longer! Good luck with the changes and I look forward to trying out the updated version sometime (I would offer to help but to be honest I am very new to React/npm!)

**Comment by emorling** [comment]
@diogofcunha can you please define "coming soon" :) It's 26 days ago now

**Comment by jsbranco** [comment]
@diogofcunha would it be possible to share the current status and what is the expected timeline for this change?

**Comment by diogofcunha** [comment]
We are exited to announce that react-data-grid 2.0 will be launched with react 15 :1st_place_medal:

**Comment by jsbranco** [comment]
That is great @diogofcunha!! :) what is the expected timeline ?
