### ISSUE TITLE
Default outline border not 100% correct on Chrome/OS X

### ISSUE THREAD

**Issue by jonaswindey** [adazzle/react-data-grid#559]
**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[x] v0.14.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[x] Chrome (OS X)
```

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**

Default outline (blue border) is partially masked on the demo site.

<img width="1106" alt="screen shot 2016-12-08 at 13 23 44" src="https://cloud.githubusercontent.com/assets/3637300/21009954/ade87d98-bd49-11e6-93d6-f8f83fd8aa36.png">

**Expected/desired behavior**

The border of the current cell should be equal around the whole cell.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.

Just visit http://adazzle.github.io/react-data-grid/examples.html#/basic and click on a cell on latest Chrome on OS X El Capitan

**What is the motivation / use case for changing the behavior?**

Better default styling.

It can be fixed by customizing the css, but it should be correct out of the box.

**Comment by tedjames** [comment]
I'm having an issue similar to this right now. Currently, none of the borders anywhere in the grid are visible with the exception of the selected cells' left, top, and bottom borders.

<img width="1464" alt="screenshot at jan 27 18-52-00" src="https://cloud.githubusercontent.com/assets/13091675/22391850/b9fdeeca-e4c1-11e6-96ae-0916bac25bf0.png">
