### ISSUE TITLE
Fixed cols example broken

### ISSUE THREAD

**Issue by jonaswindey** [adazzle/react-data-grid#560]
```
Officially Supported:
[x] v0.14.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[x] Chrome
```

```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**

The current fixed column on http://adazzle.github.io/react-data-grid/examples.html#/fixed-cols is broken. See screenshot:

<img width="486" alt="screen shot 2016-12-08 at 16 35 50" src="https://cloud.githubusercontent.com/assets/3637300/21016092/a660a468-bd64-11e6-8775-84886c1eb463.png">

**Expected/desired behavior**

The whole column should be fixed and not only the header row.

**Reproduction of the problem**

Visit http://adazzle.github.io/react-data-grid/examples.html#/fixed-cols

**Comment by jpdriver** [comment]
hey @jonaswindey -- this is a known issue and will be fixed in the next major version release of the grid (v2) that we are currently working on 🙂

**Comment by jonaswindey** [comment]
Ok thanks. Any ETA or branch I can currently use? I'm investigating this component for a future project on short term.

**Comment by malonecj** [comment]
fixed by https://github.com/adazzle/react-data-grid/pull/570
