### ISSUE TITLE
Pagination is missing this grid. How can I get pagination?

### ISSUE THREAD

**Issue by KalpanaPagariya** [adazzle/react-data-grid#562]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[ ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[ ] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Comment by malonecj** [comment]
There are no current plans to add pagination to grid. This is something that could be added to the addons package. We will accept a PR and would be happy to help if you would like to try build one

**Comment by robin-chilliapple** [comment]
Is pagination supported right now...

**Comment by jcarva** [comment]
Looking to this feature.

**Comment by bostondevin** [comment]
+1

**Comment by NourEldin275** [comment]
+1

**Comment by alexeymakarov90** [comment]
+1

**Comment by qili26** [comment]
@alexeymakarov90 
can I ask why do you want a pagination for the grid since the grid can support large number render + filter?

And a possible way to do that is like this (just a concept).

```
const RDGWrapper = (rows) => {
   const rows = getFilteredRowsByPagination(props.rows);
   const rowGetter = (i) => rows[i];

   return (
     <div>
         <RDG rowGetter-{rowGetter} />
         <Pagination />
     </div>
   );
};
```
