### ISSUE TITLE
Adding filter to column with blank entries causes error

### ISSUE THREAD

**Issue by GenoD** [adazzle/react-data-grid#565]
**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[ X ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[ X ] Chrome
```

```
Should work:
[ X ] Firefox
[ X ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
Adding a filter to a column in which some rows have no value will cause an the error:
"Cannot read property 'toString' of null"

**Expected/desired behavior**

**Reproduction of the problem**
Attempt add filter in a column that contains blanks.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Comment by diegomurakami** [comment]
Hi @GenoD,

Please, send your code here so we can help you.

Cheers~

**Comment by GenoD** [comment]
@diegomurakami 

I traced the error to RowFilterer.js but it seems that it was fixed in a future update.
