### ISSUE TITLE
Make Cell.getStyle modifiable by props

### ISSUE THREAD

**Issue by Kovak** [adazzle/react-data-grid#566]
**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[X ] v0.14.x
```

```
Community Supported:
[ ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[X ] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
It seems like right now the style dict for Cell is hardcoded here: https://github.com/adazzle/react-data-grid/blob/master/src/Cell.js#L142

**Expected/desired behavior**
It would be nice to be able to pass in some function like 
```jsx
render: function() {
        return <ReactDataGrid.Cell getStyle={this.getStyle} {...this.props}/>;
    },
```

**What is the motivation / use case for changing the behavior?**

The column formatter does not appear to allow you to accomplish a change such as setting the background color for an entire cell as the div it operates on is a child of the cell div. Using a RowRenderer it does not appear possible to do this without wholesale replacing the existing Cell component. It would be nice to be able to provide custom styling to the Cell. If this is possible in some way I have missed, please let me know.

**Comment by anil1712** [comment]
Yeah great suggestion. I also needed this. 
Is there any progress for the same?
Thanks,
