### ISSUE TITLE
Cannot build without typescript?

### ISSUE THREAD

**Issue by amithmathew** [adazzle/react-data-grid#571]
**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[x] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[x] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
Webpack build breaking when installing module from github. The stack trace shows lines where what appear like typescript definitions are mixed in.
Example : Line 77 of src/Cell.js

This works fine when installing the latest build on npm. 

I am new to the whole thing, so I could be completely off-base. If so, would appreciate any help that can be given.

**Expected/desired behavior**
Should be able to include and webpack build should run successfully.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**
Should be able to build without typescript.

**What is the motivation / use case for changing the behavior?**

**Comment by amithmathew** [comment]
Closing this. The errors were due to misunderstanding on so many levels :)

Would appreciate some information on how to build the latest version of react-data-grid from github for production use, rather than download from npm. There are too many bug fixes on here that I need.

**Comment by jpdriver** [comment]
hey @amithmathew -- we publish to NPM automatically as soon as things are merged in to `master`, so running `npm install react-data-grid` is always our recommendation.

if you need access to the built files (which are not included in our source):-

1. clone the repository
2. run `npm install` inside of it
3. run `gulp` from the root

this will build the project into a `dist` folder and bring up the examples in your browser. you can then grab the output .js files from that directory.

ps. you may also need the .css file in the `themes` directory if it looks like you're missing styles.

**Comment by amithmathew** [comment]
Thank you jpdriver, much appreciated!
