### ISSUE TITLE
Receiving sortDirection property warning when using ReactDataGrid

### ISSUE THREAD

**Issue by aschonfeld** [adazzle/react-data-grid#573]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[x] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[x] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
I am consistently getting the warning: "Warning: Invalid argument supplied to oneOf, expected an instance of array." when using the ReactDataGrid component. It appears that the <HeaderRow> component is expecting a value for sortDirection of either ASC, DESC or NONE.  Unfortunately the getInitialState() function of ReactDataGrid is setting this property to null.

**Expected/desired behavior**
No warnings

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

So I don't have this warning clogging up my browser console.

**Comment by diogofcunha** [comment]
Same as https://github.com/adazzle/react-data-grid/issues/597, closing this one
