### ISSUE TITLE
Dropdown menu is not getting shown in cell due to overflow hidden property.

### ISSUE THREAD

**Issue by anil1712** [adazzle/react-data-grid#574]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**
Yes
> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**
Hi, 

I am trying to add to Drodown menu from [Semantic UI](http://react.semantic-ui.com/modules/dropdown) by using the [Custom Formatter](http://adazzle.github.io/react-data-grid/examples.html#/custom-formatters) but its not getting show properly because cell is having `overflow: hidden` property. So anyone help me to get out of it and provide some suggestion or solution to achieve this.

Here is my sample code
```
//Columns definition
var columns = [
{
  key: 'menu',
  name: 'Menu',
  formatter: {
    <Dropdown trigger={<span>Row Menu</span>} pointing='top left'>
            <Dropdown.Menu>
                <Dropdown.Item text='Account' icon='user' />
                    <Dropdown.Item text='Edit' icon='edit' />
                    <Dropdown.Item text='Delete' icon='delete' />
             </Dropdown.Menu>
      </Dropdown>
  }
},
```

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[x] v0.14.x
```

```
Community Supported:
[ x] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[ x] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
Dropdown menu get hidden

**Expected/desired behavior**
It should appear as menu with options

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**
![row-menu](https://cloud.githubusercontent.com/assets/4207865/21341624/6f65ab36-c6b3-11e6-81db-a12d7159ed7d.png)

**What is the motivation / use case for changing the behavior?**
By using this we can provide some of the row actions in menu eg: Edit, Delete.

**Comment by diogofcunha** [comment]
Hi @anil1712. A formatter is supposed to act as way of showing data.

What you are trying to do is not supported on our formatter use cases. It is supported in our **context menu** that is triggered when you right click a row, you can have a look at the context menu [at this example](http://adazzle.github.io/react-data-grid/examples.html#/context-menu).

**Comment by anil1712** [comment]
ok, but is there any way to achieve this by using any CSS propery in cell?
