### ISSUE TITLE
DatePicker as Cell Editor on ReactDataGrid

### ISSUE THREAD

**Issue by soma83** [adazzle/react-data-grid#583]
Hello @diogofcunha, 
In [389](https://github.com/adazzle/react-data-grid/issues/389) you said: 

> Don't forget to implement getInputNode and getValue.
getInputNode will be used for the editor to know where he needs to focus when edit mode is enabled. getValue will be the function that gets the editor value before commit.

The thing is, I have no idea how to implement those functions in order to get the DatePicker component working as a React Data Grid cell editor. Please, can you share a link with documentation or a working example?

**Comment by michaeljacobdavis** [comment]
@soma83 I might be able to help on this. Here are the default implementations of [`getValue`](https://github.com/adazzle/react-data-grid/blob/master/src/addons/editors/EditorBase.js#L13-L17) and [`getInputNode`](https://github.com/adazzle/react-data-grid/blob/master/src/addons/editors/EditorBase.js#L19-L26).

`getValue` needs to be able to return the current value of the editor when called, so you can hook it up to the DatePicker if it has a callback prop like that, or you can store the value from the DatePickers `onChange` in state and just return state in `getValue`. Note the return format needs to be:
```
{
  [columnid]: value
}
``` 

`getInputNode` should return a dom element that receives focus when the editor is rendered. Not sure which DatePicker you're using but they might expose the input via `refs` or a callback.


Checkout the [`DateRangeEditor`](https://github.com/adazzle/react-data-grid/blob/master/src/addons/editors/DateRangeEditor.js#L31-L43) for an example of overriding them.

**Comment by diogofcunha** [comment]
@michaeljacobdavis thanks for the reply, you are correct.
