### ISSUE TITLE
React 15 advice

### ISSUE THREAD

**Issue by emorling** [adazzle/react-data-grid#585]
I am stuck and need advice. I need the grid working with react 15 and plugins. 

However, 
1) the plugins don't work with react15
2) I can't get a custom editor to work 

Does anyone have input on: 
1) when will the grid be working with react15?
2) has anyone managed to write a custom plugin with react15?

Thanks

**Comment by malonecj** [comment]
We are scheduling React 15 for early this year. We dont have any further update right now
