### ISSUE TITLE
Check for existing drag and drop context before creating

### ISSUE THREAD

**Issue by michaeljacobdavis** [adazzle/react-data-grid#588]
@malonecj it looks like https://github.com/adazzle/react-data-grid/pull/467 got merged but then reverted (https://github.com/adazzle/react-data-grid/pull/555) because of issues with `react-contextmenu`. 

This is still an issue for me, so I'd be happy to look into the issue if you tell me how to reproduce it.

**Comment by malonecj** [comment]
Yeah sorry, I had to revert this as it was causing some production issues for us here. As I recall, the original PR kept recreating a new React DnD context whenever the context menu was triggered via right click. A script error was then generated saying that only one DnD context may be present in the application

**Comment by michaeljacobdavis** [comment]
Got it. Are you using the built in context menu and do they have DND inside of them? I'll check it out and see if I can re-create it.

**Comment by amanmahajan7** [comment]
FYI: this issue should be resolved in v4. Here is the fix that was merged to the [_next_](https://github.com/adazzle/react-data-grid/pull/1116/commits/305367b52467d6871207f9fc2bfa5ce94e069c75) branch
