### ISSUE TITLE
getCellValue (row.get) conflicts with other libraries.

### ISSUE THREAD

**Issue by samchon** [adazzle/react-data-grid#589]
## Row.js -> getCellValue(key)
https://github.com/adazzle/react-data-grid/blob/7f51b6f9a1a1a6292b46f907ffa603bff6b7b45b/src/Row.js#L138-L139

```javascript
getCellValue(key) {
  let val;
  if (key === 'select-row') {
    return this.props.isSelected;
 } else if (typeof this.props.row.get === 'function') {
    val = this.props.row.get(key);
  } else {
    val = this.props.row[key];
  }
  return val;
}
```

The dynamic access (`val = this.props.row.get(key);`) on `Row.getCellValue` makes confliction with other libraries (Most ollection libraries have their own `get` function, that is not designed for the `react-data-grid` wants).

Accessing to the `get` function, it even causes a confliction when user makes a custom class that has a `get` function. I think it would better to erase the `get` statement such below. The `get` function can be substituted to the property getter.

```javascript
getCellValue(key) {
    let val;
    if (key === 'select-row') {
        return this.props.isSelected;
    } else {
        val = this.props.row[key];
    }
    return val;
}

class Wanted {
    constructor() {
        this._name = "John Doe";
        this._level = 3;
        this._reward = 10000;
    }

    get name() {
        return this._level + ". " + this.name;
    }
    get reward() {
        return "$" + StringUtil.numberFormat(this._reward);
    }
}
```

**Comment by malonecj** [comment]
Yes, good point. This was a poor hack for use with Immutable JS library. Instead of checking for presence of get function, we should have a check to see if the object is an Immutable JS type
