### ISSUE TITLE
selectable row input cell with custom width 

### ISSUE THREAD

**Issue by lingfa** [adazzle/react-data-grid#605]
**WHICH VERSION OF REACT ARE YOU USING?**

react-data-grid@1.0.81

**WHICH BROWSER ARE YOU USING?**

[x] Chrome

--------

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
enableRowSelect='multi'
create a column of 60px width by default with checkboxes

**Expected/desired behavior**
I want to set a custom with for the select-column

**What is the motivation / use case for changing the behavior?**

Adjust the grid to the given  Graphic Design

**Comment by diogofcunha** [comment]
Hi @lingfa.

That is not supported right now as you can check [in here](https://github.com/adazzle/react-data-grid/blob/master/src/ReactDataGrid.js#L832).

Will accept a PR, that should go in the cell selection props.

Cheers.
