### ISSUE TITLE
header cell formatter

### ISSUE THREAD

**Issue by jlarso11** [adazzle/react-data-grid#607]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[X] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[X] Chrome
```

```
Should work:
[X ] Firefox
[X] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**

**Expected/desired behavior**
Is there a way to custom format a header cell?  I found the way to do different cells, but I also am in need of customizing the headers beyond the text. 

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Comment by diogofcunha** [comment]
Hi @jlarso11.

You can specify an 'headerRenderer' to each one of your columns, as we do [in here](https://github.com/adazzle/react-data-grid/blob/master/src/ReactDataGrid.js#L840) for row selection.

Cheers.

**Comment by sjain-mi9** [comment]
@diogofcunha , not sure if I'm using it wrong, but when I pass prop, headerRenderer does not work, but when I pass it to formatter the same way, it does read and behave. Is there a probable solution for rendering header?
