### ISSUE TITLE
Merge cells 

### ISSUE THREAD

**Issue by Mavrin** [adazzle/react-data-grid#619]
**I'm submitting a ...**  (check one with "x")

- [ ]  bug report
- [x] feature request
- [ ]  support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

**Current behavior**
It is not possible specify colspan and rowspan for certain row and cell
**Expected/desired behavior**
Data grid have some api which allow set colspan and rowspan like native html table

**What is the motivation / use case for changing the behavior?**
Sometimes I need merge few cells

**Comment by diogofcunha** [comment]
Hi @Mavrin.

Looks like a nice to have, although it is not on our rode map right now.

We will accept a PR.

Cheers.

**Comment by Mavrin** [comment]
@diogofcunha thank you for response.
As I understand it is not easy implement and it will increase complexity calculation of size and can affect performance.
In my case i don't need draw big table with many column and row. I decided use native html table.

**Comment by ks549** [comment]
Hi @diogofcunha  - I am looking for Rowspan feature in react-data-grid library. Is there a way to handle it?
