### ISSUE TITLE
Examples broken in IE9

### ISSUE THREAD

**Issue by epeterson320** [adazzle/react-data-grid#631]
**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[ ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[X] IE 9 / IE 10 / IE 11
[ ] Edge
[ ] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
The examples page does not load when viewed with IE9.

**Expected/desired behavior**
When I visit http://adazzle.github.io/react-data-grid/examples.html#/all-features in IE9, a web page should load and be interactive

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.

Open the page in IE9. Open the F12 Developer Tools. The console displays an invalid syntax error in scriptDelegator.js. This is due to the use of es6 syntax.

**What is the expected behavior?**
The web page should load, and the public web page should use es5 syntax only.

**What is the motivation / use case for changing the behavior?**
It should be easy for people considering this library to test-drive it in IE9.

**Comment by vijayrajaram** [comment]
Examples doesn't seem to work in any browser. Tried Chrome 44.0.2403 and IE 11.9.9600. Does it work in any other browser? 

Other than installation steps at http://adazzle.github.io/react-data-grid/ there is no where I could see how this grid could be used :(
