### ISSUE TITLE
"headerRenderer" breaks the grid under IE

### ISSUE THREAD

**Issue by tekacharova** [adazzle/react-data-grid#637]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[x] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[x] IE 9 / IE 10 / IE 11
[ ] Edge
[ ] Chrome
```

```
Should work:
[x] IE 9 / IE 10 / IE 11
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
When using "headerRenderer" it breaks the data grid only for IE.
This is the error that it throws: 
![image](https://cloud.githubusercontent.com/assets/12809731/22458488/6b00aec0-e7a5-11e6-8360-ddc601ad69e6.png)
"Unhandled promise rejection Invariant Violation: React DOM tree root should always have a node reference."

**Expected/desired behavior**
The "headerRenderer" is working fine under Chrome. 

**Reproduction of the problem**
I want to render a custom header using the "headerRender". This breaks under IE and the grid is not showing. This is the error that I get: "Unhandled promise rejection Invariant Violation: React DOM tree root should always have a node reference."
```
`if(item.Description || item.Name) {
                  var title = item.Name;
                  var description = item.Description;
                  model.headerRenderer =
                  <div className="customHeader">
                    <a data-tip id="tooltip" data-for="tooltip">{model.name}</a>
                  </div>
                }`
```

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**
I need this issue to be fixed in order to creat a tooltip for the header cells.

**Comment by domehead100** [comment]
Why are you using string interpolation?  Shouldn't you surround your JSX expression in parens?

**Comment by tekacharova** [comment]
@domehead100 Thanks for the help. Yes, it was our mistake and we have fixed it now.
