### ISSUE TITLE
Access nested object properties without custom formatter

### ISSUE THREAD

**Issue by mknabe** [adazzle/react-data-grid#644]
**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[x] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[x] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
Trying to display data for a nested object doesn't work without a custom formatter
```
{
  name: 'Customer',  
  key: 'customer.name'
}
```

**Expected/desired behavior**
I would like to be able to access nested object properties using the above syntax or possibly with a function like below. Is this already possible somehow?

```
{
  name: 'Customer',
  key: 'customer',
  accessor: (row) => row.name
}
```

**What is the motivation / use case for changing the behavior?**
Limits the number of custom formatters needed

**Comment by moiz-emx** [comment]
👍

**Comment by moizhb** [comment]
👍

**Comment by mi-lee** [comment]
Please implement this!

**Comment by jean343** [comment]
I found a work around if you are interested.

In Row.js, they are calling row.get(key) as follow
``` JavaScript
  getCellValue(key) {
    let val;
    if (key === 'select-row') {
      return this.props.isSelected;
    } else if (typeof this.props.row.get === 'function') {
      val = this.props.row.get(key);
    } else {
      val = this.props.row[key];
    }
    return val;
  }
```

I changed my `rowGetter` to implement get. I used eval to allow key of th type: `array[0].key.name`
```JavaScript
  rowGetter(index) {
    let contract = this.props.contracts[index];
    contract.get = key => eval('contract.' + key)
    return contract;
  }
```

**Comment by philipbulley** [comment]
Out of interest, how would this be achieved when using custom formatters? Wouldn't the fact that multiple columns can't have the same key prevent this? Each key would be the name of the same parent object, right?

**Comment by moizhb** [comment]
@philipbulley Key does not necessarily have to be first level key of the object. Dot notated full path could be used as key to differentiate two columns. So in above example the key would be 'customer.name'.

**Comment by philipbulley** [comment]
@moizhb but the formatter is passed an empty string value when I use this example:

```js
{
  name: 'Customer',  
  key: 'customer.name'
}
``` 

💡  However, I've just found out that I can do:

```js
{
	name: 'Customer', 
	key: 'customer.name',
	getRowMetaData: row => row.customer.name,
}
```

...then consume the customer name as a prop named `dependentValue` in the custom formatter. Which is a little odd, but it works 👍

**Comment by jcarva** [comment]
@jean343 , you just fucking saved me hours, I also have updated my `rowGetter` function and it works very well.
```javascript
{
  name: 'Customer',  
  key: 'customer.name'
}
```
I'm just checking if the `key` has a dot.
```javascript
  rowGetter = (rowIdx) => {
    let rows =  this.getRows();
    let project = Object.assign({}, rows[rowIdx]);

    project.get = key => {
      let splitedkey = key.split(".");

      if(key.includes('.')) {
        return project[splitedkey[0]] ? project[splitedkey[0]][splitedkey[1]] : ""
      }  else {
        return project[key]
      }
    };

    return project;
  };
```
`Note:` I'm always using the **get** function

**Comment by jean343** [comment]
I am glad it helped!

About the 'dot', I like that your solution does not use `eval` however it is limited at a specific pattern.
I would suggest something found from https://stackoverflow.com/questions/6393943/convert-javascript-string-in-dot-notation-into-an-object-reference

```javascript
'a.b.etc'.split('.').reduce((o,i)=>o[i], obj)
```

**Comment by jcarva** [comment]
I'm really thankful for your tip, I have changed my function to use the **`reduce`** function as you mentioned to get any pattern, so now I got a clean and generic code.

**Comment by nzhtrtlc** [comment]
@jean343  @jcarva  good solution BUT it does not work on filtering. I don't understand why they just don't support nested object properties. They have really cool features but its really hard to combine them all. Also there is no DOCUMENTATION! i don't know what props can my columns can take.

**Comment by DrogoNevets** [comment]
An update on this issue, below is the code I used (modified from above) to allow multiple level of nesting if needed (it works it out)

feel free to optimise and post back - this is just the first pass at it

```javascript
document.get = (key) => {
      let splittedKey = key.split(".");

      if(document && key.includes('.')) {
        let current = document;

        splittedKey.forEach((splitKey) => {
          if(current) {
            current = current[splitKey];
          }
        });

        return current;
      } else {
        return document[key]
      }
    };
```

**Comment by Ben-CA** [comment]
Any current recommendations for doing this by now with react-data-grid?
