### ISSUE TITLE
Autocomplete editor returns title value

### ISSUE THREAD

**Issue by gauravagam** [adazzle/react-data-grid#654]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[ x] v15.4.2
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[ x] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
Autocomplete editor returns title value instead of id

**Expected/desired behavior**
Autocomplete editor should return id value but display value should be title value

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Comment by pie6k** [comment]
I've got exactly the same idea. 

I want user to pick some user basing on their login, but I want ID of this user to be returned as row data so I can save it into database.

**Comment by pie6k** [comment]
@malonecj why is it closed?

**Comment by lepsistemas** [comment]
Hey @pie6k 

Got this working already? Still struggling on it.
