### ISSUE TITLE
Can't disable cell select - enableCellSelect={false} doesn't work

### ISSUE THREAD

**Issue by localhosted** [adazzle/react-data-grid#655]
**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[x] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[x] Chrome
```

```
Should work:
[x ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
Setting `enableCellSelect={false}` doesn't prevent cell selection and navigation

**Expected/desired behavior**
Setting `enableCellSelect={false}` prevents cell selection and navigation

**Reproduction of the problem**
https://codepen.io/anon/pen/rjQdwz?editors=0010

**Comment by localhosted** [comment]
Just noticed that the selection is CSS only. Just need to override the default style:

    .react-grid-Cell:focus {
       outline: none;
    }

**Comment by maxrchung** [comment]
> ```
> .react-grid-Cell:focus {
>    outline: none;
> }
> ```

This does not work/no longer works for me. I was able to remove the selection border in my stylesheet by overriding this:

```css
.rdg-selected {
    border: none !important;
}
```

**Comment by lostintheway** [comment]
is there any solution for this, I want to make some columns selectable and some not

**Comment by jmenast** [comment]
I solved it but old school, eventually when you have more than one instance, it will hide the selector only from the first one ... greetings!

```js
      onCellSelected={(({idx}: any) => {
        const firstColumn = idx === (columns.length - 1)
        // Toggle opacity on `rdg-selected`
        document.getElementsByClassName('rdg-selected')[0].style.opacity = firstColumn ? 0 : 1
      })}
```

**Comment by colinscruggs** [comment]
> Is there still no fix to this?

Here's my solution, just a simple CSS override:
```
.rdg-cell-selected {
    /* disable selection border color */
    box-shadow: none !important;
}
```

Note: this is on version 7.0.0-canary.18

**Comment by otaviobps** [comment]
For the latest version is

```
.rdg-cell[aria-selected='true'] {
  box-shadow: none;
}
```

**Comment by ivan-palatov** [comment]
For the beta-12
```css
.rdg-cell[aria-selected='true'] {
  box-shadow: none;
}
```

**Comment by ivan-palatov** [comment]
Also, I'd REALLY like to be able to turn that off, since it behaves HORRIBLY with colSpans (table scrolls to the middle horizontaly), and it has a critical bug in the latest version with colSpan, when you try to click on it, which just wasted 4 hours of my life trying to fix it with no success.

**Comment by sergioengineer** [comment]
You can disable it by creating a Row custom row renderer and overriding the selectedCellIdx to undefined.
You pass this prop to the Grid component:
`components={{ rowRenderer: GridRow }}`

and then you create the GridRow component:
`
const GridRow: React.FC<RowRendererProps<unknown>> = ({ ...props }) => {
  return <Row {...props} selectedCellIdx={undefined} />;
};
`

You'll also need to import the types for this:
`import { Row, RowRendererProps } from "react-data-grid";`

**Comment by AykutSarac** [comment]
> You can disable it by creating a custom row renderer and overriding the selectedCellIdx to undefined. You pass this prop to the Grid component: `components={{ rowRenderer: GridRow }}`
> 
> and then you create the GridRow component: `const GridRow: React.FC<RowRendererProps<unknown>> = ({ ...props }) => { return <Row {...props} selectedCellIdx={undefined} />; };`
> 
> You'll also need to import the types for this: `import { Row, RowRendererProps } from "react-data-grid";`

Thanks for sharing, I was exactly looking for this.

**Comment by sergioengineer** [comment]
Np. I had just figured this out during the morning and thought it was a good idea to answer this issue in case anyone else ran into the same problem as me.

**Comment by neovirtual** [comment]
This worked for me in version 6.2.1. It's an update on sergioengineer answer. 

                    <DataGrid
                        renderers={{
                            rowRenderer: (key: Key, props: RowRendererProps<any>) =>
                                <Row key={key} {...props}
                                    selectedCellIdx={undefined} />
                        }}
