### ISSUE TITLE
ReactDataGrid width not respecting container padding

### ISSUE THREAD

**Issue by ZephD** [adazzle/react-data-grid#657]
I have a bootstrap Grid -> Row -> Col, with my ReactDataGrid inside.

The ReactDataGrid is larger than the column width by the sum of the padding on the sides.

Calls to .updateMetrics() do not fix the issue.

Probably due to using `box-sizing: border-box` in the css.

Here you can see the grid overflowing it's container:
![screenshot from 2017-02-14 15-59-07](https://cloud.githubusercontent.com/assets/1461917/22936834/94ceb286-f2ce-11e6-93d3-cc958b8f5063.png)

Here is the container (bootstrap col). Notice the overflow is the sum of the side padding (green)
![screenshot from 2017-02-14 15-58-51](https://cloud.githubusercontent.com/assets/1461917/22936876/b1c14f70-f2ce-11e6-9dc8-c9b2baccede4.png)

**Comment by ZephD** [comment]
Workaround: Wrap the ReactDataGrid in a <div>
(the new div does not have padding, but fills the bootstrap column)

**Comment by vijayrajaram** [comment]
Wrapping ReactDataGrid inside another grid doesn't seem to help 

`      <div className="row">
        <div className="col-md-12">
          <i className="fa fa-refresh fa-lg pull-right pointer mr-1 mb-1" title="Refresh"/>
        </div>

        <div className="col-md-12">
          <div>
            <ReactDataGrid
              columns={columns}
              rowGetter={rowGetter}
              rowsCount={rows.length}
              minHeight={375}/>
          </div>
        </div>
      </div>`

**Comment by jsobus-neurosys** [comment]
Addition div gives no results, calling updateMetrics() after some time (not 0) makes grid to stay inside container. But then we got flickering effect because grid is resizing itself during init.

**Comment by lavor** [comment]
@jsobus-neurosys Try to wrap grid in absolute positioned full-width div, see: https://github.com/adazzle/react-data-grid/issues/295#issuecomment-332212132

**Comment by jsobus-neurosys** [comment]
@lavor Good idea but in my case still the same. Calculation is done wrong for the first time, and need to resize widow to make it look well. My view is complex one with many dynamic items which makes me calling updateMetrics very often because grid itself is not updating its layout.

**Comment by jsobus-neurosys** [comment]
I found something, all sizing is ok now, problem was then the main container got its own scroll. I mean this scroll appears dynamically after grid is loaded. Problem was that scroll showing/hidding is not calling resize event. The fix for this can be done using that sham: https://gist.github.com/AdamMcCormick/d5f718d2e9569acdf7def25e8266bb2a
