### ISSUE TITLE
Show filter text boxes and set default filtering values in filter text boxes when initializing

### ISSUE THREAD

**Issue by sahil37** [adazzle/react-data-grid#669]
**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[ x] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[ x] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**

There is no way at the moment to show the filter boxes for each column by default on initialization without the user having the click on the filter rows button. Additionally there is no way to set default filter values for the filter boxes for each column.

**Expected/desired behavior**

A way to show the filter boxes for each column by default on initialization as well as populate these filter boxes for each column with initial values.

**What is the motivation / use case for changing the behavior?**

I am saving the filter values entered by the user on the back-end and I want to use them to repopulate the filter text boxes when the component is initialized again.

**Comment by dsego** [comment]
My workaround to show filters:

```js
    componentDidMount() {
        this.grid.onToggleFilter();
    }
    render() {
         return (
         <ReactDataGrid
                ref={(grid) => { this.grid = grid; }}

```

**Comment by tranquilize** [comment]
```javascript
componentDidMount() {
  this.refs.dataGrid.setState({canFilter: true}, () => this.hideFilterButton())
}

hideFilterButton = () => $('div.react-grid-Toolbar .tools button.btn').hide();
``` 
works for me

**Comment by mathieuripert** [comment]
+1 for having the ability to set default values for filters at initialization.

**Comment by Prashant89Chaudhary** [comment]
+1 for having the ability to set default values for filters at initialization or from any funcation

**Comment by Prashant89Chaudhary** [comment]
Any update on this.

**Comment by bostondevin** [comment]
+1

**Comment by KevinMongiello** [comment]
Here's my workaround.  In this case, I know the order of my columns never change, so I used the element selector in dev tools to find the input i wanted to set default to and voila.
```
componentDidMount() {
		this.grid.onToggleFilter();
		setTimeout(function () {
			document.getElementsByClassName("form-control")[2].value = "false";
		}, 250);
	}
```

**Comment by madhan-dhamodaran** [comment]
Any update or workaround for this. I want to show some default filter text, especially for the multi-select filter. I keep my filtering logic on the server side. So, I am getting the right results. I just need to set the filter values/text in the Filter controls. Please update if there is a work around for this. 

Thanks,
Madhan

**Comment by amanmahajan7** [comment]
Currently `RDG` does not seem to support showing the `filter` by default and @dsego [solution](https://github.com/adazzle/react-data-grid/issues/669#issuecomment-280942382) seems like a good workaround. 

To show some default filter text, [custom filters](http://adazzle.github.io/react-data-grid/examples.html#/custom-filters) can be used. Something like the following should do the trick

```
filterRenderer: (props) => <CustomFilter initialFilterTerm="value" {...props} />
```

In the `CustomFilter` `initialFilterTerm` can be used to set the initial [`state`](https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid/src/cells/headerCells/FilterableHeaderCell.js#L11)

**Comment by madhan-dhamodaran** [comment]
@amanmahajan7,

I have finished adding this and ready to raise a PR. I have been trying to get in touch with a you guys through email, slack etc., but in vain. I have added one more feature as well for customizable columns. I will raise a new issue for that.

Not sure how to reopen this issue. But, this issue is valid and I will be raising a PR before this weekend

**Comment by Antonhansel** [comment]
Up so the bot won't close ;)

**Comment by bhanu52004** [comment]
Would be very interested in the capability to set default filter values through a function for the table

**Comment by saulfrank** [comment]
How can we do this in a functional component like the examples??

**Comment by dngconsulting** [comment]
+1 How (the hell ;-)) can we use useRef() and grid.onToggleFilter() in a functional component ?
Sounds crazy not to have any way to display by default filters columns without activating this ugly toolbar...
