### ISSUE TITLE
Dynamic row height

### ISSUE THREAD

**Issue by thomasdejagere** [adazzle/react-data-grid#671]
**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[X] v0.14.x
```

```
Community Supported:
[ ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[X] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
The row height is a fixed value. The height value can be specified through the "rowHeight" property of the ReactDataGrid component. There is no (clear) way to have rows with a variable row height.

**Expected/desired behavior**
The height of the cell (and row) must be automatically changed to the height of the rendered html in the cell.

**Reproduction of the problem**
![chrome_2017-02-21_14-34-18](https://cloud.githubusercontent.com/assets/10919277/23167258/f70fe38c-f843-11e6-9041-59cb282db884.png)

**What is the motivation / use case for changing the behavior?**
I want to render html from string in a cell.

**Comment by raymondtam** [comment]
For latecomers, i can confirm that it can be easily done by returning <ReactDataGrid.Row height={your_desired_height}/> in the `rowRenderer` function & implement your own formatter if you have troubles rendering the line break. (split and render each line as a div)

**Comment by vijayrajaram** [comment]
@raymondtam returning <ReactDataGrid.Row height={your_desired_height}/> in the rowRenderer was able to produce rows of different heights but the moment I start to scroll the grid beyond the initial viewport, the grid goes into an infinite loop of re-rendering the rows. Any guidance on overcoming this?  

Using version 2.0.69

**Comment by ChelseaCallan** [comment]
@vijayrajaram Did you ever get an answer to this or find a work around? I'm running into the same issue.

**Comment by danlittlejohn** [comment]
I have a need for this as well.  Is there a way to overload the scroll function or access the virtualizer to implement something for variable row heights?  Maybe in the RowRenderer?

**Comment by joinsunil** [comment]
I am also stuck in the same issue !!

**Comment by danlittlejohn** [comment]
I have something that mostly works, but is not great.  My implementation does not have many rows and columns so I decided to force overscan

                <TableDataGrid
                    // use overScan to prevent table virtual rows
                    // this renders all rows without any virtual / rendering on demand
                    // does not work with columns
                    overScan={{
                        colsStart: columnCount,
                        colsEnd: columnCount,
                        rowsStart: overScanRows,
                        rowsEnd: overScanRows,
                    }}

This worked horizontally, but still had a lot of re-rendering horizontally so I fixed it to always render from the first column by extending the class.

    class TableDataGrid extends ReactDataGrid {
        render() {
            // force viewport columns to always start from zero
            // to prevent row re-rendering when scrolling horizontally
            if (this.base && this.base.viewport) {
                this.base.viewport.getVisibleColStart = () => 0;
            }
            return super.render();
        }
    }

On safari it is still has issues with header and body not scrolling together smoothly, but it is at least usable.  We are likely going to replace react-data-grid unless we can fix the remaining issues.

**Comment by joinsunil** [comment]
Anyone is working on this feature ?

**Comment by sontek** [comment]
Yeah, this shouldn't have been close.  Still needs to be looked at.

**Comment by AliAlperSakar** [comment]
Is there any solution for re-rendering when scrolling?

**Comment by JSoet** [comment]
Just fyi, seems like this might be fixed in the latest version... I haven't tried in my code yet because we need to upgrade, but I just tried on the example here:
https://adazzle.github.io/react-data-grid/docs/examples/render-base-row
changing the RowRender to have a variable row height:
```
const RowRenderer = ({ renderBaseRow, ...props }) => {
  const color = props.idx % 2 ? "green" : "blue";
  return <div style={{ color }}>{renderBaseRow({...props, height: (((props.idx % 2) + 1) * 40)})}</div>;
};
```
and it seemed to work

**Comment by zackify** [comment]
This project is kind of a joke. Every real issue gets closed and nobody looks at it. I get being busy, but don't close real issues without updating us...

**Comment by sammysamx20** [comment]
Any updates? I need the rows to be dynamic

**Comment by Vedican** [comment]
> Just fyi, seems like this might be fixed in the latest version... I haven't tried in my code yet because we need to upgrade, but I just tried on the example here:
> https://adazzle.github.io/react-data-grid/docs/examples/render-base-row
> changing the RowRender to have a variable row height:
> 
> ```
> const RowRenderer = ({ renderBaseRow, ...props }) => {
>   const color = props.idx % 2 ? "green" : "blue";
>   return <div style={{ color }}>{renderBaseRow({...props, height: (((props.idx % 2) + 1) * 40)})}</div>;
> };
> ```
> 
> and it seemed to work

I just gave his example a try in Chrome and when you scroll down the top rows start flickering. Also when I scrolled down slowly it kept trying to take me back to the top of the grid (scroll down slowly and you keep going back to the first few rows).

**Comment by umanga907** [comment]
Where is the fix for the dynamic height  of the row ?

**Comment by omair115** [comment]
how i can set dynamic height of table based on rows ...?

**Comment by omair115** [comment]
what the solution for dynamic height of ReactData grid  ...?

**Comment by Fi1osof** [comment]
Still waiting for...

**Comment by anisimov-evgeniy** [comment]
please suggest another library
