### ISSUE TITLE
DataGrid - themes/styles

### ISSUE THREAD

**Issue by martinnov92** [adazzle/react-data-grid#674]
Hello,

I would like to know if there is any recommended way how to style your DataGrid? 
Do you support something like themes? Or should I just override your CSS styles? 
Thank you

**Comment by Kliton** [comment]
Up

**Comment by NathanBWaters** [comment]
+1

**Comment by NathanBWaters** [comment]
Can't figure out how to override their css styles...

**Comment by martinnov92** [comment]
Hi @NathanBWaters, I do it like this: I wrapped the data grid in div with my own class name and every time I need to change css styles I use ´.my-special-class .react-data-grid...´ and override it without need of '!important'

**Comment by NathanBWaters** [comment]
@martinnov92 thanks man! 
I was using css modules so I needed to put `:global .react-data-grid` to make it work.  👍

**Comment by vnallamhawk** [comment]
@martinnov92 : Could you provide an example on how to apply custom styles by wrapping it in a div. I am new to reactjs>
