### ISSUE TITLE
Warning: Cell: `ref` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop.

### ISSUE THREAD

**Issue by lixinwei1230** [adazzle/react-data-grid#679]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**
yes, but it turns out the reason is because of new feature of react

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[X] v0.14.x
```

```
Community Supported:
[X] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[ ] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ ] feature request
[X] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
Although there is no error. But chrome keep sending the warn message: Warning: Cell: `ref` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop.

**Expected/desired behavior**
Don't show this message again.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Comment by supamanda** [comment]
Tp replicate, you can see this warning while running your tests: https://ci.appveyor.com/project/adazzle/react-data-grid/build/1.0.2649

**Comment by supamanda** [comment]
Looks like this duplicates #638

**Comment by michielboekhoff** [comment]
@supamanda It does indeed look like this is a duplicate. I'm the author of #638 and I'm currently working on it. If you've got any questions about the progress, just ask on there.
