### ISSUE TITLE
Contributing a date column type

### ISSUE THREAD

**Issue by bor3ham** [adazzle/react-data-grid#68]
This page hints at a date column type:
http://adazzle.github.io/react-data-grid/examples.html#/all-the-features

.. but the date column doesn't have a formatter / editor.

Is this something that will be built into future versions, or are users expected to roll their own? If I submit a PR using http://hacker0x01.github.io/react-datepicker/ would that be something you're interested in?

**Comment by malonecj** [comment]
We have created a date picker editor here internally based off this plugin
https://github.com/dangrossman/bootstrap-daterangepicker
I can share the code if you like

The reason we didn't include it is we want to keep the dependencies of react-data-grid to a minimum. A better way of sharing editors and including them in react-data-grid is something we are discussing at the moment. In the short term though, if you would like to create a pull request and add a new example to the examples section on how to create a date picker based off react-datepicker, we would be happy to accept that

**Comment by gtkovas** [comment]
Am not the issue poster, but I would appreciate seeing that code. I have been trying to splice in various DatePicker widgets from React (and one from jQuery) without success.

**Comment by jpdriver** [comment]
hi guys, the old PR for that is here https://github.com/adazzle/react-data-grid/pull/3.

As @malonecj mentioned, it's really just a wrapper for that bootstrap date-range picker, and in this case renders as a single-date calendar control. the actual underlying component is pretty flexible -- but at the time all we needed was a single calendar to appear as an editor...

we do still use the code written in that PR, but for now that editor is one of the ones we internalized to avoid react-data-grid getting bloated.
