### ISSUE TITLE
Highlight edited cells

### ISSUE THREAD

**Issue by dsego** [adazzle/react-data-grid#680]
**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[x] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[ ] Chrome
```

```
Should work:
[ ] Firefox
[x] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
No way to know if a cell has been edited.

**Expected/desired behavior**
After editing, cell changes background color to signify that the value is changed.

**Reproduction of the problem**
CSS class `.react-grid-Cell` and `div.react-grid-Cell__value` add padding, so having a custom formatter to highlight cells is tricky and requires overriding default styles.

**What is the expected behavior?**
Having an option to style the whole cell.

**What is the motivation / use case for changing the behavior?**
An option to add a style (background color for example), to cells that have been edited, updated or to highlight differences between original and modified data.

**Comment by dsego** [comment]
At the moment I am doing this. Looking for a better solution.
```js
class CellRenderer extends Component {
    render() {
        const { rowIdx, column: { key } } = this.props;
        const hl = this.context.shouldHighlight(rowIdx, key);
        return <Cell {...this.props} className={ hl ? 'highlight-cell' : ''}/>;
    }
}

CellRenderer.contextTypes = {
    shouldHighlight: React.PropTypes.func
};


class RowRenderer extends Component {
    render() {
        return <Row cellRenderer={CellRenderer} ref="row" {...this.props} />;
    }
}
```

**Comment by borisovano** [comment]
Hi,
I see RowRenderer in ReactDataGrid props but not CellRenderer.
Where do you call this component from? or where do you pass it to ReactDataGrid component?

**Comment by dsego** [comment]
@borisovano I export my custom RowRenderer  `export { RowRenderer };` and pass that into the grid
`<ReactDataGrid  rowRenderer={RowRenderer} />`.

**Comment by smtheard** [comment]
@dsego Thank you for this workaround, but I am having trouble understanding where you define shouldHighlight. How are you accessing that function from CellRenderer and where do you originally define it? I guess I am unfamiliar with this.context and how to initialize it.

**Comment by dsego** [comment]
@smtheard It's been a while since I looked at that code, but I think your parent component provides context for children. So you need to implement the `getChildContext` method and return a context object with the stuff you need.

```jsx
class MyCustomTable extends Component {
    // ...

    getChildContext() {
        return {
            shouldHighlight: (id, key) => {
                return this.state.updates.hasOwnProperty(id) &&
                    this.state.updates[id].hasOwnProperty(key);
            }
        };
    }

    // ...
    render() {
        return (
            <div>
                <ReactDataGrid rowRenderer={RowRenderer} />
            </div>
        );
    }
}

MyCustomTable.childContextTypes = {
    shouldHighlight: React.PropTypes.func
};


For more info:
https://facebook.github.io/react/docs/context.html

**Comment by dg92** [comment]
@dsego from where Row and Cell are imported?

**Comment by dsego** [comment]
@dg92   `import { Row, Cell } from 'react-data-grid';`

**Comment by dg92** [comment]
@dsego Thanks for that. Also, i need to change the background color of cells in a row on basis of a condition, can you help me out?

**Comment by dsego** [comment]
@dg92 You have everything here, just implement your own `shouldHighlight` method.
https://github.com/adazzle/react-data-grid/issues/680#issuecomment-287656682
https://github.com/adazzle/react-data-grid/issues/680#issuecomment-311105962

**Comment by Se0ng11** [comment]
is there any easier way to achieve this by today?

**Comment by fatalispm** [comment]
@dsego I am also implementing similar functionality. While I managed to do a lot using this functionality, I still have troubles when implementing switching highlighting using shortcuts. The problem is Cell is never rerendered, so it never changes its style. Is there a way to force rerendering?

**Comment by smtheard** [comment]
still a real issue

**Comment by smtheard** [comment]
i won't respond to this again, this is a silly bot

**Comment by akashg90** [comment]
This breaks the frozen column functionality. 
I implemented the same solution to highlight edited cells but in case if I have a frozen column then header remains frozen but cells for that column moves. 

This how it looks like in case of frozen column 
<img width="955" alt="Screen Shot 2019-03-28 at 5 54 57 PM" src="https://user-images.githubusercontent.com/10613175/55157860-7eb70500-5183-11e9-8791-9cfa07be59f9.png">

Anyone has idea to fix the issue.

**Comment by olajohn-ajiboye** [comment]
@akashg90 Did you manage to fix this issue with the broken fixed column. It has kept me awake for weeks. Nothing works. Let me know if you found a workaround. Otherwise, this would be a deal-breaker for me.

**Comment by akashg90** [comment]
@olajohn-ajiboye I was not able to fix it. Also, i dropped the idea of highlighting cell.

**Comment by kenklin** [comment]
> @dg92 Try this `import { Row, Cell } from 'react-data-grid';`

`Cell` is no longer exported in `7.0.0-beta.11`
