### ISSUE TITLE
Editor is too large for the edited cell.

### ISSUE THREAD

**Issue by jason-henriksen** [adazzle/react-data-grid#688]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[ ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[ ] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**

![image](https://cloud.githubusercontent.com/assets/15348479/23591207/c8adddca-01a1-11e7-889a-30ee4507bfdd.png)

**Expected/desired behavior**

The editor should fit the cell being edited.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.

      <ReactDataGrid
        enableCellSelect={true}
        columns={this._columns}
        rowGetter={this.rowGetter}
        rowsCount={this.props.data.costList.length}
        rowHeight={25}
        minHeight={150}
        onGridRowsUpdated={this.handleGridRowsUpdated} 
      />

**What is the expected behavior?**

Cell editor should fit the cell being edited

**What is the motivation / use case for changing the behavior?**

**Comment by gilcardenas** [comment]
I am also seeing this issue. It seems that including bootstrap does fix the issue but you should not have to depend on bootstrap for this basic behavior
