### ISSUE TITLE
Locked columns moves slightly during scroll in Edge/Internet Explorer

### ISSUE THREAD

**Issue by chrismiceli** [adazzle/react-data-grid#691]
**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[ ] v15.0.x
```

```
Other:
[x] v15.4.1
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[x] IE 9 / IE 10 / IE 11
[x] Edge
[ ] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
When scrolling horizontally while some columns are locked, the locked columns jitters only in Edge or IE, but not in Chrome.

**Expected/desired behavior**
The column shouldn't move while scrolling the grid horizontally as in Chrome.

**Reproduction of the problem**
0. Use IE or Edge
1. Create a table with at least 1 fixed column (http://adazzle.github.io/react-data-grid/examples.html#/fixed-cols)
2. Reduce the screen window to the grid has a horizontal scrollbar.
3. Scroll the horizontal scrollbar

**What is the expected behavior?**
The column shouldn't move while scrolling the grid horizontally as in Chrome.

**What is the motivation / use case for changing the behavior?**
To improve the user experience for users of Edge or IE.

**Comment by chrismiceli** [comment]
![691](https://cloud.githubusercontent.com/assets/1526781/23676031/e58026c4-0340-11e7-8cbe-0b3f8f3e2397.gif)
gif of the issue.

**Comment by jorgenho** [comment]
can confirm this is an issue in chrome  as well (v57.0.2987.110).

**Comment by jorgenho** [comment]
Got it working by removing custom styling of the  `.react-grid-Canvas ` class.

**Comment by charleyw** [comment]
@jorgenho how did you fix it ?

I have the same issue in chrome which opened in a retina screen. But in non retina screen the locked column work perfect.

**Comment by amanmahajan7** [comment]
Looks like a bug to me.
