### ISSUE TITLE
onRowUpdated is called twice when clicking away

### ISSUE THREAD

**Issue by GenoD** [adazzle/react-data-grid#692]
**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[ X ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[ X ] Chrome
```

```
Should work:
[ X ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
Table calls _onRowUpdated_ twice when clicking away as opposed to once when hitting enter.
The result is an updated view but with a wrong value in the state.

From what I can observe, the table handles the update then re-renders to present the new value. However, another _onRowUpdated_ is called and sets the value back to the original without performing a re-render.

In my situation, I am using a column as "Quantity" which I multiply by a "Price" to update a "Total" value on the page. When I edit the "Quantity" and hit enter, _onRowUpdated_ is called and completes the intended actions. Editing the "Quantity" and instead clicking away causes the view to update but _onRowUpdated_ is called twice (once to set new value and again to set the value back to its original) 

**Expected/desired behavior**
Table should only call _onRowUpdated_ once in either case

**Reproduction of the problem**
Monitor the data actually being stored in your row object and before and after editing and clicking away.

**Comment by AvoJFB** [comment]
Why you closed this?
