### ISSUE TITLE
Latest release versions not displaying on github releases page (14 March 2017)

### ISSUE THREAD

**Issue by supamanda** [adazzle/react-data-grid#695]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[x ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[x ] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
Releases page on github shows 2.0.2 as the latest release version, and npm shows 2.0.18 as the latest release version

**Expected/desired behavior**
The latest release versions on github and npm should match.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.

Go to github releases page: https://github.com/adazzle/react-data-grid/releases
It says 2.0.2 is the lastest release version

Go to npm react-data-grid page https://www.npmjs.com/package/react-data-grid
It says 2.0.18 is the latest release version

**What is the expected behavior?**

The latest release versions on github and npm should match.

**What is the motivation / use case for changing the behavior?**

**Comment by djbusby** [comment]
Now NPM is showing 2.0.19 as the latest release - but it fails on runkit, with a 'self' not defined error.

  https://runkit.com/58d3ef11ae69180014e72b42/58d3efc72872330014a51b99/branches/master

**Comment by rajanJain1991** [comment]
@djbusby did you find solution to this error?

**Comment by jpdriver** [comment]
hey @supamanda -- the reason for the different version numbers on NPM and the GitHub Releases page is due to our adoption of Lerna.

Lerna lets you publish multiple NPM packages from the same repository -- so we actually have two version numbers. If you look at the [package.json](https://github.com/adazzle/react-data-grid/blob/master/package.json#L3) file in the root, it says the version for the repository is 2.0.1. But the latest [version of the packages](https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid/package.json#L3) within it is 2.0.44.

We'll only publish a new Github Release when we need to bump the repository version.

Hope that helped!

**Comment by supamanda** [comment]
hey @jpdriver 
Thanks for your response. I see what you're saying - although there's still a discrepancy because the repository version is 2.0.1 but the latest release version is 2.0.2 (https://github.com/adazzle/react-data-grid/releases) - why is that?
Was this intended? It seems quite confusing!

**Comment by jpdriver** [comment]
that one i'm not entirely sure about. it's possible 2.0.2 was intended as a package version bump, and not a new repository version, as that would have been around the time Lerna was introduced and it may just be human error..

as a general rule of thumb, stick to either the `master` branch or what's published on NPM if you want the latest code.

**Comment by lord-xeon** [comment]
Is there a way to get the changelog for the different releases?  As it stands, I've been going through commits one at a time to see what's changed in each update.  This is tedious, especially since releases happen very often on this project, and I can easily get behind.
