### ISSUE TITLE
Can't horizontally scroll when filters return no results

### ISSUE THREAD

**Issue by tranquilize** [adazzle/react-data-grid#696]
**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[x] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[x] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
When a user applies a filter that returns no results, the spreadsheet resets to the left-most view, and horizontal scrolling stops working. If the filter applied needs to be horizontally scrolled into view, then it can't be scrolled into view to be cleared out, thus a user will be stuck on a blank spreadsheet and require a component/page refresh. The issue appears to be that column headers by themselves are not horizontally scrollable.

**Expected/desired behavior**
A user should be able to horizontally scroll to clear out the applied filter.

**Reproduction of the problem**
1) Start with a datagrid with rows and filters enabled. There should be enough columns to necessitate horizontal scrolling.
2) Scroll to a far-right filter.
3) Filter for a non-existent value
4) Receive no rows as a result.
5) Datagrid jumps back to the left-most view, and cannot horizontally scroll. 

**What is the expected behavior?**
After returning no rows for a filter that needs to be horizontally-scrolled into view, the datagrid should still be horizontally-scrollable so a user can clear out the filter.

**What is the motivation / use case for changing the behavior?**
Prevents users from being stuck on a blank datagrid.

**Comment by Prashant89Chaudhary** [comment]
Hi ,
Any workaround to fix this issue .

**Comment by mondasd** [comment]
Encountered the same issue today.  Work arounds or fixes available?

**Comment by TamerlanByteAnt** [comment]
+1

**Comment by oleksii-udovychenko** [comment]
Please find a workaround at #873

**Comment by oleksii-udovychenko** [comment]
Please find a workaround at #873

**Comment by amanmahajan7** [comment]
Duplicate issue, closing in favor of https://github.com/adazzle/react-data-grid/issues/873
