### ISSUE TITLE
Adding double click handler no longer works

### ISSUE THREAD

**Issue by GenoD** [adazzle/react-data-grid#697]
**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[ X ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[ X ] Chrome
```

```
Should work:
[ X ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
Prior to updating, the following solution worked in 1.0.40

Implementing Double Click events no longer works in version 2.0.2

**Expected/desired behavior**

**Reproduction of the problem**
````
var RowRenderer = React.createClass({

 PropTypes: {
   onDoubleClick: React.PropTypes.func
 },

 render: function() {
   return (<ReactDataGrid.Row ref="row" {...this.props} onDoubleClick={this.props.onDoubleClick} /></div>)
 }
});

````
````

function onDoubleClick(e) {
  // handle click event here
}

var Example = React.createClass({
  render: function() {
    return  (<ReactDataGrid
    columns={columns}
    rowGetter={rowGetter}
    rowsCount={_rows.length}
    minHeight={500}
    rowRenderer={<RowRenderer onDoubleClick={this.onDoubleClick} />} />);
  }
});

````

**What is the expected behavior?**
Implementation should add an onDoublClick event handler

**What is the motivation / use case for changing the behavior?**

**Comment by thomasdejagere** [comment]
I want the same functionality, the provided solution doesn't work for me neither.

**Comment by gaurav-quasar** [comment]
Similar to this, there are other events which are not supported. This change has been added in version 1.0.62 to remove warnings for unknown props.
