### ISSUE TITLE
debugger statements in npm dist (0.13.1-flow-osx673 & 0.13.1)

### ISSUE THREAD

**Issue by MalcolmDwyer** [adazzle/react-data-grid#70]
After doing an `npm install` with the either `0.13.1-flow-osx673` (the current latest in npm), or `0.13.1`, the following files have `debugger;` statements in the dist. See the first lines of `HeaderCell.render()`
```
node_modules/react-data-grid/dist/react-data-grid.js
node_modules/react-data-grid/dist/react-data-grid-with-addons.js
```
Source link: https://github.com/adazzle/react-data-grid/blob/master/src/HeaderCell.js#L27

**Comment by malonecj** [comment]
Thanks

This issue has been fixed by https://github.com/adazzle/react-data-grid/pull/72

The current default release for react-data-grid is `0.13.2'
