### ISSUE TITLE
Auto Complete Filter not filtering out similar terms

### ISSUE THREAD

**Issue by fmlharrison** [adazzle/react-data-grid#705]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[x ] v15.4.2
```

```
Community Supported:
[ ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[x] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
I am using react data grid to display the results of a donor search and each search result has alot of data. I am using the Auto Complete Filter add-on to filter by blood type of which there are types A, B, AB and O. When I select B from the drop down menu of filter terms the donors with types B **and** AB are shown, which is not what I want. I want only to see donors with B type. When I filter by A, only the donors with A type are shown and when I filter by AB, only the donors with AB type are shown.
Looking at the code for the Auto Complete Filter I think that there might be a bug in the code. Here is the link to the line where I think the problem is: https://github.com/adazzle/react-data-grid/blob/0b65faaecf8ec57c1b3c8c8f5981c482ade0c481/packages/react-data-grid-addons/src/cells/headerCells/filters/AutoCompleteFilter.js#L45
I was wondering why the first character of the cells value is not checked and if anyone else has run into this problem.
 
**Expected/desired behavior**
I would like only the donors with B blood type to be shown when I filter by B blood type not B and AB type donors.

**Reproduction of the problem**
![ab filter](https://cloud.githubusercontent.com/assets/20514501/24098414/33e52708-0d62-11e7-91c8-8e5e5d418e47.PNG)

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Comment by diegomurakami** [comment]
Hi @fmlharrison, can you send more information about your props you are sending within the component?

**Comment by fmlharrison** [comment]
Hi @diegomurakami 

I am using the AutoCompleteFilter component from the react-data-grid-addons and I am setting that as a filterRenderer property in the ABO column object:
```
{
  key: 'abo',
  name: 'ABO',
  width: 110,
  resizable: true,
  filterable: true,
  filterRenderer: AutoCompleteFilter
},
```

From what I can work out, it doesn't look like I can send this component any props.... but maybe I am wrong. Is there a way to pass your own props to the AutoCompleteFilter component?

In my ReactDataGrid component, I am passing it a <Toolbar/> component as props with filters enabled and I have other props like onAddFilter, getValidFilterValues and onClearFilter. Here is my ReactDataGrid component:
```
<ReactDataGrid
                            rowKey="id"
                            enableCellSelect={true}
                            columns={this.state._columns}
                            rowGetter={this.rowGetter.bind(this)}
                            rowsCount={this.rowsCount()}
                            headerRowHeight={60}
                            minColumnWidth={0}
                            rowHeight={70}
                            minHeight={420}
                            overScan={{colsStart: 17, colsEnd: 17, rowsStart: 25, rowsEnd: 25}}
                            toolbar={<Toolbar enableFilter={true} filterRowsButtonText="Filter"/>}
                            onAddFilter={this.handleFilterChange.bind(this)}
                            getValidFilterValues={this.getValidFilterValues.bind(this)}
                            onClearFilters={this.handleOnClearFilters.bind(this)}
                            rowSelection={{
                                showCheckbox: true,
                                enableShiftSelect: true,
                                onRowsSelected: this.onRowsSelected.bind(this),
                                onRowsDeselected: this.onRowsDeselected.bind(this),
                                selectBy: {
                                    isSelectedKey: "isSelected"
                                }
                            }}
 />
```

I followed the code in the Custom Filter Example here: http://adazzle.github.io/react-data-grid/examples.html#/custom-filters

I also have a column 'gender' which can either be 'Male' or 'Female' and when I use the same AutoCompleteFilter addon I get the same problem. That is, when I filter by 'Male', it doesn't filter out the Female results, but when I filter by 'Female', it filters out the male results as it should do.

Thanks.

**Comment by diegomurakami** [comment]
Hi @fmlharrison, I believe that https://github.com/adazzle/react-data-grid/pull/708 will fix this problem.
