### ISSUE TITLE
Cell should also accept arrays as the value

### ISSUE THREAD

**Issue by OracPrime** [adazzle/react-data-grid#706]
**WHICH VERSION OF REACT ARE YOU USING?**
```
2.0.18
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ X] Chrome
```
-------

**I'm submitting a ...**  (check one with "x")
```
[ X] bug report

```

**Current behavior**
If you provide an array as column data, it renders, but you get a console error
complaining about the proptype

**Expected/desired behavior**

When I have a row item such as this
 rowItem{
    hits: number[]
}

then I expect to be able to provide hits as a column definition and use a customer formatter
which receives a props containing a number[] field.  And indeed I do.  But Cell.js has
 a proptypes check

value: React.PropTypes.oneOfType([React.PropTypes.string, React.PropTypes.number, React.PropTypes.object, React.PropTypes.bool]).isRequired,

which needs to include React.PropTypes.array.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**
As per the current behaviour but without the error.

**What is the motivation / use case for changing the behavior?**
I have a use case where I want to display two values stacked in a cell.  This works with a custom formatter that renders a table in the cell from the array in the props, but only with an error log appearing in the console.

NB I'm happy to submit a PR if you are happy that this is a desired change

**Comment by OracPrime** [comment]
So I've submitted a PR for this, but the CI build is failing with an unresolved reference.  Which is bizarre, as it works locally for me, and the change I made should not have affected this at all.  Can anyone help?

https://github.com/adazzle/react-data-grid/pull/715

**Comment by OracPrime** [comment]
Anyone?

**Comment by jpdriver** [comment]
hey @OracPrime -- not sure why this failed... since it's just a PropTypes change we should be able to safely merge it.

cc. @diogofcunha @malonecj

**Comment by ValYouW** [comment]
Hey @jpdriver @malonecj 
Any news with that? any objection of adding array to Cell propTypes?
Thx.

**Comment by ValYouW** [comment]
@jpdriver ping... :)

**Comment by OracPrime** [comment]
I'm assuming no-one is waiting for me on this?  My PR is building locally, so I'm assuming it's a problem with the CI system?
