### ISSUE TITLE
How to handle the click row event?

### ISSUE THREAD

**Issue by xinnanzhang** [adazzle/react-data-grid#71]
set enableCellSelect={true}, need to click twice to come into force the onSelect function.

**Comment by malonecj** [comment]
What browser and operating system are you using? 

From my tests on chrome, IE, Firefox on windows - onSelect is triggered on first click.

As for row click, there is currently no onRowClick event in react-data-grid. If you want such an event you can create your own custom row renderer with a click event along the lines of this example
http://adazzle.github.io/react-data-grid/examples.html#/custom-row-renderer

**Comment by omarish** [comment]
@xinnanzhang very interesting - noticing the same thing over here - have to click twice to fire `onSelect`. I'm using Chrome 46.0.2490.86 on  OS X 10.11.0.
