### ISSUE TITLE
Excel-like formulas

### ISSUE THREAD

**Issue by nschwan94** [adazzle/react-data-grid#718]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[X ] v0.14.x
```

```
Community Supported:
[ ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[ X] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

I don't see any library out there that is able to clone excel's formulas feature, and I think it would be a huge value add for users if they could base cell values off of formulas taking other cell vals as arguments. If this is already implemented, I didn't exactly see it in the examples.

**Comment by aliscie** [comment]
> > **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**
> 
> > **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**
> 
> > **THANKS!**
> 
> **WHICH VERSION OF REACT ARE YOU USING?**
> 
> ```
> Officially Supported:
> [X ] v0.14.x
> ```
> 
> ```
> Community Supported:
> [ ] v15.0.x
> ```
> 
> **WHICH BROWSER ARE YOU USING?**
> 
> ```
> Officially Supported:
> [ ] IE 9 / IE 10 / IE 11
> [ ] Edge
> [ X] Chrome
> ```
> 
> ```
> Should work:
> [ ] Firefox
> [ ] Safari
> ```
> 
> **I'm submitting a ...** (check one with "x")
> 
> ```
> [ ] bug report
> [ X] feature request
> [ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
> ```
> 
> I don't see any library out there that is able to clone excel's formulas feature, and I think it would be a huge value add for users if they could base cell values off of formulas taking other cell vals as arguments. If this is already implemented, I didn't exactly see it in the examples.

you can try [hot formula parser](https://www.npmjs.com/package/hot-formula-parser). I just started tying it and I still don't know how to implement it yet. we can help each other on code sandbox if you like
