### ISSUE TITLE
Checkbox input in data grid.

### ISSUE THREAD

**Issue by michielboekhoff** [adazzle/react-data-grid#723]
**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[ X ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[ X ] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
I would like to support having checkboxes in my data grid. Right now, this is not possible (at least not easily) even with custom formatters & editors.

**Expected/desired behavior**
I would like a user to be able to tick a checkbox without any difficulties.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**
This way, when there is a boolean option, this will be able to be presented to the user in an intuitive manner.

**Comment by nicholaspsmith** [comment]
@michielboekhoff Did you ever find a workaround for this? I am having the same issue.
