### ISSUE TITLE
When filtering the last character entered into the filter input box is ignored

### ISSUE THREAD

**Issue by pwhipp** [adazzle/react-data-grid#725]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ x] 3.10.3
```

```
Community Supported:
[ ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[x ] Chrome
```

```
Should work:
[x ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
Entering filter term fails to use the last character typed when filtering (it is not passed back in the relevant filterTerm)

**Expected/desired behavior**
The last character typed into the filter input box should be included in the filter.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Comment by pwhipp** [comment]
This is specific to using the filters passed back in 'onAddFilter' where the value is incorrect in the callback filterTerm. Perhaps setState is being used and the callback is invoked before it is assigned.

**Comment by giacomoguerci** [comment]
I am not sure what your code looks like, but if you're using something like `componentWillUpdate `or `componentWillReceiveProps`, to pass the filters to Selectors, make sure to use nextProps/nextState.filters instead of this.props/this.state.filters. I hope this helps x
