### ISSUE TITLE
Horizontal scroll with filter bar dissociates title row from other rows

### ISSUE THREAD

**Issue by ben-freenome** [adazzle/react-data-grid#729]
**WHICH VERSION OF REACT ARE YOU USING?**
```
[X] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**
```
[X] Chrome
```

--------

**I'm submitting a ...**  (check one with "x")
```
[X] bug report
```

**Current behavior**
On horizontally-scrollable data grids with the filter bar showing, scrolling horizontally (or tabbing between columns) causes the filter row, but not the title row, to track the scroll

**Expected/desired behavior**
Both the filter and title rows should track horizontal scrolling

**Reproduction of the problem**
Create a horizontally-scrollable grid
enable filtering
enable filter row
scroll horizontally

**What is the motivation / use case for changing the behavior?**
This bug makes tracking the title very difficult for grids with long horizontal orientation.
![pre-scroll](https://cloud.githubusercontent.com/assets/25310810/24765620/5842c3a0-1aad-11e7-9e61-b21377937c9c.png)
![post-scroll](https://cloud.githubusercontent.com/assets/25310810/24765627/5bf2d558-1aad-11e7-94b1-fb243fdd8810.png)

**Comment by Whythawye** [comment]
Is this perhaps related to this issue: https://github.com/adazzle/react-data-grid/issues/724

**Comment by dmytro-danylov** [comment]
The frozen columns bug was fixed in version 2.0.29, but this issue remains (title columns don't move when the grid is scrolled horizontally and the filters are enabled).

**Comment by 0eyeshield210** [comment]
I had fixed it in file Header.js in function: 
"setScrollLeft(scrollLeft: number) {
    let node = ReactDOM.findDOMNode(this.refs.row);
    node.scrollLeft = scrollLeft;
    this.refs.row.setScrollLeft(scrollLeft);
    if (this.refs.filterRow) {
      let nodeFilters =  ReactDOM.findDOMNode(this.refs.filterRow);
      nodeFilters.scrollLeft = scrollLeft;
      this.refs.filterRow.setScrollLeft(scrollLeft);
    }
  }," => old, with the new code: 
"setScrollLeft(scrollLeft: number) {
    let headers = ReactDOM.findDOMNode(this);    
    let headerRows = headers.querySelectorAll('.react-grid-HeaderRow');      
    for (let i = 0; i < headerRows.length; i++)
    {   
      headerRows[i].scrollLeft = scrollLeft;      
    }      
  },"

**Comment by nehvaleem** [comment]
same issue for me. quite annoying :(

**Comment by james12** [comment]
I'm also face this issue please quick fix.

**Comment by Mahtabalam** [comment]
"contain: inherit" css property can fix scrolling issue in chrome. working fine in chrome, safari, Firefox etc...
