### ISSUE TITLE
Expanding/collapsing and row re-rendering rows (grouping feature) not working.

### ISSUE THREAD

**Issue by pizzadev** [adazzle/react-data-grid#733]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**
yep
> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[ ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[x] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

Expanding/collapsing rows not working. I get en error like:

Uncaught TypeError: Cannot read property '__metaData' of undefined.

                <ReactDataGrid columns={columns}
                               toolbar={toolbar}
                                rowGetter={this.getRowAt.bind(this)}
                                rowsCount={this.getCount.bind(this)}
                                minHeight={500}
                                ref={ node => this.grid = node }
                               enableCellSelect={true}
                               enableDragAndDrop={true}
                               onRowExpandToggle={this.onRowExpandToggle.bind(this)}
                               rowHeight={50}
                               minHeight={600}

                    />

    getRows() {
        let rows = Selectors.getRows(this.state);
        return rows;
    }

    getRowAt(index) {
        let rows = this.getRows();
        return rows[index];
    }

    getCount()
    {
        return this.getRows().length;
    }

    onRowExpandToggle({ columnGroupName, name, shouldExpand }) {
        let expandedRows = Object.assign({}, this.state.expandedRows);
        expandedRows[columnGroupName] = Object.assign({}, expandedRows[columnGroupName]);
        expandedRows[columnGroupName][name] = {isExpanded: shouldExpand};
        this.setState({expandedRows: expandedRows});
    }

**Comment by osolano** [comment]
Hey @pizzadev  I'm running into the same issue. did you resolve this?

**Comment by pizzadev** [comment]
yes, you should have array of selectedRows in state and working with array while expanding/collapsing rows. this array contains your rows + group rows.

**Comment by digvickey** [comment]
@pizzadev can you please post the correct code, I'm trying to get get the row-expand feature work, but can not. Thanks in advance.

**Comment by pizzadev** [comment]
super(props);
        this.state = {
           rows:[],
            expandedRows: {},
           ...
        } 
getRows() {
        let rows = Selectors.getRows(this.state);
        return rows;
    }

    getRowAt(index) {
        let rows = this.getRows();
        return rows[index];
    }

    getCount()
    {
        let t = this.getRows();
        return t.length;
    }




.....

 <ReactDataGrid
                    onRowClick={this.onRowClick.bind(this)}
                                ref={ node => this.grid = node }
                                columns={columns}
                               toolbar={toolbar}
                                rowGetter={this.getRowAt.bind(this)}
                                rowsCount={count}
                                onGridRowsUpdated={this.handleGridRowsUpdated.bind(this)}
                    rowSelection={{
            showCheckbox: false,
            selectBy: {
              isSelectedKey: 'isSelected'
            }
          }}
                    />
