### ISSUE TITLE
Still unable to use React Date Picker as a React Data Grid custom cell editor

### ISSUE THREAD

**Issue by soma83** [adazzle/react-data-grid#738]
@giko45

On #389 you asked how to hook a custom editor for replacing the regular editors. Later on you wrote about the handleSelectChange and the constructor, so, could you please give an example of this? 

I'm trying to get the react datepicker as a custom editor for a column in a react datagrid component, over and over and every time I try this is unsuccessfully... Please, anybody could give some hint? How should I invoke the DatePicker? Should I call it from a different class?

Thanks in advance, folks!

**Comment by bvn13** [comment]
Look, I wrote  simple custom editor. Try to use it as a wrapper for building your date picker editor.

`
import React from 'react';
import PropTypes from 'prop-types';
const { editors: { EditorBase } } = require('react-data-grid');


export default class ParamsEditor extends EditorBase {

    constructor(props) {
        super(props);
        this.state = {
            value : '',
        };
        this._input = null;

        this.getInputNode = this.getInputNode.bind(this);
        this.getValue = this.getValue.bind(this);

        this.onValueChanged = this.onValueChanged.bind(this);
    }

    getInputNode() {
        return this._input;
    }

    getValue() {
        var updated = {};
        updated[this.props.column.key] = '123 - '+this.state.value;
        return updated;
    }

    onValueChanged(ev) {
        this.setState({ value : ev.target.value });
    }

    render() {
        return (<div>
            <h3>editor</h3>
            <input ref={(ref) => { this._input = ref; }} value={this.state.value} onChange={this.onValueChanged}></input>
        </div>);
    }

}


ParamsEditor.propTypes = {
    column: PropTypes.any,
};
`
