### ISSUE TITLE
How to change rows from the outside?

### ISSUE THREAD

**Issue by bvn13** [adazzle/react-data-grid#740]
I wrote a wrapper for ReactDataGrid for using as Component, but it seems not to change rows-data, whisch set up from props:

`export default class EmailRecipientsEditor extends React.Component {

    constructor(props) {
        super(props);
        this.state = {
            data : this.props.hasOwnProperty('data') ? this.props.data : [],
        };

        this._columns = [
            {
                key: 'id',
                name: 'ID',
                width: 80,
            },
            {
                key: 'recipient_name',
                name: 'Name',
                editable: true,
            },
            {
                key: 'recipient_email',
                name: 'E-Mali',
                editable: true,
                //editor: PrioritiesEditor
            },
            {
                key: 'subject_parameters',
                name: 'Subject parameters',
                editable: true,
                editor: ParamsEditor,
                //formatter: IssueTypesFormatter
            },
            {
                key: 'body_parameters',
                name: 'Body parameters',
                editable: true,
                editor: ParamsEditor,
                //formatter: IssueTypesFormatter
            },
            {
                key: 'attachments',
                name: 'attachments',
                editable: true,
                //editor: ParamsEditor,
                //formatter: IssueTypesFormatter
            }
        ];

        this.rowGetter = this.rowGetter.bind(this);
        this.handleGridRowsUpdated = this.handleGridRowsUpdated.bind(this);
        this.emptyGridView = this.emptyGridView.bind(this);
        this.addNewRow = this.addNewRow.bind(this);
    }

    rowGetter(i) {
        return this.state.data[i];
    }

    handleGridRowsUpdated({ fromRow, toRow, updated }) {
        let rows = this.state.data.slice();

        for (let i = fromRow; i <= toRow; i++) {
            let rowToUpdate = rows[i];
            let updatedRow = update(rowToUpdate, {$merge: updated});
            rows[i] = updatedRow;
        }

        this.setState({ data : rows });

        this.props.onChangeHandler(rows);
    }

    addNewRow(ev) {
        ev.preventDefault();
        var rows = this.state.data;

        rows.push({
            id : this.state.data.length,
            recipient_name : '',
            recipient_email : '',
            subject_parameters : '',
            body_parameters : '',
            attachments : '',
        });

        this.setState({ data : rows });
        this.props.onChangeHandler(rows);
    }

    emptyGridView() {
        return () => (
            <div className="emailRecipientsEditor__emptyGrid">
                No recipients yet. Add one to set it up.
            </div>
        );
    }

    render() {
        return (<div className="emailRecipientsEditor">

            <div className="emailRecipientsEditor__newButton">
                <button onClick={this.addNewRow} className="btn btn-default">Add recipient</button>
            </div>

            <ReactDataGrid
                enableCellSelect={true}
                columns={this._columns}
                rowGetter={this.rowGetter}
                rowsCount={this.state.data.length}
                minHeight={500}
                onGridRowsUpdated={this.handleGridRowsUpdated}
                emptyRowsView={this.emptyGridView()}
            />

        </div>);
    }
}

EmailRecipientsEditor.propTypes = {
    onChangeHandler : PropTypes.func.isRequired,
    data : PropTypes.any,
}`

The code 
`
this.state = {
            data : this.props.hasOwnProperty('data') ? this.props.data : [],
        };
`

does not force the Grid update it's rows.

**Comment by jpdriver** [comment]
hey @bvn13 -- you should never set anything in `this.state` from `this.props`

it's an anti-pattern (see http://reactjs.cn/react/tips/props-in-getInitialState-as-anti-pattern.html), and that's the reason you're not seeing any updates.

`constructor` methods are only called once -- so when your wrapper Component first mounts it will set it's own initial `state` correctly, but this will only work once.

even if your `props` later change, there's nothing to also update the wrapper Component's local `state`.

does that make sense?

**Comment by lruckman** [comment]
Have you tried updating the state in componentWillReceiveProps  after inspecting the new props to ensure its a change you want to act on?
