### ISSUE TITLE
Update handlers are triggering twice.

### ISSUE THREAD

**Issue by AvoJFB** [adazzle/react-data-grid#742]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[x ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[ x ] Chrome
```

```
Should work:
[ x ] Firefox
[ x ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
onRowUpdated and onGridRowsUpdated handlers are triggering twice if you click away from table. On other cases(submit with enter or click on table) everything works well. And also I noticed,that if cell have an editor then handlers are triggering once

**Expected/desired behavior**
onRowUpdated and onGridRowsUpdated handlers should trigger once

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the motivation / use case for changing the behavior?**
I need to make AJAX requests on cell change and I can send 2 requests with this bug,can you help me with this?

**Comment by jean343** [comment]
Can we re-open this bug, it is not fixed.
If we change a value which will affect sorting, then the second call will pass the same rowId, but since the sorting changed we will update the wrong row.
