### ISSUE TITLE
Wrong fromRow, toRow values on updating  when grouping feature is turned on

### ISSUE THREAD

**Issue by pizzadev** [adazzle/react-data-grid#743]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[x ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[x ] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

Got wrong fromRow and ToRow  values while using 'row-grouping-feature' and updating rows.
For example, if we have an array of 5 rows. These 5 rows was grouped in 2 groups. Your grid thinks that we have 7 rows.  So, when I'm updating last row ( 5th row from array ) - I get fromRow=7 and toRow=7

**Comment by mhcdionisio** [comment]
Use `Data.Selectors.getRows(this.state);` for fetching the correct data.
