### ISSUE TITLE
findDOMNode was called on an unmounted component

### ISSUE THREAD

**Issue by bradennapier** [adazzle/react-data-grid#745]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[ ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[ ] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**

invariant.js:44 Uncaught Error: findDOMNode was called on an unmounted component.
    at invariant (invariant.js:44)
    at findDOMNode (findDOMNode.js:53)
    at Scroller.fixHorizontalScrollbar (index.js:322)

**Expected/desired behavior**
No error

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.

Honestly I don't know, the table is being removed suddenly from the page when it happens.  

**What is the expected behavior?**

No error

**What is the motivation / use case for changing the behavior?**

Errors are bad

**Comment by liz-mars** [comment]
I'm also seeing this issue with React 16 and react-data-grid 2.0.73

**Comment by amanmahajan7** [comment]
Is this still an issue?

**Comment by amanmahajan7** [comment]
Closing this issue due to lack of example. Please create a new issue if you are still facing this
