### ISSUE TITLE
Problem using Row Grouping and Draggable Header together

### ISSUE THREAD

**Issue by Komrod** [adazzle/react-data-grid#757]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**
yes

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[x] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[x] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
I'm trying to make the Row grouping works with other features, like the Draggable Header :
The drag and drop from the Row grouping actually interfers with the Drag and drop of the Draggable Header that changes the columns order.
I couldnt find a way to make the Container component (for row grouping) and DraggableContainer component (for headers) be usable together.

**Expected/desired behavior**
Actually change the column order when I drag the header title even when the Row grouping is activated.

**What is the motivation / use case for changing the behavior?**
All features must work together. I have a website that will use those features all together. If it doesn't work I will have to use another library.

Does those features have been tested together?
Is there a way to make Row Grouping and Draggable Header work at the same time?

Thank you.

**Comment by martinnov92** [comment]
Hi, are you getting error about using two ReactDnD HTML5 backends?

**Comment by filipjurcak** [comment]
Hi, I have the same issue, I can't have both features at the same time. Is there some way to make it work @martinnov92?

**Comment by nzhtrtlc** [comment]
Same issue. 
@martinnov92 I am getting error about HTML5 backend.

**Comment by amanmahajan7** [comment]
HTML5 backend issue was fixed in [v4](https://github.com/adazzle/react-data-grid/pull/1116/commits/305367b52467d6871207f9fc2bfa5ce94e069c75) but I have not tested if both features work together or not. Can one of you try if you are still facing this issue with v4 `react-data-grid@next`? Thanks.

**Comment by srikanthpavuluri** [comment]
@amanmahajan7 
React v16, 
react-data-grid: 3.0.11-next3726, react-data-grid-addons: 3.0.11-next3726,

I've following issues, would require suggestions -

1. Is there a way to make the draggable header and group by columns work together. When group by columns is added to the data grid with draggleheader activated, headerDrop() function is not being called after re-ordering the columns instead the groupByColumns placeholder is getting activated i.e, target to drop the dragged column(s)? Is this functionality (both draggable header & group by columns) is supported or achievable with this plugin? 
2.  Getting the error setScrollLeft is not a function, when the locked is set to TRUE for columns and with rowRender is enabled? (Only the header columns are getting fixed but not the rows). Without rowRender it works fine, able to freeze columns/rows. 
#6868 _this2[column.key].setScrollLeft(scrollLeft); 

Any thoughts on resolution of the above issues.? 
When could we expected the react-data-grid officially supporting v16.2?
