### ISSUE TITLE
Row hover style overriding current cell style

### ISSUE THREAD

**Issue by silverAndroid** [adazzle/react-data-grid#759]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**

Yes

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[x] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[x] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
I'm currently modifying a cell's background based on its validity, so invalid cells get a red background (as shown in #267) but when the mouse hovers over the row, it overrides the change and it becomes grey.

**Expected/desired behavior**
After changing the background colour of the individual cell, I want it to stay that way unless I remove the class that changes the background.

**Reproduction of the problem**
Checking if updated cell is valid, and if it isn't, change the cell background to red using a custom CellRenderer.

**What is the expected behavior?**
Styled cell stays the same unless changed back.

**What is the motivation / use case for changing the behavior?**
Updated/modified cells should be able to stay to the style they are set to by the developer even when hovered over.

**Comment by martinnov92** [comment]
Hi, I think if you override CSS style that should help, try to use !important or please provide some example.

**Comment by silverAndroid** [comment]
That fixed it! Thanks
