### ISSUE TITLE
Data for multiple columns in a nested object 

### ISSUE THREAD

**Issue by moizhb** [adazzle/react-data-grid#762]
**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[X] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[X] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
I have more than one column whose data is in nested object & I cannot add those columns because of the key constraint. Multiple columns cannot have the same key.

**Expected/desired behavior**
I should be able to add both the columns from nested object (may be using dot notation).

This issue solves this problem. [https://github.com/adazzle/react-data-grid/issues/644](https://github.com/adazzle/react-data-grid/issues/644)

**Comment by moizhb** [comment]
Any workaround for this in the meantime?

**Comment by jean343** [comment]
You can find a workaround in https://github.com/adazzle/react-data-grid/issues/644
I used `array[0].key.name` for the key

**Comment by Ben-CA** [comment]
Would be nice to see support for this, and proper documentation with an example.
