### ISSUE TITLE
Toggle the appearance of the select-all-checkbox in the header.

### ISSUE THREAD

**Issue by dbraynard** [adazzle/react-data-grid#766]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[x] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[x] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
A checkbox with id: select-all-checkbox appears in the header row when using showCheckbox.

**Expected/desired behavior**
Allow the appearance of that checkbox in the header to be toggled by a property. 

**What is the motivation / use case for changing the behavior?**

I only want a single row to be selectable in the datagrid

**Comment by dbraynard** [comment]
I have turned it off by applying this css style:
`[for|=select-all-checkbox] { visibility: hidden;}`

Is there a better way?

**Comment by ogg130** [comment]
> I have turned it off by applying this css style:
> `[for|=select-all-checkbox] { visibility: hidden;}`
> 
> Is there a better way?

Thanks! This worked for me mostly.

I found that clicking on the multi select box (even if the checkbox was hidden) still selected the checkboxes in my case.

A simple wrapper to check if one row is selected around the row selecton code overcame it:

  const handleRowsSelected = rows => {
    const rowIdx = rows.map(r => r.rowIdx);
    **if (rowIdx.length === 1) {**
       <<do row selecty stuff here>>
   **}**
}
