### ISSUE TITLE
Grid width not set properly when initialized inside of collapsed div

### ISSUE THREAD

**Issue by jstray** [adazzle/react-data-grid#767]
UPDATE: This is reproducible without Reactstrap, example below is plain Bootstrap now. 

This seems very similar to issue [85](https://github.com/adazzle/react-data-grid/issues/85). It's happening inside a [Bootstrap Collapse component](https://v4-alpha.getbootstrap.com/components/collapse/), with the standard Bootstrap JS plugin. The grid comes out the wrong width (too narrow, usually) until the window is resized. Bug goes away if the Collapse component starts open.

**WHICH VERSION OF REACT ARE YOU USING?**
```
Community Supported:
[x] v15.4.2
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[x] Chrome
```

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**
Wrong grid width when initially inside closed `Collapse` component. 

**Expected/desired behavior**
Correct width when grid first visible.

**Reproduction of the problem**
Minimal demo:
```
import React from 'react';
import ReactDOM from 'react-dom';
import ReactDataGrid from 'react-data-grid';
require('bootstrap/dist/css/bootstrap.css');

class WrongWidth extends React.Component {
  constructor(props) {
    super(props);
    this.rowGetter = this.rowGetter.bind(this);
    this.createRows();
    this._columns = [
      { key: 'id', name: 'ID' },
      { key: 'title', name: 'Title' },
      { key: 'count', name: 'Count' } ];
  }

  createRows() {
    let rows = [];
    for (let i = 1; i < 1000; i++) {
      rows.push({
        id: i,
        title: 'Title ' + i,
        count: i * 1000
      });
    }

    this._rows = rows;
  }

  rowGetter(i) {
    return this._rows[i];
  }

  render() {

    return  (
      <div>
        <button className="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
          Button with data-target
        </button>
        <div className="collapse" id="collapseExample">
          <div className="card card-block">
            <ReactDataGrid
            columns={this._columns}
            rowGetter={this.rowGetter}
            rowsCount={this._rows.length}
            minHeight={500} />)
          </div>
        </div>
      </div>
    );
  }
}

ReactDOM.render(
  React.createElement(WrongWidth, null),
  document.getElementById('root')
);
```

**What is the expected behavior?**
Grid should be at the correct width when first opened.

**Comment by jstray** [comment]
This bug has a different cause than [85](https://github.com/adazzle/react-data-grid/issues/85). That previous fix is working fine: looking at [where the width is set](https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid/src/ReactDataGrid.js#L917) in `ReactDataGrid.render`, `containerWidth` and `gridWidth` are both being set correctly to 100%.

Yet somehow the initial width of each columns is ending up at the [minimum column width](https://github.com/adazzle/react-data-grid/blob/9d0e0bff012f9cdedf21c87a19314d2e14bee2e1/packages/react-data-grid/src/ColumnMetricsMixin.js), that is, 80 pixels.

**Comment by jstray** [comment]
Ok, this results because [this code](
https://github.com/adazzle/react-data-grid/blob/9d0e0bff012f9cdedf21c87a19314d2e14bee2e1/packages/react-data-grid/src/ColumnMetricsMixin.js#L33)

```
    gridWidth(): number {
      return ReactDOM.findDOMNode(this).parentElement.offsetWidth;
    }
```

is returning zero. This happens when the grid is inside a `display: none` container, as happens with a Bootstrap 4 `collapse` element.

**Comment by danvn** [comment]
@jstray Hey did you ever find a fix? I have 3 tables that render together at the same time, but 2 of the tables are initially set to `display: none`. the first table renders fine with auto column widths. When I trigger an event changing the class of a hidden div to `display: block`, the column widths are set to the minimum column width. Only when resizing the window does the table eventually fill the 100% width of it's parent div

**Comment by byoder7** [comment]
Also having the same exact issue. If there is a tab, popup window, whatever, and the width doesn't seem to work right. Resize browser it resizes and all is good. I have to defer rendering of my grids if possible, so they only first try to render when the parent has size. But somehow, when parent resizes it should resize the grid too.  This is in Chrome.

**Comment by jstray** [comment]
@danvn The workaround was to reset the size manually at various points:
```
  // After the component mounts, and on any change, set the height to parent div height
  updateSize = () => {
    const domNode = ReactDOM.findDOMNode(this)
    if (domNode && domNode.parentElement) {
      const container = domNode.parentElement
      const gridHeight = Math.max(100, container.offsetHeight)
      const gridWidth = Math.max(100, container.offsetWidth)
      this.setState({ gridWidth, gridHeight })
    }
  }
```
