### ISSUE TITLE
Editors not rendering

### ISSUE THREAD

**Issue by bwwinthehouse** [adazzle/react-data-grid#77]
var states = ['pending', 'whitelisting', 'completed'];
var DropDownEditor = ReactDataGrid.Editors.DropDownEditor;
var StatesEditor = < DropDownEditor, options={states} />;

var priorities = [{id:0, title : 'Critical'}, {id:1, title : 'High'}, {id:2, title : 'Medium'}, {id:3, title : 'Low'}]
var AutoCompleteEditor = ReactDataGrid.Editors.AutoComplete;
var PrioritiesEditor = < AutoCompleteEditor, options={priorities} />;

Warning: Failed propType: Required prop `value` was not specified in `EditorContainer`. Check the render method of `Cell`.
warning.js:48 Warning: Failed propType: Required prop `commit` was not specified in `SimpleTextEditor`. Check the render method of `EditorContainer`.

**Comment by bakesteve** [comment]
sorry we missed this
http://adazzle.github.io/react-data-grid/examples.html#/editors is the best place to start from
ad if yuou replace the top area of code with: 
```
var priorities = [{id:0, title : 'Critical'}, {id:1, title : 'High'}, {id:2, title : 'Medium'}, {id:3, title : 'Low'}]

var AutoCompleteEditor = ReactDataGrid.Editors.AutoComplete;
var PrioritiesEditor = <AutoCompleteEditor options={priorities}/>

//options for IssueType dropdown editor
var issueTypes = ['pending', 'whitelisting', 'completed'];
var DropDownEditor = ReactDataGrid.Editors.DropDownEditor;
var IssueTypesEditor = <DropDownEditor options={issueTypes}/>
```
you get what (I think) you are after, so closing this off for now

**Comment by giko45** [comment]
change
	      return React.createElement(EditorContainer, { rowData: this.getRowData(), rowIdx: this.props.rowIdx,  idx: this.props.idx, cellMetaData: this.props.cellMetaData, column: col, height: this.props.height });
	    }


to 
	      return React.createElement(EditorContainer, { rowData: this.getRowData(), rowIdx: this.props.rowIdx, value: this.props.value, idx: this.props.idx, cellMetaData: this.props.cellMetaData, column: col, height: this.props.height });
	    }
