### ISSUE TITLE
Case insensitive column sorting

### ISSUE THREAD

**Issue by sun2rise** [adazzle/react-data-grid#774]
```
Community Supported:
[X] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[X] Chrome
```

--------

**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
Now when I sort a column the values are sorted in a case sensitive way: words starting with a capital letter are always all before or after the ones all in lower case.

**Expected/desired behavior**
When I sort a column the outcome should be case insensitive or at least the function that I pass to `onGridSort` property of ReactDataGrid should sign like this:
handleGridSort(sortColumn: String, sortDirection: String, caseInsensitive: Bool)

**Reproduction of the problem**
You can use the [Filterable Sortable Columns Example](http://adazzle.github.io/react-data-grid/examples.html#/filterable-sortable-grid) but modify it so that the values of a column are mixed between capital letters and all lower case words

Thanks

**Comment by elebeaup** [comment]
A suggestion is to modify the `sortRows` function (`RowSorter.js`). If a comparing property (like a function) is defined into the column definition then it is used for the comparison otherwise the default comparison function is used. This new property must be also added to the `onGridSort`.

**Comment by amanmahajan7** [comment]
This is by design, you should be able to specify your own custom sort function to handle sorting however you like. Please follow the example

http://adazzle.github.io/react-data-grid/scripts/example08-sortable-cols.js
