### ISSUE TITLE
Attempting to copy a value on a Mac (Cmd + C) leads to "C" being filled instead of copying the value

### ISSUE THREAD

**Issue by motin** [adazzle/react-data-grid#791]
**WHICH VERSION OF REACT ARE YOU USING?**
The one in the following examples page: http://adazzle.github.io/react-data-grid/examples.html#/all-features

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[X] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
Attempting to copy a value (Cmd + C) leads to "C" being filled into the Cell.

**Expected/desired behavior**
The cell contents should be copied to clipboard without being edited/changed.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.

1. Go to http://adazzle.github.io/react-data-grid/examples.html#/all-features
2. Select the "Alessandra" cell in the "First name" column
3. Press Cmd + C (Mac)

**What is the expected behavior?**

The cell contents should be copied to clipboard without being edited/changed.

**What is the motivation / use case for changing the behavior?**

In any Excel-like application it is expected to be able to copy a cell value (and then paste it into somewhere else).

**Comment by motin** [comment]
Just found that Ctrl + C actually copies the value, so this seems to be more of an issue of incorrect keyboard shortcuts than a problem with the actual copying.

**Comment by jpdriver** [comment]
hey @motin -- yeah I was about to mention that! 😄 

it's down to the event keys we check. at the moment we only [check for `e.ctrlKey`](https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid/src/KeyboardHandlerMixin.js#L59).

I think we'd just need to change that line to
```
return (e.ctrlKey === true || e.metaKey === true) && e.key !== 'Control';
```

**Comment by nitinguptadr-dori** [comment]
Has this suggested change been added? I am trying to find a simple way to just enable the copying of text data from any cell so I can paste that - i.e. I have a URL in one of my cells, I just want to be able to do CTRL-C (windows) or COMMAND-C (Mac) and copy the data so I can paste it elsewhere.

**Comment by statico** [comment]
Just a friendly bump. I'd love to see this functionality included in react-data-grid without maintaining our own branch.
