### ISSUE TITLE
column cells to the right of a locked column hidden

### ISSUE THREAD

**Issue by nazk420** [adazzle/react-data-grid#796]
I have the leftmost column locked, which works. However, part of the column cells following the locked column are hidden beneath the locked columns' cells.

The screenshot below has the "Driver" column locked and the "Mode" column that is the next to it, has part of the its cells hidden underneath the locked column cells.

![column_cells_followed_by_locked_column_hides](https://cloud.githubusercontent.com/assets/28784972/26208002/f6225bb8-3be0-11e7-98ab-b3de86dd70db.png)

**Comment by amit-sharon** [comment]
having the same problem.
I am using react version: 15.5.4 and react-data-grid 2.0.44.
also in jsfiddle when clicking the play around with it link in Frozen Columns Example.

![image](https://cloud.githubusercontent.com/assets/10973244/26281352/ea4423d0-3dfc-11e7-8e64-17d21217f6ae.png)

**Comment by nazk420** [comment]
Still not even a single comment on this!!

worked around that I used: 
Add a column just after the last locked column when you define your columns:

`{key: "emptyColumn",  				name: "#",				width: 20},`

You don't need to assign any values to the cells. Adjust the width if you like, 20 works for me.

**Comment by amit-sharon** [comment]
@nazk420 thanks but i decided to switch to a different data-grid.
i am now using fixed-data-table-2 as my grid

**Comment by akashg90** [comment]
This issue still exists even with 6.0 version. Did anyone find the solution or fix for this issue.
