### ISSUE TITLE
isRowSelected prop in CheckboxEditor

### ISSUE THREAD

**Issue by martinnov92** [adazzle/react-data-grid#799]
Hello,

does anybody knows if it possible to get isRowSelected prop to CheckboxEditor? 

I would like to make custom column with checkboxes as I need to replace select all checkbox with something else, but don´t know how - so I was thinking to make custom row with custom header and checkboxes in each row, but I need to set if checkbox is checked or not and I noticed that each row and even cell has property isRowSelected...
Is it possible to access that property from checkbox? Or should I make a pull request with passing that prop one more component down?
Or do you have any other idea how to make my solution work?

Thank you and sorry for my English, hope it makes sense...

**Comment by sjain-mi9** [comment]
@martinnov92 did you find solution to this?? If yes, can you please share it

**Comment by martinnov92** [comment]
Hello @sjain-mi9 I did not. I just set checkbox to not to be visible in header row and then I made a component which I set position to first column with css...
