### ISSUE TITLE
How to do colSpan for cell 

### ISSUE THREAD

**Issue by Suprit-S-M** [adazzle/react-data-grid#807]
I would want to apply colSpan for parent row and I don't want to apply colSpan for child rows in tree.
Can you please help me .

**Comment by jpdriver** [comment]
hey @Suprit-S-M -- unfortunately both `colSpan` and `rowSpan` attributes are not officially supported at the moment, but this may change in future.

the only thing i can think of suggesting is to forcibly override the CSS styling to make a cell visually appear to span, but as mentioned this is not officially supported.

HTH.

**Comment by Suprit-S-M** [comment]
okay , thank you

**Comment by hyeminHwang** [comment]
Not yet? I'm still waiting colSpan
