### ISSUE TITLE
PropType validation error when Cell.value is missing

### ISSUE THREAD

**Issue by mkenyon** [adazzle/react-data-grid#811]
**WHICH VERSION OF REACT ARE YOU USING?**
v15.4.2

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[x] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**

When one of the cell values for the RowGetter is null, there is a PropType validation error, even though there is a defaultProp specified. Stack trace follows:

```
msg: Warning: Failed prop type: The prop `value` is marked as required in `Cell`, but its value is `null`.
    in Cell (created by Row)
    in Row (created by Canvas)
    in div (created by SimpleRowsContainer)
    in SimpleRowsContainer (created by RowsContainer)
    in RowsContainer (created by Canvas)
    in div (created by Canvas)
    in Canvas (created by Viewport)
    in div (created by Viewport)
    in Viewport (created by Grid)
    in div (created by Grid)
    in div (created by Grid)
    in Grid (created by ReactDataGrid)
    in div (created by ReactDataGrid)
    in div (created by ReactDataGrid)
    in ReactDataGrid (created by CompGrid)
```

**Expected/desired behavior**

The `value` prop should not be required and the defaultProp should be used instead.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.

```jsx
function testCase() {
  var columns = [{key: "a", name: "a"}];
  var rowGetter = function(index) {
    return [{a: null}][index];
  }

  return <ReactDataGrid columns={columns} rowGetter={rowGetter} rowsCount={1} />
}
```

**What is the motivation / use case for changing the behavior?**

I want to be able to use this grid with sparse values, rather than needing to have a value in every single cell. Moreover, there is already a defaultProp defined.

**Comment by bostondevin** [comment]
+1
