### ISSUE TITLE
Select all checkbox does not update if all the rows are selected by hand (or via store).

### ISSUE THREAD

**Issue by MV88** [adazzle/react-data-grid#817]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**
Yes
> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```
```
Community Supported:
[x] 15.4.2
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[x] Chrome
```

```
Should work:
[x] Firefox
[x] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```
not sure it is a bug report because it can be also a feature request, but i'm not certain. (you know it's a feature not a bug)

**Current behavior**
Select all checkbox does not update if all the rows are selected by hand (or via store).

**Expected/desired behavior**
If I select all the rows by hand or if I use "isSelectedKey" and all the rows has the specified key truthy then the select all checkbox should be checked

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.
see this  and try
https://jsfiddle.net/fob2td94/2/

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**
For consistency. It is strange/misleading to have all the rows selected and the selected all checkbox not.

**Comment by animeshkayal** [comment]
Is there any update or any workaround on this issue? I also need this feature.

**Comment by gaurav3017** [comment]
Still no updates?
