### ISSUE TITLE
setState() is called multiple times

### ISSUE THREAD

**Issue by asenvalyovski** [adazzle/react-data-grid#823]
**The error is:**
>**warning.js?8a56:36 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Viewport component.**

This warning happens when very fast mount/unmount between tabs with grids on them. 

![image](https://user-images.githubusercontent.com/17852339/26889185-f55fe79c-4bb5-11e7-9162-c431765360e4.png)

**Comment by amanmahajan7** [comment]
Duplicate issue, closing in favor #764
