### ISSUE TITLE
Row value are not changing when cell drag down till end of a column.

### ISSUE THREAD

**Issue by sanjeev07** [adazzle/react-data-grid#825]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[ ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[ ] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

--------------------------------------------------------------------------------------------------------------
when we do cell drag down for so many row or till end of a column, rows values are not changing . Value should get changed for all selected rows of a particular column. and there should be shift+up/down key support for column cell selection.

**Comment by xinshiMSFT** [comment]
+1

It may be a regression: issue https://github.com/adazzle/react-data-grid/issues/451. I can only drag up to 15-20 rows at a time to apply the changes.

Repro: http://adazzle.github.io/react-data-grid/examples.html#/cell-drag-down. Drag down ~30 rows. They don't update.
