### ISSUE TITLE
Auto expand column to available space

### ISSUE THREAD

**Issue by topgun743** [adazzle/react-data-grid#839]
I am rendering my grid inside a bootstrap based modal dialog.
I need to have that grid columns auto expand to available width whenever modal is being resized.

At present column sizes remain the same when I resize my bootstrap window. See the attached snapshot. 
![rtccgrid](https://user-images.githubusercontent.com/4273108/27333919-f8f866ec-55e0-11e7-996f-63aeb248533e.png)

What should I do ?

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
 v15.4.2
Officially Supported:
[] v0.14.x
```

```
Community Supported:
[ ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**
Firefox latest version
```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[ ] Chrome
```

```
Should work:
[ x] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ ] feature request
[ x] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Comment by martinnov92** [comment]
Hello @topgun743 , I had the same issue and I solved it by removing width from column definition and then every time I resize modal (or in my case split pane), I call the resize event on window and this makes the grid to resize `window.dispatchEvent(new Event('resize'));`.
Not sure if this is the best solution, but it is working for me...
Hope it helps.
