### ISSUE TITLE
Values not showing up for right-hand column cells when the screen size is small. 

### ISSUE THREAD

**Issue by tylerbecks** [adazzle/react-data-grid#840]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[x ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[x] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
Values not showing up for right-hand columns when the screen size is small.  The smaller the screen, the less columns show values.  If I drag the size of the browser to be smaller or larger, the values all show up and never go away until a hard refresh.

**Expected/desired behavior**
For all the values to show initially.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.
Values in right-hand columns not showing up: <img width="696" alt="screen shot 2017-06-21 at 6 28 08 pm" src="https://user-images.githubusercontent.com/16826230/27413591-36c70cfa-56b1-11e7-8013-8fd9a63922e8.png">
HTML showing adjacent cells showing and not showing values: 
<img width="482" alt="screen shot 2017-06-21 at 6 23 30 pm" src="https://user-images.githubusercontent.com/16826230/27413604-4af35de6-56b1-11e7-8d60-baf599f54225.png">

**What is the expected behavior?**
Expected behavior (after I manually adjust the browser size): 
<img width="777" alt="screen shot 2017-06-21 at 6 28 13 pm" src="https://user-images.githubusercontent.com/16826230/27413627-61cbcc6a-56b1-11e7-985b-357dbde9c1ab.png">

**What is the motivation / use case for changing the behavior?**

**Comment by tylerbecks** [comment]
It seems like the cells with no values are actually indented improperly under the last cell with a value.  E.g. in the first photo, the 2017 October cell `div` is actually indented into the 2017 Sep. cell `div`

**Comment by tylerbecks** [comment]
It seems the cells with values show up as Cells and the ones without showing values are these ComponentWrapper components with Cell components inside them.
<img width="757" alt="screen shot 2017-06-21 at 11 57 48 pm" src="https://user-images.githubusercontent.com/16826230/27421064-8aa09a7c-56dd-11e7-8563-8dd6dbebde22.png">

**Comment by tylerbecks** [comment]
A solution we found is to add minColumnWidth: 10 to the gridProps

**Comment by urbinopescada** [comment]
Hello I've the same problem... I will try minColumnWidth:10 and see if it works

**Comment by urbinopescada** [comment]
It doesn't work for me :(;
When I scroll to right, at some point this occurs:
![image](https://user-images.githubusercontent.com/25552747/30289291-9387fa5a-9723-11e7-9774-87b397fc4852.png)
 
If I continue to scroll, eventually the values are shown again:
![image](https://user-images.githubusercontent.com/25552747/30289262-7d7a4be6-9723-11e7-8894-c85aa7f71bf8.png)

It seems like those cells are not rendered!

**Comment by regentcid434** [comment]
Any update on this? The last column in my grid displays this behavior, even with a static column width. The div with class="react-grid-Cell__value" isn't being rendered until my screen width hits about 457px wide.

**Comment by regentcid434** [comment]
I'm using React dev tools to figure this issue out. Digging into the src, `Cell` doesn't seem to have a condition that would prevent its content from being rendered. However, `Row` has a prop called `colVisibleEnd` that I notice increases by one when my screen reaches the width threshold where the cell renders correctly. I'm about to look into how this value is calculated to see why it's incorrect.

**Comment by regentcid434** [comment]
I found where the problem lies. In `ViewportScrollMixin.js`, the function `getRenderedColumnCount` incorrectly calculates how many columns are visible. I my case, on a small screen, my leftmost visible column has a static width of 300. The math used to determine how many columns are visible takes the total visible rendered width of the grid and subtracts the width of the leftmost column. The column index is incremented and its width is subtracted from the diminishing total until the value drops below 1. At that point, it knows which columns' cell contents to render.

The problem is the assumption that the leftmost visible column is completely visible. In my case, only about a third of the column is visible which would mean you would subtract a third of its width from the viewport width. Instead, the full value is subtracted which will cause the loop to prematurely exit before recognizing the rest of the visible columns.

So, actual scroll position would need to be used for this method to be accurate.

**Comment by regentcid434** [comment]
@tylerbecks @urbinopescada Good news everyone! Using the file in my local node_modules as my playground, I was able to fix this. I'll get started on pulling down the repo and making my changes formal.

**Comment by regentcid434** [comment]
@tylerbecks @urbinopescada This is my first public pr, but if you wanna try out my changes to make sure they work in your situations, I'd be grateful.

**Comment by GlebDolzhikov** [comment]
Have same issue, pls allow to merge!

**Comment by regentcid434** [comment]
@GlebDolzhikov The PR has merge conflicts now. In fact, I think one of the files it modifies no longer exists or was moved.

**Comment by milkers** [comment]
Anyone has at least a temporary fix to the problem?

**Comment by urbinopescada** [comment]
Hi, you can check the code I changed to workaround that issue in https://github.com/urbinopescada/react-data-grid/commit/fcd4fa6c1b3ef9742322f4859b80c3a508f126b2

**Comment by rlreamy** [comment]
We just noted the same issue in our application.  I can actually see the values appear and disappear in a small screen as I scroll left and right.

**Comment by rlreamy** [comment]
This is still an open issue for us.
