### ISSUE TITLE
Select all checkbox updates wrong grid

### ISSUE THREAD

**Issue by GenoD** [adazzle/react-data-grid#847]
**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[x ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[X ] Chrome
```

```
Should work:
[X ] Firefox
[X ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
Having multiple tables containing { showCheckBox: true } will cause undesired behavior. For my instance I have 3 tabs in a panel, each containing a data grid (favorites, frequent items, past items). Each of these grids are given the checkbox to select all rows. When clicking on either of the last two tabs' selectAll checkboxes, the first table is updated instead.

![rdg bug](https://user-images.githubusercontent.com/5068500/27494624-98a9d922-5803-11e7-9751-1d37d10c0a0b.gif)

**Expected/desired behavior**
Each selectAll checkbox should only update and select its corresponding rows.

**Reproduction of the problem**
Create several tables on the same page, all with the showCheckbox set to true.

**What is the expected behavior?**
Clicking selectAll should only select rows within the respective Data Grid.

**What is the motivation / use case for changing the behavior?**
Edge case but limits a page to a single data grid given specific requirements.

**Comment by eugenkorzh** [comment]
Got same problem. Any updates on this issue or workarounds?

**Comment by eugenkorzh** [comment]
Found issue cause, all 'select-all' checkboxes and their labels got same 'id' and 'for' attributes.
I use this workaround: 
1. Gave ref to my ReactDataGrid: 
  ref={node => this.grid = node}
2. Added unique value for 'id' and 'for' attributes:
  if (this.grid !== undefined && this.grid.selectAllCheckbox.id === 'select-all-checkbox') {
      this.grid.selectAllCheckbox.id += `-${*someUniqueValue*}`;
      this.grid.selectAllCheckbox.nextSibling.htmlFor += `-${*someUniqueValue*}`;
    }

**Comment by veromarchand** [comment]
Hi, I have a similar problem. 
I have 3 tabs and when switching tabs, I reset the selected indexes array and pass my new rows as props (within the same grid, using componentWillReceiveProps). This works fine except the "check all" checkbox doesn't get unchecked.

 I tried the workaround but I'm having trouble. When inspecting I can see the checkbox properties (ID and for attributes) do take my unique identifier, but it still remains checked when switching tabs. Any idea?

**Comment by balasubramanian1410** [comment]
this one worked for me. inside render include this check.

`if(this.props.gridName && _.get(this, 'grid.selectAllCheckbox')) {
      this.grid.selectAllCheckbox.id = `-${this.props.gridName}`;
      this.grid.selectAllCheckbox.nextSibling.htmlFor = `-${this.props.gridName}`;
    }`

u have to update the this.grid.selectAllCheckbox.id with unique values to get respective table row data.

**Comment by matt-catellier** [comment]
@balasubramanian1410 when you say "this one worked for me. inside render include this check." does that mean on the render of the row? Using a custom row rendered? 

Do you have an example?

**Comment by matt-catellier** [comment]
I have found a solution, need to use a ref, and componentDidMount() on the parant component. Had to use component did mount so the ref was available. When tried you code in render() it only worked after the first time someone selects all.  Using with componentDIdMount() it will work the first time.

```
i.e.
componentDidMount() {
    if (this.grid !== undefined && this.grid.selectAllCheckbox.id === 'select-all-checkbox') {
      const uniqueNumber = uuid.v4()
      this.grid.selectAllCheckbox.id += `-${uniqueNumber}`;
      this.grid.selectAllCheckbox.nextSibling.htmlFor += `-${uniqueNumber}`;
    }
}
render() {
<ReactDataGrid ref={node => this.grid = node}
}
```
