### ISSUE TITLE
new fork and npm package react-data-grid-extended

### ISSUE THREAD

**Issue by danielpetrov** [adazzle/react-data-grid#853]
Hi guys,

sorry for removing your pretty issue boilerplate. Just wanted to notify you something:
  1. We are developing this extensions for react-data-grid - https://github.com/danielpetrov/react-data-grid-hocs . It is still not full but we are using it in some projects.
  2. There are issues with your libraly like hardcoded classes, no support for identical keys in two different columns, lack of support for immutable data in selection/sorting.
  3. We've already made a pull request for fixing the sorting issue and it is taking too long for you to merge it (> 2 weeks)
  4. We need issues to be fixed faster, because we are chasing some deadlines.

Therefore:
  1. We will fork your project on github, fix a lot of issues with your libraly and merge our react-data-grid-hocs into it (by adding the hocs, and for example adding a support for in the headers for custom search column, etc...)
  2. We will create a new npm package called react-data-grid-extended and push our forked version to it.
  3. Anytime you decide you can merge our project into yours. We will add a link to your project in our readme and periodically merge your new releases into our fork.
  4. We hope we are not stealing any author rights, we just need the fixes to happen faster and we need the new extensions and we need that to be installed as a npm package. Once you decide to merge our fork into your project we will delete our npm package.

Yours Daniel,

P.S. You can contact us on danielpetrov222@gmail.com , maieutiquer@gmail.com

**Comment by supamanda** [comment]
Hey guys,

I agree it is frustrating to get no response to an issue or PR after weeks.

Would it be possible to give more people access to merge to this repository?
Or maybe update the contributing page to say what contributors can expect regarding response times?

Thanks :)
Amanda

**Comment by martinnov92** [comment]
Hello, I agree with @supamanda as well.
I made a pull request two months ago and it still has not been merged even tho I did only small change ☹️

**Comment by jpdriver** [comment]
Hi all,

The official Adazzle response can’t come from me – you will probably need either @malonecj or @bakesteve for that, so I’m cc’ing them in here.

My immediate thoughts are that while I understand some people might be working to deadlines that rely on faster responses than Adazzle can provide, if possible any project forks needed for specific business requirements should be kept private; or at the very least aliased to an enterprise namespace.

I appreciate that the response times can be frustrating. The unfortunate reality here is that currently the internal maintainers do not have capacity to keep up with every single issue that users open. For the immediate future, only issues that Adazzle open themselves, or that directly benefit Adazzle will be given attention by the internal team.

As for @supamanda’s query re. giving more people access to this repository, this is unlikely to happen. I would love nothing more than to give a few of our regular contributors who have proven themselves to be invaluable time and time again full read-write permissions, but that decision lies with Adazzle and for a couple of reasons I won’t go into here may or may not even be possible.

But maybe — just maybe — seeing the lengths some users are going to to address issues will prompt some internal discussions at Adazzle around the Grid and it’s future.

Obviously this isn’t a good response. I’m just trying to be as open and honest as I can be, in the spirit of the good parts of the open-source community.

As a final note just in case anyone doesn’t know who I am; I used to work at Adazzle but do not anymore. During my time there I was on the team directly responsible for React Data Grid, more or less from the start of the project.

You should in no way take *anything* I’ve said above as any kind of official response or indication thereof. Like I said, I’m just trying to be honest.

HTH.

**Comment by bakesteve** [comment]
Hi Daniel

In terms of merging in, while we fully appreciate you wanting a super fast (or simply a less than 2 week) turnaround.  I'm sure you can understand that as with any software company, we wont always be in a place to do that, as much as we would like to

In terms of your points above, for sorting and selection, we internally use immutable data patterns (through redux) and that has been one aspect we have grappled with most - how to be agnostic about how people manage state while adding features that fundamentally require some state. Or put simply, we use redux but didn't want to do anything that forced everyone else to. 

For the extensions / changes, obviously you are free to extend, fork, or anything else (its MIT after all), and pulling upstream changes is something we are always open to (albeit at times, less quickly than some might like). To avoid confusion, its obviously best if we can keep those as 'addons' - and enabling this was one of the key drivers to adopt lerna. Naturlaly though, not everything can be an extension / add on as it may need to change something in core, or need a hook that simply isnt there. For that we'll get in touch off line to work out a better way to manage that process. 
If you can hold off on the npm side for now taht'd be great to avoid confusion - but if you need that for your tooling, then fair enough. Maybe keep it as a -pre / v0 to make it clear that we may come up with a better / different approach.

Hope that helps
Steve

ps also [merged your fix for immutable](https://github.com/adazzle/react-data-grid/pull/856)

**Comment by danielpetrov** [comment]
Hi guys,

 1. Yes we need an npm package beacause it is not convinient to us to keep-to-track the changes between several projects.
 2. We are going to make changes to the CORE.
 3. We are chasing deadlines and sometimes we need the changes to happen immediatelly
 4. We will downgrade to v0 as you requested.
 5. https://www.npmjs.com/package/react-data-grid-extended - here is the npm package, https://github.com/danielpetrov/react-data-grid - here is the github repo
 6. Documentation and list of todos will be added. We will try to keep changes as transperent as possible so you can merge them later into one project if you decide so, and then we could get rid of this project.
 7. https://github.com/danielpetrov/react-data-grid-hocs - We are considering to add the hocs as you added addons into the packages folder.
 8. We will add customizable classes, htmlKey field (because you are using key which is the name of the property for html key as well) and other improvements. As pointed out above documentation will be improved.
 9. Last but not least you can merge we will open a pull request into this project and you can merge anytime any improvements as you see fit.

Daniel(s)

**Comment by bakesteve** [comment]
@danielpetrov closing this off for now, and we'll track upstream changes on the fork  either through PRs, or by us keeping an eye on it, as you see fit.
