### ISSUE TITLE
z-order fixed column is too high for fixed columns

### ISSUE THREAD

**Issue by oliverwatkins** [adazzle/react-data-grid#855]
The z-order for fixed columns is too high (99). In the styles it looks like :  

```
.react-grid-Cell--locked:last-of-type {
  border-right: 1px solid #dddddd;
  box-shadow: none;
  z-index:99;
}
```

However this interferes with loading spinners. Eg :  

![image](https://user-images.githubusercontent.com/9626175/27679493-36bc52ac-5cb9-11e7-9523-35976f431efc.png)

I changed the z-order to 10, and the table still works perfectly fine. Perhaps you should change it to a lower number.

**Comment by hiredgunhouse** [comment]
Yes, I'm having the same issue with select `rowSelection: { showCheckbox: true }`  
I get z-index: 99 which inteferes with other stuff on the page, i.e. date time pickers, popup dialogs, etc.
Please fix that.

**Comment by hiredgunhouse** [comment]
Seems this is no longer an issue, at least with version 2.0.76

**Comment by SaurabhBayani** [comment]
The issue is still there in 4.0.7
