### ISSUE TITLE
copy value ranges

### ISSUE THREAD

**Issue by jpdriver** [adazzle/react-data-grid#86]
i'd like to be able copy & paste a range of rows and columns, similar to what you can do in Excel at the moment.

this could be copying between cell ranges on the same grid, between two separate grid instances, or from somewhere off-grid (e.g. Excel).

![excel copy paste](https://cloud.githubusercontent.com/assets/2393035/10424809/3fc45d68-70ca-11e5-907a-38d63878d50a.gif)

**Comment by jpdriver** [comment]
linked PR: https://github.com/adazzle/react-data-grid/pull/88

**Comment by tnrich** [comment]
I would love this functionality as well! Any chance it'll be implemented? 

Thanks!
