### ISSUE TITLE
Draggable header not working in IE browser

### ISSUE THREAD

**Issue by randheerpolepelly** [adazzle/react-data-grid#865]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**
Yes but didn't find solution.

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```tried in both v15.0.2 and v0.14.8
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[ ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**
chrome and IE
```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[ ] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
Currently draggable header feature is working in chrome but not in IE. The example given for react-data-grid draggable header example (http://adazzle.github.io/react-data-grid/examples.html#/draggable-header) itself not working in IE.

**Expected/desired behavior**
Expecting draggable header support for IE

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.
Open this link in IE http://adazzle.github.io/react-data-grid/examples.html#/draggable-header
**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Comment by martinnov92** [comment]
There is an error in example page, because IE11 does not support `findIndex` and that is why it is not working. 
You can copy and paste the example to codepen or somewhere and just replace `findIndex` and it should work...
