### ISSUE TITLE
Grid Not Maximising Height Correctly

### ISSUE THREAD

**Issue by oliverwatkins** [adazzle/react-data-grid#871]
We are having immense never ending problems with this weird 'minHeight' thing that is set in the chart. 

Ideally we just want to throw our grid into a div and let it expand to fill. Easy right?

When we first load the grid the actual grid is maximised, but the viewport is set to the minHeight.

In the following screenshot **react-grid-Grid** is filled to max, but the **react-grid-View** is set to min value. This inconsistency does not make any sense.

![image](https://user-images.githubusercontent.com/9626175/28172309-7f2dfca6-67eb-11e7-8e2e-74f242066c0d.png)

Only by resizing and triggering a CSS reflow does the viewport fill up correctly.

If no-one knows this answer can someone point me in the right direction so that I can fix it in the code myself?

**Comment by borabilgin** [comment]
I overcame this problem by overriding the CSS and setting the height to 100% - so that it fits the parent properly.

I also used the overScan property to avoid "empty bottom row" which was referenced in some other issues here.

**Comment by ashking** [comment]
@borabilgin , can you share the snippet from your CSS that makes the data grid height adjust itself?
