### ISSUE TITLE
Empty table doesn't have horizontal scroll after filtration

### ISSUE THREAD

**Issue by YanaSavchenko** [adazzle/react-data-grid#873]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[x] v0.14.x
```

```
Community Supported:
[ ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[x] IE 9 / IE 10 / IE 11
[ ] Edge
[x] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
I have a wide filterable table with horizontal scroll. If there is no rows after filtration, scroll goes away, even tho the header is still wider than the screen. So I can't scroll to the end of the table to change filter value.

**Expected/desired behavior**
Table has horizontal scroll.

**Reproduction of the problem**
1. Create wide table (I'm using fixed columns) with filter
2. Type value that is not in the column

![image](https://user-images.githubusercontent.com/10143921/28219843-03d7c300-6883-11e7-92a4-6ea120fd6403.png)
![image](https://user-images.githubusercontent.com/10143921/28219896-3be3796a-6883-11e7-87cd-c1cce62c80e7.png)

**What is the expected behavior?**
Table has horizontal scroll.

**What is the motivation / use case for changing the behavior?**
Ability to create big tables with filters. Thanks in advance

**Comment by boades** [comment]
I have the same issue. I tried to find out why it is happening, but no luck so far. So I just add an empty row when there are no rows present in a grid after filtering. Works fine for me, but it would be nice to see a reliable fix.

**Comment by RaedsLab** [comment]
@amanmahajan7 any updates on this ?

**Comment by asaturov-b** [comment]
This is a CSS problem. In my case, I have this HTML inside .react-grid-Canvas
<img width="699" alt="2018-12-26 13 36 19" src="https://user-images.githubusercontent.com/15626501/50443269-8a402900-0913-11e9-8c04-ac0fab93b986.png">

The problem is that the div element inside .react-contextmenu-wrapper (for my case) does not have a height. So, when there is no rows, element is not visible.

To fix this problem, I've added this CSS:
.react-grid-Canvas div {
    min-height: 1px;
}

That works fine for me.
