### ISSUE TITLE
react-data-grid-addons overrides custom css of react-select

### ISSUE THREAD

**Issue by YanaSavchenko** [adazzle/react-data-grid#876]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[x] v0.14.x
```

```
Community Supported:
[ ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[x] IE 9 / IE 10 / IE 11
[ ] Edge
[x] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
After installing react-data-grid-addons all custom styles for react-select dropdown changed.

**Expected/desired behavior**
Custom style stay the same

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.

1. Create custom react-select field
2. Install react-data-grid-addons
![image](https://user-images.githubusercontent.com/10143921/28330651-fca14ba4-6bb3-11e7-86e4-ad70cb655638.png)
![image](https://user-images.githubusercontent.com/10143921/28330656-0346d7f8-6bb4-11e7-8e0d-3b03a1a463ba.png)

**What is the expected behavior?**
All styles should not be changed

**What is the motivation / use case for changing the behavior?**
I want to use Sortable and Filterable features, but this package damages my css

**Comment by lord-xeon** [comment]
It's likely due to a version mis-match between what react-data-grid includes, and what you have installed.

rdg is asking for     "react-select": "^1.0.0-beta14",

The latest version [v1.0.0-rc.5](https://github.com/JedWatson/react-select/blob/master/HISTORY.md).  beta14 came out a year ago, and it's likely the CSS between the versions is stepping on things improperly.

**Comment by YanaSavchenko** [comment]
I tried to use an old version of react-select, but got the same issue. 
I'm using:
```
"react-data-grid": "2.0.46",
"react-data-grid-addons": "^2.0.53"
```
