### ISSUE TITLE
Boolean Values Not Showing in Cell

### ISSUE THREAD

**Issue by estermer** [adazzle/react-data-grid#882]
**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[x] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[x] Chrome
```

```
Should work:
[x] Firefox
[x] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
Grid Cells are rendering values of all data types except for booleans

**Expected/desired behavior**
Grid Cells render all data types including booleans

**What is the motivation / use case for changing the behavior?**
We are handling data that contains boolean values and would like that information rendered in the Cell without having to translate it to a String before passing it into the rowGetter.

**Comment by MV88** [comment]
We ended up to pass a formatter function that transforms a boolean value into a string. 
Something like this:
```
module.exports = {
    getFormatter: (desc) => desc.localType === 'boolean' ? (({value} = {}) => value !== undefined ? <span>{value.toString()}</span> : undefined) : undefined
};
```
each column then will have that getFormatter function

**Comment by Gertoolz** [comment]
I still have this problem with versions on Chrome dash_table_experiments 0.6.0, dash 0.28.1
