### ISSUE TITLE
How to join Own components

### ISSUE THREAD

**Issue by bwqdxxg** [adazzle/react-data-grid#883]
editor or formatter after write component errors :
“this.getEditor(...).getInputNode is not a function”

**Comment by malonecj** [comment]
**Writing a custom editor** 
Your custom editor needs to implement two methods
1. `getInputNode` - This is called by the EditorContainer to know which input to focus on when the editor loads.
2. getValue - This is called by the EditorContainer when a value is committed on the grid via a custom editor. It should return an object of key/value properties whereby the key corresponds to a column value eg ```{col1: 'somevalue'}```
Likewise you can return values for other columns from a single editor for more advanced use cases
```{col1: 'someValue', col2: 'anotherValue'}```
