### ISSUE TITLE
Zero values are skipped by filter

### ISSUE THREAD

**Issue by YanaSavchenko** [adazzle/react-data-grid#884]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[x] v0.14.x
```

```
Community Supported:
[ ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[x] IE 9 / IE 10 / IE 11
[ ] Edge
[x] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
When filter with value "0" is applied, rows that have this value are skipped

**Expected/desired behavior**
Rows that have "0" in the column should be displayed

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.
1. Create rows that have value 0
2. Try to filter by 0

![image](https://user-images.githubusercontent.com/10143921/28677221-718c8366-72b2-11e7-8d1c-68a359f24473.png)
![image](https://user-images.githubusercontent.com/10143921/28677243-830a4858-72b2-11e7-8aaf-56a3aaa52e44.png)

**What is the expected behavior?**
Rows that contain zero in value or with zero value should be displayed

**What is the motivation / use case for changing the behavior?**
Improve filtration

**Comment by amanmahajan7** [comment]
I believe this issue has been fixed in #819
