### ISSUE TITLE
Unable to use Immutable Lists for columns

### ISSUE THREAD

**Issue by lord-xeon** [adazzle/react-data-grid#886]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[x] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[x] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
When passing in an Immutable List for the columns, the Grid fails to load/render anything with the following message:

```
Uncaught TypeError: Cannot read property 'setScrollLeft' of undefined
    at index.js:46950
    at List.__iterate (immutable.js:2208)
    at List.forEach (immutable.js:4383)
    at Object.setScrollLeft (index.js:46948)
    at Object.setScrollLeft (index.js:46742)
    at Object._onScroll (index.js:46552)
    at Object.componentDidMount (index.js:46523)
    at Object.chainedFunction (factory.js:617)
    at Object.chainedFunction [as componentDidMount] (factory.js:616)
    at ReactCompositeComponent.js:264
```

**Expected/desired behavior**
Ability to use Immutable Lists for column definitions

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Comment by chmielot** [comment]
This is probably related to https://github.com/adazzle/react-data-grid/issues/80
What I did to solve #80 is to add the following to my webpack config:

```
plugins: [
    new webpack.ProvidePlugin({
      Immutable: "immutable",    // https://github.com/adazzle/react-data-grid/issues/80
    }),
  ],
```
