### ISSUE TITLE
Some of the links to the source code are broken on the web site 

### ISSUE THREAD

**Issue by priand** [adazzle/react-data-grid#888]
For example, if you go to the tree view snippet and click 'jump to source', you get a 404.
http://adazzle.github.io/react-data-grid/examples.html#/tree-view

Would be great to also have a link pointing directly to the Github repo, like https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid-examples/src/scripts/example25-tree-view.js

**Comment by colindjk** [comment]
The broken link was fixed recently in pull #900 btw.
