### ISSUE TITLE
Allow for more functional design (rather than OO)

### ISSUE THREAD

**Issue by mikub** [adazzle/react-data-grid#89]
Not sure whether this would be an enhancement you would consider but it might be beneficial to use a little bit more of functions and attributes rather then objects and properties. 
I am just evaluating this together with facebook's fixed-data-table - and fb's table (while having less features than react-data-grid) works perfectly in this regards, it just requires functions where a function is needed (cell renders aka formatters, cell data getters etc.) and expects necessary data to be passed as such function's arguments (which makes such function's use quite self-explanatory). 
React-data-grid on the other hand (while having much more features) seems to expect everything to be an object that has functions (with no attributes) that are supposed to access object's properties that were somehow (miraculously) set before.
I am trying to use react-data-grid from a functional language (clojurescript) and pretty much I just have to resort to writing js code quite often whereas with fixed-data-table there are no issues.
Apologies if I misunderstood the concept  (I am new to react-data-grid) or am missing something. Basically what I am trying to understand is follows - what are the benefits of using this design:
```javascript
//Custom Formatter component
var PercentCompleteFormatter = React.createClass({
  render:function(){
    var percentComplete = this.props.value + '%';
    return (
      <div className="progress" style={{marginTop:'20px'}}>
        <div className="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style={{width:percentComplete}}>
        {percentComplete}
      </div>
      </div>);
    }
  });
```
as opposed to this design (e.g. used by fixed-data-table):
*The cell renderer that returns React-renderable content for table cell.*
**cellRenderer**
```javascript
function(
  cellData: any,
  cellDataKey: string,
  rowData: object,
  rowIndex: number,
  columnData: any,
  width: number
): ?$jsx
```

`type: func`

**Comment by bakesteve** [comment]
Internally we leverage the above pattern using reusable components. But I cant see any reason we cant either:
- take either a func OR a component
- take a func, that would just return a component

we'll have a look at the impact for this and see which options seems most sensible
