### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by dodzin** [adazzle/react-data-grid#891]
Hi,
Do you plan to do RTL support in next version?

**Comment by jpdriver** [comment]
hi @dodzin -- there aren't any current plans for it, as far as I'm aware..

beyond the text direction, would you want things like Tab to advance between cells RTL too?

**Comment by YochayCO** [comment]
Hi, I wish for an RTL support as well :)
Some things can probably be easy to adjust with css (text-align: right solves text direction),
Others I believe are in the code itself, like resizing tabs and **calculating row size**...
Pretty much **rooting the grid to the right** and not to the left.

How difficult do you think is it gonna make a feature like that?
I love your grid, if it's not too hard I might make this kind of RTL PR myself!

**Comment by Mulli** [comment]
I would love RTL support.
In addition to the above, column resize is affected by rtl-ing the display.
Is there some support by now?
