### ISSUE TITLE
Grouping rows by a column not working

### ISSUE THREAD

**Issue by oscarthenoob** [adazzle/react-data-grid#892]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
15.6.1

Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[x] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**
Chrome Version 59.0.3071.115
```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[x] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
Not grouping rows by a columns throws an error
Warning: Failed prop type: Invalid prop `name` of type `object` supplied to `GroupedColumnButton`, expected `string`.

**Expected/desired behavior**
group rows by column name.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.
Took source code on this link 
http://adazzle.github.io/react-data-grid/scripts/example21-grouping.js
passed it and tried, no luck so far.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Comment by ibiBgOR** [comment]
Which version of react-data-grid and addons do you use? I got the same problem using version 2.0.2. A look in the code showed, that you only can add strings in the older versions.

**Comment by snigam1** [comment]
The grouping code runs without error. But I can not see the data. It seems react-data-grid is not showing inside <DraggableContainer>. But its is rendering with all the props successfully.  Why i cant see the grid ? pls help

**Comment by nzhtrtlc** [comment]
I have the same issue, did you fixed ? @snigam1

**Comment by giorgim** [comment]
@nzhtrtlc I also seem to have same issue running code like this one: http://adazzle.github.io/react-data-grid/scripts/example21-grouping.js
I can drag column but rows aren't grouped. (also titles of some columns are not shown)
