### ISSUE TITLE
warning after connect 'react-data-grid-addons'

### ISSUE THREAD

**Issue by YuraBaev** [adazzle/react-data-grid#895]
After I just connected 'react-data-grid-addons' to file:
` import { Toolbar } from 'react-data-grid-addons';`
I don't use Toolbar, just connect. 

I get warning in console:

> proxyConsole.js:56 Warning: Invalid argument supplid to oneOfType. Expected an array of check functions, but received undefined at index 0.

**Comment by amanmahajan7** [comment]
Duplicate issue, closing in favor of https://github.com/adazzle/react-data-grid/issues/858
