### ISSUE TITLE
Grid Scroll Issue

### ISSUE THREAD

**Issue by NourEldin275** [adazzle/react-data-grid#899]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ✅ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [  ✅] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [  ✅] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ✅ ] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details
The grid snaps to the left when scrolling anywhere. For example, my case is that I have a SingleSelectFilter rendered. When I try to scroll the items, the grid snaps to the left.

**- The current behavior is:**
```The grid snaps to the left when scrolling anywhere. For example, my case is that I have a SingleSelectFilter rendered. When I try to scroll the items, the grid snaps to the left.```

**The desired behvaior is:**
```When I scroll, the grid doesn't snap and it scrolls only the element in focus```
**- Steps to reproduce the issue:**
```Use a SingleSelectFilter and try to scroll the items of the filter. Or, select the first item, and try to change it more than once.```

It is believed that ```onHeaderScroll``` is fired by the ```SingleSelectFilter``` component for some reason.

**Comment by amanmahajan7** [comment]
@NourEldin275  are you still facing this issue. If yes then can you provide an codesandbox example. Thanks
