### ISSUE TITLE
Upgrade to React V0.13

### ISSUE THREAD

**Issue by malonecj** [adazzle/react-data-grid#9]

**Comment by theTechie** [comment]
Hi - I am getting the following error with React > 0.13. Looks like its because of some core changes in react.

Uncaught TypeError: Can't add property context, object is not extensible

**Comment by bakesteve** [comment]
Yes - there are a number of major changes in v13 vs v12
We've upgraded a fair amount of internal tooling so have a good idea on what the issues are, but don't have a firm date yet when we will update this, but probably in the next few weeks.

And of course, we'd welcome a pull request

**Comment by bakesteve** [comment]
WIP on #2

**Comment by aeng** [comment]
Any progress on this upgrade?

**Comment by acthp** [comment]
I also need this.

**Comment by puruzio** [comment]
+1

**Comment by acthp** [comment]
Has anyone tested the cm-react013-upgrade branch? I've been unable to get npm to install it. It installs only a few of the directories when done like so:

    npm install "git://github.com/adazzle/react-data-grid.git#cm-react013-upgrade"

**Comment by bakesteve** [comment]
We don't commit the dist into Github, so you'll need to run gulp under node_modules/react-data-grid
Well publish a pre release tag for this too so you can just npm that. Will post the details here once that is up

**Comment by joewood** [comment]
Any news on the pre-release npm package?

**Comment by alexvetter** [comment]
+1

**Comment by tonylinyy** [comment]
+1

**Comment by demeyr** [comment]
+1

**Comment by malonecj** [comment]
Hi

https://github.com/adazzle/react-data-grid/pull/2 has now been merged to master supporting React 0.13.3. 

Current npm version of react-data-grid is 0.13.1. Closing this issue
