### ISSUE TITLE
Groupheaders inside the table getting the wrong name

### ISSUE THREAD

**Issue by ibiBgOR** [adazzle/react-data-grid#902]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?
15.3.2

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [x] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is: My groupheaders get the name of the internal keys of the columns.
- What the desired behvaior is: Either I can control what gets choosen or (better) the name of the column will work as groupheader name
- (If Bug) Steps to reproduce the issue:
Create a grid
Columns with different key than name
Group
-> Groupheader should not show the internal key but the name of the column
- (If Feature) The motivation / use case for the feature:
We code in english but get a german ui.

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by ibiBgOR** [comment]
Was able to track down the bug to the following code line: https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid-addons/src/data/RowGrouper.js#L32
The name should not get mapped to the key

**Comment by phkavitha** [comment]
@ibiBgOR, can you not use `rowGroupRenderer`?
