### ISSUE TITLE
Optimizing the packages

### ISSUE THREAD

**Issue by priand** [adazzle/react-data-grid#903]
The build packages are not optimized. For example, the addons module includes 'classnames' 3 times, while this is also included in the core react-grid package.
Can you please release the modules on npm in a /lib directory without the dependencies being included? The idea is to only include the necessary modules or use the "transform-imports" plugins to optimize the final JS file. See, for example, [http://redux-form.com/7.0.3/docs/faq/BundleSize.md/](http://redux-form.com/7.0.3/docs/faq/BundleSize.md/).
Unless you advise to use a different method?

**Comment by malonecj** [comment]
Thanks, we will take a look at that

**Comment by priand** [comment]
Thanks. Having modules would be a great win. I want to group rows, which only requires the data/ package from addons. But right now, I have to drag down the full library, which is overkill. I ended up by making a copy of these files to minimize my app.
