### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by adamdonahue** [adazzle/react-data-grid#904]
I can't find any documentation that canonicalizes the options and behavior of the react-data-grid outside the examples.  The API documentation is of a single function.  Is there a better source?

**Comment by jpdriver** [comment]
hey @adamdonahue -- not right now, but we're hoping to improve the documentation in future.

**Comment by adamdonahue** [comment]
Happy to help.  We're trying to use this but will need a bit more robustness before buying in fully, so if we can contribute we're happy to do so.

**Comment by andrewlorenz** [comment]
DEFINITELY lacking in documentation, and only really possible to work things out by reverse engineering examples and snippets in the issues raised!  Such a shame.
