### ISSUE TITLE
Clear Filters Text Input

### ISSUE THREAD

**Issue by mhsueh2** [adazzle/react-data-grid#905]
### Which version of React JS are you using?
- [x] v15.4.2
### Which React-Data-Grid are you using? 
- [x] V2.0.17
### Which browser are you using?
- [x] Chrome
### I'm submitting a ...
- [x] 🐛 Bug Report
- [x] 💡 Feature Request
---
I have been trying to clear the text inputs via React, but i can't find a way.  The only way it works for me is via HTML elements, where i get all the "text"input elements then reset their values to nothing. 

Is there a more clean way to do this?  I noticed that on the Filters example that the inputs are cleared when you click the "Filter Row" button again, but i can't find the source code for that button. 

Also, how does the onClearFilters() property work? I am not sure how it's even triggered.

BTW, we are not using the "toggle" feature, our filters are always displayed. Is onClearFilter linked to the toggle button? 

Thanks,

Martin

**Comment by mhsueh2** [comment]
Update: 

So I found a hack to clear the filters by hiding/displaying the filter columns bar:
  render() {
    if (this.props.resetFilters) {
      this.grid.setState({ canFilter: false });
      setTimeout(() => this.grid.setState({ canFilter: true }), 1);
    }
    return (
        <ReactDataGrid ref={input => (this.grid = input)} />
   )


It works for now, but if there are better suggestions please comment. Thanks!

**Comment by JanBN** [comment]
I also need this. Is there a way how to clear filters text ?
The hack above causes a blink and a resize of grid which does not work for me

**Comment by shaneardell** [comment]
The documentation mentions a prop on ReactDataGrid for `onClearFilters`, and the example even shows a function that clears the filters in the state that is passed to that prop. However, even the example doesn't have anything that would actually trigger it. The documentation on this could really be fleshed out.
