### ISSUE TITLE
Copy and paste data as in excel ?

### ISSUE THREAD

**Issue by kamarajuPrathi** [adazzle/react-data-grid#906]
- Have you already searched for similar issues? Please help us out and double-check first!
 Yes
- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
I just wanted to check if the copy paste works for multiple rows on in a single column ..?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by kamaldlk** [comment]
have u did this

**Comment by jiangytcn** [comment]
any update about this feature, quite useful

**Comment by ZackKnopp** [comment]
Okay, here it is, cell range copy-paste functionality built on top of react-data-grid.

You can copy from external sources and paste into the grid as well. Anything outside of the current grid is truncated, because my use-case needs this.

https://gist.github.com/ZackKnopp/40fc0691feb03f0fba3e25e7353b73ae

**Comment by Rohit0510** [comment]
Hi ,
I am following your code . But when I am trying to implement the same , getting issue in copy paste the data within the grid.
Any idea how to resolve the issue.

Thanks in advance for your help.
