### ISSUE TITLE
Single row selection 

### ISSUE THREAD

**Issue by vidushijain** [adazzle/react-data-grid#908]
Hi,

I want to restrict user to select only one row instead of multiple row. How can I do that? 
Currently we can selected multiple rows.

Thanks,
Vidushi

**Comment by phkavitha** [comment]
@vidushijain , I would use customRowRenderer and override `onRowsSelectedToggle` function in such a way that it checks for a condition say foo and then selects the row if it's true. I'm not sure whether there is any other optimized solution

**Comment by davgonza** [comment]
just a heads up, this can be accomplished with slight tweaking of the sample code in the docs (https://adazzle.github.io/react-data-grid/docs/examples/row-selection)

```
    onRowsSelected = rows => {
        // take only the value from "rows"... this contains the last selected row from the user
        this.setState({
            selectedIndexes: rows.map(r => r.rowIdx)
        })
    }

```

and then bind to it the usual way
```
            rowSelection={{
                minWidth: 5,
                    maxWidth: 50,
                    resizable: true,
                    showCheckbox: true,
                    enableShiftSelect: false,
                    onRowsSelected: this.onRowsSelected,
                    onRowsDeselected: this.onRowsDeselected,
                    selectBy: {
                        indexes: this.state.selectedIndexes
                    }
            }}
```
