### ISSUE TITLE
Can't navigate grid using keyboard in core-ui react

### ISSUE THREAD

**Issue by neosign** [adazzle/react-data-grid#911]
### Which version of React JS are you using?

✅ Officially supported ✅
- [x ] v15.4.2

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [x] Edge
- [x] Chrome

---

### I'm submitting a ...

- [x ] 🐛 Bug Report

### Issue Details

I'm using core-ui react (1.0.0-alpha.6) integrated with react-data-grid , It can't navigate using arrow keys.
When I click the cell it is supposed to be selected(highlighted) and be able to navigate using arrows key.

Here is mine screen (I can't select (mouse click) the cells and  navigate using arrow keys   )
![download 7](https://user-images.githubusercontent.com/4457571/29780541-669eaae0-8c40-11e7-9ae4-6a6840618100.png)
Expect to see following example screen
![1503934140699](https://user-images.githubusercontent.com/4457571/29780616-9b57d5b8-8c40-11e7-9a13-9a3569e19552.jpg)

**Comment by jpdriver** [comment]
hey @neosign -- this won't be an issue with React Data Grid. please can you open an issue on the [CoreUI repo](https://github.com/mrholek/CoreUI-React) (if you haven't already) thanks! 🙂

**Comment by neosign** [comment]
@jpdriver ok thanks anyway.
