### ISSUE TITLE
Render selective(multiple) grid cells in editing mode on page load to show the validation errors

### ISSUE THREAD

**Issue by gymneganesh** [adazzle/react-data-grid#913]
- Have you already searched for similar issues? Please help us out and double-check first!
Yes
- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [x] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [x] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by gymneganesh** [comment]
I need to render the table grid with selective cells opened under edit mode to show the validation errors for the respective cells.

**Comment by jpdriver** [comment]
@gymneganesh -- my two cents are that you shouldn't need to open cells under edit mode to do this. Showing validation errors (at any stage) should be doable by passing a Custom Formatter in with your Column.

That way you can render different things (e.g. green for valid, red for invalid) without it being tied to edits.
