### ISSUE TITLE
Any way that we can disable lazyload (Keep all rows in DOM all the time)?

### ISSUE THREAD

**Issue by w3nisar** [adazzle/react-data-grid#915]
### Which version of React JS are you using?

✅ Officially supported ✅
- [✅] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [] IE 9 / IE 10 / IE 11
- [ ] Edge
- [✅ ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [✅ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
  Records are loaded and removed from DOM as we scroll

- What the desired behvaior is]
  I would like all the records to be in DOM all the time.

**Comment by lord-xeon** [comment]
This would very quickly slow down the entire browser as many hundreds or even thousands of DOM elements and event listeners are added to the DOM.  What purpose do you need to keep all of the items for?

**Comment by bhunjadi** [comment]
@lord-xeon 
I'm using pagination and only showing up to 20 rows per page. Also, I have defined custom RowRenderer which shows a form below the row when the row is clicked. So when I scroll a bit the component is removed from DOM.

I know I can keep state (form values and the flag if row is expanded) somewhere else, but it would be handy in this case to have an option to keep all elements in DOM.

**Comment by amanmahajan7** [comment]
I think you can override [`overScan`](https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid/src/ReactDataGrid.js#L138) to change the virtual scrolling window.

**Comment by Vedican** [comment]
> I think you can override [`overScan`](https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid/src/ReactDataGrid.js#L138) to change the virtual scrolling window.

How would you suggest doing this?
