### ISSUE TITLE
To Enable Filter by default without button click

### ISSUE THREAD

**Issue by gmarathi-nisum-com** [adazzle/react-data-grid#919]
Do/Can we have any property on component to enable filterable row without click of button?

**Comment by sdarmaputra** [comment]
Yes, we can. I found a simple trick after reading the source code if ReactDataGrid component. Still, use `toolbar` props of ReactDataGrid to achieve this behavior.
Here's how I do this:

First, I create empty toolbar component like this:

```
class EmptyToolbar extends React.Component {
	componentDidMount() {
		this.props.onToggleFilter()
	}
	
	render() {
		return (<div></div>)
	}
}
```
I found that ReactDataGrid component has `onToggleFilter` method to change the state of table header whether to show filter or not. This method injected into element defined in `toolbar` prop of ReactDataGrid component.

So, the last step just to pass this empty toolbar component into `toolbar` prop of ReactDataGrid component, like this:

```
<ReactDataGrid
enableCellSelect={true}
columns={this.state.columns}
onGridRowsUpdated={this.handleGridRowsUpdate}
onGridSort={this.handleGridSort}
rowGetter={this.getRow}
rowsCount={this.handleRowsCount()}				                  		
toolbar={<EmptyToolbar/>} //here's the EmptyToolbar component placed
onAddFilter={this.handleFilterChange}
getValidFilterValues={this.handleGetValidFilterValues}
onClearFilters={this.handleClearFilters} />	
```

The point is to execute `onToggleFilter` method of ReactDataGrid component. By executing this method we change the state of the table header to show filters. Then, if we execute it again, it will hide the filters. Maybe there's a better way to achieve this but here's my solution. Hope this will help :)

**Comment by gmarathi-nisum-com** [comment]
Thank you for the Trick:)

**Comment by daredevil82** [comment]
@sdarmaputra very good solution, and thanks for posting a clear and concise implementation

**Comment by jacek-jaskolski** [comment]
You can simply:
`import React, { Component } from 'react';
import ReactDataGrid from 'react-data-grid';

class Grid extends Component {

  componentDidMount = () => this.refs.grid.onToggleFilter();

  render() {
    return (
        <ReactDataGrid 
          ref="grid" 
        />
    );
  }
}`

**Comment by jacek-jaskolski** [comment]
Simpler solution:

```
import React, { Component } from 'react';
import ReactDataGrid from 'react-data-grid';

class Grid extends Component {

  componentDidMount = () => this.refs.grid.onToggleFilter();

  render() {
    return (
        <ReactDataGrid 
          ref="grid" 
        />
    );
  }
}

**Comment by rpatelcode** [comment]
May I ask you how to use in functional component?

**Comment by tonym3nsa** [comment]
> May I ask you how to use in functional component?

> <ReactDataGrid 
>           ref="grid" 
>         />

I know this comes a little too late but this is one way you can go about it

```
import React, { useEffect, useRef } from "react";
import ReactDataGrid from "react-data-grid";

function Grid() {
  const grid = useRef();
  useEffect(() => {
    grid.current.onToggleFilter();
  }, []);

  return <ReactDataGrid ref={grid} />;
}

export default Grid;

```

**Comment by Randhir01** [comment]
> <ReactDataGrid 
>           ref="grid" 
>         />

I have implemented same way but didn't work for me..Could you please suggest what's wrong on below code..Thanks in advance
i'm facing the issue when integrate the sorting and filter using react data grid and react version 18..Below code is use. Any suggestion what's wrong in the code.

import React, { createContext, createElement, useContext, useMemo, useEffect, useLayoutEffect as useLayoutEffect$1, useRef, useState, useCallback, memo, useId, forwardRef, useImperativeHandle } from 'react';
import { flushSync } from 'react-dom';
import clsx from 'clsx';
import { jsx, jsxs, Fragment } from 'react/jsx-runtime';
import ReactDataGrid from "react-data-grid";
import 'react-data-grid/lib/styles.css';

class EmptyToolbar extends React.Component {
componentDidMount() {
this.props.onToggleFilter()
}

render() {
    return (<div></div>)
}
}

class Title extends React.Component {
constructor(props) {
super(props);
this.state = {
rows: [
{ id: 1, name: 'John', age: 25 },
{ id: 2, name: 'Jane', age: 30 },
{ id: 3, name: 'Doe', age: 40 },
],
columns: [
{
key: 'id',
name: 'ID',
width: 100,
sortable: true,
filterRenderer: () => ,
},
{
key: 'name',
name: 'Name',
width: 200,
sortable: true,
filterRenderer: () => ,
},
{
key: 'age',
name: 'Age',
width: 100,
sortable: true,
filterRenderer: () => ,
},
],
sortColumn: null,
sortDirection: 'NONE',
filters: {},
};
}

    handleSort = (columnKey, direction) => {
        this.setState({ sortColumn: columnKey, sortDirection: direction });
    };

    handleFilterChange = (columnKey, value) => {
        this.setState((prevState) => ({
            filters: { ...prevState.filters, [columnKey]: value },
        }));
    };
    rowGetter = rowIdx => {
        const rows = this.state.rows;
        return rows[rowIdx];
    };
render() {
    //return 
    const { rows, sortColumn, sortDirection, filters } = this.state;

    const FilterInput = ({ columnKey }) => (
        <input
            type="text"
            onChange={(e) => this.handleFilterChange(columnKey, e.target.value)}
            placeholder={`Filter ${columnKey}`}
        />
    );

    const filteredRows = rows.filter((row) =>
        Object.entries(filters).every(([key, value]) =>
            row[key].toString().toLowerCase().includes(value.toLowerCase())
        )
    );
    return (
        <div>
           
            <ReactDataGrid
                enableCellSelect={true}
                columns={this.state.columns}
                
                onGridSort={this.handleSort}
                
                rowsCount={this.state.rows.length}
                toolbar={<EmptyToolbar />} //here's the EmptyToolbar component placed
                onAddFilter={this.handleFilterChange}
                 />
        </div>
    );

}
}

export default Title;
