### ISSUE TITLE
Settings first and last column to locking = true causes rendering issues

### ISSUE THREAD

**Issue by m2jobe** [adazzle/react-data-grid#921]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [x ] v15.5.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x ] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details
Settings first and last column to locking = true causes rendering issues
```
Please include:
- What the current behavior is
Renders but scroll is delayed and as you get to the end you see the rows for that last locked column however the column header isnt working
- What the desired behvaior is
If locking on first and last column set then it scrolls horizontally the columns in between
- (If Bug) Steps to reproduce the issue
Follow frozen columns example: http://adazzle.github.io/react-data-grid/examples.html#/fixed-cols
set last column locking to true
- (If Feature) The motivation / use case for the feature
To allow horizontal scrolling of large number of columns whilst keeping the first and last column fixed
We especially love screenshots / videos of problems, and remember
![image](https://user-images.githubusercontent.com/9561974/30084627-2c0a2fe0-9261-11e7-8e14-d28d1d7836db.png)
![image](https://user-images.githubusercontent.com/9561974/30084647-417235bc-9261-11e7-9211-1411638b1e6e.png)

The Best Issue Is A Pull Request™
```

**Comment by m2jobe** [comment]
Ultimately this is what i am trying to achieve

https://datatables.net/extensions/fixedcolumns/examples/initialisation/left_right_columns.html

**Comment by kozaxinan** [comment]
Example for issue; 
https://jsfiddle.net/k7tfnw1n/427/

Also this configuration triggers #211.

Is it possible to #285 causing this?
