### ISSUE TITLE
Data-grid needs an excel-like Bulk copy feature

### ISSUE THREAD

**Issue by LMS007** [adazzle/react-data-grid#922]
Currently there is no way to bulk copy cells from excel to data-grid. You have to do this one at a time.

Perhaps there should be two modes for copy. 
1. Double click inside a cell + copy (current behavior) 
2. Single click + copy  (should be a multi-cell copy similar to excel)

This makes it easy to transfer spreadsheets from excel to data-grid.

**Comment by kamaldlk** [comment]
@LMS007  have u did this
