### ISSUE TITLE
Inline editing doesn't work in iPhone and iPad

### ISSUE THREAD

**Issue by jper92** [adazzle/react-data-grid#928]
- Have you already searched for similar issues? Yes, there's a similar issue at Issue #256  where it's stated that the bug was fixed but it isn't

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [x] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

- What the current behavior is: When I'm on iPhone and iPad specifically, the inline editing doesn't work. Maybe it's related to the double click event. It works on other mobile devices such as android.
- What the desired behvaior is: The inline editing working on the specified devices
- (If Bug) Steps to reproduce the issue: In my case I tried with iPhone 5s and went to any of the examples in data grid page, and it doesn't matter how many times I tap, the inline editing and the device keyboard won't show.

**Comment by todvenn** [comment]
I wonder whether this lib actually aims to support mobile at all, I wonder if the use of tables on mobile devices is so rare / undesirable, that the creators didn't aim to support them...

**Comment by psyycker** [comment]
Still happening

**Comment by suuf** [comment]
Cell selection events don't seem to be available anymore and inline editing on mobile devices in general doesn't work 😞
