### ISSUE TITLE
How to make default view of tree view structure as expanded?

### ISSUE THREAD

**Issue by praveenvasya** [adazzle/react-data-grid#929]
- Have you already searched for similar issues? Please help us out and double-check first!
Yes
- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

I am able to display data in tree view parent child structure. I have to click triangle from parent row to see details of sub road. Which is as per the behavior.
Need to display parent - children data structure by default in expanded form.

Please include:
- What the current behavior is
Data displayed in collapsed form. Once we click on the parent column, subrows get expanded
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature
Need to implement new behavior in which tree view ge displayed in expanded form by default.
Please help.

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by praveenvasya** [comment]
Please help me on this feature. Need to display tree view in expanded mode by default.

**Comment by praveenvasya** [comment]
Hi ,
To implement this feature, I have created one similar method like oncellexpand, and set expanded as true for each row. To do this I have call that newly created method from componentWillMount method and pass this.state.rows in that method.

I am able to display only last row expanded by default. All other rows are in collapsed form only. During debug, what I observed that while setting expanded value true for each rows, every row is being overriden by proceeding rows and ultimately only last row value is being set as true.

Can anybody please help me to implement the same ( display rows in expanded form by default) for other rows as well?!!

**Comment by praveenvasya** [comment]
Please help....I can't put my code here because of security policy from client.

**Comment by praveenvasya** [comment]
@jpdriver could you please help or suggest me with below:
1. Need to display tree view structure by default in expanded mode?
2. Is it possible to have tree view with two parent - children set of structure? I mean in a row I can have two triangle in two column and their children?

**Comment by diogofcunha** [comment]
Hi @praveenvasya.

To get all the rows expanded by default, if you follow [this example](http://adazzle.github.io/react-data-grid/scripts/example25-tree-view.js) all you need to do is set the initial state to contain a collection of all the rowIds and use that in getSubRowDetails to figure out what's expanded or not.

The second point is not supported and would make the ui too confusing, we won't be supporting that out of the box

**Comment by meghna0593** [comment]
Hi @diogofcunha , 

Could you please elaborate on how to implement this with a sample code. I tried implementing this by setting 'expanded' to true and removed if/else if condition. I have to click the arrow once to expand it. Doesn't collapse after that. 
I want the child rows to expand by default.

onCellExpand = (args) => {
   console.log("inside onCellExpand");
   console.log(args);
    let rows = this.state.rows_1.slice(0);
    let rowKey = args.rowData.name;
    let rowIndex = rows.indexOf(args.rowData);
    let subRows = args.expandArgs.children;
    // let subRows = args.expandArgs.children;
    console.log(rows,rowKey,rowIndex);
    let expanded = Object.assign({}, this.state.expanded);
    console.log(expanded[rowKey]);
    console.log("inside if"); 
    expanded[rowKey] = true;
    this.updateSubRowDetails(subRows, args.rowData.treeDepth);
    rows.splice(rowIndex + 1, 0, ...subRows);
    console.log(rows);
    this.setState({ expanded: expanded, rows_1: rows });
};

**Comment by nimesha95** [comment]
sorry comment on a closed issue
@praveenvasya did you figure out a way to do this? 
I also want the functionality you described.
