### ISSUE TITLE
Accessing selected rows in react 0.13

### ISSUE THREAD

**Issue by nmalancea** [adazzle/react-data-grid#93]
Can anyone help me figure out how to **access the selected rows**? I need to take the selected rows and add them to another table then assign those records to a parent. 

I looked in the tests and saw they're accessed via the component's state (`component.state.selectedRows`).

How would I do that from the context where I render my `ReactDataGrid` (my `render` function)? I thought I could use a `ref` but `ref` is not working because of `cloneWithProps` being used in ReactDataGrid, which drops `refs`. Any plans to update `cloneWithProps` calls to the new `cloneElement` any time soon? https://facebook.github.io/react/blog/2015/03/03/react-v0.13-rc2.html

**Comment by chicagogrrl** [comment]
+1

**Comment by bakesteve** [comment]
for `cloneElement` that will be done as part of the prep work for #63 

for selectedRows, internally we are using that, so we have something like this:
```
React.createClass({
  render: () => {
    return (<ReactDataGrid ref="grid" {...props}/>)
  },
  doStuff: () => {
    let  selected = this.refs.grid.state.selectedRows;
  }
})
```

My gut feel is this is down to react changes on cloneWithPros vs cloneElement?

we have talked internally about moving this to be accessed more explicitly via a onRowSelectedProp - will update here if we go that way

**Comment by malonecj** [comment]
This example shows how you can access selected rows in React 14. If needed we can port this back to the 0.13x branch

http://adazzle.github.io/react-data-grid/examples.html#/multi-row-select
