### ISSUE TITLE
Scroll position can not be decided while using margin at row and it causes to vibrate scroll bar 

### ISSUE THREAD

**Issue by kozaxinan** [adazzle/react-data-grid#932]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [x] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [x] v15.5.x
- [x] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is

If we set a margin to row, at some point of scroll, scroll bar vibrate to up and down. Data grid can not decide to draw top row and continuously add and remove top one.

- What the desired behavior is

Scroll bar should stay stable

- (If Bug) Steps to reproduce the issue

https://jsfiddle.net/rn06qa41/
Open on Chrome and scroll to bottom slowly. When 32. element near top, scroll bug start moving

- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
http://gph.is/2f5EpYs

The Best Issue Is A Pull Request™
```

**Comment by serdaryesilmurat** [comment]
We encountered the same problem in our project too. Will be very appreciated if this issue is addressed and resolved really soon.
