### ISSUE TITLE
Looking for a grid example like below

### ISSUE THREAD

**Issue by jkathir** [adazzle/react-data-grid#934]
I'm looking for a grid example like below with search, pagination and export option

https://pyntax.net/wp-content/uploads/2015/07/Export-HTML-Table-Data-to-Excel-CSV-PDF.png

**Comment by martinnov92** [comment]
Hello, you can use search in current grid, but I think pagination is not possible with react-data-grid. I implemented to mine grid Export to Excel thanks to library called https://github.com/SheetJS/js-xlsx.

**Comment by diogofcunha** [comment]
Hi guys.

As @martinnov92 said,  you can use search in current grid.

All the rest shouldn't be the grid responsibility.

To export to excel use another library that can transform the grid content into excel values.

For pagination you can create your own component that keeps track of the page and changes the rows rendered by react-data-grid depending on the page number.
