### ISSUE TITLE
server side filter/sort/paging?

### ISSUE THREAD

**Issue by mstruensee** [adazzle/react-data-grid#935]
any plans for server side searching, sorting, paging and filtering?

**Comment by ray-matos-mpf** [comment]
really, such a basic feature and its not baked in.

**Comment by fh-jashmore** [comment]
Are there any examples out there using this?

**Comment by jstray** [comment]
I implemented pagination successfully like this https://github.com/adazzle/react-data-grid/issues/152#issuecomment-336747776

**Comment by luishdez** [comment]
Spend hours and then you find out this basic function is not implemented…

**Comment by Se0ng11** [comment]
not see any pagination being develop, any chance to add in future release?

**Comment by luishdez** [comment]
I did move to https://react-table.js.org/#/story/readme it works pretty well
