### ISSUE TITLE
Custom cell editor doesn't work well

### ISSUE THREAD

**Issue by sergeyzwezdin** [adazzle/react-data-grid#936]
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [x] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

---

### Issue Details

We're trying to implement custom cell editor for data-grid with [react-color](https://github.com/casesandberg/react-color). I noticed that popup from this color is hidden under grid's boundary. Spend some time on problem investigation but still have no luck.

After that I checked [this example](http://adazzle.github.io/react-data-grid/examples.html#/built-in-editors) and noticed it has similar problem. If you click on cell for "Priority" column editor would be hidden inside grid:

![image](https://user-images.githubusercontent.com/800755/30426833-f0019968-9966-11e7-8f8d-9c81754d7cc2.png)

Are there any ways to fix the issue?

**Comment by jsobus-neurosys** [comment]
I strongly advice using https://github.com/souporserious/react-tether for that issue :)
