### ISSUE TITLE
Adding Animation to Column Inserted

### ISSUE THREAD

**Issue by audiolion** [adazzle/react-data-grid#939]
### Which version of React JS are you using?

✅ Officially supported ✅
- [x] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

---

### Issue Details

```
- (If Feature) The motivation / use case for the feature

When a new column is inserted I would like to use something like react-transition-group to add a css transition to the column to help with the UI/UX. If you insert a column in a sheet that has a few hundred columns it can be hard to tell which column just got inserted. An animation effect could help the user visually identify where the change took place.
The Best Issue Is A Pull Request™
```

Is there a way to do this currently? Nothing I can see allows me to pass in a `<CSSTransitionGroup />` component with children that include an entire column. If the way it is designed doesn't allow a column perhaps I can just do it on the Header Cell of the new column that is created, but still unsure of how this could work given the current API and operation of the library.

**Comment by diogofcunha** [comment]
Hi @audiolion.

You should be able to achieve the header part by passing a `headerRenderer` to your newly added column.

You can also add animations to the cells by specifying a `rowRenderer` and inside that rowRenderer specify a `cellRenderer`
