### ISSUE TITLE
How to get filtered rows in adazzle/react-data-grid

### ISSUE THREAD

**Issue by Sharu2806** [adazzle/react-data-grid#945]
Hi,

I want result of filtered rows.
E.g. If I add filter to 1 column and select 24 value to filter, then how should I get rows which will only contain value 24. 

I printed output of rowsGetter and got filtered rows, but I am not able to understand how do I can get that rows.

Please anyone help me ??

**Comment by chumak84** [comment]
Probably you should handle filters on your own.
The grid doesn't implement filtering.
At least it says on documentation
http://adazzle.github.io/react-data-grid/examples.html#/filterable-grid
'While ReactDataGrid doesn't not provide the ability to filter directly, it does provide hooks that allow you to provide your own filter function'
So you filters rows on your own. Then update state/props with new rowsCount after that grid will get rows by function that you provided aka rowGetter
