### ISSUE TITLE
onGridRowsUpdated firing even when no change is made

### ISSUE THREAD

**Issue by jdh-invicara** [adazzle/react-data-grid#950]
### Which version of React JS are you using?
⚠️ Not officially supported, expect warnings ⚠️
- [x] v15.6.x

---

### Which browser are you using?

✅ Officially supported ✅
- [x] Chrome

---

### I'm submitting a ...

- [x] 🐛 Bug Report

---

### Issue Details

When I click into a cell to edit, make no changes and then click out of the cell the onGridRowsUpdated event fires - even though nothing has changed.

If this is expected behavior then is there a way to grab the initial state of the row before editing so that I can filter out non-change-events?

**Comment by SteveDowsett** [comment]
Im noticing the same issue, in onGridRowsUpdated im updating the local state of the table and then firing off an api call to save the data. But if there are no changes made after entering the editor, i wouldnt expect onGridRowsUpdated to fire. Is there a way to surpress this if there are no changes?
