### ISSUE TITLE
Bottom scroll dissapears when no results found (filter feature)

### ISSUE THREAD

**Issue by ejnu** [adazzle/react-data-grid#958]
### Which version of React JS are you using?

✅ Officially supported ✅
- [x] v15.4.x

### Which browser are you using?

✅ Officially supported ✅
- [x] IE 9 / IE 10 / IE 11
- [x] Edge
- [x] Chrome

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

---

### Issue Details

In most of cases we can't use filter when there is no filtered data in table because there is no horizontal scroll and rest of columns are not visible (see the picture)

![scroll](https://user-images.githubusercontent.com/26431406/31123911-76952d16-a842-11e7-9dc2-dc769df4e73e.jpg)

**Comment by amanmahajan7** [comment]
Duplicate issue, closing in favor of https://github.com/adazzle/react-data-grid/issues/873
