### ISSUE TITLE
Horizontal scrolling results in header rows not matching body rows

### ISSUE THREAD

**Issue by namibian15** [adazzle/react-data-grid#959]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ x] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x ] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

**Current Behavior**
Column definitions are as follows:
`        //Grid Columns
        let columns = [
            {
                key: 'areaId',
                name: ' ',
                width: 0,
                locked: true,
                hidden: true
            },
            {
                key: "areaColor",
                name: ' ',
                width: 35,
                editable: false,
                locked: true,
                formatter: ColorBlockFormatter,
                cellClass: "text-center"
            },
            {
                key: "areaName",
                name: this.state.i18n.editArea.nameCol,
                sortable: true,
                editable: false,
                width: 150,
                locked: true
            },
            {
                key: "fixed",
                name: this.state.i18n.editArea.fixedCol,
                width: 55,
                editable: true,
                editor: CheckMarkEditor,
                formatter:CheckMarkFormatter,
                cellClass: "text-center"
            },
            {
                key: "weight",
                name: this.state.i18n.editArea.weightCol,
                editable: true,
                width: 65,
                cellClass: "text-right"
            }
        ];
`
With 3 frozen columns, the first which is also hidden, when I scroll to the left, the header rows are not aligned with the "body" rows.
![react-data-grid](https://user-images.githubusercontent.com/14940661/31188792-1caf4486-a904-11e7-8993-6a8ce455c35f.png)

**Desired Behavior**
When scrolling, frozen columns should always align with "body columns"
```

**Comment by namibian15** [comment]
I should add that I try to render the table inside a bootstrap "well" class inside a bootstrap modal dialog

**Comment by eduardosmatheus** [comment]
Has anyone got some workaround to solve it? I'm having the same problem here after updating to 5.0.2.

**Comment by jeffal** [comment]
I have noticed this issue within the following demo:
https://adazzle.github.io/react-data-grid/#/examples/immutable-data

Working with the library locally, when I have greater then 12 or so columns the issue begins to become very noticeable.
