### ISSUE TITLE
Resize column doesnt work on firefox when also draggable

### ISSUE THREAD

**Issue by Nevosis** [adazzle/react-data-grid#963]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ x] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ x] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

When the user tries to resize a column, it will drag it instead. The bug can be seen on the example page (https://adazzle.github.io/react-data-grid/examples.html#/draggable-header).

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by shoshannamb** [comment]
Any progress on this? We're also trying to use drag resize and drag to reorder and it works great in IE and Chrome, but this functionality is totally unusable in Firefox.

**Comment by Gtosta96** [comment]
up
