### ISSUE TITLE
setState(...) warning when quickling mounting/unmounting

### ISSUE THREAD

**Issue by chuntley** [adazzle/react-data-grid#964]
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [x] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request
---

### Issue Details

When quickly mounting, unmounting, then mounting another react-data-grid, the follow error is shown in the console:

```
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Viewport component.
```

I tracked down the lines of code that are causing this in `/src/ViewportScrollMixin.js`:

```
  resetScrollStateAfterDelay() {
    if (this.resetScrollStateTimeoutId) {
      clearTimeout(this.resetScrollStateTimeoutId);
    }

    this.resetScrollStateTimeoutId = setTimeout(
      this.resetScrollStateAfterDelayCallback,
      500
    );
  },

  resetScrollStateAfterDelayCallback() {
    this.resetScrollStateTimeoutId = null;
    this.setState({
      isScrolling: false
    });
  },
```

The problem is with the setTimeout. If you unmount then mount another react-data-grid within 500ms, the error displays because it fires off the delayed callback which tries to setState on an unmounted component.

I couldn't figure out the exact reason why this delay is in there. Could it be removed? Or what steps could we take to refactor it?

Thanks!

**Comment by amanmahajan7** [comment]
Duplicate issue, closing in favor #764
