### ISSUE TITLE
Grid is not horizontally scrollable if empty.

### ISSUE THREAD

**Issue by terolepisto** [adazzle/react-data-grid#966]
Grid is not horizontally scrollable if empty. This causes weirdness if user uses filters that don't match any of the data. If grid is very wide and scrolled, the filters are positioned off-screen and can't be manipulated anymore.

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [x] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
Filters can be placed offscreen if the grid is wide and grid data returns empty results (when used filters). Filters become un-usable when they're rendered offscreen and grid can't be scrolled horizontally.

- What the desired behvaior is
Grid should be scrolled horizontally even if the grid is empty.

- (If Bug) Steps to reproduce the issue
Make wide screen (that has fixed size columns), if grid doesn't have any data, it is not 
```

**Comment by amanmahajan7** [comment]
Duplicate issue, closing in favor of https://github.com/adazzle/react-data-grid/issues/873
