### ISSUE TITLE
Add classNames in columns 

### ISSUE THREAD

**Issue by markmus** [adazzle/react-data-grid#97]
I dont know if this is possible right now but according to documentation there is still no way how I could add classNames or styles by columns.

Currently what I could do is to create a custom formatter, however it will be much more easy if we could add `classNames` upon declaration.

In example:

```
//Columns definition
var columns = [
{
  key: 'id',
  name: 'ID',
  locked : true,
  classNames: 'center'
},
{
  key: 'task',
  name: 'Title',
  width: 200
}
```

**Comment by malonecj** [comment]
Hi, You should be able to use  the `cellClass` property of a column to set the class. I will add this to the documentation

**Comment by alistairjcbrown** [comment]
Is the `cellClass` also set on the header cell? Or is there another prop which can be used for this? I'm hoping to align right the cell text in columns with numeric data, but would also want to include the heading text.

**Comment by alistairjcbrown** [comment]
Added PR #170 to add the `cellClass` value to the class of the header cells as well

**Comment by txm** [comment]
Could cellClass default to the key?
