### ISSUE TITLE
Lock Rows

### ISSUE THREAD

**Issue by woodgit** [adazzle/react-data-grid#974]
I want to create a table that has locked cols on the left, but also lock the three last rows. Is there a way to achieve this by adding aproperty to the row data?

**Comment by woodgit** [comment]
Closing without any comment?

**Comment by woodgit** [comment]
@bulentjotform I decided to go on to another grid implementation for the next version of my project.

**Comment by nitinkarthy** [comment]
@woodgit ... Could you please let me know which other grid implementation you chose which can freeze/lock both columns and rows?
