### ISSUE TITLE
React Data Grid PropType is null error () with React version 16.0.0

### ISSUE THREAD

**Issue by kwkau** [adazzle/react-data-grid#982]
Having an issue with setting up a simple react-data-grid example i saw  [@addazle]( http://adazzle.github.io/react-data-grid/examples.html#/basic)
i copied and pasted the code below from the source page
const ReactDataGrid = require('react-data-grid');
const React = require('react');

class Example extends React.Component {
  constructor(props, context) {
    super(props, context);
    this.createRows();
    this._columns = [
      { key: 'id', name: 'ID' },
      { key: 'title', name: 'Title' },
      { key: 'count', name: 'Count' } ];

    this.state = null;
  }

  createRows = () => {
    let rows = [];
    for (let i = 1; i < 1000; i++) {
      rows.push({
        id: i,
        title: 'Title ' + i,
        count: i * 1000
      });
    }

    this._rows = rows;
  };

  rowGetter = (i) => {
    return this._rows[i];
  };

  render() {
    return  (
      <ReactDataGrid
        columns={this._columns}
        rowGetter={this.rowGetter.bind(this)}
        rowsCount={this._rows.length}
        minHeight={500} />);
  }
}

but i get this error when i run the react application
Uncaught TypeError: Cannot read property 'number' of undefined

![react-data-grid_error](https://user-images.githubusercontent.com/1039665/31828778-33505156-b5b3-11e7-990a-2788ea5b7494.PNG)

i tried to debug the issue with console.log(_react) and console.log(_react2)
the console.log revealed that the PropType property does not exist on the two objects
_react or _react2
am using the latest Chrome browser.
hope i can get the issue fixed as asap.
thanks

**Comment by pankajpatel** [comment]
#954

**Comment by kwkau** [comment]
patiently waiting @pankajpatel

**Comment by pankajpatel** [comment]
@kwkau me as well, development is on pause.

**Comment by jpdriver** [comment]
hey @kwkau -- we're hoping to support React 16 in a future release, but for now (as mentioned in the Issue Template) we are not officially supporting it.

we'll merge the PropTypes migration PR mentioned above in when we can. Until then if you really really need to use React 16 immediately, you can use the temporary workaround detailed [here](https://github.com/adazzle/react-data-grid/issues/744#issuecomment-333890937)

**Comment by kwkau** [comment]
thanks, you just saved my ass big time
