### ISSUE TITLE
Copy and Paste values into other cells

### ISSUE THREAD

**Issue by kamaldlk** [adazzle/react-data-grid#984]
Copy and Paste values into other cells not working If I use command c  getting type in cell letter C

**Comment by kwkau** [comment]
Hey @jpdriver  i posted an issue about an error i was getting, #982, but i was informed that development had been paused; i really need help with this issue urgently if you could find a way help me out it would be much appreciated.
thanks in advance

**Comment by jpdriver** [comment]
let's keep thing on-topic here; we should only be using this Issue to discuss Copy - Pasting values using Cmd + C. I'll reply to your other thread separately.

**Comment by kwkau** [comment]
okay, sorry for going of topic

**Comment by kamaldlk** [comment]
@jpdriver  @kwkau  thanks for your valuable reply. there is any possibility to do copy paste now

**Comment by jitenderchand1** [comment]
@jpdriver  @kamaldlk Did you find a way to copy cell value?
