### ISSUE TITLE
react-data-grid-addons Missing type definitions for Typescript

### ISSUE THREAD

**Issue by kwkau** [adazzle/react-data-grid#986]
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [ ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by omgaz** [comment]
You can use DefinitelyTyped

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-data-grid

npm i --save-dev @types/react-data-grid

**Comment by weitjong** [comment]
Not sure if I did something wrong here or there is a version mismatch between the types and the actual component, but I just could not successfully import the addons (I tried Toolbar) and use it in my page without any compile time or runtime error. Using Typescript 2.6.2, react-data-grid(-addons) 3.0.3, @types/react-data-grid 2.0.7.
