### ISSUE TITLE
2.0.64 has removed prop-types which are **required** for react v16 compatibility

### ISSUE THREAD

**Issue by Michael-Tajmajer-Emrsn** [adazzle/react-data-grid#991]
I diffed the 2.0.64 changes and was extremely disappointed that the references to prop-types, which are *needed* for react v16 compatibility were removed.

Why are you moving the project farther away from v16?

**From: https://reactjs.org/blog/2017/09/26/react-v16.0.html**

The deprecations introduced in 15.x have been removed from the core package. React.createClass is now available as create-react-class, **React.PropTypes as prop-types**, React.DOM as react-dom-factories, react-addons-test-utils as react-dom/test-utils, and shallow renderer as react-test-renderer/shallow. See 15.5.0 and 15.6.0 blog posts for instructions on migrating code and automated codemods.

**Comment by amanmahajan7** [comment]
This does not seem correct. PR (https://github.com/adazzle/react-data-grid/pull/954) migrated `React.PropTypes` to separate `prop-types` package and was merged yesterday.

**Comment by Michael-Tajmajer-Emrsn** [comment]
You are correct!  
I misread the diff -- sorry for the confusion.
