### ISSUE TITLE
Resizing a column can make other column values disappear

### ISSUE THREAD

**Issue by asifm01** [adazzle/react-data-grid#992]
Please see details below of a possible bug when resizing columns in the data grid using the online example.  Is this something that can be looked into please?

### Which version of React JS are you using?
⚠️ Not officially supported, expect warnings ⚠️
- [✅] v15.5.4

### Which browser are you using?
✅ Officially supported ✅
- [✅ ] IE 9 / IE 10 / IE 11
- [ ✅] Edge
- [ ✅] Chrome

### I'm submitting a ...
- [✅ ] 🐛 Bug Report

### Issue Details
- What the current behavior is
When resizing a column past the grid boundary, the cell values of the columns that appear to the right of it are wiped.  The values do not come back even when reverting the column back to it's original (or near enough)!) size.

- What the desired behvaior is
Resizing a column should not affect the values displayed in other columns.

- (If Bug) Steps to reproduce the issue
1. Go to http://adazzle.github.io/react-data-grid/examples.html#/resizable-cols.
2. Not that all cells are populated.
3. Grab the column sizer of the Title column and drag it past the right-hand side boundary of the grid.
4. Move the horizontal grid scrollbar all the way to the right.
5. The cell values of the last 3 columns are no longer visible.

Note: If we now revert the column size, the values still don't appear (unless we move the H slider which seems to force a refresh).

Please refer to the attached video to see the issue.
![reactdatagridcolumnresizeissues](https://user-images.githubusercontent.com/33087929/31994082-5aaa1968-b977-11e7-932f-26d608a7111e.gif)

**Comment by amanmahajan7** [comment]
Related issues
#1135 
#1087
