### ISSUE TITLE
Copy and Paste select row or columns  like excel there is any possible 

### ISSUE THREAD

**Issue by kamaldlk** [adazzle/react-data-grid#999]
@jpdriver Copy and Paste select row or columns like excel there is any possibility.

**Comment by jpdriver** [comment]
hey @kamaldlk -- the UI / UX isn't 💯exactly the same, but we do have similar functions. What is it you're actually trying to do?

**Comment by kamaldlk** [comment]
1. I have row A. and row B.
In rowA contains cell11, cell12,cell13 and rowB have cell21, cell22, cell23, I want to replace in a single shot 3cells. like google sheet 
2. undo also if there looks fine.

**Comment by kamaldlk** [comment]
@jpdriver  please send me your wat's app no : 9944929666

**Comment by kamaldlk** [comment]
@jpdriver  urgent like this possible in this lib copy paste :(
https://nadbm.github.io/react-datasheet/

**Comment by jpdriver** [comment]
It's possible to copy whole Rows (and I think it wouldn't be too hard to implement the same for columns) -- but at the moment copying value ranges is not supported by this grid.

**Comment by kamaldlk** [comment]
Thanks JP Bro :), I'll start to do that

**Comment by kamaldlk** [comment]
@jpdriver  is there any development going regarding this

**Comment by ZackKnopp** [comment]
Okay, here it is, cell range copy-paste functionality built on top of react-data-grid.

You can copy from external sources and paste into the grid as well. Anything outside of the current grid is truncated, because my use-case needs this.

https://gist.github.com/ZackKnopp/40fc0691feb03f0fba3e25e7353b73ae
